/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Stacks.DeligneMumfordCriterionFinal

/-!
# The local slicing hypothesis of the converse Deligne--Mumford criterion, corrected

`Stacks.DeligneMumfordCriterionFinal` isolates the scheme-level proposition `LocalSlicing`: for
`t s : R ⟶ U` with `t` smooth surjective and `(t, s) : R ⟶ U ⨯ U` unramified there is a family
`g i : W i ⟶ U` with all slices `pullback.snd (g i) s ≫ t : s⁻¹(W i) ⟶ U` etale and with the
`g i` *jointly surjective onto `U`*.

**That statement is false**, so nothing can be deduced from it (the theorems of
`Stacks.DeligneMumfordCriterionFinal` that assumed it were vacuous and have been removed).  This
file isolates the error, proves the reduction from the corrected hypothesis
`SaturatedLocalSlicing` -- `AlgebraicStack.exists_etaleChart_of_unramified_diagonal_of_saturated`
and `AlgebraicStack.toDeligneMumfordStack_of_saturated`, the form in which the converse criterion
is available in the library, `SaturatedLocalSlicing` itself remaining unproved -- and shows that
the corrected hypothesis is not merely sufficient but *equivalent* to what the stack-level
conclusion needs.

## Why `LocalSlicing` is false

`etale_slice_id_iff` and `unramified_prod_lift_id` combine into
`exists_etale_comp_family_of_localSlicing`: taking `R = U` and `s = 𝟙 U` (the graph
`prod.lift t (𝟙 U)` is an immersion, hence unramified, for *every* `t`), `LocalSlicing` implies
that for every scheme `U`, every smooth surjective `t : U ⟶ U` and every point `u : U` there are
`g : W ⟶ U` and `w : W` with `g w = u` and `g ≫ t` etale
(`exists_etale_comp_of_localSlicing`).  This fails already for

`U = Spec ℤ[x₁, x₂, x₃, …]` and `t = Spec.map σ` where `σ xᵢ = xᵢ₊₁`:

`σ` identifies `A := ℤ[x₁, x₂, …]` with `ℤ[x₂, x₃, …]`, over which `A` is a polynomial ring in
one variable, so `t` is smooth of relative dimension `1`; and `t` is surjective because a prime
`p` of `ℤ[x₂, …]` extends to the prime `p · A`.  Let `u` be the generic point of the integral
scheme `U`.  If `g w = u` and `g ≫ t` is etale then the residue field extension
`κ ((g ≫ t) w) ⟶ κ w` is finite, while it factors as
`Frac ℤ[x₂, …] ⟶ Frac A = κ u ⟶ κ w`, and `Frac A = (Frac ℤ[x₂, …]) (x₁)` is transcendental
over `Frac ℤ[x₂, …]`; contradiction.

The mistake is the covering condition, not the slicing itself: the classical construction
(Stacks 06N3) cuts `W ⊆ U` out of an affine open by `d = dim t` functions *vanishing at `u`*,
which exist only where the cotangent space of `U` is generated by differentials of functions
vanishing at `u`.  What the criterion actually needs is that the *slices* cover `U`, i.e. that
the sliced chart is surjective over the stack; this is strictly weaker, because a slice through
one point of a `(t, s)`-orbit covers the whole orbit.

## Main results

* `exists_slice_family_prod_of_localSlicing`: the same failure for a genuine *self-overlap*,
  `(prod.fst, prod.snd) : U ⨯ U ⇉ U` for `U` smooth surjective over `Spec ℤ`, so restricting
  `LocalSlicing` to self-overlaps does not repair it.
* `exists_etale_over_terminal_of_localSlicing`: the sharpest formal consequence -- `LocalSlicing`
  would make every scheme smooth and surjective over `Spec ℤ` be covered by the images of schemes
  *etale over* `Spec ℤ`, which `𝔸¹_ℤ` is not.
* `not_localSlicing_of_forall_not_etale`: `¬ LocalSlicing` from the one concrete geometric fact
  above, namely that some smooth surjective self-map has a point with no etale slice through it.
* `SaturatedEtaleSliceExists t s`: the corrected slicing statement — the family of slice
  morphisms `pullback.snd (g i) s ≫ t` is jointly surjective (instead of the family of `g i`).
* `StackChart.selfOverlapUnit`, `selfOverlapInv`, `selfOverlapComp` (with their `_fst`/`_snd`
  identities): the unit, inverse and composition of the groupoid `R = U ×_X U` as *scheme*
  morphisms (`U ⟶ R`, `R ⟶ R`, `R ×_{s, U, t} R ⟶ R`), all from the universal property of the
  presentation.  These are the pieces the transport step of Stacks 06N3 needs and which were
  previously available only as stack-level 2-cell data.
* `saturatedEtaleSliceExists_of_orbit`: the covering condition in the form "the slices meet every
  orbit of `(t, s)`"; `StackChart.selfOverlapUnit` (the scheme-level diagonal `U ⟶ U ×_X U`, with
  `selfOverlapUnit_fst`, `selfOverlapUnit_snd`) and
  `StackChart.saturatedEtaleSliceExists_selfOverlap_of_etaleSliceExists` then show that for a
  self-overlap the corrected condition really is implied by the old one.
* `saturatedEtaleSliceExists_of_pointwise`: the corrected statement is local on `U` -- one etale
  slice per point of `U`, not through that point, suffices.
* `saturatedEtaleSliceExists_of_etaleSliceExists`: in the presence of a unit section
  (`e ≫ t = 𝟙`, `e ≫ s = 𝟙`, available for the self-overlap `R = U ×_X U`) the old condition
  implies the new one, so nothing is lost.
* `surjective_slice_sigmaDesc`, `exists_surjective_etale_slice_of_saturated_family` and
  `saturatedEtaleSliceExists_iff`: the corrected condition is *equivalent* to the existence of a
  single etale slice `∐ W ⟶ U` whose slice morphism is surjective.
* `StackChart.restrict_isEtaleSurjective_iff_surjective_slice`: the sliced chart
  `SiteChart.restrict A g` is an etale surjective atlas **iff** the slice
  `pullback.snd g pR.snd ≫ pR.fst` is etale and surjective.  So the corrected covering
  condition is exactly the right one, and `Surjective g` (the hypothesis of
  `StackChart.restrict_isEtaleSurjective_of_slice`) is sufficient but not necessary.
* `SaturatedLocalSlicing` and
  `AlgebraicStack.exists_etaleChart_of_unramified_diagonal_of_saturated`,
  `AlgebraicStack.toDeligneMumfordStack_of_saturated`: the converse Deligne--Mumford criterion
  from the corrected hypothesis, and the form in which the criterion is available in the library.
  `SaturatedLocalSlicing` itself is still unproved (see below).

## What is still missing

`SaturatedLocalSlicing` itself, i.e. Stacks 06N3.  With the covering condition corrected, the
remaining work is what `Stacks.EtaleSliceLocal` starts: for each point `u` of `U` in a set of
points meeting every orbit, cut an affine open `V ∋ u` by `d` functions vanishing at `u` whose
differentials generate `Ω_{R/U,t}` at the unit `e u` — possible by unramifiedness of `(t, s)`,
cf. `EtaleSliceLocal.exists_subfamily_notMem_smul_mem_span` — shrink `W` to the open locus where
the differentials still generate along the unit section, and then spread the generation from
`e u` to the whole of `s⁻¹(W)` using the groupoid composition of `R = U ×_X U`.  The last step is
why `Etale (pullback.snd g s ≫ t)`, a condition on *all* of `s⁻¹(W)`, does not follow from
`EtaleSliceLocal.etale_slice_specMap` alone (which needs `R` itself to be shrunk).  The groupoid
morphisms it needs are supplied here as scheme morphisms (`StackChart.selfOverlapUnit`,
`selfOverlapInv`, `selfOverlapComp`); what is still missing is the cotangent functoriality along
them and the groupoid laws.
-/

open CategoryTheory CategoryTheory.Limits
open _root_.AlgebraicGeometry
open GromovWitten.AlgebraicGeometry.Sites

namespace GromovWitten.AlgebraicGeometry

universe u

/-! ## `EtaleSliceExists` asks for a slice through every point -/

/-- For `s = 𝟙 U` the slice attached to `g : W ⟶ U` is `g ≫ t`, because `pullback g (𝟙 U) ≅ W`
compatibly with the two projections. -/
theorem etale_slice_id_iff {U W : Scheme.{u}} (t : U ⟶ U) (g : W ⟶ U) :
    Etale (pullback.snd g (𝟙 U) ≫ t) ↔ Etale (g ≫ t) := by
  have _hres : MorphismProperty.RespectsIso (@Etale : MorphismProperty Scheme.{u}) :=
    MorphismProperty.IsStableUnderBaseChange.respectsIso
  have hiso : IsIso (pullback.fst g (𝟙 U)) :=
    (IsPullback.of_hasPullback g (𝟙 U)).isIso_fst_of_isIso
  have he : pullback.fst g (𝟙 U) ≫ g ≫ t = pullback.snd g (𝟙 U) ≫ t := by
    rw [← Category.assoc, pullback.condition, Category.comp_id]
  rw [← he]
  exact MorphismProperty.cancel_left_of_respectsIso (@Etale : MorphismProperty Scheme.{u}) _ _

/-- **The graph of a self-map of a scheme is unramified.**  `prod.lift t (𝟙 U)` is a section of
`prod.snd`, hence an immersion (`IsImmersion.of_comp`), hence unramified.  Consequently the
hypothesis `Unramified (prod.lift t s)` of `LocalSlicing` is satisfied by `s = 𝟙 U` for every
`t : U ⟶ U` whatsoever. -/
theorem unramified_prod_lift_id {U : Scheme.{u}} (t : U ⟶ U) :
    Unramified (prod.lift t (𝟙 U)) := by
  have h : IsImmersion (prod.lift t (𝟙 U) ≫ prod.snd) := by
    rw [prod.lift_snd]
    infer_instance
  have h2 : IsImmersion (prod.lift t (𝟙 U)) := IsImmersion.of_comp _ prod.snd
  infer_instance

/-- **`LocalSlicing` implies that every smooth surjective self-map of a scheme becomes etale
after a base change whose image is everything.**  Apply `LocalSlicing` to `R = U`, `s = 𝟙 U`:
the unramifiedness hypothesis is `unramified_prod_lift_id`, and the slices are the `g i ≫ t` by
`etale_slice_id_iff`. -/
theorem exists_etale_comp_family_of_localSlicing (hLS : LocalSlicing.{u}) {U : Scheme.{u}}
    (t : U ⟶ U) (hsm : _root_.AlgebraicGeometry.Smooth t)
    (hsurj : _root_.AlgebraicGeometry.Surjective t) :
    ∃ (σ : Type u) (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U),
      (∀ i, Etale (g i ≫ t)) ∧ ∀ u : U, ∃ (i : σ) (w : W i), (g i) w = u := by
  obtain ⟨σ, W, g, hEt, hcov⟩ := hLS U U t (𝟙 U) hsm hsurj (unramified_prod_lift_id t)
  exact ⟨σ, W, g, fun i ↦ (etale_slice_id_iff t (g i)).1 (hEt i), hcov⟩

/-- **The pointwise form of `exists_etale_comp_family_of_localSlicing`**, which is what fails for
`U = Spec ℤ[x₁, x₂, …]`, `t = Spec.map (xᵢ ↦ xᵢ₊₁)` and `u` the generic point: the residue field
extension of an etale morphism is finite, but `κ u = Frac ℤ[x₁, x₂, …]` is transcendental over
the residue field `Frac ℤ[x₂, x₃, …]` of `t u`.  Hence `LocalSlicing` is false. -/
theorem exists_etale_comp_of_localSlicing (hLS : LocalSlicing.{u}) {U : Scheme.{u}} (t : U ⟶ U)
    (hsm : _root_.AlgebraicGeometry.Smooth t) (hsurj : _root_.AlgebraicGeometry.Surjective t)
    (u : U) : ∃ (W : Scheme.{u}) (g : W ⟶ U) (w : W), g w = u ∧ Etale (g ≫ t) := by
  obtain ⟨σ, W, g, hEt, hcov⟩ := exists_etale_comp_family_of_localSlicing hLS t hsm hsurj
  obtain ⟨i, w, hw⟩ := hcov u
  exact ⟨W i, g i, w, hw, hEt i⟩

/-- **A refutation scheme for `LocalSlicing`.**  `LocalSlicing` fails as soon as some scheme `U`
carries a smooth surjective self-map `t` and a point `u` admitting no morphism `g : W ⟶ U` through
`u` with `g ≫ t` etale.  For `U = Spec ℤ[x₁, x₂, …]`, `t = Spec.map (xᵢ ↦ xᵢ₊₁)` and `u` the
generic point the hypothesis `hno` holds, because `Etale (g ≫ t)` forces the residue field
extension `κ ((g ≫ t) w) ⟶ κ w` to be finite while `κ u = Frac ℤ[x₁, x₂, …]` is transcendental
over `κ (t u) = Frac ℤ[x₂, x₃, …]`; that concrete verification is not formalised here. -/
theorem not_localSlicing_of_forall_not_etale {U : Scheme.{u}} (t : U ⟶ U)
    (hsm : _root_.AlgebraicGeometry.Smooth t) (hsurj : _root_.AlgebraicGeometry.Surjective t)
    (u : U) (hno : ∀ (W : Scheme.{u}) (g : W ⟶ U) (w : W), g w = u → ¬ Etale (g ≫ t)) :
    ¬ LocalSlicing.{u} := by
  intro hLS
  obtain ⟨W, g, w, hw, hEt⟩ := exists_etale_comp_of_localSlicing hLS t hsm hsurj u
  exact hno W g w hw hEt

/-- The two projections `U ⨯ U ⇉ U` form a pullback square over the terminal scheme. -/
theorem isPullback_prod_fst_snd (U : Scheme.{u}) :
    IsPullback (prod.fst : U ⨯ U ⟶ U) (prod.snd : U ⨯ U ⟶ U) (terminal.from U)
      (terminal.from U) :=
  IsPullback.of_iso_pullback ⟨terminal.hom_ext _ _⟩ (prodIsoPullback U U) (by simp) (by simp)

/-- **`LocalSlicing` applies to a genuine self-overlap.**  For `U` smooth and surjective over
`Spec ℤ = ⊤_ Scheme` the pair `(prod.fst, prod.snd) : U ⨯ U ⇉ U` is the self-overlap of the chart
`U ⟶ Spec ℤ` of the terminal stack: `prod.fst` is smooth and surjective by base change, and
`prod.lift prod.fst prod.snd = 𝟙` is unramified.  So `LocalSlicing` yields a family of slices
`g i : W i ⟶ U` whose *images cover `U`* and whose slice morphisms
`pullback.snd (g i) prod.snd ≫ prod.fst` are etale.

This is where the strong covering condition of `EtaleSliceExists` really breaks down, and it
breaks down for a self-overlap, so restricting `LocalSlicing` to self-overlaps does not repair
it: the slice morphism above is the base change of `terminal.from (W i)` along the fppf cover
`terminal.from U`, so etaleness of the slice forces `W i` to be etale over `Spec ℤ`.  For
`U = 𝔸¹_ℤ = Spec ℤ[x]` the points of `U` in the image of a scheme etale over `Spec ℤ` have
residue field finite over a finite field or over `ℚ`, so the generic point of `𝔸¹_ℤ`
(residue field `ℚ(x)`) is in no such image, and no such family can cover `U`. -/
theorem exists_slice_family_prod_of_localSlicing (hLS : LocalSlicing.{u}) (U : Scheme.{u})
    (hsm : _root_.AlgebraicGeometry.Smooth (terminal.from U))
    (hsurj : _root_.AlgebraicGeometry.Surjective (terminal.from U)) :
    ∃ (σ : Type u) (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U),
      (∀ i, Etale (pullback.snd (g i) (prod.snd : U ⨯ U ⟶ U) ≫ prod.fst)) ∧
        ∀ u : U, ∃ (i : σ) (w : W i), (g i) w = u := by
  refine hLS (U ⨯ U) U prod.fst prod.snd
    (MorphismProperty.of_isPullback (isPullback_prod_fst_snd U).flip hsm)
    (MorphismProperty.of_isPullback (isPullback_prod_fst_snd U).flip hsurj) ?_
  rw [prod.lift_fst_snd]
  infer_instance

/-- **The slice of the self-overlap `(prod.fst, prod.snd)` along `g : W ⟶ U` is the base change
of `W ⟶ ⊤_ Scheme` along `U ⟶ ⊤_ Scheme`**, i.e. `s⁻¹(W) = U ⨯ W` with slice morphism the first
projection.  Pasting the defining square of `pullback g prod.snd` onto
`isPullback_prod_fst_snd`. -/
theorem isPullback_slice_prod {U W : Scheme.{u}} (g : W ⟶ U) :
    IsPullback (pullback.fst g (prod.snd : U ⨯ U ⟶ U))
      (pullback.snd g (prod.snd : U ⨯ U ⟶ U) ≫ prod.fst) (terminal.from W)
      (terminal.from U) := by
  have h := (IsPullback.of_hasPullback g (prod.snd : U ⨯ U ⟶ U)).paste_vert
    (isPullback_prod_fst_snd U).flip
  rwa [terminal.hom_ext (g ≫ terminal.from U) (terminal.from W)] at h

/-- **A scheme carrying an etale slice of the self-overlap of `U ⟶ ⊤_ Scheme` is etale over
`⊤_ Scheme`.**  The slice morphism is the base change of `terminal.from W` along the fppf cover
`terminal.from U` (`isPullback_slice_prod`), and `Etale` descends along fppf covers. -/
theorem etale_terminalFrom_of_etale_slice {U W : Scheme.{u}} (g : W ⟶ U)
    (hcov : FppfCover.{u} (terminal.from U))
    (h : Etale (pullback.snd g (prod.snd : U ⨯ U ⟶ U) ≫ prod.fst)) :
    Etale (terminal.from W) :=
  MorphismProperty.of_isPullback_of_descendsAlong (isPullback_slice_prod g).flip hcov h

/-- **The sharpest formal consequence of `LocalSlicing`, and the one that refutes it:** every
scheme `U` that is smooth and surjective over `Spec ℤ = ⊤_ Scheme` would be covered by the images
of a family of morphisms `g i : W i ⟶ U` with every `W i` *etale over* `Spec ℤ`.

Taking `U = 𝔸¹_ℤ = Spec ℤ[x]` (smooth and surjective over `Spec ℤ`) this is false: a scheme `W`
etale over `Spec ℤ` has all residue fields finite over `ℚ` or over a finite field, so no point of
`W` can map to the generic point of `𝔸¹_ℤ`, whose residue field is `ℚ(x)`.  The family
`(prod.fst, prod.snd)` used here is the self-overlap of the chart `U ⟶ Spec ℤ` of the terminal
stack, so `LocalSlicing` cannot be repaired by restricting it to self-overlaps of charts. -/
theorem exists_etale_over_terminal_of_localSlicing (hLS : LocalSlicing.{u}) (U : Scheme.{u})
    (hsm : _root_.AlgebraicGeometry.Smooth (terminal.from U))
    (hsurj : _root_.AlgebraicGeometry.Surjective (terminal.from U)) :
    ∃ (σ : Type u) (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U),
      (∀ i, Etale (terminal.from (W i))) ∧ ∀ u : U, ∃ (i : σ) (w : W i), (g i) w = u := by
  obtain ⟨σ, W, g, hEt, hcovU⟩ := exists_slice_family_prod_of_localSlicing hLS U hsm hsurj
  exact ⟨σ, W, g, fun i ↦ etale_terminalFrom_of_etale_slice (g i)
    (smoothCover_le_fppfCover _ ⟨hsurj, hsm⟩) (hEt i), hcovU⟩

/-! ## The corrected slicing statement -/

/-- **The corrected local slicing statement.**  A family of slices `g i : W i ⟶ U` whose slice
morphisms `pullback.snd (g i) s ≫ t : s⁻¹(W i) ⟶ U` are etale and *jointly surjective*.  This is
`EtaleSliceExists` with the covering condition moved from the `g i` to the slices; in the
groupoid case it says that the `g i` meet every `(t, s)`-orbit, which is what surjectivity of
the sliced chart over the stack amounts to
(`StackChart.restrict_isEtaleSurjective_iff_surjective_slice`). -/
def SaturatedEtaleSliceExists {R U : Scheme.{u}} (t s : R ⟶ U) : Prop :=
  ∃ (σ : Type u) (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U),
    (∀ i, Etale (pullback.snd (g i) s ≫ t)) ∧
      ∀ u : U, ∃ (i : σ) (p : (pullback (g i) s : Scheme.{u})), (pullback.snd (g i) s ≫ t) p = u

/-- **The corrected slicing statement is local on `U` in the weakest sense:** it suffices to
produce, for each point `u` of `U` separately, one etale slice whose slice morphism hits `u`.  The
slices need not be related to each other, and need not pass through `u` -- which is exactly the
freedom that `EtaleSliceExists` lacks.  This is the shape in which Stacks 06N3 produces slices. -/
theorem saturatedEtaleSliceExists_of_pointwise {R U : Scheme.{u}} (t s : R ⟶ U)
    (h : ∀ u : U, ∃ (W : Scheme.{u}) (g : W ⟶ U), Etale (pullback.snd g s ≫ t) ∧
      ∃ p : (pullback g s : Scheme.{u}), (pullback.snd g s ≫ t) p = u) :
    SaturatedEtaleSliceExists t s := by
  choose W g hEt hp using h
  exact ⟨↑U, W, g, fun u ↦ hEt u, fun u ↦ ⟨u, hp u⟩⟩

/-- **`SaturatedEtaleSliceExists` is weaker than `EtaleSliceExists`** whenever `(t, s)` has a
unit section, as the self-overlap `R = U ×_X U` of a chart does: a point `w` of `W i` gives the
point `(w, e (g i w))` of the slice `s⁻¹(W i)`, which lies over `g i w`. -/
theorem saturatedEtaleSliceExists_of_etaleSliceExists {R U : Scheme.{u}} {t s : R ⟶ U}
    (e : U ⟶ R) (het : e ≫ t = 𝟙 U) (hes : e ≫ s = 𝟙 U) (h : EtaleSliceExists t s) :
    SaturatedEtaleSliceExists t s := by
  obtain ⟨σ, W, g, hEt, hcov⟩ := h
  refine ⟨σ, W, g, hEt, fun u ↦ ?_⟩
  obtain ⟨i, w, hw⟩ := hcov u
  have hcond : 𝟙 (W i) ≫ g i = (g i ≫ e) ≫ s := by
    rw [Category.id_comp, Category.assoc, hes, Category.comp_id]
  refine ⟨i, pullback.lift (𝟙 (W i)) (g i ≫ e) hcond w, ?_⟩
  have hcomp : pullback.lift (𝟙 (W i)) (g i ≫ e) hcond ≫ pullback.snd (g i) s ≫ t = g i := by
    rw [← Category.assoc, pullback.lift_snd, Category.assoc, het, Category.comp_id]
  rw [← Scheme.Hom.comp_apply, hcomp]
  exact hw

/-- **The covering condition of `SaturatedEtaleSliceExists` in orbit form:** it is enough that
every point of `U` is joined by an arrow of `R` to a point in the image of one of the slices.
(The underlying set of `pullback (g i) s` surjects onto the set-theoretic fibre product, by
`AlgebraicGeometry.Scheme.Pullback.exists_preimage_pullback`.) -/
theorem saturatedEtaleSliceExists_of_orbit {R U : Scheme.{u}} (t s : R ⟶ U) {σ : Type u}
    (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U) (hEt : ∀ i, Etale (pullback.snd (g i) s ≫ t))
    (hcov : ∀ u : U, ∃ (i : σ) (w : W i) (r : R), g i w = s r ∧ t r = u) :
    SaturatedEtaleSliceExists t s := by
  refine ⟨σ, W, g, hEt, fun u ↦ ?_⟩
  obtain ⟨i, w, r, hwr, hru⟩ := hcov u
  obtain ⟨q, -, hq⟩ := Scheme.Pullback.exists_preimage_pullback w r hwr
  exact ⟨i, q, by rw [Scheme.Hom.comp_apply, hq, hru]⟩

/-- **Nonvacuity of `SaturatedEtaleSliceExists`:** if `t` is etale and surjective then the
trivial slice `g = 𝟙 U` works, its slice morphism being isomorphic to `t`.  (In particular the
counterexample to `LocalSlicing` is no counterexample here.) -/
theorem saturatedEtaleSliceExists_of_etale {R U : Scheme.{u}} (t s : R ⟶ U) (ht : Etale t)
    (hts : _root_.AlgebraicGeometry.Surjective t) : SaturatedEtaleSliceExists t s := by
  have _hres : MorphismProperty.RespectsIso (@Etale : MorphismProperty Scheme.{u}) :=
    MorphismProperty.IsStableUnderBaseChange.respectsIso
  have hiso : IsIso (pullback.snd (𝟙 U) s) :=
    (IsPullback.of_hasPullback (𝟙 U) s).isIso_snd_of_isIso
  have he : inv (pullback.snd (𝟙 U) s) ≫ pullback.snd (𝟙 U) s ≫ t = t := by
    rw [← Category.assoc, IsIso.inv_hom_id, Category.id_comp]
  refine ⟨PUnit.{u + 1}, fun _ ↦ U, fun _ ↦ 𝟙 U, fun _ ↦ ?_, fun u ↦ ⟨PUnit.unit, ?_⟩⟩
  · exact (MorphismProperty.cancel_left_of_respectsIso
      (@Etale : MorphismProperty Scheme.{u}) (pullback.snd (𝟙 U) s) t).2 ht
  · obtain ⟨r, hr⟩ := hts.surj u
    refine ⟨inv (pullback.snd (𝟙 U) s) r, ?_⟩
    rw [← Scheme.Hom.comp_apply, he]
    exact hr

/-- **A family of etale slices with jointly surjective slice morphisms glues to a single
surjective etale slice.**  This is the surjectivity half; the etaleness half is
`AlgebraicGeometry.etale_slice_sigmaDesc`. -/
theorem surjective_slice_sigmaDesc {R U : Scheme.{u}} (t s : R ⟶ U) {σ : Type u}
    (W : σ → Scheme.{u}) (g : ∀ i, W i ⟶ U)
    (hcov : ∀ u : U, ∃ (i : σ) (p : (pullback (g i) s : Scheme.{u})),
      (pullback.snd (g i) s ≫ t) p = u) :
    _root_.AlgebraicGeometry.Surjective (pullback.snd (Sigma.desc g) s ≫ t) := by
  refine ⟨fun u ↦ ?_⟩
  obtain ⟨i, p, hp⟩ := hcov u
  have hc : (pullback.fst (g i) s ≫ Sigma.ι W i) ≫ Sigma.desc g = pullback.snd (g i) s ≫ s := by
    rw [Category.assoc, Sigma.ι_desc]
    exact pullback.condition
  have hmap : pullback.lift (pullback.fst (g i) s ≫ Sigma.ι W i) (pullback.snd (g i) s) hc ≫
      pullback.snd (Sigma.desc g) s ≫ t = pullback.snd (g i) s ≫ t := by
    rw [← Category.assoc, pullback.lift_snd]
  exact ⟨_, by rw [← Scheme.Hom.comp_apply, hmap]; exact hp⟩

/-- **The corrected input of the converse Deligne--Mumford criterion produces a surjective etale
slice**, in the shape consumed by
`StackChart.restrict_isEtaleSurjective_of_surjective_slice`. -/
theorem exists_surjective_etale_slice_of_saturated_family {R U : Scheme.{u}} (t s : R ⟶ U)
    (h : SaturatedEtaleSliceExists t s) :
    ∃ (W : Scheme.{u}) (g : W ⟶ U), Etale (pullback.snd g s ≫ t) ∧
      _root_.AlgebraicGeometry.Surjective (pullback.snd g s ≫ t) := by
  obtain ⟨σ, W, g, hEt, hcov⟩ := h
  exact ⟨∐ W, Sigma.desc g, _root_.AlgebraicGeometry.etale_slice_sigmaDesc t s W g hEt,
    surjective_slice_sigmaDesc t s W g hcov⟩

/-- **The corrected slicing statement is exactly the existence of one surjective etale slice.**
Forwards this is the gluing `exists_surjective_etale_slice_of_saturated_family`; backwards a single
slice is a one-element family. -/
theorem saturatedEtaleSliceExists_iff {R U : Scheme.{u}} (t s : R ⟶ U) :
    SaturatedEtaleSliceExists t s ↔ ∃ (W : Scheme.{u}) (g : W ⟶ U),
      Etale (pullback.snd g s ≫ t) ∧
        _root_.AlgebraicGeometry.Surjective (pullback.snd g s ≫ t) := by
  refine ⟨exists_surjective_etale_slice_of_saturated_family t s, ?_⟩
  rintro ⟨W, g, hEt, hsurj⟩
  refine ⟨PUnit.{u + 1}, fun _ ↦ W, fun _ ↦ g, fun _ ↦ hEt, fun x ↦ ?_⟩
  obtain ⟨q, hq⟩ := hsurj.surj x
  exact ⟨PUnit.unit, q, hq⟩

/-! ## The sliced chart -/

namespace StackChart

variable {X : FppfStack.{u}} {A : StackChart X}

variable (A) in
/-- **The unit section of the self-overlap groupoid, at the scheme level:** the diagonal
`U ⟶ R = U ×_X U` of a presentation `pR` of the self-overlap, obtained from the universal
property of `pR` applied to `(𝟙 U, 𝟙 U)` and the canonical 2-cell `stackPullbackIdIso`. -/
noncomputable def selfOverlapUnit
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.scheme ⟶ pR.space :=
  pR.lift (𝟙 A.scheme) (𝟙 A.scheme)
    (stackPullbackIdIso X A.scheme (A.obj A.scheme (𝟙 A.scheme)))

variable (A) in
/-- The first projection of the unit section is the identity. -/
theorem selfOverlapUnit_fst
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapUnit pR ≫ pR.fst = 𝟙 A.scheme :=
  pR.lift_fst _ _ _

variable (A) in
/-- The second projection of the unit section is the identity. -/
theorem selfOverlapUnit_snd
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapUnit pR ≫ pR.snd = 𝟙 A.scheme :=
  pR.lift_snd _ _ _

variable (A) in
/-- **The inverse of the self-overlap groupoid, at the scheme level:** the morphism `R ⟶ R`
exchanging the two legs, from the universal property of `pR` and the swap 2-cell
`StackChart.PullbackPresentation.selfSwapComparison`. -/
noncomputable def selfOverlapInv
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    pR.space ⟶ pR.space :=
  pR.lift pR.snd pR.fst pR.selfSwapComparison

variable (A) in
/-- The inverse exchanges target and source. -/
theorem selfOverlapInv_fst
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapInv pR ≫ pR.fst = pR.snd :=
  pR.lift_fst _ _ _

variable (A) in
/-- The inverse exchanges source and target. -/
theorem selfOverlapInv_snd
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapInv pR ≫ pR.snd = pR.fst :=
  pR.lift_snd _ _ _

variable (A) in
/-- **The composition of the self-overlap groupoid, at the scheme level.**  A morphism
`R ×_{s, U, t} R ⟶ R` on the scheme of composable pairs: a pair `(r₁, r₂)` with `s r₁ = t r₂` is
sent to an arrow with target `t r₁` (`selfOverlapComp_fst`) and source `s r₂`
(`selfOverlapComp_snd`).  The required 2-cell is `pR.comparison` induced along the two
projections (`StackChart.inducedComparison`), spliced with the canonical identification of a
chart object with a pullback of the tautological object
(`StackChart.identityObjectPullbackComparison`) across the pullback condition.  Together with
`selfOverlapUnit` and `StackChart.PullbackPresentation.selfSwap` (the inverse) this is the
groupoid structure of `R = U ×_X U` as *scheme* morphisms, whose absence blocks the transport
step of Stacks 06N3. -/
noncomputable def selfOverlapComp
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    pullback pR.snd pR.fst ⟶ pR.space :=
  pR.lift (pullback.fst pR.snd pR.fst ≫ pR.fst) (pullback.snd pR.snd pR.fst ≫ pR.snd)
    ((A.inducedComparison pR.fst pR.snd pR.comparison (pullback.snd pR.snd pR.fst)).trans
      (((A.identityObjectPullbackComparison (pullback.snd pR.snd pR.fst ≫ pR.fst)).symm).trans
        ((A.objIsoOfEq pullback.condition.symm).trans
          (A.inducedComparison pR.fst pR.snd pR.comparison (pullback.fst pR.snd pR.fst)))))

variable (A) in
/-- **The target of a composite is the target of the first arrow.** -/
theorem selfOverlapComp_fst
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapComp pR ≫ pR.fst = pullback.fst pR.snd pR.fst ≫ pR.fst :=
  pR.lift_fst _ _ _

variable (A) in
/-- **The source of a composite is the source of the second arrow.** -/
theorem selfOverlapComp_snd
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    A.selfOverlapComp pR ≫ pR.snd = pullback.snd pR.snd pR.fst ≫ pR.snd :=
  pR.lift_snd _ _ _

variable (A) in
/-- **For the self-overlap of a chart the corrected slicing condition is implied by the old one**,
via the unit section: so the hypothesis `SaturatedLocalSlicing` of
`AlgebraicStack.exists_etaleChart_of_unramified_diagonal_of_saturated` is weaker than the false
`LocalSlicing` of `Stacks.DeligneMumfordCriterionFinal`. -/
theorem saturatedEtaleSliceExists_selfOverlap_of_etaleSliceExists
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)))
    (h : EtaleSliceExists pR.fst pR.snd) : SaturatedEtaleSliceExists pR.fst pR.snd :=
  saturatedEtaleSliceExists_of_etaleSliceExists (A.selfOverlapUnit pR)
    (A.selfOverlapUnit_fst pR) (A.selfOverlapUnit_snd pR) h

/-- **A slice whose slice morphism is etale and surjective gives an etale surjective chart.**
This is `StackChart.restrict_isEtaleSurjective_of_slice` with the hypothesis `Surjective g`
weakened to surjectivity of the slice morphism `s⁻¹(W) ⟶ U`, which is all that proof used. -/
theorem restrict_isEtaleSurjective_of_surjective_slice (hA : A.IsSmoothSurjective)
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)))
    {W : Scheme.{u}} (g : W ⟶ A.scheme)
    (hslice : Etale (pullback.snd g pR.snd ≫ pR.fst))
    (hsurj : _root_.AlgebraicGeometry.Surjective (pullback.snd g pR.snd ≫ pR.fst)) :
    (SiteChart.restrict A g).IsEtaleSurjective := by
  have _inst : MorphismProperty.IsStableUnderBaseChange
      ((@Etale ⊓ @_root_.AlgebraicGeometry.Surjective) : MorphismProperty Scheme.{u}) :=
    MorphismProperty.IsStableUnderBaseChange.inf
  have _inst2 : MorphismProperty.DescendsAlong
      ((@Etale ⊓ @_root_.AlgebraicGeometry.Surjective) : MorphismProperty Scheme.{u})
      FppfCover.{u} := MorphismProperty.DescendsAlong.inf
  exact restrict_hasRepresentableProperty_of_slice A
    (@Etale ⊓ @_root_.AlgebraicGeometry.Surjective) hA pR g ⟨hslice, hsurj⟩

/-- **Etale surjectivity of a sliced chart is equivalent to etaleness and surjectivity of the
slice morphism.**  In particular the covering condition of `EtaleSliceExists` (surjectivity of
`g` itself) is sufficient but *not necessary*: what the criterion needs is surjectivity of
`s⁻¹(W) ⟶ U`. -/
theorem restrict_isEtaleSurjective_iff_surjective_slice (hA : A.IsSmoothSurjective)
    (pR : A.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)))
    {W : Scheme.{u}} (g : W ⟶ A.scheme) :
    (SiteChart.restrict A g).IsEtaleSurjective ↔
      Etale (pullback.snd g pR.snd ≫ pR.fst) ∧
        _root_.AlgebraicGeometry.Surjective (pullback.snd g pR.snd ≫ pR.fst) :=
  ⟨fun h ↦ slice_of_restrict_hasRepresentableProperty A
      (@Etale ⊓ @_root_.AlgebraicGeometry.Surjective) pR g h,
    fun h ↦ restrict_isEtaleSurjective_of_surjective_slice hA pR g h.1 h.2⟩

end StackChart

/-! ## The converse Deligne--Mumford criterion from the corrected hypothesis -/

/-- **The corrected local slicing proposition** (Stacks 06N3, scheme level): for `t` smooth
surjective with `(t, s)` unramified there is a family of etale slices whose slice morphisms are
jointly surjective.  Unlike `LocalSlicing` this is not refuted by
`exists_etale_comp_of_localSlicing`: for `s = 𝟙 U` and `t` etale surjective it holds with the
single slice `g = 𝟙 U` (`saturatedEtaleSliceExists_of_etale`). -/
def SaturatedLocalSlicing : Prop :=
  ∀ (R U : Scheme.{u}) (t s : R ⟶ U), _root_.AlgebraicGeometry.Smooth t →
    _root_.AlgebraicGeometry.Surjective t → Unramified (prod.lift t s) →
      SaturatedEtaleSliceExists t s

/-- **The converse Deligne--Mumford criterion, from the corrected local slicing statement.**
An algebraic stack with a smooth surjective chart `A` and representably unramified diagonal has
an etale surjective chart, provided `SaturatedLocalSlicing` holds -- which is still unproved.
The false `LocalSlicing` of `Stacks.DeligneMumfordCriterionFinal` would not do. -/
theorem AlgebraicStack.exists_etaleChart_of_unramified_diagonal_of_saturated
    (hLS : SaturatedLocalSlicing.{u}) (X : AlgebraicStack.{u}) (A : StackChart X.toStack)
    (hA : A.IsSmoothSurjective) (hdiag : (stackDiagonal X.toStack).Unramified) :
    ∃ B : StackChart X.toStack, B.IsEtaleSurjective := by
  obtain ⟨pR⟩ := hA.1 A.scheme (A.obj A.scheme (𝟙 A.scheme))
  have hrep : A.IsRepresentable := A.isRepresentable_of_hasRepresentableProperty _ hA
  have ht := hA.2 A.scheme (A.obj A.scheme (𝟙 A.scheme)) pR
  obtain ⟨V, g, hEt, hsurj⟩ := exists_surjective_etale_slice_of_saturated_family pR.fst pR.snd
    (hLS pR.space A.scheme pR.fst pR.snd ht.1 ht.2
      (A.selfOverlapPair_unramified_of_diagonal hrep pR hdiag))
  exact ⟨SiteChart.restrict A g,
    StackChart.restrict_isEtaleSurjective_of_surjective_slice hA pR g hEt hsurj⟩

/-- **The Deligne--Mumford stack attached to an algebraic stack with unramified diagonal**,
modulo `SaturatedLocalSlicing`. -/
def AlgebraicStack.toDeligneMumfordStack_of_saturated (hLS : SaturatedLocalSlicing.{u})
    (X : AlgebraicStack.{u}) (A : StackChart X.toStack) (hA : A.IsSmoothSurjective)
    (hdiag : (stackDiagonal X.toStack).Unramified) : DeligneMumfordStack.{u} where
  toAlgebraicStack := X
  etaleAtlas := X.exists_etaleChart_of_unramified_diagonal_of_saturated hLS A hA hdiag

end GromovWitten.AlgebraicGeometry
