/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
import Mathlib.AlgebraicGeometry.Morphisms.Etale
import Mathlib.RingTheory.Etale.Locus
import Mathlib.RingTheory.Smooth.Basic
import Mathlib.RingTheory.Smooth.StandardSmoothCotangent
import Mathlib.RingTheory.TensorProduct.Free

/-!
# Étale slices: the ring-theoretic content of Stacks 06N3

Let `X` be an algebraic stack with unramified diagonal and let `u : U → X` be a smooth
surjective chart.  The Deligne–Mumford criterion (Stacks Project tag 06N3) produces an étale
chart by *slicing*: one cuts `U` down by `d` functions whose differentials form a basis of the
relative cotangent module, where `d` is the relative dimension.  This file formalises the
commutative-algebra input of that argument, for a tower of rings `A → B → C` (think
`A = 𝒪_X`, `B = 𝒪_U`, `C = 𝒪_W` for the slice `W ⊆ U`).

## Main results

* `surjective_mapBaseChange_of_formallyUnramified`: if `C` is formally unramified over `B`
  then `C ⊗[B] Ω[B⁄A] → Ω[C⁄A]` is surjective.  This is the "`Ω_{R/U × U} = 0` forces
  `s^*Ω_{U} → Ω_{R/U}` to be surjective" step of 06N3, in its ring-theoretic form.
* `subsingleton_kaehlerDifferential_of_span_eq_top`, `formallyUnramified_of_span_eq_top`: if the
  differentials `d bᵢ` generate `C ⊗[B] Ω[B⁄A]` and each `bᵢ` dies in `C`, then `Ω[C⁄A] = 0`,
  i.e. the slice is unramified over the base.
* `formallyEtale_of_basis`, `etale_of_basis`: the **Jacobian criterion for a slice**.  If `B`
  is formally smooth over `A`, `C` is a quotient of `B` by the ideal generated by
  `b : ι → B`, and the differentials `1 ⊗ d bᵢ` form a *basis* of `C ⊗[B] Ω[B⁄A]`, then `C`
  is formally étale over `A` (and étale once it is of finite presentation).  The proof splits
  the cotangent complex of the extension `B ↠ C` using
  `Algebra.Extension.formallySmooth_iff_split_injection`.
* `exists_basis_of_span_eq_top`: the dimension count of 06N3, namely that `n` generators of a
  free module of rank `n` form a basis (Orzech's theorem).
* `etale_of_span_eq_top`, `etale_of_span_eq_top_of_isStandardSmooth`: the local form of the
  slicing construction.  If `B` is standard smooth over `A` of relative dimension `n`,
  `b : Fin n → B` generates the kernel of `B ↠ C`, and the `1 ⊗ d bᵢ` merely *generate*
  `C ⊗[B] Ω[B⁄A]`, then `C` is étale over `A`.
* `isEtale_specMap_of_span_eq_top`: the same statement for the induced morphism of affine
  schemes `Spec C ⟶ Spec A`.

What is *not* done here is the globalisation: producing, for a smooth chart `u : U → X` of an
algebraic stack with unramified diagonal, the functions `f₁, …, f_d` on an open subscheme of `U`
whose differentials generate the relative cotangent module of `R = U ×_X U` over `U`, and
gluing the resulting étale slices into an étale atlas.  Note that the openness of the étale
locus needed for the shrinking step is available in Mathlib as `Algebra.isOpen_etaleLocus`
and `Algebra.exists_etale_of_isEtaleAt`.
-/

universe u v w

open TensorProduct KaehlerDifferential

namespace GromovWitten.EtaleSlice

variable {A : Type u} {B : Type v} {C : Type w} [CommRing A] [CommRing B] [CommRing C]
  [Algebra A B] [Algebra A C] [Algebra B C] [IsScalarTower A B C]

/-- If `C` is formally unramified over `B`, the base-changed map `C ⊗[B] Ω[B⁄A] → Ω[C⁄A]` is
surjective: in the relative cotangent sequence `C ⊗[B] Ω[B⁄A] → Ω[C⁄A] → Ω[C⁄B] → 0` the
right-hand term vanishes.  Geometrically this is the step of Stacks 06N3 which uses that the
map `R = U ×_X U → U × U` is unramified. -/
theorem surjective_mapBaseChange_of_formallyUnramified [Algebra.FormallyUnramified B C] :
    Function.Surjective (KaehlerDifferential.mapBaseChange A B C) := by
  rw [← LinearMap.range_eq_top, KaehlerDifferential.range_mapBaseChange, ← top_le_iff]
  exact fun x _ ↦ LinearMap.mem_ker.mpr (Subsingleton.elim _ _)

/-- **Slicing kills the differentials.** If the elements `b i` of `B` all become zero in `C`,
their differentials generate `C ⊗[B] Ω[B⁄A]`, and `C ⊗[B] Ω[B⁄A] → Ω[C⁄A]` is surjective, then
`Ω[C⁄A] = 0`. -/
theorem subsingleton_kaehlerDifferential_of_span_eq_top {ι : Type*} (b : ι → B)
    (hsurj : Function.Surjective (KaehlerDifferential.mapBaseChange A B C))
    (hspan : Submodule.span C
      (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) = ⊤)
    (hzero : ∀ i, algebraMap B C (b i) = 0) :
    Subsingleton Ω[C⁄A] := by
  have h1 : Submodule.map (KaehlerDifferential.mapBaseChange A B C) ⊤ = ⊤ := by
    rw [Submodule.map_top, LinearMap.range_eq_top]
    exact hsurj
  have htop : (⊤ : Submodule C Ω[C⁄A]) = ⊥ := by
    rw [← h1, ← hspan, Submodule.map_span, Submodule.span_eq_bot]
    rintro x ⟨y, ⟨i, rfl⟩, rfl⟩
    simp [hzero i]
  have hz : ∀ z : Ω[C⁄A], z = 0 := fun z ↦ by
    have hmem : z ∈ (⊥ : Submodule C Ω[C⁄A]) := by rw [← htop]; exact Submodule.mem_top
    simpa using hmem
  exact ⟨fun x y ↦ by rw [hz x, hz y]⟩

/-- The version of `subsingleton_kaehlerDifferential_of_span_eq_top` for a quotient: if
`B → C` is surjective, the `b i` die in `C` and their differentials generate
`C ⊗[B] Ω[B⁄A]`, then `C` is formally unramified over `A`. -/
theorem formallyUnramified_of_span_eq_top {ι : Type*} (b : ι → B)
    (hsurj : Function.Surjective (algebraMap B C))
    (hspan : Submodule.span C
      (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) = ⊤)
    (hzero : ∀ i, algebraMap B C (b i) = 0) :
    Algebra.FormallyUnramified A C :=
  ⟨subsingleton_kaehlerDifferential_of_span_eq_top b
    (KaehlerDifferential.mapBaseChange_surjective A B C hsurj) hspan hzero⟩

section Slice

variable (A) in
/-- The extension `B ↠ C` viewed as a presentation of `C` as an `A`-algebra. -/
noncomputable def sliceExtension (hsurj : Function.Surjective (algebraMap B C)) :
    Algebra.Extension.{v} A C where
  Ring := B
  σ x := (hsurj x).choose
  algebraMap_σ x := (hsurj x).choose_spec

/-- **Jacobian criterion for a slice, formal part.** Let `B` be a formally smooth `A`-algebra,
let `C` be the quotient of `B` by the ideal generated by a family `b : ι → B`, and assume that
the differentials `1 ⊗ d (b i)` form a basis of `C ⊗[B] Ω[B⁄A]`.  Then `C` is formally étale
over `A`. -/
theorem formallyEtale_of_basis {ι : Type*} [Algebra.FormallySmooth A B] (b : ι → B)
    (hsurj : Function.Surjective (algebraMap B C))
    (hker : Ideal.span (Set.range b) = RingHom.ker (algebraMap B C))
    (bas : Module.Basis ι C (C ⊗[B] Ω[B⁄A]))
    (hbas : ∀ i, bas i = (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) :
    Algebra.FormallyEtale A C := by
  set P := sliceExtension A hsurj
  have hFS : Algebra.FormallySmooth A P.Ring := ‹Algebra.FormallySmooth A B›
  have hmem : ∀ i, b i ∈ P.ker := fun i ↦ hker.le (Ideal.subset_span ⟨i, rfl⟩)
  -- `P.Cotangent` is generated over `C` by the classes of the `b i`.
  have hspanCot : Submodule.span C (Set.range fun i ↦
      Algebra.Extension.Cotangent.mk (P := P) ⟨b i, hmem i⟩) = ⊤ :=
    Algebra.Extension.Cotangent.span_eq_top_of_span_eq_ker (P := P) b hker
  -- The section of the cotangent complex defined on the given basis.
  set s := bas.constr C fun i ↦ Algebra.Extension.Cotangent.mk (P := P) ⟨b i, hmem i⟩ with hs
  have hsSurj : Function.Surjective s := by
    rw [← LinearMap.range_eq_top, hs, Module.Basis.constr_range]
    exact hspanCot
  have hsection : ∀ x, P.cotangentComplex (s x) = x := by
    have hb : ∀ i, P.cotangentComplex (s (bas i)) = bas i := by
      intro i
      rw [hs, Module.Basis.constr_basis, Algebra.Extension.cotangentComplex_mk]
      exact (hbas i).symm
    have hid : P.cotangentComplex ∘ₗ s = LinearMap.id := by
      refine bas.ext fun i ↦ ?_
      change P.cotangentComplex (s (bas i)) = bas i
      exact hb i
    exact fun x ↦ congr($hid x)
  have hbij : Function.Bijective P.cotangentComplex := by
    refine ⟨fun x y hxy ↦ ?_, fun z ↦ ⟨s z, hsection z⟩⟩
    obtain ⟨x', rfl⟩ := hsSurj x
    obtain ⟨y', rfl⟩ := hsSurj y
    rw [hsection, hsection] at hxy
    rw [hxy]
  have hSmooth : Algebra.FormallySmooth A C := by
    rw [P.formallySmooth_iff_split_injection]
    refine ⟨(LinearEquiv.ofBijective P.cotangentComplex hbij).symm.toLinearMap,
      LinearMap.ext fun x ↦ ?_⟩
    simp
  have hUnram : Algebra.FormallyUnramified A C := by
    refine formallyUnramified_of_span_eq_top b hsurj ?_ fun i ↦ RingHom.mem_ker.mp (hmem i)
    have hrange : (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i))
        = Set.range bas := by simp only [← hbas]
    rw [hrange]
    exact bas.span_eq
  exact Algebra.FormallyEtale.of_formallyUnramified_and_formallySmooth

/-- **Jacobian criterion for a slice.** Same hypotheses as `formallyEtale_of_basis`, plus
finite presentation: the slice is étale over the base. -/
theorem etale_of_basis {ι : Type*} [Algebra.FormallySmooth A B] [Algebra.FinitePresentation A C]
    (b : ι → B) (hsurj : Function.Surjective (algebraMap B C))
    (hker : Ideal.span (Set.range b) = RingHom.ker (algebraMap B C))
    (bas : Module.Basis ι C (C ⊗[B] Ω[B⁄A]))
    (hbas : ∀ i, bas i = (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) :
    Algebra.Etale A C :=
  ⟨formallyEtale_of_basis b hsurj hker bas hbas, inferInstance⟩

/-- **Dimension count.** A family of `n` elements generating a free module of rank `n` is a
basis.  (Over a commutative ring this is Orzech's theorem: a surjective endomorphism of a
finitely generated module is injective.)  This is the step of Stacks 06N3 which upgrades
"the `d fᵢ` generate the relative cotangent module" to "the `d fᵢ` form a basis". -/
theorem exists_basis_of_span_eq_top {M : Type*} [AddCommGroup M] [Module C M] {ι : Type*}
    [Finite ι] (bas₀ : Module.Basis ι C M) (v : ι → M)
    (hspan : Submodule.span C (Set.range v) = ⊤) :
    ∃ bas : Module.Basis ι C M, ∀ i, bas i = v i := by
  have hfin : Module.Finite C M := Module.Finite.of_basis bas₀
  have hsurj : Function.Surjective (bas₀.constr C v) := by
    rw [← LinearMap.range_eq_top, Module.Basis.constr_range]
    exact hspan
  have hbij := OrzechProperty.bijective_of_surjective_endomorphism _ hsurj
  refine ⟨bas₀.map (LinearEquiv.ofBijective _ hbij), fun i ↦ ?_⟩
  rw [Module.Basis.map_apply, LinearEquiv.ofBijective_apply, Module.Basis.constr_basis]

/-- **Ring-theoretic étale slicing.** Let `B` be a formally smooth `A`-algebra, let `C` be the
quotient of `B` by the ideal generated by a finite family `b : ι → B`, and assume that
`C ⊗[B] Ω[B⁄A]` is free of rank `#ι` (which holds when `B` is smooth over `A` of relative
dimension `#ι`) and that the differentials `1 ⊗ d (b i)` generate it.  Then `C` is étale
over `A`.  This is the local form of the slicing construction of Stacks 06N3. -/
theorem etale_of_span_eq_top {ι : Type*} [Finite ι] [Algebra.FormallySmooth A B]
    [Algebra.FinitePresentation A C] (b : ι → B)
    (hsurj : Function.Surjective (algebraMap B C))
    (hker : Ideal.span (Set.range b) = RingHom.ker (algebraMap B C))
    (bas₀ : Module.Basis ι C (C ⊗[B] Ω[B⁄A]))
    (hspan : Submodule.span C
      (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) = ⊤) :
    Algebra.Etale A C := by
  obtain ⟨bas, hbas⟩ := exists_basis_of_span_eq_top bas₀ _ hspan
  exact etale_of_basis b hsurj hker bas hbas

/-- **Étale slicing, Stacks 06N3 (local form).**  Let `B` be a standard smooth `A`-algebra of
relative dimension `n`, let `b : Fin n → B` and let `C` be the quotient of `B` by the ideal
generated by the `b i`.  If the differentials `1 ⊗ d (b i)` generate `C ⊗[B] Ω[B⁄A]`, then `C`
is étale over `A`.  Both the freeness of the relative cotangent module of rank `n` and the
resulting dimension count are supplied here, so the only inputs are the generation of the
differentials and the presentation of `C`. -/
theorem etale_of_span_eq_top_of_isStandardSmooth (n : ℕ) [Nontrivial B]
    [Algebra.IsStandardSmoothOfRelativeDimension n A B] [Algebra.FinitePresentation A C]
    (b : Fin n → B) (hsurj : Function.Surjective (algebraMap B C))
    (hker : Ideal.span (Set.range b) = RingHom.ker (algebraMap B C))
    (hspan : Submodule.span C
      (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) = ⊤) :
    Algebra.Etale A C := by
  have hss : Algebra.IsStandardSmooth A B :=
    Algebra.IsStandardSmoothOfRelativeDimension.isStandardSmooth n
  have hfr : Module.finrank B Ω[B⁄A] = n := Module.finrank_eq_of_rank_eq
    (Algebra.IsStandardSmoothOfRelativeDimension.rank_kaehlerDifferential n)
  exact etale_of_span_eq_top b hsurj hker
    (Algebra.TensorProduct.basis C (Module.finBasisOfFinrankEq B Ω[B⁄A] hfr)) hspan

end Slice

section SchemeLevel

variable {A B C : Type u} [CommRing A] [CommRing B] [CommRing C]
  [Algebra A B] [Algebra A C] [Algebra B C] [IsScalarTower A B C]

open AlgebraicGeometry in
/-- **Étale slicing, scheme-level form.**  In the situation of
`etale_of_span_eq_top_of_isStandardSmooth`, the morphism of affine schemes
`Spec C ⟶ Spec A` cut out by the slice is étale. -/
theorem isEtale_specMap_of_span_eq_top (n : ℕ) [Nontrivial B]
    [Algebra.IsStandardSmoothOfRelativeDimension n A B] [Algebra.FinitePresentation A C]
    (b : Fin n → B) (hsurj : Function.Surjective (algebraMap B C))
    (hker : Ideal.span (Set.range b) = RingHom.ker (algebraMap B C))
    (hspan : Submodule.span C
      (Set.range fun i ↦ (1 : C) ⊗ₜ[B] KaehlerDifferential.D A B (b i)) = ⊤) :
    Etale (Spec.map (CommRingCat.ofHom (algebraMap A C))) := by
  rw [HasRingHomProperty.Spec_iff (P := @Etale)]
  exact RingHom.etale_algebraMap.mpr
    (etale_of_span_eq_top_of_isStandardSmooth n b hsurj hker hspan)

end SchemeLevel

end GromovWitten.EtaleSlice
