/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Stacks.AtlasRefinement
import GromovWitten.AlgebraicGeometry.Stacks.OverlapSwap
import Mathlib.Topology.Maps.OpenQuotient
import Mathlib.AlgebraicGeometry.Morphisms.UniversallyOpen

/-!
# Atlas independence of the underlying topological space of an algebraic stack

`Stacks.Geometry` builds the point set and the topology of an algebraic stack as the quotient of
the *internally chosen* smooth atlas by the relation generated by the two projections of its
represented self-overlap.  This file proves that the resulting topological space does not depend
on that choice: every smooth surjective chart computes it, canonically and compatibly.

## The cross relation of two charts

The organising notion is `StackChart.crossRel A B`, a relation between the points of the schemes
of two charts: `x : A.scheme` and `y : B.scheme` are related when some (equivalently, by
`StackChart.crossRel_iff`, any) presentation of the overlap `A.scheme ×_X B.scheme` carries a
point with the two projections `x` and `y`.  For `A = B` it is exactly the relation
`StackChart.pointRelation` of `Stacks.AtlasRefinement`, and for the chosen atlas of an algebraic
stack it is `AlgebraicStack.atlasPointRelation` (`AlgebraicStack.chosenAtlas_crossRel_iff`).

The cross relation is a groupoid-like calculus, *constructed* from the universal properties:

* `StackChart.crossRel_iff`: independence of the chosen overlap presentation, via the comparison
  morphism `StackChart.presentationComparison`;
* `StackChart.crossRel_symm`: symmetry, via `StackChart.PullbackPresentation.swap` of
  `Stacks.OverlapSwap` — this is the only place where the two legs of an overlap are exchanged;
* `StackChart.crossRel_refl`: reflexivity, via the unit section of a self-overlap;
* `StackChart.crossRel_trans`: transitivity, via the scheme of composable pairs
  `pullback P.snd Q.fst` and the comparison cell `StackChart.crossComposeComparison`.

Reflexivity and transitivity need the target chart to be representable; nothing else is assumed.

## The point space of a chart and its independence

`StackChart.pointSpace A` is the quotient of `A.scheme` by the equivalence relation generated by
`A.crossRel A`, with the quotient topology, and `StackChart.pointMap` is the quotient map.  For a
representable chart the generated closure adds nothing (`StackChart.pointMap_eq_iff`).

The comparison of two atlases is `StackChart.chartPointHomeo`: for smooth surjective charts `A`
and `B` it is a homeomorphism `A.pointSpace ≃ₜ B.pointSpace`.  It is built from the overlap
`A.scheme ×_X B.scheme`, whose two projections are smooth surjective — the first because `B` is
an atlas, the second because `A` is, using the swap of `Stacks.OverlapSwap` — hence open quotient
maps on points (`isOpenQuotientMap_of_smooth_surjective`, from `UniversallyOpen.of_flat`).  Two
quotient maps out of one space with the same fibres identify their targets
(`homeomorphOfIsQuotientMap`), and the fibre comparison is exactly the groupoid calculus above.

The comparison is characterised by the cross relation (`StackChart.chartPointHomeo_apply_eq_iff`),
hence is the unique map compatible with the point maps (`StackChart.chartPointHomeo_unique`), is
the identity for `A = B`, is inverted by exchanging the charts, and satisfies the cocycle law
`StackChart.chartPointHomeo_trans`.

## Consequences

* `AlgebraicStack.pointSpaceHomeo`: every smooth surjective chart of an algebraic stack computes
  its underlying topological space, `A.pointSpace ≃ₜ UnderlyingStackPoint X`.
* `AlgebraicStack.atlasToPoint` is the resulting surjective open quotient map from any atlas, it
  agrees with `AlgebraicStack.atlasPointMap` on the chosen atlas, and openness, closedness,
  quasi-compactness and irreducibility of the underlying space may be tested on it
  (`AlgebraicStack.isOpen_iff_atlasToPoint`, `AlgebraicStack.isClosed_iff_atlasToPoint`,
  `AlgebraicStack.compactSpace_of_atlas`, `AlgebraicStack.irreducibleSpace_of_atlas`).
* `FppfStack.underlyingStackPointHomeoScheme`: the underlying space of the stack represented by a
  scheme `Z` is homeomorphic to `Z`.
-/

open CategoryTheory Topology

namespace GromovWitten.AlgebraicGeometry

universe u

/-! ## Two quotient maps with the same fibres -/

/-- Transfer a map along a surjection: the value at `a` is the value of `g` at some chosen
preimage of `a`. -/
noncomputable def quotientTransfer {Z α β : Type*} {f : Z → α}
    (hf : Function.Surjective f) (g : Z → β) : α → β :=
  fun a ↦ g (Classical.choose (hf a))

/-- The transferred map computes the original one as soon as the original is constant on the
fibres of the surjection. -/
theorem quotientTransfer_apply {Z α β : Type*} {f : Z → α} (hf : Function.Surjective f)
    {g : Z → β} (hfib : ∀ z z' : Z, f z = f z' → g z = g z') (z : Z) :
    quotientTransfer hf g (f z) = g z :=
  hfib _ _ (Classical.choose_spec (hf (f z)))

/-- **Two quotient maps out of the same space with the same fibres identify their targets.**
This is the topological input for atlas independence: a smooth surjection from an overlap to two
atlases makes both point spaces quotients of the overlap. -/
noncomputable def homeomorphOfIsQuotientMap {Z α β : Type*} [TopologicalSpace Z]
    [TopologicalSpace α] [TopologicalSpace β] {f : Z → α} {g : Z → β}
    (hf : IsQuotientMap f) (hg : IsQuotientMap g)
    (hfib : ∀ z z' : Z, f z = f z' ↔ g z = g z') : α ≃ₜ β where
  toFun := quotientTransfer hf.surjective g
  invFun := quotientTransfer hg.surjective f
  left_inv a := by
    obtain ⟨z, rfl⟩ := hf.surjective a
    rw [quotientTransfer_apply hf.surjective (fun z z' h ↦ (hfib z z').mp h),
      quotientTransfer_apply hg.surjective (fun z z' h ↦ (hfib z z').mpr h)]
  right_inv b := by
    obtain ⟨z, rfl⟩ := hg.surjective b
    rw [quotientTransfer_apply hg.surjective (fun z z' h ↦ (hfib z z').mpr h),
      quotientTransfer_apply hf.surjective (fun z z' h ↦ (hfib z z').mp h)]
  continuous_toFun := by
    rw [hf.continuous_iff]
    have hcomp : quotientTransfer hf.surjective g ∘ f = g :=
      funext fun z ↦ quotientTransfer_apply hf.surjective (fun z z' h ↦ (hfib z z').mp h) z
    rw [hcomp]
    exact hg.continuous
  continuous_invFun := by
    rw [hg.continuous_iff]
    have hcomp : quotientTransfer hg.surjective f ∘ g = f :=
      funext fun z ↦ quotientTransfer_apply hg.surjective (fun z z' h ↦ (hfib z z').mpr h) z
    rw [hcomp]
    exact hf.continuous

/-- The homeomorphism attached to two quotient maps with the same fibres is compatible with
them. -/
theorem homeomorphOfIsQuotientMap_apply {Z α β : Type*} [TopologicalSpace Z]
    [TopologicalSpace α] [TopologicalSpace β] {f : Z → α} {g : Z → β}
    (hf : IsQuotientMap f) (hg : IsQuotientMap g)
    (hfib : ∀ z z' : Z, f z = f z' ↔ g z = g z') (z : Z) :
    homeomorphOfIsQuotientMap hf hg hfib (f z) = g z :=
  quotientTransfer_apply hf.surjective (fun z z' h ↦ (hfib z z').mp h) z

/-- **A smooth surjective morphism of schemes is an open quotient map on points.**  Smooth
morphisms are flat and locally of finite presentation, hence universally open. -/
theorem isOpenQuotientMap_of_smooth_surjective {W U : Scheme.{u}} (q : W ⟶ U)
    (hq : ((@_root_.AlgebraicGeometry.Smooth ⊓ @_root_.AlgebraicGeometry.Surjective :
      MorphismProperty Scheme.{u})) q) :
    IsOpenQuotientMap (fun w : W ↦ q.base w) := by
  have hsmooth : _root_.AlgebraicGeometry.Smooth q := hq.1
  have hsurj : _root_.AlgebraicGeometry.Surjective q := hq.2
  exact ⟨hsurj.surj, q.continuous, q.isOpenMap⟩

namespace StackChart

variable {X : FppfStack.{u}}

/-! ## The cross relation of two charts -/

/-- **The cross relation of two charts.**  A point of the scheme of `A` and a point of the scheme
of `B` are related when an actual point of a presentation of the overlap
`A.scheme ×_X B.scheme` projects to them.  For `A = B` this is `StackChart.pointRelation`. -/
def crossRel (A B : StackChart X) (x : A.scheme) (y : B.scheme) : Prop :=
  ∃ (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) (r : P.space),
    P.fst.base r = x ∧ P.snd.base r = y

/-- The comparison morphism between two presentations of the same base change of a chart,
constructed by the universal property of the target presentation. -/
noncomputable def presentationComparison {A : StackChart X} {T : Scheme.{u}}
    {x : StackFiber X T} (P Q : A.PullbackPresentation T x) : Q.space ⟶ P.space :=
  P.lift Q.fst Q.snd Q.comparison

/-- The comparison morphism of presentations respects the first projection. -/
theorem presentationComparison_fst {A : StackChart X} {T : Scheme.{u}}
    {x : StackFiber X T} (P Q : A.PullbackPresentation T x) :
    presentationComparison P Q ≫ P.fst = Q.fst :=
  P.lift_fst _ _ _

/-- The comparison morphism of presentations respects the second projection. -/
theorem presentationComparison_snd {A : StackChart X} {T : Scheme.{u}}
    {x : StackFiber X T} (P Q : A.PullbackPresentation T x) :
    presentationComparison P Q ≫ P.snd = Q.snd :=
  P.lift_snd _ _ _

/-- **The cross relation may be tested on any single overlap presentation.**  In particular it
does not depend on a choice of presentation. -/
theorem crossRel_iff (A B : StackChart X)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)))
    {x : A.scheme} {y : B.scheme} :
    A.crossRel B x y ↔ ∃ r : P.space, P.fst.base r = x ∧ P.snd.base r = y := by
  constructor
  · rintro ⟨Q, r, hr₁, hr₂⟩
    refine ⟨(presentationComparison P Q).base r, ?_, ?_⟩
    · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, presentationComparison_fst]
      exact hr₁
    · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, presentationComparison_snd]
      exact hr₂
  · rintro ⟨r, hr₁, hr₂⟩
    exact ⟨P, r, hr₁, hr₂⟩

/-- Every point of an overlap presentation witnesses the cross relation of its projections. -/
theorem crossRel_of_point (A B : StackChart X)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) (r : P.space) :
    A.crossRel B (P.fst.base r) (P.snd.base r) :=
  ⟨P, r, rfl, rfl⟩

/-- **The cross relation is symmetric in the two charts**, by the leg exchange of an overlap
presentation. -/
theorem crossRel_symm {A B : StackChart X} {x : A.scheme} {y : B.scheme}
    (h : A.crossRel B x y) : B.crossRel A y x := by
  obtain ⟨P, r, hr₁, hr₂⟩ := h
  exact ⟨PullbackPresentation.swap B A P, r, hr₂, hr₁⟩

/-- **The cross relation of a chart with itself is reflexive**, witnessed by the unit section of
a self-overlap. -/
theorem crossRel_refl {A : StackChart X} (hA : A.IsRepresentable) (x : A.scheme) :
    A.crossRel A x x := by
  obtain ⟨P⟩ := hA.1 A.scheme (A.obj A.scheme (𝟙 A.scheme))
  refine ⟨P, (P.lift (𝟙 _) (𝟙 _)
    (A.identityObjectPullbackComparison (𝟙 A.scheme))).base x, ?_, ?_⟩
  · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, P.lift_fst]
    simp
  · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, P.lift_snd]
    simp

/-- The comparison cell classifying the composite of two overlap points.  It is assembled from
the two pulled-back universal comparisons of the overlaps and the identity-object comparison of
the middle chart. -/
noncomputable def crossComposeComparison (A B C : StackChart X)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)))
    (Q : C.PullbackPresentation B.scheme (B.obj B.scheme (𝟙 B.scheme))) :
    C.obj (Limits.pullback P.snd Q.fst)
        (Limits.pullback.snd P.snd Q.fst ≫ Q.snd) ≅
      (stackPullback X (Limits.pullback.fst P.snd Q.fst ≫ P.fst)).obj
        (A.obj A.scheme (𝟙 A.scheme)) :=
  ((C.inducedComparison Q.fst Q.snd Q.comparison
        (Limits.pullback.snd P.snd Q.fst)).trans
      ((stackPullbackObjIsoOfEq X Limits.pullback.condition.symm
          (B.obj B.scheme (𝟙 B.scheme))).trans
        (B.identityObjectPullbackComparison
          (Limits.pullback.fst P.snd Q.fst ≫ P.snd)).symm)).trans
    (B.inducedComparison P.fst P.snd P.comparison (Limits.pullback.fst P.snd Q.fst))

/-- **The cross relation composes**, by the constructed composition on the scheme of composable
pairs of overlap points.  Only representability of the last chart is used. -/
theorem crossRel_trans {A B C : StackChart X} (hC : C.IsRepresentable)
    {x : A.scheme} {y : B.scheme} {z : C.scheme}
    (h₁ : A.crossRel B x y) (h₂ : B.crossRel C y z) : A.crossRel C x z := by
  obtain ⟨P, r, hr₁, hr₂⟩ := h₁
  obtain ⟨Q, s, hs₁, hs₂⟩ := h₂
  obtain ⟨R⟩ := hC.1 A.scheme (A.obj A.scheme (𝟙 A.scheme))
  obtain ⟨t, ht₁, ht₂⟩ :=
    _root_.AlgebraicGeometry.Scheme.Pullback.exists_preimage_pullback
      (f := P.snd) (g := Q.fst) r s (by rw [hr₂, hs₁])
  refine ⟨R, (R.lift (Limits.pullback.fst P.snd Q.fst ≫ P.fst)
    (Limits.pullback.snd P.snd Q.fst ≫ Q.snd)
    (crossComposeComparison A B C P Q)).base t, ?_, ?_⟩
  · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, R.lift_fst,
      _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, ht₁]
    exact hr₁
  · rw [← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, R.lift_snd,
      _root_.AlgebraicGeometry.Scheme.Hom.comp_apply, ht₂]
    exact hs₂

/-- A smooth surjective chart is representable. -/
theorem isRepresentable_of_smoothSurjective {A : StackChart X} (hA : A.IsSmoothSurjective) :
    A.IsRepresentable :=
  A.isRepresentable_of_hasRepresentableProperty _ hA

/-- **Every point of one atlas is cross related to a point of any other atlas**, because the
projection of the overlap to the first chart is surjective. -/
theorem exists_crossRel {A B : StackChart X} (hB : B.IsSmoothSurjective) (x : A.scheme) :
    ∃ y : B.scheme, A.crossRel B x y := by
  obtain ⟨P⟩ := hB.1 A.scheme (A.obj A.scheme (𝟙 A.scheme))
  obtain ⟨r, hr⟩ := (hB.2 A.scheme (A.obj A.scheme (𝟙 A.scheme)) P).2.surj x
  exact ⟨P.snd.base r, P, r, hr, rfl⟩

/-! ## The point space of a chart -/

/-- **The point space of a chart**: the quotient of its scheme by the equivalence relation
generated by the cross relation of the chart with itself, with the quotient topology. -/
abbrev pointSpace (A : StackChart X) : Type u :=
  Quotient (Relation.EqvGen.setoid (A.crossRel A))

/-- The quotient map from the scheme of a chart to its point space. -/
def pointMap (A : StackChart X) : A.scheme → A.pointSpace :=
  Quotient.mk (Relation.EqvGen.setoid (A.crossRel A))

/-- The point map of a chart is a topological quotient map. -/
theorem isQuotientMap_pointMap (A : StackChart X) : IsQuotientMap A.pointMap :=
  ⟨⟨rfl⟩, Quotient.exists_rep⟩

/-- The point map of a chart is surjective. -/
theorem pointMap_surjective (A : StackChart X) : Function.Surjective A.pointMap :=
  (A.isQuotientMap_pointMap).surjective

/-- A subset of the point space of a chart is open exactly when its preimage in the chart scheme
is open. -/
theorem isOpen_pointSpace_iff (A : StackChart X) (S : Set A.pointSpace) :
    IsOpen S ↔ IsOpen (A.pointMap ⁻¹' S) :=
  Iff.rfl

/-- **For a representable chart the generated equivalence relation adds nothing**: the cross
relation of a chart with itself is already an equivalence relation. -/
theorem eqvGen_crossRel_iff {A : StackChart X} (hA : A.IsRepresentable) {x y : A.scheme} :
    Relation.EqvGen (A.crossRel A) x y ↔ A.crossRel A x y := by
  constructor
  · intro h
    induction h with
    | rel a b hab => exact hab
    | refl a => exact crossRel_refl hA a
    | symm a b _ ih => exact crossRel_symm ih
    | trans a b c _ _ hab hbc => exact crossRel_trans hA hab hbc
  · exact Relation.EqvGen.rel _ _

/-- **The point space of a representable chart is the honest orbit set of its overlap
groupoid.** -/
theorem pointMap_eq_iff {A : StackChart X} (hA : A.IsRepresentable) {x y : A.scheme} :
    A.pointMap x = A.pointMap y ↔ A.crossRel A x y := by
  constructor
  · intro h
    have h' : Quotient.mk (Relation.EqvGen.setoid (A.crossRel A)) x =
        Quotient.mk (Relation.EqvGen.setoid (A.crossRel A)) y := h
    exact (eqvGen_crossRel_iff hA).mp (Quotient.exact h')
  · intro h
    exact Quotient.sound (Relation.EqvGen.rel _ _ h)

/-! ## The comparison homeomorphism of two atlases -/

/-- A chosen presentation of the overlap of two charts, available because the second chart is
representable. -/
noncomputable def overlapPresentation (A B : StackChart X) (hB : B.IsRepresentable) :
    B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme)) :=
  Classical.choice (hB.1 A.scheme (A.obj A.scheme (𝟙 A.scheme)))

/-- The first projection of an overlap presentation is an open quotient map on points, because
the second chart is a smooth surjective atlas. -/
theorem isQuotientMap_pointMap_fst {A B : StackChart X} (hB : B.IsSmoothSurjective)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    IsQuotientMap (fun r : P.space ↦ A.pointMap (P.fst.base r)) :=
  (A.isQuotientMap_pointMap).comp
    (isOpenQuotientMap_of_smooth_surjective P.fst
      (hB.2 A.scheme (A.obj A.scheme (𝟙 A.scheme)) P)).isQuotientMap

/-- The second projection of an overlap presentation is an open quotient map on points, because
the *first* chart is a smooth surjective atlas.  This is where the leg exchange of
`Stacks.OverlapSwap` is used. -/
theorem isQuotientMap_pointMap_snd {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) :
    IsQuotientMap (fun r : P.space ↦ B.pointMap (P.snd.base r)) := by
  have hsnd : ((@_root_.AlgebraicGeometry.Smooth ⊓ @_root_.AlgebraicGeometry.Surjective :
      MorphismProperty Scheme.{u})) P.snd :=
    hA.2 B.scheme (B.obj B.scheme (𝟙 B.scheme)) (PullbackPresentation.swap B A P)
  exact (B.isQuotientMap_pointMap).comp
    (isOpenQuotientMap_of_smooth_surjective P.snd hsnd).isQuotientMap

/-- **The two projections of an overlap have the same fibres on point spaces.**  This is the
groupoid calculus of the cross relation in its point-set form. -/
theorem overlap_pointMap_eq_iff {A B : StackChart X} (hA : A.IsRepresentable)
    (hB : B.IsRepresentable)
    (P : B.PullbackPresentation A.scheme (A.obj A.scheme (𝟙 A.scheme))) (r r' : P.space) :
    A.pointMap (P.fst.base r) = A.pointMap (P.fst.base r') ↔
      B.pointMap (P.snd.base r) = B.pointMap (P.snd.base r') := by
  rw [pointMap_eq_iff hA, pointMap_eq_iff hB]
  constructor
  · intro h
    exact crossRel_trans hB
      (crossRel_trans hA (crossRel_symm (crossRel_of_point A B P r)) h)
      (crossRel_of_point A B P r')
  · intro h
    exact crossRel_trans hA
      (crossRel_trans hB (crossRel_of_point A B P r) h)
      (crossRel_symm (crossRel_of_point A B P r'))

/-- **Atlas independence of the point space.**  Any two smooth surjective charts of a stack have
canonically homeomorphic point spaces, through the overlap of the two charts. -/
noncomputable def chartPointHomeo {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) : A.pointSpace ≃ₜ B.pointSpace :=
  homeomorphOfIsQuotientMap
    (isQuotientMap_pointMap_fst hB
      (overlapPresentation A B (isRepresentable_of_smoothSurjective hB)))
    (isQuotientMap_pointMap_snd hA
      (overlapPresentation A B (isRepresentable_of_smoothSurjective hB)))
    (fun r r' ↦ overlap_pointMap_eq_iff (isRepresentable_of_smoothSurjective hA)
      (isRepresentable_of_smoothSurjective hB)
      (overlapPresentation A B (isRepresentable_of_smoothSurjective hB)) r r')

/-- **The comparison homeomorphism is characterised by the cross relation.**  It sends the class
of `x` to the class of `y` exactly when `x` and `y` are cross related. -/
theorem chartPointHomeo_apply_eq_iff {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) (x : A.scheme) (y : B.scheme) :
    chartPointHomeo hA hB (A.pointMap x) = B.pointMap y ↔ A.crossRel B x y := by
  have hAr := isRepresentable_of_smoothSurjective hA
  have hBr := isRepresentable_of_smoothSurjective hB
  set P := overlapPresentation A B hBr with hP
  obtain ⟨r, hr⟩ := (hB.2 A.scheme (A.obj A.scheme (𝟙 A.scheme)) P).2.surj x
  have hmap : chartPointHomeo hA hB (A.pointMap x) = B.pointMap (P.snd.base r) := by
    rw [← hr]
    exact homeomorphOfIsQuotientMap_apply _ _ _ r
  rw [hmap, pointMap_eq_iff hBr]
  have hxr : A.crossRel B x (P.snd.base r) := by
    rw [← hr]
    exact crossRel_of_point A B P r
  constructor
  · intro h
    exact crossRel_trans hBr hxr h
  · intro h
    exact crossRel_trans hBr (crossRel_symm hxr) h

/-- The comparison homeomorphism sends the class of a point to the class of any cross related
point. -/
theorem chartPointHomeo_pointMap {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) {x : A.scheme} {y : B.scheme} (h : A.crossRel B x y) :
    chartPointHomeo hA hB (A.pointMap x) = B.pointMap y :=
  (chartPointHomeo_apply_eq_iff hA hB x y).mpr h

/-- **Uniqueness of the comparison.**  Any map of point spaces compatible with the point maps and
the cross relation is the comparison homeomorphism. -/
theorem chartPointHomeo_unique {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) (F : A.pointSpace → B.pointSpace)
    (hF : ∀ (x : A.scheme) (y : B.scheme), A.crossRel B x y → F (A.pointMap x) = B.pointMap y) :
    F = chartPointHomeo hA hB := by
  funext a
  obtain ⟨x, rfl⟩ := A.pointMap_surjective a
  obtain ⟨y, hy⟩ := exists_crossRel hB x
  rw [hF x y hy, chartPointHomeo_pointMap hA hB hy]

/-- The comparison of a smooth surjective chart with itself is the identity. -/
theorem chartPointHomeo_self {A : StackChart X} (hA : A.IsSmoothSurjective) :
    chartPointHomeo hA hA = Homeomorph.refl A.pointSpace := by
  have hAr := isRepresentable_of_smoothSurjective hA
  refine Homeomorph.ext fun a ↦ ?_
  obtain ⟨x, rfl⟩ := A.pointMap_surjective a
  exact chartPointHomeo_pointMap hA hA (crossRel_refl hAr x)

/-- **The comparisons satisfy the cocycle law**: comparing `A` with `B` and then `B` with `C` is
comparing `A` with `C`. -/
theorem chartPointHomeo_trans {A B C : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) (hC : C.IsSmoothSurjective) :
    (chartPointHomeo hA hB).trans (chartPointHomeo hB hC) = chartPointHomeo hA hC := by
  have hCr := isRepresentable_of_smoothSurjective hC
  refine Homeomorph.ext fun a ↦ ?_
  obtain ⟨x, rfl⟩ := A.pointMap_surjective a
  obtain ⟨y, hy⟩ := exists_crossRel hB x
  obtain ⟨z, hz⟩ := exists_crossRel hC y
  rw [Homeomorph.trans_apply, chartPointHomeo_pointMap hA hB hy,
    chartPointHomeo_pointMap hB hC hz,
    chartPointHomeo_pointMap hA hC (crossRel_trans hCr hy hz)]

/-- The comparison in the opposite direction is the inverse comparison. -/
theorem chartPointHomeo_symm {A B : StackChart X} (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) :
    (chartPointHomeo hA hB).symm = chartPointHomeo hB hA := by
  refine Homeomorph.ext fun b ↦ ?_
  obtain ⟨y, rfl⟩ := B.pointMap_surjective b
  obtain ⟨x, hx⟩ := exists_crossRel hA y
  rw [chartPointHomeo_pointMap hB hA hx, Homeomorph.symm_apply_eq,
    chartPointHomeo_pointMap hA hB (crossRel_symm hx)]

/-! ## The point map of a chart is open -/

/-- **The point map of a smooth surjective chart is open.**  The saturation of an open subset is
the image under the second projection of its preimage under the first projection of a
self-overlap, and both projections of a self-overlap are smooth surjective. -/
theorem isOpenMap_pointMap {A : StackChart X} (hA : A.IsSmoothSurjective) :
    IsOpenMap A.pointMap := by
  have hAr := isRepresentable_of_smoothSurjective hA
  intro S hS
  rw [isOpen_pointSpace_iff]
  set P := overlapPresentation A A hAr with hP
  have hsnd : ((@_root_.AlgebraicGeometry.Smooth ⊓ @_root_.AlgebraicGeometry.Surjective :
      MorphismProperty Scheme.{u})) P.snd :=
    hA.2 A.scheme (A.obj A.scheme (𝟙 A.scheme)) (PullbackPresentation.swap A A P)
  have hset : A.pointMap ⁻¹' (A.pointMap '' S) =
      (fun r : P.space ↦ P.snd.base r) '' ((fun r : P.space ↦ P.fst.base r) ⁻¹' S) := by
    ext x
    constructor
    · rintro ⟨u, huS, hu⟩
      obtain ⟨r, hr₁, hr₂⟩ := (crossRel_iff A A P).mp ((pointMap_eq_iff hAr).mp hu)
      exact ⟨r, by simpa [hr₁] using huS, hr₂⟩
    · rintro ⟨r, hrS, hr⟩
      exact ⟨P.fst.base r, hrS, (pointMap_eq_iff hAr).mpr
        ⟨P, r, rfl, hr⟩⟩
  rw [hset]
  exact (isOpenQuotientMap_of_smooth_surjective P.snd hsnd).isOpenMap _
    (hS.preimage P.fst.continuous)

end StackChart

/-! ## The underlying space of an algebraic stack -/

namespace AlgebraicStack

variable (Y : AlgebraicStack.{u})

/-- The point map of the chosen atlas onto the constructed underlying space is a topological
quotient map. -/
theorem isQuotientMap_atlasPointMap : IsQuotientMap Y.atlasPointMap :=
  ⟨⟨rfl⟩, Y.atlasPointMap_surjective⟩

/-- The cross relation of the chosen atlas with itself is the atlas point relation used to build
the underlying space of an algebraic stack. -/
theorem chosenAtlas_crossRel_iff {x y : Y.chosenSmoothAtlas.scheme} :
    Y.chosenSmoothAtlas.crossRel Y.chosenSmoothAtlas x y ↔ Y.atlasPointRelation x y :=
  StackChart.crossRel_iff _ _ Y.chosenAtlasSelfOverlap

/-- **The point space of the chosen atlas is the constructed underlying space of the stack.** -/
noncomputable def chosenAtlasPointHomeo :
    Y.chosenSmoothAtlas.pointSpace ≃ₜ UnderlyingStackPoint Y :=
  homeomorphOfIsQuotientMap (StackChart.isQuotientMap_pointMap _) Y.isQuotientMap_atlasPointMap
    (fun x y ↦ by
      rw [StackChart.pointMap_eq_iff (StackChart.isRepresentable_of_smoothSurjective
          Y.chosenSmoothAtlas_isSmoothSurjective), Y.atlasPointMap_eq_iff,
        Y.chosenAtlas_crossRel_iff])

/-- The identification of the point space of the chosen atlas with the underlying space is
compatible with the two quotient maps. -/
theorem chosenAtlasPointHomeo_apply (x : Y.chosenSmoothAtlas.scheme) :
    Y.chosenAtlasPointHomeo (Y.chosenSmoothAtlas.pointMap x) = Y.atlasPointMap x :=
  homeomorphOfIsQuotientMap_apply _ _ _ x

/-- **Every smooth surjective chart computes the underlying topological space of an algebraic
stack.** -/
noncomputable def pointSpaceHomeo (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective) :
    A.pointSpace ≃ₜ UnderlyingStackPoint Y :=
  (StackChart.chartPointHomeo hA Y.chosenSmoothAtlas_isSmoothSurjective).trans
    Y.chosenAtlasPointHomeo

/-- The map from the scheme of an arbitrary smooth surjective chart to the underlying space of
the stack. -/
noncomputable def atlasToPoint (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective) :
    A.scheme → UnderlyingStackPoint Y :=
  fun x ↦ Y.pointSpaceHomeo A hA (A.pointMap x)

/-- On the chosen atlas the general atlas map is the constructed quotient map. -/
theorem atlasToPoint_chosen :
    Y.atlasToPoint Y.chosenSmoothAtlas Y.chosenSmoothAtlas_isSmoothSurjective =
      Y.atlasPointMap := by
  funext x
  change Y.chosenAtlasPointHomeo
    (StackChart.chartPointHomeo Y.chosenSmoothAtlas_isSmoothSurjective
      Y.chosenSmoothAtlas_isSmoothSurjective (Y.chosenSmoothAtlas.pointMap x)) =
    Y.atlasPointMap x
  rw [StackChart.chartPointHomeo_self]
  exact Y.chosenAtlasPointHomeo_apply x

/-- **Two points of an arbitrary atlas have the same image in the stack exactly when they are
cross related.** -/
theorem atlasToPoint_eq_iff (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    {x y : A.scheme} :
    Y.atlasToPoint A hA x = Y.atlasToPoint A hA y ↔ A.crossRel A x y := by
  change Y.pointSpaceHomeo A hA (A.pointMap x) = Y.pointSpaceHomeo A hA (A.pointMap y) ↔ _
  rw [(Y.pointSpaceHomeo A hA).injective.eq_iff,
    StackChart.pointMap_eq_iff (StackChart.isRepresentable_of_smoothSurjective hA)]

/-- **The maps to the underlying space from two different atlases are compatible**: a point of
one atlas and a point of another have the same image in the stack exactly when they are cross
related.  This determines the comparison of atlases completely, because the atlas maps are
surjective. -/
theorem atlasToPoint_eq_iff_crossRel (A B : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    (hB : B.IsSmoothSurjective) {x : A.scheme} {y : B.scheme} :
    Y.atlasToPoint A hA x = Y.atlasToPoint B hB y ↔ A.crossRel B x y := by
  have hc := Y.chosenSmoothAtlas_isSmoothSurjective
  have hcr := StackChart.isRepresentable_of_smoothSurjective hc
  have hBr := StackChart.isRepresentable_of_smoothSurjective hB
  obtain ⟨z, hz⟩ := StackChart.exists_crossRel hc x
  obtain ⟨w, hw⟩ := StackChart.exists_crossRel hc y
  have hxz : Y.atlasToPoint A hA x = Y.atlasPointMap z := by
    change Y.chosenAtlasPointHomeo
      (StackChart.chartPointHomeo hA hc (A.pointMap x)) = Y.atlasPointMap z
    rw [StackChart.chartPointHomeo_pointMap hA hc hz]
    exact Y.chosenAtlasPointHomeo_apply z
  have hyw : Y.atlasToPoint B hB y = Y.atlasPointMap w := by
    change Y.chosenAtlasPointHomeo
      (StackChart.chartPointHomeo hB hc (B.pointMap y)) = Y.atlasPointMap w
    rw [StackChart.chartPointHomeo_pointMap hB hc hw]
    exact Y.chosenAtlasPointHomeo_apply w
  rw [hxz, hyw, Y.atlasPointMap_eq_iff, ← Y.chosenAtlas_crossRel_iff]
  constructor
  · intro h
    exact StackChart.crossRel_trans hBr (StackChart.crossRel_trans hcr hz h)
      (StackChart.crossRel_symm hw)
  · intro h
    exact StackChart.crossRel_trans hcr
      (StackChart.crossRel_trans hBr (StackChart.crossRel_symm hz) h) hw

/-- The map from an arbitrary atlas to the underlying space is surjective. -/
theorem atlasToPoint_surjective (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective) :
    Function.Surjective (Y.atlasToPoint A hA) :=
  (Y.pointSpaceHomeo A hA).surjective.comp A.pointMap_surjective

/-- **The map from an arbitrary atlas to the underlying space is a surjective open quotient
map.** -/
theorem isOpenQuotientMap_atlasToPoint (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective) :
    IsOpenQuotientMap (Y.atlasToPoint A hA) :=
  ⟨Y.atlasToPoint_surjective A hA,
    (Y.pointSpaceHomeo A hA).continuous.comp (A.isQuotientMap_pointMap).continuous,
    (Y.pointSpaceHomeo A hA).isOpenMap.comp (StackChart.isOpenMap_pointMap hA)⟩

/-- **Openness of a set of stack points may be tested on any atlas.** -/
theorem isOpen_iff_atlasToPoint (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    (S : Set (UnderlyingStackPoint Y)) :
    IsOpen S ↔ IsOpen (Y.atlasToPoint A hA ⁻¹' S) :=
  (Y.isOpenQuotientMap_atlasToPoint A hA).isQuotientMap.isOpen_preimage.symm

/-- **Closedness of a set of stack points may be tested on any atlas.** -/
theorem isClosed_iff_atlasToPoint (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    (S : Set (UnderlyingStackPoint Y)) :
    IsClosed S ↔ IsClosed (Y.atlasToPoint A hA ⁻¹' S) :=
  ((Y.isOpenQuotientMap_atlasToPoint A hA).isQuotientMap.isClosed_preimage).symm

/-- **Quasi-compactness of the underlying space may be tested on any atlas.** -/
theorem compactSpace_of_atlas (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    [CompactSpace A.scheme] : CompactSpace (UnderlyingStackPoint Y) :=
  (Y.atlasToPoint_surjective A hA).compactSpace
    (Y.isOpenQuotientMap_atlasToPoint A hA).continuous

/-- **Irreducibility of the underlying space may be tested on any atlas.** -/
theorem irreducibleSpace_of_atlas (A : StackChart Y.toStack) (hA : A.IsSmoothSurjective)
    [IrreducibleSpace A.scheme] : IrreducibleSpace (UnderlyingStackPoint Y) :=
  (Y.atlasToPoint_surjective A hA).irreducibleSpace
    (Y.isOpenQuotientMap_atlasToPoint A hA).continuous

end AlgebraicStack

/-! ## The underlying space of a represented stack -/

namespace FppfStack

variable (Z : Scheme.{u})

/-- **The point relation of the identity chart of a scheme is equality.**  Every presentation of
the self-overlap of the identity chart has an isomorphism as first projection, so a point of the
overlap is determined by its first projection; reflexivity then forces the second projection to
agree with the first. -/
theorem schemeChart_crossRel_iff {x y : (schemeChart Z).scheme} :
    (schemeChart Z).crossRel (schemeChart Z) x y ↔ x = y := by
  have hAr := StackChart.isRepresentable_of_smoothSurjective (schemeChart_isSmoothSurjective Z)
  constructor
  · intro h
    obtain ⟨P⟩ := hAr.1 (schemeChart Z).scheme
      ((schemeChart Z).obj (schemeChart Z).scheme (𝟙 (schemeChart Z).scheme))
    obtain ⟨r, hr₁, hr₂⟩ := (StackChart.crossRel_iff _ _ P).mp h
    obtain ⟨s, hs₁, hs₂⟩ :=
      (StackChart.crossRel_iff _ _ P).mp (StackChart.crossRel_refl hAr x)
    have hiso : IsIso P.fst := (schemeChartPullbackPresentationIso Z _ _ P).isIso_hom
    have hrs : r = s := P.fst.homeomorph.injective (hr₁.trans hs₁.symm)
    rw [← hr₂, hrs, hs₂]
  · rintro rfl
    exact StackChart.crossRel_refl hAr x

/-- **The point space of the identity chart of a scheme is the scheme itself.** -/
noncomputable def schemeChartPointHomeo : (schemeChart Z).pointSpace ≃ₜ Z :=
  homeomorphOfIsQuotientMap (StackChart.isQuotientMap_pointMap _) IsQuotientMap.id
    (fun x y ↦ by
      rw [StackChart.pointMap_eq_iff (StackChart.isRepresentable_of_smoothSurjective
        (schemeChart_isSmoothSurjective Z)), schemeChart_crossRel_iff]
      exact Iff.rfl)

/-- **The underlying topological space of the stack represented by a scheme is the scheme.** -/
noncomputable def underlyingStackPointHomeoScheme :
    UnderlyingStackPoint (ofSchemeAlgebraicStack Z) ≃ₜ Z :=
  ((ofSchemeAlgebraicStack Z).pointSpaceHomeo (schemeChart Z)
    (schemeChart_isSmoothSurjective Z)).symm.trans (schemeChartPointHomeo Z)

end FppfStack

end GromovWitten.AlgebraicGeometry
