/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.Algebra.FlatDescentAlgebra
import GromovWitten.AlgebraicGeometry.Stacks.TorsorStack

/-!
# Effective descent of affine schemes along a faithfully flat cover of an affine base

Let `A → B` be a ring homomorphism, `S = Spec A`, `S' = Spec B`, and let `F` be an fppf sheaf
over `S` (structure morphism `π : F ⟶ y S`, `y = fppfYoneda`).  Suppose that the base change
`F ×_S S'` is identified, over `S'`, with `y (Spec M)` for a `B`-algebra `M`
(`AffineDescentInput`).  This file shows that `F` is then itself represented by an affine scheme
`Spec C` over `S`, when `B` is faithfully flat and of finite presentation over `A`
(Stacks Project, Tag 0245).

The proof is organised around the round-25 cocycle-form descent of algebras
(`GromovWitten.Algebra.AlgDescentDatum`, `Algebra/FlatDescentAlgebra.lean`).  A morphism
`T ⟶ Spec M` is the same as a section of `F` over `T` (`point`) together with a morphism
`T ⟶ Spec B` lying over the same morphism to `S` (`hom_ext_point`, `pointLift`).  The coaction
`τ : M → B ⊗[A] M` is the ring homomorphism of the morphism `Spec (B ⊗[A] M) ⟶ Spec M` which has
the section of `F` of `m ↦ 1 ⊗ m` and lies over `b ↦ b ⊗ 1` (`coact`); the cocycle condition and
the bijectivity of the associated map `M ⊗[A] B → B ⊗[A] M` both follow because a morphism to
`Spec M` is determined by its section of `F` and its morphism to `Spec B`.  The descended algebra
`C = {m | τ m = 1 ⊗ m}` is then `descended`, and the comparison morphism `F ⟶ y (Spec C)` is
glued (`RelHomFamily.glue`) along the fppf covering sieve generated by `S' ⟶ S`.

## Main results

* `AffineDescentInput` : the input data `(M, θ, θ_over)`.
* `AffineDescentInput.descentDatum` : the algebra descent datum on `M` (no flatness needed).
* `AffineDescentInput.descended` : the descended `A`-subalgebra `C` of `M`.
* `AffineDescentInput.descended_tensor` : for `B` flat over `A`, `B ⊗[A] C ≅ M`.
* `AffineDescentInput.toSpec` : the comparison morphism `F ⟶ y (Spec C)`, for `B` faithfully
  flat and of finite presentation over `A`; `AffineDescentInput.toSpec_comp` : it lies over `S`.
* `AffineDescentInput.isIso_toSpec` : the comparison morphism is an isomorphism.
* `AffineDescentInput.etale_descended`, `AffineDescentInput.finite_descended` : étaleness and
  finiteness of `M` over `B` descend to `C` over `A` (for `B` faithfully flat over `A`).
* `fppfSheaf_isIso_of_bijective` : a morphism of fppf sheaves which is bijective on sections over
  every scheme is an isomorphism.
-/

open CategoryTheory CategoryTheory.Limits
open _root_.AlgebraicGeometry
open GromovWitten.Algebra
open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

universe u

/-- A morphism of fppf sheaves which induces a bijection on sections over every scheme (in the
form of morphisms out of representable sheaves) is an isomorphism.  This is the absolute
analogue of `SheafGluing.isIso_of_sections` (`Stacks/SheafGluing.lean`), which works over a base
and along a covering sieve. -/
theorem fppfSheaf_isIso_of_bijective {P Q : FppfSheaf.{u}} (ψ : P ⟶ Q)
    (h : ∀ T : Scheme.{u}, Function.Bijective fun α : fppfYoneda.obj T ⟶ P ↦ α ≫ ψ) :
    IsIso ψ := by
  have happ : ∀ T : Scheme.{u}ᵒᵖ, IsIso (((sheafToPresheaf fppfJ (Type u)).map ψ).app T) := by
    intro T
    obtain ⟨T⟩ := T
    change IsIso (ψ.hom.app _)
    rw [isIso_iff_bijective]
    have : ⇑(ψ.hom.app (Opposite.op T)) =
        fppfJ.yonedaEquiv ∘ (fun α ↦ α ≫ ψ) ∘ fppfJ.yonedaEquiv.symm := by
      funext a
      simp only [Function.comp, fppfJ.yonedaEquiv_comp, Equiv.apply_symm_apply]
    rw [this]
    exact fppfJ.yonedaEquiv.bijective.comp ((h T).comp fppfJ.yonedaEquiv.symm.bijective)
  have : IsIso ((sheafToPresheaf fppfJ (Type u)).map ψ) := NatIso.isIso_of_isIso_app _
  exact (fullyFaithfulSheafToPresheaf fppfJ (Type u)).isIso_of_isIso_map ψ

/-- The input of effective descent of an affine scheme along `Spec B ⟶ Spec A`: an fppf sheaf
`F` over `S = Spec A` (structure morphism `π`) together with a `B`-algebra `M` and an isomorphism
`θ : F ×_S Spec B ≅ Spec M` over `Spec B`.  Here `F ×_S Spec B` is the sheaf pullback
`pullback π (fppfYoneda.map (Spec B ⟶ Spec A))`, as in `Stacks/TorsorStack.lean`.  No flatness
is assumed in the structure itself. -/
structure AffineDescentInput (A B : Type u) [CommRing A] [CommRing B] [Algebra A B]
    (F : FppfSheaf.{u}) (π : F ⟶ fppfYoneda.obj (Spec (CommRingCat.of A))) where
  /-- The coordinate ring of the base change `F ×_S S'`. -/
  M : Type u
  [commRing : CommRing M]
  [algebra : Algebra B M]
  /-- The `A`-algebra structure on `M`, compatible with `A → B → M`. -/
  [algebraBase : Algebra A M]
  /-- The scalar tower `A → B → M`. -/
  [isScalarTower : IsScalarTower A B M]
  /-- The identification of `F ×_S S'` with `Spec M`. -/
  θ : Limits.pullback π (fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A B)))) ≅
        fppfYoneda.obj (Spec (CommRingCat.of M))
  /-- `θ` lies over `S' = Spec B`. -/
  θ_over : θ.hom ≫ fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap B M))) =
        Limits.pullback.snd _ _

namespace AffineDescentInput

attribute [instance] commRing algebra algebraBase isScalarTower

variable {A B : Type u} [CommRing A] [CommRing B] [Algebra A B] {F : FppfSheaf.{u}}
  {π : F ⟶ fppfYoneda.obj (Spec (CommRingCat.of A))} (D : AffineDescentInput A B F π)

omit [Algebra A B] in
/-- `Spec` of a composite of ring homomorphisms. -/
private lemma specMap_comp {R₁ R₂ R₃ : Type u} [CommRing R₁] [CommRing R₂] [CommRing R₃]
    (u : R₂ →+* R₃) (v : R₁ →+* R₂) :
    Spec.map (CommRingCat.ofHom (u.comp v)) =
      Spec.map (CommRingCat.ofHom u) ≫ Spec.map (CommRingCat.ofHom v) := by
  rw [CommRingCat.ofHom_comp, Spec.map_comp]

omit [Algebra A B] in
/-- `Spec` is faithful on ring homomorphisms given by `CommRingCat.ofHom`. -/
private lemma ringHom_eq_of_specMap {R₁ R₂ : Type u} [CommRing R₁] [CommRing R₂] {u v : R₁ →+* R₂}
    (h : Spec.map (CommRingCat.ofHom u) = Spec.map (CommRingCat.ofHom v)) : u = v :=
  congrArg CommRingCat.Hom.hom (Spec.map_injective h)

/-! ### Points of `Spec M` as points of `F` over `Spec B` -/

/-- The section of `F` over `T` underlying a morphism `T ⟶ Spec M`, through `θ` and the first
projection `F ×_S S' ⟶ F`. -/
noncomputable def point {T : Scheme.{u}} (g : T ⟶ Spec (CommRingCat.of D.M)) :
    fppfYoneda.obj T ⟶ F :=
  fppfYoneda.map g ≫ D.θ.inv ≫ pullback.fst _ _

/-- `θ⁻¹` followed by the projection to `Spec B` is the structure morphism of `Spec M`. -/
lemma θ_inv_snd : D.θ.inv ≫ pullback.snd _ _ =
    fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap B D.M))) := by
  rw [← D.θ_over, Iso.inv_hom_id_assoc]

/-- `point` is natural in the test scheme. -/
lemma point_comp {T T' : Scheme.{u}} (k : T' ⟶ T) (g : T ⟶ Spec (CommRingCat.of D.M)) :
    D.point (k ≫ g) = fppfYoneda.map k ≫ D.point g := by
  simp [point, Functor.map_comp]

/-- The section `point g` lies over `Spec A` through `g` and `Spec M ⟶ Spec B ⟶ Spec A`. -/
lemma point_π {T : Scheme.{u}} (g : T ⟶ Spec (CommRingCat.of D.M)) :
    D.point g ≫ π = fppfYoneda.map (g ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) ≫
      Spec.map (CommRingCat.ofHom (algebraMap A B))) := by
  rw [point, Category.assoc, Category.assoc, pullback.condition, ← Category.assoc D.θ.inv,
    θ_inv_snd]
  simp [Functor.map_comp]

/-- A morphism to `Spec M` is determined by its section of `F` and its morphism to `Spec B`. -/
lemma hom_ext_point {T : Scheme.{u}} {g g' : T ⟶ Spec (CommRingCat.of D.M)}
    (h₁ : D.point g = D.point g')
    (h₂ : g ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) =
      g' ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M))) : g = g' := by
  apply fppfYoneda.map_injective
  rw [← cancel_mono D.θ.inv]
  apply pullback.hom_ext
  · simpa [point] using h₁
  · rw [Category.assoc, Category.assoc, θ_inv_snd, ← Functor.map_comp, ← Functor.map_comp, h₂]

/-- The morphism `T ⟶ Spec M` with prescribed section of `F` and morphism to `Spec B`. -/
noncomputable def pointLift {T : Scheme.{u}} (x : fppfYoneda.obj T ⟶ F)
    (h : T ⟶ Spec (CommRingCat.of B))
    (w : x ≫ π = fppfYoneda.map (h ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)))) :
    T ⟶ Spec (CommRingCat.of D.M) :=
  fppfYoneda.preimage
    (pullback.lift x (fppfYoneda.map h) (by rw [w, Functor.map_comp]) ≫ D.θ.hom)

/-- `pointLift x h w` has section `x`. -/
lemma point_pointLift {T : Scheme.{u}} (x : fppfYoneda.obj T ⟶ F)
    (h : T ⟶ Spec (CommRingCat.of B))
    (w : x ≫ π = fppfYoneda.map (h ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)))) :
    D.point (D.pointLift x h w) = x := by
  simp only [point, pointLift, Functor.map_preimage, Category.assoc, Iso.hom_inv_id_assoc]
  exact pullback.lift_fst _ _ _

/-- `pointLift x h w` lies over `h`. -/
lemma pointLift_comp {T : Scheme.{u}} (x : fppfYoneda.obj T ⟶ F)
    (h : T ⟶ Spec (CommRingCat.of B))
    (w : x ≫ π = fppfYoneda.map (h ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)))) :
    D.pointLift x h w ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) = h := by
  apply fppfYoneda.map_injective
  simp only [pointLift, Functor.map_comp, Functor.map_preimage, Category.assoc, D.θ_over]
  exact pullback.lift_snd _ _ _

/-! ### Ring-level transport -/

section Ring

variable {R : Type u} [CommRing R]

/-- Transport of a ring homomorphism `u : M → R` to the one with the same section of `F` and
the prescribed restriction `v` to `B`. -/
noncomputable def transport (u : D.M →+* R) (v : B →+* R)
    (huv : u.comp (algebraMap A D.M) = v.comp (algebraMap A B)) : D.M →+* R :=
  (Spec.preimage (D.pointLift (D.point (Spec.map (CommRingCat.ofHom u)))
    (Spec.map (CommRingCat.ofHom v)) (by
      rw [point_π, ← specMap_comp, ← specMap_comp, ← specMap_comp,
        ← IsScalarTower.algebraMap_eq, huv]))).hom

/-- `Spec` of `transport u v huv` is the corresponding `pointLift`. -/
lemma specMap_transport (u : D.M →+* R) (v : B →+* R)
    (huv : u.comp (algebraMap A D.M) = v.comp (algebraMap A B)) :
    Spec.map (CommRingCat.ofHom (D.transport u v huv)) =
      D.pointLift (D.point (Spec.map (CommRingCat.ofHom u)))
        (Spec.map (CommRingCat.ofHom v)) (by
          rw [point_π, ← specMap_comp, ← specMap_comp, ← specMap_comp,
            ← IsScalarTower.algebraMap_eq, huv]) := by
  simp [transport]

/-- `transport u v huv` has the same section of `F` as `u`. -/
lemma point_transport (u : D.M →+* R) (v : B →+* R)
    (huv : u.comp (algebraMap A D.M) = v.comp (algebraMap A B)) :
    D.point (Spec.map (CommRingCat.ofHom (D.transport u v huv))) =
      D.point (Spec.map (CommRingCat.ofHom u)) := by
  rw [specMap_transport, point_pointLift]

/-- `transport u v huv` restricts to `v` on `B`. -/
lemma transport_comp (u : D.M →+* R) (v : B →+* R)
    (huv : u.comp (algebraMap A D.M) = v.comp (algebraMap A B)) :
    (D.transport u v huv).comp (algebraMap B D.M) = v := by
  apply ringHom_eq_of_specMap
  rw [specMap_comp, specMap_transport, pointLift_comp]

/-- A ring homomorphism `M → R` is determined by its section of `F` and its restriction to `B`. -/
lemma ringHom_ext {u u' : D.M →+* R}
    (h₁ : D.point (Spec.map (CommRingCat.ofHom u)) = D.point (Spec.map (CommRingCat.ofHom u')))
    (h₂ : u.comp (algebraMap B D.M) = u'.comp (algebraMap B D.M)) : u = u' := by
  apply ringHom_eq_of_specMap
  apply D.hom_ext_point h₁
  rw [← specMap_comp, ← specMap_comp, h₂]

/-- The section of `F` attached to a composite ring homomorphism. -/
lemma point_specMap_comp {R' : Type u} [CommRing R'] (w : R →+* R') (u : D.M →+* R) :
    D.point (Spec.map (CommRingCat.ofHom (w.comp u))) =
      fppfYoneda.map (Spec.map (CommRingCat.ofHom w)) ≫
        D.point (Spec.map (CommRingCat.ofHom u)) := by
  rw [specMap_comp, point_comp]

/-- Postcomposition with `w` commutes with transport, on sections of `F`. -/
lemma point_comp_transport {R' : Type u} [CommRing R'] (w : R →+* R') (u : D.M →+* R)
    (v : B →+* R) (huv : u.comp (algebraMap A D.M) = v.comp (algebraMap A B)) :
    D.point (Spec.map (CommRingCat.ofHom (w.comp (D.transport u v huv)))) =
      D.point (Spec.map (CommRingCat.ofHom (w.comp u))) := by
  rw [point_specMap_comp, point_transport, point_specMap_comp]

end Ring

/-! ### The coactions and the isomorphism `φ : M ⊗[A] B ≃ B ⊗[A] M` -/

/-- `m ↦ 1 ⊗ m` and `b ↦ b ⊗ 1` agree on `A`. -/
lemma includeRight_comp_algebraMap :
    ((Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) : D.M →+* B ⊗[A] D.M).comp
        (algebraMap A D.M) =
      Algebra.TensorProduct.includeLeftRingHom.comp (algebraMap A B) := by
  ext a
  change (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) (algebraMap A D.M a) = _
  rw [AlgHom.commutes, Algebra.TensorProduct.algebraMap_apply]
  rfl

/-- `m ↦ m ⊗ 1` and `b ↦ 1 ⊗ b` agree on `A`. -/
lemma includeLeft_comp_algebraMap :
    (Algebra.TensorProduct.includeLeftRingHom : D.M →+* D.M ⊗[A] B).comp (algebraMap A D.M) =
      ((Algebra.TensorProduct.includeRight : B →ₐ[A] D.M ⊗[A] B) : B →+* D.M ⊗[A] B).comp
        (algebraMap A B) := by
  ext a
  change _ = (Algebra.TensorProduct.includeRight : B →ₐ[A] D.M ⊗[A] B) (algebraMap A B a)
  rw [AlgHom.commutes, Algebra.TensorProduct.algebraMap_apply]
  rfl

/-- The coaction `τ : M → B ⊗[A] M`, as a ring homomorphism: the morphism
`Spec (B ⊗[A] M) ⟶ Spec M` with the section of `F` of `m ↦ 1 ⊗ m` and lying over
`b ↦ b ⊗ 1`. -/
noncomputable def coact : D.M →+* B ⊗[A] D.M :=
  D.transport (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M)
    Algebra.TensorProduct.includeLeftRingHom D.includeRight_comp_algebraMap

/-- The inverse coaction `τ' : M → M ⊗[A] B`, as a ring homomorphism. -/
noncomputable def coact' : D.M →+* D.M ⊗[A] B :=
  D.transport Algebra.TensorProduct.includeLeftRingHom
    (Algebra.TensorProduct.includeRight : B →ₐ[A] D.M ⊗[A] B) D.includeLeft_comp_algebraMap

/-- The coaction restricts to `b ↦ b ⊗ 1` on `B`. -/
lemma coact_algebraMap (b : B) : D.coact (algebraMap B D.M b) = b ⊗ₜ[A] (1 : D.M) := by
  have := D.transport_comp _ _ D.includeRight_comp_algebraMap
  exact (RingHom.congr_fun this b).trans rfl

/-- The inverse coaction restricts to `b ↦ 1 ⊗ b` on `B`. -/
lemma coact'_algebraMap (b : B) : D.coact' (algebraMap B D.M b) = (1 : D.M) ⊗ₜ[A] b := by
  have := D.transport_comp _ _ D.includeLeft_comp_algebraMap
  exact (RingHom.congr_fun this b).trans rfl

/-- After any ring homomorphism, the coaction has the section of `F` of `m ↦ 1 ⊗ m`. -/
lemma point_comp_coact {R : Type u} [CommRing R] (w : B ⊗[A] D.M →+* R) :
    D.point (Spec.map (CommRingCat.ofHom (w.comp D.coact))) =
      D.point (Spec.map (CommRingCat.ofHom
        (w.comp (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M)))) :=
  D.point_comp_transport _ _ _ _

/-- After any ring homomorphism, the inverse coaction has the section of `F` of
`m ↦ m ⊗ 1`. -/
lemma point_comp_coact' {R : Type u} [CommRing R] (w : D.M ⊗[A] B →+* R) :
    D.point (Spec.map (CommRingCat.ofHom (w.comp D.coact'))) =
      D.point (Spec.map (CommRingCat.ofHom (w.comp Algebra.TensorProduct.includeLeftRingHom))) :=
  D.point_comp_transport _ _ _ _

/-- The coaction as an `A`-algebra homomorphism. -/
noncomputable def coactAlgHom : D.M →ₐ[A] B ⊗[A] D.M :=
  { D.coact with
    commutes' := fun a ↦ by
      change D.coact (algebraMap A D.M a) = _
      rw [IsScalarTower.algebraMap_apply A B D.M]
      rw [coact_algebraMap, Algebra.TensorProduct.algebraMap_apply] }

/-- The inverse coaction as an `A`-algebra homomorphism. -/
noncomputable def coactAlgHom' : D.M →ₐ[A] D.M ⊗[A] B :=
  { D.coact' with
    commutes' := fun a ↦ by
      change D.coact' (algebraMap A D.M a) = _
      rw [IsScalarTower.algebraMap_apply A B D.M]
      rw [coact'_algebraMap]
      exact (Algebra.TensorProduct.includeRight : B →ₐ[A] D.M ⊗[A] B).commutes a }

/-- `coactAlgHom` is `coact`. -/
@[simp] lemma coactAlgHom_apply (m : D.M) : D.coactAlgHom m = D.coact m := rfl

/-- `coactAlgHom'` is `coact'`. -/
@[simp] lemma coactAlgHom'_apply (m : D.M) : D.coactAlgHom' m = D.coact' m := rfl

/-- The isomorphism `φ : M ⊗[A] B → B ⊗[A] M`, `m ⊗ b ↦ τ m * (1 ⊗ b)`. -/
noncomputable def phi : D.M ⊗[A] B →ₐ[A] B ⊗[A] D.M :=
  Algebra.TensorProduct.lift D.coactAlgHom
    ((Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M).comp
      (IsScalarTower.toAlgHom A B D.M)) (fun _ _ ↦ Commute.all _ _)

/-- The inverse `ψ : B ⊗[A] M → M ⊗[A] B`, `b ⊗ m ↦ (b ⊗ 1) * τ' m`. -/
noncomputable def psi : B ⊗[A] D.M →ₐ[A] D.M ⊗[A] B :=
  Algebra.TensorProduct.lift
    ((Algebra.TensorProduct.includeLeft (S := A) : D.M →ₐ[A] D.M ⊗[A] B).comp
      (IsScalarTower.toAlgHom A B D.M)) D.coactAlgHom' (fun _ _ ↦ Commute.all _ _)

/-- The value of `phi` on pure tensors. -/
@[simp] lemma phi_tmul (m : D.M) (b : B) :
    D.phi (m ⊗ₜ[A] b) = D.coact m * ((1 : B) ⊗ₜ[A] algebraMap B D.M b) := by
  simp [phi]

/-- The value of `psi` on pure tensors. -/
@[simp] lemma psi_tmul (b : B) (m : D.M) :
    D.psi (b ⊗ₜ[A] m) = (algebraMap B D.M b ⊗ₜ[A] (1 : B)) * D.coact' m := by
  simp [psi]

/-- `φ ∘ τ' = (m ↦ 1 ⊗ m)`. -/
lemma phi_comp_coact' :
    (D.phi : D.M ⊗[A] B →+* B ⊗[A] D.M).comp D.coact' =
      (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) := by
  apply D.ringHom_ext
  · rw [point_comp_coact']
    have : (D.phi : D.M ⊗[A] B →+* B ⊗[A] D.M).comp Algebra.TensorProduct.includeLeftRingHom =
        D.coact := by
      ext m; simp [← Algebra.TensorProduct.one_def]
    rw [this]
    exact D.point_transport _ _ _
  · ext b
    simp [coact'_algebraMap]

/-- `ψ ∘ τ = (m ↦ m ⊗ 1)`. -/
lemma psi_comp_coact :
    (D.psi : B ⊗[A] D.M →+* D.M ⊗[A] B).comp D.coact =
      Algebra.TensorProduct.includeLeftRingHom := by
  apply D.ringHom_ext
  · rw [point_comp_coact]
    have : (D.psi : B ⊗[A] D.M →+* D.M ⊗[A] B).comp
        (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) = D.coact' := by
      ext m; simp [← Algebra.TensorProduct.one_def]
    rw [this]
    exact D.point_transport _ _ _
  · ext b
    simp [coact_algebraMap]

/-- Pointwise form of `phi_comp_coact'`. -/
lemma phi_coact' (m : D.M) : D.phi (D.coact' m) = (1 : B) ⊗ₜ[A] m :=
  RingHom.congr_fun D.phi_comp_coact' m

/-- Pointwise form of `psi_comp_coact`. -/
lemma psi_coact (m : D.M) : D.psi (D.coact m) = m ⊗ₜ[A] (1 : B) :=
  RingHom.congr_fun D.psi_comp_coact m

/-- `ψ` is a left inverse of `φ`. -/
lemma psi_phi (x : D.M ⊗[A] B) : D.psi (D.phi x) = x := by
  have : D.psi.comp D.phi = AlgHom.id A _ := by
    apply Algebra.TensorProduct.ext'
    intro m b
    simp [psi_coact, coact'_algebraMap, Algebra.TensorProduct.tmul_mul_tmul]
  exact AlgHom.congr_fun this x

/-- `ψ` is a right inverse of `φ`. -/
lemma phi_psi (x : B ⊗[A] D.M) : D.phi (D.psi x) = x := by
  have : D.phi.comp D.psi = AlgHom.id A _ := by
    apply Algebra.TensorProduct.ext'
    intro b m
    simp [phi_coact', coact_algebraMap, Algebra.TensorProduct.tmul_mul_tmul]
  exact AlgHom.congr_fun this x

/-! ### The descent datum -/

/-- The coaction is semilinear for the left `B`-action. -/
lemma coact_smul (b : B) (m : D.M) : D.coact (b • m) = b • D.coact m := by
  rw [Algebra.smul_def, map_mul, coact_algebraMap]
  induction D.coact m using TensorProduct.induction_on with
  | zero => simp
  | tmul b' m' => simp [Algebra.TensorProduct.tmul_mul_tmul, TensorProduct.smul_tmul']
  | add x y hx hy => rw [mul_add, smul_add, hx, hy]

/-- The right `B`-action on `B ⊗[A] M` is multiplication by `1 ⊗ b`. -/
lemma descentRightSmul_eq (b : B) (x : B ⊗[A] D.M) :
    descentRightSmul A B D.M b x = x * ((1 : B) ⊗ₜ[A] algebraMap B D.M b) := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul b' m' =>
    rw [descentRightSmul_tmul, Algebra.TensorProduct.tmul_mul_tmul, mul_one, Algebra.smul_def,
      mul_comm]
  | add x y hx hy => rw [map_add, hx, hy, add_mul]

/-- The map `descentToPhi` of the coaction is `φ`. -/
lemma descentToPhi_eq (x : D.M ⊗[A] B) :
    descentToPhi A B D.M D.coactAlgHom.toLinearMap x = D.phi x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul m b => rw [descentToPhi_tmul, descentRightSmul_eq, phi_tmul]; rfl
  | add x y hx hy => rw [map_add, map_add, hx, hy]

/-- The map `B ⊗[A] M → B ⊗[A] (B ⊗[A] M)`, `b ⊗ m ↦ b ⊗ τ m`. -/
noncomputable def coactLeft : B ⊗[A] D.M →ₐ[A] B ⊗[A] (B ⊗[A] D.M) :=
  Algebra.TensorProduct.map (AlgHom.id A B) D.coactAlgHom

/-- The cocycle condition for the coaction, as an equality of ring homomorphisms
`M → B ⊗[A] (B ⊗[A] M)`: both sides are morphisms to `Spec M` with the same section of `F`
and the same morphism to `Spec B`. -/
lemma coact_cocycle_ringHom :
    (D.coactLeft : B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp D.coact =
      (AlgDescentDatum.algCanonicalMap A B D.M : B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp
        D.coact := by
  apply D.ringHom_ext
  · rw [point_comp_coact, point_comp_coact]
    have h1 : (D.coactLeft : B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp
        (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) =
        ((Algebra.TensorProduct.includeRight : B ⊗[A] D.M →ₐ[A] B ⊗[A] (B ⊗[A] D.M)) :
          B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp D.coact := by
      ext m; simp [coactLeft]
    have h2 : (AlgDescentDatum.algCanonicalMap A B D.M :
        B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp
        (Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) =
        ((Algebra.TensorProduct.includeRight : B ⊗[A] D.M →ₐ[A] B ⊗[A] (B ⊗[A] D.M)) :
          B ⊗[A] D.M →+* B ⊗[A] (B ⊗[A] D.M)).comp
          ((Algebra.TensorProduct.includeRight : D.M →ₐ[A] B ⊗[A] D.M) :
            D.M →+* B ⊗[A] D.M) := by
      ext m; simp [AlgDescentDatum.algCanonicalMap]
    rw [h1, h2, point_comp_coact]
  · ext b
    simp [coact_algebraMap, coactLeft, AlgDescentDatum.algCanonicalMap,
      ← Algebra.TensorProduct.one_def]

/-- The cocycle condition for the coaction, in the form of `DescentDatum.cocycle`. -/
lemma coact_cocycle (m : D.M) :
    LinearMap.lTensor B D.coactAlgHom.toLinearMap (D.coactAlgHom m) =
      TensorProduct.assoc A B B D.M
        (LinearMap.rTensor D.M (descentInsLeft A B) (D.coactAlgHom m)) := by
  have hl : ∀ x : B ⊗[A] D.M,
      LinearMap.lTensor B D.coactAlgHom.toLinearMap x = D.coactLeft x := by
    intro x
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul b m => simp [coactLeft]
    | add x y hx hy => rw [map_add, map_add, hx, hy]
  have hr : ∀ x : B ⊗[A] D.M,
      TensorProduct.assoc A B B D.M (LinearMap.rTensor D.M (descentInsLeft A B) x) =
        AlgDescentDatum.algCanonicalMap A B D.M x := by
    intro x
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul b m => simp [AlgDescentDatum.algCanonicalMap, descentInsLeft_apply]
    | add x y hx hy => rw [map_add, map_add, map_add, hx, hy]
  rw [hl, hr]
  exact RingHom.congr_fun D.coact_cocycle_ringHom m

/-- The algebra descent datum on `M` (in `τ`-form, `Algebra/FlatDescentAlgebra.lean`) attached to
the identification `θ : F ×_S Spec B ≅ Spec M`: its coaction `τ : M → B ⊗[A] M` is the ring
homomorphism of the morphism `Spec (B ⊗[A] M) ⟶ Spec M` whose section of `F` is that of
`m ↦ 1 ⊗ m` and which lies over `b ↦ b ⊗ 1`.  No flatness is needed. -/
noncomputable def descentDatum : AlgDescentDatum A B D.M where
  τ := D.coactAlgHom.toLinearMap
  τ_smul := D.coact_smul
  cocycle := D.coact_cocycle
  bijective := by
    have : ⇑(descentToPhi A B D.M D.coactAlgHom.toLinearMap) = ⇑D.phi :=
      funext D.descentToPhi_eq
    rw [this]
    exact Function.bijective_iff_has_inverse.mpr ⟨D.psi, D.psi_phi, D.phi_psi⟩
  τₐ := D.coactAlgHom
  τ_eq := rfl

/-- The descended `A`-subalgebra `C = {m | τ m = 1 ⊗ m}` of `M`
(`AlgDescentDatum.descendedAlgebra` of `descentDatum`). -/
noncomputable abbrev descended : Subalgebra A D.M := D.descentDatum.descendedAlgebra

/-- An element of `C` is fixed by the coaction. -/
lemma coact_of_mem {c : D.M} (hc : c ∈ D.descended) : D.coact c = (1 : B) ⊗ₜ[A] c := hc

/-- An element `c` of `C` satisfies `τ' c = c ⊗ 1`. -/
lemma coact'_of_mem {c : D.M} (hc : c ∈ D.descended) : D.coact' c = c ⊗ₜ[A] (1 : B) := by
  have h := D.psi_tmul 1 c
  rw [map_one, ← Algebra.TensorProduct.one_def, one_mul, ← D.coact_of_mem hc, psi_coact] at h
  exact h.symm

/-- The inclusion `C → M` as a ring homomorphism. -/
noncomputable abbrev descendedVal : D.descended →+* D.M := D.descended.val.toRingHom

/-- `τ'` and `m ↦ m ⊗ 1` agree on `C`. -/
lemma coact'_comp_descendedVal :
    D.coact'.comp D.descendedVal =
      (Algebra.TensorProduct.includeLeftRingHom : D.M →+* D.M ⊗[A] B).comp D.descendedVal := by
  ext c
  exact D.coact'_of_mem c.2

/-- `Spec M ⟶ Spec A` factors through `Spec B`. -/
lemma specMap_algebraMap_base :
    Spec.map (CommRingCat.ofHom (algebraMap A D.M)) =
      Spec.map (CommRingCat.ofHom (algebraMap B D.M)) ≫
        Spec.map (CommRingCat.ofHom (algebraMap A B)) :=
  by rw [← specMap_comp, ← IsScalarTower.algebraMap_eq]

/-- Two morphisms to `Spec M` with the same section of `F` have the same composite with
`Spec M ⟶ Spec C`. -/
lemma comp_specMap_descendedVal {T : Scheme.{u}} {G G' : T ⟶ Spec (CommRingCat.of D.M)}
    (h : D.point G = D.point G') :
    G ≫ Spec.map (CommRingCat.ofHom D.descendedVal) =
      G' ≫ Spec.map (CommRingCat.ofHom D.descendedVal) := by
  have hw : G ≫ Spec.map (CommRingCat.ofHom (algebraMap A D.M)) =
      (G' ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M))) ≫
        Spec.map (CommRingCat.ofHom (algebraMap A B)) := by
    apply fppfYoneda.map_injective
    rw [specMap_algebraMap_base, Category.assoc, ← D.point_π, ← D.point_π, h]
  let k : T ⟶ Spec (CommRingCat.of (D.M ⊗[A] B)) :=
    pullback.lift G _ hw ≫ (pullbackSpecIso A D.M B).hom
  have hk₁ : k ≫ Spec.map (CommRingCat.ofHom Algebra.TensorProduct.includeLeftRingHom) = G := by
    simp only [k, Category.assoc, pullbackSpecIso_hom_fst]
    exact pullback.lift_fst _ _ _
  have hk₂ : k ≫ Spec.map (CommRingCat.ofHom
      ((Algebra.TensorProduct.includeRight : B →ₐ[A] D.M ⊗[A] B) : B →+* D.M ⊗[A] B)) =
      G' ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) := by
    simp only [k, Category.assoc, pullbackSpecIso_hom_snd]
    exact pullback.lift_snd _ _ _
  have hG' : G' = k ≫ Spec.map (CommRingCat.ofHom D.coact') := by
    apply D.hom_ext_point
    · rw [point_comp, coact', point_transport, ← point_comp, hk₁, h]
    · rw [Category.assoc, ← specMap_comp, coact', transport_comp, hk₂]
  rw [hG', Category.assoc, ← specMap_comp, coact'_comp_descendedVal, specMap_comp,
    ← Category.assoc, hk₁]

/-! ### The descended algebra recovers `M` (flat case) -/

section Flat

variable [Module.Flat A B]

/-- The descent isomorphism `e : B ⊗[A] C ≃ₐ[B] M`, `b ⊗ c ↦ b • c`, for `B` flat over `A`
(round 25, `AlgDescentDatum.descentAlgEquiv`). -/
noncomputable abbrev descentEquiv : B ⊗[A] D.descended ≃ₐ[B] D.M :=
  D.descentDatum.descentAlgEquiv

/-- `e` restricts to the structure map on `B`. -/
lemma descentEquiv_comp_includeLeft :
    (D.descentEquiv : B ⊗[A] D.descended →+* D.M).comp Algebra.TensorProduct.includeLeftRingHom =
      algebraMap B D.M := by
  ext b
  simp [AlgDescentDatum.descentAlgEquiv_tmul, Algebra.algebraMap_eq_smul_one]

/-- `e` restricts to the inclusion on `C`. -/
lemma descentEquiv_comp_includeRight :
    (D.descentEquiv : B ⊗[A] D.descended →+* D.M).comp
      ((Algebra.TensorProduct.includeRight : D.descended →ₐ[A] B ⊗[A] D.descended) :
        D.descended →+* B ⊗[A] D.descended) = D.descendedVal := by
  ext c
  simp [AlgDescentDatum.descentAlgEquiv_tmul]

/-- `e⁻¹` sends `b • 1` to `b ⊗ 1`. -/
lemma descentEquiv_symm_comp_algebraMap :
    (D.descentEquiv.symm : D.M →+* B ⊗[A] D.descended).comp (algebraMap B D.M) =
      Algebra.TensorProduct.includeLeftRingHom := by
  ext b
  apply D.descentEquiv.injective
  simp [(RingHom.congr_fun D.descentEquiv_comp_includeLeft b).symm]

/-- `e⁻¹` sends `c ∈ C` to `1 ⊗ c`. -/
lemma descentEquiv_symm_comp_descendedVal :
    (D.descentEquiv.symm : D.M →+* B ⊗[A] D.descended).comp D.descendedVal =
      ((Algebra.TensorProduct.includeRight : D.descended →ₐ[A] B ⊗[A] D.descended) :
        D.descended →+* B ⊗[A] D.descended) := by
  ext c
  apply D.descentEquiv.injective
  simp

/-- A morphism to `Spec M` is determined by its composites with `Spec M ⟶ Spec B` and
`Spec M ⟶ Spec C`. -/
lemma hom_ext_descended {T : Scheme.{u}} {G₁ G₂ : T ⟶ Spec (CommRingCat.of D.M)}
    (h₁ : G₁ ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) =
      G₂ ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)))
    (h₂ : G₁ ≫ Spec.map (CommRingCat.ofHom D.descendedVal) =
      G₂ ≫ Spec.map (CommRingCat.ofHom D.descendedVal)) : G₁ = G₂ := by
  have hid : ∀ G : T ⟶ Spec (CommRingCat.of D.M),
      G = (G ≫ Spec.map (CommRingCat.ofHom (D.descentEquiv : B ⊗[A] D.descended →+* D.M))) ≫
        Spec.map (CommRingCat.ofHom (D.descentEquiv.symm : D.M →+* B ⊗[A] D.descended)) := by
    intro G
    have : (D.descentEquiv : B ⊗[A] D.descended →+* D.M).comp
        (D.descentEquiv.symm : D.M →+* B ⊗[A] D.descended) = RingHom.id D.M := by
      ext m; simp
    rw [Category.assoc, ← specMap_comp, this, CommRingCat.ofHom_id, Spec.map_id,
      Category.comp_id]
  rw [hid G₁, hid G₂]
  congr 1
  rw [← Category.comp_id (G₁ ≫ _), ← Category.comp_id (G₂ ≫ _),
    ← (pullbackSpecIso A B D.descended).inv_hom_id, ← Category.assoc, ← Category.assoc]
  congr 1
  apply pullback.hom_ext
  · rw [Category.assoc, Category.assoc, pullbackSpecIso_inv_fst, Category.assoc,
      Category.assoc, pullbackSpecIso_inv_fst, ← specMap_comp, descentEquiv_comp_includeLeft, h₁]
  · rw [Category.assoc, Category.assoc, pullbackSpecIso_inv_snd, Category.assoc,
      Category.assoc, pullbackSpecIso_inv_snd, ← specMap_comp, descentEquiv_comp_includeRight, h₂]

/-- The morphism to `Spec M` with prescribed composites with `Spec M ⟶ Spec B` and
`Spec M ⟶ Spec C`. -/
noncomputable def descendedLift {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of B))
    (c : T ⟶ Spec (CommRingCat.of D.descended))
    (w : t ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) =
      c ≫ Spec.map (CommRingCat.ofHom (algebraMap A D.descended))) :
    T ⟶ Spec (CommRingCat.of D.M) :=
  pullback.lift t c w ≫ (pullbackSpecIso A B D.descended).hom ≫
    Spec.map (CommRingCat.ofHom (D.descentEquiv.symm : D.M →+* B ⊗[A] D.descended))

/-- `descendedLift t c w` lies over `t`. -/
lemma descendedLift_comp_algebraMap {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of B))
    (c : T ⟶ Spec (CommRingCat.of D.descended))
    (w : t ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) =
      c ≫ Spec.map (CommRingCat.ofHom (algebraMap A D.descended))) :
    D.descendedLift t c w ≫ Spec.map (CommRingCat.ofHom (algebraMap B D.M)) = t := by
  rw [descendedLift, Category.assoc, Category.assoc, ← specMap_comp,
    descentEquiv_symm_comp_algebraMap, pullbackSpecIso_hom_fst, pullback.lift_fst]

/-- `descendedLift t c w` lies over `c`. -/
lemma descendedLift_comp_val {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of B))
    (c : T ⟶ Spec (CommRingCat.of D.descended))
    (w : t ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) =
      c ≫ Spec.map (CommRingCat.ofHom (algebraMap A D.descended))) :
    D.descendedLift t c w ≫ Spec.map (CommRingCat.ofHom D.descendedVal) = c := by
  rw [descendedLift, Category.assoc, Category.assoc, ← specMap_comp,
    descentEquiv_symm_comp_descendedVal, pullbackSpecIso_hom_snd, pullback.lift_snd]

/-- For `B` flat over `A`, `B ⊗[A] C ≅ M` as `B`-algebras. -/
theorem descended_tensor : Nonempty (B ⊗[A] D.descended ≃ₐ[B] D.M) :=
  ⟨D.descentEquiv⟩

end Flat

/-! ### Gluing the comparison morphism `F ⟶ Spec C` -/

/-- The sieve on `Spec A` generated by `Spec B ⟶ Spec A`. -/
noncomputable abbrev coverSieve : Sieve (Spec (CommRingCat.of A)) :=
  Sieve.generate (Presieve.singleton (Spec.map (CommRingCat.ofHom (algebraMap A B))))

omit D in
/-- The members of `coverSieve` are the morphisms factoring through `Spec B`. -/
lemma mem_coverSieve_iff {X : Scheme.{u}} (f : X ⟶ Spec (CommRingCat.of A)) :
    (coverSieve (A := A) (B := B)).arrows f ↔
      ∃ g : X ⟶ Spec (CommRingCat.of B),
        g ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) = f := by
  constructor
  · rintro ⟨Y, h, g, ⟨⟩, rfl⟩
    exact ⟨h, rfl⟩
  · rintro ⟨g, rfl⟩
    exact ⟨_, g, _, Presieve.singleton.mk, rfl⟩

omit D in
/-- For `B` faithfully flat and of finite presentation over `A`, the sieve generated by
`Spec B ⟶ Spec A` is an fppf covering sieve. -/
lemma coverSieve_mem [Module.FaithfullyFlat A B] [Algebra.FinitePresentation A B] :
    coverSieve (A := A) (B := B) ∈ fppfJ.{u} (Spec (CommRingCat.of A)) := by
  have hff : (CommRingCat.ofHom (algebraMap A B)).hom.FaithfullyFlat :=
    RingHom.faithfullyFlat_algebraMap_iff.2 inferInstance
  obtain ⟨_, _⟩ := (flat_and_surjective_SpecMap_iff _).2 hff
  have : LocallyOfFinitePresentation (Spec.map (CommRingCat.ofHom (algebraMap A B))) :=
    (LocallyOfFinitePresentation.SpecMap_iff _).2
      (RingHom.finitePresentation_algebraMap.2 inferInstance)
  exact Precoverage.generate_mem_toGrothendieck (Scheme.Hom.singleton_mem_fppfPrecoverage _)

/-- The section of `F` underlying a section of `F ×_S Spec B`, through `θ`. -/
lemma point_preimage {T : Scheme.{u}}
    (α : fppfYoneda.obj T ⟶
      pullback π (fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A B))))) :
    D.point (fppfYoneda.preimage (α ≫ D.θ.hom)) = α ≫ pullback.fst _ _ := by
  simp [point]

/-- Composition of the base change morphisms `relBaseChange`, in the special case of a second
factor through `Spec B ⟶ Spec A` (an instance of a general fact about `relBaseChange` for any
`f : X ⟶ S`). -/
lemma relBaseChange_comp {X Y : Scheme.{u}} (f : X ⟶ Spec (CommRingCat.of A))
    (k : Y ⟶ X) (h : Y ⟶ Spec (CommRingCat.of A)) (hh : k ≫ f = h)
    (g : X ⟶ Spec (CommRingCat.of B))
    (hg : g ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) = f) :
    relBaseChange π f k h hh ≫
        relBaseChange π (Spec.map (CommRingCat.ofHom (algebraMap A B))) g f hg =
      relBaseChange π (Spec.map (CommRingCat.ofHom (algebraMap A B))) (k ≫ g) h
        (by rw [Category.assoc, hg, hh]) := by
  apply pullback.hom_ext <;> simp [Functor.map_comp]

/-- The composite `F ×_S X ⟶ F ×_S Spec B ≅ Spec M ⟶ Spec C` does not depend on the chosen
factorisation of `X ⟶ Spec A` through `Spec B`. -/
lemma relBaseChange_θ_eq {X : Scheme.{u}} (f : X ⟶ Spec (CommRingCat.of A))
    (g₁ g₂ : X ⟶ Spec (CommRingCat.of B))
    (h₁ : g₁ ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) = f)
    (h₂ : g₂ ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) = f) :
    relBaseChange π _ g₁ f h₁ ≫ D.θ.hom ≫
        fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal)) =
      relBaseChange π _ g₂ f h₂ ≫ D.θ.hom ≫
        fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal)) := by
  apply fppfSheaf_hom_ext
  intro T α
  have key : ∀ (g : X ⟶ Spec (CommRingCat.of B))
      (hg : g ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) = f),
      α ≫ relBaseChange π _ g f hg ≫ D.θ.hom ≫
        fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal)) =
      fppfYoneda.map (fppfYoneda.preimage (α ≫ relBaseChange π _ g f hg ≫ D.θ.hom) ≫
        Spec.map (CommRingCat.ofHom D.descendedVal)) := by
    intro g hg
    rw [Functor.map_comp, Functor.map_preimage]
    simp only [Category.assoc]
  rw [key, key]
  congr 1
  apply D.comp_specMap_descendedVal
  rw [← Category.assoc, ← Category.assoc, point_preimage, point_preimage, Category.assoc,
    Category.assoc, relBaseChange_fst, relBaseChange_fst]

/-- The compatible family `F ×_S X ⟶ Spec C` on the sieve generated by `Spec B ⟶ Spec A`. -/
noncomputable def toSpecFamily :
    RelHomFamily π (fppfYoneda.obj (Spec (CommRingCat.of D.descended)))
      (coverSieve (A := A) (B := B)) where
  hom f hf := relBaseChange π _ ((mem_coverSieve_iff f).1 hf).choose f
      ((mem_coverSieve_iff f).1 hf).choose_spec ≫ D.θ.hom ≫
    fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal))
  compat f k h hh hf hh' := by
    rw [← Category.assoc (relBaseChange π f k h hh), relBaseChange_comp]
    exact D.relBaseChange_θ_eq _ _ _ _ _

/-- The comparison morphism `F ⟶ Spec C`, for `B` faithfully flat and of finite presentation
over `A`: glued, along the fppf covering sieve generated by `Spec B ⟶ Spec A`, from
`F ×_S Spec B ≅ Spec M ⟶ Spec C` (the hypotheses make that sieve a covering sieve). -/
noncomputable def toSpec [Module.FaithfullyFlat A B] [Algebra.FinitePresentation A B] :
    F ⟶ fppfYoneda.obj (Spec (CommRingCat.of D.descended)) :=
  D.toSpecFamily.glue (coverSieve_mem (A := A) (B := B))

section Comparison

variable [Module.FaithfullyFlat A B] [Algebra.FinitePresentation A B]

/-- `toSpec` restricted to `F ×_S Spec B` is `θ` followed by `Spec M ⟶ Spec C`. -/
@[reassoc]
lemma fst_toSpec :
    pullback.fst π (fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A B)))) ≫
        D.toSpec =
      D.θ.hom ≫ fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal)) := by
  have hf : (coverSieve (A := A) (B := B)).arrows
      (Spec.map (CommRingCat.ofHom (algebraMap A B))) :=
    (mem_coverSieve_iff _).2 ⟨𝟙 _, Category.id_comp _⟩
  rw [toSpec, RelHomFamily.glue_spec _ _ _ hf]
  change relBaseChange π _ _ _ _ ≫ _ = _
  rw [D.relBaseChange_θ_eq _ _ (𝟙 _) _ (Category.id_comp _)]
  have : relBaseChange π (Spec.map (CommRingCat.ofHom (algebraMap A B))) (𝟙 _) _
      (Category.id_comp _) = 𝟙 _ := by
    apply pullback.hom_ext <;> simp
  rw [this, Category.id_comp]

/-- `toSpec` on the section of `F` attached to a morphism `G : T ⟶ Spec M`. -/
lemma point_toSpec {T : Scheme.{u}} (G : T ⟶ Spec (CommRingCat.of D.M)) :
    D.point G ≫ D.toSpec =
      fppfYoneda.map (G ≫ Spec.map (CommRingCat.ofHom D.descendedVal)) := by
  rw [point, Category.assoc, Category.assoc, fst_toSpec, Iso.inv_hom_id_assoc,
    Functor.map_comp]

/-- The comparison morphism lies over `Spec A`. -/
theorem toSpec_comp :
    D.toSpec ≫ fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A D.descended))) = π := by
  refine hom_ext_of_cover π (coverSieve_mem (A := A) (B := B)) ?_
  intro X f hf
  obtain ⟨g, rfl⟩ := (mem_coverSieve_iff f).1 hf
  have hC : Spec.map (CommRingCat.ofHom D.descendedVal) ≫
      Spec.map (CommRingCat.ofHom (algebraMap A D.descended)) =
      Spec.map (CommRingCat.ofHom (algebraMap B D.M)) ≫
        Spec.map (CommRingCat.ofHom (algebraMap A B)) := by
    rw [← specMap_comp, ← specMap_algebraMap_base]
    rfl
  have hC' : fppfYoneda.map (Spec.map (CommRingCat.ofHom D.descendedVal)) ≫
      fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A D.descended))) =
      fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap B D.M))) ≫
        fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A B))) := by
    rw [← Functor.map_comp, hC, Functor.map_comp]
  rw [← relBaseChange_fst π _ g _ rfl, Category.assoc, fst_toSpec_assoc, hC',
    ← Category.assoc D.θ.hom, D.θ_over, relBaseChange_snd_assoc, ← Functor.map_comp,
    relBaseChange_fst, pullback.condition]

/-! ### The comparison morphism is an isomorphism -/

/-- The base change of `toSpec` along a member of `coverSieve` is an isomorphism
(bijective on sections over every scheme). -/
lemma isIso_relMap_toSpec {X : Scheme.{u}} (f : X ⟶ Spec (CommRingCat.of A))
    (hf : (coverSieve (A := A) (B := B)).arrows f) :
    IsIso (relMap π (fppfYoneda.map (Spec.map (CommRingCat.ofHom (algebraMap A D.descended))))
      D.toSpec D.toSpec_comp f) := by
  obtain ⟨g, rfl⟩ := (mem_coverSieve_iff f).1 hf
  set fX := g ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) with hfX
  apply fppfSheaf_isIso_of_bijective
  intro T
  constructor
  · intro α₁ α₂ h
    beta_reduce at h
    have hs : α₁ ≫ pullback.snd π (fppfYoneda.map fX) =
        α₂ ≫ pullback.snd π (fppfYoneda.map fX) := by
      rw [← relMap_snd π _ D.toSpec D.toSpec_comp fX, ← Category.assoc, ← Category.assoc, h]
    have hf' : α₁ ≫ pullback.fst π (fppfYoneda.map fX) ≫ D.toSpec =
        α₂ ≫ pullback.fst π (fppfYoneda.map fX) ≫ D.toSpec := by
      rw [← relMap_fst π _ D.toSpec D.toSpec_comp fX, ← Category.assoc, ← Category.assoc, h]
    let t : T ⟶ X := fppfYoneda.preimage (α₁ ≫ pullback.snd π (fppfYoneda.map fX))
    have ht₁ : α₁ ≫ pullback.snd π (fppfYoneda.map fX) = fppfYoneda.map t := by simp [t]
    have ht₂ : α₂ ≫ pullback.snd π (fppfYoneda.map fX) = fppfYoneda.map t := by
      rw [← hs]; simp [t]
    have hw : ∀ i : fppfYoneda.obj T ⟶ pullback π (fppfYoneda.map fX),
        i ≫ pullback.snd π (fppfYoneda.map fX) = fppfYoneda.map t →
        (i ≫ pullback.fst π (fppfYoneda.map fX)) ≫ π =
          fppfYoneda.map ((t ≫ g) ≫ Spec.map (CommRingCat.ofHom (algebraMap A B))) := by
      intro i hi
      rw [Category.assoc, pullback.condition, ← Category.assoc, hi, Category.assoc,
        ← Functor.map_comp]
    let G₁ := D.pointLift _ _ (hw α₁ ht₁)
    let G₂ := D.pointLift _ _ (hw α₂ ht₂)
    have hG : G₁ = G₂ := by
      apply D.hom_ext_descended
      · rw [pointLift_comp, pointLift_comp]
      · apply fppfYoneda.map_injective
        rw [← point_toSpec, ← point_toSpec, point_pointLift, point_pointLift, Category.assoc,
          Category.assoc, hf']
    have hx : α₁ ≫ pullback.fst _ _ = α₂ ≫ pullback.fst _ _ := by
      have := congrArg D.point hG
      rwa [point_pointLift, point_pointLift] at this
    exact pullback.hom_ext hx hs
  · intro β
    let c := fppfYoneda.preimage (β ≫ pullback.fst _ (fppfYoneda.map fX))
    let t : T ⟶ X := fppfYoneda.preimage (β ≫ pullback.snd _ (fppfYoneda.map fX))
    have hw : (t ≫ g) ≫ Spec.map (CommRingCat.ofHom (algebraMap A B)) =
        c ≫ Spec.map (CommRingCat.ofHom (algebraMap A D.descended)) := by
      apply fppfYoneda.map_injective
      simp only [c, t, Functor.map_comp, Functor.map_preimage, Category.assoc]
      rw [← Functor.map_comp, ← hfX, ← pullback.condition]
    let G := D.descendedLift (t ≫ g) c hw
    refine ⟨pullback.lift (D.point G) (fppfYoneda.map t) ?_, ?_⟩
    · rw [point_π, ← Category.assoc G, descendedLift_comp_algebraMap, Functor.map_comp,
        Functor.map_comp, Functor.map_comp, Category.assoc]
    · beta_reduce
      apply pullback.hom_ext
      · simp only [Category.assoc, relMap_fst, pullback.lift_fst_assoc]
        rw [point_toSpec, descendedLift_comp_val]
        simp [c]
      · rw [Category.assoc, relMap_snd, pullback.lift_snd]
        simp [t]

/-- **Effective descent of affine schemes.** For `B` faithfully flat and of finite presentation
over `A`, the comparison morphism `F ⟶ Spec C` is an isomorphism. -/
theorem isIso_toSpec : IsIso D.toSpec :=
  isIso_of_cover π _ D.toSpec D.toSpec_comp (coverSieve_mem (A := A) (B := B))
    (fun f hf ↦ D.isIso_relMap_toSpec f hf)

end Comparison

/-- If `B` is faithfully flat over `A` and `M` is étale over `B`, then the descended algebra `C`
is étale over `A` (round 25, `AlgDescentDatum.etale_descendedAlgebra`). -/
theorem etale_descended [Module.FaithfullyFlat A B] [Algebra.Etale B D.M] :
    Algebra.Etale A D.descended :=
  D.descentDatum.etale_descendedAlgebra

/-- If `B` is faithfully flat over `A` and `M` is a finite `B`-module, then the descended algebra
`C` is a finite `A`-module (round 25, `AlgDescentDatum.finite_descendedAlgebra`). -/
theorem finite_descended [Module.FaithfullyFlat A B] [Module.Finite B D.M] :
    Module.Finite A D.descended :=
  D.descentDatum.finite_descendedAlgebra

end AffineDescentInput

end GromovWitten.AlgebraicGeometry
