/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.AlgebraicGeometry.Spaces.Representable
import Mathlib.AlgebraicGeometry.Morphisms.Finite
import Mathlib.AlgebraicGeometry.Sites.Representability

/-!
# Zariski gluing of representable fppf sheaves over a base

Let `π : F ⟶ fppfYoneda.obj T` be a morphism of fppf sheaves of sets on the big category of
schemes.  Suppose that `T` is covered by opens `U i` (`⨆ i, U i = ⊤`) and that, for every `i`,
the base change `F ×_T U i := pullback π (fppfYoneda.map (U i).ι)` is represented by a scheme
`X i`, compatibly with a given morphism `g i : X i ⟶ U i`.  This file proves that `F` itself is
represented by a scheme over `T`, glued from the `X i`, and that its structure morphism to `T`
has every property of morphisms that is local on the target in the Zariski topology and holds
for all the `g i` (Stacks Project, Tag 01JJ; Tag 02L2 for the base-change statement).

The gluing itself is Mathlib's `AlgebraicGeometry.Scheme.LocalRepresentability`
(`Mathlib/AlgebraicGeometry/Sites/Representability.lean`), which glues a Zariski sheaf from a
family of relatively representable open immersions `yoneda.obj (X i) ⟶ F` that is locally
surjective; its gluing data is a `Scheme.GlueData` with overlaps the representing objects of the
fibre products `X i ×_F X j`.  The work done here is to verify its hypotheses for the restriction
of the fppf sheaf `F` to the Zariski topology:

* `LocallyRepresentable.exists_isPullback_toSheaf`: for a section `s : fppfYoneda.obj Y ⟶ F`
  lying over `φ : Y ⟶ T`, the open subscheme `φ ⁻¹ᵁ U i` of `Y` represents the pullback of
  `X i ⟶ F` along `s` (pasting the pullback square `isPullback_morphismRestrict` with the
  defining square of `F ×_T U i`);
* `LocallyRepresentable.isOpenImmersion_presheafMap`: hence `yoneda.obj (X i) ⟶ F` is a
  relatively representable open immersion of presheaves;
* `LocallyRepresentable.isLocallySurjective_sigmaDesc`: the family is jointly locally surjective
  for the Zariski topology, since the sieve generated by the opens `φ ⁻¹ᵁ U i` covers `Y`.

## Main results

* `LocallyRepresentable F π`: the input data `(U i, X i, g i, θ i)`;
* `LocallyRepresentable.scheme`, `LocallyRepresentable.toBase : L.scheme ⟶ T`;
* `LocallyRepresentable.iso : fppfYoneda.obj L.scheme ≅ F` and
  `LocallyRepresentable.iso_hom_comp : L.iso.hom ≫ π = fppfYoneda.map L.toBase`;
* `LocallyRepresentable.ιPiece i : X i ⟶ L.scheme` (an open immersion) and
  `LocallyRepresentable.isPullback_piece`: `X i` is the fibre product `L.scheme ×_T U i`;
* `LocallyRepresentable.toBase_property`: if `P` is local at the target for the Zariski
  topology and every `g i` has `P`, then `L.toBase` has `P`; specialisations
  `etale_toBase`, `surjective_toBase`, `isFinite_toBase`.
-/

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry Opposite

namespace GromovWitten.AlgebraicGeometry

universe u

/-- Zariski-local representability data for a morphism `π : F ⟶ fppfYoneda.obj T` of fppf
sheaves: a family of opens `U i` covering `T`, schemes `X i` with morphisms `g i : X i ⟶ U i`,
and isomorphisms `θ i` from the base change `F ×_T U i = pullback π (fppfYoneda.map (U i).ι)` to
`fppfYoneda.obj (X i)` under which the second projection becomes `g i` (stated after composing
with the open immersion `(U i).ι`, field `θ_over`). -/
structure LocallyRepresentable {T : Scheme.{u}} (F : FppfSheaf.{u})
    (π : F ⟶ fppfYoneda.obj T) where
  /-- The index type of the cover. -/
  ι : Type u
  /-- The opens of `T`. -/
  U : ι → T.Opens
  /-- The opens cover `T`. -/
  iSup_U : ⨆ i, U i = ⊤
  /-- The scheme representing `F ×_T U i`. -/
  X : ι → Scheme.{u}
  /-- The structure morphism of `X i` to `U i`. -/
  g : ∀ i, X i ⟶ (U i).toScheme
  /-- The identification of `F ×_T U i` with `X i`. -/
  θ : ∀ i, Limits.pullback π (fppfYoneda.map (U i).ι) ≅ fppfYoneda.obj (X i)
  /-- `θ i` lies over `T`: it identifies the projection to `U i` with `g i`. -/
  θ_over : ∀ i, (θ i).hom ≫ fppfYoneda.map (g i ≫ (U i).ι) =
    Limits.pullback.snd _ _ ≫ fppfYoneda.map (U i).ι

-- Duplicates the public `zariskiTopology_le_fppfTopology` of `Stacks/TorsorStackCover.lean`
-- (importing that file here would invert the layering), pending a move to an earlier module.
private lemma zariskiTopology_le_fppfTopology' :
    Scheme.zariskiTopology.{u} ≤ Scheme.fppfTopology.{u} :=
  Precoverage.toGrothendieck_mono Scheme.zariskiPrecoverage_le_fppfPrecoverage

/-- An fppf sheaf of sets on schemes, regarded as a sheaf for the (coarser) Zariski topology. -/
noncomputable def FppfSheaf.toZariski (F : FppfSheaf.{u}) :
    Sheaf Scheme.zariskiTopology.{u} (Type u) :=
  ⟨F.obj, F.property.of_le zariskiTopology_le_fppfTopology'⟩

namespace LocallyRepresentable

variable {T : Scheme.{u}} {F : FppfSheaf.{u}} {π : F ⟶ fppfYoneda.obj T}
  (L : LocallyRepresentable F π)

/-- `θ i` identifies the projection `F ×_T U i ⟶ U i` with `g i`. -/
@[reassoc]
lemma θ_hom_g (i : L.ι) :
    (L.θ i).hom ≫ fppfYoneda.map (L.g i) = pullback.snd _ _ := by
  rw [← cancel_mono (fppfYoneda.map (L.U i).ι), Category.assoc, ← Functor.map_comp, L.θ_over]

/-- The morphism `fppfYoneda.obj (X i) ≅ F ×_T U i ⟶ F`. -/
noncomputable def toSheaf (i : L.ι) : fppfYoneda.obj (L.X i) ⟶ F :=
  (L.θ i).inv ≫ pullback.fst _ _

/-- For a section `s` of `F` over a scheme `Y`, lying over `φ : Y ⟶ T`, the open subscheme
`φ ⁻¹ᵁ U i` of `Y` represents the fibre product of `s` and `L.toSheaf i`. -/
lemma exists_isPullback_toSheaf (i : L.ι) {Y : Scheme.{u}} (s : fppfYoneda.obj Y ⟶ F)
    (φ : Y ⟶ T) (hφ : s ≫ π = fppfYoneda.map φ) :
    ∃ a : (φ ⁻¹ᵁ L.U i).toScheme ⟶ L.X i,
      IsPullback (fppfYoneda.map a) (fppfYoneda.map (φ ⁻¹ᵁ L.U i).ι) (L.toSheaf i) s := by
  have outer := (isPullback_morphismRestrict φ (L.U i)).map fppfYoneda
  rw [← hφ] at outer
  let h₁₁ : fppfYoneda.obj (φ ⁻¹ᵁ L.U i) ⟶ pullback π (fppfYoneda.map (L.U i).ι) :=
    pullback.lift (fppfYoneda.map (φ ⁻¹ᵁ L.U i).ι ≫ s) (fppfYoneda.map (φ ∣_ L.U i))
      (by rw [Category.assoc, outer.w])
  have left : IsPullback h₁₁ (fppfYoneda.map (φ ⁻¹ᵁ L.U i).ι) (pullback.fst _ _) s :=
    IsPullback.of_right (by rw [pullback.lift_snd]; exact outer) (pullback.lift_fst _ _ _)
      (IsPullback.of_hasPullback π (fppfYoneda.map (L.U i).ι)).flip
  refine ⟨Scheme.fppfTopology.yonedaFullyFaithful.preimage (h₁₁ ≫ (L.θ i).hom), ?_⟩
  rw [Functor.FullyFaithful.map_preimage]
  exact left.of_iso (Iso.refl _) (L.θ i) (Iso.refl _) (Iso.refl _) (by simp) (by simp)
    (by simp [toSheaf]) (by simp)

/-- The underlying morphism of presheaves `yoneda.obj (X i) ⟶ F` of `L.toSheaf i`. -/
noncomputable def presheafMap (i : L.ι) : yoneda.obj (L.X i) ⟶ (FppfSheaf.toZariski F).obj :=
  (L.toSheaf i).hom

/-- `yoneda.obj (X i) ⟶ F` is a relatively representable open immersion of presheaves. -/
lemma isOpenImmersion_presheafMap (i : L.ι) :
    IsOpenImmersion.presheaf (L.presheafMap i) := by
  refine MorphismProperty.relative.of_exists fun Y g ↦ ?_
  let s : fppfYoneda.obj Y ⟶ F := ObjectProperty.homMk g
  obtain ⟨a, ha⟩ := L.exists_isPullback_toSheaf i s
    (Scheme.fppfTopology.yonedaFullyFaithful.preimage (s ≫ π)) (by simp)
  exact ⟨_, _, _, ha.map (sheafToPresheaf _ _), inferInstance⟩

/-- Evaluation of `L.presheafMap i` on a `V`-point of `X i`. -/
lemma presheafMap_app (i : L.ι) {V : Scheme.{u}} (b : V ⟶ L.X i) :
    (L.presheafMap i).app (op V) b =
      Scheme.fppfTopology.yonedaEquiv (fppfYoneda.map b ≫ L.toSheaf i) := by
  rw [GrothendieckTopology.yonedaEquiv_comp, GrothendieckTopology.yonedaEquiv_yoneda_map]
  rfl

/-- The family `yoneda.obj (X i) ⟶ F` is jointly locally surjective for the Zariski topology. -/
instance isLocallySurjective_sigmaDesc :
    Presheaf.IsLocallySurjective Scheme.zariskiTopology (Sigma.desc L.presheafMap) where
  imageSieve_mem {Y} s := by
    let s' : fppfYoneda.obj Y ⟶ F := Scheme.fppfTopology.yonedaEquiv.symm s
    let φ := Scheme.fppfTopology.yonedaFullyFaithful.preimage (s' ≫ π)
    have hcov : TopologicalSpace.IsOpenCover (fun i ↦ φ ⁻¹ᵁ L.U i) := by
      rw [TopologicalSpace.IsOpenCover, eq_top_iff]
      intro x _
      have hx : φ x ∈ ⨆ i, L.U i := L.iSup_U ▸ trivial
      rw [TopologicalSpace.Opens.mem_iSup] at hx ⊢
      exact hx
    have hmem : Sieve.ofArrows (fun i : L.ι ↦ (φ ⁻¹ᵁ L.U i).toScheme)
        (fun i ↦ (φ ⁻¹ᵁ L.U i).ι) ∈ Scheme.zariskiTopology Y :=
      (Y.openCoverOfIsOpenCover _ hcov).mem_grothendieckTopology
    refine Scheme.zariskiTopology.superset_covering ?_ hmem
    rintro V _ ⟨W, k, _, ⟨i⟩, rfl⟩
    obtain ⟨a, ha⟩ := L.exists_isPullback_toSheaf i s' φ (by simp [φ])
    refine ⟨(Sigma.ι (fun i ↦ yoneda.obj (L.X i)) i).app (op V) (k ≫ a), ?_⟩
    have e1 := congr_arg (fun t ↦ t.app (op V) (k ≫ a))
      (Sigma.ι_desc L.presheafMap i)
    dsimp only at e1
    rw [NatTrans.comp_app_apply] at e1
    rw [e1, presheafMap_app]
    have e2 := Scheme.fppfTopology.yonedaEquiv_naturality s' (k ≫ (φ ⁻¹ᵁ L.U i).ι)
    have hs : Scheme.fppfTopology.yonedaEquiv s' = s := Equiv.apply_symm_apply _ _
    rw [hs] at e2
    refine Eq.trans ?_ e2.symm
    congr 1
    rw [Functor.map_comp, Functor.map_comp, Category.assoc, Category.assoc, ha.w]

/-- The scheme representing `F`, glued from the `X i` (Mathlib's
`Scheme.LocalRepresentability.glueData`). -/
noncomputable def scheme : Scheme.{u} :=
  (Scheme.LocalRepresentability.glueData (F := FppfSheaf.toZariski F)
    L.isOpenImmersion_presheafMap).glued

/-- The open immersion of the piece `X i` into the glued scheme. -/
noncomputable def ιPiece (i : L.ι) : L.X i ⟶ L.scheme :=
  Scheme.LocalRepresentability.toGlued L.isOpenImmersion_presheafMap i

instance (i : L.ι) : IsOpenImmersion (L.ιPiece i) :=
  inferInstanceAs (IsOpenImmersion
    (Scheme.LocalRepresentability.toGlued L.isOpenImmersion_presheafMap i))

/-- The glued scheme represents `F`. -/
noncomputable def iso : fppfYoneda.obj L.scheme ≅ F :=
  (fullyFaithfulSheafToPresheaf _ _).preimageIso
    ((sheafToPresheaf Scheme.zariskiTopology _).mapIso
      (Scheme.LocalRepresentability.yonedaIsoSheaf L.isOpenImmersion_presheafMap))

/-- Restricted to the piece `X i`, `L.iso` is `L.toSheaf i`. -/
@[reassoc]
lemma map_ιPiece_iso_hom (i : L.ι) :
    fppfYoneda.map (L.ιPiece i) ≫ L.iso.hom = L.toSheaf i :=
  Sheaf.hom_ext (by exact
    Scheme.LocalRepresentability.yoneda_toGlued_yonedaGluedToSheaf L.isOpenImmersion_presheafMap i)

/-- The structure morphism of the glued scheme to `T`, corresponding to `π` under `L.iso`. -/
noncomputable def toBase : L.scheme ⟶ T :=
  Scheme.fppfTopology.yonedaFullyFaithful.preimage (L.iso.hom ≫ π)

/-- `L.iso` lies over `T`. -/
@[reassoc]
theorem iso_hom_comp : L.iso.hom ≫ π = fppfYoneda.map L.toBase :=
  (Scheme.fppfTopology.yonedaFullyFaithful.map_preimage _).symm

/-- The piece `X i` is the fibre product `L.scheme ×_T U i`, with projections `L.ιPiece i` and
`L.g i`. -/
theorem isPullback_piece (i : L.ι) :
    IsPullback (L.ιPiece i) (L.g i) L.toBase (L.U i).ι := by
  have H : IsPullback (fppfYoneda.map (L.ιPiece i)) (fppfYoneda.map (L.g i))
      (fppfYoneda.map L.toBase) (fppfYoneda.map (L.U i).ι) :=
    (IsPullback.of_hasPullback π (fppfYoneda.map (L.U i).ι)).of_iso (L.θ i) L.iso.symm
      (Iso.refl _) (Iso.refl _)
      (by rw [Iso.symm_hom, Iso.comp_inv_eq, Category.assoc, map_ιPiece_iso_hom, toSheaf,
        Iso.hom_inv_id_assoc])
      (by rw [Iso.refl_hom, Category.comp_id, θ_hom_g])
      (by rw [Iso.symm_hom, Iso.refl_hom, Category.comp_id, ← iso_hom_comp,
        Iso.inv_hom_id_assoc])
      (by simp)
  exact H.of_map_of_faithful fppfYoneda

/-- A property of morphisms that is local on the target for the Zariski topology holds for
`L.toBase` as soon as it holds for every `g i`.  For several of Mathlib's standard properties
(étale, finite, affine, …) instance search for `IsZariskiLocalAtTarget` only succeeds under
`set_option backward.isDefEq.respectTransparency.types false`; the specialisations
`etale_toBase`, `surjective_toBase` and `isFinite_toBase` are provided ready to use. -/
theorem toBase_property (P : MorphismProperty Scheme.{u}) [IsZariskiLocalAtTarget P]
    (h : ∀ i, P (L.g i)) : P L.toBase := by
  refine IsZariskiLocalAtTarget.of_iSup_eq_top L.U L.iSup_U fun i ↦ ?_
  let e := (L.isPullback_piece i).flip.isoIsPullback _ _
    (isPullback_morphismRestrict L.toBase (L.U i))
  rw [← P.cancel_left_of_respectsIso e.hom, IsPullback.isoIsPullback_hom_fst]
  exact h i

-- Instance search for `IsZariskiLocalAtTarget` from `HasAffineProperty`/`HasRingHomProperty`
-- needs the transparency setting under which Mathlib registered those instances.
set_option backward.isDefEq.respectTransparency.types false in
/-- The glued scheme is étale over `T` if every piece is étale over its open. -/
theorem etale_toBase (h : ∀ i, Etale (L.g i)) : Etale L.toBase :=
  L.toBase_property @Etale h

/-- The glued scheme is surjective over `T` if every piece is surjective over its open. -/
theorem surjective_toBase (h : ∀ i, Surjective (L.g i)) : Surjective L.toBase :=
  L.toBase_property @Surjective h

-- Instance search for `IsZariskiLocalAtTarget` from `HasAffineProperty`/`HasRingHomProperty`
-- needs the transparency setting under which Mathlib registered those instances.
set_option backward.isDefEq.respectTransparency.types false in
/-- The glued scheme is finite over `T` if every piece is finite over its open. -/
theorem isFinite_toBase (h : ∀ i, IsFinite (L.g i)) : IsFinite L.toBase :=
  L.toBase_property @IsFinite h

end LocallyRepresentable

end GromovWitten.AlgebraicGeometry
