/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Sites.StackSiteMorphisms
import GromovWitten.AlgebraicGeometry.Stacks.OverlapSwap

/-!
# Continuity of the inclusions between the sites of a stack

The sites of a stack used in `Sites/Stack.lean` are full subcategories of the Grothendieck
total category `X.total` of the stack, cut out by a presentation predicate, and their
topologies are the `Functor.inducedTopology`s of the étale (or fppf) topology along the
underlying-scheme functor.  This file develops the comparison of two such sites.

## Contents

* `base_mem_of_hom`: the scheme morphism underlying a morphism of stack objects whose source
  has a chart with a representable property `P ⊇ Etale` and whose target has an étale chart
  is itself in `P`.  In particular a morphism of small-étale objects is étale on underlying
  schemes (`etale_base_of_hom_isEtaleObject`), and a morphism from a lisse object to a
  small-étale object is smooth on underlying schemes
  (`smooth_base_of_hom_isLisseObject`).
* `StackSubsite.HasEtaleLifts`: the closure property of the object family of a subsite that
  makes its topology computable, namely that étale scheme morphisms into the underlying
  scheme of an object of the subsite can be lifted to morphisms of the subsite.
* `StackSubsite.etaleLiftCoverage`: the coverage of the subsite generated by such lifted
  étale covers, and `StackSubsite.isContinuous_toScheme`: the underlying-scheme functor is
  continuous for the topology that coverage generates.  Together with
  `StackSubsite.exists_etaleLiftCovering_le` this yields the concrete description
  `StackSubsite.mem_inducedTopology_iff` of the covering sieves of the induced topology of a
  subsite: they are the sieves whose pushforward to schemes is an étale covering sieve.
* `SiteChart.restrict A g`: the chart `A` of a stack precomposed with a morphism of schemes
  `g`, together with the identification of all its comparison data with that of `A`;
  `SiteChart.inducedComparison_id` and `SiteChart.inducedComparison_comp` are the unit and
  associativity coherences of the stack pseudofunctor in the form needed to make
  `StackChart.Classifies` reflexive (`SiteChart.classifies_id`) and transitive
  (`SiteChart.classifies_comp`).  These give the uniqueness of chart pullback presentations
  (`SiteChart.presentationIso`), hence the criterion
  `SiteChart.hasRepresentableProperty_of_exists`, and finally, with the explicit base-change
  presentation `SiteChart.restrictPresentation`, the theorem
  `SiteChart.restrict_hasRepresentableProperty`: a chart with a representable property `P`
  stable under base change and composition keeps `P` after precomposition with a morphism of
  schemes in `P`.
* `isEtaleObject_domainCartesianLift`, `isLisseObject_domainCartesianLift`: the cartesian
  pullback of a small-étale, respectively lisse, object of a stack along an étale morphism of
  schemes is again such an object.  Hence `hasEtaleLifts_smallEtale` and
  `hasEtaleLifts_lisseEtale`, so the covering sieves of both stack topologies are described by
  `mem_smallEtaleStackTopology_iff` and `mem_lisseEtaleStackTopology_iff`.
* `smallEtaleToLisse_compatiblePreserving`, `smallEtaleToLisse_coverPreserving` and
  `smallEtaleToLisse_isContinuous`: the inclusion of the small-étale site of a
  Deligne--Mumford stack into its lisse-étale site is a continuous functor of sites.  The
  compatibility statement is where the fibre product of two small-étale objects over a third
  is used; it is a small-étale object because morphisms of small-étale objects are étale on
  underlying schemes.
* `smallEtaleToLisseRingedSiteMorphism` and `smallEtaleToLisseModules`: the resulting
  morphism of ringed sites and the restriction of module sheaves along it.
* `lisseEtaleForget_coverPreserving`: the inclusion of the lisse-étale site into the big fppf
  site of a stack preserves covering sieves.  Its compatibility statement is *not* proved; see
  the discussion at that declaration.
-/

open CategoryTheory CategoryTheory.Limits
open _root_.AlgebraicGeometry

namespace GromovWitten.AlgebraicGeometry.Sites

universe t u

open GromovWitten.AlgebraicGeometry
open CategoryTheory.Pseudofunctor.CoGrothendieck

/-! ## Underlying scheme morphisms of morphisms of stack objects -/

/-- The scheme morphism underlying a morphism of stack objects whose source has a chart with a
representable property `P` containing the étale morphisms and whose target has an étale chart
is itself in `P`.  The proof compares the two charts on the fibre product of their schemes
over the stack: the second projection of that fibre product is étale because the target chart
is étale, the morphism of stack objects provides a section of it, and the section is therefore
étale by cancellation. -/
theorem base_mem_of_hom (X : FppfStack.{u})
    (P : MorphismProperty Scheme.{u}) (hPcomp : P.IsStableUnderComposition)
    (hPE : (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) ≤ P)
    {y z : X.total} (φ : y ⟶ z)
    (py : StackObjectPresentation X y) (hy : py.chart.HasRepresentableProperty P)
    (pz : StackObjectPresentation X z) (hz : pz.chart.IsEtale) :
    P φ.base := by
  have _inst : P.IsStableUnderComposition := hPcomp
  obtain ⟨Yb, Yf⟩ := y
  obtain ⟨Zb, Zf⟩ := z
  obtain ⟨A, hA, cA⟩ := py
  obtain ⟨B, hB, cB⟩ := pz
  change Yb = A.scheme at hA
  change Zb = B.scheme at hB
  subst hA
  subst hB
  change A.HasRepresentableProperty P at hy
  change B.IsEtale at hz
  change A.obj A.scheme (eqToHom rfl) ≅ Yf at cA
  change B.obj B.scheme (eqToHom rfl) ≅ Zf at cB
  obtain ⟨P₀⟩ := hy.1 B.scheme (B.obj B.scheme (𝟙 B.scheme))
  have hfst : P P₀.fst := hy.2 _ _ P₀
  have hsnd : _root_.AlgebraicGeometry.Etale P₀.snd :=
    hz.2 A.scheme (A.obj A.scheme (𝟙 A.scheme))
      (StackChart.PullbackPresentation.swap A B P₀)
  let c : A.obj A.scheme (𝟙 A.scheme) ≅
      (stackPullback X φ.base).obj (B.obj B.scheme (𝟙 B.scheme)) :=
    cA ≪≫ asIso φ.fiber ≪≫ (stackPullback X φ.base).mapIso cB.symm
  let τ : A.scheme ⟶ P₀.space := P₀.lift φ.base (𝟙 A.scheme) c
  have hτ₁ : τ ≫ P₀.fst = φ.base := P₀.lift_fst _ _ _
  have hτ₂ : τ ≫ P₀.snd = 𝟙 A.scheme := P₀.lift_snd _ _ _
  have hτ : _root_.AlgebraicGeometry.Etale τ := by
    refine MorphismProperty.HasOfPostcompProperty.of_postcomp
      (W' := (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}))
      τ P₀.snd hsnd ?_
    rw [hτ₂]
    infer_instance
  rw [← hτ₁]
  exact P.comp_mem _ _ (hPE _ _ τ hτ) hfst

/-- A morphism between two small-étale objects of a stack is étale on underlying schemes. -/
theorem etale_base_of_hom_isEtaleObject {X : FppfStack.{u}} {y z : X.total}
    (hy : IsEtaleObject X y) (hz : IsEtaleObject X z) (φ : y ⟶ z) :
    _root_.AlgebraicGeometry.Etale φ.base := by
  obtain ⟨py, hpy⟩ := hy
  obtain ⟨pz, hpz⟩ := hz
  exact base_mem_of_hom X (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u})
    MorphismProperty.IsMultiplicative.toIsStableUnderComposition le_rfl φ py hpy pz hpz

/-- A morphism from a lisse object to a small-étale object of a stack is smooth on underlying
schemes. -/
theorem smooth_base_of_hom_isLisseObject {X : FppfStack.{u}} {y z : X.total}
    (hy : IsLisseObject X y) (hz : IsEtaleObject X z) (φ : y ⟶ z) :
    _root_.AlgebraicGeometry.Smooth φ.base := by
  obtain ⟨py, hpy⟩ := hy
  obtain ⟨pz, hpz⟩ := hz
  refine base_mem_of_hom X (@_root_.AlgebraicGeometry.Smooth : MorphismProperty Scheme.{u})
    inferInstance ?_ φ py hpy pz hpz
  intro _ _ f hf
  let _ := hf
  infer_instance

/-! ## Subsites of the total category of a stack -/

namespace StackSubsite

variable {X : FppfStack.{u}} {O : Type (u + 1)}

/-- The underlying-scheme functor of a full subcategory of the total category of a stack. -/
abbrev toScheme (ob : O → X.total) : InducedCategory X.total ob ⥤ Scheme.{u} :=
  inducedFunctor ob ⋙ X.projection

/-- The object family of a subsite of the total category of a stack *has étale lifts* if every
étale morphism of schemes into the underlying scheme of an object of the subsite is, up to an
isomorphism of its source, the underlying scheme morphism of a morphism of the subsite.  For
the small-étale and the lisse-étale site this is the statement that an étale, respectively
smooth, chart of the stack remains étale, respectively smooth, after precomposition with an
étale morphism of schemes. -/
def HasEtaleLifts (ob : O → X.total) : Prop :=
  ∀ (o : O) {W : Scheme.{u}} (g : W ⟶ (ob o).base),
    _root_.AlgebraicGeometry.Etale g →
      ∃ (o' : O) (φ : ob o' ⟶ ob o) (e : W ≅ (ob o').base), e.hom ≫ φ.base = g

variable {ob : O → X.total}

/-- Every morphism of the total category of a stack in groupoids is strongly cartesian over its
underlying scheme morphism. -/
theorem isStronglyCartesian_base {a b : X.total} (φ : a ⟶ b) :
    Functor.IsStronglyCartesian X.projection φ.base φ :=
  StackInGroupoids.isStronglyCartesian (F := X.toPseudofunctor) φ

/-- Every morphism of the total category lifts its underlying scheme morphism. -/
theorem isHomLift_base {a b : X.total} (φ : a ⟶ b) :
    Functor.IsHomLift X.projection φ.base φ :=
  Functor.IsHomLift.map (p := X.projection) φ

/-- A morphism of a subsite, viewed as a morphism of the total category. -/
abbrev toTotal {o o' : InducedCategory X.total ob} (φ : o' ⟶ o) : ob o' ⟶ ob o := φ.hom

/-- A morphism of the subsite whose underlying scheme morphism factors through the underlying
scheme morphism of a morphism of a sieve belongs to that sieve.  This uses that all morphisms
of the total category are strongly cartesian. -/
theorem mem_of_base_factors {o c o' : InducedCategory X.total ob} (S : Sieve o)
    {α : c ⟶ o} (hα : S.arrows α) (φ : o' ⟶ o)
    {k : (ob o').base ⟶ (ob c).base}
    (hk : (toTotal φ).base = k ≫ (toTotal α).base) : S.arrows φ := by
  have _hcart := isStronglyCartesian_base (toTotal α)
  have _hlift := isHomLift_base (toTotal φ)
  have hmem := S.downward_closed hα (InducedCategory.homMk
    (Functor.IsStronglyCartesian.map X.projection (toTotal α).base (toTotal α) hk (toTotal φ)))
  have hfac : InducedCategory.homMk
      (Functor.IsStronglyCartesian.map X.projection (toTotal α).base (toTotal α) hk
        (toTotal φ)) ≫ α = φ := by
    apply InducedCategory.hom_ext
    change Functor.IsStronglyCartesian.map X.projection (toTotal α).base (toTotal α) hk
      (toTotal φ) ≫ toTotal α = toTotal φ
    exact Functor.IsStronglyCartesian.fac _ _ _ _ _
  rwa [hfac] at hmem

/-- The covering presieves of a subsite of the total category of a stack: those generated by a
family of morphisms of the subsite whose underlying scheme morphisms are étale and generate a
covering sieve of the étale topology. -/
def etaleLiftCovering (ob : O → X.total) (o : InducedCategory X.total ob) :
    Set (Presieve o) :=
  {R | ∃ (I : Type (u + 1)) (sob : I → InducedCategory X.total ob)
      (arr : ∀ i, sob i ⟶ o),
      R = Presieve.ofArrows sob arr ∧
      (∀ i, _root_.AlgebraicGeometry.Etale (toTotal (arr i)).base) ∧
      Sieve.ofArrows (fun i ↦ (ob (sob i)).base) (fun i ↦ (toTotal (arr i)).base) ∈
        Scheme.etaleTopology ((ob o).base)}

/-- Étale morphisms of schemes form a class of morphisms stable under isomorphisms.  This is not
found by instance search in Mathlib, so it is recorded here for local use. -/
theorem etale_respectsIso : MorphismProperty.RespectsIso
    (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) :=
  MorphismProperty.IsStableUnderBaseChange.respectsIso

/-- The underlying scheme morphism of a composition. -/
theorem base_comp {a b c : X.total} (ψ : a ⟶ b) (χ : b ⟶ c) :
    (ψ ≫ χ).base = ψ.base ≫ χ.base :=
  X.projection.map_comp ψ χ

/-- Covering sieves of the étale topology only depend on the family of morphisms up to
factorisation: if every member of a covering family factors through a member of a second
family, the second family is covering as well. -/
theorem sieve_ofArrows_mem_of_factors {V : Scheme.{u}} {I J : Type*}
    {A : I → Scheme.{u}} {B : J → Scheme.{u}} (a : ∀ i, A i ⟶ V) (b : ∀ j, B j ⟶ V)
    (fac : ∀ i, ∃ (j : J) (t : A i ⟶ B j), a i = t ≫ b j)
    (ha : Sieve.ofArrows A a ∈ Scheme.etaleTopology V) :
    Sieve.ofArrows B b ∈ Scheme.etaleTopology V := by
  refine Scheme.etaleTopology.superset_covering ?_ ha
  rw [Sieve.generate_le_iff]
  rintro W g ⟨i⟩
  obtain ⟨j, t, ht⟩ := fac i
  exact (Sieve.mem_ofArrows_iff _ _ _).2 ⟨j, t, ht⟩

/-- The base change of a family of morphisms of schemes generating a covering sieve of the étale
topology again generates a covering sieve. -/
theorem sieve_ofArrows_pullback_mem {V V' : Scheme.{u}} {I : Type (u + 1)}
    {A : I → Scheme.{u}} (a : ∀ i, A i ⟶ V) (h : V' ⟶ V)
    (ha : Sieve.ofArrows A a ∈ Scheme.etaleTopology V) :
    Sieve.ofArrows (fun i ↦ Limits.pullback h (a i))
        (fun i ↦ Limits.pullback.fst h (a i)) ∈ Scheme.etaleTopology V' := by
  refine Scheme.etaleTopology.superset_covering ?_
    (Scheme.etaleTopology.pullback_stable h ha)
  intro U t ht
  obtain ⟨i, k, hk⟩ := (Sieve.mem_ofArrows_iff _ _ _).1 ht
  refine (Sieve.mem_ofArrows_iff _ _ _).2 ⟨i, Limits.pullback.lift t k hk, ?_⟩
  exact (Limits.pullback.lift_fst _ _ _).symm

/-- The coverage of a subsite whose covering presieves are the families of morphisms of the
subsite lifting an étale covering family of the underlying schemes. -/
def etaleLiftCoverage (hob : HasEtaleLifts ob) : Coverage (InducedCategory X.total ob) where
  coverings := etaleLiftCovering ob
  pullback := by
    rintro o o₂ f R ⟨I, sob, arr, rfl, harr, hcov⟩
    have hrespects : MorphismProperty.RespectsIso
        (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) :=
      MorphismProperty.IsStableUnderBaseChange.respectsIso
    have hfst : ∀ i, _root_.AlgebraicGeometry.Etale
        (Limits.pullback.fst (toTotal f).base (toTotal (arr i)).base) := fun i ↦
      MorphismProperty.of_isPullback (P := (@_root_.AlgebraicGeometry.Etale :
        MorphismProperty Scheme.{u})) (CategoryTheory.IsPullback.of_hasPullback _ _).flip (harr i)
    choose sob' arr' e he using fun i ↦ hob o₂
      (Limits.pullback.fst (toTotal f).base (toTotal (arr i)).base) (hfst i)
    have hbase : ∀ i, (arr' i).base =
        (e i).inv ≫ Limits.pullback.fst (toTotal f).base (toTotal (arr i)).base := by
      intro i
      rw [← he i, Iso.inv_hom_id_assoc]
    refine ⟨Presieve.ofArrows sob' (fun i ↦ InducedCategory.homMk (arr' i)), ?_, ?_⟩
    · refine ⟨I, sob', fun i ↦ InducedCategory.homMk (arr' i), rfl, fun i ↦ ?_, ?_⟩
      · change _root_.AlgebraicGeometry.Etale (arr' i).base
        rw [hbase i]
        exact (MorphismProperty.cancel_left_of_respectsIso
          (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) (e i).inv _).2 (hfst i)
      · refine sieve_ofArrows_mem_of_factors _ _ (fun i ↦ ⟨i, (e i).hom, (he i).symm⟩) ?_
        exact sieve_ofArrows_pullback_mem _ _ hcov
    · rintro Z g ⟨i⟩
      have _hcart := isStronglyCartesian_base (toTotal (arr i))
      have _hlift := isHomLift_base (arr' i ≫ toTotal f)
      have hfac : (arr' i ≫ toTotal f).base =
          ((e i).inv ≫ Limits.pullback.snd (toTotal f).base (toTotal (arr i)).base) ≫
            (toTotal (arr i)).base := by
        rw [base_comp, hbase i, Category.assoc, Category.assoc, Limits.pullback.condition]
      refine ⟨sob i, InducedCategory.homMk (Functor.IsStronglyCartesian.map X.projection
        (toTotal (arr i)).base (toTotal (arr i)) hfac (arr' i ≫ toTotal f)), arr i, ⟨i⟩, ?_⟩
      apply InducedCategory.hom_ext
      change Functor.IsStronglyCartesian.map X.projection (toTotal (arr i)).base
        (toTotal (arr i)) hfac (arr' i ≫ toTotal f) ≫ toTotal (arr i) = arr' i ≫ toTotal f
      exact Functor.IsStronglyCartesian.fac _ _ _ _ _

/-- A presheaf of the étale site of schemes, restricted to a subsite of the total category,
satisfies the sheaf condition for every lifted étale cover.  This is the step where the fibre
product of two members of the covering family is lifted to the subsite: the fibre product is
étale over the first member because the second member is étale, which is exactly the situation
covered by `HasEtaleLifts`. -/
theorem isSheafFor_etaleLiftCovering (hob : HasEtaleLifts ob)
    {P : Scheme.{u}ᵒᵖ ⥤ Type t} (hP : Presieve.IsSheaf Scheme.etaleTopology P)
    {o : InducedCategory X.total ob} {R : Presieve o}
    (hR : R ∈ etaleLiftCovering ob o) :
    Presieve.IsSheafFor ((toScheme ob).op ⋙ P) R := by
  obtain ⟨I, sob, arr, rfl, harr, hcov⟩ := hR
  have hPsheaf : Presieve.IsSheafFor P
      (Presieve.ofArrows (fun i ↦ (ob (sob i)).base) fun i ↦ (toTotal (arr i)).base) := by
    rw [Presieve.isSheafFor_iff_generate]
    exact hP _ hcov
  rw [Presieve.isSheafFor_arrows_iff] at hPsheaf ⊢
  intro x hx
  refine hPsheaf x ?_
  intro i j V a b hab
  have hfst : _root_.AlgebraicGeometry.Etale
      (Limits.pullback.fst (toTotal (arr i)).base (toTotal (arr j)).base) :=
    MorphismProperty.of_isPullback (P := (@_root_.AlgebraicGeometry.Etale :
      MorphismProperty Scheme.{u})) (CategoryTheory.IsPullback.of_hasPullback _ _).flip (harr j)
  obtain ⟨p, ψ, e, he⟩ := hob (sob i) _ hfst
  have hψ : ψ.base =
      e.inv ≫ Limits.pullback.fst (toTotal (arr i)).base (toTotal (arr j)).base := by
    rw [← he, Iso.inv_hom_id_assoc]
  have _hcart := isStronglyCartesian_base (toTotal (arr j))
  have _hlift := isHomLift_base (ψ ≫ toTotal (arr i))
  have hfac : (ψ ≫ toTotal (arr i)).base =
      (e.inv ≫ Limits.pullback.snd (toTotal (arr i)).base (toTotal (arr j)).base) ≫
        (toTotal (arr j)).base := by
    rw [base_comp, hψ, Category.assoc, Category.assoc, Limits.pullback.condition]
  obtain ⟨χ, hχlift, hχfac⟩ : ∃ χ : ob p ⟶ ob (sob j),
      Functor.IsHomLift X.projection
        (e.inv ≫ Limits.pullback.snd (toTotal (arr i)).base (toTotal (arr j)).base) χ ∧
      χ ≫ toTotal (arr j) = ψ ≫ toTotal (arr i) :=
    ⟨Functor.IsStronglyCartesian.map X.projection (toTotal (arr j)).base
      (toTotal (arr j)) hfac (ψ ≫ toTotal (arr i)),
      Functor.IsStronglyCartesian.map_isHomLift X.projection (toTotal (arr j)).base
        (toTotal (arr j)) hfac (ψ ≫ toTotal (arr i)),
      Functor.IsStronglyCartesian.fac _ _ _ _ _⟩
  have hχbase : χ.base =
      e.inv ≫ Limits.pullback.snd (toTotal (arr i)).base (toTotal (arr j)).base :=
    (@IsHomLift.eq_of_isHomLift _ _ _ _ X.projection (ob p) (ob (sob j)) _ χ hχlift).symm
  have hcompat := hx i j p (InducedCategory.homMk ψ) (InducedCategory.homMk χ) (by
    apply InducedCategory.hom_ext
    change ψ ≫ toTotal (arr i) = χ ≫ toTotal (arr j)
    exact hχfac.symm)
  have hva : (Limits.pullback.lift a b hab ≫ e.hom) ≫ ψ.base = a := by
    rw [Category.assoc, he, Limits.pullback.lift_fst]
  have hvb : (Limits.pullback.lift a b hab ≫ e.hom) ≫ χ.base = b := by
    rw [hχbase, Category.assoc, Iso.hom_inv_id_assoc, Limits.pullback.lift_snd]
  have key : ∀ (yi : P.obj (Opposite.op (ob (sob i)).base))
      (yj : P.obj (Opposite.op (ob (sob j)).base)),
      P.map ψ.base.op yi = P.map χ.base.op yj → P.map a.op yi = P.map b.op yj := by
    intro yi yj h
    have e1 : P.map a.op yi =
        P.map (Limits.pullback.lift a b hab ≫ e.hom).op (P.map ψ.base.op yi) := by
      rw [← types_comp_apply (P.map ψ.base.op)
        (P.map (Limits.pullback.lift a b hab ≫ e.hom).op), ← P.map_comp, ← op_comp, hva]
    have e2 : P.map b.op yj =
        P.map (Limits.pullback.lift a b hab ≫ e.hom).op (P.map χ.base.op yj) := by
      rw [← types_comp_apply (P.map χ.base.op)
        (P.map (Limits.pullback.lift a b hab ≫ e.hom).op), ← P.map_comp, ← op_comp, hvb]
    rw [e1, e2, h]
  exact key _ _ hcompat

/-- The underlying-scheme functor of a subsite with étale lifts is continuous for the topology
generated by the lifted étale covers. -/
theorem isContinuous_toScheme (hob : HasEtaleLifts ob) :
    (toScheme ob).IsContinuous (etaleLiftCoverage hob).toGrothendieck
      Scheme.etaleTopology where
  op_comp_isSheaf_of_types G := by
    rw [Presieve.isSheaf_coverage]
    intro o R hR
    exact isSheafFor_etaleLiftCovering hob
      ((isSheaf_iff_isSheaf_of_type _ _).1 G.2) hR

/-- Every sieve of a subsite with étale lifts which contains a lifted étale cover is a covering
sieve for the induced topology. -/
theorem mem_inducedTopology_of_le (hob : HasEtaleLifts ob)
    {o : InducedCategory X.total ob} {S : Sieve o} {R : Presieve o}
    (hR : R ∈ etaleLiftCovering ob o) (hRS : R ≤ S.arrows) :
    S ∈ (toScheme ob).inducedTopology Scheme.etaleTopology o := by
  have hle : (etaleLiftCoverage hob).toGrothendieck ≤
      (toScheme ob).inducedTopology Scheme.etaleTopology :=
    Functor.le_inducedTopology_iff.2 (isContinuous_toScheme hob)
  exact hle _ (Coverage.mem_toGrothendieck_sieves_of_superset _ hRS hR)

/-- **Reduction of `HasEtaleLifts` to a closure property of the object family.**  It suffices
that the canonical cartesian pullback of an object of the subsite along an étale morphism of
schemes is again an object of the subsite. -/
theorem hasEtaleLifts_of_domainCartesianLift_mem
    (h : ∀ (o : O) {W : Scheme.{u}} (g : W ⟶ (ob o).base),
      _root_.AlgebraicGeometry.Etale g →
        ∃ o' : O, ob o' = domainCartesianLift (ob o).fiber g) :
    HasEtaleLifts ob := by
  intro o W g hg
  obtain ⟨o', ho'⟩ := h o g hg
  refine ⟨o', eqToHom ho' ≫ cartesianLift (ob o).fiber g,
    eqToIso (congrArg (fun z : X.total ↦ z.base) ho').symm, ?_⟩
  have h1 : (eqToHom ho' : ob o' ⟶ domainCartesianLift (ob o).fiber g).base =
      eqToHom (congrArg (fun z : X.total ↦ z.base) ho') :=
    eqToHom_map X.projection ho'
  have hmap : (eqToHom ho' ≫ cartesianLift (ob o).fiber g).base =
      eqToHom (congrArg (fun z : X.total ↦ z.base) ho') ≫ g := by
    rw [base_comp, h1]
  rw [hmap, eqToIso.hom, ← Category.assoc, eqToHom_trans, eqToHom_refl, Category.id_comp]

/-- Covering sieves of the induced topology of a subsite push forward to covering sieves of the
étale topology of schemes. -/
theorem functorPushforward_mem_of_mem_inducedTopology {o : InducedCategory X.total ob}
    {S : Sieve o} (hS : S ∈ (toScheme ob).inducedTopology Scheme.etaleTopology o) :
    S.functorPushforward (toScheme ob) ∈ Scheme.etaleTopology ((ob o).base) :=
  (CoverPreserving.of_isContinuous (toScheme ob)
    ((toScheme ob).inducedTopology Scheme.etaleTopology) Scheme.etaleTopology).cover_preserve hS

/-- A sieve of a subsite with étale lifts whose pushforward to schemes is a covering sieve of the
étale topology contains a lifted étale cover.  Every arrow of the lifted cover lies in the sieve
because all arrows of the total category are strongly cartesian. -/
theorem exists_etaleLiftCovering_le (hob : HasEtaleLifts ob)
    {o : InducedCategory X.total ob} {S : Sieve o}
    (hS : S.functorPushforward (toScheme ob) ∈ Scheme.etaleTopology ((ob o).base)) :
    ∃ R ∈ etaleLiftCovering ob o, R ≤ S.arrows := by
  have hrespects := etale_respectsIso.{u}
  obtain ⟨𝒰, h𝒰⟩ := Scheme.mem_grothendieckTopology_iff.1 hS
  have hetale : ∀ i, _root_.AlgebraicGeometry.Etale (𝒰.f i) :=
    ((Scheme.ofArrows_mem_precoverage_iff _).1 𝒰.mem₀).2
  choose sob' arr' e he using fun i ↦ hob o (𝒰.f i) (hetale i)
  have harr : ∀ i, S.arrows (InducedCategory.homMk (arr' i)) := by
    intro i
    obtain ⟨c, g, h, hg, hfac⟩ := h𝒰 _ _ (Presieve.ofArrows.mk i)
    refine mem_of_base_factors S hg _ (k := (e i).inv ≫ h) ?_
    have h1 : (e i).inv ≫ 𝒰.f i = (arr' i).base := by
      rw [← he i, Iso.inv_hom_id_assoc]
    change (arr' i).base = ((e i).inv ≫ h) ≫ (toTotal g).base
    rw [← h1, hfac]
    exact (Category.assoc _ _ _).symm
  refine ⟨Presieve.ofArrows (fun j : ULift.{u + 1} 𝒰.I₀ ↦ sob' j.down)
    (fun j ↦ InducedCategory.homMk (arr' j.down)), ⟨_, _, _, rfl, fun j ↦ ?_, ?_⟩, ?_⟩
  · have h1 : _root_.AlgebraicGeometry.Etale ((e j.down).hom ≫ (arr' j.down).base) := by
      rw [he]
      exact hetale j.down
    exact (MorphismProperty.cancel_left_of_respectsIso
      (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) (e j.down).hom
      ((arr' j.down).base)).1 h1
  · refine sieve_ofArrows_mem_of_factors 𝒰.f _
      (fun i ↦ ⟨ULift.up i, (e i).hom, (he i).symm⟩) ?_
    exact 𝒰.mem_grothendieckTopology
  · rintro Z g ⟨j⟩
    exact harr j.down

/-- **The covering sieves of the induced topology of a subsite with étale lifts** are exactly the
sieves whose pushforward to schemes is a covering sieve of the étale topology. -/
theorem mem_inducedTopology_iff (hob : HasEtaleLifts ob)
    {o : InducedCategory X.total ob} (S : Sieve o) :
    S ∈ (toScheme ob).inducedTopology Scheme.etaleTopology o ↔
      S.functorPushforward (toScheme ob) ∈ Scheme.etaleTopology ((ob o).base) := by
  refine ⟨functorPushforward_mem_of_mem_inducedTopology, fun hS ↦ ?_⟩
  obtain ⟨R, hR, hRS⟩ := exists_etaleLiftCovering_le hob hS
  exact mem_inducedTopology_of_le hob hR hRS

end StackSubsite

/-! ## Charts precomposed with a morphism of schemes

This section provides the geometric input for `StackSubsite.HasEtaleLifts`: a chart of a stack
precomposed with a morphism of schemes with a representable property `P` again has the
representable property `P`, provided `P` is stable under base change and composition.  The two
coherence lemmas `SiteChart.inducedComparison_id` and `SiteChart.inducedComparison_comp` say
that the classification predicate `StackChart.Classifies` is reflexive and transitive; this
gives the uniqueness of chart pullback presentations up to a canonical isomorphism
(`SiteChart.presentationIso`) and hence the criterion
`SiteChart.hasRepresentableProperty_of_exists`, which only asks for *one* good presentation of
each base change. -/

namespace SiteChart

variable {X : FppfStack.{u}} (A : StackChart X)

set_option backward.isDefEq.respectTransparency false in
/-- Component formula for the pseudonaturality cell of a composite of stack morphisms. -/
theorem comp_naturality_app {Y Z : FppfStack.{u}}
    (η : StackHom Y Z) {Z' : FppfStack.{u}} (θ : StackHom Z Z') {S T : Scheme.{u}}
    (h : S ⟶ T) (y : StackFiber Y T) :
    ((Pseudofunctor.StrongTrans.vcomp η θ).naturality ⟨h.op⟩).hom.toNatTrans.app y =
      (θ.appFunctor S).map ((η.naturality ⟨h.op⟩).hom.toNatTrans.app y) ≫
        (θ.naturality ⟨h.op⟩).hom.toNatTrans.app ((η.appFunctor T).obj y) := by
  have hc := congrArg (fun k ↦ k.toNatTrans.app y)
    (Pseudofunctor.StrongTrans.categoryStruct_comp_naturality_hom η θ ⟨h.op⟩)
  change ((Pseudofunctor.StrongTrans.vcomp η θ).naturality ⟨h.op⟩).hom.toNatTrans.app y = _ at hc
  simp at hc
  exact hc.trans (Category.id_comp _)

/-- The chart obtained from `A` by precomposing with a morphism of schemes. -/
noncomputable def restrict {W : Scheme.{u}} (g : W ⟶ A.scheme) : StackChart X where
  scheme := W
  map := Pseudofunctor.StrongTrans.vcomp (FppfStack.mapOfSchemeHom g) A.map

@[simp]
theorem restrict_scheme {W : Scheme.{u}} (g : W ⟶ A.scheme) :
    (restrict A g).scheme = W := rfl

/-- The objects of a precomposed chart are the objects of the original chart at the composed
scheme maps. -/
theorem restrict_obj {W T : Scheme.{u}} (g : W ⟶ A.scheme) (f : T ⟶ W) :
    (restrict A g).obj T f = A.obj T (f ≫ g) := rfl

/-- The equality-induced isomorphisms of a precomposed chart are those of the original chart. -/
theorem restrict_objIsoOfEq {W T : Scheme.{u}} (g : W ⟶ A.scheme) {f f' : T ⟶ W}
    (h : f = f') :
    (restrict A g).objIsoOfEq h = A.objIsoOfEq (congrArg (· ≫ g) h) := by
  subst h; rfl

set_option backward.isDefEq.respectTransparency false in
/-- The pseudonaturality isomorphism of a precomposed chart is the one of the original chart at
the composed scheme map: the promoted scheme morphism contributes the identity, because the
fibres of a represented stack are discrete. -/
theorem restrict_objPullbackIso {W T S : Scheme.{u}} (g : W ⟶ A.scheme) (f : T ⟶ W)
    (m : S ⟶ T) :
    (restrict A g).objPullbackIso m f = A.objPullbackIso m (f ≫ g) := by
  apply Iso.ext
  have hc := comp_naturality_app (FppfStack.mapOfSchemeHom g) A.map m
    (Discrete.mk (ULift.up f))
  change ((restrict A g).map.naturality ⟨m.op⟩).hom.toNatTrans.app
    (Discrete.mk (ULift.up f)) = _ at hc
  change ((restrict A g).map.naturality ⟨m.op⟩).hom.toNatTrans.app (Discrete.mk (ULift.up f)) =
    (A.map.naturality ⟨m.op⟩).hom.toNatTrans.app (Discrete.mk (ULift.up (f ≫ g)))
  rw [hc]
  have hone : (((FppfStack.mapOfSchemeHom g).naturality
      (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op T) ⟶
        LocallyDiscrete.mk (Opposite.op S))).hom.toNatTrans.app
          (Discrete.mk (ULift.up f))) = 𝟙 _ := by
    change @Eq (ULift (PLift (_ = _))) _ _
    apply Subsingleton.elim
  have hid : (A.map.appFunctor S).map
      (((FppfStack.mapOfSchemeHom g).naturality
        (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op T) ⟶
          LocallyDiscrete.mk (Opposite.op S))).hom.toNatTrans.app
            (Discrete.mk (ULift.up f))) = 𝟙 _ := by
    rw [hone]
    exact (A.map.appFunctor S).map_id _
  rw [hid, Category.id_comp]
  rfl

set_option backward.isDefEq.respectTransparency false in
/-- The induced comparison of a precomposed chart is the induced comparison of the original
chart at the composed chart leg. -/
theorem restrict_inducedComparison {W U T S : Scheme.{u}} (g : W ⟶ A.scheme) (fst : U ⟶ T)
    (snd : U ⟶ W) {x : StackFiber X T}
    (universal : A.obj U (snd ≫ g) ≅ (stackPullback X fst).obj x) (m : S ⟶ U) :
    (restrict A g).inducedComparison fst snd universal m =
      A.inducedComparison fst (snd ≫ g) universal m := by
  apply Iso.ext
  simp only [StackChart.inducedComparison, Iso.trans_hom]
  rw [show ((Cat.Hom.toNatIso ((restrict A g).map.naturality
        (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op U) ⟶
          LocallyDiscrete.mk (Opposite.op S)))).app (Discrete.mk (ULift.up snd))).hom =
      ((Cat.Hom.toNatIso (A.map.naturality
        (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op U) ⟶
          LocallyDiscrete.mk (Opposite.op S)))).app
            (Discrete.mk (ULift.up (snd ≫ g)))).hom from
    congrArg Iso.hom (restrict_objPullbackIso A g snd m)]

set_option backward.isDefEq.respectTransparency false in
/-- The comparison induced along an identity is the original comparison: this is the unit
coherence of the stack pseudofunctor. -/
theorem inducedComparison_id {T U : Scheme.{u}} (fst : U ⟶ T) (snd : U ⟶ A.scheme)
    {x : StackFiber X T} (universal : A.obj U snd ≅ (stackPullback X fst).obj x) :
    A.inducedComparison fst snd universal (𝟙 U) = universal := by
  apply Iso.ext
  have hnat : A.map.naturality (⟨(𝟙 U).op⟩ : LocallyDiscrete.mk (Opposite.op U) ⟶
      LocallyDiscrete.mk (Opposite.op U)) = A.map.naturality (𝟙 _) := rfl
  have h0 : (stackPullbackCompIso X (𝟙 U) fst x).hom =
      (X.toPseudofunctor.mapComp (⟨fst.op⟩ : LocallyDiscrete.mk (Opposite.op T) ⟶
          LocallyDiscrete.mk (Opposite.op U))
        (𝟙 (LocallyDiscrete.mk (Opposite.op U)))).inv.toNatTrans.app x := rfl
  have h1 : ((representedStack A.scheme).toPseudofunctor.mapId
      (LocallyDiscrete.mk (Opposite.op U))).hom.toNatTrans.app
        (Discrete.mk (ULift.up snd)) = 𝟙 _ := by
    change @Eq (ULift (PLift (_ = _))) _ _
    apply Subsingleton.elim
  have h2 : (X.toPseudofunctor.mapId (LocallyDiscrete.mk (Opposite.op U))).inv.toNatTrans.app
        ((A.map.appFunctor U).obj (Discrete.mk (ULift.up snd))) ≫
        (stackPullback X (𝟙 U)).map universal.hom =
      universal.hom ≫ (X.toPseudofunctor.mapId
        (LocallyDiscrete.mk (Opposite.op U))).inv.toNatTrans.app
          ((stackPullback X fst).obj x) :=
    ((X.toPseudofunctor.mapId (LocallyDiscrete.mk (Opposite.op U))).inv.toNatTrans.naturality
      universal.hom).symm
  have h3 : (X.toPseudofunctor.mapId (LocallyDiscrete.mk (Opposite.op U))).inv.toNatTrans.app
        ((stackPullback X fst).obj x) ≫
      (X.toPseudofunctor.mapId (LocallyDiscrete.mk (Opposite.op U))).hom.toNatTrans.app
        ((stackPullback X fst).obj x) = 𝟙 _ := by
    simp
  have h4 : (X.toPseudofunctor.map₂ (Bicategory.rightUnitor
      (⟨fst.op⟩ : LocallyDiscrete.mk (Opposite.op T) ⟶
      LocallyDiscrete.mk (Opposite.op U))).inv).toNatTrans.app x = 𝟙 _ := by
    simp only [Bicategory.Strict.rightUnitor_eqToIso, eqToIso.inv, PrelaxFunctor.map₂_eqToHom,
      Cat.Hom₂.eqToHom_toNatTrans, eqToHom_app]
    apply eqToHom_refl
  simp only [StackChart.inducedComparison, Iso.trans_hom, Functor.mapIso_hom, Iso.app_hom,
    Cat.Hom.toNatIso_hom, hnat]
  rw [Pseudofunctor.StrongTrans.naturality_id_hom_app, h0,
    Pseudofunctor.mapComp_id_right_inv_app]
  simp only [h1, CategoryTheory.Functor.map_id, Category.id_comp, Category.assoc]
  rw [reassoc_of% h2, reassoc_of% h3, h4, Category.comp_id]

set_option backward.isDefEq.respectTransparency false in
/-- The comparison induced in two steps is the comparison induced along the composite: this is
the associativity coherence of the stack pseudofunctor. -/
theorem inducedComparison_comp {V U T S : Scheme.{u}} (fst : U ⟶ T) (snd : U ⟶ A.scheme)
    {x : StackFiber X T} (universal : A.obj U snd ≅ (stackPullback X fst).obj x)
    (k : V ⟶ U) (m : S ⟶ V) :
    A.inducedComparison (k ≫ fst) (k ≫ snd) (A.inducedComparison fst snd universal k) m =
      A.inducedComparison fst snd universal (m ≫ k) := by
  apply Iso.ext
  simp only [StackChart.inducedComparison, Iso.trans_hom, Functor.mapIso_hom,
    CategoryTheory.Functor.map_comp, Category.assoc, Iso.app_hom, Cat.Hom.toNatIso_hom]
  have hp := (Cat.Hom.toNatIso
    (X.toPseudofunctor.mapComp (⟨k.op⟩ : LocallyDiscrete.mk (Opposite.op U) ⟶
        LocallyDiscrete.mk (Opposite.op V))
      (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op V) ⟶
        LocallyDiscrete.mk (Opposite.op S)))).inv.naturality universal.hom
  change (stackPullback X m).map ((stackPullback X k).map universal.hom) ≫
      (stackPullbackCompIso X m k ((stackPullback X fst).obj x)).hom =
    (stackPullbackCompIso X m k (A.obj U snd)).hom ≫
      (stackPullback X (m ≫ k)).map universal.hom at hp
  rw [stackPullbackCompIso_assoc X m k fst x]
  rw [reassoc_of% hp]
  have hn : (A.map.naturality (⟨m.op⟩ : LocallyDiscrete.mk (Opposite.op V) ⟶
          LocallyDiscrete.mk (Opposite.op S))).hom.toNatTrans.app
            (Discrete.mk (ULift.up (k ≫ snd))) ≫
        (stackPullback X m).map ((A.map.naturality (⟨k.op⟩ :
            LocallyDiscrete.mk (Opposite.op U) ⟶
            LocallyDiscrete.mk (Opposite.op V))).hom.toNatTrans.app
              (Discrete.mk (ULift.up snd))) ≫
          (stackPullbackCompIso X m k (A.obj U snd)).hom =
      (A.map.appFunctor S).map
          (stackPullbackCompIso (representedStack A.scheme) m k
            (Discrete.mk (ULift.up snd))).hom ≫
        (A.map.naturality (⟨(m ≫ k).op⟩ : LocallyDiscrete.mk (Opposite.op U) ⟶
          LocallyDiscrete.mk (Opposite.op S))).hom.toNatTrans.app
            (Discrete.mk (ULift.up snd)) :=
    (stackHomNaturalityCompPullback A.map m k (Discrete.mk (ULift.up snd))).symm
  rw [reassoc_of% hn]
  have hobj : (A.map.appFunctor S).map
      (stackPullbackCompIso (representedStack A.scheme) m k
        (Discrete.mk (ULift.up snd))).hom = 𝟙 _ := by
    have hone : (stackPullbackCompIso (representedStack A.scheme) m k
        (Discrete.mk (ULift.up snd))).hom = 𝟙 _ := by
      change @Eq (ULift (PLift (_ = _))) _ _
      apply Subsingleton.elim
    rw [hone]
    exact (A.map.appFunctor S).map_id _
  have hrefl : stackPullbackObjIsoOfEq X (Category.assoc m k fst) x = Iso.refl _ := by
    rw [Subsingleton.elim (Category.assoc m k fst) rfl]
    rfl
  simp only [hobj, hrefl, Iso.refl_hom, Category.comp_id]
  exact Category.id_comp _

/-- The classification predicate, with prescribed witnesses for the two leg equations. -/
theorem classifies_iff {T U S : Scheme.{u}} {fst : U ⟶ T} {snd : U ⟶ A.scheme}
    {x : StackFiber X T} {universal : A.obj U snd ≅ (stackPullback X fst).obj x}
    {toBase : S ⟶ T} {toChart : S ⟶ A.scheme}
    {c : A.obj S toChart ≅ (stackPullback X toBase).obj x} {m : S ⟶ U}
    (fst_eq : m ≫ fst = toBase) (snd_eq : m ≫ snd = toChart) :
    A.Classifies fst snd universal toBase toChart c m ↔
      (A.objIsoOfEq snd_eq).symm.trans
        ((A.inducedComparison fst snd universal m).trans
          (stackPullbackObjIsoOfEq X fst_eq x)) = c := by
  constructor
  · rintro ⟨f, s, e⟩
    rw [Subsingleton.elim fst_eq f, Subsingleton.elim snd_eq s]
    exact e
  · intro e
    exact ⟨fst_eq, snd_eq, e⟩

/-- Reflexivity of the classification predicate. -/
theorem classifies_id {T U : Scheme.{u}} (fst : U ⟶ T) (snd : U ⟶ A.scheme)
    {x : StackFiber X T} (universal : A.obj U snd ≅ (stackPullback X fst).obj x) :
    A.Classifies fst snd universal fst snd universal (𝟙 U) := by
  refine ⟨rfl, rfl, ?_⟩
  rw [inducedComparison_id A fst snd universal]
  apply Iso.ext
  change 𝟙 (A.obj U snd) ≫ universal.hom ≫ 𝟙 ((stackPullback X fst).obj x) = universal.hom
  rw [Category.comp_id, Category.id_comp]

/-- Transitivity, and its converse, for the classification predicate. -/
theorem classifies_comp_iff {T U V S : Scheme.{u}} {fst : U ⟶ T} {snd : U ⟶ A.scheme}
    {x : StackFiber X T} {universal : A.obj U snd ≅ (stackPullback X fst).obj x}
    {toBase : V ⟶ T} {toChart : V ⟶ A.scheme}
    {c : A.obj V toChart ≅ (stackPullback X toBase).obj x}
    {toBase' : S ⟶ T} {toChart' : S ⟶ A.scheme}
    {c' : A.obj S toChart' ≅ (stackPullback X toBase').obj x}
    {m : V ⟶ U} {m' : S ⟶ V}
    (h : A.Classifies fst snd universal toBase toChart c m)
    (fst_eq' : m' ≫ toBase = toBase') (snd_eq' : m' ≫ toChart = toChart') :
    A.Classifies toBase toChart c toBase' toChart' c' m' ↔
      A.Classifies fst snd universal toBase' toChart' c' (m' ≫ m) := by
  obtain ⟨fst_eq, snd_eq, hc⟩ := h
  subst fst_eq
  subst snd_eq
  subst hc
  subst fst_eq'
  subst snd_eq'
  have hu : ((A.objIsoOfEq (rfl : m ≫ snd = m ≫ snd)).symm.trans
      ((A.inducedComparison fst snd universal m).trans
        (stackPullbackObjIsoOfEq X (rfl : m ≫ fst = m ≫ fst) x))) =
      A.inducedComparison fst snd universal m := by
    apply Iso.ext
    change 𝟙 (A.obj V (m ≫ snd)) ≫ (A.inducedComparison fst snd universal m).hom ≫
      𝟙 ((stackPullback X (m ≫ fst)).obj x) = (A.inducedComparison fst snd universal m).hom
    rw [Category.comp_id, Category.id_comp]
  have e1 : (m' ≫ m) ≫ fst = m' ≫ m ≫ fst := Category.assoc m' m fst
  have e2 : (m' ≫ m) ≫ snd = m' ≫ m ≫ snd := Category.assoc m' m snd
  rw [classifies_iff A (rfl : m' ≫ (m ≫ fst) = m' ≫ (m ≫ fst))
      (rfl : m' ≫ (m ≫ snd) = m' ≫ (m ≫ snd)),
    classifies_iff A e1 e2, hu, inducedComparison_comp A fst snd universal m m']
  exact Iff.rfl

/-- Transitivity of the classification predicate. -/
theorem classifies_comp {T U V S : Scheme.{u}} {fst : U ⟶ T} {snd : U ⟶ A.scheme}
    {x : StackFiber X T} {universal : A.obj U snd ≅ (stackPullback X fst).obj x}
    {toBase : V ⟶ T} {toChart : V ⟶ A.scheme}
    {c : A.obj V toChart ≅ (stackPullback X toBase).obj x}
    {toBase' : S ⟶ T} {toChart' : S ⟶ A.scheme}
    {c' : A.obj S toChart' ≅ (stackPullback X toBase').obj x}
    {m : V ⟶ U} {m' : S ⟶ V}
    (h : A.Classifies fst snd universal toBase toChart c m)
    (h' : A.Classifies toBase toChart c toBase' toChart' c' m') :
    A.Classifies fst snd universal toBase' toChart' c' (m' ≫ m) := by
  obtain ⟨f, s, e⟩ := h'
  exact (classifies_comp_iff A h f s).1 ⟨f, s, e⟩

/-- **Any two chart pullback presentations of the same base change are canonically
isomorphic.** -/
noncomputable def presentationIso {T : Scheme.{u}} {x : StackFiber X T}
    (p q : A.PullbackPresentation T x) : q.space ≅ p.space where
  hom := p.lift q.fst q.snd q.comparison
  inv := q.lift p.fst p.snd p.comparison
  hom_inv_id := by
    have h1 := q.lift_unique q.fst q.snd q.comparison
      (p.lift q.fst q.snd q.comparison ≫ q.lift p.fst p.snd p.comparison)
      (classifies_comp A (q.lift_compatible p.fst p.snd p.comparison)
        (p.lift_compatible q.fst q.snd q.comparison))
    have h2 := q.lift_unique q.fst q.snd q.comparison (𝟙 q.space)
      (classifies_id A q.fst q.snd q.comparison)
    exact h1.trans h2.symm
  inv_hom_id := by
    have h1 := p.lift_unique p.fst p.snd p.comparison
      (q.lift p.fst p.snd p.comparison ≫ p.lift q.fst q.snd q.comparison)
      (classifies_comp A (p.lift_compatible q.fst q.snd q.comparison)
        (q.lift_compatible p.fst p.snd p.comparison))
    have h2 := p.lift_unique p.fst p.snd p.comparison (𝟙 p.space)
      (classifies_id A p.fst p.snd p.comparison)
    exact h1.trans h2.symm

/-- The canonical isomorphism of two presentations is compatible with the projections. -/
theorem presentationIso_hom_fst {T : Scheme.{u}} {x : StackFiber X T}
    (p q : A.PullbackPresentation T x) :
    (presentationIso A p q).hom ≫ p.fst = q.fst :=
  p.lift_fst _ _ _

/-- **A chart has a representable property as soon as one presentation of each base change has
that property**, by the uniqueness of presentations up to isomorphism. -/
theorem hasRepresentableProperty_of_exists (P : MorphismProperty Scheme.{u})
    (hP : P.RespectsIso)
    (h : ∀ (T : Scheme.{u}) (x : StackFiber X T),
      ∃ p : A.PullbackPresentation T x, P p.fst) :
    A.HasRepresentableProperty P := by
  have _inst : P.RespectsIso := hP
  refine ⟨fun T x ↦ ⟨(h T x).choose⟩, fun T x q ↦ ?_⟩
  obtain ⟨p, hp⟩ := h T x
  have _inst2 : IsIso (presentationIso A p q).hom := (presentationIso A p q).isIso_hom
  rw [← presentationIso_hom_fst A p q]
  exact (MorphismProperty.cancel_left_of_respectsIso P (presentationIso A p q).hom p.fst).2 hp

/-- Reversing an equality-induced isomorphism. -/
theorem objIsoOfEq_symm {S : Scheme.{u}} {f f' : S ⟶ A.scheme} (h : f = f') :
    (A.objIsoOfEq h).symm = A.objIsoOfEq h.symm := by
  subst h; rfl

set_option backward.isDefEq.respectTransparency false in
/-- Classification for a precomposed chart is classification for the original chart, with both
chart legs composed with the precomposed scheme morphism. -/
theorem restrict_classifies_iff {W U T S : Scheme.{u}} (g : W ⟶ A.scheme) {fst : U ⟶ T}
    {snd : U ⟶ W} {x : StackFiber X T}
    {universal : A.obj U (snd ≫ g) ≅ (stackPullback X fst).obj x}
    {toBase : S ⟶ T} {toChart : S ⟶ W}
    {c : A.obj S (toChart ≫ g) ≅ (stackPullback X toBase).obj x} {m : S ⟶ U}
    (fst_eq : m ≫ fst = toBase) (snd_eq : m ≫ snd = toChart) :
    (restrict A g).Classifies fst snd universal toBase toChart c m ↔
      A.Classifies fst (snd ≫ g) universal toBase (toChart ≫ g) c m := by
  refine (classifies_iff (restrict A g) fst_eq snd_eq).trans
    (Iff.trans ?_ (classifies_iff A fst_eq
      (congrArg (· ≫ g) snd_eq : m ≫ snd ≫ g = toChart ≫ g)).symm)
  rw [restrict_objIsoOfEq, restrict_inducedComparison]

set_option backward.isDefEq.respectTransparency false in
/-- The second projection of the scheme pullback used below classifies the base-change data of
a precomposed chart. -/
theorem restrict_snd_classifies {W T : Scheme.{u}} (g : W ⟶ A.scheme) {x : StackFiber X T}
    (p : A.PullbackPresentation T x) :
    A.Classifies p.fst p.snd p.comparison (Limits.pullback.snd g p.snd ≫ p.fst)
      (Limits.pullback.fst g p.snd ≫ g)
      ((A.objIsoOfEq Limits.pullback.condition).trans
        (A.inducedComparison p.fst p.snd p.comparison (Limits.pullback.snd g p.snd)))
      (Limits.pullback.snd g p.snd) := by
  refine ⟨rfl, Limits.pullback.condition.symm, ?_⟩
  rw [objIsoOfEq_symm, show stackPullbackObjIsoOfEq X
      (rfl : Limits.pullback.snd g p.snd ≫ p.fst = Limits.pullback.snd g p.snd ≫ p.fst) x =
      Iso.refl _ from rfl, Iso.trans_refl]

set_option backward.isDefEq.respectTransparency false in
/-- **The base-change presentation of a precomposed chart**, built from a presentation of the
original chart and an ordinary pullback of schemes. -/
noncomputable def restrictPresentation {W T : Scheme.{u}} (g : W ⟶ A.scheme)
    {x : StackFiber X T} (p : A.PullbackPresentation T x) :
    (restrict A g).PullbackPresentation T x where
  space := Limits.pullback g p.snd
  fst := Limits.pullback.snd g p.snd ≫ p.fst
  snd := Limits.pullback.fst g p.snd
  comparison := (A.objIsoOfEq Limits.pullback.condition).trans
    (A.inducedComparison p.fst p.snd p.comparison (Limits.pullback.snd g p.snd))
  lift toBase toChart c := Limits.pullback.lift toChart
    (p.lift toBase (toChart ≫ g) c) (p.lift_snd toBase (toChart ≫ g) c).symm
  lift_fst toBase toChart c := by
    rw [← Category.assoc, Limits.pullback.lift_snd, p.lift_fst]
  lift_snd toBase toChart c := Limits.pullback.lift_fst _ _ _
  lift_compatible toBase toChart c := by
    have hfst : Limits.pullback.lift toChart (p.lift toBase (toChart ≫ g) c)
          (p.lift_snd toBase (toChart ≫ g) c).symm ≫
        (Limits.pullback.snd g p.snd ≫ p.fst) = toBase := by
      rw [← Category.assoc, Limits.pullback.lift_snd, p.lift_fst]
    have hsnd : Limits.pullback.lift toChart (p.lift toBase (toChart ≫ g) c)
          (p.lift_snd toBase (toChart ≫ g) c).symm ≫ Limits.pullback.fst g p.snd = toChart :=
      Limits.pullback.lift_fst _ _ _
    refine (restrict_classifies_iff A g hfst hsnd).mpr ?_
    refine (classifies_comp_iff A (restrict_snd_classifies A g p) hfst
      (congrArg (· ≫ g) hsnd)).mpr ?_
    rw [Limits.pullback.lift_snd]
    exact p.lift_compatible toBase (toChart ≫ g) c
  lift_unique toBase toChart c m compatible := by
    obtain ⟨hf, hs, he⟩ := compatible
    apply Limits.pullback.hom_ext
    · rw [Limits.pullback.lift_fst]
      exact hs
    · rw [Limits.pullback.lift_snd]
      refine p.lift_unique toBase (toChart ≫ g) c (m ≫ Limits.pullback.snd g p.snd) ?_
      refine (classifies_comp_iff A (restrict_snd_classifies A g p) hf
        (congrArg (· ≫ g) hs)).mp ?_
      exact (restrict_classifies_iff A g hf hs).mp ⟨hf, hs, he⟩

/-- **A chart precomposed with a morphism of schemes with a representable property `P` again has
the representable property `P`**, provided `P` is stable under base change and composition. -/
theorem restrict_hasRepresentableProperty (P : MorphismProperty Scheme.{u})
    (hPcomp : P.IsStableUnderComposition) (hPbc : P.IsStableUnderBaseChange)
    {W : Scheme.{u}} (g : W ⟶ A.scheme) (hg : P g)
    (hA : A.HasRepresentableProperty P) :
    (restrict A g).HasRepresentableProperty P := by
  have _inst : P.IsStableUnderComposition := hPcomp
  have _inst2 : P.IsStableUnderBaseChange := hPbc
  refine hasRepresentableProperty_of_exists (restrict A g) P
    MorphismProperty.IsStableUnderBaseChange.respectsIso ?_
  intro T x
  obtain ⟨p⟩ := hA.1 T x
  refine ⟨restrictPresentation A g p, ?_⟩
  change P (Limits.pullback.snd g p.snd ≫ p.fst)
  exact P.comp_mem _ _
    (MorphismProperty.of_isPullback (CategoryTheory.IsPullback.of_hasPullback g p.snd) hg)
    (hA.2 T x p)

end SiteChart

/-! ## The small-étale to lisse-étale inclusion -/

/-- The object family of the small-étale site of a Deligne--Mumford stack. -/
abbrev smallEtaleOb (X : DeligneMumfordStack.{u}) :
    SmallEtaleStackObject X → X.toStack.total :=
  fun z ↦ z.underlying

/-- The object family of the lisse-étale site of a stack. -/
abbrev lisseEtaleOb (X : FppfStack.{u}) : LisseEtaleObject X → X.total :=
  fun z ↦ z.underlying

/-- **The cartesian pullback of a small-étale object along an étale morphism of schemes is a
small-étale object.** -/
theorem isEtaleObject_domainCartesianLift {X : FppfStack.{u}} {z : X.total}
    (hz : IsEtaleObject X z) {W : Scheme.{u}} (g : W ⟶ z.base)
    (hg : _root_.AlgebraicGeometry.Etale g) :
    IsEtaleObject X (domainCartesianLift z.fiber g) := by
  have hrespects := StackSubsite.etale_respectsIso.{u}
  obtain ⟨pz, hpz⟩ := hz
  refine ⟨⟨SiteChart.restrict pz.chart (g ≫ eqToHom pz.chartScheme), rfl,
    (pz.chart.objPullbackIso g (eqToHom pz.chartScheme)).trans
      ((stackPullback X g).mapIso pz.comparison)⟩, ?_⟩
  refine SiteChart.restrict_hasRepresentableProperty pz.chart
    (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u})
    MorphismProperty.IsMultiplicative.toIsStableUnderComposition inferInstance _ ?_ hpz
  exact (MorphismProperty.cancel_right_of_respectsIso
    (@_root_.AlgebraicGeometry.Etale : MorphismProperty Scheme.{u}) g
    (eqToHom pz.chartScheme)).2 hg

/-- **The cartesian pullback of a lisse object along an étale morphism of schemes is a lisse
object.** -/
theorem isLisseObject_domainCartesianLift {X : FppfStack.{u}} {z : X.total}
    (hz : IsLisseObject X z) {W : Scheme.{u}} (g : W ⟶ z.base)
    (hg : _root_.AlgebraicGeometry.Etale g) :
    IsLisseObject X (domainCartesianLift z.fiber g) := by
  have hrespects : MorphismProperty.RespectsIso
      (@_root_.AlgebraicGeometry.Smooth : MorphismProperty Scheme.{u}) :=
    MorphismProperty.IsStableUnderBaseChange.respectsIso
  obtain ⟨pz, hpz⟩ := hz
  refine ⟨⟨SiteChart.restrict pz.chart (g ≫ eqToHom pz.chartScheme), rfl,
    (pz.chart.objPullbackIso g (eqToHom pz.chartScheme)).trans
      ((stackPullback X g).mapIso pz.comparison)⟩, ?_⟩
  refine SiteChart.restrict_hasRepresentableProperty pz.chart
    (@_root_.AlgebraicGeometry.Smooth : MorphismProperty Scheme.{u})
    inferInstance inferInstance _ ?_ hpz
  refine (MorphismProperty.cancel_right_of_respectsIso
    (@_root_.AlgebraicGeometry.Smooth : MorphismProperty Scheme.{u}) g
    (eqToHom pz.chartScheme)).2 ?_
  let _ := hg
  infer_instance

/-- For the small-étale site of a Deligne--Mumford stack, `HasEtaleLifts` is exactly the
stability of `IsEtaleObject` under cartesian base change along étale morphisms of schemes. -/
theorem hasEtaleLifts_smallEtaleOb (X : DeligneMumfordStack.{u})
    (h : ∀ z : X.toStack.total, IsEtaleObject X.toStack z → ∀ {W : Scheme.{u}}
      (g : W ⟶ z.base), _root_.AlgebraicGeometry.Etale g →
        IsEtaleObject X.toStack (domainCartesianLift z.fiber g)) :
    StackSubsite.HasEtaleLifts (smallEtaleOb X) :=
  StackSubsite.hasEtaleLifts_of_domainCartesianLift_mem
    (fun o _ g hg ↦ ⟨⟨domainCartesianLift o.underlying.fiber g, h _ o.etale g hg⟩, rfl⟩)

/-- For the lisse-étale site of a stack, `HasEtaleLifts` is exactly the stability of
`IsLisseObject` under cartesian base change along étale morphisms of schemes. -/
theorem hasEtaleLifts_lisseEtaleOb (X : FppfStack.{u})
    (h : ∀ z : X.total, IsLisseObject X z → ∀ {W : Scheme.{u}}
      (g : W ⟶ z.base), _root_.AlgebraicGeometry.Etale g →
        IsLisseObject X (domainCartesianLift z.fiber g)) :
    StackSubsite.HasEtaleLifts (lisseEtaleOb X) :=
  StackSubsite.hasEtaleLifts_of_domainCartesianLift_mem
    (fun o _ g hg ↦ ⟨⟨domainCartesianLift o.underlying.fiber g, h _ o.lisse g hg⟩, rfl⟩)

/-- **The small-étale site of a Deligne--Mumford stack has étale lifts.** -/
theorem hasEtaleLifts_smallEtale (X : DeligneMumfordStack.{u}) :
    StackSubsite.HasEtaleLifts (smallEtaleOb X) := by
  refine hasEtaleLifts_smallEtaleOb X ?_
  intro z hz W g hg
  exact isEtaleObject_domainCartesianLift hz g hg

/-- **The lisse-étale site of a stack has étale lifts.** -/
theorem hasEtaleLifts_lisseEtale (X : FppfStack.{u}) :
    StackSubsite.HasEtaleLifts (lisseEtaleOb X) := by
  refine hasEtaleLifts_lisseEtaleOb X ?_
  intro z hz W g hg
  exact isLisseObject_domainCartesianLift hz g hg

/-- **The covering sieves of the lisse-étale topology** are the sieves whose pushforward to
schemes is a covering sieve for the étale topology. -/
theorem mem_lisseEtaleStackTopology_iff (X : FppfStack.{u})
    (o : LisseEtaleStackSite X) (S : Sieve o) :
    S ∈ lisseEtaleStackTopology X o ↔
      S.functorPushforward (lisseEtaleToScheme X) ∈ Scheme.etaleTopology (o.underlying.base) :=
  StackSubsite.mem_inducedTopology_iff (hasEtaleLifts_lisseEtale X) S

/-- **The covering sieves of the small-étale topology of a Deligne--Mumford stack** are the
sieves whose pushforward to schemes is a covering sieve for the étale topology. -/
theorem mem_smallEtaleStackTopology_iff (X : DeligneMumfordStack.{u})
    (o : SmallEtaleStackSite X) (S : Sieve o) :
    S ∈ smallEtaleStackTopology X o ↔
      S.functorPushforward (smallEtaleStackToScheme X) ∈
        Scheme.etaleTopology (o.underlying.base) :=
  StackSubsite.mem_inducedTopology_iff (hasEtaleLifts_smallEtale X) S

/-- The small-étale inclusion preserves covering sieves: the covering sieves of both sites are
detected on the underlying schemes, and the inclusion does not change the underlying schemes. -/
theorem smallEtaleToLisse_coverPreserving (X : DeligneMumfordStack.{u}) :
    CoverPreserving (smallEtaleStackTopology X) (lisseEtaleStackTopology X.toStack)
      (smallEtaleToLisse X) := by
  constructor
  intro Z S hS
  rw [show lisseEtaleStackTopology X.toStack =
      (StackSubsite.toScheme (lisseEtaleOb X.toStack)).inducedTopology
        Scheme.etaleTopology from rfl,
    StackSubsite.mem_inducedTopology_iff (hasEtaleLifts_lisseEtale X.toStack),
    ← Sieve.functorPushforward_comp]
  exact StackSubsite.functorPushforward_mem_of_mem_inducedTopology hS

/-- The small-étale inclusion preserves compatible families of elements.  Given two morphisms
`f₁ : W ⟶ Y₁`, `f₂ : W ⟶ Y₂` from a lisse object into small-étale objects which agree after
composing with two morphisms `g₁ : Y₁ ⟶ Z`, `g₂ : Y₂ ⟶ Z` of the small-étale site, the fibre
product of the underlying schemes of `Y₁` and `Y₂` over that of `Z` carries a small-étale object
`P`: its first projection is étale because `g₂` is étale on underlying schemes.  Both `f₁` and
`f₂` factor through `P`, by the strong cartesianness of all morphisms of the total category. -/
theorem smallEtaleToLisse_compatiblePreserving (X : DeligneMumfordStack.{u}) :
    CompatiblePreserving.{t} (lisseEtaleStackTopology X.toStack) (smallEtaleToLisse X) := by
  have hrespects := StackSubsite.etale_respectsIso.{u}
  have hC : StackSubsite.HasEtaleLifts (smallEtaleOb X) := hasEtaleLifts_smallEtale X
  constructor
  intro ℱ Z T x hx Y₁ Y₂ W f₁ f₂ g₁ g₂ hg₁ hg₂ heq
  set a₁ : W.underlying ⟶ Y₁.underlying := f₁.hom with ha₁
  set a₂ : W.underlying ⟶ Y₂.underlying := f₂.hom with ha₂
  have heq' : a₁ ≫ g₁.hom = a₂ ≫ g₂.hom :=
    congrArg InducedCategory.Hom.hom heq
  clear_value a₁ a₂
  have hbase : a₁.base ≫ g₁.hom.base = a₂.base ≫ g₂.hom.base :=
    calc a₁.base ≫ g₁.hom.base = (a₁ ≫ g₁.hom).base :=
          (StackSubsite.base_comp _ _).symm
      _ = (a₂ ≫ g₂.hom).base := congrArg _ heq'
      _ = a₂.base ≫ g₂.hom.base := StackSubsite.base_comp _ _
  have hg₂etale : _root_.AlgebraicGeometry.Etale g₂.hom.base :=
    etale_base_of_hom_isEtaleObject Y₂.etale Z.etale g₂.hom
  have hfstEtale : _root_.AlgebraicGeometry.Etale
      (Limits.pullback.fst g₁.hom.base g₂.hom.base) :=
    MorphismProperty.of_isPullback (P := (@_root_.AlgebraicGeometry.Etale :
      MorphismProperty Scheme.{u})) (CategoryTheory.IsPullback.of_hasPullback _ _).flip hg₂etale
  obtain ⟨Pobj, q₁, e, he⟩ := hC Y₁ _ hfstEtale
  let P : SmallEtaleStackSite X := Pobj
  have hq₁base : q₁.base =
      e.inv ≫ Limits.pullback.fst g₁.hom.base g₂.hom.base := by
    rw [← he, Iso.inv_hom_id_assoc]
  -- the second projection of the fibre product, as a morphism of the total category
  have _hcart₂ := StackSubsite.isStronglyCartesian_base g₂.hom
  have _hlift₂ := StackSubsite.isHomLift_base (q₁ ≫ g₁.hom)
  have hfac₂ : (q₁ ≫ g₁.hom).base =
      (e.inv ≫ Limits.pullback.snd g₁.hom.base g₂.hom.base) ≫ g₂.hom.base := by
    rw [StackSubsite.base_comp, hq₁base, Category.assoc, Category.assoc,
      Limits.pullback.condition]
  obtain ⟨q₂, hq₂lift, hq₂fac⟩ : ∃ q₂ : Pobj.underlying ⟶ Y₂.underlying,
      Functor.IsHomLift X.toStack.projection
        (e.inv ≫ Limits.pullback.snd g₁.hom.base g₂.hom.base) q₂ ∧
      q₂ ≫ g₂.hom = q₁ ≫ g₁.hom :=
    ⟨Functor.IsStronglyCartesian.map X.toStack.projection g₂.hom.base g₂.hom hfac₂
      (q₁ ≫ g₁.hom),
      Functor.IsStronglyCartesian.map_isHomLift X.toStack.projection g₂.hom.base g₂.hom hfac₂
        (q₁ ≫ g₁.hom),
      Functor.IsStronglyCartesian.fac _ _ _ _ _⟩
  have hq₂base : q₂.base = e.inv ≫ Limits.pullback.snd g₁.hom.base g₂.hom.base :=
    (@IsHomLift.eq_of_isHomLift _ _ _ _ X.toStack.projection Pobj.underlying Y₂.underlying
      _ q₂ hq₂lift).symm
  -- the factorisation of `f₁` and `f₂` through `P`
  have _hcart₁ := StackSubsite.isStronglyCartesian_base q₁
  have _hlift₁ := StackSubsite.isHomLift_base a₁
  have hfacu : a₁.base =
      (Limits.pullback.lift a₁.base a₂.base hbase ≫ e.hom) ≫ q₁.base := by
    rw [hq₁base]
    simp only [Category.assoc, Iso.hom_inv_id_assoc]
    exact (Limits.pullback.lift_fst _ _ _).symm
  obtain ⟨v, hvlift, hvfac⟩ : ∃ v : W.underlying ⟶ Pobj.underlying,
      Functor.IsHomLift X.toStack.projection
        (Limits.pullback.lift a₁.base a₂.base hbase ≫ e.hom) v ∧ v ≫ q₁ = a₁ :=
    ⟨Functor.IsStronglyCartesian.map X.toStack.projection q₁.base q₁ hfacu a₁,
      Functor.IsStronglyCartesian.map_isHomLift X.toStack.projection q₁.base q₁ hfacu a₁,
      Functor.IsStronglyCartesian.fac _ _ _ _ _⟩
  have hvbase : v.base = Limits.pullback.lift a₁.base a₂.base hbase ≫ e.hom :=
    (@IsHomLift.eq_of_isHomLift _ _ _ _ X.toStack.projection W.underlying Pobj.underlying
      _ v hvlift).symm
  have hvq₂base : (v ≫ q₂).base = a₂.base := by
    rw [StackSubsite.base_comp, hvbase, hq₂base, Category.assoc, Iso.hom_inv_id_assoc,
      Limits.pullback.lift_snd]
  have hvq₂ : v ≫ q₂ = a₂ := by
    have hf' : (a₁ ≫ g₁.hom).base = a₂.base ≫ g₂.hom.base := by
      rw [StackSubsite.base_comp, hbase]
    have _hl₀ := StackSubsite.isHomLift_base (a₁ ≫ g₁.hom)
    have _hl₁ : Functor.IsHomLift X.toStack.projection a₂.base (v ≫ q₂) :=
      hvq₂base ▸ StackSubsite.isHomLift_base (v ≫ q₂)
    have _hl₂ := StackSubsite.isHomLift_base a₂
    have e1 : (v ≫ q₂) = Functor.IsStronglyCartesian.map X.toStack.projection g₂.hom.base
        g₂.hom hf' (a₁ ≫ g₁.hom) := by
      refine Functor.IsStronglyCartesian.map_uniq X.toStack.projection g₂.hom.base g₂.hom
        hf' (a₁ ≫ g₁.hom) (v ≫ q₂) ?_
      rw [Category.assoc, hq₂fac, ← Category.assoc, hvfac]
    have e2 : a₂ = Functor.IsStronglyCartesian.map X.toStack.projection g₂.hom.base
        g₂.hom hf' (a₁ ≫ g₁.hom) :=
      Functor.IsStronglyCartesian.map_uniq X.toStack.projection g₂.hom.base g₂.hom
        hf' (a₁ ≫ g₁.hom) a₂ heq'.symm
    exact e1.trans e2.symm
  -- conclude with the compatibility of `x` at the two projections
  let Q₁ : P ⟶ Y₁ := InducedCategory.homMk q₁
  let Q₂ : P ⟶ Y₂ := InducedCategory.homMk q₂
  let V : W ⟶ (smallEtaleToLisse X).obj P := InducedCategory.homMk v
  have hQ : Q₁ ≫ g₁ = Q₂ ≫ g₂ := by
    apply InducedCategory.hom_ext
    change q₁ ≫ g₁.hom = q₂ ≫ g₂.hom
    exact hq₂fac.symm
  have hcompat := hx Q₁ Q₂ hg₁ hg₂ hQ
  have hf₁ : V ≫ (smallEtaleToLisse X).map Q₁ = f₁ := by
    apply InducedCategory.hom_ext
    change v ≫ q₁ = f₁.hom
    rw [← ha₁]
    exact hvfac
  have hf₂ : V ≫ (smallEtaleToLisse X).map Q₂ = f₂ := by
    apply InducedCategory.hom_ext
    change v ≫ q₂ = f₂.hom
    rw [← ha₂]
    exact hvq₂
  have key : ∀ (yi : ℱ.obj.obj (Opposite.op ((smallEtaleToLisse X).obj Y₁)))
      (yj : ℱ.obj.obj (Opposite.op ((smallEtaleToLisse X).obj Y₂))),
      ℱ.obj.map ((smallEtaleToLisse X).map Q₁).op yi =
        ℱ.obj.map ((smallEtaleToLisse X).map Q₂).op yj →
      ℱ.obj.map f₁.op yi = ℱ.obj.map f₂.op yj := by
    intro yi yj h
    have e1 : ℱ.obj.map f₁.op yi =
        ℱ.obj.map V.op (ℱ.obj.map ((smallEtaleToLisse X).map Q₁).op yi) := by
      rw [← types_comp_apply (ℱ.obj.map _) (ℱ.obj.map _), ← ℱ.obj.map_comp, ← op_comp, hf₁]
    have e2 : ℱ.obj.map f₂.op yj =
        ℱ.obj.map V.op (ℱ.obj.map ((smallEtaleToLisse X).map Q₂).op yj) := by
      rw [← types_comp_apply (ℱ.obj.map _) (ℱ.obj.map _), ← ℱ.obj.map_comp, ← op_comp, hf₂]
    rw [e1, e2, h]
  exact key _ _ hcompat

/-- **The small-étale to lisse-étale inclusion is a continuous functor of sites.** -/
instance smallEtaleToLisse_isContinuous (X : DeligneMumfordStack.{u}) :
    (smallEtaleToLisse X).IsContinuous (smallEtaleStackTopology X)
      (lisseEtaleStackTopology X.toStack) :=
  Functor.isContinuous_of_coverPreserving
    (smallEtaleToLisse_compatiblePreserving X)
    (smallEtaleToLisse_coverPreserving X)

/-- **The inclusion of the small-étale site of a Deligne--Mumford stack into its lisse-étale
site, as a morphism of ringed sites.**  The structure-sheaf comparison is the identity: both
structure sheaves are the regular functions of the underlying scheme, and the inclusion does not
change the underlying scheme. -/
def smallEtaleToLisseRingedSiteMorphism (X : DeligneMumfordStack.{u}) :
    RingedSiteMorphism.{u + 1, u + 1, u + 1} (canonicalSmallEtaleRingedSite X)
      (canonicalLisseEtaleRingedSite X.toStack) where
  siteFunctor := smallEtaleToLisse X
  continuous := smallEtaleToLisse_isContinuous X
  structureIso := Iso.refl _

/-- Restriction of module sheaves from the lisse-étale site of a Deligne--Mumford stack to its
small-étale site. -/
noncomputable def smallEtaleToLisseModules (X : DeligneMumfordStack.{u}) :
    (canonicalLisseEtaleRingedSite X.toStack).Modules ⥤
      (canonicalSmallEtaleRingedSite X).Modules :=
  (smallEtaleToLisseRingedSiteMorphism X).moduleInverseImage

/-! ## The lisse-étale to big fppf inclusion

Only cover preservation is proved: the covering sieves of the lisse-étale topology push forward
to étale covering sieves of the underlying schemes, hence to fppf covering sieves, which by
`mem_bigFppfStackTopology_iff` is exactly membership in the big fppf topology of the stack.  The
compatibility statement for this inclusion does *not* follow by the argument used for the
small-étale inclusion: the fibre product of two lisse objects over a third has underlying scheme
the fibre product of the underlying schemes, and its projections need not be smooth, because a
morphism of lisse objects need not be smooth on underlying schemes (only
`smooth_base_of_hom_isLisseObject`, whose target is *étale*, is available). -/

/-- The inclusion of the lisse-étale site of a stack into its big fppf site preserves covering
sieves. -/
theorem lisseEtaleForget_coverPreserving (X : FppfStack.{u}) :
    CoverPreserving (lisseEtaleStackTopology X) (bigFppfStackTopology X)
      (lisseEtaleForget X) := by
  constructor
  intro Z S hS
  rw [mem_bigFppfStackTopology_iff, ← Sieve.functorPushforward_comp]
  exact etaleTopology_le_fppfTopology _
    (StackSubsite.functorPushforward_mem_of_mem_inducedTopology hS)

end GromovWitten.AlgebraicGeometry.Sites

