/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude Opus 5
-/

import GromovWitten.AlgebraicGeometry.CotangentComplex.TransitivityEtale
import Mathlib.RingTheory.Etale.StandardEtale
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.RingTheory.Unramified.LocalStructure
import Mathlib.RingTheory.LocalProperties.Exactness

/-!
# Standard étale base change of `H⁻¹` of the cotangent complex

`Transitivity.lean` proves that `jzH1BaseChange R S T : H⁻¹(L_{S/R}) ⊗_S T ⟶ H⁻¹(L_{T/R})` is
*surjective* for `S → T` formally étale and `T` flat over `S`, and `TransitivityEtale.lean`
upgrades this to *bijectivity* when `T` is a localization of `S`.  This file proves bijectivity
when `T` is **standard étale** over `S` (`Algebra.IsStandardEtale S T`, i.e.
`T ≃ (S[x]/f)[1/g]` with `f` monic and `f'` invertible), and for composites of a localization
followed by a standard étale map.

## Main results

* `Transitivity.bijective_liftBaseChange_h1CotangentMap`: *presentation independence*.  If `Q` is
  any extension of `T` over `R` with `Q.Ring` formally smooth over `R`, and
  `f : (Generators.self R S).toExtension.Hom Q` is a hom of extensions for which
  `(Extension.H1Cotangent.map f).liftBaseChange T` is bijective, then
  `(Algebra.H1Cotangent.map R R S T).liftBaseChange T` is bijective.  This is what allows one to
  feed Mathlib's `Algebra.Extension.tensorH1CotangentOfFormallyEtale` a *convenient* presentation
  of `T`, rather than the tautological one (which can never work, see `TransitivityEtale.lean`).
* `Transitivity.bijective_liftBaseChange_comp`: the base change map is compatible with composing
  `R → S → A → T`.
* `Transitivity.bijective_mapKer_liftBaseChange`: flatness of `P.Ring → Q.Ring` together with
  `Q.ker = P.ker · Q.Ring` gives the `H₂` hypothesis of `tensorH1CotangentOfFormallyEtale`.
* `Transitivity.LiftedPair` / `Transitivity.nonempty_liftedPair`: a standard étale pair over `S`
  can be lifted along any surjection `A ↠ S`.  Only `f` lifts on the nose; the localization
  polynomial `g` is *defined* from lifted Bézout witnesses of `P.cond`, hence only lifts a
  positive power `g ^ (exp + 1)` of `g`.  `LiftedPair.lift_surjective` and
  `LiftedPair.ker_lift_le` show the lifted standard étale `A`-algebra still surjects onto `T`
  with kernel generated by `ker (A ↠ S)`.
* `Transitivity.bijective_liftBaseChange_of_isStandardEtale`,
  `Transitivity.tensorH1CotangentOfIsStandardEtale`,
  `Transitivity.bijective_jzH1BaseChange_of_isStandardEtale`,
  `Transitivity.hNegOneBaseChangeIso_of_isStandardEtale`: the isomorphism
  `H⁻¹(L_{S/R}) ⊗_S T ≅ H⁻¹(L_{T/R})` for `T` standard étale over `S`.
* `Transitivity.span_standardEtaleAwaySet_eq_top`: the local structure theorem, packaged as
  "the `r : T` with `T[1/r]` standard étale over `S` generate the unit ideal".
* `Transitivity.bijective_liftBaseChange_of_etale`,
  `Transitivity.tensorH1CotangentOfEtale`, `Transitivity.bijective_jzH1BaseChange_of_etale`,
  `Transitivity.hNegOneBaseChangeIso_of_etale`, and the equivalent formally-étale-plus-finite-
  presentation forms `Transitivity.bijective_jzH1BaseChange_of_formallyEtale` and
  `Transitivity.hNegOneBaseChangeIso`: **the main results.**  For `T` étale over `S`,
  `jzH1BaseChange R S T : H⁻¹(L_{S/R}) ⊗_S T ⟶ H⁻¹(L_{T/R})` is an isomorphism.  The proof
  localizes on `T`: `Module.bijective_of_isLocalized_span` reduces bijectivity to the standard
  étale localizations `T[1/r]` produced by `Algebra.IsEtaleAt.exists_isStandardEtale`, using that
  both `T ⊗[S] H¹(L_{S/R})` (via `IsLocalizedModule.rTensor`) and `H¹(L_{T/R})` (via Mathlib's
  `Algebra.H1Cotangent.isLocalizedModule`) commute with those localizations.

## Not done

Formally étale maps that are *not* of finite presentation (e.g. arbitrary localizations that are
not `Localization.Away`, or infinite ind-étale extensions) are not covered by
`bijective_liftBaseChange_of_etale`; for arbitrary localizations use
`Transitivity.bijective_jzH1BaseChange_of_isLocalization` (in `TransitivityEtale.lean`)
instead.  A common generalization
covering both would need a version of the local structure theorem without finite presentation,
which is not available in Mathlib.
-/

universe u

namespace GromovWitten.AlgebraicGeometry.CotangentComplex

open CategoryTheory

open scoped TensorProduct

namespace Transitivity

section Transport

variable (R S T : Type u) [CommRing R] [CommRing S] [CommRing T]
variable [Algebra R S] [Algebra R T] [Algebra S T] [IsScalarTower R S T]

/-- The canonical hom of extensions from the tautological presentation
`MvPolynomial T R ↠ T` to an arbitrary extension `Q` of `T` over `R`, obtained by sending the
variable `X t` to the chosen preimage `Q.σ t`. -/
noncomputable def homSelfExtension (Q : Algebra.Extension.{u} R T) :
    (Algebra.Generators.self R T).toExtension.Hom Q where
  toRingHom := (MvPolynomial.aeval (R := R) Q.σ).toRingHom
  toRingHom_algebraMap := (MvPolynomial.aeval (R := R) Q.σ).commutes
  algebraMap_toRingHom := by
    have h : (IsScalarTower.toAlgHom R Q.Ring T).comp (MvPolynomial.aeval (R := R) Q.σ) =
        IsScalarTower.toAlgHom R (Algebra.Generators.self R T).toExtension.Ring T := by
      ext i
      change _ = algebraMap (Algebra.Generators.self R T).Ring T (.X i)
      simp
    exact DFunLike.congr_fun h

/-- **Presentation independence for the Jacobi–Zariski base change map.**  If some extension `Q`
of `T` over `R` with formally smooth `Q.Ring` receives a hom `f` from the tautological
presentation of `S` over `R` for which the base-changed map on `H¹` is bijective, then the
canonical map `T ⊗[S] H¹(L_{S/R}) → H¹(L_{T/R})` is bijective. -/
theorem bijective_liftBaseChange_h1CotangentMap {Q : Algebra.Extension.{u} R T}
    [hsm : Algebra.FormallySmooth R Q.Ring]
    (f : (Algebra.Generators.self R S).toExtension.Hom Q)
    (hb : Function.Bijective ((Algebra.Extension.H1Cotangent.map f).liftBaseChange T)) :
    Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  have _ : Algebra.FormallySmooth R (Algebra.Generators.self R T).toExtension.Ring :=
    inferInstanceAs (Algebra.FormallySmooth R (MvPolynomial T R))
  have key : Algebra.Extension.H1Cotangent.map f =
      (Algebra.Extension.H1Cotangent.map (homSelfExtension R T Q)).restrictScalars S ∘ₗ
        (Algebra.H1Cotangent.map R R S T) := by
    rw [Algebra.H1Cotangent.map, ← Algebra.Extension.H1Cotangent.map_comp]
    exact Algebra.Extension.H1Cotangent.map_eq _ _
  have hbg : Function.Bijective
      (Algebra.Extension.H1Cotangent.map (homSelfExtension R T Q)) := by
    rw [← Algebra.Extension.H1Cotangent.equivOfFormallySmooth_toLinearMap
      (homSelfExtension R T Q)]
    exact (Algebra.Extension.H1Cotangent.equivOfFormallySmooth _ _).bijective
  rw [key, ← LinearMap.liftBaseChange_comp, LinearMap.coe_comp] at hb
  exact (Function.Bijective.of_comp_iff' hbg _).mp hb

/-- Functoriality of `Algebra.H1Cotangent.map` in the middle algebra of a tower
`R → S → A → T`. -/
theorem h1CotangentMap_comp (A : Type u) [CommRing A] [Algebra R A] [Algebra S A] [Algebra A T]
    [IsScalarTower R S A] [IsScalarTower R A T] [IsScalarTower S A T] :
    Algebra.H1Cotangent.map R R S T =
      (Algebra.H1Cotangent.map R R A T).restrictScalars S ∘ₗ
        Algebra.H1Cotangent.map R R S A := by
  rw [Algebra.H1Cotangent.map, Algebra.H1Cotangent.map, Algebra.H1Cotangent.map,
    ← Algebra.Extension.H1Cotangent.map_comp]
  exact Algebra.Extension.H1Cotangent.map_eq _ _

/-- The Jacobi–Zariski base change map is compatible with composition: if it is bijective for
`R → S → A` and for `R → A → T`, then it is bijective for `R → S → T`. -/
theorem bijective_liftBaseChange_comp (A : Type u) [CommRing A] [Algebra R A] [Algebra S A]
    [Algebra A T] [IsScalarTower R S A] [IsScalarTower R A T] [IsScalarTower S A T]
    (h₁ : Function.Bijective ((Algebra.H1Cotangent.map R R S A).liftBaseChange A))
    (h₂ : Function.Bijective ((Algebra.H1Cotangent.map R R A T).liftBaseChange T)) :
    Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  set e : (A ⊗[S] Algebra.H1Cotangent R S) ≃ₗ[A] Algebra.H1Cotangent R A :=
    LinearEquiv.ofBijective _ h₁ with he
  set G := TensorProduct.AlgebraTensorModule.congr (LinearEquiv.refl T T) e with hG
  set H := (TensorProduct.AlgebraTensorModule.cancelBaseChange S A T T
    (Algebra.H1Cotangent R S)).symm with hH
  have hpt : ∀ z, (Algebra.H1Cotangent.map R R S T).liftBaseChange T z =
      (Algebra.H1Cotangent.map R R A T).liftBaseChange T (G (H z)) := by
    intro z
    induction z with
    | zero => simp
    | tmul t x =>
      have hx : (Algebra.H1Cotangent.map R R S T) x =
          (Algebra.H1Cotangent.map R R A T) ((Algebra.H1Cotangent.map R R S A) x) :=
        congr($(h1CotangentMap_comp R S T A) x)
      simp only [hH, hG, he, LinearMap.liftBaseChange_tmul,
        TensorProduct.AlgebraTensorModule.cancelBaseChange_symm_tmul,
        TensorProduct.AlgebraTensorModule.congr_tmul, LinearEquiv.refl_apply,
        LinearEquiv.ofBijective_apply, one_smul, hx]
    | add x y hx hy => simp only [map_add, hx, hy]
  have hfun : ⇑((Algebra.H1Cotangent.map R R S T).liftBaseChange T) =
      (⇑((Algebra.H1Cotangent.map R R A T).liftBaseChange T)) ∘ (⇑G ∘ ⇑H) := funext hpt
  rw [hfun]
  exact h₂.comp (G.bijective.comp H.bijective)

end Transport

section KerBaseChange

variable {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]
variable [Algebra R S] [Algebra R T] [Algebra S T] [IsScalarTower R S T]

omit [IsScalarTower R S T] in
/-- If `P.Ring → Q.Ring` is flat and `Q.ker` is generated by the image of `P.ker`, then
`Q.Ring ⊗[P.Ring] P.ker → Q.ker` is bijective.  This is the `H₂` hypothesis of Mathlib's
`Algebra.Extension.tensorH1CotangentOfFormallyEtale`. -/
theorem bijective_mapKer_liftBaseChange {P : Algebra.Extension.{u} R S}
    {Q : Algebra.Extension.{u} R T} (f : P.Hom Q) [alg : Algebra P.Ring Q.Ring]
    (halg : algebraMap P.Ring Q.Ring = f.toRingHom) [hflat : Module.Flat P.Ring Q.Ring]
    (hker : Q.ker ≤ Ideal.map (algebraMap P.Ring Q.Ring) P.ker) :
    Function.Bijective ((f.mapKer halg).liftBaseChange Q.Ring) := by
  set m := (f.mapKer halg).liftBaseChange Q.Ring with hm
  set n := ((Algebra.linearMap P.Ring Q.Ring).comp P.ker.subtype).liftBaseChange Q.Ring with hn
  have hcomp : ∀ z, ((m z : Q.Ring)) = n z := by
    intro z
    induction z with
    | zero => simp
    | tmul c x =>
      simp only [hm, hn, LinearMap.liftBaseChange_tmul, LinearMap.coe_comp, Function.comp_apply,
        Submodule.coe_subtype, Algebra.linearMap_apply, SetLike.val_smul, smul_eq_mul, halg]
      rfl
    | add x y hx hy => simp only [map_add, Submodule.coe_add, hx, hy]
  have hnval : ∀ z, n z =
      TensorProduct.rid P.Ring Q.Ring (LinearMap.lTensor Q.Ring P.ker.subtype z) := by
    intro z
    induction z with
    | zero => simp
    | tmul c x =>
      simp only [hn, LinearMap.liftBaseChange_tmul, LinearMap.coe_comp, Function.comp_apply,
        Submodule.coe_subtype, Algebra.linearMap_apply, LinearMap.lTensor_tmul,
        TensorProduct.rid_tmul, Algebra.smul_def]
      simp [mul_comm]
    | add x y hx hy => simp only [map_add, hx, hy]
  have hninj : Function.Injective n := by
    have h1 : Function.Injective
        (LinearMap.lTensor Q.Ring (P.ker.subtype : P.ker →ₗ[P.Ring] P.Ring)) :=
      Module.Flat.lTensor_preserves_injective_linearMap _ Subtype.val_injective
    intro x y hxy
    apply h1
    apply (TensorProduct.rid P.Ring Q.Ring).injective
    rw [← hnval, ← hnval, hxy]
  constructor
  · intro x y hxy
    apply hninj
    rw [← hcomp, ← hcomp, hxy]
  · rintro ⟨j, hj⟩
    have hle : Ideal.map (algebraMap P.Ring Q.Ring) P.ker ≤ LinearMap.range n :=
      Ideal.map_le_iff_le_comap.mpr fun x hx ↦ ⟨1 ⊗ₜ ⟨x, hx⟩, by simp [hn]⟩
    obtain ⟨z, hz⟩ := hle (hker hj)
    exact ⟨z, Subtype.ext ((hcomp z).trans hz)⟩

end KerBaseChange

section Lift

open Polynomial

variable {A S : Type*} [CommRing A] [CommRing S] [Algebra A S]

/-- The data of a lift of a standard étale pair `P` over `S` to a standard étale pair over a
ring `A` surjecting onto `S`.  The polynomial `f` is lifted on the nose, whereas `g` is only
lifted up to replacing it by a positive power `g ^ (exp + 1)`: the Bézout witnesses of `P.cond`
do not lift compatibly, so one *defines* the lift of `g` out of lifted Bézout witnesses. -/
structure LiftedPair (P : StandardEtalePair S) (A : Type*) [CommRing A] [Algebra A S] where
  /-- The lifted standard étale pair over `A`. -/
  pair : StandardEtalePair A
  /-- The exponent: `pair.g` lifts `P.g ^ (exp + 1)`. -/
  exp : ℕ
  /-- `pair.f` lifts `P.f`. -/
  map_f : pair.f.map (algebraMap A S) = P.f
  /-- `pair.g` lifts the positive power `P.g ^ (exp + 1)` of `P.g`. -/
  map_g : pair.g.map (algebraMap A S) = P.g ^ (exp + 1)

/-- A standard étale pair over `S` can be lifted along any surjection `A ↠ S`. -/
theorem nonempty_liftedPair (hsurj : Function.Surjective (algebraMap A S))
    (P : StandardEtalePair S) : Nonempty (LiftedPair P A) := by
  have hmap : Function.Surjective (Polynomial.map (algebraMap A S)) :=
    Polynomial.map_surjective _ hsurj
  obtain ⟨F, hF, -, hFm⟩ := Polynomial.lifts_and_natDegree_eq_and_monic
    (f := (algebraMap A S : A →+* S)) (p := P.f) (hmap P.f) P.monic_f
  obtain ⟨p₁, p₂, n, he⟩ := P.cond
  obtain ⟨q₁, hq₁⟩ := hmap p₁
  obtain ⟨q₂, hq₂⟩ := hmap p₂
  obtain ⟨G₀, hG₀⟩ := hmap P.g
  refine ⟨⟨⟨F, hFm, derivative F * (q₁ * G₀) + F * (q₂ * G₀),
    ⟨q₁ * G₀, q₂ * G₀, 1, (pow_one _).symm⟩⟩, n, hF, ?_⟩⟩
  simp only [Polynomial.map_add, Polynomial.map_mul, ← Polynomial.derivative_map, hF, hq₁, hq₂,
    hG₀]
  linear_combination P.g * he

section Map

section Target

variable {B : Type*} [CommRing B] [Algebra S B] [Algebra A B] [IsScalarTower A S B]

/-- Evaluating the lifted `g` at a point of an `S`-algebra gives a power of the value of `g`. -/
theorem LiftedPair.aeval_g {P : StandardEtalePair S} (L : LiftedPair P A) (x : B) :
    Polynomial.aeval x L.pair.g = (Polynomial.aeval x P.g : B) ^ (L.exp + 1) := by
  rw [← Polynomial.aeval_map_algebraMap S x L.pair.g, L.map_g, map_pow]

/-- A lifted pair has a map wherever the original pair does. -/
theorem LiftedPair.hasMap {P : StandardEtalePair S} (L : LiftedPair P A) {x : B}
    (h : P.HasMap x) : L.pair.HasMap x := by
  refine ⟨?_, ?_⟩
  · rw [← Polynomial.aeval_map_algebraMap S x L.pair.f, L.map_f]
    exact h.1
  · rw [L.aeval_g x]
    exact h.2.pow _

end Target

variable {T : Type*} [CommRing T] [Algebra S T] [Algebra A T] [IsScalarTower A S T]

/-- The lift of a standard étale presentation of `T` over `S` to a standard étale pair over `A`
still surjects onto `T`. -/
theorem LiftedPair.lift_surjective (hsurj : Function.Surjective (algebraMap A S))
    (Pres : StandardEtalePresentation S T) (L : LiftedPair Pres.P A) :
    Function.Surjective (L.pair.lift Pres.x (L.hasMap Pres.hasMap)) := by
  set φ := L.pair.lift Pres.x (L.hasMap Pres.hasMap) with hφ
  have hlift : φ L.pair.X = Pres.x := L.pair.lift_X _ _
  have hxmem : Pres.x ∈ φ.range := ⟨L.pair.X, hlift⟩
  have hSmem : ∀ s : S, algebraMap S T s ∈ φ.range := by
    intro s
    obtain ⟨a, rfl⟩ := hsurj s
    refine ⟨algebraMap A L.pair.Ring a, ?_⟩
    rw [← IsScalarTower.algebraMap_apply A S T a]
    exact φ.commutes a
  have haev : ∀ p : Polynomial S, Polynomial.aeval Pres.x p ∈ φ.range := by
    intro p
    induction p using Polynomial.induction_on' with
    | add p q hp hq => simpa using add_mem hp hq
    | monomial n s =>
      rw [Polynomial.aeval_monomial]
      exact mul_mem (hSmem s) (pow_mem hxmem n)
  set a : T := Polynomial.aeval Pres.x Pres.g with ha
  have hamem : a ∈ φ.range := haev _
  set b : T := φ ↑(StandardEtalePair.hasMap_X (P := L.pair)).2.unit⁻¹ with hb
  have hbmem : b ∈ φ.range := ⟨_, rfl⟩
  have h1 : (Polynomial.aeval Pres.x L.pair.g : T) =
      φ (Polynomial.aeval L.pair.X L.pair.g) := by
    rw [← Polynomial.aeval_algHom_apply, hlift]
  have hab : a ^ (L.exp + 1) * b = 1 := by
    rw [← L.aeval_g Pres.x, h1, hb, ← map_mul,
      (StandardEtalePair.hasMap_X (P := L.pair)).2.mul_val_inv, map_one]
  have hw : a * (a ^ L.exp * b) = 1 := by
    rw [← mul_assoc, ← pow_succ']
    exact hab
  intro t
  obtain ⟨p, n, hpn⟩ := Pres.exists_mul_aeval_x_g_pow_eq_aeval_x t
  have haw : a ^ n * (a ^ L.exp * b) ^ n = 1 := by rw [← mul_pow, hw, one_pow]
  have ht : t = Polynomial.aeval Pres.x p * (a ^ L.exp * b) ^ n := by
    calc t = t * (a ^ n * (a ^ L.exp * b) ^ n) := by rw [haw, mul_one]
      _ = t * a ^ n * (a ^ L.exp * b) ^ n := by ring
      _ = Polynomial.aeval Pres.x p * (a ^ L.exp * b) ^ n := by
        rw [← ha] at hpn
        rw [hpn]
  have : t ∈ φ.range := by
    rw [ht]
    exact mul_mem (haev p) (pow_mem (mul_mem (pow_mem hamem _) hbmem) n)
  obtain ⟨y, hy⟩ := this
  exact ⟨y, hy⟩

/-- Any `A`-algebra map out of the lifted standard étale algebra which kills the kernel of
`A ↠ S` factors through the surjection onto `T`. -/
theorem LiftedPair.exists_comp_eq (hsurj : Function.Surjective (algebraMap A S))
    (Pres : StandardEtalePresentation S T) (L : LiftedPair Pres.P A) {D : Type*} [CommRing D]
    [Algebra A D] (hI : RingHom.ker (Algebra.ofId A S).toRingHom ≤
      RingHom.ker (Algebra.ofId A D).toRingHom) (u : L.pair.Ring →ₐ[A] D) :
    ∃ ψ : T →ₐ[A] D, ψ.comp (L.pair.lift Pres.x (L.hasMap Pres.hasMap)) = u := by
  let σ : S →ₐ[A] D := AlgHom.liftOfSurjective (Algebra.ofId A S) hsurj (Algebra.ofId A D) hI
  let _ : Algebra S D := σ.toRingHom.toAlgebra
  have _ : IsScalarTower A S D :=
    .of_algebraMap_eq fun a ↦ (AlgHom.liftOfSurjective_apply _ hsurj _ hI a).symm
  have hfz : Polynomial.aeval (u L.pair.X) Pres.P.f = (0 : D) := by
    rw [← L.map_f, Polynomial.aeval_map_algebraMap S, Polynomial.aeval_algHom_apply,
      (StandardEtalePair.hasMap_X (P := L.pair)).1, map_zero]
  have hgu : IsUnit (Polynomial.aeval (u L.pair.X) Pres.P.g : D) := by
    have h2 : IsUnit (Polynomial.aeval (u L.pair.X) L.pair.g : D) := by
      rw [Polynomial.aeval_algHom_apply]
      exact (StandardEtalePair.hasMap_X (P := L.pair)).2.map u
    rw [L.aeval_g (u L.pair.X), pow_succ'] at h2
    exact isUnit_of_mul_isUnit_left h2
  refine ⟨((Pres.P.lift (u L.pair.X) ⟨hfz, hgu⟩).comp
    Pres.equivRing.toAlgHom).restrictScalars A, ?_⟩
  refine StandardEtalePair.hom_ext ?_
  change (Pres.P.lift (u L.pair.X) ⟨hfz, hgu⟩) (Pres.equivRing
    (L.pair.lift Pres.x (L.hasMap Pres.hasMap) L.pair.X)) = u L.pair.X
  rw [L.pair.lift_X, Pres.equivRing_x]
  exact Pres.P.lift_X _ _

/-- The kernel of the lift is generated by the kernel of `A ↠ S`. -/
theorem LiftedPair.ker_lift_le (hsurj : Function.Surjective (algebraMap A S))
    (Pres : StandardEtalePresentation S T) (L : LiftedPair Pres.P A) :
    RingHom.ker (L.pair.lift Pres.x (L.hasMap Pres.hasMap)).toRingHom ≤
      Ideal.map (algebraMap A L.pair.Ring) (RingHom.ker (algebraMap A S)) := by
  intro j hj
  obtain ⟨ψ, hψ⟩ := L.exists_comp_eq hsurj Pres
    (D := L.pair.Ring ⧸ Ideal.map (algebraMap A L.pair.Ring) (RingHom.ker (algebraMap A S)))
    (fun i hi ↦ by
      simp only [RingHom.mem_ker] at hi ⊢
      change algebraMap A (L.pair.Ring ⧸ _) i = 0
      rw [IsScalarTower.algebraMap_apply A L.pair.Ring _]
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_map_of_mem _ hi))
    (Ideal.Quotient.mkₐ A _)
  rw [← Ideal.Quotient.eq_zero_iff_mem]
  have h := DFunLike.congr_fun hψ j
  simp only [AlgHom.coe_comp, Function.comp_apply] at h
  rw [show (Ideal.Quotient.mkₐ A (Ideal.map (algebraMap A L.pair.Ring)
      (RingHom.ker (algebraMap A S)))) j = Ideal.Quotient.mk _ j from rfl] at h
  rw [← h, show (L.pair.lift Pres.x (L.hasMap Pres.hasMap)) j = 0 from hj, map_zero]

end Map

end Lift

section ExtensionOfSurjective

variable {R T C : Type u} [CommRing R] [CommRing T] [CommRing C] [Algebra R C] [Algebra R T]

/-- `Algebra.Extension.ofSurjective` spelled as an `abbrev`, so that the underlying ring of
the resulting extension is *reducibly* the given ring `C`; this is what makes instance search
for `C`-instances work on `(extensionOfSurjective φ hφ).Ring`. -/
noncomputable abbrev extensionOfSurjective (φ : C →ₐ[R] T) (hφ : Function.Surjective φ) :
    Algebra.Extension.{u} R T where
  Ring := C
  algebra₂ := φ.toAlgebra
  isScalarTower := letI := φ.toAlgebra; IsScalarTower.of_algebraMap_eq' φ.comp_algebraMap.symm
  σ x := (hφ x).choose
  algebraMap_σ x := (hφ x).choose_spec

end ExtensionOfSurjective

noncomputable section Main

variable (R S T : Type u) [CommRing R] [CommRing S] [CommRing T]
variable [Algebra R S] [Algebra R T] [Algebra S T] [IsScalarTower R S T]

/-- **Standard étale base change for `H¹` of the (naive) cotangent complex.**  If `T` is a
standard étale `S`-algebra then `T ⊗[S] H¹(L_{S/R}) → H¹(L_{T/R})` is bijective. -/
theorem bijective_liftBaseChange_of_isStandardEtale [Algebra.IsStandardEtale S T] :
    Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  obtain ⟨Pres⟩ := (Algebra.IsStandardEtale.nonempty_standardEtalePresentation :
    Nonempty (StandardEtalePresentation S T))
  let P : Algebra.Extension.{u} R S := (Algebra.Generators.self R S).toExtension
  let _ : Algebra P.Ring T := ((algebraMap S T).comp (algebraMap P.Ring S)).toAlgebra
  have _ : IsScalarTower P.Ring S T := .of_algebraMap_eq' rfl
  have _ : IsScalarTower R P.Ring T := by
    refine .of_algebraMap_eq fun r ↦ ?_
    rw [IsScalarTower.algebraMap_apply P.Ring S T, ← IsScalarTower.algebraMap_apply R P.Ring S,
      ← IsScalarTower.algebraMap_apply R S T]
  obtain ⟨L⟩ := nonempty_liftedPair (A := P.Ring) P.algebraMap_surjective Pres.P
  let _ : Algebra R L.pair.Ring :=
    ((algebraMap P.Ring L.pair.Ring).comp (algebraMap R P.Ring)).toAlgebra
  have _ : IsScalarTower R P.Ring L.pair.Ring := .of_algebraMap_eq' rfl
  have _ : Algebra.FormallySmooth R P.Ring :=
    inferInstanceAs (Algebra.FormallySmooth R (MvPolynomial S R))
  have _ : Algebra.FormallySmooth R L.pair.Ring := .comp R P.Ring L.pair.Ring
  let φ : L.pair.Ring →ₐ[P.Ring] T := L.pair.lift Pres.x (L.hasMap Pres.hasMap)
  have hφs : Function.Surjective φ := L.lift_surjective P.algebraMap_surjective Pres
  let hom : P.Hom (extensionOfSurjective (φ.restrictScalars R) hφs) :=
    { toRingHom := algebraMap P.Ring L.pair.Ring
      toRingHom_algebraMap := fun _ ↦ rfl
      algebraMap_toRingHom := fun x ↦ φ.commutes x }
  have H₁ : (algebraMap P.Ring L.pair.Ring).FormallyEtale :=
    RingHom.formallyEtale_algebraMap.mpr inferInstance
  have H₂ := bijective_mapKer_liftBaseChange hom rfl
    (L.ker_lift_le P.algebraMap_surjective Pres)
  refine bijective_liftBaseChange_h1CotangentMap R S T hom ?_
  exact (Algebra.Extension.tensorH1CotangentOfFormallyEtale hom rfl H₁ H₂).bijective

/-- The isomorphism `T ⊗[S] H¹(L_{S/R}) ≃ H¹(L_{T/R})` for `T` standard étale over `S`; the
standard étale analogue of Mathlib's `Algebra.tensorH1CotangentOfIsLocalization`. -/
def tensorH1CotangentOfIsStandardEtale [Algebra.IsStandardEtale S T] :
    T ⊗[S] Algebra.H1Cotangent R S ≃ₗ[T] Algebra.H1Cotangent R T :=
  LinearEquiv.ofBijective _ (bijective_liftBaseChange_of_isStandardEtale R S T)

/-- If `A` is a localization of `S` and `T` is standard étale over `A`, then the base change map
`T ⊗[S] H¹(L_{S/R}) → H¹(L_{T/R})` is bijective. -/
theorem bijective_liftBaseChange_of_isLocalization_of_isStandardEtale (A : Type u) [CommRing A]
    [Algebra R A] [Algebra S A] [Algebra A T] [IsScalarTower R S A] [IsScalarTower R A T]
    [IsScalarTower S A T] (M : Submonoid S) [IsLocalization M A] [Algebra.IsStandardEtale A T] :
    Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  refine bijective_liftBaseChange_comp R S T A ?_
    (bijective_liftBaseChange_of_isStandardEtale R A T)
  rw [← Algebra.tensorH1CotangentOfIsLocalization_toLinearMap R A M]
  exact (Algebra.tensorH1CotangentOfIsLocalization R A M).bijective

/-- Bijectivity of `jzH1BaseChange` is exactly bijectivity of Mathlib's base change map on
`H¹` of the cotangent complex. -/
theorem bijective_jzH1BaseChange_iff :
    Function.Bijective (jzH1BaseChange R S T).hom ↔
      Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  rw [jzH1BaseChange_hom_eq]
  exact Function.Bijective.of_comp_iff'
    (f := (Full.cohomologyNegOne R T).toLinearEquiv.symm.toLinearMap)
    (Full.cohomologyNegOne R T).toLinearEquiv.symm.bijective
    ((Algebra.H1Cotangent.map R R S T).liftBaseChange T)

/-- Along a standard étale map `S → T`, `jzH1BaseChange` is bijective. -/
theorem bijective_jzH1BaseChange_of_isStandardEtale [Algebra.IsStandardEtale S T] :
    Function.Bijective (jzH1BaseChange R S T).hom :=
  (bijective_jzH1BaseChange_iff R S T).mpr (bijective_liftBaseChange_of_isStandardEtale R S T)

/-- If `A` is a localization of `S` and `T` is standard étale over `A`, then `jzH1BaseChange`
is bijective for `R → S → T`. -/
theorem bijective_jzH1BaseChange_of_isLocalization_of_isStandardEtale (A : Type u) [CommRing A]
    [Algebra R A] [Algebra S A] [Algebra A T] [IsScalarTower R S A] [IsScalarTower R A T]
    [IsScalarTower S A T] (M : Submonoid S) [IsLocalization M A] [Algebra.IsStandardEtale A T] :
    Function.Bijective (jzH1BaseChange R S T).hom :=
  (bijective_jzH1BaseChange_iff R S T).mpr
    (bijective_liftBaseChange_of_isLocalization_of_isStandardEtale R S T A M)

/-- The isomorphism `H⁻¹(L_{S/R}) ⊗_S T ≅ H⁻¹(L_{T/R})` for `T` standard étale over `S`. -/
noncomputable def hNegOneBaseChangeIso_of_isStandardEtale [Algebra.IsStandardEtale S T] :
    ModuleCat.of T (T ⊗[S] Algebra.H1Cotangent R S) ≅
      Full.cohomology (Full.cotangentComplex R T) (-1) :=
  haveI : IsIso (jzH1BaseChange R S T) :=
    (ConcreteCategory.isIso_iff_bijective _).mpr
      (bijective_jzH1BaseChange_of_isStandardEtale R S T)
  asIso (jzH1BaseChange R S T)

/-- The set of `r : T` such that `T[1/r]` has a standard étale presentation over `S`. -/
def standardEtaleAwaySet : Set T :=
  {r : T | Nonempty (StandardEtalePresentation S (Localization.Away r))}

/-- For `T` étale over `S`, the elements `r` with `T[1/r]` standard étale over `S` generate the
unit ideal: this is the local structure theorem for étale algebras. -/
theorem span_standardEtaleAwaySet_eq_top [Algebra.Etale S T] :
    Ideal.span (standardEtaleAwaySet S T) = ⊤ := by
  by_contra hne
  obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hne
  have _ : m.IsPrime := hm.isPrime
  obtain ⟨g, hg, hstd⟩ := Algebra.IsEtaleAt.exists_isStandardEtale (R := S) m
  exact hg (hle (Ideal.subset_span
    (hstd.nonempty_standardEtalePresentation : Nonempty (StandardEtalePresentation S _))))

/-- **Étale base change for `H¹` of the (naive) cotangent complex.**  If `T` is an étale
`S`-algebra then `T ⊗[S] H¹(L_{S/R}) → H¹(L_{T/R})` is bijective.  The proof localizes on `T`:
by the local structure theorem `T` is a standard étale `S`-algebra after inverting each element
of a family generating the unit ideal, and both sides of the map commute with such
localizations. -/
theorem bijective_liftBaseChange_of_etale [Algebra.Etale S T] :
    Function.Bijective ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) := by
  refine bijective_of_isLocalized_span (standardEtaleAwaySet S T)
    (span_standardEtaleAwaySet_eq_top S T)
    (fun r ↦ Localization.Away r.1 ⊗[S] Algebra.H1Cotangent R S)
    (fun r ↦ TensorProduct.AlgebraTensorModule.rTensor S (Algebra.H1Cotangent R S)
      (Algebra.linearMap T (Localization.Away r.1)))
    (fun r ↦ Algebra.H1Cotangent R (Localization.Away r.1))
    (fun r ↦ Algebra.H1Cotangent.map R R T (Localization.Away r.1))
    ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) (fun r ↦ ?_)
  have hstd : Algebra.IsStandardEtale S (Localization.Away r.1) := ⟨r.2⟩
  have key : IsLocalizedModule.map (Submonoid.powers r.1)
      (TensorProduct.AlgebraTensorModule.rTensor S (Algebra.H1Cotangent R S)
        (Algebra.linearMap T (Localization.Away r.1)))
      (Algebra.H1Cotangent.map R R T (Localization.Away r.1))
      ((Algebra.H1Cotangent.map R R S T).liftBaseChange T) =
      ((Algebra.H1Cotangent.map R R S (Localization.Away r.1)).liftBaseChange
        (Localization.Away r.1)).restrictScalars T := by
    refine IsLocalizedModule.linearMap_ext (Submonoid.powers r.1)
      (TensorProduct.AlgebraTensorModule.rTensor S (Algebra.H1Cotangent R S)
        (Algebra.linearMap T (Localization.Away r.1)))
      (Algebra.H1Cotangent.map R R T (Localization.Away r.1)) ?_
    rw [IsLocalizedModule.map_comp]
    ext x
    have hx := congr($(h1CotangentMap_comp R S (Localization.Away r.1) T) x)
    simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.coe_restrictScalars,
      TensorProduct.AlgebraTensorModule.curry_apply, TensorProduct.curry_apply,
      TensorProduct.AlgebraTensorModule.rTensor_tmul, Algebra.linearMap_apply, map_one,
      LinearMap.liftBaseChange_tmul, one_smul] at hx ⊢
    rw [hx]
  rw [key]
  exact bijective_liftBaseChange_of_isStandardEtale R S (Localization.Away r.1)

/-- Along an étale map `S → T`, `jzH1BaseChange` is bijective. -/
theorem bijective_jzH1BaseChange_of_etale [Algebra.Etale S T] :
    Function.Bijective (jzH1BaseChange R S T).hom :=
  (bijective_jzH1BaseChange_iff R S T).mpr (bijective_liftBaseChange_of_etale R S T)

/-- The isomorphism `T ⊗[S] H¹(L_{S/R}) ≃ H¹(L_{T/R})` for `T` étale over `S`. -/
def tensorH1CotangentOfEtale [Algebra.Etale S T] :
    T ⊗[S] Algebra.H1Cotangent R S ≃ₗ[T] Algebra.H1Cotangent R T :=
  LinearEquiv.ofBijective _ (bijective_liftBaseChange_of_etale R S T)

/-- The isomorphism `H⁻¹(L_{S/R}) ⊗_S T ≅ H⁻¹(L_{T/R})` for `T` étale over `S`. -/
def hNegOneBaseChangeIso_of_etale [Algebra.Etale S T] :
    ModuleCat.of T (T ⊗[S] Algebra.H1Cotangent R S) ≅
      Full.cohomology (Full.cotangentComplex R T) (-1) :=
  haveI : IsIso (jzH1BaseChange R S T) :=
    (ConcreteCategory.isIso_iff_bijective _).mpr (bijective_jzH1BaseChange_of_etale R S T)
  asIso (jzH1BaseChange R S T)

/-- Along a formally étale map `S → T` of finite presentation (i.e. an étale map),
`jzH1BaseChange : H⁻¹(L_{S/R}) ⊗_S T ⟶ H⁻¹(L_{T/R})` is bijective. -/
theorem bijective_jzH1BaseChange_of_formallyEtale [Algebra.FormallyEtale S T]
    [Algebra.FinitePresentation S T] : Function.Bijective (jzH1BaseChange R S T).hom :=
  have : Algebra.Etale S T := ⟨inferInstance, inferInstance⟩
  bijective_jzH1BaseChange_of_etale R S T

/-- The isomorphism `H⁻¹(L_{S/R}) ⊗_S T ≅ H⁻¹(L_{T/R})` for `S → T` formally étale of finite
presentation. -/
def hNegOneBaseChangeIso [Algebra.FormallyEtale S T] [Algebra.FinitePresentation S T] :
    ModuleCat.of T (T ⊗[S] Algebra.H1Cotangent R S) ≅
      Full.cohomology (Full.cotangentComplex R T) (-1) :=
  haveI : IsIso (jzH1BaseChange R S T) :=
    (ConcreteCategory.isIso_iff_bijective _).mpr
      (bijective_jzH1BaseChange_of_formallyEtale R S T)
  asIso (jzH1BaseChange R S T)

end Main

end Transitivity

end GromovWitten.AlgebraicGeometry.CotangentComplex
