/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.LciFormula
import GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.ResolvedConeDimension
import GromovWitten.Algebra.DimensionFormula
import Mathlib.RingTheory.Kaehler.Polynomial
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.KrullDimension.Regular
import Mathlib.RingTheory.KrullDimension.Zero
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Ideal.MinimalPrime.Localization

/-!
# The unconditional lci formula for regular sequences in a polynomial ring

`LciFormula.lean` proves `OverField.lci_formula`, giving `[X]^vir = [X]` for `X = Spec (R ⧸ I)`,
`R` finite type over an infinite field `k`, up to two remaining explicit hypotheses:
`[Module.Free (R ⧸ I) I.Cotangent]` and a purity hypothesis `hpureX` for the chosen dimension
function of `X`.  This file discharges both when `R = MvPolynomial σ k` and `I` is generated by a
finite family `x` which is a genuine **regular sequence** in the sense of
`AffineNormalCone.RegularGenerators` (Mathlib's `RingTheory.Sequence.IsWeaklyRegular`).

## Main declarations

* `AffineNormalCone.QuasiregularGenerators.cotangentBasis`: a quasi-regular sequence gives a
  basis of `I.Cotangent` over `R ⧸ I`, indexed by its generators (**Goal 1**).
* `VirtualClass.virtualDimension_lciHom_eq`: for `R = MvPolynomial σ k`, the virtual dimension of
  the identity obstruction theory is `card σ - x.length` (**Goal 2**).
* `height_eq_length_of_isWeaklyRegular`: a general commutative-algebra fact, the height of a
  minimal prime over an ideal generated by a (Mathlib) regular sequence equals the length of the
  sequence.
* `dimensionFunction_eq_of_isMax`: purity of `Spec (R ⧸ I)` for `R = MvPolynomial σ k` and `I`
  generated by a regular sequence `x`: every generic point of an irreducible component has
  dimension `card σ - x.length` (**Goal 3**).
* `OverField.lci_formula_polynomial`: the fully unconditional lci formula for a regular sequence
  in a polynomial ring over an infinite field (**Goal 4**).
-/

universe u

open CategoryTheory AlgebraicGeometry
open scoped TensorProduct
open RingTheory.Sequence

noncomputable section

/-! ## Goal 1: freeness of the conormal module -/

namespace GromovWitten.AlgebraicGeometry.AffineNormalCone

namespace QuasiregularGenerators

variable {R : Type u} [CommRing R] {I : Ideal R} (x : QuasiregularGenerators R I)

/-- The `R`-module structure on `I.Cotangent` factors through `R ⧸ I`: scalar multiplication by
`c : R` on `I.toCotangent (c • y)` for `y ∈ I.genMem` agrees with `R ⧸ I`-scalar multiplication by
`c`'s class. -/
theorem toCotangent_smul_genMem (i : Fin x.length) (c : R) :
    I.toCotangent (c • x.genMem i) = (Ideal.Quotient.mk I c) • x.conormalGen i := by
  rw [map_smul]
  exact (Module.IsTorsionBySet.mk_smul (Ideal.isTorsionBySet_cotangent (I := I)) c
    (x.conormalGen i)).symm

/-- The classes of the generators span `I.Cotangent` over `R ⧸ I`. -/
theorem span_range_conormalGen :
    (⊤ : Submodule (R ⧸ I) I.Cotangent) = Submodule.span (R ⧸ I) (Set.range x.conormalGen) := by
  refine le_antisymm ?_ le_top
  rintro m -
  obtain ⟨y, rfl⟩ := I.toCotangent_surjective m
  obtain ⟨c, hc⟩ := Ideal.mem_span_range_iff_exists_fun.1 (by rw [x.span_eq]; exact y.2)
  have hy : (y : R) = ∑ i, c i * x.gen i := hc.symm
  have heq : y = ∑ i : Fin x.length, c i • x.genMem i := by
    apply Subtype.ext
    push_cast
    simp only [smul_eq_mul]
    rw [hy]
    rfl
  rw [heq, map_sum]
  refine Submodule.sum_mem _ fun i _ => ?_
  rw [toCotangent_smul_genMem]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- The classes of the generators are linearly independent over `R ⧸ I`: this is exactly the
degree-one case of quasi-regularity. -/
theorem linearIndependent_conormalGen : LinearIndependent (R ⧸ I) x.conormalGen := by
  classical
  rw [Fintype.linearIndependent_iff]
  intro c hc j
  choose r hr using fun i => Ideal.Quotient.mk_surjective (I := I) (c i)
  have hc' : I.toCotangent (∑ i, r i • x.genMem i) = 0 := by
    rw [map_sum, ← hc]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [toCotangent_smul_genMem, hr]
  rw [I.toCotangent_eq_zero] at hc'
  have hcoe : ((∑ i, r i • x.genMem i : I) : R) = ∑ i, r i * x.gen i := by
    push_cast
    simp only [smul_eq_mul]
    rfl
  rw [hcoe] at hc'
  set F : MvPolynomial (Fin x.length) R := ∑ i, MvPolynomial.monomial (Finsupp.single i 1) (r i)
    with hF
  have hFhom : F.IsHomogeneous 1 := by
    rw [hF]
    exact MvPolynomial.IsHomogeneous.sum _ _ _ fun i _ =>
      MvPolynomial.isHomogeneous_monomial _ (by simp)
  have hFeval : MvPolynomial.eval x.gen F = ∑ i, r i * x.gen i := by
    rw [hF, map_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [MvPolynomial.eval_monomial, Finsupp.prod_single_index (by simp)]
    simp
  have hval : MvPolynomial.eval x.gen F ∈ (Ideal.span (Set.range x.gen)) ^ (1 + 1) := by
    rw [hFeval, x.span_eq]
    exact_mod_cast hc'
  have hcoeff := x.isQuasiregular 1 F hFhom hval (Finsupp.single j 1)
  have hFj : F.coeff (Finsupp.single j 1) = r j := by
    rw [hF, MvPolynomial.coeff_sum]
    rw [Finset.sum_eq_single j]
    · simp
    · intro i _ hij
      rw [MvPolynomial.coeff_monomial, if_neg]
      exact fun h => hij (Finsupp.single_left_injective one_ne_zero h)
    · simp
  rw [hFj] at hcoeff
  rw [← hr j, Ideal.Quotient.eq_zero_iff_mem, ← x.span_eq]
  exact hcoeff

/-- **Goal 1.** A quasi-regular sequence generating `I` gives a basis of `I.Cotangent` over
`R ⧸ I`, indexed by the generators. -/
def cotangentBasis : Module.Basis (Fin x.length) (R ⧸ I) I.Cotangent :=
  Module.Basis.mk x.linearIndependent_conormalGen (x.span_range_conormalGen ▸ le_refl _)

@[simp]
theorem cotangentBasis_apply (i : Fin x.length) : x.cotangentBasis i = x.conormalGen i :=
  Module.Basis.mk_apply _ _ i

include x in
/-- A quasi-regular sequence generating `I` makes `I.Cotangent` a free `R ⧸ I`-module (to be used
via `haveI`/`letI` at the point of use, since it depends on the data `x`). -/
theorem free_cotangent : Module.Free (R ⧸ I) I.Cotangent :=
  Module.Free.of_basis (cotangentBasis x)

include x in
/-- A quasi-regular sequence generating `I` makes `I.Cotangent` a finite `R ⧸ I`-module. -/
theorem finite_cotangent : Module.Finite (R ⧸ I) I.Cotangent :=
  Module.Finite.of_basis (cotangentBasis x)

/-- The rank of the conormal module of a quasi-regular ideal is the length of the generating
sequence. -/
theorem finrank_cotangent [Nontrivial (R ⧸ I)] : Module.finrank (R ⧸ I) I.Cotangent = x.length :=
  (Module.finrank_eq_card_basis x.cotangentBasis).trans (by simp)

end QuasiregularGenerators

end GromovWitten.AlgebraicGeometry.AffineNormalCone

/-! ## Goal 2: virtual dimension for polynomial rings -/

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.VirtualClass

open scoped TensorProduct
open NormalSheafPicard.AffineIntrinsicNormalSheaf

variable {σ : Type u} [Fintype σ] (k : Type u) [Field k] (I : Ideal (MvPolynomial σ k))
  [Nontrivial (MvPolynomial σ k ⧸ I)]

/-- The relative Kähler differentials of a polynomial ring over a field `k` stay free of rank
`card σ` after base change along `MvPolynomial σ k → (MvPolynomial σ k) ⧸ I`. -/
theorem finrank_degreeOne_conormalComplex :
    Module.finrank (MvPolynomial σ k ⧸ I)
        ((MvPolynomial σ k ⧸ I) ⊗[MvPolynomial σ k] Ω[MvPolynomial σ k⁄k]) = Fintype.card σ := by
  rw [Module.finrank_baseChange,
    Module.finrank_eq_card_basis (KaehlerDifferential.mvPolynomialBasis k σ)]

/-- **Goal 2.** For `R = MvPolynomial σ k`, the virtual dimension of the identity obstruction
theory `lciHom k I` is `card σ - rk I.Cotangent`. -/
theorem virtualDimension_lciHom_eq
    [Module.Free (MvPolynomial σ k ⧸ I) I.Cotangent]
    [Module.Finite (MvPolynomial σ k ⧸ I) I.Cotangent] :
    virtualDimension (lciHom k I) =
      (Fintype.card σ : ℤ) - (Module.finrank (MvPolynomial σ k ⧸ I) I.Cotangent : ℤ) := by
  change (Module.finrank (MvPolynomial σ k ⧸ I)
      ((MvPolynomial σ k ⧸ I) ⊗[MvPolynomial σ k] Ω[MvPolynomial σ k⁄k]) : ℤ) -
      (Module.finrank (MvPolynomial σ k ⧸ I) I.Cotangent : ℤ) = _
  rw [finrank_degreeOne_conormalComplex]

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.VirtualClass

/-! ## A general commutative-algebra fact: height of a minimal prime over a regular sequence -/

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass

open RingTheory.Sequence

/-- **Height of a minimal prime over an ideal generated by a regular sequence.** If `p` is a
minimal prime over `Ideal.ofList rs` for a (Mathlib) weakly regular sequence `rs`, then
`p.height = rs.length`.  The upper bound is Krull's height theorem; the lower bound is proved by
localising at `p` and applying `ringKrullDim_add_length_eq_ringKrullDim_of_isRegular` (the local
form of the dimension formula for regular sequences), using that `p` becomes the unique minimal
prime of the extended ideal, hence the localised quotient has Krull dimension zero. -/
theorem height_eq_length_of_isWeaklyRegular {R : Type u} [CommRing R] [IsNoetherianRing R]
    (rs : List R) (hrs : IsWeaklyRegular R rs) (p : Ideal R) [hp : p.IsPrime]
    (hmin : p ∈ (Ideal.ofList rs).minimalPrimes) :
    p.height = (rs.length : ℕ∞) := by
  classical
  let S := Localization.AtPrime p
  have hSinst : IsLocalization.AtPrime S p :=
    inferInstanceAs (IsLocalization.AtPrime (Localization.AtPrime p) p)
  have hflat : Module.Flat R S := IsLocalization.flat S p.primeCompl
  have h1 : IsWeaklyRegular S rs := by
    have h0 : IsWeaklyRegular (S ⊗[R] R) rs := hrs.isWeaklyRegular_lTensor (M₂ := S)
    exact (LinearEquiv.isWeaklyRegular_congr (TensorProduct.rid R S) rs).mp h0
  have h2 : IsWeaklyRegular S (rs.map (algebraMap R S)) :=
    (isWeaklyRegular_map_algebraMap_iff S S rs).mpr h1
  have hJrad : ((Ideal.ofList rs).map (algebraMap R S)).radical =
      IsLocalRing.maximalIdeal S := by
    have := IsLocalization.AtPrime.radical_map_of_mem_minimalPrimes (A := S) p
      (Ideal.ofList rs) hmin
    rwa [IsLocalization.AtPrime.map_eq_maximalIdeal (R := R) (p := p) (Rₚ := S)] at this
  have hJeq : Ideal.ofList (rs.map (algebraMap R S)) = (Ideal.ofList rs).map (algebraMap R S) :=
    (Ideal.map_ofList _ _).symm
  have hJmin : ∀ J ∈ (Ideal.ofList (rs.map (algebraMap R S))).minimalPrimes, J.IsMaximal := by
    rw [hJeq, ← Ideal.radical_minimalPrimes, hJrad, Ideal.minimalPrimes_eq_subsingleton_self]
    rintro J rfl
    exact IsLocalRing.maximalIdeal.isMaximal S
  have h3 : (⊤ : Ideal S) ≠ Ideal.ofList (rs.map (algebraMap R S)) := by
    rw [hJeq]
    intro h
    have hm : IsLocalRing.maximalIdeal S = ⊤ := by rw [← hJrad, ← h]; simp
    exact (IsLocalRing.maximalIdeal.isMaximal S).ne_top hm
  have hsmul : Ideal.ofList (rs.map (algebraMap R S)) • (⊤ : Ideal S) =
      Ideal.ofList (rs.map (algebraMap R S)) := by simp
  have h3' : (⊤ : Ideal S) ≠ Ideal.ofList (rs.map (algebraMap R S)) • (⊤ : Ideal S) := by
    rwa [hsmul]
  have hreg : IsRegular S (rs.map (algebraMap R S)) := ⟨h2, h3'⟩
  have hdim := ringKrullDim_add_length_eq_ringKrullDim_of_isRegular
    (R := S) (rs.map (algebraMap R S)) hreg
  have hK0 : Ring.KrullDimLE 0 (S ⧸ Ideal.ofList (rs.map (algebraMap R S))) :=
    Ideal.krullDimLE_zero_quotient_iff_forall_minimalPrimes_isMaximal.mpr hJmin
  have hnontriv : Nontrivial (S ⧸ Ideal.ofList (rs.map (algebraMap R S))) :=
    Submodule.Quotient.nontrivial_iff.mpr h3.symm
  have hzero : ringKrullDim (S ⧸ Ideal.ofList (rs.map (algebraMap R S))) = 0 :=
    ringKrullDimZero_iff_ringKrullDim_eq_zero.mp hK0
  rw [hzero, zero_add] at hdim
  have hheight : ringKrullDim S = (p.height : WithBot ℕ∞) :=
    IsLocalization.AtPrime.ringKrullDim_eq_height p S
  rw [hheight] at hdim
  have hlen : (rs.map (algebraMap R S)).length = rs.length := by simp
  rw [hlen] at hdim
  exact_mod_cast hdim.symm

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass

/-! ## Goal 3: purity of `Spec (R ⧸ I)` for a regular sequence in a polynomial ring -/

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass

open IntersectionTheory hiding Scheme AlgebraicCycle
open AffineNormalCone

variable {σ : Type u} [Fintype σ] (k : Type u) [Field k] (I : Ideal (MvPolynomial σ k))
  (x : RegularGenerators (MvPolynomial σ k) I)

omit [Fintype σ] in
include x in
/-- The ideal `I` is generated by the underlying list of the regular sequence `x`. -/
theorem ofList_gen_eq : Ideal.ofList (List.ofFn x.gen) = I := by
  have hset : {r | r ∈ List.ofFn x.gen} = Set.range x.gen :=
    Set.ext fun r => List.mem_ofFn' x.gen r
  change Ideal.span {r | r ∈ List.ofFn x.gen} = I
  rw [hset, x.span_eq]

include x in
/-- **Goal 3 (purity).**  For `R = MvPolynomial σ k` and `I` generated by a regular sequence `x`,
every generic point of an irreducible component of `Spec (R ⧸ I)` has dimension
`card σ - x.length`, for any certified dimension function of `Spec (R ⧸ I)`. -/
theorem dimensionFunction_eq_of_isMax
    (dimX : DimensionFunction (Spec (CommRingCat.of (MvPolynomial σ k ⧸ I))))
    (p : ↥(Spec (CommRingCat.of (MvPolynomial σ k ⧸ I)))) (hp : IsMax p) :
    dimX p = (Fintype.card σ : ℤ) - (x.length : ℤ) := by
  have hmin : (p : PrimeSpectrum (MvPolynomial σ k ⧸ I)).asIdeal ∈
      minimalPrimes (MvPolynomial σ k ⧸ I) :=
    ResolvedCone.mem_minimalPrimes_of_isMax p
      ((VectorBundle.specOrderIso (MvPolynomial σ k ⧸ I)).isMax_apply.mpr hp)
  set q := (p : PrimeSpectrum (MvPolynomial σ k ⧸ I)).asIdeal with hqdef
  set P := Ideal.comap (Ideal.Quotient.mk I) q with hPdef
  have hPmin : P ∈ I.minimalPrimes := by
    rw [Ideal.minimalPrimes_eq_comap]; exact ⟨q, hmin, rfl⟩
  have hPprime : P.IsPrime := hPmin.isPrime
  have hIP : I ≤ P := hPmin.le
  have hPmin' : P ∈ (Ideal.ofList (List.ofFn x.gen)).minimalPrimes := by
    rw [ofList_gen_eq (k := k) (I := I) x]; exact hPmin
  have hheight : P.height = (x.length : ℕ∞) := by
    have := height_eq_length_of_isWeaklyRegular (List.ofFn x.gen) x.isWeaklyRegular P hPmin'
    rwa [List.length_ofFn] at this
  have hcard : ringKrullDim (MvPolynomial σ k) = (Fintype.card σ : WithBot ℕ∞) := by
    rw [MvPolynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field]
    simp
  have hdimAdd := GromovWitten.Algebra.ringKrullDim_quotient_add_height k (MvPolynomial σ k) P
  rw [hcard, hheight] at hdimAdd
  have hquot : (MvPolynomial σ k ⧸ I) ⧸ q ≃+* MvPolynomial σ k ⧸ P := by
    have hle : I ≤ P := hIP
    have hmap : P.map (Ideal.Quotient.mk I) = q := by
      rw [hPdef, Ideal.map_comap_of_surjective _ Ideal.Quotient.mk_surjective]
    exact hmap ▸ DoubleQuot.quotQuotEquivQuotOfLE hle
  have hringq : ringKrullDim ((MvPolynomial σ k ⧸ I) ⧸ q) = ringKrullDim (MvPolynomial σ k ⧸ P) :=
    ringKrullDim_eq_of_ringEquiv hquot
  have hco := GromovWitten.Algebra.PrimeSpectrum.coheight_eq_ringKrullDim_quotient
    (p : PrimeSpectrum (MvPolynomial σ k ⧸ I))
  have hdimf := VectorBundle.coheight_eq_dimension (MvPolynomial σ k ⧸ I) dimX
    (p : PrimeSpectrum (MvPolynomial σ k ⧸ I))
  rw [← hqdef, hringq, hdimf] at hco
  -- `hco : ((Int.toNat (dimX p) : ℕ∞) : WithBot ℕ∞) = ringKrullDim (MvPolynomial σ k ⧸ P)`
  rw [← hco] at hdimAdd
  -- `hdimAdd : ((Int.toNat (dimX p) : ℕ∞) : WithBot ℕ∞) + (x.length : WithBot ℕ∞)
  --              = (Fintype.card σ : WithBot ℕ∞)`
  have hnat : Int.toNat (dimX p) + x.length = Fintype.card σ := by exact_mod_cast hdimAdd
  have hzint : (dimX p) + (x.length : ℤ) = (Fintype.card σ : ℤ) := by
    rw [← Int.toNat_of_nonneg (dimX.nonnegative p)]
    exact_mod_cast hnat
  omega

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass

/-! ## Goal 4: the fully unconditional lci formula -/

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.OverField

open IntersectionTheory hiding Scheme AlgebraicCycle
open NormalSheafPicard.AffineIntrinsicNormalSheaf
open AffineNormalCone

variable {σ : Type u} [Finite σ] (k : Type u) [Field k] [Infinite k]
  (I : Ideal (MvPolynomial σ k)) [Nontrivial (MvPolynomial σ k ⧸ I)]

/-- **Goal 4 (the unconditional lci formula for a regular sequence in a polynomial ring).**  Over
an infinite field `k`, `R = MvPolynomial σ k`, and `I` generated by a genuine regular sequence
`x` (Mathlib's `RingTheory.Sequence.IsWeaklyRegular`), the virtual fundamental class of the
identity ("lci") obstruction theory on `X = Spec (R ⧸ I)` is the class of the fundamental cycle of
`X`, with **no hypothesis** beyond `x` and `[Nontrivial (R ⧸ I)]`: the freeness of `I.Cotangent`
(Goal 1) and the purity of the dimension function of `X` (Goal 3) are both derived from `x`. -/
theorem lci_formula_polynomial (x : RegularGenerators (MvPolynomial σ k) I) :
    letI := x.toQuasiregular.free_cotangent
    letI := x.toQuasiregular.finite_cotangent
    ∀ (dimX : DimensionFunction (Spec (CommRingCat.of (MvPolynomial σ k ⧸ I))))
      (dimE : DimensionFunction (ResolvedCone.bundleSpace (VirtualClass.lciHom k I)))
      (RX : RationalEquivalenceSystem (Spec (CommRingCat.of (MvPolynomial σ k ⧸ I))) dimX
        (VirtualClass.virtualDimension (VirtualClass.lciHom k I)))
      (RE : RationalEquivalenceSystem (ResolvedCone.bundleSpace (VirtualClass.lciHom k I)) dimE
        (VirtualClass.coneDegree (VirtualClass.lciHom k I))),
      virtualClass (VirtualClass.lciHom k I) dimX dimE RX RE =
        RX.quotientMap (cyclesOfDimension.fundamental
          (show ∀ p, IsMax p → dimX p = VirtualClass.virtualDimension (VirtualClass.lciHom k I)
            from
              let _ := Fintype.ofFinite σ
              fun p hp => by
                rw [VirtualClass.virtualDimension_lciHom_eq,
                  x.toQuasiregular.finrank_cotangent]
                exact dimensionFunction_eq_of_isMax k I x dimX p hp)) := by
  let _ := x.toQuasiregular.free_cotangent
  let _ := x.toQuasiregular.finite_cotangent
  let _ := Fintype.ofFinite σ
  intro dimX dimE RX RE
  refine lci_formula k I x.toQuasiregular dimX dimE RX RE fun p hp => ?_
  rw [VirtualClass.virtualDimension_lciHom_eq, x.toQuasiregular.finrank_cotangent]
  exact dimensionFunction_eq_of_isMax k I x dimX p hp

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.OverField
