/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/

import GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneCone

/-!
# The resolved-cone ideal of a coordinate-hyperplane base change (issue #75)

`RelativeHyperplaneCone.lean` identifies the associated graded ring of the coordinate-hyperplane
base change `Y' = 𝔸^{τ'} ↪ Y = 𝔸^{Option τ'}`, `y₀ = 0`, of `X = Spec (R ⧸ I) → Y`
(`R = k[x_σ, y_{Option τ'}]`, `R' = k[x_σ, y_{τ'}]`, `J = ρ(I)` for `ρ : R → R'` the specialisation
`y₀ ↦ 0`): under `RegularOnPowers I y₀` it produces the identification
`symQuotEquiv : Sym_{Base I}(M) ⧸ (y₀) ≃+* Sym_{Base J}(Base J ⊗ M)` of the coordinate ring of a
bundle over `X` with that of the base-changed bundle over `X' = X ×_Y Y'`, the identification
`relProductQuotEquiv : relProductRing φ ⧸ (y₀) ≃+* relProductRing (reindexHom I φ)` of the
coordinate ring of `C ×_X E₀`, and the transversality criterion `ker_quotientSpanHom_eq_map` under
which the resolved-cone ideal base-changes.  This file completes the identity: it proves the
commuting square relating those two identifications to the coordinate-ring map of the resolved
cone, and deduces the resolved-cone ideal identity of issue #75.

## Main results

* `symRingHom_ext`: two ring homomorphisms out of a symmetric algebra agree as soon as they agree on
  the image of the base ring and on the generators.  This is the `RingHom` analogue of
  `SymmetricAlgebra.algHom_ext`; it needs no algebra structure on the target and therefore applies
  to the hyperplane-section comparison maps, whose targets are algebras over `Base I ⧸ (y₀)`.
* `symQuotEquiv_mk`: the identification `symQuotEquiv`, precomposed with the quotient map, *is* the
  canonical scalar extension `GradedCone.SymmetricFunctoriality.scalarExtensionMap`.  Hence
  `surjective_scalarExtensionMap_base` and `scalarExtensionMap_symHyperplaneCoord` (the equation of
  the hyperplane becomes zero on every bundle over `X'`).
* `relProductMap_scalarExtensionMap`: **the commuting square**
  `relProductMap (reindexHom I φ) ∘ scalarExtensionMap =
  relProductQuotEquiv ∘ (relProductMap φ mod y₀)`, proved by induction over the symmetric algebra
  from the generator computations `relProductMap_reindexHom_one_tmul` and
  `relProductQuotEquiv_mk_relProductMap_ι`.
* `ResolvedConeTransversal I φ`: transversality of the resolved cone of `φ` to the hyperplane, i.e.
  the hypothesis of `ker_quotientSpanHom_eq_map` for the coordinate-ring map of the resolved cone.
  It holds when that map is surjective (`resolvedConeTransversal_of_surjective`), when the equation
  of the hyperplane is a unit on `X` (`resolvedConeTransversal_of_isUnit`) and — the substantial
  case — when `y₀` is a non-zero-divisor on `Base I` and the cokernel of the coordinate-ring map is
  a flat `Base I`-module (`resolvedConeTransversal_of_flat`).
* `ideal'_reindexHom` and `ideal_absHom_reindexHom`: **the resolved-cone ideal identity of issue
  #75**, `ResolvedCone.ideal (absHom (reindexHom I φ)) = (ResolvedCone.ideal (absHom φ)).map
  (scalarExtensionMap (Base I) (Base J) E⁰)`, under `RegularOnPowers I y₀` and
  `ResolvedConeTransversal I φ`; `ideal'_reindexHom_of_flat` is the flat case.
* `comap_ideal'_reindexHom`: equivalently, the resolved cone of the base-changed datum is the
  scheme-theoretic intersection of the resolved cone of `φ` with the divisor `y₀ = 0` of the bundle
  `E₁`; `resolvedConeSupEquiv` and `resolvedConeQuotEquiv` are the ring-theoretic forms of this (the
  coordinate ring of the resolved cone of `reindexHom I φ` is that of the intersection, equivalently
  that of the resolved cone of `φ` modulo `y₀`) and `quotientCycle_comap_ideal'_reindexHom` the
  resulting equality of cycles on `E₁`.
* `resolvedConeTransversal_iff_ideal'_reindexHom`: conversely the ideal identity *forces*
  transversality as soon as `y₀` is a non-zero-divisor on `gr_I(R) ⊗ Sym(E₁)`, which by
  `isLeftRegular_relProductMap_symHyperplaneCoord` is automatic under `RegularOnPowers I y₀` when
  the bundle `E₀` is free (`resolvedConeTransversal_iff_ideal'_reindexHom_of_free`).  So the
  hypothesis of `ideal'_reindexHom` is not merely sufficient but necessary.

The transversality hypothesis cannot be dropped, and it is a hypothesis on the resolved cone rather
than on `X`: the module docstring of `RelativeHyperplaneCone.lean` records a counterexample in which
`I` is generated by polynomials not involving `y₀` — so that every regularity hypothesis on `X`
holds — and the conclusion fails.  By `forall_mem_range_of_ker_quotientSpanHom_le` the hypothesis is
moreover necessary whenever `y₀` is a non-zero-divisor on `gr_I(R) ⊗ Sym(E₁)`.

What remains of issue #75 after this file is the comparison of `RelativeAbsolute.relConeCycle
(reindexHom I φ)` — a cycle on the *smaller* bundle `E₁ ×_X X'` — with the Gysin image of
`RelativeAbsolute.relConeCycle φ`.  `quotientCycle_comap_ideal'_reindexHom` is the part of that
comparison which takes place on `E₁` itself; the missing step is to identify the pushforward of
`relConeCycle (reindexHom I φ)` along the closed immersion `Spec Sym_{Base J}(Base J ⊗ E⁰) ↪ Spec
Sym_{Base I}(E⁰)` with the left-hand side.  That needs
`AlgebraicCycle.map_comp_of_isClosedImmersion` together with the invariance of fundamental cycles
under the isomorphism `Spec (Sym_{Base J}(Base J ⊗ E⁰) ⧸ ideal' (reindexHom I φ)) ≅
Spec (Sym_{Base I}(E⁰) ⧸ (ideal' φ ⊔ (y₀)))`, and the matching of the associated dimension
functions.
-/

universe u

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneCone

/-! ## Ring homomorphisms out of a symmetric algebra -/

section SymRingHom

variable {R : Type u} [CommRing R] {M : Type u} [AddCommGroup M] [Module R M]
variable {S : Type u} [CommRing S]

/-- **Two ring homomorphisms out of a symmetric algebra agree** as soon as they agree on the
structural image of the base ring and on the generators.  This is the `RingHom` analogue of
`SymmetricAlgebra.algHom_ext`; unlike the latter it does not require the target to be an algebra
over the base ring, which is what makes it applicable to the comparison maps of a hyperplane
section, whose targets are algebras over a *quotient* of the base ring. -/
theorem symRingHom_ext {f g : SymmetricAlgebra R M →+* S}
    (halg : ∀ r : R, f (algebraMap R (SymmetricAlgebra R M) r) =
      g (algebraMap R (SymmetricAlgebra R M) r))
    (hι : ∀ x : M, f (SymmetricAlgebra.ι R M x) = g (SymmetricAlgebra.ι R M x)) : f = g := by
  refine RingHom.ext fun a => ?_
  induction a using SymmetricAlgebra.induction with
  | algebraMap r => exact halg r
  | ι x => exact hι x
  | mul a b ha hb => rw [map_mul, map_mul, ha, hb]
  | add a b ha hb => rw [map_add, map_add, ha, hb]

end SymRingHom

/-! ## The hyperplane section of the coordinate ring of a bundle, explicitly -/

section SymQuot

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open scoped TensorProduct

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable (M : Type u) [AddCommGroup M] [Module (Base I) M]

/-- **`symQuotEquiv` is a map of algebras over the coordinate ring of `X`**: it sends the class of
`algebraMap a` to `algebraMap a`, the structure map of the base-changed bundle being taken along
`Base I → Base J`.  This is the `algebraMap` companion of `symQuotEquiv_mk_ι`. -/
theorem symQuotEquiv_mk_algebraMap (a : Base I) :
    symQuotEquiv I M (Ideal.Quotient.mk (symHyperplaneSpan I M)
        (algebraMap (Base I) (SymmetricAlgebra (Base I) M) a)) =
      algebraMap (Base I) (SymmetricAlgebra (Base (reindexIdeal I))
        (Base (reindexIdeal I) ⊗[Base I] M)) a := by
  have hcongr : (Algebra.TensorProduct.congr (baseQuotEquiv I)
        (AlgEquiv.refl (R := Base I) (A₁ := SymmetricAlgebra (Base I) M)))
        ((1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I]
          algebraMap (Base I) (SymmetricAlgebra (Base I) M) a) =
      (1 : Base (reindexIdeal I)) ⊗ₜ[Base I]
        algebraMap (Base I) (SymmetricAlgebra (Base I) M) a := by
    rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul, map_one]
    rfl
  rw [symQuotEquiv, RingEquiv.trans_apply, RingEquiv.trans_apply, RingEquiv.trans_apply,
    Ideal.quotEquivOfEq_mk]
  simp only [AlgEquiv.coe_ringEquiv]
  rw [Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk, hcongr,
    scalarExtensionEquiv_one_tmul, AlgHom.commutes]

/-- **The hyperplane section of the coordinate ring of a bundle is its scalar extension**: the
identification `symQuotEquiv` of `Sym_{Base I}(M) ⧸ (y₀)` with `Sym_{Base J}(Base J ⊗ M)` composed
with the quotient map is the canonical scalar-extension map
`GradedCone.SymmetricFunctoriality.scalarExtensionMap`. -/
theorem symQuotEquiv_mk (s : SymmetricAlgebra (Base I) M) :
    symQuotEquiv I M (Ideal.Quotient.mk (symHyperplaneSpan I M) s) =
      scalarExtensionMap (Base I) (Base (reindexIdeal I)) M s := by
  induction s using SymmetricAlgebra.induction with
  | algebraMap a => rw [symQuotEquiv_mk_algebraMap, AlgHom.commutes]
  | ι x => rw [symQuotEquiv_mk_ι, scalarExtensionMap_ι]
  | mul a b ha hb => simp only [map_mul, ha, hb]
  | add a b ha hb => simp only [map_add, ha, hb]

/-- **The scalar extension of the coordinate ring of a bundle along the hyperplane is
surjective**: it is the quotient map followed by the isomorphism `symQuotEquiv`. -/
theorem surjective_scalarExtensionMap_base :
    Function.Surjective (scalarExtensionMap (Base I) (Base (reindexIdeal I)) M) := by
  intro z
  obtain ⟨s, hs⟩ := Ideal.Quotient.mk_surjective ((symQuotEquiv I M).symm z)
  refine ⟨s, ?_⟩
  rw [← symQuotEquiv_mk, hs, RingEquiv.apply_symm_apply]

/-- **The kernel of the scalar extension is the ideal of the hyperplane**: the coordinate ring of a
bundle over `X'` is the coordinate ring of the bundle over `X` modulo the equation `y₀`. -/
theorem ker_scalarExtensionMap_base :
    RingHom.ker (scalarExtensionMap (Base I) (Base (reindexIdeal I)) M) =
      symHyperplaneSpan I M := by
  refine Ideal.ext fun s => ?_
  rw [RingHom.mem_ker, ← symQuotEquiv_mk, (symQuotEquiv I M).map_eq_zero_iff,
    Ideal.Quotient.eq_zero_iff_mem]

/-- **The saturation of an ideal along the hyperplane**: the pullback of the image of an ideal `K`
under the scalar extension is `K` together with the ideal of the hyperplane. -/
theorem comap_map_scalarExtensionMap (K : Ideal (SymmetricAlgebra (Base I) M)) :
    Ideal.comap (scalarExtensionMap (Base I) (Base (reindexIdeal I)) M)
        (Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) M) K) =
      K ⊔ symHyperplaneSpan I M := by
  rw [Ideal.comap_map_of_surjective _ (surjective_scalarExtensionMap_base I M),
    ← RingHom.ker_eq_comap_bot, ker_scalarExtensionMap_base]

/-- The class of the equation of the hyperplane vanishes in the coordinate ring of `X'`. -/
theorem algebraMap_base_hyperplaneCoord :
    algebraMap (Base I) (Base (reindexIdeal I))
        (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) = 0 := by
  rw [algebraMap_reindex_mk, reindexAlgHom_hyperplaneCoord]
  exact map_zero _

end SymQuot

/-! ## The hyperplane section of the coordinate ring of `C ×_X E₀` on the base ring -/

section RelProductQuot

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open ConeTranslation (Gr)
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u} [Fintype σ]
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable {E : LinearTwoTermComplex (Base I)}
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

/-- **The hyperplane section of `C ×_X E₀` is a map of algebras over the coordinate ring of `X`**:
the `algebraMap` companion of `relProductQuotEquiv_mk_tmul`. -/
theorem relProductQuotEquiv_mk_algebraMap
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) (a : Base I) :
    relProductQuotEquiv I φ h (Ideal.Quotient.mk (relProductHyperplaneSpan I φ)
        (algebraMap (Base I) (relProductRing φ) a)) =
      algebraMap (Base (reindexIdeal I)) (relProductRing (reindexHom I φ))
        (algebraMap (Base I) (Base (reindexIdeal I)) a) := by
  have h1 : algebraMap (Base I) (relProductRing φ) a =
      algebraMap (Base I) (Gr I) a ⊗ₜ[Base I]
        (1 : SymmetricAlgebra (Base I) E.degreeOne) := rfl
  rw [h1, relProductQuotEquiv_mk_tmul, map_one, grReindexHom_algebraMap]
  rfl

omit [Fintype σ] in
/-- **The scalar extension of the hyperplane equation vanishes**: the equation `y₀` of the
hyperplane is zero on `X'`, hence on every bundle over `X'`. -/
theorem scalarExtensionMap_symHyperplaneCoord :
    scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero
        (symHyperplaneCoord I E) = 0 := by
  rw [symHyperplaneCoord, AlgHom.commutes,
    IsScalarTower.algebraMap_apply (Base I) (Base (reindexIdeal I))
      (SymmetricAlgebra (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] E.degreeZero)),
    algebraMap_base_hyperplaneCoord, map_zero]

end RelProductQuot

/-! ## Transversality of the resolved cone to the hyperplane -/

section Transversal

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open ConeTranslation (Gr)
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable {E : LinearTwoTermComplex (Base I)}
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

/-- **Transversality of the resolved cone of `φ` to the hyperplane `y₀ = 0`**: the equation `y₀` of
the hyperplane is a non-zero-divisor on the cokernel of the coordinate-ring map
`Sym(E⁰) → gr_I(R) ⊗ Sym(E₁)` of the resolved cone, i.e. `y₀ · t` is a function on `C ×_X E₀`
pulled back from `E₁` only if `t` is.

This is a condition on the *resolved cone*, not on `X`: the module docstring of
`RelativeHyperplaneCone.lean` records an ideal `I` generated by polynomials not involving `y₀` —
so satisfying every regularity hypothesis on `X` — and a datum `φ` for which it fails, and for
which the resolved-cone ideal identity `ideal'_reindexHom` below is false.  By
`forall_mem_range_of_ker_quotientSpanHom_le` it is also necessary as soon as `y₀` is a
non-zero-divisor on `gr_I(R) ⊗ Sym(E₁)`. -/
def ResolvedConeTransversal : Prop :=
  ∀ t : relProductRing φ,
    (relProductMap φ).toRingHom (symHyperplaneCoord I E) * t ∈
        Set.range (relProductMap φ).toRingHom →
      t ∈ Set.range (relProductMap φ).toRingHom

/-- **A closed immersion of the resolved cone is transversal to every hyperplane**: if the
coordinate-ring map of the resolved cone is surjective — i.e. `C ×_X E₀ → E₁` is a closed
immersion, so that the resolved cone *is* `C ×_X E₀` — the transversality condition is
vacuous. -/
theorem resolvedConeTransversal_of_surjective
    (hsurj : Function.Surjective (relProductMap φ)) : ResolvedConeTransversal I φ :=
  fun t _ => hsurj t

/-- **A hyperplane missing `X` is transversal to the resolved cone**: if the equation of the
hyperplane is a unit on the bundle `E₁` (equivalently, on `X`), transversality holds. -/
theorem resolvedConeTransversal_of_isUnit (hy : IsUnit (symHyperplaneCoord I E)) :
    ResolvedConeTransversal I φ := by
  intro t ht
  obtain ⟨s, hs⟩ := ht
  obtain ⟨v, hv⟩ := hy
  refine ⟨(↑v⁻¹ : SymmetricAlgebra (Base I) E.degreeZero) * s, ?_⟩
  rw [map_mul, hs, ← hv, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]

/-- **Transversality is regularity of `y₀` on the cokernel**: the definition unwound into its
module-theoretic form.  The cokernel is taken in `Base I`-modules, and the scalar action of the
class of `y₀` is multiplication by the image of `y₀` under the coordinate-ring map of the
resolved cone. -/
theorem resolvedConeTransversal_iff_isSMulRegular :
    ResolvedConeTransversal I φ ↔
      IsSMulRegular (relProductRing φ ⧸ LinearMap.range (relProductMap φ).toLinearMap)
        (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) := by
  have hsmul_eq : ∀ t : relProductRing φ,
      (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) • t =
        (relProductMap φ).toRingHom (symHyperplaneCoord I E) * t := by
    intro t
    rw [relProductMap_symHyperplaneCoord, Algebra.smul_def]
  constructor
  · intro htrans x y hxy
    obtain ⟨a, rfl⟩ := Submodule.mkQ_surjective _ x
    obtain ⟨b, rfl⟩ := Submodule.mkQ_surjective _ y
    have h1 : (LinearMap.range (relProductMap φ).toLinearMap).mkQ
        ((Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) • (a - b)) = 0 := by
      rw [map_smul, map_sub, smul_sub, sub_eq_zero]
      exact hxy
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero] at h1
    have h3 : a - b ∈ Set.range (relProductMap φ).toRingHom :=
      htrans (a - b) (by rw [← hsmul_eq]; exact LinearMap.mem_range.1 h1)
    have h4 : (LinearMap.range (relProductMap φ).toLinearMap).mkQ (a - b) = 0 := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact LinearMap.mem_range.2 h3
    rw [map_sub] at h4
    exact sub_eq_zero.1 h4
  · intro hsmul t ht
    obtain ⟨s, hs⟩ := ht
    have h1 : (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) •
        (LinearMap.range (relProductMap φ).toLinearMap).mkQ t = 0 := by
      rw [← map_smul, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact ⟨s, hs.trans (hsmul_eq t).symm⟩
    have h2 : (LinearMap.range (relProductMap φ).toLinearMap).mkQ t = 0 :=
      hsmul (by simpa only [smul_zero] using h1)
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero] at h2
    exact h2

/-- **Flatness of the resolved cone's cokernel implies transversality**: if the cokernel of the
coordinate-ring map of the resolved cone is a flat module over the coordinate ring `Base I` of `X`
and `y₀` is a non-zero-divisor on `Base I` (i.e. the hyperplane contains no component of `X`), then
the resolved cone is transversal to the hyperplane.  This is the honest "flat case" of issue #75:
both hypotheses are conditions one checks on `X` and on the resolved cone separately. -/
theorem resolvedConeTransversal_of_flat
    (hy : IsSMulRegular (Base I)
      (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))))
    [Module.Flat (Base I)
      (relProductRing φ ⧸ LinearMap.range (relProductMap φ).toLinearMap)] :
    ResolvedConeTransversal I φ :=
  (resolvedConeTransversal_iff_isSMulRegular I φ).2
    (Module.Flat.isSMulRegular_of_isRegular
      ((Commute.isRegular_iff (fun b => Commute.all _ b)).2 hy))

/-- **The equation of the hyperplane is a non-zero-divisor on the coordinate ring of `C ×_X E₀`**
when it is one on the normal cone and the bundle `E₀` is a free bundle: multiplication by `y₀` on
`gr_I(R) ⊗ Sym(E₁)` is the tensor product of multiplication by `y₀` on `gr_I(R)` with the identity,
and `Sym(E₁)` is a free — hence flat — `Base I`-module.  This is the hypothesis under which
`resolvedConeTransversal_iff_ideal'_reindexHom` shows the transversality condition to be
necessary. -/
theorem isLeftRegular_relProductMap_symHyperplaneCoord
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    [Module.Free (Base I) E.degreeOne] :
    IsLeftRegular ((relProductMap φ).toRingHom (symHyperplaneCoord I E)) := by
  have hmul : ∀ w : relProductRing φ,
      (relProductMap φ).toRingHom (symHyperplaneCoord I E) * w =
        LinearMap.rTensor (SymmetricAlgebra (Base I) E.degreeOne)
          (LinearMap.mulLeft (Base I) (grHyperplaneCoord I)) w := by
    intro w
    induction w using TensorProduct.induction_on with
    | zero => rw [mul_zero, map_zero]
    | tmul z s =>
        rw [relProductMap_symHyperplaneCoord, LinearMap.rTensor_tmul]
        change (grHyperplaneCoord I ⊗ₜ[Base I] (1 : SymmetricAlgebra (Base I) E.degreeOne)) *
          (z ⊗ₜ[Base I] s) = _
        rw [Algebra.TensorProduct.tmul_mul_tmul, one_mul]
        rfl
    | add a b ha hb => rw [mul_add, map_add, ha, hb]
  have hinj : Function.Injective (LinearMap.rTensor
      (SymmetricAlgebra (Base I) E.degreeOne)
      (LinearMap.mulLeft (Base I) (grHyperplaneCoord I))) :=
    Module.Flat.rTensor_preserves_injective_linearMap _ (isLeftRegular_grHyperplaneCoord I h)
  refine fun x y hxy => hinj ?_
  rw [← hmul, ← hmul]
  exact hxy

end Transversal

/-! ## The commuting square and the resolved-cone ideal identity -/

section Identity

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open ConeTranslation (Gr)
open AffineNormalCone
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u} [Fintype σ]
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable {E : LinearTwoTermComplex (Base I)}
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

set_option synthInstance.maxHeartbeats 400000 in
-- Recognising the quotient of the coordinate ring of `C ×_X E₀` as an additive monoid exceeds the
-- default instance-search budget, and
set_option maxHeartbeats 1000000 in
-- `relProductQuotEquiv` is a five-step composite of tensor-product equivalences, so computing it on
-- the image of a generator of the symmetric algebra exceeds the default heartbeat budget.
/-- **The hyperplane section of the coordinate-ring map of the resolved cone, on generators**: the
image of `ι x` under `relProductMap φ`, read in the coordinate ring of `C ×_X E₀` for the
base-changed datum, is the corresponding expression for the specialised conormal class. -/
theorem relProductQuotEquiv_mk_relProductMap_ι
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) (x : E.degreeZero) :
    relProductQuotEquiv I φ h (Ideal.Quotient.mk (relProductHyperplaneSpan I φ)
        (relProductMap φ (SymmetricAlgebra.ι (Base I) E.degreeZero x))) =
      conormalToAssociatedGraded (MvPolynomial (σ ⊕ τ') k) (reindexIdeal I)
            (idealCotangentReindex I (φ.degreeZero x)) ⊗ₜ[Base (reindexIdeal I)]
          (1 : SymmetricAlgebra (Base (reindexIdeal I))
            (Base (reindexIdeal I) ⊗[Base I] E.degreeOne)) +
        (1 : Gr (reindexIdeal I)) ⊗ₜ[Base (reindexIdeal I)]
          SymmetricAlgebra.ι (Base (reindexIdeal I))
            (Base (reindexIdeal I) ⊗[Base I] E.degreeOne)
            ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] E.differential x) := by
  rw [relProductMap_ι, map_add (Ideal.Quotient.mk (relProductHyperplaneSpan I φ)),
    map_add (relProductQuotEquiv I φ h), relProductQuotEquiv_mk_tmul,
    relProductQuotEquiv_mk_tmul,
    map_one (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeOne),
    map_one (grReindexHom I), scalarExtensionMap_ι,
    grReindexHom_conormalToAssociatedGraded]

/-- **The coordinate-ring map of the resolved cone of the base-changed datum, on generators**: it is
computed by the specialisation `y₀ ↦ 0` of the conormal class of `φ.degreeZero x` and by the base
change of the differential of `E`. -/
theorem relProductMap_reindexHom_one_tmul (x : E.degreeZero) :
    relProductMap (reindexHom I φ)
        (SymmetricAlgebra.ι (Base (reindexIdeal I))
          (Base (reindexIdeal I) ⊗[Base I] E.degreeZero)
          ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] x)) =
      conormalToAssociatedGraded (MvPolynomial (σ ⊕ τ') k) (reindexIdeal I)
            (idealCotangentReindex I (φ.degreeZero x)) ⊗ₜ[Base (reindexIdeal I)]
          (1 : SymmetricAlgebra (Base (reindexIdeal I))
            (Base (reindexIdeal I) ⊗[Base I] E.degreeOne)) +
        (1 : Gr (reindexIdeal I)) ⊗ₜ[Base (reindexIdeal I)]
          SymmetricAlgebra.ι (Base (reindexIdeal I))
            (Base (reindexIdeal I) ⊗[Base I] E.degreeOne)
            ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] E.differential x) := by
  rw [relProductMap_ι, reindexHom_degreeZero_one_tmul,
    LinearTwoTermComplex.baseChange_differential, LinearMap.baseChange_tmul]

set_option synthInstance.maxHeartbeats 400000 in
-- Recognising the quotient of the coordinate ring of `C ×_X E₀` as an additive monoid exceeds the
-- default instance-search budget, and
set_option maxHeartbeats 1000000 in
-- Comparing the two ring homomorphisms on the image of the base ring unfolds the algebra structure
-- of a quotient of a tensor product of the associated graded ring.
/-- **The commuting square of the hyperplane section of the resolved cone**: the coordinate-ring
map of the resolved cone of the base-changed datum `reindexHom I φ` is the reduction modulo `y₀` of
the coordinate-ring map of the resolved cone of `φ`, under the identifications `symQuotEquiv` of
the two bundles `E₁` and `relProductQuotEquiv` of the two products `C ×_X E₀`.  Both sides are ring
maps out of `Sym_{Base I}(E⁰)`; they are compared on the generators of the symmetric algebra and on
the image of the base ring. -/
theorem relProductMap_scalarExtensionMap
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (s : SymmetricAlgebra (Base I) E.degreeZero) :
    relProductMap (reindexHom I φ)
        (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero s) =
      relProductQuotEquiv I φ h
        (Ideal.Quotient.mk (relProductHyperplaneSpan I φ) (relProductMap φ s)) := by
  have key : (relProductMap (reindexHom I φ)).toRingHom.comp
        (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero).toRingHom =
      (relProductQuotEquiv I φ h).toRingHom.comp
        ((Ideal.Quotient.mk (relProductHyperplaneSpan I φ)).comp
          (relProductMap φ).toRingHom) := by
    refine symRingHom_ext (fun a => ?_) (fun x => ?_)
    · have hl : scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero
              (algebraMap (Base I) (SymmetricAlgebra (Base I) E.degreeZero) a) =
            algebraMap (Base (reindexIdeal I)) (SymmetricAlgebra (Base (reindexIdeal I))
                (Base (reindexIdeal I) ⊗[Base I] E.degreeZero))
              (algebraMap (Base I) (Base (reindexIdeal I)) a) := by
        rw [AlgHom.commutes]
        exact IsScalarTower.algebraMap_apply (Base I) (Base (reindexIdeal I)) _ a
      have hr : relProductMap φ
            (algebraMap (Base I) (SymmetricAlgebra (Base I) E.degreeZero) a) =
          algebraMap (Base I) (relProductRing φ) a := AlgHom.commutes _ a
      have hgoal : relProductMap (reindexHom I φ)
              (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero
                (algebraMap (Base I) (SymmetricAlgebra (Base I) E.degreeZero) a)) =
            relProductQuotEquiv I φ h (Ideal.Quotient.mk (relProductHyperplaneSpan I φ)
              (relProductMap φ
                (algebraMap (Base I) (SymmetricAlgebra (Base I) E.degreeZero) a))) := by
        rw [hl, hr, AlgHom.commutes, relProductQuotEquiv_mk_algebraMap]
      exact hgoal
    · have hgoal : relProductMap (reindexHom I φ)
              (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero
                (SymmetricAlgebra.ι (Base I) E.degreeZero x)) =
            relProductQuotEquiv I φ h (Ideal.Quotient.mk (relProductHyperplaneSpan I φ)
              (relProductMap φ (SymmetricAlgebra.ι (Base I) E.degreeZero x))) := by
        rw [scalarExtensionMap_ι, relProductMap_reindexHom_one_tmul,
          relProductQuotEquiv_mk_relProductMap_ι]
      exact hgoal
  exact DFunLike.congr_fun key s

/-- **The resolved-cone ideal identity along a coordinate hyperplane** (issue #75): if `y₀` is a
non-zero-divisor on every `R ⧸ Iⁿ` (`RegularOnPowers`, so that the normal cone of `X` base-changes)
*and* the resolved cone of `φ` is transversal to the hyperplane, then the ideal of the resolved
cone of the base-changed datum is the image of the ideal of the resolved cone of `φ` under the
scalar extension `Sym_{Base I}(E⁰) → Sym_{Base J}(Base J ⊗ E⁰)`.

Both hypotheses are needed: `RegularOnPowers` for the normal cone
(`RelativeHyperplaneReindex.surjective_grReindexHom` and `ker_grReindexHom`), and transversality
for the resolved cone (the module docstring of `RelativeHyperplaneCone.lean` has a counterexample
with `RegularOnPowers` satisfied and the conclusion false). -/
theorem ideal'_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    ideal' (reindexHom I φ) =
      Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero)
        (ideal' φ) := by
  refine le_antisymm ?_ ?_
  · intro z hz
    obtain ⟨s, rfl⟩ := surjective_scalarExtensionMap_base I E.degreeZero z
    rw [mem_ideal'_iff, relProductMap_scalarExtensionMap I φ h s] at hz
    have hz' : Ideal.Quotient.mk (relProductHyperplaneSpan I φ) (relProductMap φ s) = 0 :=
      (relProductQuotEquiv I φ h).map_eq_zero_iff.1 hz
    have hker : Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E}) s ∈
        RingHom.ker (quotientSpanHom (relProductMap φ).toRingHom (symHyperplaneCoord I E)) := by
      rw [mem_ker_quotientSpanHom_iff, span_relProductMap_symHyperplaneCoord]
      exact Ideal.Quotient.eq_zero_iff_mem.1 hz'
    rw [ker_quotientSpanHom_relProductMap φ htrans] at hker
    obtain ⟨u, hu, hmk⟩ :=
      (Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective).1 hker
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 (Ideal.Quotient.eq.1 hmk)
    have hsu : s = u - c * symHyperplaneCoord I E := by
      rw [hc]
      ring
    rw [hsu, map_sub (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero),
      map_mul (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero),
      scalarExtensionMap_symHyperplaneCoord, mul_zero, sub_zero]
    exact Ideal.mem_map_of_mem _ hu
  · rw [Ideal.map_le_iff_le_comap]
    intro s hs
    rw [Ideal.mem_comap, mem_ideal'_iff, relProductMap_scalarExtensionMap I φ h s,
      mem_ideal'_iff.1 hs, map_zero, map_zero]

/-- **The resolved-cone ideal identity in the flat case**: if the cokernel of the coordinate-ring
map of the resolved cone is flat over the coordinate ring of `X` and `y₀` is a non-zero-divisor on
every `R ⧸ Iⁿ`, the resolved-cone ideal base-changes along the hyperplane with no further
hypothesis. -/
theorem ideal'_reindexHom_of_flat
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    [Module.Flat (Base I)
      (relProductRing φ ⧸ LinearMap.range (relProductMap φ).toLinearMap)] :
    ideal' (reindexHom I φ) =
      Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero)
        (ideal' φ) :=
  ideal'_reindexHom I φ h (resolvedConeTransversal_of_flat I φ h.isSMulRegular)

/-- **The resolved cone of the base-changed datum is the hyperplane section of the resolved cone**:
pulled back to the coordinate ring `Sym_{Base I}(E⁰)` of the bundle `E₁` over `X`, the ideal of the
resolved cone of `reindexHom I φ` is the sum of the ideal of the resolved cone of `φ` and the ideal
of the hyperplane.  In other words the resolved cone of the base-changed datum is the
scheme-theoretic intersection of the resolved cone of `φ` with the divisor `y₀ = 0` of `E₁` — the
statement the hyperplane Gysin map needs. -/
theorem comap_ideal'_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    Ideal.comap (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero)
        (ideal' (reindexHom I φ)) =
      ideal' φ ⊔ symHyperplaneSpan I E.degreeZero := by
  rw [ideal'_reindexHom I φ h htrans, comap_map_scalarExtensionMap]

/-- **Transversality is necessary for the ideal identity**, as soon as the equation of the
hyperplane is a non-zero-divisor on the coordinate ring of `C ×_X E₀`: the converse of
`ideal'_reindexHom`.
Together with `forall_mem_range_of_ker_quotientSpanHom_le` this shows that the transversality
hypothesis of `ideal'_reindexHom` is not an artefact of the proof. -/
theorem resolvedConeTransversal_of_ideal'_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (hreg : IsLeftRegular ((relProductMap φ).toRingHom (symHyperplaneCoord I E)))
    (hid : ideal' (reindexHom I φ) =
      Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero) (ideal' φ)) :
    ResolvedConeTransversal I φ := by
  have hle : RingHom.ker (quotientSpanHom (relProductMap φ).toRingHom (symHyperplaneCoord I E)) ≤
      Ideal.map (Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E})) (ideal' φ) := by
    intro z hz
    obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective z
    rw [mem_ker_quotientSpanHom_iff, span_relProductMap_symHyperplaneCoord,
      ← Ideal.Quotient.eq_zero_iff_mem] at hz
    have hz' : Ideal.Quotient.mk (relProductHyperplaneSpan I φ) (relProductMap φ s) = 0 := hz
    have h1 : scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero s ∈
        ideal' (reindexHom I φ) := by
      rw [mem_ideal'_iff, relProductMap_scalarExtensionMap I φ h s, hz', map_zero]
    have h2 : s ∈ ideal' φ ⊔ symHyperplaneSpan I E.degreeZero := by
      rw [← comap_map_scalarExtensionMap I E.degreeZero (ideal' φ), ← hid]
      exact h1
    obtain ⟨a, ha, c, hc, hac⟩ := Submodule.mem_sup.1 h2
    have hc0 : Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E}) c = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.2 hc
    have hs : Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E}) s =
        Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E}) a := by
      rw [← hac, map_add (Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E})), hc0, add_zero]
    rw [hs]
    exact Ideal.mem_map_of_mem _ ha
  exact forall_mem_range_of_ker_quotientSpanHom_le _ _ hreg hle

/-- **The resolved-cone ideal identity holds exactly under transversality**, when the equation of
the hyperplane is a non-zero-divisor on the coordinate ring of `C ×_X E₀`. -/
theorem resolvedConeTransversal_iff_ideal'_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (hreg : IsLeftRegular ((relProductMap φ).toRingHom (symHyperplaneCoord I E))) :
    ResolvedConeTransversal I φ ↔
      ideal' (reindexHom I φ) =
        Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero) (ideal' φ) :=
  ⟨ideal'_reindexHom I φ h, resolvedConeTransversal_of_ideal'_reindexHom I φ h hreg⟩

/-- **The resolved-cone ideal identity holds exactly under transversality, for a free bundle `E₀`**:
the specialisation of `resolvedConeTransversal_iff_ideal'_reindexHom` whose hypotheses are all
conditions on `I` and on `E`. -/
theorem resolvedConeTransversal_iff_ideal'_reindexHom_of_free
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    [Module.Free (Base I) E.degreeOne] :
    ResolvedConeTransversal I φ ↔
      ideal' (reindexHom I φ) =
        Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero) (ideal' φ) :=
  resolvedConeTransversal_iff_ideal'_reindexHom I φ h
    (isLeftRegular_relProductMap_symHyperplaneCoord I φ h)

/-- **The coordinate-ring map of the resolved cone of the base-changed datum**, as a quotient of the
coordinate ring `Sym_{Base I}(E⁰)` of the bundle `E₁` over `X`: the scalar extension followed by the
quotient by the resolved-cone ideal. -/
noncomputable def resolvedConeBaseChangeHom :
    SymmetricAlgebra (Base I) E.degreeZero →+*
      (SymmetricAlgebra (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] E.degreeZero) ⧸
        ideal' (reindexHom I φ)) :=
  (Ideal.Quotient.mk (ideal' (reindexHom I φ))).comp
    (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero).toRingHom

theorem surjective_resolvedConeBaseChangeHom :
    Function.Surjective (resolvedConeBaseChangeHom I φ) := by
  intro z
  obtain ⟨w, rfl⟩ := Ideal.Quotient.mk_surjective z
  obtain ⟨s, rfl⟩ := surjective_scalarExtensionMap_base I E.degreeZero w
  exact ⟨s, rfl⟩

/-- The kernel of `resolvedConeBaseChangeHom` is the ideal of the intersection of the resolved cone
of `φ` with the hyperplane. -/
theorem ker_resolvedConeBaseChangeHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    RingHom.ker (resolvedConeBaseChangeHom I φ) =
      ideal' φ ⊔ symHyperplaneSpan I E.degreeZero := by
  have h1 : RingHom.ker (resolvedConeBaseChangeHom I φ) =
      Ideal.comap (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero).toRingHom
        (RingHom.ker (Ideal.Quotient.mk (ideal' (reindexHom I φ)))) :=
    (RingHom.comap_ker (Ideal.Quotient.mk (ideal' (reindexHom I φ)))
      (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero).toRingHom).symm
  rw [h1, Ideal.mk_ker]
  exact comap_ideal'_reindexHom I φ h htrans

/-- **The resolved cone of the base-changed datum, as a closed subscheme of the bundle `E₁` over
`X`**: the coordinate ring of the scheme-theoretic intersection of the resolved cone of `φ` with the
hyperplane is the coordinate ring of the resolved cone of `reindexHom I φ`.  This is the form of
`resolvedConeQuotEquiv` in which the closed immersion into `E₁` is the quotient map by a single
ideal, i.e. the form a cycle-level comparison needs. -/
noncomputable def resolvedConeSupEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    (SymmetricAlgebra (Base I) E.degreeZero ⧸
        (ideal' φ ⊔ symHyperplaneSpan I E.degreeZero)) ≃+*
      (SymmetricAlgebra (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] E.degreeZero) ⧸
        ideal' (reindexHom I φ)) :=
  (Ideal.quotEquivOfEq (ker_resolvedConeBaseChangeHom I φ h htrans).symm).trans
    (RingHom.quotientKerEquivOfSurjective (surjective_resolvedConeBaseChangeHom I φ))

@[simp]
theorem resolvedConeSupEquiv_mk
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) (s : SymmetricAlgebra (Base I) E.degreeZero) :
    resolvedConeSupEquiv I φ h htrans
        (Ideal.Quotient.mk (ideal' φ ⊔ symHyperplaneSpan I E.degreeZero) s) =
      Ideal.Quotient.mk (ideal' (reindexHom I φ))
        (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero s) := by
  rw [resolvedConeSupEquiv, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk,
    RingHom.quotientKerEquivOfSurjective_apply_mk]
  rfl

/-- **The coordinate ring of the resolved cone base-changes along the hyperplane**: the coordinate
ring of the resolved cone of the base-changed datum is the coordinate ring of the resolved cone of
`φ` modulo the equation `y₀` of the hyperplane.  (By `RelativeAbsolute.ideal_absHom` the ideals
`ideal' φ` and `ResolvedCone.ideal (absHom φ)` agree, so the left-hand side is the hyperplane
section of `ResolvedCone.ring (absHom φ)`.)  This is the ring-theoretic form of
`comap_ideal'_reindexHom`. -/
noncomputable def resolvedConeQuotEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    ((SymmetricAlgebra (Base I) E.degreeZero ⧸ ideal' φ) ⧸
        Ideal.map (Ideal.Quotient.mk (ideal' φ)) (symHyperplaneSpan I E.degreeZero)) ≃+*
      (SymmetricAlgebra (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] E.degreeZero) ⧸
        ideal' (reindexHom I φ)) :=
  (DoubleQuot.quotQuotEquivQuotSup (ideal' φ) (symHyperplaneSpan I E.degreeZero)).trans
    (resolvedConeSupEquiv I φ h htrans)

@[simp]
theorem resolvedConeQuotEquiv_mk_mk
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) (s : SymmetricAlgebra (Base I) E.degreeZero) :
    resolvedConeQuotEquiv I φ h htrans
        (Ideal.Quotient.mk _ (Ideal.Quotient.mk (ideal' φ) s)) =
      Ideal.Quotient.mk (ideal' (reindexHom I φ))
        (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero s) := by
  have h0 : Ideal.Quotient.mk (Ideal.map (Ideal.Quotient.mk (ideal' φ))
        (symHyperplaneSpan I E.degreeZero)) (Ideal.Quotient.mk (ideal' φ) s) =
      DoubleQuot.quotQuotMk (ideal' φ) (symHyperplaneSpan I E.degreeZero) s := rfl
  rw [resolvedConeQuotEquiv, RingEquiv.trans_apply, h0,
    DoubleQuot.quotQuotEquivQuotSup_quotQuotMk, resolvedConeSupEquiv_mk]

end Identity

/-! ## The cycle of the resolved cone of the base-changed datum -/

section Cycle

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open IntersectionTheory
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u} [Fintype σ]
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k)) [IsNoetherianRing (Base I)]
variable {E : LinearTwoTermComplex (Base I)}
variable [Module.Free (Base I) E.degreeZero] [Module.Finite (Base I) E.degreeZero]
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

/-- **The cycle-level form of the resolved-cone identity**: in the bundle `E₁` over `X`, the cycle
of the resolved cone of the base-changed datum `reindexHom I φ` — that is, of its scheme-theoretic
image under the closed immersion `E₁ ×_X X' ↪ E₁` — is the cycle of the scheme-theoretic
intersection of the resolved cone of `φ` with the hyperplane `y₀ = 0`.

This is the cycle statement that `comap_ideal'_reindexHom` gives directly.  The remaining step of
issue #75, comparing `RelativeAbsolute.relConeCycle (reindexHom I φ)` — a cycle on the *smaller*
bundle `E₁ ×_X X'` — with the Gysin image of `RelativeAbsolute.relConeCycle φ`, needs a pushforward
of cycles along that closed immersion and the corresponding comparison of dimension functions, which
the cycle API does not provide yet. -/
theorem quotientCycle_comap_ideal'_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ)
    (dim : DimensionFunction (_root_.AlgebraicGeometry.Spec
      (CommRingCat.of (SymmetricAlgebra (Base I) E.degreeZero)))) (d : ℤ) :
    HomotopyInvariance.quotientCycle
        (Ideal.comap (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero)
          (ideal' (reindexHom I φ))) dim d =
      HomotopyInvariance.quotientCycle (ideal' φ ⊔ symHyperplaneSpan I E.degreeZero) dim d :=
  HomotopyInvariance.quotientCycle_congr (comap_ideal'_reindexHom I φ h htrans) dim d

end Cycle

/-! ## The identity for the associated absolute obstruction datum -/

section AbsoluteIdentity

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u} [Fintype σ] [Fintype τ']
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable {E : LinearTwoTermComplex (Base I)}
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

/-- **The resolved-cone ideal identity of issue #75**, in the form left open by
`RelativeHyperplaneReindex.lean`: the ideal of the resolved cone of the absolute obstruction datum
associated with the base-changed relative datum `reindexHom I φ` is the image of the ideal of the
resolved cone of `absHom φ` under the scalar extension `Sym_{Base I}(E⁰) → Sym_{Base J}(Base J ⊗
E⁰)` — the coordinate-ring map of the closed immersion of the bundle `E₁ ×_X X'` into `E₁`.

The hypotheses are the Tor-independence of the normal cone (`RegularOnPowers I y₀`) and the
transversality of the resolved cone to the hyperplane (`ResolvedConeTransversal I φ`); the second
cannot be dropped, see the module docstring. -/
theorem ideal_absHom_reindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))
    (htrans : ResolvedConeTransversal I φ) :
    ResolvedCone.ideal (absHom (reindexHom I φ)) =
      Ideal.map (scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeZero)
        (ResolvedCone.ideal (absHom φ)) := by
  rw [ideal_absHom, ideal_absHom, ideal'_reindexHom I φ h htrans]

end AbsoluteIdentity

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneCone
