/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/

import GromovWitten.AlgebraicGeometry.Cones.SymmetricFunctoriality
import GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneBaseChange

/-!
# The associated graded ring of a coordinate-hyperplane base change (issue #75)

`RelativeHyperplaneReindex.lean` constructs the comparison map of associated graded rings
`grReindexHom I : gr_I(R) → gr_J(R')` attached to the coordinate-hyperplane base change
`Y' = 𝔸^{τ'} ↪ Y = 𝔸^{Option τ'}`, `y₀ = 0`, of `X = Spec (R ⧸ I) → Y`
(`R = k[x_σ, y_{Option τ'}]`, `R' = k[x_σ, y_{τ'}]`, `J = ρ(I)` for `ρ : R → R'` the specialisation
`y₀ ↦ 0`), and proves it surjective, leaving its kernel — the Tor-independence of `gr_I(R)`
along the hyperplane — open.  This file identifies that kernel.

## Main results

### The hypothesis and its equivalent formulations

* `RegularOnPowers I y`: the condition `∀ n a, y * a ∈ Iⁿ → a ∈ Iⁿ`, i.e. `y` is a
  non-zero-divisor on every `A ⧸ Iⁿ`.  It has three equivalent formulations:
  `regularOnPowers_iff_isSMulRegular` (`∀ n, IsSMulRegular (A ⧸ Iⁿ) y`),
  `regularOnPowers_iff_graded` (`y` is a non-zero-divisor on every graded piece `Iⁿ/Iⁿ⁺¹` of
  `gr_I(A)`) and, in the polynomial model, `regularOnPowers_iff_isLeftRegular_grHyperplaneCoord`
  (`y₀` is a non-zero-divisor on the normal cone `gr_I(R)` itself, the classical
  superficial-element condition: the hyperplane contains no component of the normal cone).
* `RegularOnPowers.isSMulRegular` is the `n = 1` case, which is the hypothesis used in
  `RelativeHyperplaneObstruction.lean` and `RelativeHyperplaneBaseChange.lean`.  The converse
  implication is false in general (new associated primes of `A ⧸ Iⁿ` appear), which is why the
  hypothesis is stated for all `n`.
* `RegularOnPowers.pow_inf_span` and `RegularOnPowers.pow_inf_sup`: the Tor-independence
  identities `Iⁿ ∩ (y) = y Iⁿ` and `Iⁿ ∩ (Iⁿ⁺¹ + (y)) = Iⁿ⁺¹ + y Iⁿ`, the second being the
  injectivity in degree `n` of `Base J ⊗_{Base I} gr_I(R) → gr_J(R')`.  For `n = 1` the first is
  the input of the degree-one comparison of `RelativeHyperplaneObstruction.lean`.
* Non-vacuity: `regularOnPowers_bot`, and the geometrically relevant
  `regularOnPowers_map_reindexSection`: the hypothesis holds whenever `I` is generated by
  polynomials not involving `y₀`, that is whenever `X → Y` is a product in the `y₀`-direction (the
  flat case).  It is deduced from the abstract criterion `regularOnPowers_of_polynomialHom` and the
  presentation `polyEquiv : R ≃ₐ[k] R'[y₀]`.

### The base change of the associated graded ring

* `map_algebraMap_reesAlgebra_eq` / `mem_map_algebraMap_reesAlgebra_iff`: for every ideal `K` of
  `R`, a Rees element lies in `K · Rees_I(R)` if and only if its degree-`n` coefficient lies in
  `K · Iⁿ` for every `n`.  (The case `K = I` is in the repository; the general case is what the
  hyperplane comparison needs.)
* `ker_grReindexHom`: **the Tor-independence theorem.**  Under `RegularOnPowers I y₀`,
  `RingHom.ker (grReindexHom I) = Ideal.span {algebraMap R (gr_I R) y₀}`.
* `grReindexQuotEquiv : gr_I(R) ⧸ (y₀) ≃+* gr_J(R')`, and its tensor form
  `grReindexTensorEquiv : Base J ⊗[Base I] gr_I(R) ≃+* gr_J(R')`, which is an isomorphism of
  `Base J`-algebras (`grReindexTensorAlgEquiv`) carrying `1 ⊗ z` to `grReindexHom I z`
  (`grReindexTensorEquiv_one_tmul`).  Geometrically: the normal cone of `X' ⊆ 𝔸^σ × Y'` is the
  scheme-theoretic base change along `Y' ↪ Y` of the normal cone of `X ⊆ 𝔸^σ × Y`, which is the
  Tor-independence left open by `RelativeHyperplaneReindex.surjective_grReindexHom`.
* `ker_algebraMap_base` and `baseQuotEquiv`: `Base J ≅ Base I ⧸ (y₀)` as `Base I`-algebras, i.e.
  `X'` is the hyperplane section of `X`.

### The resolved cone

The resolved-cone ideal identity `ResolvedCone.ideal (reindexHom I φ) = (ideal' φ).map …` does
*not* follow from `RegularOnPowers I y₀`: it is false in that generality.  A counterexample:
`σ = ∅` (so that the chain-map condition on `φ` is vacuous), `τ' = {y₁}`, `R = k[y₀, y₁]` and
`I = (y₁)` — for which `RegularOnPowers I y₀` holds, by `regularOnPowers_map_reindexSection` —
together with `E⁰ = Base I = k[y₀]`, `E₁ = 0` and `φ.degreeZero 1 = [y₀ y₁] ∈ I/I²`.  Then
`gr_I(R) = k[y₀][T]` and `relProductMap φ : k[y₀][u] → k[y₀][T]`, `u ↦ y₀ T`, is injective, so
`ideal' φ = ⊥` and the resolved cone is all of `E₀`; after base change `Base J = k`,
`gr_J(R') = k[T]` and `u ↦ 0`, so the ideal of the resolved cone of the base-changed datum is
`(u) ≠ ⊥`.  The obstruction is a failure of transversality of the resolved cone to the hyperplane,
*not* of the normal cone: the hypothesis on `I` alone can never suffice.

`ker_quotientSpanHom_eq_map` isolates the exact extra hypothesis: for a ring map `f : S → T` and
`y : S`, the kernel of the induced map `S ⧸ (y) → T ⧸ (f y)` is generated by the image of
`RingHom.ker f` as soon as `f y` is a non-zero-divisor on the cokernel of `f`, that is
`f y * t ∈ range f → t ∈ range f`; and `forall_mem_range_of_ker_quotientSpanHom_le` shows that this
is also necessary whenever `f y` is a non-zero-divisor on `T`.  One inclusion,
`map_ker_le_ker_quotientSpanHom`, always holds: it is the closed immersion of the resolved cone of
the hyperplane section into the hyperplane section of the resolved cone.
`ker_quotientSpanHom_doubleSubst_ne_map` is a machine-checked witness that the hypothesis cannot
be dropped: for the substitution `u ↦ 2u` of `ℤ[u]` and `y = 2` the conclusion fails, although `2`
is a non-zero-divisor on source and target and the substitution is injective.  This is the abstract
shadow of the counterexample above.  Finally
`ker_quotientSpanHom_relProductMap` is the instance of this criterion for the coordinate-ring map
`relProductMap φ` of the resolved cone of a relative obstruction datum and the hyperplane equation
`y₀` (`relProductMap_symHyperplaneCoord` identifies the hyperplane equations on `E₀` and on
`C ×_X E₀`).

### The two hyperplane sections of the resolved-cone data

Both objects the criterion speaks about are identified with the corresponding objects of the
base-changed datum `reindexHom I φ`:

* `symQuotEquiv : Sym_{Base I}(M) ⧸ (y₀) ≃+* Sym_{Base J}(Base J ⊗_{Base I} M)`, with
  `symQuotEquiv_mk_ι`; no hypothesis is needed, a symmetric algebra being a flat construction.
  For `M = E⁰` this is the restriction of the bundle `E₀` to `X'`.
* `relProductQuotEquiv : relProductRing φ ⧸ (y₀) ≃+* relProductRing (reindexHom I φ)`, with
  `relProductQuotEquiv_mk_tmul`, under `RegularOnPowers I y₀`: the restriction of `C ×_X E₀` to
  `X'` is the corresponding product for the base-changed datum.  Its proof composes
  `grReindexTensorAlgEquiv` with the flat base change of the symmetric algebra and the standard
  associativity and base-change-cancellation isomorphisms of tensor products.

The generators are also under control: `reindexHom_degreeZero_one_tmul` computes the degree-zero
component of the reindexed datum on the generators `1 ⊗ x` as the specialisation `y₀ ↦ 0` of
`φ.degreeZero` (via `reindexCotangentMap_hyperplaneCotangentMapAux`, the agreement of the two
conormal comparison maps `I/I² → J/J²`).

What remains for the resolved-cone identity of issue #75 is the commuting square
`relProductMap (reindexHom I φ) ∘ symQuotEquiv = relProductQuotEquiv ∘ (relProductMap φ mod y₀)`,
after which `ker_quotientSpanHom_relProductMap` becomes the ideal identity
`ResolvedCone.ideal (reindexHom I φ) = (ideal' φ).map …` *with* the transversality hypothesis, and
the cycle and Gysin comparisons become reachable.  Checking that square means comparing two ring
maps out of `Sym_{Base J}(Base J ⊗ E⁰)`, of which only one is visibly a map of `Base J`-algebras:
the other factors through quotients carrying a `Base I ⧸ (y₀)`-algebra structure rather than a
`Base J`-algebra structure, so it has to be repackaged (using the analogues of
`symQuotEquiv_mk_ι` and `relProductQuotEquiv_mk_tmul` for `algebraMap`) before
`SymmetricAlgebra.algHom_ext` applies; on the generators `ι (1 ⊗ x)` the two sides then agree by
`relProductMap_ι`, `relProductQuotEquiv_mk_tmul`, `scalarExtensionMap_ι`,
`reindexHom_degreeZero_one_tmul` and
`RelativeHyperplaneReindex.grReindexHom_conormalToAssociatedGraded`.
-/

universe u

namespace GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneCone

/-! ## Regularity on all powers of an ideal -/

section Regular

variable {A : Type*} [CommRing A]

/-- **`y` is a non-zero-divisor on `A ⧸ Iⁿ` for every `n`**, stated elementwise.  For `n = 1`
this is the hypothesis `IsSMulRegular (A ⧸ I) y` used in the hyperplane base change of the
conormal complex; the statement for all `n` is what the associated graded ring needs, and it is
strictly stronger. -/
def RegularOnPowers (I : Ideal A) (y : A) : Prop :=
  ∀ (n : ℕ) (a : A), y * a ∈ I ^ n → a ∈ I ^ n

/-- Elementwise description of `IsSMulRegular (A ⧸ I) y`. -/
theorem isSMulRegular_quotient_iff (I : Ideal A) (y : A) :
    IsSMulRegular (A ⧸ I) (Ideal.Quotient.mk I y) ↔ ∀ a : A, y * a ∈ I → a ∈ I := by
  constructor
  · intro h a ha
    have h0 : Ideal.Quotient.mk I y • Ideal.Quotient.mk I a =
        Ideal.Quotient.mk I y • (0 : A ⧸ I) := by
      rw [smul_zero, smul_eq_mul, ← map_mul]
      exact Ideal.Quotient.eq_zero_iff_mem.2 ha
    exact Ideal.Quotient.eq_zero_iff_mem.1 (h h0)
  · intro h a b hab
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective b
    have hmul : Ideal.Quotient.mk I (y * a) = Ideal.Quotient.mk I (y * b) := by
      rw [map_mul, map_mul]
      simpa only [smul_eq_mul] using hab
    rw [Ideal.Quotient.eq] at hmul ⊢
    refine h _ ?_
    rw [mul_sub]
    exact hmul

/-- **First equivalent formulation**: regularity on all powers is `IsSMulRegular (A ⧸ Iⁿ) y`
for every `n`. -/
theorem regularOnPowers_iff_isSMulRegular (I : Ideal A) (y : A) :
    RegularOnPowers I y ↔
      ∀ n : ℕ, IsSMulRegular (A ⧸ I ^ n) (Ideal.Quotient.mk (I ^ n) y) := by
  constructor
  · intro h n
    exact (isSMulRegular_quotient_iff _ _).2 (h n)
  · intro h n
    exact (isSMulRegular_quotient_iff _ _).1 (h n)

/-- **Second equivalent formulation**: `y` is a non-zero-divisor on every graded piece
`Iⁿ/Iⁿ⁺¹` of `gr_I(A)`, that is, on `gr_I(A)` itself. -/
theorem regularOnPowers_iff_graded (I : Ideal A) (y : A) :
    RegularOnPowers I y ↔
      ∀ (n : ℕ) (a : A), a ∈ I ^ n → y * a ∈ I ^ (n + 1) → a ∈ I ^ (n + 1) := by
  constructor
  · intro h n a _ hya
    exact h (n + 1) a hya
  · intro h n
    induction n with
    | zero =>
      intro a _
      rw [pow_zero, Ideal.one_eq_top]
      exact Submodule.mem_top (R := A) (M := A)
    | succ m ih =>
      intro a ha
      have ham : y * a ∈ I ^ m := Ideal.pow_le_pow_right (Nat.le_succ m) ha
      exact h m a (ih a ham) ha

/-- The `n = 1` case: regularity on all powers implies the hypothesis
`IsSMulRegular (A ⧸ I) y` of the hyperplane base change of the conormal complex. -/
theorem RegularOnPowers.isSMulRegular {I : Ideal A} {y : A} (h : RegularOnPowers I y) :
    IsSMulRegular (A ⧸ I) (Ideal.Quotient.mk I y) := by
  refine (isSMulRegular_quotient_iff I y).2 fun a ha => ?_
  have h1 := h 1 a (by rwa [pow_one])
  rwa [pow_one] at h1

/-- **The Tor-independence consequence.**  If `y` is a non-zero-divisor on all `A ⧸ Iⁿ`, then
`Iⁿ ∩ (Iⁿ⁺¹ + (y)) ⊆ Iⁿ⁺¹ + y Iⁿ`; the right-hand side is written `(I ⊔ (y)) * Iⁿ`, the form in
which the Rees algebra needs it. -/
theorem RegularOnPowers.mem_sup_mul {I : Ideal A} {y : A} (h : RegularOnPowers I y) {n : ℕ}
    {a : A} (ha : a ∈ I ^ n) (ha' : a ∈ I ^ (n + 1) ⊔ Ideal.span {y}) :
    a ∈ (I ⊔ Ideal.span {y}) * I ^ n := by
  obtain ⟨b, hb, c, hc, rfl⟩ := Submodule.mem_sup.1 ha'
  obtain ⟨d, rfl⟩ := Ideal.mem_span_singleton'.1 hc
  have hdn : d ∈ I ^ n := by
    refine h n d ?_
    have hbn : b ∈ I ^ n := Ideal.pow_le_pow_right (Nat.le_succ n) hb
    have : y * d = b + d * y - b := by ring
    rw [this]
    exact Ideal.sub_mem _ ha hbn
  refine Ideal.add_mem _ ?_ ?_
  · have hb' : b ∈ I * I ^ n := by rwa [pow_succ'] at hb
    exact Ideal.mul_mono_left le_sup_left hb'
  · have hyd : d * y = y * d := mul_comm d y
    rw [hyd]
    exact Ideal.mul_mem_mul (Ideal.mem_sup_right (Ideal.mem_span_singleton_self y)) hdn

/-- **The Tor-independence identity `Iⁿ ∩ (y) = y Iⁿ`.**  For `n = 1` this is the input
`I ∩ (y₀) = y₀ I` of the degree-one comparison
`RelativeHyperplaneObstruction.hyperplaneCotangentEquiv`, which only needs the `n = 1` case of the
hypothesis; the statement for all `n` is what the associated graded ring needs. -/
theorem RegularOnPowers.pow_inf_span {I : Ideal A} {y : A} (h : RegularOnPowers I y) (n : ℕ) :
    I ^ n ⊓ Ideal.span {y} = Ideal.span {y} * I ^ n := by
  refine le_antisymm (fun a ha => ?_) (le_inf Ideal.mul_le_right Ideal.mul_le_left)
  obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.1 (Submodule.mem_inf.1 ha).2
  have hcn : c ∈ I ^ n := by
    refine h n c ?_
    have hyc : y * c = c * y := mul_comm y c
    rw [hyc]
    exact (Submodule.mem_inf.1 ha).1
  have hyc : c * y = y * c := mul_comm c y
  rw [hyc]
  exact Ideal.mul_mem_mul (Ideal.mem_span_singleton_self y) hcn

/-- **The degreewise Tor-independence identity** `Iⁿ ∩ (Iⁿ⁺¹ + (y)) = Iⁿ⁺¹ + y Iⁿ`, which is the
injectivity in degree `n` of `Base J ⊗_{Base I} gr_I(R) → gr_J(R')`.  The inclusion `⊇` is
unconditional. -/
theorem RegularOnPowers.pow_inf_sup {I : Ideal A} {y : A} (h : RegularOnPowers I y) (n : ℕ) :
    I ^ n ⊓ (I ^ (n + 1) ⊔ Ideal.span {y}) = I ^ (n + 1) ⊔ Ideal.span {y} * I ^ n := by
  refine le_antisymm (fun a ha => ?_) ?_
  · have h1 := h.mem_sup_mul (Submodule.mem_inf.1 ha).1 (Submodule.mem_inf.1 ha).2
    rwa [Ideal.sup_mul, ← pow_succ'] at h1
  · refine le_inf (sup_le ?_ Ideal.mul_le_right) (sup_le le_sup_left ?_)
    · exact Ideal.pow_le_pow_right (Nat.le_succ n)
    · exact le_trans Ideal.mul_le_left le_sup_right

/-- **First sufficient condition** (non-vacuity): a non-zero-divisor of `A` is regular on all
powers of the zero ideal. -/
theorem regularOnPowers_bot {y : A} (hy : IsLeftRegular y) : RegularOnPowers (⊥ : Ideal A) y := by
  intro n a ha
  match n with
  | 0 =>
    rw [pow_zero, Ideal.one_eq_top]
    exact Submodule.mem_top (R := A) (M := A)
  | (m + 1) =>
    rw [Ideal.bot_pow (Nat.succ_ne_zero m)] at ha ⊢
    have hya : y * a = y * 0 := by
      rw [mul_zero]
      exact Ideal.mem_bot.1 ha
    exact Ideal.mem_bot.2 (hy hya)

end Regular

/-! ## Ideals of the Rees algebra extended from the base ring -/

section Rees

variable {R : Type*} [CommRing R] (I K : Ideal R)

/-- **The coefficientwise ideal** of the Rees algebra: the Rees elements all of whose degree-`n`
coefficients lie in `K · Iⁿ`.  It is the extension of `K` to `Rees_I(R)`, see
`map_algebraMap_reesAlgebra_eq`. -/
def reesCoeffIdeal : Ideal (reesAlgebra I) where
  carrier := {q : reesAlgebra I | ∀ n : ℕ, (q : Polynomial R).coeff n ∈ K * I ^ n}
  add_mem' := by
    intro x y hx hy n
    have hco : ((x + y : reesAlgebra I) : Polynomial R) =
        (x : Polynomial R) + (y : Polynomial R) := rfl
    rw [hco, Polynomial.coeff_add]
    exact Ideal.add_mem _ (hx n) (hy n)
  zero_mem' := by
    intro n
    have hco : ((0 : reesAlgebra I) : Polynomial R) = 0 := rfl
    rw [hco, Polynomial.coeff_zero]
    exact Submodule.zero_mem _
  smul_mem' := by
    intro c x hx n
    have hco : ((c • x : reesAlgebra I) : Polynomial R) =
        (c : Polynomial R) * (x : Polynomial R) := rfl
    rw [hco, Polynomial.coeff_mul]
    refine Ideal.sum_mem _ fun ij hij => ?_
    have hci : (c : Polynomial R).coeff ij.1 ∈ I ^ ij.1 := (mem_reesAlgebra_iff I _).1 c.2 ij.1
    have hmem := Ideal.mul_mem_mul hci (hx ij.2)
    have heq : I ^ ij.1 * (K * I ^ ij.2) = K * I ^ n := by
      rw [mul_left_comm, ← pow_add, Finset.mem_antidiagonal.1 hij]
    rwa [heq] at hmem

theorem mem_reesCoeffIdeal_iff {q : reesAlgebra I} :
    q ∈ reesCoeffIdeal I K ↔ ∀ n : ℕ, (q : Polynomial R).coeff n ∈ K * I ^ n :=
  Iff.rfl

/-- **The extension of an ideal `K` of `R` to the Rees algebra of `I` is computed
coefficientwise**: `K · Rees_I(R)` consists of the Rees elements whose degree-`n` coefficient lies
in `K · Iⁿ`.  For `K = I` this is the pair of results
`AffineNormalCone.coeff_mem_pow_succ_of_mem_map_rees` and
`AffineDeformationSpace.mem_map_of_forall_coeff_mem_pow_succ` of the repository; the general case
is what the comparison of associated graded rings along a hyperplane needs. -/
theorem map_algebraMap_reesAlgebra_eq :
    Ideal.map (algebraMap R (reesAlgebra I)) K = reesCoeffIdeal I K := by
  classical
  refine le_antisymm ?_ ?_
  · rw [Ideal.map_le_iff_le_comap]
    intro a ha
    refine (mem_reesCoeffIdeal_iff I K).2 fun n => ?_
    have hcoe : ((algebraMap R (reesAlgebra I) a : reesAlgebra I) : Polynomial R) =
        Polynomial.C a := rfl
    rw [hcoe, Polynomial.coeff_C]
    match n with
    | 0 =>
      rw [if_pos rfl, pow_zero, mul_one]
      exact ha
    | (m + 1) =>
      rw [if_neg (Nat.succ_ne_zero m)]
      exact Submodule.zero_mem _
  · intro q hq
    have key : ∀ (i : ℕ) (c : R), c ∈ K * I ^ i →
        ∃ hc : c ∈ I ^ i, (⟨Polynomial.monomial i c, reesAlgebra.monomial_mem.mpr hc⟩ :
          reesAlgebra I) ∈ Ideal.map (algebraMap R (reesAlgebra I)) K := by
      intro i c hc
      refine Submodule.mul_induction_on hc ?_ ?_
      · intro a ha b hb
        refine ⟨Ideal.mul_mem_left _ a hb, ?_⟩
        have hmon : (⟨Polynomial.monomial i (a * b),
              reesAlgebra.monomial_mem.mpr (Ideal.mul_mem_left _ a hb)⟩ : reesAlgebra I) =
            algebraMap R (reesAlgebra I) a * ⟨Polynomial.monomial i b,
              reesAlgebra.monomial_mem.mpr hb⟩ := by
          apply Subtype.ext
          change Polynomial.monomial i (a * b) = Polynomial.C a * Polynomial.monomial i b
          rw [Polynomial.C_mul_monomial]
        rw [hmon]
        exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ ha)
      · rintro x y ⟨hx, hx'⟩ ⟨hy, hy'⟩
        refine ⟨Ideal.add_mem _ hx hy, ?_⟩
        have hadd : (⟨Polynomial.monomial i (x + y),
              reesAlgebra.monomial_mem.mpr (Ideal.add_mem _ hx hy)⟩ : reesAlgebra I) =
            (⟨Polynomial.monomial i x, reesAlgebra.monomial_mem.mpr hx⟩ : reesAlgebra I) +
              ⟨Polynomial.monomial i y, reesAlgebra.monomial_mem.mpr hy⟩ := by
          apply Subtype.ext
          change Polynomial.monomial i (x + y) =
            Polynomial.monomial i x + Polynomial.monomial i y
          rw [map_add]
        rw [hadd]
        exact Ideal.add_mem _ hx' hy'
    have hsum : q = ∑ i ∈ (q : Polynomial R).support,
        (⟨Polynomial.monomial i ((q : Polynomial R).coeff i),
          reesAlgebra.monomial_mem.mpr ((mem_reesAlgebra_iff I _).mp q.2 i)⟩ : reesAlgebra I) := by
      apply Subtype.ext
      rw [AddSubmonoidClass.coe_finsetSum]
      exact Polynomial.as_sum_support (q : Polynomial R)
    rw [hsum]
    refine Ideal.sum_mem _ fun i _ ↦ ?_
    obtain ⟨_, h⟩ := key i _ ((mem_reesCoeffIdeal_iff I K).1 hq i)
    exact h

/-- Coefficientwise membership in `K · Rees_I(R)`. -/
theorem mem_map_algebraMap_reesAlgebra_iff {q : reesAlgebra I} :
    q ∈ Ideal.map (algebraMap R (reesAlgebra I)) K ↔
      ∀ n : ℕ, (q : Polynomial R).coeff n ∈ K * I ^ n := by
  rw [map_algebraMap_reesAlgebra_eq]
  exact mem_reesCoeffIdeal_iff I K

end Rees

/-! ## The kernel of the graded comparison map of a coordinate hyperplane -/

section Hyperplane

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex AffineNormalCone
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open ConeTranslation (Gr)

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))

/-- **The class of the hyperplane coordinate `y₀` in `gr_I(R)`**, that is, the image of `y₀` under
`R → Base I → gr_I(R)`: the equation of the hyperplane on the normal cone. -/
noncomputable abbrev grHyperplaneCoord : Gr I :=
  algebraMap (Base I) (Gr I)
    (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))

theorem grHyperplaneCoord_eq_mk :
    grHyperplaneCoord I = Ideal.Quotient.mk _
      (algebraMap (MvPolynomial (σ ⊕ Option τ') k) (reesAlgebra I)
        (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :=
  rfl

/-- The Rees comparison map acts coefficientwise by the specialisation `ρ : y₀ ↦ 0`. -/
theorem coeff_reesReindexHom (x : reesAlgebra I) (n : ℕ) :
    ((reesReindexHom I x : reesAlgebra (reindexIdeal I)) :
        Polynomial (MvPolynomial (σ ⊕ τ') k)).coeff n =
      reindexAlgHom ((x : Polynomial (MvPolynomial (σ ⊕ Option τ') k)).coeff n) := by
  rw [coe_reesReindexHom, Polynomial.coeff_map]
  rfl

/-- **An element whose specialisation lies in `Jⁿ` lies in `Iⁿ + (y₀)`**, because `ρ` is surjective
with kernel `(y₀)` and `J = ρ(I)`. -/
theorem mem_sup_span_of_reindexAlgHom_mem_pow {n : ℕ}
    {a : MvPolynomial (σ ⊕ Option τ') k} (ha : reindexAlgHom a ∈ reindexIdeal I ^ n) :
    a ∈ I ^ n ⊔ Ideal.span {hyperplaneCoord (k := k) (σ := σ) (τ' := τ')} := by
  rw [← Ideal.map_pow] at ha
  obtain ⟨b, hb, hab⟩ := (Ideal.mem_map_iff_of_surjective _ surjective_reindexAlgHom).1 ha
  have hsub : a - b ∈ Ideal.span {hyperplaneCoord (k := k) (σ := σ) (τ' := τ')} := by
    rw [← ker_reindexAlgHom, RingHom.mem_ker, map_sub, hab, sub_self]
  exact Submodule.mem_sup.2 ⟨b, hb, a - b, hsub, by ring⟩

/-- **The Tor-independence of the associated graded ring along the hyperplane `y₀ = 0`.**

If `y₀` is a non-zero-divisor on every `R ⧸ Iⁿ` (`RegularOnPowers`), the kernel of the comparison
map `gr_I(R) → gr_J(R')` of `RelativeHyperplaneReindex` is generated by the equation `y₀` of the
hyperplane.  Degreewise this is the ideal identity `Iⁿ ∩ (Iⁿ⁺¹ + (y₀)) = Iⁿ⁺¹ + y₀ Iⁿ`.  Together
with `RelativeHyperplaneReindex.surjective_grReindexHom` it says that the normal cone of
`X' ⊆ 𝔸^σ × Y'` is the scheme-theoretic base change along `Y' ↪ Y` of the normal cone of
`X ⊆ 𝔸^σ × Y`. -/
theorem ker_grReindexHom
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    RingHom.ker (grReindexHom I) = Ideal.span {grHyperplaneCoord I} := by
  rw [grHyperplaneCoord_eq_mk]
  refine le_antisymm ?_ ?_
  · intro z hz
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective z
    rw [RingHom.mem_ker, grReindexHom_mk, Ideal.Quotient.eq_zero_iff_mem,
      mem_map_algebraMap_reesAlgebra_iff] at hz
    have hx : x ∈ Ideal.map (algebraMap (MvPolynomial (σ ⊕ Option τ') k) (reesAlgebra I))
        (hyperplaneIdeal I) := by
      rw [mem_map_algebraMap_reesAlgebra_iff]
      intro n
      have h1 : reindexAlgHom ((x : Polynomial (MvPolynomial (σ ⊕ Option τ') k)).coeff n) ∈
          reindexIdeal I ^ (n + 1) := by
        have hn := hz n
        rw [coeff_reesReindexHom, ← pow_succ'] at hn
        exact hn
      exact h.mem_sup_mul ((mem_reesAlgebra_iff I _).1 x.2 n)
        (mem_sup_span_of_reindexAlgHom_mem_pow I h1)
    rw [hyperplaneIdeal, Ideal.map_sup, Ideal.map_span, Set.image_singleton] at hx
    obtain ⟨u, hu, v, hv, huv⟩ := Submodule.mem_sup.1 hx
    rw [← huv, map_add, Ideal.Quotient.eq_zero_iff_mem.2 hu, zero_add]
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.1 hv
    rw [map_mul]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker,
      grReindexHom_mk, reesReindexHom_algebraMap, reindexAlgHom_hyperplaneCoord, map_zero]
    exact map_zero _

/-- **The associated graded ring of the hyperplane section is the base change of the associated
graded ring**: `gr_J(R') ≅ gr_I(R) ⧸ y₀ gr_I(R) ≅ Base J ⊗_{Base I} gr_I(R)`, the coordinate-ring
form of "the normal cone of `X'` is the base change of the normal cone of `X`". -/
noncomputable def grReindexQuotEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    (Gr I ⧸ Ideal.span {grHyperplaneCoord I}) ≃+* Gr (reindexIdeal I) :=
  (Ideal.quotEquivOfEq (ker_grReindexHom I h).symm).trans
    (RingHom.quotientKerEquivOfSurjective (surjective_grReindexHom I))

@[simp]
theorem grReindexQuotEquiv_mk
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) (z : Gr I) :
    grReindexQuotEquiv I h (Ideal.Quotient.mk _ z) = grReindexHom I z := by
  rw [grReindexQuotEquiv, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk,
    RingHom.quotientKerEquivOfSurjective_apply_mk]

/-- **The class in `gr_I(R)` of a monomial `a tⁿ`** with `a ∈ Iⁿ`: a general element of the
degree-`n` piece `Iⁿ/Iⁿ⁺¹` of the normal cone. -/
noncomputable def grMonomial {n : ℕ} {a : MvPolynomial (σ ⊕ Option τ') k} (ha : a ∈ I ^ n) :
    Gr I :=
  Ideal.Quotient.mk _ ⟨Polynomial.monomial n a, reesAlgebra.monomial_mem.mpr ha⟩

theorem coe_reesMonomial {n : ℕ} {a : MvPolynomial (σ ⊕ Option τ') k} (ha : a ∈ I ^ n) :
    ((⟨Polynomial.monomial n a, reesAlgebra.monomial_mem.mpr ha⟩ : reesAlgebra I) :
        Polynomial (MvPolynomial (σ ⊕ Option τ') k)) = Polynomial.monomial n a :=
  rfl

/-- **A degree-`n` class of the normal cone vanishes exactly when its representative lies in
`Iⁿ⁺¹`.** -/
theorem grMonomial_eq_zero_iff {n : ℕ} {a : MvPolynomial (σ ⊕ Option τ') k} (ha : a ∈ I ^ n) :
    grMonomial I ha = 0 ↔ a ∈ I ^ (n + 1) := by
  rw [grMonomial, Ideal.Quotient.eq_zero_iff_mem, mem_map_algebraMap_reesAlgebra_iff]
  constructor
  · intro hmem
    have hn := hmem n
    rw [coe_reesMonomial I ha, Polynomial.coeff_monomial, if_pos rfl, ← pow_succ'] at hn
    exact hn
  · intro hmem m
    rw [coe_reesMonomial I ha, Polynomial.coeff_monomial]
    by_cases hmn : n = m
    · subst hmn
      rw [if_pos rfl, ← pow_succ']
      exact hmem
    · rw [if_neg hmn]
      exact Submodule.zero_mem _

/-- Multiplying a degree-`n` class of the normal cone by the hyperplane equation `y₀`. -/
theorem grHyperplaneCoord_mul_grMonomial {n : ℕ} {a : MvPolynomial (σ ⊕ Option τ') k}
    (ha : a ∈ I ^ n) :
    grHyperplaneCoord I * grMonomial I ha =
      grMonomial I (Ideal.mul_mem_left (I ^ n)
        (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) ha) := by
  rw [grHyperplaneCoord_eq_mk, grMonomial, grMonomial, ← map_mul]
  refine congrArg _ (Subtype.ext ?_)
  change Polynomial.C (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) *
    Polynomial.monomial n a = Polynomial.monomial n (hyperplaneCoord * a)
  rw [Polynomial.C_mul_monomial]

/-- **Under `RegularOnPowers I y₀`, the hyperplane equation is a non-zero-divisor on the normal
cone `gr_I(R)`**: no component of the normal cone of `X ⊆ 𝔸^σ × Y` is contained in the
hyperplane. -/
theorem isLeftRegular_grHyperplaneCoord
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    IsLeftRegular (grHyperplaneCoord I) := by
  have key : ∀ z : Gr I, grHyperplaneCoord I * z = 0 → z = 0 := by
    intro z hz
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective z
    rw [grHyperplaneCoord_eq_mk, ← map_mul, Ideal.Quotient.eq_zero_iff_mem,
      mem_map_algebraMap_reesAlgebra_iff] at hz
    rw [Ideal.Quotient.eq_zero_iff_mem, mem_map_algebraMap_reesAlgebra_iff]
    intro n
    have hcoe : (((algebraMap (MvPolynomial (σ ⊕ Option τ') k) (reesAlgebra I)
          (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) * x : reesAlgebra I)) :
          Polynomial (MvPolynomial (σ ⊕ Option τ') k)).coeff n =
        hyperplaneCoord * (x : Polynomial (MvPolynomial (σ ⊕ Option τ') k)).coeff n := by
      change (Polynomial.C (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) *
        (x : Polynomial (MvPolynomial (σ ⊕ Option τ') k))).coeff n = _
      rw [Polynomial.coeff_C_mul]
    have hn := hz n
    rw [hcoe, ← pow_succ'] at hn
    have hx := h (n + 1) _ hn
    rwa [← pow_succ']
  intro a b hab
  have hab' : grHyperplaneCoord I * a = grHyperplaneCoord I * b := hab
  have h0 : grHyperplaneCoord I * (a - b) = 0 := by
    rw [mul_sub, hab', sub_self]
  exact sub_eq_zero.1 (key _ h0)

/-- **Third equivalent formulation of the hypothesis, the geometric one**: `y₀` is a
non-zero-divisor on every `R ⧸ Iⁿ` if and only if it is a non-zero-divisor on the normal cone
`gr_I(R)`, i.e. if and only if the hyperplane `y₀ = 0` contains no component of the normal cone of
`X ⊆ 𝔸^σ × Y`.  (This is the classical "superficial element" condition, and the reason why the
degree-one hypothesis `IsSMulRegular (Base I) y₀` of `RelativeHyperplaneObstruction.lean` is not
enough for the cone.) -/
theorem regularOnPowers_iff_isLeftRegular_grHyperplaneCoord :
    RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) ↔
      IsLeftRegular (grHyperplaneCoord I) := by
  refine ⟨isLeftRegular_grHyperplaneCoord I, fun hreg => ?_⟩
  rw [regularOnPowers_iff_graded]
  intro n a ha hya
  have h1 : grHyperplaneCoord I * grMonomial I ha = grHyperplaneCoord I * 0 := by
    rw [mul_zero, grHyperplaneCoord_mul_grMonomial, grMonomial_eq_zero_iff]
    exact hya
  exact (grMonomial_eq_zero_iff I ha).1 (hreg h1)

end Hyperplane

/-! ## The flat case: ideals generated by polynomials not involving `y₀` -/

section FlatCase

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex

/-- **Abstract sufficient condition.**  If `A` is a polynomial ring `A₀[y]` in `y` and `I` is
extended from an ideal of `A₀`, then `y` is a non-zero-divisor on every `A ⧸ Iⁿ`: membership in
`I₀ⁿ · A₀[y]` is a condition on coefficients, and multiplication by `y` only shifts coefficients. -/
theorem regularOnPowers_of_polynomialHom {A : Type*} [CommRing A] {A₀ : Type*} [CommRing A₀]
    (f : A →+* Polynomial A₀) (hf : Function.Bijective f) {y : A} (hy : f y = Polynomial.X)
    {I : Ideal A} {I₀ : Ideal A₀}
    (hI : Ideal.map f I = Ideal.map (Polynomial.C : A₀ →+* Polynomial A₀) I₀) :
    RegularOnPowers I y := by
  intro n a ha
  have hmapn : Ideal.map f (I ^ n) =
      Ideal.map (Polynomial.C : A₀ →+* Polynomial A₀) (I₀ ^ n) := by
    rw [Ideal.map_pow, Ideal.map_pow, hI]
  have hmem : Polynomial.X * f a ∈
      Ideal.map (Polynomial.C : A₀ →+* Polynomial A₀) (I₀ ^ n) := by
    rw [← hmapn, ← hy, ← map_mul]
    exact Ideal.mem_map_of_mem _ ha
  have hcoeff : ∀ m : ℕ, (f a).coeff m ∈ I₀ ^ n := by
    intro m
    have hm := Ideal.mem_map_C_iff.1 hmem (m + 1)
    rwa [Polynomial.coeff_X_mul] at hm
  have hea : f a ∈ Ideal.map f (I ^ n) := by
    rw [hmapn]
    exact Ideal.mem_map_C_iff.2 hcoeff
  obtain ⟨b, hb, hab⟩ := (Ideal.mem_map_iff_of_surjective f hf.2).1 hea
  have hba : b = a := hf.1 hab
  rw [← hba]
  exact hb

variable {k : Type u} [CommRing k] {σ τ' : Type u}

/-- The reindexing `σ ⊕ Option τ' ≃ Option (σ ⊕ τ')` which makes `y₀` the distinguished
variable. -/
def sumOptionEquiv : σ ⊕ Option τ' ≃ Option (σ ⊕ τ') where
  toFun x := match x with
    | Sum.inl i => some (Sum.inl i)
    | Sum.inr none => none
    | Sum.inr (some j) => some (Sum.inr j)
  invFun x := match x with
    | none => Sum.inr none
    | some (Sum.inl i) => Sum.inl i
    | some (Sum.inr j) => Sum.inr (some j)
  left_inv x := by rcases x with i | (_ | j) <;> rfl
  right_inv x := by rcases x with _ | (i | j) <;> rfl

/-- **`R = k[x_σ, y_{Option τ'}]` as the polynomial ring `R'[y₀]`** over
`R' = k[x_σ, y_{τ'}]`. -/
noncomputable def polyEquiv :
    MvPolynomial (σ ⊕ Option τ') k ≃ₐ[k] Polynomial (MvPolynomial (σ ⊕ τ') k) :=
  (MvPolynomial.renameEquiv k sumOptionEquiv).trans (MvPolynomial.optionEquivLeft k (σ ⊕ τ'))

theorem polyEquiv_hyperplaneCoord :
    polyEquiv (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) = Polynomial.X := by
  have h1 : (MvPolynomial.renameEquiv k (sumOptionEquiv (σ := σ) (τ' := τ')))
      (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) =
      MvPolynomial.X (none : Option (σ ⊕ τ')) := by
    simp [hyperplaneCoord, sumOptionEquiv]
  rw [polyEquiv, AlgEquiv.trans_apply, h1, MvPolynomial.optionEquivLeft_X_none]

theorem polyEquiv_X_some (v : σ ⊕ τ') :
    polyEquiv (MvPolynomial.X (sumOptionEquiv.symm (some v)) :
        MvPolynomial (σ ⊕ Option τ') k) = Polynomial.C (MvPolynomial.X v) := by
  rw [polyEquiv, AlgEquiv.trans_apply, MvPolynomial.renameEquiv_apply, MvPolynomial.rename_X,
    Equiv.apply_symm_apply, MvPolynomial.optionEquivLeft_X_some]

/-- **The section `R' → R` becomes the inclusion of constants** under `polyEquiv`. -/
theorem polyEquiv_reindexSection (g : MvPolynomial (σ ⊕ τ') k) :
    polyEquiv (reindexSection g) = Polynomial.C g := by
  induction g using MvPolynomial.induction_on with
  | C a =>
    have h1 : reindexSection (MvPolynomial.C a : MvPolynomial (σ ⊕ τ') k) =
        MvPolynomial.C a := by
      simp [reindexSection]
    have h2 : (MvPolynomial.renameEquiv k (sumOptionEquiv (σ := σ) (τ' := τ')))
        (MvPolynomial.C a) = MvPolynomial.C a := by
      simp
    rw [h1, polyEquiv, AlgEquiv.trans_apply, h2, MvPolynomial.optionEquivLeft_C]
  | add p q hp hq => rw [map_add, map_add, hp, hq, map_add]
  | mul_X p v hp =>
    rw [map_mul, map_mul, hp, map_mul]
    refine congrArg (fun z => Polynomial.C p * z) ?_
    have hv : reindexSection (MvPolynomial.X v : MvPolynomial (σ ⊕ τ') k) =
        MvPolynomial.X (sumOptionEquiv.symm (some v)) := by
      rcases v with i | j
      · rw [reindexSection_X_inl]
        rfl
      · rw [reindexSection_X_inr]
        rfl
    rw [hv, polyEquiv_X_some]

/-- **Second sufficient condition** (the geometrically relevant one, non-vacuity of the
hypothesis): if the ideal `I` of `X` is generated by polynomials not involving `y₀` — that is, if
`X → Y` is a product in the `y₀`-direction, the flat case — then `y₀` is a non-zero-divisor on
every `R ⧸ Iⁿ`, so `ker_grReindexHom` applies. -/
theorem regularOnPowers_map_reindexSection (I₀ : Ideal (MvPolynomial (σ ⊕ τ') k)) :
    RegularOnPowers (Ideal.map (reindexSection (k := k) (σ := σ) (τ' := τ')) I₀)
      (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')) := by
  refine regularOnPowers_of_polynomialHom
    ((polyEquiv (k := k) (σ := σ) (τ' := τ')).toRingEquiv : _ →+* _)
    (polyEquiv (k := k) (σ := σ) (τ' := τ')).bijective polyEquiv_hyperplaneCoord (I₀ := I₀) ?_
  have hcoe : ∀ g : MvPolynomial (σ ⊕ τ') k,
      ((polyEquiv (k := k) (σ := σ) (τ' := τ')).toRingEquiv : _ →+* _) (reindexSection g) =
        Polynomial.C g := polyEquiv_reindexSection
  refine le_antisymm ?_ ?_
  · rw [Ideal.map_le_iff_le_comap, Ideal.map_le_iff_le_comap]
    intro b hb
    rw [Ideal.mem_comap, Ideal.mem_comap, hcoe]
    exact Ideal.mem_map_of_mem _ hb
  · rw [Ideal.map_le_iff_le_comap]
    intro b hb
    rw [Ideal.mem_comap, ← hcoe b]
    exact Ideal.mem_map_of_mem _ (Ideal.mem_map_of_mem _ hb)

end FlatCase

/-! ## Kernels after dividing by one element: the resolved cone of a hyperplane section -/

section KernelBaseChange

variable {S T : Type*} [CommRing S] [CommRing T] (f : S →+* T) (y : S)

theorem span_le_comap_span : Ideal.span {y} ≤ Ideal.comap f (Ideal.span {f y}) := by
  rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, Ideal.mem_comap]
  exact Ideal.mem_span_singleton_self _

/-- **The hyperplane section of a ring map**: the map induced by `f` on the quotients by `y` and
`f y`.  For `f = relProductMap φ` the coordinate-ring map of the resolved cone and `y = y₀` the
equation of the hyperplane, this is the coordinate-ring map of the resolved cone intersected with
the hyperplane. -/
def quotientSpanHom : S ⧸ Ideal.span {y} →+* T ⧸ Ideal.span {f y} :=
  Ideal.quotientMap _ f (span_le_comap_span f y)

@[simp]
theorem quotientSpanHom_mk (s : S) :
    quotientSpanHom f y (Ideal.Quotient.mk _ s) = Ideal.Quotient.mk _ (f s) :=
  rfl

theorem mem_ker_quotientSpanHom_iff {s : S} :
    Ideal.Quotient.mk (Ideal.span {y}) s ∈ RingHom.ker (quotientSpanHom f y) ↔
      f s ∈ Ideal.span {f y} := by
  rw [RingHom.mem_ker, quotientSpanHom_mk, Ideal.Quotient.eq_zero_iff_mem]

/-- **The always-true inclusion**: the ideal generated by the image of `ker f` is contained in the
kernel of the hyperplane section of `f`.  Geometrically: the hyperplane section of the closed
subscheme cut out by `ker f` contains the closed subscheme cut out by the kernel of the
hyperplane-section map — the closed immersion of the resolved cone of the base-changed datum into
the base change of the resolved cone. -/
theorem map_ker_le_ker_quotientSpanHom :
    Ideal.map (Ideal.Quotient.mk (Ideal.span {y})) (RingHom.ker f) ≤
      RingHom.ker (quotientSpanHom f y) := by
  rw [Ideal.map_le_iff_le_comap]
  intro s hs
  rw [Ideal.mem_comap, mem_ker_quotientSpanHom_iff, RingHom.mem_ker.1 hs]
  exact Submodule.zero_mem _

/-- **The criterion for the kernel to base-change.**  If `f y` is a non-zero-divisor on the
cokernel of `f` — that is, if `f y * t` lies in the image of `f` only when `t` does — then the
kernel of the hyperplane section of `f` is generated by the image of `ker f`.

For `f = relProductMap φ` and `y = y₀` this is the transversality of the resolved cone of `φ` to
the hyperplane `y₀ = 0`, and it is exactly what the resolved-cone ideal identity of issue #75
needs: it does *not* follow from `RegularOnPowers I y₀` (see the counterexample in the module
docstring). -/
theorem ker_quotientSpanHom_eq_map
    (h : ∀ t : T, f y * t ∈ Set.range f → t ∈ Set.range f) :
    RingHom.ker (quotientSpanHom f y) =
      Ideal.map (Ideal.Quotient.mk (Ideal.span {y})) (RingHom.ker f) := by
  refine le_antisymm ?_ (map_ker_le_ker_quotientSpanHom f y)
  intro z hz
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective z
  rw [mem_ker_quotientSpanHom_iff] at hz
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 hz
  have hfs : f y * c = f s := by
    rw [mul_comm]
    exact hc
  obtain ⟨s', hs'⟩ := h c ⟨s, hfs.symm⟩
  have hker : s - y * s' ∈ RingHom.ker f := by
    have h1 : f (s - y * s') = f s - f y * c := by
      rw [map_sub, map_mul, hs']
    rw [RingHom.mem_ker, h1, ← hfs, sub_self]
  have hmk : Ideal.Quotient.mk (Ideal.span {y}) s =
      Ideal.Quotient.mk (Ideal.span {y}) (s - y * s') := by
    rw [eq_comm, Ideal.Quotient.eq]
    have hsub : s - y * s' - s = -s' * y := by ring
    rw [hsub]
    exact Ideal.mem_span_singleton'.2 ⟨-s', rfl⟩
  rw [hmk]
  exact Ideal.mem_map_of_mem _ hker

/-- **The criterion is sharp** when `f y` is a non-zero-divisor on `T`: then the kernel of the
hyperplane section of `f` is generated by the image of `ker f` only if `f y` is a non-zero-divisor
on the cokernel of `f`. -/
theorem forall_mem_range_of_ker_quotientSpanHom_le (hreg : IsLeftRegular (f y))
    (h : RingHom.ker (quotientSpanHom f y) ≤
      Ideal.map (Ideal.Quotient.mk (Ideal.span {y})) (RingHom.ker f)) :
    ∀ t : T, f y * t ∈ Set.range f → t ∈ Set.range f := by
  intro t ht
  obtain ⟨s, hs⟩ := ht
  have hmem : Ideal.Quotient.mk (Ideal.span {y}) s ∈ RingHom.ker (quotientSpanHom f y) := by
    rw [mem_ker_quotientSpanHom_iff]
    refine Ideal.mem_span_singleton'.2 ⟨t, ?_⟩
    rw [mul_comm]
    exact hs.symm
  obtain ⟨u, hu, huv⟩ :=
    (Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective).1 (h hmem)
  rw [Ideal.Quotient.eq] at huv
  obtain ⟨w, hw⟩ := Ideal.mem_span_singleton'.1 huv
  have hsu : s = u - w * y := by
    rw [hw]
    ring
  have hgoal : f y * f (-w) = f y * t := by
    rw [map_neg, ← hs, hsu, map_sub, map_mul, RingHom.mem_ker.1 hu]
    ring
  exact ⟨-w, hreg hgoal⟩

end KernelBaseChange

/-! ## The resolved cone of a relative obstruction datum along the hyperplane -/

section ResolvedCone

open RelativeVirtualClassBaseChange RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

/-- **The equation of the hyperplane `y₀ = 0` on the bundle `E₀`**: the image of `y₀` under
`R → Base I → Sym_{Base I}(E⁰)`. -/
noncomputable abbrev symHyperplaneCoord {k : Type u} [CommRing k] {σ τ' : Type u}
    (I : Ideal (MvPolynomial (σ ⊕ Option τ') k)) (E : LinearTwoTermComplex (Base I)) :
    SymmetricAlgebra (Base I) E.degreeZero :=
  algebraMap (Base I) (SymmetricAlgebra (Base I) E.degreeZero)
    (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))

/-- **The resolved cone of a relative obstruction datum meets the hyperplane `y₀ = 0` in the cone
cut out by the image of its ideal**, provided `y₀` is a non-zero-divisor on the cokernel of the
coordinate-ring map `Sym(E⁰) → gr_I(R) ⊗ Sym(E₁)` of the resolved cone.

This is the honest form of the resolved-cone half of issue #75: the transversality hypothesis
`htrans` is *not* implied by `RegularOnPowers I y₀` — the module docstring records a
counterexample with `I` generated by polynomials not involving `y₀` — and
`forall_mem_range_of_ker_quotientSpanHom_le` shows it is also necessary whenever `y₀` is a
non-zero-divisor on `gr_I(R) ⊗ Sym(E₁)`.  The inclusion `⊇` holds unconditionally
(`map_ker_le_ker_quotientSpanHom`). -/
theorem ker_quotientSpanHom_relProductMap {k : Type u} [CommRing k] {σ τ' : Type u}
    {I : Ideal (MvPolynomial (σ ⊕ Option τ') k)}
    {E : LinearTwoTermComplex (Base I)}
    (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))
    (htrans : ∀ t : relProductRing φ,
      (relProductMap φ).toRingHom (symHyperplaneCoord I E) * t ∈
          Set.range (relProductMap φ).toRingHom →
        t ∈ Set.range (relProductMap φ).toRingHom) :
    RingHom.ker (quotientSpanHom (relProductMap φ).toRingHom (symHyperplaneCoord I E)) =
      Ideal.map (Ideal.Quotient.mk (Ideal.span {symHyperplaneCoord I E})) (ideal' φ) :=
  ker_quotientSpanHom_eq_map _ _ htrans

end ResolvedCone

/-! ## The base change of the associated graded ring as a tensor product -/

section Tensor

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex AffineNormalCone
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open ConeTranslation (Gr)
open scoped TensorProduct

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))

/-- **The ideal of the hyperplane `y₀ = 0` in the coordinate ring `Base I` of `X`.** -/
noncomputable abbrev baseHyperplaneIdeal : Ideal (Base I) :=
  Ideal.span {Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))}

theorem map_baseHyperplaneIdeal :
    Ideal.map (algebraMap (Base I) (Gr I)) (baseHyperplaneIdeal I) =
      Ideal.span {grHyperplaneCoord I} := by
  rw [Ideal.map_span, Set.image_singleton]

/-- `Base I → Base J` is surjective: it is `ρ` followed by a quotient map. -/
theorem surjective_algebraMap_base :
    Function.Surjective (algebraMap (Base I) (Base (reindexIdeal I))) := by
  intro z
  obtain ⟨r', rfl⟩ := Ideal.Quotient.mk_surjective z
  obtain ⟨r, rfl⟩ := surjective_reindexAlgHom r'
  exact ⟨Ideal.Quotient.mk I r, algebraMap_reindex_mk I r⟩

/-- **The kernel of `Base I → Base J` is the ideal of the hyperplane**: this is the `n = 1` case of
`mem_sup_span_of_reindexAlgHom_mem_pow`, i.e. `X' = X ×_Y Y'` is the hyperplane section of `X`. -/
theorem ker_algebraMap_base :
    RingHom.ker (algebraMap (Base I) (Base (reindexIdeal I))) = baseHyperplaneIdeal I := by
  refine le_antisymm ?_ ?_
  · intro z hz
    obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective z
    rw [RingHom.mem_ker, algebraMap_reindex_mk, Ideal.Quotient.eq_zero_iff_mem] at hz
    have h1 : reindexAlgHom r ∈ reindexIdeal I ^ 1 := by
      rwa [pow_one]
    have h2 := mem_sup_span_of_reindexAlgHom_mem_pow I h1
    rw [pow_one] at h2
    obtain ⟨u, hu, v, hv, huv⟩ := Submodule.mem_sup.1 h2
    rw [← huv, map_add, Ideal.Quotient.eq_zero_iff_mem.2 hu, zero_add]
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.1 hv
    rw [map_mul]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker,
      algebraMap_reindex_mk, reindexAlgHom_hyperplaneCoord]
    exact map_zero _

/-- **The coordinate ring of `X' = X ×_Y Y'` is the quotient of that of `X` by the hyperplane**:
`Base J ≅ Base I ⧸ (y₀)`, as `Base I`-algebras. -/
noncomputable def baseQuotEquiv :
    (Base I ⧸ baseHyperplaneIdeal I) ≃ₐ[Base I] Base (reindexIdeal I) :=
  AlgEquiv.ofRingEquiv (f := (Ideal.quotEquivOfEq (ker_algebraMap_base I).symm).trans
      (RingHom.quotientKerEquivOfSurjective (surjective_algebraMap_base I)))
    fun x => by
      rw [Ideal.Quotient.algebraMap_eq, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk,
        RingHom.quotientKerEquivOfSurjective_apply_mk]

/-- **The associated graded ring base-changes along the coordinate hyperplane**:
`gr_J(R') ≅ Base J ⊗_{Base I} gr_I(R)`, when `y₀` is a non-zero-divisor on every `R ⧸ Iⁿ`.  This is
the statement that the normal cone of `X' ⊆ 𝔸^σ × Y'` is the base change along `Y' ↪ Y` of the
normal cone of `X ⊆ 𝔸^σ × Y`, i.e. the Tor-independence needed by issue #75. -/
noncomputable def grReindexTensorEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    Base (reindexIdeal I) ⊗[Base I] Gr I ≃+* Gr (reindexIdeal I) :=
  ((Algebra.TensorProduct.congr (baseQuotEquiv I).symm
        (AlgEquiv.refl (R := Base I) (A₁ := Gr I))).toRingEquiv.trans
      (Algebra.TensorProduct.quotIdealMapEquivQuotTensor (Gr I)
        (baseHyperplaneIdeal I)).symm.toRingEquiv).trans
    ((Ideal.quotEquivOfEq (map_baseHyperplaneIdeal I)).trans (grReindexQuotEquiv I h))

@[simp]
theorem grReindexTensorEquiv_one_tmul
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) (z : Gr I) :
    grReindexTensorEquiv I h ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] z) = grReindexHom I z := by
  have h1 : (Algebra.TensorProduct.congr (baseQuotEquiv I).symm
        (AlgEquiv.refl (R := Base I) (A₁ := Gr I)))
        ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] z) =
      (1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] z := by
    rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul, map_one]
    rfl
  have h2 : (Algebra.TensorProduct.quotIdealMapEquivQuotTensor (Gr I)
        (baseHyperplaneIdeal I)).symm
        ((1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] z) =
      Ideal.Quotient.mk _ z := by
    rw [AlgEquiv.symm_apply_eq]
    exact (Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk (Gr I)
      (baseHyperplaneIdeal I) z).symm
  rw [grReindexTensorEquiv, RingEquiv.trans_apply, RingEquiv.trans_apply,
    RingEquiv.trans_apply]
  simp only [AlgEquiv.coe_ringEquiv]
  rw [h1, h2, Ideal.quotEquivOfEq_mk, grReindexQuotEquiv_mk]

/-- The image of `r ∈ Base I` in `Base J` pulls back to its class in `Base I ⧸ (y₀)`. -/
theorem baseQuotEquiv_mk (r : Base I) :
    baseQuotEquiv I (Ideal.Quotient.mk (baseHyperplaneIdeal I) r) =
      algebraMap (Base I) (Base (reindexIdeal I)) r := by
  have h := (baseQuotEquiv I).commutes r
  rwa [Ideal.Quotient.algebraMap_eq] at h

/-- **The base change of the associated graded ring is an isomorphism of `Base J`-algebras**, so
that `gr_J(R') ≅ Base J ⊗_{Base I} gr_I(R)` as algebras over the coordinate ring of `X'`. -/
noncomputable def grReindexTensorAlgEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    Base (reindexIdeal I) ⊗[Base I] Gr I ≃ₐ[Base (reindexIdeal I)] Gr (reindexIdeal I) :=
  AlgEquiv.ofRingEquiv (f := grReindexTensorEquiv I h) fun b => by
    obtain ⟨r, rfl⟩ := surjective_algebraMap_base I b
    have hleft : algebraMap (Base (reindexIdeal I))
        (Base (reindexIdeal I) ⊗[Base I] Gr I)
          (algebraMap (Base I) (Base (reindexIdeal I)) r) =
        (algebraMap (Base I) (Base (reindexIdeal I)) r) ⊗ₜ[Base I] (1 : Gr I) := rfl
    have hcongr : (Algebra.TensorProduct.congr (baseQuotEquiv I).symm
          (AlgEquiv.refl (R := Base I) (A₁ := Gr I)))
          ((algebraMap (Base I) (Base (reindexIdeal I)) r) ⊗ₜ[Base I] (1 : Gr I)) =
        (Ideal.Quotient.mk (baseHyperplaneIdeal I) r) ⊗ₜ[Base I] (1 : Gr I) := by
      have hb : (baseQuotEquiv I).symm (algebraMap (Base I) (Base (reindexIdeal I)) r) =
          Ideal.Quotient.mk (baseHyperplaneIdeal I) r := by
        rw [AlgEquiv.symm_apply_eq, baseQuotEquiv_mk]
      rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul, map_one,
        AlgEquiv.coe_toAlgHom, hb]
    have htmul : (Ideal.Quotient.mk (baseHyperplaneIdeal I) r) ⊗ₜ[Base I] (1 : Gr I) =
        (1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] (algebraMap (Base I) (Gr I) r) := by
      have h1 : (Ideal.Quotient.mk (baseHyperplaneIdeal I) r) =
          r • (1 : Base I ⧸ baseHyperplaneIdeal I) := by
        rw [Algebra.smul_def, mul_one, Ideal.Quotient.algebraMap_eq]
      have h2 : (algebraMap (Base I) (Gr I) r) = r • (1 : Gr I) := by
        rw [Algebra.smul_def, mul_one]
      rw [h1, h2, TensorProduct.smul_tmul]
    have hsymm : (Algebra.TensorProduct.quotIdealMapEquivQuotTensor (Gr I)
          (baseHyperplaneIdeal I)).symm
          ((1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] (algebraMap (Base I) (Gr I) r)) =
        Ideal.Quotient.mk _ (algebraMap (Base I) (Gr I) r) := by
      rw [AlgEquiv.symm_apply_eq]
      exact (Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk (Gr I)
        (baseHyperplaneIdeal I) (algebraMap (Base I) (Gr I) r)).symm
    rw [hleft, grReindexTensorEquiv, RingEquiv.trans_apply, RingEquiv.trans_apply,
      RingEquiv.trans_apply]
    simp only [AlgEquiv.coe_ringEquiv]
    rw [hcongr, htmul, hsymm, Ideal.quotEquivOfEq_mk, grReindexQuotEquiv_mk,
      grReindexHom_algebraMap]

end Tensor

/-! ## Sharpness: the transversality hypothesis cannot be dropped -/

section Sharpness

/-- **The substitution `u ↦ 2u` of `ℤ[u]`**: an injective ring map whose cokernel has
`2`-torsion, although `2` is a non-zero-divisor on both source and target. -/
noncomputable def doubleSubst : Polynomial ℤ →+* Polynomial ℤ :=
  (Polynomial.aeval (Polynomial.C 2 * Polynomial.X : Polynomial ℤ)).toRingHom

theorem doubleSubst_apply (p : Polynomial ℤ) :
    doubleSubst p = p.comp (Polynomial.C 2 * Polynomial.X) :=
  Polynomial.comp_eq_aeval.symm

theorem doubleSubst_X : doubleSubst Polynomial.X = Polynomial.C 2 * Polynomial.X := by
  rw [doubleSubst_apply, Polynomial.X_comp]

theorem C_two_eq_two : (Polynomial.C (2 : ℤ)) = 2 :=
  map_ofNat Polynomial.C 2

/-- The substitution `u ↦ 2u` is injective. -/
theorem ker_doubleSubst : RingHom.ker doubleSubst = ⊥ := by
  rw [RingHom.ker_eq_bot_iff_eq_zero]
  intro p hp
  rw [doubleSubst_apply, Polynomial.comp_eq_zero_iff] at hp
  rcases hp with hp | ⟨_, hq⟩
  · exact hp
  · exfalso
    have hc : (Polynomial.C (2 : ℤ) * Polynomial.X).coeff 0 = 0 := by
      simp
    rw [hc, map_zero] at hq
    have h1 : (Polynomial.C (2 : ℤ) * Polynomial.X).coeff 1 = 2 := by
      simp
    rw [hq] at h1
    simp at h1

/-- **`u` is not in the image of the substitution**, although `2u` is: the cokernel of
`doubleSubst` has `2`-torsion.  The proof compares leading coefficients. -/
theorem not_mem_range_doubleSubst : Polynomial.X ∉ Set.range doubleSubst := by
  rintro ⟨p, hp⟩
  rw [doubleSubst_apply] at hp
  have hq : (Polynomial.C (2 : ℤ) * Polynomial.X).natDegree = 1 :=
    Polynomial.natDegree_C_mul_X 2 two_ne_zero
  have hdeg : p.natDegree = 1 := by
    have h1 : (p.comp (Polynomial.C (2 : ℤ) * Polynomial.X)).natDegree = 1 := by
      rw [hp, Polynomial.natDegree_X]
    rwa [Polynomial.natDegree_comp, hq, mul_one] at h1
  have hlead : p.leadingCoeff * 2 ^ p.natDegree = 1 := by
    have h2 := Polynomial.leadingCoeff_comp (p := p)
      (q := Polynomial.C (2 : ℤ) * Polynomial.X) (by rw [hq]; exact one_ne_zero)
    rw [hp, Polynomial.leadingCoeff_X, Polynomial.leadingCoeff_C_mul_X] at h2
    exact h2.symm
  rw [hdeg, pow_one] at hlead
  omega

/-- **The transversality hypothesis of `ker_quotientSpanHom_eq_map` cannot be dropped.**

For the substitution `u ↦ 2u` of `ℤ[u]` and `y = 2`: `2` is a non-zero-divisor on source and
target, the substitution is injective, yet the kernel of the induced map
`ℤ[u] ⧸ (2) → ℤ[u] ⧸ (2)` contains the class of `u`, so it is *not* generated by the image of the
kernel of the substitution.  This is the abstract shadow of the counterexample to the
resolved-cone ideal identity described in the module docstring: there `2` is replaced by `y₀` and
`u ↦ 2u` by the coordinate-ring map `Sym(E⁰) → gr_I(R)`, `u ↦ y₀ T`. -/
theorem ker_quotientSpanHom_doubleSubst_ne_map :
    RingHom.ker (quotientSpanHom doubleSubst 2) ≠
      Ideal.map (Ideal.Quotient.mk (Ideal.span {(2 : Polynomial ℤ)}))
        (RingHom.ker doubleSubst) := by
  intro heq
  have hmem : Ideal.Quotient.mk (Ideal.span {(2 : Polynomial ℤ)}) Polynomial.X ∈
      RingHom.ker (quotientSpanHom doubleSubst 2) := by
    rw [mem_ker_quotientSpanHom_iff]
    refine Ideal.mem_span_singleton'.2 ⟨Polynomial.X, ?_⟩
    have h2 : doubleSubst 2 = 2 := map_ofNat doubleSubst 2
    have hx : doubleSubst Polynomial.X = 2 * Polynomial.X := by
      rw [doubleSubst_X, C_two_eq_two]
    rw [h2, hx, mul_comm]
  rw [heq, ker_doubleSubst, Ideal.map_bot] at hmem
  have hX : Polynomial.X ∈ Ideal.span {(2 : Polynomial ℤ)} :=
    Ideal.Quotient.eq_zero_iff_mem.1 (Ideal.mem_bot.1 hmem)
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 hX
  have h1 : (c * 2).coeff 1 = (Polynomial.X : Polynomial ℤ).coeff 1 := by
    rw [hc]
  rw [Polynomial.coeff_X_one, ← C_two_eq_two, Polynomial.coeff_mul_C] at h1
  omega

end Sharpness

/-! ## The bundle `E₀` along the hyperplane -/

section SymQuot

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open scoped TensorProduct

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable (M : Type u) [AddCommGroup M] [Module (Base I) M]

/-- **The ideal of the hyperplane `y₀ = 0` in the coordinate ring `Sym_{Base I}(M)`** of a bundle
over `X`. -/
noncomputable abbrev symHyperplaneSpan : Ideal (SymmetricAlgebra (Base I) M) :=
  Ideal.span {algebraMap (Base I) (SymmetricAlgebra (Base I) M)
    (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))}

theorem map_baseHyperplaneIdeal_sym :
    Ideal.map (algebraMap (Base I) (SymmetricAlgebra (Base I) M)) (baseHyperplaneIdeal I) =
      symHyperplaneSpan I M := by
  rw [Ideal.map_span, Set.image_singleton]

/-- **A bundle over `X` base-changes along the hyperplane**: the coordinate ring of the
restriction of the bundle `Spec Sym_{Base I}(M)` to `X' = X ×_Y Y'` is the coordinate ring of the
base-changed bundle, `Sym_{Base I}(M) ⧸ (y₀) ≅ Sym_{Base J}(Base J ⊗_{Base I} M)`.  Unlike the
associated graded ring, this needs no hypothesis: a symmetric algebra is a *flat* (indeed free)
construction. -/
noncomputable def symQuotEquiv :
    (SymmetricAlgebra (Base I) M ⧸ symHyperplaneSpan I M) ≃+*
      SymmetricAlgebra (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] M) :=
  ((Ideal.quotEquivOfEq (map_baseHyperplaneIdeal_sym I M).symm).trans
      (Algebra.TensorProduct.quotIdealMapEquivQuotTensor (SymmetricAlgebra (Base I) M)
        (baseHyperplaneIdeal I)).toRingEquiv).trans
    ((Algebra.TensorProduct.congr (baseQuotEquiv I)
        (AlgEquiv.refl (R := Base I) (A₁ := SymmetricAlgebra (Base I) M))).toRingEquiv.trans
      (scalarExtensionEquiv (Base I) (Base (reindexIdeal I)) M).toRingEquiv)

@[simp]
theorem symQuotEquiv_mk_ι (x : M) :
    symQuotEquiv I M (Ideal.Quotient.mk _ (SymmetricAlgebra.ι (Base I) M x)) =
      SymmetricAlgebra.ι (Base (reindexIdeal I)) (Base (reindexIdeal I) ⊗[Base I] M)
        (1 ⊗ₜ[Base I] x) := by
  have hcongr : (Algebra.TensorProduct.congr (baseQuotEquiv I)
        (AlgEquiv.refl (R := Base I) (A₁ := SymmetricAlgebra (Base I) M)))
        ((1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] SymmetricAlgebra.ι (Base I) M x) =
      (1 : Base (reindexIdeal I)) ⊗ₜ[Base I] SymmetricAlgebra.ι (Base I) M x := by
    rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul, map_one]
    rfl
  rw [symQuotEquiv, RingEquiv.trans_apply, RingEquiv.trans_apply, RingEquiv.trans_apply,
    Ideal.quotEquivOfEq_mk]
  simp only [AlgEquiv.coe_ringEquiv]
  rw [Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk, hcongr,
    scalarExtensionEquiv_one_tmul, scalarExtensionMap_ι]

end SymQuot

/-! ## The coordinate ring of `C ×_X E₀` along the hyperplane -/

section RelProductQuot

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open GradedCone.SymmetricFunctoriality
open ConeTranslation (Gr)
open scoped TensorProduct

-- Tensor products of the associated graded ring with a symmetric algebra need a deeper instance
-- search, exactly as in `RelativeAbsolute.lean`.
set_option maxSynthPendingDepth 5

variable {k : Type u} [CommRing k] {σ τ' : Type u} [Fintype σ]
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))
variable {E : LinearTwoTermComplex (Base I)}
variable (φ : LinearTwoTermComplex.Hom E (relConormalComplex I))

/-- **The ideal of the hyperplane `y₀ = 0` in the coordinate ring `gr_I(R) ⊗ Sym(E₁)`** of
`C ×_X E₀`. -/
noncomputable abbrev relProductHyperplaneSpan : Ideal (relProductRing φ) :=
  Ideal.span {algebraMap (Base I) (relProductRing φ)
    (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ')))}

omit [Fintype σ] in
theorem map_baseHyperplaneIdeal_relProduct :
    Ideal.map (algebraMap (Base I) (relProductRing φ)) (baseHyperplaneIdeal I) =
      relProductHyperplaneSpan I φ := by
  rw [Ideal.map_span, Set.image_singleton]

/-- **The coordinate ring of `C ×_X E₀` base-changes along the hyperplane**: given the
Tor-independence of the normal cone (`RegularOnPowers I y₀`), the restriction of `C ×_X E₀` to the
hyperplane is the corresponding product for the base-changed datum `reindexHom I φ`.  The proof
composes the flat base change of the symmetric algebra
(`GradedCone.SymmetricFunctoriality.scalarExtensionEquiv`) with `grReindexTensorAlgEquiv` and the
standard tensor manipulations `Algebra.TensorProduct.assoc` and
`Algebra.TensorProduct.cancelBaseChange`. -/
noncomputable def relProductQuotEquiv
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :
    (relProductRing φ ⧸ relProductHyperplaneSpan I φ) ≃+* relProductRing (reindexHom I φ) :=
  ((Ideal.quotEquivOfEq (map_baseHyperplaneIdeal_relProduct I φ).symm).trans
      (Algebra.TensorProduct.quotIdealMapEquivQuotTensor (relProductRing φ)
        (baseHyperplaneIdeal I)).toRingEquiv).trans <|
    ((Algebra.TensorProduct.congr (baseQuotEquiv I)
        (AlgEquiv.refl (R := Base I) (A₁ := relProductRing φ))).toRingEquiv).trans <|
      ((Algebra.TensorProduct.assoc (R := Base I) (S := Base I)
          (T := Base (reindexIdeal I)) (A := Base (reindexIdeal I)) (C := Gr I)
          (D := SymmetricAlgebra (Base I) E.degreeOne)).symm.toRingEquiv).trans <|
        ((Algebra.TensorProduct.cancelBaseChange (R := Base I) (S := Base (reindexIdeal I))
            (T := Base (reindexIdeal I))
            (A := Base (reindexIdeal I) ⊗[Base I] Gr I)
            (B := SymmetricAlgebra (Base I) E.degreeOne)).symm.toRingEquiv).trans
          (Algebra.TensorProduct.congr (grReindexTensorAlgEquiv I h)
            (scalarExtensionEquiv (Base I) (Base (reindexIdeal I))
              E.degreeOne)).toRingEquiv

omit [Fintype σ] in
/-- The coordinate-ring map of the resolved cone sends the hyperplane equation on `E₀` to the
hyperplane equation on `C ×_X E₀`, because it is a `Base I`-algebra map. -/
theorem relProductMap_symHyperplaneCoord :
    (relProductMap φ).toRingHom (symHyperplaneCoord I E) =
      algebraMap (Base I) (relProductRing φ)
        (Ideal.Quotient.mk I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) :=
  AlgHom.commutes _ _

omit [Fintype σ] in
theorem span_relProductMap_symHyperplaneCoord :
    Ideal.span {(relProductMap φ).toRingHom (symHyperplaneCoord I E)} =
      relProductHyperplaneSpan I φ := by
  rw [relProductMap_symHyperplaneCoord]

set_option maxHeartbeats 1000000 in
-- Unfolding the five-step composite of `relProductQuotEquiv` on a tensor generator forces
-- definitional unfolding of the quotient of `relProductRing`, which exceeds the default budget.
@[simp]
theorem relProductQuotEquiv_mk_tmul
    (h : RegularOnPowers I (hyperplaneCoord (k := k) (σ := σ) (τ' := τ'))) (z : Gr I)
    (s : SymmetricAlgebra (Base I) E.degreeOne) :
    relProductQuotEquiv I φ h (Ideal.Quotient.mk _ (z ⊗ₜ[Base I] s)) =
      grReindexHom I z ⊗ₜ[Base (reindexIdeal I)]
        scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeOne s := by
  have hcongr : (Algebra.TensorProduct.congr (baseQuotEquiv I)
        (AlgEquiv.refl (R := Base I) (A₁ := relProductRing φ)))
        ((1 : Base I ⧸ baseHyperplaneIdeal I) ⊗ₜ[Base I] (z ⊗ₜ[Base I] s)) =
      (1 : Base (reindexIdeal I)) ⊗ₜ[Base I] (z ⊗ₜ[Base I] s) := by
    rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul, map_one]
    rfl
  have hcancel : (Algebra.TensorProduct.cancelBaseChange (R := Base I)
        (S := Base (reindexIdeal I)) (T := Base (reindexIdeal I))
        (A := Base (reindexIdeal I) ⊗[Base I] Gr I)
        (B := SymmetricAlgebra (Base I) E.degreeOne)).symm
        (((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] z) ⊗ₜ[Base I] s) =
      ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] z) ⊗ₜ[Base (reindexIdeal I)]
        ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] s) := by
    rw [AlgEquiv.symm_apply_eq, Algebra.TensorProduct.cancelBaseChange_tmul, one_smul]
  rw [relProductQuotEquiv, RingEquiv.trans_apply, RingEquiv.trans_apply, RingEquiv.trans_apply,
    RingEquiv.trans_apply, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk]
  simp only [AlgEquiv.coe_ringEquiv]
  rw [Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk, hcongr,
    Algebra.TensorProduct.assoc_symm_tmul, hcancel, Algebra.TensorProduct.congr_apply,
    Algebra.TensorProduct.map_tmul]
  rw [AlgEquiv.coe_toAlgHom, AlgEquiv.coe_toAlgHom, scalarExtensionEquiv_one_tmul]
  refine congrArg (fun w => w ⊗ₜ[Base (reindexIdeal I)]
    scalarExtensionMap (Base I) (Base (reindexIdeal I)) E.degreeOne s) ?_
  exact grReindexTensorEquiv_one_tmul I h z

end RelProductQuot

/-! ## The degree-zero component of the reindexed datum on generators -/

section DegreeZero

open RelativeVirtualClassBaseChange RelativeHyperplaneReindex RelativeAbsolute
open RelativeHyperplaneObstruction
open GromovWitten.AlgebraicGeometry.NormalConeAction (Base)
open scoped TensorProduct

variable {k : Type u} [CommRing k] {σ τ' : Type u}
variable (I : Ideal (MvPolynomial (σ ⊕ Option τ') k))

/-- **The two conormal comparison maps `I/I² → J/J²` agree**: enlarging `I` to `I' = I + (y₀)` and
then specialising `y₀ ↦ 0` is the same as applying `ρ` directly. -/
theorem reindexCotangentMap_hyperplaneCotangentMapAux (m : I.Cotangent) :
    reindexCotangentMap I (hyperplaneCotangentMapAux I m) = idealCotangentReindex I m := by
  obtain ⟨a, rfl⟩ := Ideal.toCotangent_surjective I m
  rw [hyperplaneCotangentMapAux, Ideal.mapCotangent_toCotangent,
    reindexCotangentMap_toCotangent, idealCotangentReindex_toCotangent]
  rfl

variable [Fintype σ] {E : LinearTwoTermComplex (Base I)}

/-- **The degree-zero component of the reindexed datum, on the generators `1 ⊗ x`**: it is the
specialisation `y₀ ↦ 0` of `φ.degreeZero`.  This is the compatibility needed to compare the
coordinate-ring maps of the resolved cones of `φ` and of `reindexHom I φ`. -/
theorem reindexHom_degreeZero_one_tmul
    (φ : LinearTwoTermComplex.Hom E (relConormalComplex I)) (x : E.degreeZero) :
    (reindexHom I φ).degreeZero ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] x) =
      idealCotangentReindex I (φ.degreeZero x) := by
  have hsymm : (tensorReindexEquiv I E.degreeZero).symm
      ((1 : Base (reindexIdeal I)) ⊗ₜ[Base I] x) =
      (1 : Base (hyperplaneIdeal I)) ⊗ₜ[Base I] x := by
    rw [LinearEquiv.symm_apply_eq, tensorReindexEquiv_tmul, map_one]
  have h1 : (hyperplaneHom I φ).degreeZero ((1 : Base (hyperplaneIdeal I)) ⊗ₜ[Base I] x) =
      (hyperplaneComparisonHom I).degreeZero
        ((1 : Base (hyperplaneIdeal I)) ⊗ₜ[Base I] φ.degreeZero x) := by
    rw [hyperplaneHom_eq_comp]
    change (hyperplaneComparisonHom I).degreeZero
      ((φ.baseChange (Base (hyperplaneIdeal I))).degreeZero
        ((1 : Base (hyperplaneIdeal I)) ⊗ₜ[Base I] x)) = _
    rw [LinearTwoTermComplex.Hom.baseChange_degreeZero, LinearMap.baseChange_tmul]
  rw [reindexHom_degreeZero_apply, hsymm, h1, hyperplaneComparison_degreeZero_tmul, one_smul,
    hyperplaneCotangentReindexEquiv_mk, reindexCotangentMap_hyperplaneCotangentMapAux]

end DegreeZero

end GromovWitten.AlgebraicGeometry.VirtualFundamentalClass.RelativeHyperplaneCone
