/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude Opus 5
-/

import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import GromovWitten.AlgebraicGeometry.Curves.StableReduction.SpecialFibreStalk

/-!
# The special fibre is the closed subscheme cut out by a uniformiser

Let `M` be a model of a curve over a discrete valuation ring `R` with uniformiser `π`.  The
special fibre `F` of `M` is defined in `Fibers.lean` as the base change of `M.total` along
`Spec (R ⧸ m) ⟶ Spec R`.  This file identifies it with the closed subscheme of `M.total` cut out
by the pullback of `π`, and deduces that the stalks of `F` are the quotients
`𝒪_{M,x} ⧸ (germ π)`.

## Main results

* `principalIdealSheaf`: the ideal sheaf `U ↦ (s|_U)` generated by a global section `s`;
  `appTop_eq_zero_of_forall_affine` is the local criterion for the vanishing of a section.
* `ker_eq_map_of_isLocalization_atPrime`: the kernel of a localisation of a surjective ring map
  is generated by the image of the kernel; `ker_stalkMap_of_isClosedImmersion` is the resulting
  computation of the kernel of the stalk map of a closed immersion.
* `ker_specialFiberι`: the kernel ideal sheaf of the closed immersion `specialFiberι` is the
  principal ideal sheaf generated by the pullback of a uniformiser, and
  `specialFiberSchemeIsoSubscheme` identifies the special fibre with the corresponding closed
  subscheme of the total space.
* `ker_specialFiberι_ideal_eq_span`: on an affine open `U`, the kernel of
  `Γ(M.total, U) ⟶ Γ(F, ι⁻¹U)` is the ideal generated by the restriction of `π`.
* `ker_stalkMap_specialFiberι`: the kernel of the stalk map
  `𝒪_{M,x} ⟶ 𝒪_{F,x'}` is the principal ideal generated by `baseElementGerm x π`.
* `specialFiberStalkQuotientHom_injective` and `specialFiberStalkIso`: the ring isomorphism
  `𝒪_{M,x} ⧸ (germ π) ≃+* 𝒪_{F,x'}`.
* `ringKrullDim_stalk_specialFiberScheme_eq`,
  `ringKrullDim_stalk_specialFiberScheme_eq_one`,
  `ringKrullDim_stalk_specialFiberScheme_add_one`: the Krull dimension of the stalks of the
  special fibre; the special fibre drops the dimension by exactly one at a closed point.
* `forall_ringKrullDim_stalk_le_one_iff`,
  `topologicalKrullDim_specialFiberScheme_le_one_iff`: the three forms of the hypothesis "the
  special fibre is at most one-dimensional" all agree, namely
  `topologicalKrullDim M.specialFiberScheme ≤ 1`, the pointwise statement that all local rings of
  the special fibre have Krull dimension at most one, and the combinatorial hypothesis `hgen` of
  `SpecialFibreStalk.lean`.  The two new implications are
  `exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one` (which uses the stalk isomorphism)
  and `topologicalKrullDim_specialFiberScheme_le_one`.  All the results of
  `SpecialFibreStalk.lean` depending on `hgen` are therefore restated here with the pointwise
  hypothesis (`ringKrullDim_stalk_eq_two_of_stalk_le_one`,
  `krullDimLE_two_stalk_of_stalk_le_one`, `finite_componentCloseds_inter_of_stalk_le_one`,
  `componentIntersection_ne_top_of_stalk_le_one`,
  `coe_componentIntersectionNat_of_stalk_le_one`).

## Implementation notes

The identification of the special fibre with the subscheme cut out by `π` is obtained from the
universal property of the pullback rather than from an affine base-change computation: the
closed subscheme `Z` cut out by the principal ideal sheaf of `π` carries a morphism to
`Spec (R ⧸ m)` because `π` restricts to `0` on `Z` and `m = (π)`, hence a morphism `Z ⟶ F` over
`M.total`.  This gives `ker (specialFiberι) ≤ (π)`, and the reverse inequality is the (easy)
vanishing of `π` on the special fibre.

With the stalk isomorphism in hand the one-dimensionality hypothesis on the special fibre can be
taken in its most natural form, namely that all local rings of the special fibre have Krull
dimension at most one; this is *equivalent* both to the combinatorial hypothesis `hgen` of
`SpecialFibreStalk.lean` (`forall_ringKrullDim_stalk_le_one_iff`) and to
`topologicalKrullDim M.specialFiberScheme ≤ 1`
(`topologicalKrullDim_specialFiberScheme_le_one_iff`).  The hypothesis `hnc` (no component of the
special fibre is a single point) is still needed for the *lower* bounds on dimensions and cannot be
removed: it fails for the special fibre `Spec (R ⧸ m)` of `Spec R` itself.
-/

open CategoryTheory Limits
open AlgebraicGeometry
open IsLocalRing

universe u

namespace GromovWitten.AlgebraicGeometry.Curves.StableReduction

noncomputable section

/-! ### A commutative algebra lemma on localisations of surjections -/

/-- **The kernel of a localised surjection.**  Let `φ : A →+* B` be surjective, let `q` be a
prime of `B` with contraction `p`, and let `ψ : S →+* T` be a ring map between localisations of
`A` at `p` and of `B` at `q` compatible with `φ`.  Then the kernel of `ψ` is generated by the
image of the kernel of `φ`. -/
theorem ker_eq_map_of_isLocalization_atPrime
    {A B S T : Type*} [CommRing A] [CommRing B] [CommRing S] [CommRing T]
    [Algebra A S] [Algebra B T] {p : Ideal A} [p.IsPrime] {q : Ideal B} [q.IsPrime]
    [IsLocalization.AtPrime S p] [IsLocalization.AtPrime T q]
    {φ : A →+* B} (hφ : Function.Surjective φ) (hpq : q.comap φ = p)
    {ψ : S →+* T} (hcomm : ∀ a : A, ψ (algebraMap A S a) = algebraMap B T (φ a)) :
    RingHom.ker ψ = (RingHom.ker φ).map (algebraMap A S) := by
  refine le_antisymm (fun s hs => ?_) (Ideal.map_le_iff_le_comap.mpr fun a ha => ?_)
  · obtain ⟨⟨a, u⟩, hau⟩ := IsLocalization.surj p.primeCompl s
    have ha0 : algebraMap B T (φ a) = 0 := by
      rw [← hcomm, ← hau, map_mul, RingHom.mem_ker.mp hs, zero_mul]
    obtain ⟨⟨v, hv⟩, hva⟩ := (IsLocalization.map_eq_zero_iff q.primeCompl T _).mp ha0
    obtain ⟨w, rfl⟩ := hφ v
    have hw : w ∈ p.primeCompl := fun hc => hv (Ideal.mem_comap.mp (hpq.ge hc))
    have hmem : algebraMap A S (w * a) ∈ (RingHom.ker φ).map (algebraMap A S) :=
      Ideal.mem_map_of_mem _ (by rw [RingHom.mem_ker, map_mul]; exact hva)
    rw [map_mul] at hmem
    have ha : algebraMap A S a ∈ (RingHom.ker φ).map (algebraMap A S) :=
      (Ideal.unit_mul_mem_iff_mem _ (IsLocalization.map_units S ⟨w, hw⟩)).mp hmem
    rw [← hau, mul_comm] at ha
    exact (Ideal.unit_mul_mem_iff_mem _ (IsLocalization.map_units S u)).mp ha
  · rw [Ideal.mem_comap, RingHom.mem_ker, hcomm, RingHom.mem_ker.mp ha, map_zero]

/-! ### The principal ideal sheaf generated by a global section -/

/-- The ideal sheaf whose value on an affine open `U` is generated by the restriction to `U` of a
fixed global section `s`: the ideal sheaf cutting out the zero scheme of `s`. -/
def principalIdealSheaf (X : Scheme.{u}) (s : Γ(X, ⊤)) : X.IdealSheafData where
  ideal U := Ideal.span {X.presheaf.map (homOfLE (le_top (a := U.1))).op s}
  map_ideal_basicOpen U f := by
    have h : (X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom
          ((X.presheaf.map (homOfLE (le_top (a := U.1))).op) s) =
        (X.presheaf.map (homOfLE (le_top (a := (X.affineBasicOpen f).1))).op) s := by
      rw [← CommRingCat.comp_apply, ← X.presheaf.map_comp]
      rfl
    rw [Ideal.map_span, Set.image_singleton, h]
    rfl

/-- The component of the principal ideal sheaf of `s` at an affine open. -/
@[simp]
theorem principalIdealSheaf_ideal (X : Scheme.{u}) (s : Γ(X, ⊤)) (U : X.affineOpens) :
    (principalIdealSheaf X s).ideal U =
      Ideal.span {X.presheaf.map (homOfLE (le_top (a := U.1))).op s} := rfl


/-! ### Vanishing of a global section on a scheme -/

/-- Naturality of the components of a morphism of schemes with respect to the restriction of a
global section to an open subset. -/
theorem app_map_le_top {X Y : Scheme.{u}} (f : X ⟶ Y) (U : Y.Opens) (s : Γ(Y, ⊤)) :
    f.app U (Y.presheaf.map (homOfLE (le_top (a := U))).op s) =
      X.presheaf.map (homOfLE (le_top (a := f ⁻¹ᵁ U))).op (f.appTop s) := by
  rw [← CommRingCat.comp_apply, ← CommRingCat.comp_apply, f.naturality]
  rfl

/-- If a global section is annihilated by `f.appTop`, then all its restrictions are annihilated by
the corresponding components of `f`. -/
theorem app_map_le_top_eq_zero {X Y : Scheme.{u}} (f : X ⟶ Y) (U : Y.Opens) {s : Γ(Y, ⊤)}
    (hs : f.appTop s = 0) :
    f.app U (Y.presheaf.map (homOfLE (le_top (a := U))).op s) = 0 := by
  rw [app_map_le_top, hs, map_zero]

/-- **Local criterion for the vanishing of a pulled back global section.**  If the restriction of
`s` to every affine open `U` of `Y` is annihilated by `f.app U`, then `s` is annihilated by
`f.appTop`. -/
theorem appTop_eq_zero_of_forall_affine {X Y : Scheme.{u}} (f : X ⟶ Y) {s : Γ(Y, ⊤)}
    (hs : ∀ U : Y.affineOpens,
      f.app U.1 (Y.presheaf.map (homOfLE (le_top (a := U.1))).op s) = 0) :
    f.appTop s = 0 := by
  refine X.IsSheaf.section_ext (U := Opposite.op ⊤) (s := f.appTop s) (t := 0) ?_
  intro x _
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
    Y.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ (f x)) isOpen_univ
  refine ⟨f ⁻¹ᵁ U, le_top, hxU, ?_⟩
  rw [map_zero, ← app_map_le_top]
  exact hs ⟨U, hU⟩


/-- An ideal sheaf generated by a global section that is annihilated by `f` is contained in the
kernel ideal sheaf of `f`. -/
theorem principalIdealSheaf_le_ker {X Y : Scheme.{u}} (f : X ⟶ Y) {s : Γ(Y, ⊤)}
    (hs : f.appTop s = 0) : principalIdealSheaf Y s ≤ f.ker := by
  refine Scheme.IdealSheafData.le_ofIdeals_iff.mpr (fun U => ?_)
  rw [principalIdealSheaf_ideal, Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
    RingHom.mem_ker]
  exact app_map_le_top_eq_zero f U.1 hs

/-- **A morphism to an affine scheme is the one induced by its map on global sections.** -/
theorem toSpecΓ_comp_Spec_map_appTop {W : Scheme.{u}} {A : CommRingCat.{u}} (g : W ⟶ Spec A) :
    W.toSpecΓ ≫ Spec.map ((Scheme.ΓSpecIso A).inv ≫ g.appTop) = g := by
  rw [Spec.map_comp, ← Category.assoc, ← Scheme.toSpecΓ_naturality, Category.assoc,
    toSpecΓ_SpecMap_ΓSpecIso_inv, Category.comp_id]


/-! ### The kernel of the stalk map of a closed immersion -/

/-- **The kernel of the stalk map of a closed immersion.**  If `U` is an affine open neighbourhood
of `f x`, then the kernel of the stalk map `𝒪_{Y, f x} ⟶ 𝒪_{X, x}` is generated by the image under
the germ map of the kernel of `f.app U`. -/
theorem ker_stalkMap_of_isClosedImmersion {X Y : Scheme.{u}} (f : X ⟶ Y) [IsClosedImmersion f]
    {U : Y.Opens} (hU : IsAffineOpen U) (x : X) (hx : f x ∈ U) :
    RingHom.ker (f.stalkMap x).hom =
      (RingHom.ker (f.app U).hom).map (Y.presheaf.germ U (f x) hx).hom := by
  have hV : IsAffineOpen (f ⁻¹ᵁ U) := hU.preimage f
  let _ := Y.presheaf.algebra_section_stalk (⟨f x, hx⟩ : U)
  let _ := X.presheaf.algebra_section_stalk (⟨x, hx⟩ : f ⁻¹ᵁ U)
  have h1 := hU.isLocalization_stalk (⟨f x, hx⟩ : U)
  have h2 := hV.isLocalization_stalk (⟨x, hx⟩ : f ⁻¹ᵁ U)
  have hpq : (hV.primeIdealOf ⟨x, hx⟩).asIdeal.comap (f.app U).hom =
      (hU.primeIdealOf ⟨f x, hx⟩).asIdeal := by
    have h0 := IsAffineOpen.comap_primeIdealOf_appLE U hU (f ⁻¹ᵁ U) hV le_rfl hx
    rw [Scheme.Hom.appLE_eq_app] at h0
    exact congrArg PrimeSpectrum.asIdeal h0
  exact ker_eq_map_of_isLocalization_atPrime
    (p := (hU.primeIdealOf ⟨f x, hx⟩).asIdeal) (q := (hV.primeIdealOf ⟨x, hx⟩).asIdeal)
    (f.app_surjective U hU) hpq
    (fun a => Scheme.Hom.germ_stalkMap_apply f U x hx a)


/-! ### The special fibre is the subscheme cut out by a uniformiser -/

variable {R K : Type u} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
variable [Field K] [Algebra R K] [IsFractionRing R K]
variable {C : Scheme.{u}} {toK : C ⟶ Spec (.of K)} {M : Model R K C toK}

/-- The ideal sheaf on the total space of a model generated by the pullback of an element of the
base ring.  For a uniformiser it cuts out the special fibre. -/
abbrev baseElementIdealSheaf (M : Model R K C toK) (r : R) : M.total.IdealSheafData :=
  principalIdealSheaf M.total (baseElementSection M r)

/-- The ideal sheaf generated by the pullback of an element of the maximal ideal of the base is
contained in the kernel ideal sheaf of the immersion of the special fibre. -/
theorem baseElementIdealSheaf_le_ker {π : R} (hπ : π ∈ maximalIdeal R) :
    baseElementIdealSheaf M π ≤ (specialFiberι R M.toBase).ker :=
  principalIdealSheaf_le_ker _ (appTop_specialFiberι_baseElementSection hπ)

/-- The pullback of `r` vanishes on the closed subscheme of the total space that it cuts out. -/
theorem appTop_subschemeι_baseElementSection (r : R) :
    (baseElementIdealSheaf M r).subschemeι.appTop (baseElementSection M r) = 0 := by
  refine appTop_eq_zero_of_forall_affine _ (fun U => ?_)
  have hmem : M.total.presheaf.map (homOfLE (le_top (a := U.1))).op (baseElementSection M r) ∈
      RingHom.ker ((baseElementIdealSheaf M r).subschemeι.app U.1).hom := by
    rw [Scheme.IdealSheafData.ker_subschemeι_app, principalIdealSheaf_ideal]
    exact Ideal.mem_span_singleton_self _
  exact hmem

/-- The ring map from the base ring to the global sections of the closed subscheme of the total
space cut out by the pullback of `r`. -/
def subschemeBaseRingHom (M : Model R K C toK) (r : R) :
    R →+* Γ((baseElementIdealSheaf M r).subscheme, ⊤) :=
  ((Scheme.ΓSpecIso (.of R)).inv ≫
    ((baseElementIdealSheaf M r).subschemeι ≫ M.toBase).appTop).hom

/-- The element `r` is annihilated by the structure map of the closed subscheme it cuts out. -/
theorem subschemeBaseRingHom_self (r : R) : subschemeBaseRingHom M r r = 0 := by
  have h : subschemeBaseRingHom M r r =
      (baseElementIdealSheaf M r).subschemeι.appTop (baseElementSection M r) := by
    change ((Scheme.ΓSpecIso (.of R)).inv ≫
      ((baseElementIdealSheaf M r).subschemeι ≫ M.toBase).appTop) r = _
    rw [Scheme.Hom.comp_appTop]
    rfl
  rw [h, appTop_subschemeι_baseElementSection]

/-- The kernel of the residue map of the base is contained in the kernel of the structure map of
the closed subscheme cut out by a uniformiser. -/
theorem ker_algebraMap_le_ker_subschemeBaseRingHom {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    RingHom.ker (algebraMap R (specialResidueField R)) ≤
      RingHom.ker (subschemeBaseRingHom M π) := by
  rw [Ideal.ker_algebraMap_residueField, hπ, Ideal.span_le]
  exact Set.singleton_subset_iff.mpr (RingHom.mem_ker.mpr (subschemeBaseRingHom_self π))

/-- The ring map from the residue field of the base to the global sections of the closed
subscheme cut out by a uniformiser, obtained by factoring the structure map. -/
def subschemeSpecialPointHom (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    specialResidueField R →+* Γ((baseElementIdealSheaf M π).subscheme, ⊤) :=
  RingHom.liftOfSurjective (algebraMap R (specialResidueField R))
    (Ideal.algebraMap_residueField_surjective _)
    ⟨subschemeBaseRingHom M π, ker_algebraMap_le_ker_subschemeBaseRingHom hπ⟩

/-- The factorisation defining `subschemeSpecialPointHom`. -/
theorem subschemeSpecialPointHom_comp (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (subschemeSpecialPointHom M hπ).comp (algebraMap R (specialResidueField R)) =
      subschemeBaseRingHom M π :=
  RingHom.liftOfRightInverse_comp _ _ _ _

/-- The morphism from the closed subscheme cut out by a uniformiser to the spectrum of the residue
field of the base: the uniformiser generates the maximal ideal, so the structure map of the
subscheme kills the maximal ideal. -/
def subschemeToSpecialPoint (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (baseElementIdealSheaf M π).subscheme ⟶ Spec (.of (specialResidueField R)) :=
  (baseElementIdealSheaf M π).subscheme.toSpecΓ ≫
    Spec.map (CommRingCat.ofHom (subschemeSpecialPointHom M hπ))

/-- **The closed subscheme cut out by a uniformiser lies over the closed point of the base.** -/
theorem subschemeι_toBase (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (baseElementIdealSheaf M π).subschemeι ≫ M.toBase =
      subschemeToSpecialPoint M hπ ≫ specialPointMap R := by
  have hring : CommRingCat.ofHom (algebraMap R (specialResidueField R)) ≫
      CommRingCat.ofHom (subschemeSpecialPointHom M hπ) =
      (Scheme.ΓSpecIso (.of R)).inv ≫
        ((baseElementIdealSheaf M π).subschemeι ≫ M.toBase).appTop := by
    rw [← CommRingCat.ofHom_comp, subschemeSpecialPointHom_comp]
    rfl
  calc (baseElementIdealSheaf M π).subschemeι ≫ M.toBase
      = (baseElementIdealSheaf M π).subscheme.toSpecΓ ≫
          Spec.map ((Scheme.ΓSpecIso (.of R)).inv ≫
            ((baseElementIdealSheaf M π).subschemeι ≫ M.toBase).appTop) :=
        (toSpecΓ_comp_Spec_map_appTop _).symm
    _ = subschemeToSpecialPoint M hπ ≫ specialPointMap R := by
        rw [subschemeToSpecialPoint, specialPointMap, Category.assoc, ← hring]
        congr 1
        exact Spec.map_comp _ _

/-- **The kernel ideal sheaf of the immersion of the special fibre is generated by the pullback of
a uniformiser**: the special fibre is the closed subscheme cut out by `π`. -/
theorem ker_specialFiberι (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (specialFiberι R M.toBase).ker = baseElementIdealSheaf M π := by
  refine le_antisymm ?_ (baseElementIdealSheaf_le_ker
    (by rw [hπ]; exact Ideal.mem_span_singleton_self π))
  have hcomp : (pullback.lift (baseElementIdealSheaf M π).subschemeι
      (subschemeToSpecialPoint M hπ) (subschemeι_toBase M hπ)) ≫ specialFiberι R M.toBase =
      (baseElementIdealSheaf M π).subschemeι := pullback.lift_fst _ _ _
  have h := Scheme.Hom.le_ker_comp (pullback.lift (baseElementIdealSheaf M π).subschemeι
    (subschemeToSpecialPoint M hπ) (subschemeι_toBase M hπ)) (specialFiberι R M.toBase)
  rwa [hcomp, Scheme.IdealSheafData.ker_subschemeι] at h

/-- **On an affine open `U` of the total space, the kernel of the restriction map to the special
fibre is the ideal generated by the uniformiser.** -/
theorem ker_specialFiberι_ideal_eq_span (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) (U : M.total.affineOpens) :
    RingHom.ker ((specialFiberι R M.toBase).app U.1).hom =
      Ideal.span {M.total.presheaf.map (homOfLE (le_top (a := U.1))).op
        (baseElementSection M π)} := by
  rw [← Scheme.Hom.ker_apply, ker_specialFiberι M hπ, principalIdealSheaf_ideal]


/-- The kernel ideal sheaf of the immersion of the special fibre agrees with the kernel ideal
sheaf of the closed subscheme cut out by a uniformiser. -/
theorem ker_specialFiberι_eq_ker_subschemeι (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (specialFiberι R M.toBase).ker = (baseElementIdealSheaf M π).subschemeι.ker :=
  (ker_specialFiberι M hπ).trans (Scheme.IdealSheafData.ker_subschemeι _).symm

/-- **The special fibre is isomorphic, as a closed subscheme of the total space, to the closed
subscheme cut out by a uniformiser of the base.** -/
def specialFiberSchemeIsoSubscheme (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (baseElementIdealSheaf M π).subscheme ≅ M.specialFiberScheme :=
  @asIso _ _ _ _
    (IsClosedImmersion.lift (specialFiberι R M.toBase) (baseElementIdealSheaf M π).subschemeι
      (ker_specialFiberι_eq_ker_subschemeι M hπ).le)
    (IsClosedImmersion.isIso_lift _ _ (ker_specialFiberι_eq_ker_subschemeι M hπ))

/-- The isomorphism `specialFiberSchemeIsoSubscheme` is compatible with the two closed
immersions into the total space. -/
@[reassoc (attr := simp)]
theorem specialFiberSchemeIsoSubscheme_hom_specialFiberι (M : Model R K C toK) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    (specialFiberSchemeIsoSubscheme M hπ).hom ≫ specialFiberι R M.toBase =
      (baseElementIdealSheaf M π).subschemeι :=
  IsClosedImmersion.lift_fac _ _ _


/-! ### The stalks of the special fibre -/

/-- **The kernel of the stalk map of the immersion of the special fibre is generated by the germ of
a uniformiser.** -/
theorem ker_stalkMap_specialFiberι (M : Model R K C toK) (x' : M.specialFiberScheme) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    RingHom.ker ((specialFiberι R M.toBase).stalkMap x').hom =
      Ideal.span {baseElementGerm (specialFiberι R M.toBase x') π} := by
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
    M.total.isBasis_affineOpens.exists_subset_of_mem_open
      (Set.mem_univ (specialFiberι R M.toBase x')) isOpen_univ
  have hgerm : (M.total.presheaf.germ U (specialFiberι R M.toBase x') hxU).hom
      (M.total.presheaf.map (homOfLE (le_top (a := U))).op (baseElementSection M π)) =
      baseElementGerm (specialFiberι R M.toBase x') π :=
    M.total.presheaf.germ_res_apply (homOfLE (le_top (a := U))) _ hxU _
  rw [ker_stalkMap_of_isClosedImmersion _ hU x' hxU,
    ker_specialFiberι_ideal_eq_span M hπ ⟨U, hU⟩, Ideal.map_span, Set.image_singleton, hgerm]

/-- **The comparison map from the stalk of the total space modulo the germ of a uniformiser onto
the stalk of the special fibre is injective**, completing the identification of the stalks of the
special fibre. -/
theorem specialFiberStalkQuotientHom_injective (x' : M.specialFiberScheme) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) (hπmem : π ∈ maximalIdeal R) :
    Function.Injective (specialFiberStalkQuotientHom x' hπmem) := by
  refine (injective_iff_map_eq_zero _).mpr (fun a ha => ?_)
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective a
  rw [specialFiberStalkQuotientHom_mk] at ha
  rw [Ideal.Quotient.eq_zero_iff_mem, ← ker_stalkMap_specialFiberι M x' hπ]
  exact ha

/-- **The stalks of the special fibre are the quotients of the stalks of the total space by the
germ of a uniformiser of the base.** -/
def specialFiberStalkIso (x' : M.specialFiberScheme) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) (hπmem : π ∈ maximalIdeal R) :
    (M.total.presheaf.stalk (specialFiberι R M.toBase x') ⧸
        Ideal.span {baseElementGerm (specialFiberι R M.toBase x') π}) ≃+*
      M.specialFiberScheme.presheaf.stalk x' :=
  RingEquiv.ofBijective (specialFiberStalkQuotientHom x' hπmem)
    ⟨specialFiberStalkQuotientHom_injective x' hπ hπmem,
      specialFiberStalkQuotientHom_surjective x' hπmem⟩

/-- The isomorphism `specialFiberStalkIso` is the map induced by the stalk map of the immersion of
the special fibre. -/
@[simp]
theorem specialFiberStalkIso_mk (x' : M.specialFiberScheme) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) (hπmem : π ∈ maximalIdeal R)
    (a : M.total.presheaf.stalk (specialFiberι R M.toBase x')) :
    specialFiberStalkIso x' hπ hπmem (Ideal.Quotient.mk _ a) =
      (specialFiberι R M.toBase).stalkMap x' a := rfl

/-- **The Krull dimension of the stalk of the special fibre** equals that of the quotient of the
stalk of the total space by the germ of a uniformiser. -/
theorem ringKrullDim_stalk_specialFiberScheme_eq (x' : M.specialFiberScheme) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.specialFiberScheme.presheaf.stalk x') =
      ringKrullDim (M.total.presheaf.stalk (specialFiberι R M.toBase x') ⧸
        Ideal.span {baseElementGerm (specialFiberι R M.toBase x') π}) :=
  (ringKrullDim_eq_of_ringEquiv
    (specialFiberStalkIso x' hπ (hπ ▸ Ideal.mem_span_singleton_self π))).symm

/-- A point of the special fibre is a closed point of the total space as soon as it is a closed
point of the special fibre. -/
theorem isClosed_singleton_specialFiberι (x' : M.specialFiberScheme)
    (hx' : IsClosed ({x'} : Set M.specialFiberScheme)) :
    IsClosed ({specialFiberι R M.toBase x'} : Set M.total) := by
  have h := (Scheme.Hom.isClosedEmbedding (specialFiberι R M.toBase)).isClosedMap _ hx'
  rwa [Set.image_singleton] at h

/-- **The stalk of the special fibre of a regular proper arithmetic surface at a closed point is
one-dimensional.** -/
theorem ringKrullDim_stalk_specialFiberScheme_eq_one
    (hgen : ∀ y : M.total, M.toBase y = dvrSpecialPoint R → ¬ IsClosed ({y} : Set M.total) →
      ∃ i : ArithmeticSurface.Component M, y = genericPoint i)
    (hnc : ∀ i : ArithmeticSurface.Component M,
      ¬ IsClosed ({genericPoint i} : Set M.total))
    (x' : M.specialFiberScheme) (hx' : IsClosed ({x'} : Set M.specialFiberScheme)) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.specialFiberScheme.presheaf.stalk x') = 1 := by
  rw [ringKrullDim_stalk_specialFiberScheme_eq x' hπ]
  exact ringKrullDim_quotient_baseElementGerm_eq_one hgen hnc
    (toBase_specialFiberι x') (isClosed_singleton_specialFiberι x' hx') hπ


/-! ### Pointwise one-dimensionality of the special fibre -/

/-- **The stalk of the total space modulo the germ of a uniformiser is at most one-dimensional as
soon as the corresponding stalk of the special fibre is.**  This replaces the combinatorial
one-dimensionality hypothesis `hgen` of `SpecialFibreStalk.lean` by the (weaker) pointwise
statement that the local rings of the special fibre are at most one-dimensional. -/
theorem ringKrullDim_quotient_baseElementGerm_le_one_of_stalk_le_one
    (x' : M.specialFiberScheme)
    (hdim : ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.total.presheaf.stalk (specialFiberι R M.toBase x') ⧸
      Ideal.span {baseElementGerm (specialFiberι R M.toBase x') π}) ≤ 1 := by
  rw [← ringKrullDim_stalk_specialFiberScheme_eq x' hπ]
  exact hdim

/-- **The local ring of a regular proper model at a closed point of the special fibre has Krull
dimension two**, assuming only that the local ring of the special fibre at that point is at most
one-dimensional and that no component of the special fibre is a single point. -/
theorem ringKrullDim_stalk_eq_two_of_stalk_le_one (hM : ArithmeticSurface M)
    (hnc : ∀ i : ArithmeticSurface.Component M,
      ¬ IsClosed ({genericPoint i} : Set M.total))
    (x' : M.specialFiberScheme)
    (hdim : ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    (hx' : IsClosed ({x'} : Set M.specialFiberScheme)) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.total.presheaf.stalk (specialFiberι R M.toBase x')) = 2 := by
  have hxc := isClosed_singleton_specialFiberι x' hx'
  obtain ⟨i, hxi⟩ := exists_mem_componentCloseds (toBase_specialFiberι x')
  refine ringKrullDim_stalk_eq_two hM (toBase_specialFiberι x')
    (hπ ▸ Ideal.mem_span_singleton_self π) (uniformiser_ne_zero hπ) (le_antisymm
      (ringKrullDim_quotient_baseElementGerm_le_one_of_stalk_le_one x' hdim hπ)
      (one_le_ringKrullDim_quotient_baseElementGerm hπ hxi ?_))
  intro hc
  rw [hc] at hxc
  exact hnc i hxc

/-- **The local ring of the special fibre at a closed point is exactly one-dimensional**, assuming
only that it is at most one-dimensional and that no component of the special fibre is a point. -/
theorem ringKrullDim_stalk_specialFiberScheme_eq_one_of_stalk_le_one
    (hnc : ∀ i : ArithmeticSurface.Component M,
      ¬ IsClosed ({genericPoint i} : Set M.total))
    (x' : M.specialFiberScheme)
    (hdim : ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    (hx' : IsClosed ({x'} : Set M.specialFiberScheme)) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.specialFiberScheme.presheaf.stalk x') = 1 := by
  have hxc := isClosed_singleton_specialFiberι x' hx'
  obtain ⟨i, hxi⟩ := exists_mem_componentCloseds (toBase_specialFiberι x')
  rw [ringKrullDim_stalk_specialFiberScheme_eq x' hπ]
  refine le_antisymm (ringKrullDim_quotient_baseElementGerm_le_one_of_stalk_le_one x' hdim hπ)
    (one_le_ringKrullDim_quotient_baseElementGerm hπ hxi ?_)
  intro hc
  rw [hc] at hxc
  exact hnc i hxc

/-- **The special fibre drops the dimension by exactly one at a closed point**: the local ring of
the total space of a regular proper arithmetic surface at a closed point of the special fibre is
two-dimensional, while the local ring of the special fibre there is one-dimensional. -/
theorem ringKrullDim_stalk_specialFiberScheme_add_one (hM : ArithmeticSurface M)
    (hnc : ∀ i : ArithmeticSurface.Component M,
      ¬ IsClosed ({genericPoint i} : Set M.total))
    (x' : M.specialFiberScheme)
    (hdim : ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    (hx' : IsClosed ({x'} : Set M.specialFiberScheme)) {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    ringKrullDim (M.specialFiberScheme.presheaf.stalk x') + 1 =
      ringKrullDim (M.total.presheaf.stalk (specialFiberι R M.toBase x')) := by
  rw [ringKrullDim_stalk_specialFiberScheme_eq_one_of_stalk_le_one hnc x' hdim hx' hπ,
    ringKrullDim_stalk_eq_two_of_stalk_le_one hM hnc x' hdim hx' hπ]
  rfl


/-! ### Deriving the one-dimensionality hypothesis from the stalk dimensions -/

/-- **There is no chain of three distinct specialising points of the special fibre ending at a
point where the special fibre is at most one-dimensional.**  This is the converse of
`not_specializes_chain`: the three points give three distinct primes of `𝒪_{M,y₂}` containing the
germ of a uniformiser, so the middle one is neither minimal nor maximal in the zero locus. -/
theorem not_specializes_chain_of_ringKrullDim_le_one {π : R} (hπ : π ∈ maximalIdeal R)
    {y₀ y₁ y₂ : M.total} (h₀ : M.toBase y₀ = dvrSpecialPoint R)
    (h₁ : M.toBase y₁ = dvrSpecialPoint R) (h₂ : M.toBase y₂ = dvrSpecialPoint R)
    (hs₀ : y₀ ⤳ y₁) (hs₁ : y₁ ⤳ y₂) (hne₀ : y₀ ≠ y₁) (hne₁ : y₁ ≠ y₂)
    (hle : ringKrullDim (M.total.presheaf.stalk y₂ ⧸
      Ideal.span {baseElementGerm y₂ π}) ≤ 1) : False := by
  have hemb := Scheme.Hom.isEmbedding (M.total.fromSpecStalk y₂)
  obtain ⟨q₀, hq₀⟩ : ∃ q : PrimeSpectrum (M.total.presheaf.stalk y₂),
      M.total.fromSpecStalk y₂ q = y₀ := by
    have hr : y₀ ∈ Set.range (M.total.fromSpecStalk y₂) := by
      rw [Scheme.range_fromSpecStalk]
      exact hs₀.trans hs₁
    exact hr
  obtain ⟨q₁, hq₁⟩ : ∃ q : PrimeSpectrum (M.total.presheaf.stalk y₂),
      M.total.fromSpecStalk y₂ q = y₁ := by
    have hr : y₁ ∈ Set.range (M.total.fromSpecStalk y₂) := by
      rw [Scheme.range_fromSpecStalk]
      exact hs₁
    exact hr
  have hzl : ∀ q : PrimeSpectrum (M.total.presheaf.stalk y₂), baseElementGerm y₂ π ∈ q.asIdeal →
      q ∈ PrimeSpectrum.zeroLocus
        (Ideal.span {baseElementGerm y₂ π} : Set (M.total.presheaf.stalk y₂)) := fun q hq =>
    (PrimeSpectrum.mem_zeroLocus _ _).mpr (SetLike.coe_subset_coe.mpr
      (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hq)))
  have hmem₀ : baseElementGerm y₂ π ∈ q₀.asIdeal :=
    baseElementGerm_mem_of_toBase_eq y₂ hπ (by rw [hq₀]; exact h₀)
  have hmem₁ : baseElementGerm y₂ π ∈ q₁.asIdeal :=
    baseElementGerm_mem_of_toBase_eq y₂ hπ (by rw [hq₁]; exact h₁)
  have hmem₂ : baseElementGerm y₂ π ∈ (closedPoint (M.total.presheaf.stalk y₂)).asIdeal :=
    baseElementGerm_mem_of_toBase_eq y₂ hπ
      (by rw [Scheme.fromSpecStalk_closedPoint]; exact h₂)
  have hlt₀ : q₀ < q₁ := by
    refine lt_of_le_of_ne ((PrimeSpectrum.le_iff_specializes q₀ q₁).mpr
      (hemb.isInducing.specializes_iff.mp ?_)) ?_
    · rw [hq₀, hq₁]
      exact hs₀
    · intro hc
      rw [hc, hq₁] at hq₀
      exact hne₀ hq₀.symm
  have hlt₁ : q₁ < closedPoint (M.total.presheaf.stalk y₂) := by
    refine lt_of_le_of_ne ((PrimeSpectrum.asIdeal_le_asIdeal _ _).mp
      (IsLocalRing.le_maximalIdeal q₁.2.1)) ?_
    intro hc
    rw [hc, Scheme.fromSpecStalk_closedPoint] at hq₁
    exact hne₁ hq₁.symm
  rw [ringKrullDim_quotient, Order.krullDim_le_one_iff] at hle
  rcases hle ⟨q₁, hzl q₁ hmem₁⟩ with hmin | hmax
  · have h := hmin (Subtype.coe_le_coe.mp
      (show ((⟨q₀, hzl q₀ hmem₀⟩ : PrimeSpectrum.zeroLocus _) : PrimeSpectrum _) ≤ q₁ from hlt₀.le))
    exact absurd (lt_of_lt_of_le hlt₀ (Subtype.coe_le_coe.mpr h)) (lt_irrefl q₀)
  · have h := hmax (Subtype.coe_le_coe.mp
      (show (q₁ : PrimeSpectrum _) ≤ ((⟨closedPoint _, hzl _ hmem₂⟩ :
        PrimeSpectrum.zeroLocus _) : PrimeSpectrum _) from hlt₁.le))
    exact absurd (lt_of_lt_of_le hlt₁ (Subtype.coe_le_coe.mpr h)) (lt_irrefl q₁)

/-- A point specialising to a point of the special fibre lies on the special fibre. -/
theorem toBase_eq_of_specializes {y z : M.total} (hy : M.toBase y = dvrSpecialPoint R)
    (hyz : y ⤳ z) : M.toBase z = dvrSpecialPoint R := by
  have hspec : dvrSpecialPoint R ⤳ M.toBase z := by
    have h := hyz.map M.toBase.continuous
    rwa [hy] at h
  have hclosed : IsClosed ({dvrSpecialPoint R} : Set (Spec (.of R))) :=
    (PrimeSpectrum.isClosed_singleton_iff_isMaximal _).mpr (maximalIdeal.isMaximal R)
  exact (hspec.mem_closed hclosed rfl).symm ▸ rfl

/-- **The one-dimensionality hypothesis `hgen` of `SpecialFibreStalk.lean` follows from the
pointwise statement that the local rings of the special fibre are at most one-dimensional.**  This
is a weaker hypothesis than `topologicalKrullDim M.specialFiberScheme ≤ 1`, which implies it by
`ringKrullDim_stalk_specialFiberScheme_le_one_of_topologicalKrullDim_le_one`. -/
theorem exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one
    (hdim : ∀ x' : M.specialFiberScheme,
      ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    {π : R} (hπ : maximalIdeal R = Ideal.span {π}) (y : M.total)
    (hy : M.toBase y = dvrSpecialPoint R) (hync : ¬ IsClosed ({y} : Set M.total)) :
    ∃ i : ArithmeticSurface.Component M, y = genericPoint i := by
  have hπmem : π ∈ maximalIdeal R := by
    rw [hπ]
    exact Ideal.mem_span_singleton_self π
  obtain ⟨i, hyi⟩ := exists_mem_componentCloseds hy
  refine ⟨i, ?_⟩
  by_contra hne
  obtain ⟨z, hz, hzne⟩ : ∃ z, z ∈ closure ({y} : Set M.total) ∧ z ≠ y := by
    by_contra hc
    push Not at hc
    exact hync (closure_eq_iff_isClosed.mp
      (Set.Subset.antisymm (fun w hw => hc w hw) subset_closure))
  have hyz : y ⤳ z := specializes_iff_mem_closure.mpr hz
  have hgy : genericPoint i ⤳ y := by
    refine specializes_iff_mem_closure.mpr ?_
    rw [isGenericPoint_genericPoint i]
    exact hyi
  obtain ⟨z', rfl⟩ : ∃ z' : M.specialFiberScheme, specialFiberι R M.toBase z' = z := by
    have hr : z ∈ Set.range (specialFiberι R M.toBase) := by
      rw [range_specialFiberι]
      exact toBase_eq_of_specializes hy hyz
    exact hr
  refine not_specializes_chain_of_ringKrullDim_le_one hπmem (toBase_genericPoint i) hy
    (toBase_specialFiberι z') hgy hyz (fun hc => hne hc.symm) (fun hc => hzne hc.symm) ?_
  rw [← ringKrullDim_stalk_specialFiberScheme_eq z' hπ]
  exact hdim z'


/-- **Two distinct components of the special fibre meet in a finite set of closed points**, for a
model all of whose special-fibre stalks are at most one-dimensional. -/
theorem finite_componentCloseds_inter_of_stalk_le_one
    (hdim : ∀ x' : M.specialFiberScheme,
      ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    {π : R} (hπ : maximalIdeal R = Ideal.span {π})
    {i j : ArithmeticSurface.Component M} (hij : i ≠ j) :
    ((componentCloseds i : Set M.total) ∩ componentCloseds j).Finite :=
  finite_componentCloseds_inter
    (exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one hdim hπ) hij

/-- **The intersection number of two distinct components of the special fibre of a regular proper
model is a genuine natural number**, for a model all of whose special-fibre stalks are at most
one-dimensional. -/
theorem componentIntersection_ne_top_of_stalk_le_one (hM : ArithmeticSurface M)
    (hdim : ∀ x' : M.specialFiberScheme,
      ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    {π : R} (hπ : maximalIdeal R = Ideal.span {π})
    {i j : ArithmeticSurface.Component M} (hij : i ≠ j) :
    componentIntersection i j ≠ ⊤ :=
  componentIntersection_ne_top_of_ne hM
    (exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one hdim hπ) hij

/-- The natural-number intersection number of two distinct components of the special fibre agrees
with the `ℕ∞`-valued one, for a model all of whose special-fibre stalks are at most
one-dimensional. -/
theorem coe_componentIntersectionNat_of_stalk_le_one (hM : ArithmeticSurface M)
    (hdim : ∀ x' : M.specialFiberScheme,
      ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    {π : R} (hπ : maximalIdeal R = Ideal.span {π})
    {i j : ArithmeticSurface.Component M} (hij : i ≠ j) :
    (componentIntersectionNat i j : ℕ∞) = componentIntersection i j :=
  ENat.natCast_toNat (componentIntersection_ne_top_of_stalk_le_one hM hdim hπ hij)

/-- **The local ring of a regular proper model at a closed point of the special fibre is a
two-dimensional regular local ring**, for a model all of whose special-fibre stalks are at most
one-dimensional and none of whose special-fibre components is a single point. -/
theorem krullDimLE_two_stalk_of_stalk_le_one (hM : ArithmeticSurface M)
    (hdim : ∀ x' : M.specialFiberScheme,
      ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1)
    (hnc : ∀ i : ArithmeticSurface.Component M,
      ¬ IsClosed ({genericPoint i} : Set M.total))
    {x : M.total} (hx : M.toBase x = dvrSpecialPoint R) (hxc : IsClosed ({x} : Set M.total))
    {π : R} (hπ : maximalIdeal R = Ideal.span {π}) :
    Ring.KrullDimLE 2 (M.total.presheaf.stalk x) :=
  krullDimLE_two_stalk hM (exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one hdim hπ)
    hnc hx hxc hπ


/-- **The pointwise one-dimensionality of the special fibre is equivalent to the one-dimensionality
hypothesis `hgen` used in `SpecialFibreStalk.lean`**, and hence is implied by
`topologicalKrullDim M.specialFiberScheme ≤ 1`. -/
theorem forall_ringKrullDim_stalk_le_one_iff {π : R} (hπ : maximalIdeal R = Ideal.span {π}) :
    (∀ x' : M.specialFiberScheme, ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1) ↔
      ∀ y : M.total, M.toBase y = dvrSpecialPoint R → ¬ IsClosed ({y} : Set M.total) →
        ∃ i : ArithmeticSurface.Component M, y = genericPoint i :=
  ⟨fun hdim => exists_eq_genericPoint_of_forall_ringKrullDim_stalk_le_one hdim hπ,
    fun hgen x' => ringKrullDim_stalk_specialFiberScheme_le_one hgen x' hπ⟩


/-- Every irreducible closed subset of a scheme is the closure of its generic point. -/
theorem exists_closure_singleton_eq_irreducibleCloseds {X : Scheme.{u}}
    (Z : TopologicalSpace.IrreducibleCloseds X) : ∃ g : X, closure ({g} : Set X) = (Z : Set X) := by
  refine ⟨Z.isIrreducible'.genericPoint, ?_⟩
  have h := Z.isIrreducible'.isGenericPoint_genericPoint_closure
  rwa [Z.isClosed'.closure_eq] at h

/-- **The special fibre has topological Krull dimension at most one as soon as the hypothesis
`hgen` holds.**  A chain of three irreducible closed subsets of the special fibre produces, through
their generic points, a chain of three distinct specialising points of the special fibre, which
`not_specializes_chain` excludes. -/
theorem topologicalKrullDim_specialFiberScheme_le_one
    (hgen : ∀ y : M.total, M.toBase y = dvrSpecialPoint R → ¬ IsClosed ({y} : Set M.total) →
      ∃ i : ArithmeticSurface.Component M, y = genericPoint i) :
    topologicalKrullDim M.specialFiberScheme ≤ 1 := by
  have hcont : Continuous (specialFiberι R M.toBase) :=
    (Scheme.Hom.isClosedEmbedding (specialFiberι R M.toBase)).continuous
  have hinj : Function.Injective (specialFiberι R M.toBase) :=
    (Scheme.Hom.isClosedEmbedding (specialFiberι R M.toBase)).injective
  change Order.krullDim (TopologicalSpace.IrreducibleCloseds M.specialFiberScheme) ≤ 1
  rw [Order.krullDim_le_one_iff]
  intro Z
  by_contra hc
  rw [not_or] at hc
  obtain ⟨Z₀, hZ₀⟩ := not_isMin_iff.mp hc.1
  obtain ⟨Z₂, hZ₂⟩ := not_isMax_iff.mp hc.2
  obtain ⟨g₀, hg₀⟩ := exists_closure_singleton_eq_irreducibleCloseds Z₀
  obtain ⟨g₁, hg₁⟩ := exists_closure_singleton_eq_irreducibleCloseds Z
  obtain ⟨g₂, hg₂⟩ := exists_closure_singleton_eq_irreducibleCloseds Z₂
  have hmem₀ : g₀ ∈ (Z₀ : Set M.specialFiberScheme) := by
    rw [← hg₀]
    exact subset_closure rfl
  have hmem₁ : g₁ ∈ (Z : Set M.specialFiberScheme) := by
    rw [← hg₁]
    exact subset_closure rfl
  have hs₀ : g₁ ⤳ g₀ := by
    refine specializes_iff_mem_closure.mpr ?_
    rw [hg₁]
    exact (hZ₀.le : (Z₀ : Set M.specialFiberScheme) ⊆ (Z : Set M.specialFiberScheme)) hmem₀
  have hs₁ : g₂ ⤳ g₁ := by
    refine specializes_iff_mem_closure.mpr ?_
    rw [hg₂]
    exact (hZ₂.le : (Z : Set M.specialFiberScheme) ⊆ (Z₂ : Set M.specialFiberScheme)) hmem₁
  have hne₀ : g₂ ≠ g₁ := by
    intro hcon
    have hset : (Z₂ : Set M.specialFiberScheme) = (Z : Set M.specialFiberScheme) := by
      rw [← hg₂, ← hg₁, hcon]
    exact lt_irrefl Z (lt_of_lt_of_le hZ₂ (hset.le : (Z₂ : Set M.specialFiberScheme) ⊆ _))
  have hne₁ : g₁ ≠ g₀ := by
    intro hcon
    have hset : (Z : Set M.specialFiberScheme) = (Z₀ : Set M.specialFiberScheme) := by
      rw [← hg₁, ← hg₀, hcon]
    exact lt_irrefl Z (lt_of_le_of_lt (hset.le : (Z : Set M.specialFiberScheme) ⊆ _) hZ₀)
  exact not_specializes_chain hgen (toBase_specialFiberι g₂) (toBase_specialFiberι g₁)
    (hs₁.map hcont) (hs₀.map hcont) (fun hcon => hne₀ (hinj hcon)) (fun hcon => hne₁ (hinj hcon))

/-- **The three forms of the hypothesis that the special fibre is at most one-dimensional agree.**
The topological Krull dimension of the special fibre is at most one if and only if all its local
rings are at most one-dimensional, if and only if every non-closed point of the special fibre is
the generic point of an irreducible component of it. -/
theorem topologicalKrullDim_specialFiberScheme_le_one_iff {π : R}
    (hπ : maximalIdeal R = Ideal.span {π}) :
    topologicalKrullDim M.specialFiberScheme ≤ 1 ↔
      ∀ x' : M.specialFiberScheme,
        ringKrullDim (M.specialFiberScheme.presheaf.stalk x') ≤ 1 :=
  ⟨fun htop => (forall_ringKrullDim_stalk_le_one_iff hπ).mpr
      (exists_eq_genericPoint_of_topologicalKrullDim_le_one htop),
    fun hdim => topologicalKrullDim_specialFiberScheme_le_one
      ((forall_ringKrullDim_stalk_le_one_iff hπ).mp hdim)⟩


end

end GromovWitten.AlgebraicGeometry.Curves.StableReduction
