/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/

import Mathlib.Algebra.Module.Presentation.Differentials
import Mathlib.Algebra.Module.Presentation.Finite
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.Reindex
import Mathlib.LinearAlgebra.Finsupp.SumProd
import Mathlib.Logic.Equiv.Fin.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Support
import Mathlib.RingTheory.Unramified.Basic
import Mathlib.RingTheory.Unramified.Locus

/-!
# Determinantal and Fitting ideals

This file begins the algebraic foundation for relative singular loci.  It defines the ideal of
`q`-minors of a finite matrix, proves its exact behavior under arbitrary coefficient-ring maps,
and attaches the usual determinantal Fitting ideal to a chosen finite module presentation.

Independence of the chosen presentation and the localization/sheafification API are intentionally
separate later steps; the definitions here expose the concrete minors those proofs must compare.
-/

namespace GromovWitten.AlgebraicGeometry

open CategoryTheory
open _root_.AlgebraicGeometry

universe u v w x

noncomputable section

namespace Matrix

variable {R : Type u} [CommRing R]
variable {S : Type v} [CommRing S]
variable {m : Type w} {n : Type x}

/-- The determinant of a square submatrix selected by embeddings of `Fin q` into the row and
column index types. -/
def minor (A : Matrix m n R) (q : ℕ) (rows : Fin q ↪ m) (cols : Fin q ↪ n) : R :=
  Matrix.det fun i j ↦ A (rows i) (cols j)

/-- The set of all `q`-minors of a finite matrix. -/
def minorSet (A : Matrix m n R) (q : ℕ) : Set R :=
  {a | ∃ (rows : Fin q ↪ m) (cols : Fin q ↪ n), minor A q rows cols = a}

/-- The determinantal ideal generated by all `q`-minors of a finite matrix. -/
def minorIdeal (A : Matrix m n R) (q : ℕ) : Ideal R :=
  Ideal.span (minorSet A q)

/-- The unique embedding from the empty finite type. -/
def emptyEmbedding (a : Type*) : Fin 0 ↪ a where
  toFun := Fin.elim0
  inj' i := Fin.elim0 i

/-- A ring map carries each minor to the corresponding minor of the mapped matrix. -/
theorem minor_map (f : R →+* S) (A : Matrix m n R) (q : ℕ)
    (rows : Fin q ↪ m) (cols : Fin q ↪ n) :
    minor (fun i j ↦ f (A i j)) q rows cols = f (minor A q rows cols) := by
  unfold GromovWitten.AlgebraicGeometry.Matrix.minor
  let B : _root_.Matrix (Fin q) (Fin q) R := fun i j ↦ A (rows i) (cols j)
  change Matrix.det (f.mapMatrix B) = f (Matrix.det B)
  exact (f.map_det B).symm

/-- Determinantal ideals commute with arbitrary maps of coefficient rings. -/
theorem map_minorIdeal (f : R →+* S) (A : Matrix m n R) (q : ℕ) :
    Ideal.map f (minorIdeal A q) = minorIdeal (fun i j ↦ f (A i j)) q := by
  unfold GromovWitten.AlgebraicGeometry.Matrix.minorIdeal
  rw [Ideal.map_span]
  congr 1
  ext a
  constructor
  · rintro ⟨b, ⟨rows, cols, hminor⟩, rfl⟩
    refine ⟨rows, cols, ?_⟩
    rw [minor_map, hminor]
  · rintro ⟨rows, cols, hminor⟩
    refine ⟨minor A q rows cols, ⟨rows, cols, rfl⟩, ?_⟩
    rw [← minor_map]
    exact hminor

/-- Reindexing the rows and columns of a matrix does not change any determinantal ideal. -/
theorem minorIdeal_reindex {m' n' : Type*} (A : Matrix m n R) (q : ℕ)
    (eₘ : m ≃ m') (eₙ : n ≃ n') :
    minorIdeal (Matrix.reindex eₘ eₙ A) q = minorIdeal A q := by
  apply congrArg Ideal.span
  ext a
  constructor
  · rintro ⟨rows, cols, h⟩
    refine ⟨rows.trans eₘ.symm.toEmbedding, cols.trans eₙ.symm.toEmbedding, ?_⟩
    rw [← h]
    unfold minor
    congr
  · rintro ⟨rows, cols, h⟩
    refine ⟨rows.trans eₘ.toEmbedding, cols.trans eₙ.toEmbedding, ?_⟩
    have hreindex :
        minor (Matrix.reindex eₘ eₙ A) q
            (rows.trans eₘ.toEmbedding) (cols.trans eₙ.toEmbedding) =
          minor A q
            ((rows.trans eₘ.toEmbedding).trans eₘ.symm.toEmbedding)
            ((cols.trans eₙ.toEmbedding).trans eₙ.symm.toEmbedding) := by
      unfold minor
      congr
    rw [hreindex]
    have hrows : (rows.trans eₘ.toEmbedding).trans eₘ.symm.toEmbedding = rows := by
      ext i
      simp
    have hcols : (cols.trans eₙ.toEmbedding).trans eₙ.symm.toEmbedding = cols := by
      ext i
      simp
    simpa only [hrows, hcols] using h

/-- Transposing a matrix does not change its determinantal ideals. -/
theorem minorIdeal_transpose (A : Matrix m n R) (q : ℕ) :
    minorIdeal A.transpose q = minorIdeal A q := by
  apply congrArg Ideal.span
  ext a
  constructor
  · rintro ⟨rows, cols, h⟩
    refine ⟨cols, rows, ?_⟩
    let B : _root_.Matrix (Fin q) (Fin q) R := fun i j ↦ A (cols i) (rows j)
    have htranspose : minor A.transpose q rows cols = minor A q cols rows := by
      unfold minor
      change Matrix.det B.transpose = Matrix.det B
      exact Matrix.det_transpose B
    exact htranspose.symm.trans h
  · rintro ⟨rows, cols, h⟩
    refine ⟨cols, rows, ?_⟩
    let B : _root_.Matrix (Fin q) (Fin q) R := fun i j ↦ A (rows i) (cols j)
    have htranspose : minor A.transpose q cols rows = minor A q rows cols := by
      unfold minor
      change Matrix.det B.transpose = Matrix.det B
      exact Matrix.det_transpose B
    exact htranspose.trans h

private theorem minorIdeal_updateRow_add_smul_le (A : Matrix m n R) (q : ℕ)
    [DecidableEq m] (i j : m) (hij : i ≠ j) (c : R) :
    minorIdeal (A.updateRow i (A i + c • A j)) q ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  by_cases hi : i ∈ Set.range rows
  · rcases hi with ⟨ri, hri⟩
    by_cases hj : j ∈ Set.range rows
    · rcases hj with ⟨rj, hrj⟩
      have hrij : ri ≠ rj := by
        intro h
        apply hij
        rw [← hri, ← hrj, h]
      let B : _root_.Matrix (Fin q) (Fin q) R :=
        fun a b ↦ A (rows a) (cols b)
      have hminor :
          minor (A.updateRow i (A i + c • A j)) q rows cols =
            (B.updateRow ri (B ri + c • B rj)).det := by
        unfold minor
        congr 1
        ext a b
        by_cases ha : a = ri
        · subst a
          rw [hri]
          rw [Matrix.updateRow_self, Matrix.updateRow_self]
          simp only [Pi.add_apply, Pi.smul_apply, B, hri, hrj, smul_eq_mul]
        · have hai : rows a ≠ i := by
            intro h
            exact ha (rows.injective (h.trans hri.symm))
          rw [Matrix.updateRow_ne hai, Matrix.updateRow_ne ha]
      rw [hminor, Matrix.det_updateRow_add_smul_self B hrij c]
      exact Ideal.subset_span ⟨rows, cols, rfl⟩
    · let rows' : Fin q ↪ m :=
        { toFun := Function.update rows ri j
          inj' := by
            intro a b hab
            by_cases ha : a = ri
            · subst a
              by_cases hb : b = ri
              · exact hb.symm
              · exfalso
                apply hj
                refine ⟨b, ?_⟩
                have hrow : j = rows b := by
                  simpa [Function.update_self, Function.update_of_ne hb] using hab
                exact hrow.symm
            · by_cases hb : b = ri
              · subst b
                exfalso
                apply hj
                refine ⟨a, ?_⟩
                have hrow : rows a = j := by
                  simpa [Function.update_of_ne ha, Function.update_self] using hab
                exact hrow
              · exact rows.injective (by
                  simpa [Function.update_of_ne ha, Function.update_of_ne hb] using hab) }
      let B : _root_.Matrix (Fin q) (Fin q) R :=
        fun a b ↦ A (rows a) (cols b)
      let C : Fin q → R := fun b ↦ A j (cols b)
      have hrows'_self : rows' ri = j := by
        change Function.update (fun k ↦ rows k) ri j ri = j
        simp only [Function.update_self]
      have hrows'_ne (a : Fin q) (ha : a ≠ ri) : rows' a = rows a := by
        change Function.update (fun k ↦ rows k) ri j a = rows a
        simp only [Function.update_of_ne ha]
      have hminor :
          minor (A.updateRow i (A i + c • A j)) q rows cols =
            (B.updateRow ri (B ri + c • C)).det := by
        unfold minor
        congr 1
        ext a b
        by_cases ha : a = ri
        · subst a
          rw [hri]
          rw [Matrix.updateRow_self, Matrix.updateRow_self]
          simp only [Pi.add_apply, Pi.smul_apply, B, C, hri, smul_eq_mul]
        · have hai : rows a ≠ i := by
            intro h
            exact ha (rows.injective (h.trans hri.symm))
          rw [Matrix.updateRow_ne hai, Matrix.updateRow_ne ha]
      have hreplace : (B.updateRow ri C).det = minor A q rows' cols := by
        unfold minor
        congr 1
        ext a b
        by_cases ha : a = ri
        · subst a
          rw [Matrix.updateRow_self]
          rw [hrows'_self]
        · rw [Matrix.updateRow_ne ha]
          rw [hrows'_ne a ha]
      rw [hminor, Matrix.det_updateRow_add, Matrix.updateRow_eq_self,
        Matrix.det_updateRow_smul, hreplace]
      exact Ideal.add_mem _
        (Ideal.subset_span ⟨rows, cols, rfl⟩)
        (Ideal.mul_mem_left _ c (Ideal.subset_span ⟨rows', cols, rfl⟩))
  · have hminor :
        minor (A.updateRow i (A i + c • A j)) q rows cols = minor A q rows cols := by
      unfold minor
      congr 1
      ext a b
      have hai : rows a ≠ i := by
        intro h
        exact hi ⟨a, h⟩
      simp [hai]
    rw [hminor]
    exact Ideal.subset_span ⟨rows, cols, rfl⟩

/-- Adding a scalar multiple of one row to a different row does not change any determinantal
ideal. -/
theorem minorIdeal_updateRow_add_smul (A : Matrix m n R) (q : ℕ) [DecidableEq m]
    (i j : m) (hij : i ≠ j) (c : R) :
    minorIdeal (A.updateRow i (A i + c • A j)) q = minorIdeal A q := by
  apply le_antisymm
  · exact minorIdeal_updateRow_add_smul_le A q i j hij c
  · let A' : Matrix m n R := A.updateRow i (A i + c • A j)
    have hinv : A'.updateRow i (A' i + (-c) • A' j) = A := by
      ext a b
      by_cases ha : a = i
      · subst a
        have hji : j ≠ i := hij.symm
        simp [A', hji]
      · simp [A', ha]
    calc
      minorIdeal A q = minorIdeal (A'.updateRow i (A' i + (-c) • A' j)) q :=
        congrArg (fun B ↦ minorIdeal B q) hinv.symm
      _ ≤ minorIdeal A' q := minorIdeal_updateRow_add_smul_le A' q i j hij (-c)

/-- Adding a scalar multiple of one column to a different column does not change any
determinantal ideal. -/
theorem minorIdeal_updateCol_add_smul (A : Matrix m n R) (q : ℕ) [DecidableEq n]
    (i j : n) (hij : i ≠ j) (c : R) :
    minorIdeal (A.updateCol i (fun k ↦ A k i + c • A k j)) q = minorIdeal A q := by
  let A' : Matrix m n R := A.updateCol i (fun k ↦ A k i + c • A k j)
  have htranspose : A'.transpose =
      A.transpose.updateRow i (A.transpose i + c • A.transpose j) := by
    ext a b
    by_cases ha : a = i
    · subst a
      simp [A']
    · simp [A', ha]
  calc
    minorIdeal A' q = minorIdeal A'.transpose q := (minorIdeal_transpose A' q).symm
    _ = minorIdeal (A.transpose.updateRow i (A.transpose i + c • A.transpose j)) q :=
      congrArg (fun B ↦ minorIdeal B q) htranspose
    _ = minorIdeal A.transpose q := minorIdeal_updateRow_add_smul A.transpose q i j hij c
    _ = minorIdeal A q := minorIdeal_transpose A q

private theorem minorIdeal_updateRow_smul_le (A : Matrix m n R) (q : ℕ)
    [DecidableEq m] (i : m) (c : R) :
    minorIdeal (A.updateRow i (c • A i)) q ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  by_cases hi : i ∈ Set.range rows
  · rcases hi with ⟨ri, hri⟩
    let B : _root_.Matrix (Fin q) (Fin q) R := fun a b ↦ A (rows a) (cols b)
    have hminor : minor (A.updateRow i (c • A i)) q rows cols =
        (B.updateRow ri (c • B ri)).det := by
      unfold minor
      congr 1
      ext a b
      by_cases ha : a = ri
      · subst a
        rw [hri]
        rw [Matrix.updateRow_self, Matrix.updateRow_self]
        simp only [Pi.smul_apply, B, hri, smul_eq_mul]
      · have hai : rows a ≠ i := by
          intro h
          exact ha (rows.injective (h.trans hri.symm))
        rw [Matrix.updateRow_ne hai, Matrix.updateRow_ne ha]
    rw [hminor, Matrix.det_updateRow_smul, Matrix.updateRow_eq_self]
    exact Ideal.mul_mem_left _ c (Ideal.subset_span ⟨rows, cols, rfl⟩)
  · have hminor : minor (A.updateRow i (c • A i)) q rows cols = minor A q rows cols := by
      unfold minor
      congr 1
      ext a b
      have hai : rows a ≠ i := by
        intro h
        exact hi ⟨a, h⟩
      simp [hai]
    rw [hminor]
    exact Ideal.subset_span ⟨rows, cols, rfl⟩

/-- Multiplying one row by a unit does not change any determinantal ideal. -/
theorem minorIdeal_updateRow_unit_smul (A : Matrix m n R) (q : ℕ) [DecidableEq m]
    (i : m) (u : Rˣ) :
    minorIdeal (A.updateRow i ((u : R) • A i)) q = minorIdeal A q := by
  apply le_antisymm
  · exact minorIdeal_updateRow_smul_le A q i u
  · let A' : Matrix m n R := A.updateRow i ((u : R) • A i)
    have hinv : A'.updateRow i ((↑u⁻¹ : R) • A' i) = A := by
      ext a b
      by_cases ha : a = i
      · subst a
        simp [A']
      · simp [A', ha]
    calc
      minorIdeal A q = minorIdeal (A'.updateRow i ((↑u⁻¹ : R) • A' i)) q :=
        congrArg (fun B ↦ minorIdeal B q) hinv.symm
      _ ≤ minorIdeal A' q := minorIdeal_updateRow_smul_le A' q i ↑u⁻¹

/-- Multiplying one column by a unit does not change any determinantal ideal. -/
theorem minorIdeal_updateCol_unit_smul (A : Matrix m n R) (q : ℕ) [DecidableEq n]
    (i : n) (u : Rˣ) :
    minorIdeal (A.updateCol i (fun k ↦ (u : R) • A k i)) q = minorIdeal A q := by
  let A' : Matrix m n R := A.updateCol i (fun k ↦ (u : R) • A k i)
  have htranspose : A'.transpose = A.transpose.updateRow i ((u : R) • A.transpose i) := by
    ext a b
    by_cases ha : a = i
    · subst a
      simp [A']
    · simp [A', ha]
  calc
    minorIdeal A' q = minorIdeal A'.transpose q := (minorIdeal_transpose A' q).symm
    _ = minorIdeal (A.transpose.updateRow i ((u : R) • A.transpose i)) q :=
      congrArg (fun B ↦ minorIdeal B q) htranspose
    _ = minorIdeal A.transpose q := minorIdeal_updateRow_unit_smul A.transpose q i u
    _ = minorIdeal A q := minorIdeal_transpose A q

/-- Left multiplication can only decrease a determinantal ideal: every minor of the product is a
linear combination of minors of the right-hand matrix. -/
theorem minorIdeal_mul_left_le {l : Type*} [Fintype m]
    (U : Matrix l m R) (A : Matrix m n R) (q : ℕ) :
    minorIdeal (U * A) q ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let baseRow (k : m) : Fin q → R := fun j ↦ A k (cols j)
  let g (i : Fin q) (k : m) : Fin q → R := U (rows i) k • baseRow k
  have hrows : (fun i j ↦ (U * A) (rows i) (cols j)) = fun i ↦ ∑ k, g i k := by
    ext i j
    simp [g, baseRow, Matrix.mul_apply, smul_eq_mul]
  unfold minor
  rw [hrows]
  change Matrix.detRowAlternating.toMultilinearMap (fun i ↦ ∑ k, g i k) ∈ minorIdeal A q
  rw [MultilinearMap.map_sum]
  refine Ideal.sum_mem _ fun r _ ↦ ?_
  let D : _root_.Matrix (Fin q) (Fin q) R := fun i j ↦ A (r i) (cols j)
  have hg : (fun i ↦ g i (r i)) = fun i ↦ U (rows i) (r i) • D i := by
    rfl
  rw [hg, MultilinearMap.map_smul_univ]
  by_cases hr : Function.Injective r
  · let rowEmbedding : Fin q ↪ m := ⟨r, hr⟩
    change (∏ i, U (rows i) (r i)) • minor A q rowEmbedding cols ∈ minorIdeal A q
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨rowEmbedding, cols, rfl⟩)
  · obtain ⟨i, j, heq, hij⟩ := Function.not_injective_iff.mp hr
    have hdet : D.det = 0 := by
      apply Matrix.det_zero_of_row_eq hij
      ext k
      simp [D, heq]
    change (∏ i, U (rows i) (r i)) * D.det ∈ minorIdeal A q
    rw [hdet, mul_zero]
    exact Ideal.zero_mem _

/-- Right multiplication can only decrease a determinantal ideal. -/
theorem minorIdeal_mul_right_le {l : Type*} [Fintype n]
    (A : Matrix m n R) (V : Matrix n l R) (q : ℕ) :
    minorIdeal (A * V) q ≤ minorIdeal A q := by
  calc
    minorIdeal (A * V) q = minorIdeal (A * V).transpose q :=
      (minorIdeal_transpose (A * V) q).symm
    _ = minorIdeal (V.transpose * A.transpose) q :=
      congrArg (fun B ↦ minorIdeal B q) (Matrix.transpose_mul A V)
    _ ≤ minorIdeal A.transpose q := minorIdeal_mul_left_le V.transpose A.transpose q
    _ = minorIdeal A q := minorIdeal_transpose A q

/-- Two matrices with the same row type have identical determinantal ideals when each family of
columns is obtained by taking linear combinations of the other. -/
theorem minorIdeal_eq_of_mutual_right_factorization {l : Type*}
    [Fintype n] [Fintype l]
    (A : Matrix m n R) (B : Matrix m l R)
    (U : Matrix l n R) (V : Matrix n l R)
    (hA : A = B * U) (hB : B = A * V) (q : ℕ) :
    minorIdeal A q = minorIdeal B q := by
  apply le_antisymm
  · rw [hA]
    exact minorIdeal_mul_right_le B U q
  · rw [hB]
    exact minorIdeal_mul_right_le A V q

/-- Multiplication on the left by a matrix with a left inverse leaves all determinantal ideals
unchanged. In particular, this proves invariance under every invertible row-basis change. -/
theorem minorIdeal_mul_left_eq_of_leftInverse [Fintype m] [DecidableEq m]
    (U V : Matrix m m R) (hVU : V * U = 1) (A : Matrix m n R) (q : ℕ) :
    minorIdeal (U * A) q = minorIdeal A q := by
  apply le_antisymm
  · exact minorIdeal_mul_left_le U A q
  · have hA : V * (U * A) = A := by
      rw [← Matrix.mul_assoc, hVU, Matrix.one_mul]
    calc
      minorIdeal A q = minorIdeal (V * (U * A)) q :=
        congrArg (fun B ↦ minorIdeal B q) hA.symm
      _ ≤ minorIdeal (U * A) q := minorIdeal_mul_left_le V (U * A) q

/-- Multiplication on the right by a matrix with a right inverse leaves all determinantal ideals
unchanged. In particular, this proves invariance under every invertible column-basis change. -/
theorem minorIdeal_mul_right_eq_of_rightInverse [Fintype n] [DecidableEq n]
    (A : Matrix m n R) (U V : Matrix n n R) (hUV : U * V = 1) (q : ℕ) :
    minorIdeal (A * U) q = minorIdeal A q := by
  apply le_antisymm
  · exact minorIdeal_mul_right_le A U q
  · have hA : (A * U) * V = A := by
      rw [Matrix.mul_assoc, hUV, Matrix.mul_one]
    calc
      minorIdeal A q = minorIdeal ((A * U) * V) q :=
        congrArg (fun B ↦ minorIdeal B q) hA.symm
      _ ≤ minorIdeal (A * U) q := minorIdeal_mul_right_le (A * U) V q

/-- Determinantal ideals are decreasing in the size of the minors. -/
theorem minorIdeal_succ_le (A : Matrix m n R) (q : ℕ) :
    minorIdeal A (q + 1) ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let B : _root_.Matrix (Fin (q + 1)) (Fin (q + 1)) R :=
    fun i j ↦ A (rows i) (cols j)
  rw [show minor A (q + 1) rows cols = B.det from rfl, Matrix.det_succ_row B 0]
  refine Ideal.sum_mem _ fun j _ ↦ ?_
  let rows' : Fin q ↪ m := (Fin.succAboveEmb (0 : Fin (q + 1))).trans rows
  let cols' : Fin q ↪ n := (Fin.succAboveEmb j).trans cols
  have hdet : (B.submatrix (0 : Fin (q + 1)).succAbove j.succAbove).det =
      minor A q rows' cols' := by
    rfl
  rw [hdet]
  exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨rows', cols', rfl⟩)

/-- Adjoin a trivial row-column pair to a matrix. The new row and column meet in a single `1`
and vanish elsewhere. -/
def unitStabilization (A : Matrix m n R) : Matrix (Option m) (Option n) R
  | some i, some j => A i j
  | none, none => 1
  | _, _ => 0

private def dropNoneEmbedding {q : ℕ} (e : Fin q ↪ Option m)
    (h : none ∉ Set.range e) : Fin q ↪ m :=
  let e' : Fin q ↪ {x : Option m // x.isSome} :=
    { toFun := fun k ↦ ⟨e k, by
        rw [← Option.ne_none_iff_isSome]
        intro hk
        exact h ⟨k, hk⟩⟩
      inj' := fun a b hab ↦ e.injective (congrArg Subtype.val hab) }
  e'.trans (Equiv.optionIsSomeEquiv m).toEmbedding

private theorem some_dropNoneEmbedding {q : ℕ} (e : Fin q ↪ Option m)
    (h : none ∉ Set.range e) (k : Fin q) : some (dropNoneEmbedding e h k) = e k := by
  exact Option.some_get _

private theorem minorIdeal_le_unitStabilization (A : Matrix m n R) (q : ℕ) :
    minorIdeal A q ≤ minorIdeal (unitStabilization A) (q + 1) := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let rows' : Fin (q + 1) ↪ Option m :=
    (finSuccEquiv q).toEmbedding.trans (Function.Embedding.optionMap rows)
  let cols' : Fin (q + 1) ↪ Option n :=
    (finSuccEquiv q).toEmbedding.trans (Function.Embedding.optionMap cols)
  apply Ideal.subset_span
  refine ⟨rows', cols', ?_⟩
  let B : _root_.Matrix (Fin (q + 1)) (Fin (q + 1)) R :=
    fun i j ↦ unitStabilization A (rows' i) (cols' j)
  have hsub : B.submatrix Fin.succ Fin.succ = fun i j ↦ A (rows i) (cols j) := by
    ext i j
    change unitStabilization A
      (Option.map rows (finSuccEquiv q i.succ))
      (Option.map cols (finSuccEquiv q j.succ)) = A (rows i) (cols j)
    rw [finSuccEquiv_succ, finSuccEquiv_succ]
    rfl
  have h00 : B 0 0 = 1 := by
    simp [B, rows', cols', unitStabilization]
  have h0succ (j : Fin q) : B 0 j.succ = 0 := by
    simp [B, rows', cols', unitStabilization]
  rw [show minor (unitStabilization A) (q + 1) rows' cols' = B.det from rfl,
    Matrix.det_succ_row_zero]
  rw [Fin.sum_univ_succ]
  simp [h00, h0succ, hsub]
  rfl

private theorem minorIdeal_unitStabilization_le (A : Matrix m n R) (q : ℕ) :
    minorIdeal (unitStabilization A) (q + 1) ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let B : _root_.Matrix (Fin (q + 1)) (Fin (q + 1)) R :=
    fun i j ↦ unitStabilization A (rows i) (cols j)
  by_cases hr : none ∈ Set.range rows
  · rcases hr with ⟨ri, hri⟩
    by_cases hc : none ∈ Set.range cols
    · rcases hc with ⟨ci, hci⟩
      rw [show minor (unitStabilization A) (q + 1) rows cols = B.det from rfl,
        Matrix.det_succ_row B ri]
      refine Ideal.sum_mem _ fun k _ ↦ ?_
      by_cases hk : k = ci
      · subst k
        let rows0 : Fin q ↪ Option m := (Fin.succAboveEmb ri).trans rows
        let cols0 : Fin q ↪ Option n := (Fin.succAboveEmb ci).trans cols
        have hrows0 : none ∉ Set.range rows0 := by
          rintro ⟨k, hk⟩
          exact Fin.succAbove_ne ri k (rows.injective (hk.trans hri.symm))
        have hcols0 : none ∉ Set.range cols0 := by
          rintro ⟨k, hk⟩
          exact Fin.succAbove_ne ci k (cols.injective (hk.trans hci.symm))
        let rowsA : Fin q ↪ m := dropNoneEmbedding rows0 hrows0
        let colsA : Fin q ↪ n := dropNoneEmbedding cols0 hcols0
        have hdet : (B.submatrix ri.succAbove ci.succAbove).det =
            minor A q rowsA colsA := by
          unfold minor
          congr 1
          ext a b
          change unitStabilization A (rows0 a) (cols0 b) = A (rowsA a) (colsA b)
          rw [← some_dropNoneEmbedding rows0 hrows0 a,
            ← some_dropNoneEmbedding cols0 hcols0 b]
          rfl
        rw [hdet]
        exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨rowsA, colsA, rfl⟩)
      · have hzero : B ri k = 0 := by
          have hknone : cols k ≠ none := by
            intro h
            apply hk
            exact cols.injective (h.trans hci.symm)
          cases hcol : cols k with
          | none => exact (hknone hcol).elim
          | some col =>
              change unitStabilization A (rows ri) (cols k) = 0
              rw [hri, hcol]
              rfl
        simp [hzero]
    · have hzero (k : Fin (q + 1)) : B ri k = 0 := by
        have hknone : cols k ≠ none := by
          intro h
          exact hc ⟨k, h⟩
        cases hcol : cols k with
        | none => exact (hknone hcol).elim
        | some col =>
            change unitStabilization A (rows ri) (cols k) = 0
            rw [hri, hcol]
            rfl
      rw [show minor (unitStabilization A) (q + 1) rows cols = B.det from rfl,
        Matrix.det_eq_zero_of_row_eq_zero ri hzero]
      exact Ideal.zero_mem _
  · by_cases hc : none ∈ Set.range cols
    · rcases hc with ⟨ci, hci⟩
      have hzero (k : Fin (q + 1)) : B k ci = 0 := by
        have hknone : rows k ≠ none := by
          intro h
          exact hr ⟨k, h⟩
        cases hrow : rows k with
        | none => exact (hknone hrow).elim
        | some row =>
            change unitStabilization A (rows k) (cols ci) = 0
            rw [hrow, hci]
            rfl
      rw [show minor (unitStabilization A) (q + 1) rows cols = B.det from rfl,
        Matrix.det_eq_zero_of_column_eq_zero ci hzero]
      exact Ideal.zero_mem _
    · let rowsA : Fin (q + 1) ↪ m := dropNoneEmbedding rows hr
      let colsA : Fin (q + 1) ↪ n := dropNoneEmbedding cols hc
      have hminor : minor (unitStabilization A) (q + 1) rows cols =
          minor A (q + 1) rowsA colsA := by
        unfold minor
        congr 1
        ext a b
        rw [← some_dropNoneEmbedding rows hr a,
          ← some_dropNoneEmbedding cols hc b]
        rfl
      rw [hminor]
      exact minorIdeal_succ_le A q (Ideal.subset_span ⟨rowsA, colsA, rfl⟩)

/-- Adjoining a trivial generator-relation pair shifts the size of the minors by one and leaves
the resulting determinantal ideal unchanged. -/
theorem minorIdeal_unitStabilization (A : Matrix m n R) (q : ℕ) :
    minorIdeal (unitStabilization A) (q + 1) = minorIdeal A q :=
  le_antisymm (minorIdeal_unitStabilization_le A q)
    (minorIdeal_le_unitStabilization A q)

/-! ### Finite stabilization -/

/-- Reindexing one further `Option`-stabilization as a leading `Fin (k + 1)` block. -/
def optionFinSumEquiv (k : ℕ) (a : Type*) : Option (Fin k ⊕ a) ≃ Fin (k + 1) ⊕ a where
  toFun
    | none => Sum.inl 0
    | some (Sum.inl i) => Sum.inl i.succ
    | some (Sum.inr x) => Sum.inr x
  invFun
    | Sum.inl i => (finSuccEquiv k i).map Sum.inl
    | Sum.inr x => some (Sum.inr x)
  left_inv x := by
    rcases x with _ | x
    · simp
    · rcases x with i | x
      · simp
      · simp
  right_inv x := by
    rcases x with i | x
    · cases h : finSuccEquiv k i with
      | none =>
          have hi : i = 0 := finSuccEquiv_eq_none.mp h
          subst i
          simp
      | some j =>
          have hi : i = j.succ := finSuccEquiv_eq_some.mp h
          subst i
          simp
    · simp

@[simp] theorem optionFinSumEquiv_symm_inl_zero (k : ℕ) (a : Type*) :
    (optionFinSumEquiv k a).symm (Sum.inl 0) = none := by
  rfl

@[simp] theorem optionFinSumEquiv_symm_inl_succ (k : ℕ) (a : Type*) (i : Fin k) :
    (optionFinSumEquiv k a).symm (Sum.inl i.succ) = some (Sum.inl i) := by
  simp [optionFinSumEquiv]

@[simp] theorem optionFinSumEquiv_symm_inr (k : ℕ) (a : Type*) (x : a) :
    (optionFinSumEquiv k a).symm (Sum.inr x) = some (Sum.inr x) := by
  rfl

/-- Adjoin `k` independent unit row-column pairs, indexed by a leading `Fin k` block. -/
def finUnitStabilization (A : Matrix m n R) :
    (k : ℕ) → Matrix (Fin k ⊕ m) (Fin k ⊕ n) R
  | 0 => Matrix.reindex (Equiv.emptySum (Fin 0) m).symm
      (Equiv.emptySum (Fin 0) n).symm A
  | k + 1 => Matrix.reindex (optionFinSumEquiv k m)
      (optionFinSumEquiv k n)
      (unitStabilization (finUnitStabilization A k))

/-- Adjoining `k` unit pairs shifts the minor size by exactly `k`. -/
theorem minorIdeal_finUnitStabilization (A : Matrix m n R) (q k : ℕ) :
    minorIdeal (finUnitStabilization A k) (q + k) = minorIdeal A q := by
  induction k with
  | zero =>
      simp only [Nat.add_zero, finUnitStabilization]
      rw [minorIdeal_reindex]
  | succ k ih =>
      rw [show q + (k + 1) = (q + k) + 1 by omega,
        finUnitStabilization, minorIdeal_reindex,
        minorIdeal_unitStabilization, ih]

/-- Adjoin a finite identity block with an arbitrary finite index type. -/
def finiteUnitStabilization (A : Matrix m n R) (l : Type*) [Fintype l] :
    Matrix (l ⊕ m) (l ⊕ n) R :=
  Matrix.reindex
    (Equiv.sumCongr (Fintype.equivFin l).symm (Equiv.refl m))
    (Equiv.sumCongr (Fintype.equivFin l).symm (Equiv.refl n))
    (finUnitStabilization A (Fintype.card l))

/-- A finite identity block shifts the minor size by its cardinality. -/
theorem minorIdeal_finiteUnitStabilization (A : Matrix m n R)
    (l : Type*) [Fintype l] (q : ℕ) :
    minorIdeal (finiteUnitStabilization A l) (q + Fintype.card l) =
      minorIdeal A q := by
  rw [finiteUnitStabilization, minorIdeal_reindex,
    minorIdeal_finUnitStabilization]

@[simp] theorem finUnitStabilization_inr_inr (A : Matrix m n R) (k : ℕ)
    (i : m) (j : n) :
    finUnitStabilization A k (Sum.inr i) (Sum.inr j) = A i j := by
  induction k with
  | zero => rfl
  | succ k ih =>
      simpa [finUnitStabilization, unitStabilization] using ih

@[simp] theorem finUnitStabilization_inl_inl (A : Matrix m n R) (k : ℕ)
    (i j : Fin k) :
    finUnitStabilization A k (Sum.inl i) (Sum.inl j) = if i = j then 1 else 0 := by
  induction k with
  | zero => exact Fin.elim0 i
  | succ k ih =>
      cases hi : finSuccEquiv k i with
      | none =>
          have hi' : i = 0 := finSuccEquiv_eq_none.mp hi
          subst i
          cases hj : finSuccEquiv k j with
          | none =>
              have hj' : j = 0 := finSuccEquiv_eq_none.mp hj
              subst j
              simp [finUnitStabilization, unitStabilization]
          | some j' =>
              have hj' : j = j'.succ := finSuccEquiv_eq_some.mp hj
              subst j
              have hne : (0 : Fin (k + 1)) ≠ j'.succ := (Fin.succ_ne_zero j').symm
              rw [if_neg hne]
              simp [finUnitStabilization, unitStabilization]
      | some i' =>
          have hi' : i = i'.succ := finSuccEquiv_eq_some.mp hi
          subst i
          cases hj : finSuccEquiv k j with
          | none =>
              have hj' : j = 0 := finSuccEquiv_eq_none.mp hj
              subst j
              simp [finUnitStabilization, unitStabilization]
          | some j' =>
              have hj' : j = j'.succ := finSuccEquiv_eq_some.mp hj
              subst j
              simpa [finUnitStabilization, unitStabilization] using ih i' j'

@[simp] theorem finUnitStabilization_inl_inr (A : Matrix m n R) (k : ℕ)
    (i : Fin k) (j : n) :
    finUnitStabilization A k (Sum.inl i) (Sum.inr j) = 0 := by
  induction k with
  | zero => exact Fin.elim0 i
  | succ k ih =>
      cases hi : finSuccEquiv k i with
      | none =>
          have hi' : i = 0 := finSuccEquiv_eq_none.mp hi
          subst i
          simp [finUnitStabilization, unitStabilization]
      | some i' =>
          have hi' : i = i'.succ := finSuccEquiv_eq_some.mp hi
          subst i
          simpa [finUnitStabilization, unitStabilization] using ih i'

@[simp] theorem finUnitStabilization_inr_inl (A : Matrix m n R) (k : ℕ)
    (i : m) (j : Fin k) :
    finUnitStabilization A k (Sum.inr i) (Sum.inl j) = 0 := by
  induction k with
  | zero => exact Fin.elim0 j
  | succ k ih =>
      cases hj : finSuccEquiv k j with
      | none =>
          have hj' : j = 0 := finSuccEquiv_eq_none.mp hj
          subst j
          simp [finUnitStabilization, unitStabilization]
      | some j' =>
          have hj' : j = j'.succ := finSuccEquiv_eq_some.mp hj
          subst j
          simpa [finUnitStabilization, unitStabilization] using ih j'

@[simp] theorem finiteUnitStabilization_inr_inr (A : Matrix m n R)
    (l : Type*) [Fintype l] (i : m) (j : n) :
    finiteUnitStabilization A l (Sum.inr i) (Sum.inr j) = A i j := by
  simp [finiteUnitStabilization]

@[simp] theorem finiteUnitStabilization_inl_inl (A : Matrix m n R)
    (l : Type*) [Fintype l] [DecidableEq l] (i j : l) :
    finiteUnitStabilization A l (Sum.inl i) (Sum.inl j) = if i = j then 1 else 0 := by
  classical
  simp [finiteUnitStabilization]

@[simp] theorem finiteUnitStabilization_inl_inr (A : Matrix m n R)
    (l : Type*) [Fintype l] (i : l) (j : n) :
    finiteUnitStabilization A l (Sum.inl i) (Sum.inr j) = 0 := by
  simp [finiteUnitStabilization]

@[simp] theorem finiteUnitStabilization_inr_inl (A : Matrix m n R)
    (l : Type*) [Fintype l] (i : m) (j : l) :
    finiteUnitStabilization A l (Sum.inr i) (Sum.inl j) = 0 := by
  simp [finiteUnitStabilization]

/-- A minor no larger than the adjoined identity block already contains `1`. -/
theorem minorIdeal_finiteUnitStabilization_eq_top_of_le_card
    (A : Matrix m n R) (l : Type*) [Fintype l] (q : ℕ)
    (hq : q ≤ Fintype.card l) :
    minorIdeal (finiteUnitStabilization A l) q = ⊤ := by
  classical
  rw [Ideal.eq_top_iff_one]
  have hq' : Fintype.card (Fin q) ≤ Fintype.card l := by simpa using hq
  obtain ⟨e⟩ := Function.Embedding.nonempty_of_card_le hq'
  apply Ideal.subset_span
  refine ⟨e.trans Function.Embedding.inl, e.trans Function.Embedding.inl, ?_⟩
  unfold minor
  change Matrix.det (fun i j ↦ finiteUnitStabilization A l
      (Sum.inl (e i)) (Sum.inl (e j))) = 1
  rw [show (fun i j ↦ finiteUnitStabilization A l
      (Sum.inl (e i)) (Sum.inl (e j))) = (1 : Matrix (Fin q) (Fin q) R) by
    ext i j
    simp [Matrix.one_apply]]
  exact Matrix.det_one

/-- The ideal of zero-minors is the unit ideal. -/
@[simp]
theorem minorIdeal_zero (A : Matrix m n R) : minorIdeal A 0 = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  apply Ideal.subset_span
  refine ⟨emptyEmbedding m, emptyEmbedding n, ?_⟩
  change Matrix.det (fun i j : Fin 0 ↦ A ((emptyEmbedding m) i) ((emptyEmbedding n) j)) = 1
  exact Matrix.det_isEmpty

/-! ### Adjoining an arbitrary finite generator family -/

/-- Add a finite generator block to a relation matrix. The new relation indexed by `j` says that
the new generator `j` equals the linear combination of old generators with coefficients `a j`. -/
def generatorExtension [DecidableEq l] (A : Matrix m n R) (a : l → m → R) :
    Matrix (m ⊕ l) (l ⊕ n) R
  | Sum.inl i, Sum.inl j => -a j i
  | Sum.inr i, Sum.inl j => if i = j then 1 else 0
  | Sum.inl i, Sum.inr j => A i j
  | Sum.inr _, Sum.inr _ => 0

/-- The unit lower-triangular row shear which inserts the old-generator expression into each new
generator relation. -/
def generatorExtensionShear [DecidableEq m] [DecidableEq l] (a : l → m → R) :
    Matrix (m ⊕ l) (m ⊕ l) R
  | Sum.inl i, Sum.inl j => if i = j then 1 else 0
  | Sum.inl i, Sum.inr j => -a j i
  | Sum.inr _, Sum.inl _ => 0
  | Sum.inr i, Sum.inr j => if i = j then 1 else 0

/-- The inverse row shear, with the off-diagonal block negated. -/
def generatorExtensionShearInv [DecidableEq m] [DecidableEq l] (a : l → m → R) :
    Matrix (m ⊕ l) (m ⊕ l) R
  | Sum.inl i, Sum.inl j => if i = j then 1 else 0
  | Sum.inl i, Sum.inr j => a j i
  | Sum.inr _, Sum.inl _ => 0
  | Sum.inr i, Sum.inr j => if i = j then 1 else 0

theorem generatorExtensionShearInv_mul [Fintype m] [Fintype l]
    [DecidableEq m] [DecidableEq l] (a : l → m → R) :
    generatorExtensionShearInv a * generatorExtensionShear a = 1 := by
  ext i j
  rcases i with i | i <;> rcases j with j | j
  · simp [generatorExtensionShearInv, generatorExtensionShear, Matrix.mul_apply,
      Matrix.one_apply]
  · simp [generatorExtensionShearInv, generatorExtensionShear, Matrix.mul_apply]
  · simp [generatorExtensionShearInv, generatorExtensionShear, Matrix.mul_apply]
  · simp [generatorExtensionShearInv, generatorExtensionShear, Matrix.mul_apply,
      Matrix.one_apply]

theorem generatorExtension_eq_mul [Fintype m] [Fintype l]
    [DecidableEq m] [DecidableEq l]
    (A : Matrix m n R) (a : l → m → R) :
    generatorExtension A a = generatorExtensionShear a *
      Matrix.reindex (Equiv.sumComm l m) (Equiv.refl (l ⊕ n))
        (finiteUnitStabilization A l) := by
  ext i j
  rcases i with i | i <;> rcases j with j | j
  · simp [generatorExtension, generatorExtensionShear, Matrix.mul_apply]
  · simp [generatorExtension, generatorExtensionShear, Matrix.mul_apply]
  · simp [generatorExtension, generatorExtensionShear, Matrix.mul_apply]
  · simp [generatorExtension, generatorExtensionShear, Matrix.mul_apply]

/-- Adding finitely many generators with matching relations shifts the minor size by the size of
the new generator family and preserves the determinantal ideal. -/
theorem minorIdeal_generatorExtension [Finite m] [Fintype l]
    [DecidableEq l]
    (A : Matrix m n R) (a : l → m → R) (q : ℕ) :
    minorIdeal (generatorExtension A a) (q + Fintype.card l) = minorIdeal A q := by
  classical
  let _ := Fintype.ofFinite m
  rw [generatorExtension_eq_mul]
  rw [minorIdeal_mul_left_eq_of_leftInverse _ (generatorExtensionShearInv a)
    (generatorExtensionShearInv_mul a)]
  rw [minorIdeal_reindex, minorIdeal_finiteUnitStabilization]

theorem minorIdeal_generatorExtension_eq_top_of_le_card [Finite m] [Fintype l]
    [DecidableEq l]
    (A : Matrix m n R) (a : l → m → R) (q : ℕ)
    (hq : q ≤ Fintype.card l) :
    minorIdeal (generatorExtension A a) q = ⊤ := by
  classical
  let _ := Fintype.ofFinite m
  rw [generatorExtension_eq_mul]
  rw [minorIdeal_mul_left_eq_of_leftInverse _ (generatorExtensionShearInv a)
    (generatorExtensionShearInv_mul a)]
  rw [minorIdeal_reindex,
    minorIdeal_finiteUnitStabilization_eq_top_of_le_card A l q hq]

/-- The Fitting-index form of finite generator stabilization, including the range where the
adjoined identity block makes the ideal equal to `⊤`. -/
theorem minorIdeal_generatorExtension_fitting [Fintype m] [Fintype l]
    [DecidableEq l]
    (A : Matrix m n R) (a : l → m → R) (i : ℕ) :
    minorIdeal (generatorExtension A a) (Fintype.card m + Fintype.card l - i) =
      minorIdeal A (Fintype.card m - i) := by
  classical
  by_cases hi : i ≤ Fintype.card m
  · rw [show Fintype.card m + Fintype.card l - i =
        (Fintype.card m - i) + Fintype.card l by omega,
      minorIdeal_generatorExtension]
  · have him : Fintype.card m ≤ i := Nat.le_of_lt (lt_of_not_ge hi)
    have hq : Fintype.card m + Fintype.card l - i ≤ Fintype.card l := by omega
    rw [minorIdeal_generatorExtension_eq_top_of_le_card A a _ hq,
      Nat.sub_eq_zero_of_le him, minorIdeal_zero]

/-- Adjoin a zero column to a matrix. -/
def zeroColumnExtension (A : Matrix m n R) : Matrix m (Option n) R
  | i, some j => A i j
  | _, none => 0

private theorem minorIdeal_le_zeroColumnExtension (A : Matrix m n R) (q : ℕ) :
    minorIdeal A q ≤ minorIdeal (zeroColumnExtension A) q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let cols' : Fin q ↪ Option n := cols.trans Function.Embedding.some
  apply Ideal.subset_span
  refine ⟨rows, cols', ?_⟩
  unfold minor
  congr 1

private theorem minorIdeal_zeroColumnExtension_le (A : Matrix m n R) (q : ℕ) :
    minorIdeal (zeroColumnExtension A) q ≤ minorIdeal A q := by
  rw [minorIdeal]
  refine Ideal.span_le.2 ?_
  rintro a ⟨rows, cols, rfl⟩
  let B : _root_.Matrix (Fin q) (Fin q) R :=
    fun i j ↦ zeroColumnExtension A (rows i) (cols j)
  by_cases hc : none ∈ Set.range cols
  · rcases hc with ⟨ci, hci⟩
    have hzero (k : Fin q) : B k ci = 0 := by
      change zeroColumnExtension A (rows k) (cols ci) = 0
      rw [hci]
      rfl
    rw [show minor (zeroColumnExtension A) q rows cols = B.det from rfl,
      Matrix.det_eq_zero_of_column_eq_zero ci hzero]
    exact Ideal.zero_mem _
  · let colsA : Fin q ↪ n := dropNoneEmbedding cols hc
    have hminor : minor (zeroColumnExtension A) q rows cols =
        minor A q rows colsA := by
      unfold minor
      congr 1
      ext a b
      rw [← some_dropNoneEmbedding cols hc b]
      rfl
    rw [hminor]
    exact Ideal.subset_span ⟨rows, colsA, rfl⟩

/-- Adjoining a zero column does not change any determinantal ideal. -/
theorem minorIdeal_zeroColumnExtension (A : Matrix m n R) (q : ℕ) :
    minorIdeal (zeroColumnExtension A) q = minorIdeal A q :=
  le_antisymm (minorIdeal_zeroColumnExtension_le A q)
    (minorIdeal_le_zeroColumnExtension A q)

/-- If the requested minor size exceeds the number of rows, the determinantal ideal vanishes. -/
theorem minorIdeal_eq_bot_of_card_rows_lt (A : Matrix m n R) (q : ℕ)
    [Fintype m] (h : Fintype.card m < q) : minorIdeal A q = ⊥ := by
  have hempty : minorSet A q = ∅ := by
    apply Set.eq_empty_iff_forall_notMem.mpr
    intro a ha
    rcases ha with ⟨rows, _, _⟩
    have hc : q ≤ Fintype.card m := by
      simpa using Fintype.card_le_of_injective rows rows.injective
    exact (Nat.not_le_of_gt h) hc
  rw [minorIdeal, hempty, Ideal.span_empty]

/-- If the requested minor size exceeds the number of columns, the determinantal ideal
vanishes. -/
theorem minorIdeal_eq_bot_of_card_cols_lt (A : Matrix m n R) (q : ℕ)
    [Fintype n] (h : Fintype.card n < q) : minorIdeal A q = ⊥ := by
  have hempty : minorSet A q = ∅ := by
    apply Set.eq_empty_iff_forall_notMem.mpr
    intro a ha
    rcases ha with ⟨_, cols, _⟩
    have hc : q ≤ Fintype.card n := by
      simpa using Fintype.card_le_of_injective cols cols.injective
    exact (Nat.not_le_of_gt h) hc
  rw [minorIdeal, hempty, Ideal.span_empty]

/-- For a two-by-one matrix, the ideal of one-minors is generated by its two entries. -/
theorem minorIdeal_fin_two_fin_one_one (A : Matrix (Fin 2) (Fin 1) R) :
    minorIdeal A 1 = Ideal.span ({A 0 0, A 1 0} : Set R) := by
  apply congrArg Ideal.span
  ext a
  constructor
  · rintro ⟨rows, cols, h⟩
    have hcol : cols 0 = 0 := Subsingleton.elim _ _
    generalize hrow : rows 0 = r
    fin_cases r
    · left
      have ha : a = A (rows 0) (cols 0) := calc
        a = minor A 1 rows cols := h.symm
        _ = Matrix.det (fun i j ↦ A (rows i) (cols j)) := rfl
        _ = A (rows 0) (cols 0) := Matrix.det_fin_one _
      simpa [hrow, hcol] using ha
    · right
      have ha : a = A (rows 0) (cols 0) := calc
        a = minor A 1 rows cols := h.symm
        _ = Matrix.det (fun i j ↦ A (rows i) (cols j)) := rfl
        _ = A (rows 0) (cols 0) := Matrix.det_fin_one _
      simpa [hrow, hcol] using ha
  · rintro (rfl | rfl)
    · let rows : Fin 1 ↪ Fin 2 :=
        ⟨fun _ ↦ 0, fun _ _ _ ↦ Subsingleton.elim _ _⟩
      let cols : Fin 1 ↪ Fin 1 :=
        ⟨fun i ↦ i, fun _ _ h ↦ h⟩
      refine ⟨rows, cols, ?_⟩
      calc
        minor A 1 rows cols = A (rows 0) (cols 0) := Matrix.det_fin_one _
        _ = A 0 0 := rfl
    · let rows : Fin 1 ↪ Fin 2 :=
        ⟨fun _ ↦ 1, fun _ _ _ ↦ Subsingleton.elim _ _⟩
      let cols : Fin 1 ↪ Fin 1 :=
        ⟨fun i ↦ i, fun _ _ h ↦ h⟩
      refine ⟨rows, cols, ?_⟩
      calc
        minor A 1 rows cols = A (rows 0) (cols 0) := Matrix.det_fin_one _
        _ = A 1 0 := rfl

variable {n' : Type*} [Fintype n'] [DecidableEq n']

/-- The ideal of maximal minors of an identity matrix is the unit ideal. -/
theorem minorIdeal_one_card_eq_top :
    minorIdeal (1 : Matrix n' n' R) (Fintype.card n') = ⊤ := by
  classical
  rw [Ideal.eq_top_iff_one]
  let e : Fin (Fintype.card n') ≃ n' := (Fintype.equivFin n').symm
  apply Ideal.subset_span
  refine ⟨e.toEmbedding, e.toEmbedding, ?_⟩
  unfold minor
  change Matrix.det (fun i j ↦ if e i = e j then 1 else 0) = 1
  rw [show (fun i j ↦ if e i = e j then (1 : R) else 0) =
      (1 : Matrix (Fin (Fintype.card n')) (Fin (Fintype.card n')) R) by
    ext i j
    simp [Matrix.one_apply]]
  exact Matrix.det_one

end Matrix

namespace Module.Presentation

variable {A : Type u} [CommRing A]
variable {M : Type v} [AddCommGroup M] [Module A M]

/-- The relation matrix of a chosen presentation: generators index rows and relations index
columns. -/
def relationMatrix (P : Module.Presentation.{w, x} A M) : Matrix P.G P.R A :=
  fun g r ↦ P.relation r g

/-- The `i`th determinantal Fitting ideal attached to a chosen finite presentation.  If there
are `g` generators, it is generated by the `(g-i)`-minors of the relation matrix. -/
def fittingIdeal (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) : Ideal A :=
  Matrix.minorIdeal (relationMatrix P) (Fintype.card P.G - i)

/-- Once `i` is at least the number of chosen generators, the presentation Fitting ideal is
the unit ideal. -/
theorem fittingIdeal_eq_top_of_card_le (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) (h : Fintype.card P.G ≤ i) :
    fittingIdeal P i = ⊤ := by
  simp [fittingIdeal, Nat.sub_eq_zero_of_le h]

/-- If a finite presentation has fewer relations than generators, its zeroth Fitting ideal
vanishes. -/
theorem fittingIdeal_zero_eq_bot_of_card_relations_lt_generators
    (P : Module.Presentation.{w, x} A M) [Fintype P.G] [Fintype P.R]
    (h : Fintype.card P.R < Fintype.card P.G) : fittingIdeal P 0 = ⊥ := by
  rw [fittingIdeal, Nat.sub_zero]
  exact Matrix.minorIdeal_eq_bot_of_card_cols_lt (relationMatrix P) _ h

private theorem minor_max_smul_var_eq_zero
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G]
    (rows : Fin (Fintype.card P.G) ↪ P.G)
    (cols : Fin (Fintype.card P.G) ↪ P.R) (g : P.G) :
    Matrix.minor (relationMatrix P) (Fintype.card P.G) rows cols • P.var g = 0 := by
  classical
  have hrows : Function.Bijective rows :=
    (Fintype.bijective_iff_injective_and_card rows).mpr ⟨rows.injective, by simp⟩
  let e : Fin (Fintype.card P.G) ≃ P.G := Equiv.ofBijective rows hrows
  obtain ⟨i, rfl⟩ := e.surjective g
  let B : Matrix (Fin (Fintype.card P.G)) (Fin (Fintype.card P.G)) A :=
    fun i j ↦ relationMatrix P (e i) (cols j)
  let c : P.R →₀ A := ∑ j, Finsupp.single (cols j) (Matrix.adjugate B j i)
  have hsingle (j : Fin (Fintype.card P.G)) :
      P.map (Finsupp.single (cols j) (Matrix.adjugate B j i)) =
        Matrix.adjugate B j i • P.relation (cols j) := by
    have hs : Finsupp.single (cols j) (Matrix.adjugate B j i) =
        Matrix.adjugate B j i • Finsupp.single (cols j) 1 := by
      ext r
      simp
    calc
      P.map (Finsupp.single (cols j) (Matrix.adjugate B j i)) =
          P.map (Matrix.adjugate B j i • Finsupp.single (cols j) 1) := congrArg P.map hs
      _ = Matrix.adjugate B j i • P.map (Finsupp.single (cols j) 1) :=
        LinearMap.map_smul P.map _ _
      _ = Matrix.adjugate B j i • P.relation (cols j) := by rw [P.map_single]
  have hmap : P.map c = Finsupp.single (e i) B.det := by
    ext g
    obtain ⟨k, rfl⟩ := e.surjective g
    have hadj := congrArg (fun C : Matrix (Fin (Fintype.card P.G))
        (Fin (Fintype.card P.G)) A ↦ C k i) (Matrix.mul_adjugate B)
    change (∑ j, B k j * Matrix.adjugate B j i) =
      B.det * (1 : Matrix (Fin (Fintype.card P.G))
        (Fin (Fintype.card P.G)) A) k i at hadj
    change (P.map c) (e k) = (Finsupp.single (e i) B.det) (e k)
    rw [show P.map c = ∑ j, P.map
        (Finsupp.single (cols j) (Matrix.adjugate B j i)) by
      simp [c]]
    simp_rw [hsingle]
    simpa [B, relationMatrix, Matrix.one_apply,
      Finsupp.single_apply, mul_comm, eq_comm] using hadj
  have hz := P.toSolution.π_comp_map_apply c
  rw [hmap] at hz
  have hminor : Matrix.minor (relationMatrix P) (Fintype.card P.G) rows cols = B.det := by
    rfl
  rw [hminor]
  have hsingle : Finsupp.single (e i) B.det =
      B.det • Finsupp.single (e i) 1 := by
    ext g
    simp [Finsupp.single_apply]
  rw [hsingle, LinearMap.map_smul, P.toSolution.π_single] at hz
  exact hz

/-- Every maximal minor of a finite relation matrix annihilates the presented module. Thus the
zeroth Fitting ideal is contained in the module annihilator. -/
theorem fittingIdeal_zero_le_annihilator
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] :
    fittingIdeal P 0 ≤ Module.annihilator A M := by
  classical
  rw [fittingIdeal, Nat.sub_zero, Matrix.minorIdeal, Ideal.span_le]
  rintro a ⟨rows, cols, rfl⟩
  change Matrix.minor (relationMatrix P) (Fintype.card P.G) rows cols ∈
    Module.annihilator A M
  rw [Module.mem_annihilator]
  intro m
  obtain ⟨p, rfl⟩ := P.toIsPresentation.surjective_π m
  induction p using Finsupp.induction with
  | zero => simp
  | single_add g b p _ _ ih =>
      rw [map_add, smul_add, ih, add_zero]
      have hs : Finsupp.single g b = b • Finsupp.single g 1 := by
        ext h
        simp
      rw [hs, LinearMap.map_smul, P.toSolution.π_single]
      have hz := congrArg (fun z : M ↦ b • z)
        (minor_max_smul_var_eq_zero P rows cols g)
      simpa only [smul_smul, mul_comm, smul_zero] using hz

/-- If the presented module is zero, its zeroth Fitting ideal is the unit ideal. -/
theorem fittingIdeal_zero_eq_top_of_subsingleton
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R]
    [Subsingleton M] : fittingIdeal P 0 = ⊤ := by
  classical
  have hspan : Submodule.span A (Set.range P.relation) = ⊤ := by
    rw [← P.toIsPresentation.ker_π, LinearMap.ker_eq_top]
    exact Subsingleton.elim _ _
  have hrange : LinearMap.range P.map = ⊤ := by
    rw [P.range_map, hspan]
  have hsurj : Function.Surjective P.map := LinearMap.range_eq_top.mp hrange
  have hpre (g : P.G) : ∃ r : P.R →₀ A, P.map r = Finsupp.single g 1 :=
    hsurj (Finsupp.single g 1)
  choose r hr using hpre
  let V : Matrix P.R P.G A := fun a g ↦ r g a
  have hmul : relationMatrix P * V = 1 := by
    ext g h
    have heq := congrArg (fun z : P.G →₀ A ↦ z g) (hr h)
    change (∑ x, (P.relation x) g * (r h) x) = if g = h then 1 else 0
    simpa [Module.Relations.map, Finsupp.linearCombination_apply,
      Finsupp.sum_fintype, mul_comm, Finsupp.single_apply, eq_comm] using heq
  unfold fittingIdeal
  rw [Nat.sub_zero]
  apply le_antisymm le_top
  rw [← Matrix.minorIdeal_one_card_eq_top (R := A) (n' := P.G), ← hmul]
  exact Matrix.minorIdeal_mul_right_le (relationMatrix P) V _

/-- A finite presentation has unit zeroth Fitting ideal only if its module is zero. -/
theorem subsingleton_of_fittingIdeal_zero_eq_top
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R]
    (h : fittingIdeal P 0 = ⊤) : Subsingleton M := by
  apply (Module.annihilator_eq_top_iff (R := A) (M := M)).mp
  apply top_unique
  rw [← h]
  exact fittingIdeal_zero_le_annihilator P

/-- For a finitely presented module, the zeroth Fitting ideal is the unit ideal exactly when the
module is zero. -/
theorem fittingIdeal_zero_eq_top_iff
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] :
    fittingIdeal P 0 = ⊤ ↔ Subsingleton M := by
  constructor
  · exact subsingleton_of_fittingIdeal_zero_eq_top P
  · intro h
    let _ : Subsingleton M := h
    exact fittingIdeal_zero_eq_top_of_subsingleton P

/-- Every annihilator element raised to the number of chosen generators belongs to the zeroth
Fitting ideal. Together with `fittingIdeal_zero_le_annihilator`, this is the determinant trick
relating the two ideals up to radical. -/
theorem annihilator_element_pow_card_generators_mem_fittingIdeal_zero
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (a : A)
    (ha : a ∈ Module.annihilator A M) :
    a ^ Fintype.card P.G ∈ fittingIdeal P 0 := by
  classical
  have hrange : LinearMap.range P.map = LinearMap.ker P.toSolution.π := by
    rw [P.range_map, ← P.toIsPresentation.ker_π]
  have hpre (g : P.G) : ∃ r : P.R →₀ A,
      P.map r = a • Finsupp.single g 1 := by
    apply LinearMap.mem_range.mp
    rw [hrange, LinearMap.mem_ker, LinearMap.map_smul, P.toSolution.π_single]
    exact Module.mem_annihilator.mp ha (P.var g)
  choose r hr using hpre
  let V : Matrix P.R P.G A := fun z g ↦ r g z
  have hmul : relationMatrix P * V = a • 1 := by
    ext g h
    have heq := congrArg (fun z : P.G →₀ A ↦ z g) (hr h)
    change (∑ x, (P.relation x) g * (r h) x) =
      (a • (1 : Matrix P.G P.G A)) g h
    simpa [Module.Relations.map, Finsupp.linearCombination_apply,
      Finsupp.sum_fintype, Matrix.one_apply, Finsupp.single_apply,
      mul_comm, eq_comm] using heq
  have hmem : a ^ Fintype.card P.G ∈
      Matrix.minorIdeal (relationMatrix P * V) (Fintype.card P.G) := by
    let e : Fin (Fintype.card P.G) ≃ P.G := (Fintype.equivFin P.G).symm
    apply Ideal.subset_span
    refine ⟨e.toEmbedding, e.toEmbedding, ?_⟩
    rw [hmul]
    unfold Matrix.minor
    change Matrix.det (fun i j ↦
      (a • (1 : Matrix P.G P.G A)) (e i) (e j)) = a ^ Fintype.card P.G
    rw [show (fun i j ↦ (a • (1 : Matrix P.G P.G A)) (e i) (e j)) =
        a • (1 : Matrix (Fin (Fintype.card P.G)) (Fin (Fintype.card P.G)) A) by
      ext i j
      simp [Matrix.one_apply]]
    rw [Matrix.det_smul, Matrix.det_one, mul_one]
    simp
  change a ^ Fintype.card P.G ∈
    Matrix.minorIdeal (relationMatrix P) (Fintype.card P.G)
  exact Matrix.minorIdeal_mul_right_le (relationMatrix P) V _ hmem

/-- The zeroth Fitting ideal and the module annihilator have the same radical. -/
theorem radical_fittingIdeal_zero_eq_radical_annihilator
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] :
    (fittingIdeal P 0).radical = (Module.annihilator A M).radical := by
  apply le_antisymm
  · exact Ideal.radical_mono (fittingIdeal_zero_le_annihilator P)
  · rw [Ideal.radical_le_radical_iff]
    intro a ha
    exact ⟨Fintype.card P.G,
      annihilator_element_pow_card_generators_mem_fittingIdeal_zero P a ha⟩

/-- The support of a finitely presented module is exactly the zero locus of its zeroth Fitting
ideal. This is the presentation-level support theorem needed by affine singular-locus
constructions. -/
theorem support_eq_zeroLocus_fittingIdeal_zero
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] :
    Module.support A M = PrimeSpectrum.zeroLocus (fittingIdeal P 0) := by
  let _ : Module.Finite A M := P.finite
  calc
    Module.support A M = PrimeSpectrum.zeroLocus (Module.annihilator A M) :=
      Module.support_eq_zeroLocus
    _ = PrimeSpectrum.zeroLocus (Module.annihilator A M).radical :=
      (PrimeSpectrum.zeroLocus_radical _).symm
    _ = PrimeSpectrum.zeroLocus (fittingIdeal P 0).radical := by
      rw [radical_fittingIdeal_zero_eq_radical_annihilator P]
    _ = PrimeSpectrum.zeroLocus (fittingIdeal P 0) :=
      PrimeSpectrum.zeroLocus_radical _

/-- Mapping coefficients in the relation matrix maps its determinantal Fitting ideal exactly.
This is the algebraic equality used by localization and base-change proofs. -/
theorem map_fittingIdeal_relationMatrix
    (P : Module.Presentation.{w, x} A M) [Fintype P.G] [Fintype P.R]
    {B : Type*} [CommRing B] (f : A →+* B) (i : ℕ) :
    Ideal.map f (fittingIdeal P i) =
      Matrix.minorIdeal (fun g r ↦ f (relationMatrix P g r))
        (Fintype.card P.G - i) := by
  exact Matrix.map_minorIdeal f (relationMatrix P) _

/-- Merely relabelling the generators and relations of a finite presentation leaves its
determinantal Fitting ideals unchanged.  This is the first presentation-independence move; basis
changes and stabilization by trivial generator-relation pairs are treated separately. -/
theorem fittingIdeal_eq_of_relationMatrix_reindex
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (eG : P.G ≃ Q.G) (eR : P.R ≃ Q.R)
    (hmatrix : relationMatrix Q = Matrix.reindex eG eR (relationMatrix P)) (i : ℕ) :
    fittingIdeal P i = fittingIdeal Q i := by
  unfold fittingIdeal
  rw [hmatrix, ← Matrix.minorIdeal_reindex (relationMatrix P)
    (Fintype.card P.G - i) eG eR]
  rw [Fintype.card_congr eG]

/-- Invertible changes of bases among the generators and relations leave every finite-presentation
Fitting ideal unchanged. The hypotheses give explicit inverses for the two basis-change matrices. -/
theorem fittingIdeal_eq_of_relationMatrix_basisChange
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    [DecidableEq P.G] [DecidableEq P.R]
    (eG : P.G ≃ Q.G) (eR : P.R ≃ Q.R)
    (UG VG : Matrix P.G P.G A) (hG : VG * UG = 1)
    (UR VR : Matrix P.R P.R A) (hR : UR * VR = 1)
    (hmatrix : relationMatrix Q = Matrix.reindex eG eR
      ((UG * relationMatrix P) * UR)) (i : ℕ) :
    fittingIdeal P i = fittingIdeal Q i := by
  unfold fittingIdeal
  rw [hmatrix, Matrix.minorIdeal_reindex, ← Fintype.card_congr eG,
    Matrix.minorIdeal_mul_right_eq_of_rightInverse _ UR VR hR,
    Matrix.minorIdeal_mul_left_eq_of_leftInverse UG VG hG]

/-- Adjoining one trivial generator and one matching relation leaves every presentation Fitting
ideal unchanged. The equivalences identify the new generator and relation with the `none` indices
of `Matrix.unitStabilization`. -/
theorem fittingIdeal_eq_of_relationMatrix_unitStabilization
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (eG : Option P.G ≃ Q.G) (eR : Option P.R ≃ Q.R)
    (hmatrix : relationMatrix Q = Matrix.reindex eG eR
      (Matrix.unitStabilization (relationMatrix P))) (i : ℕ) :
    fittingIdeal P i = fittingIdeal Q i := by
  have hcard : Fintype.card Q.G = Fintype.card P.G + 1 := by
    rw [← Fintype.card_congr eG]
    simp
  by_cases hi : i ≤ Fintype.card P.G
  · unfold fittingIdeal
    rw [hmatrix, Matrix.minorIdeal_reindex, hcard]
    have hsub : Fintype.card P.G + 1 - i = (Fintype.card P.G - i) + 1 := by
      omega
    rw [hsub, Matrix.minorIdeal_unitStabilization]
  · have hPi : Fintype.card P.G ≤ i := Nat.le_of_lt (lt_of_not_ge hi)
    have hQi : Fintype.card Q.G ≤ i := by
      rw [hcard]
      omega
    rw [fittingIdeal_eq_top_of_card_le P i hPi,
      fittingIdeal_eq_top_of_card_le Q i hQi]

/-- Adjoining a redundant zero relation leaves every presentation Fitting ideal unchanged. -/
theorem fittingIdeal_eq_of_relationMatrix_zeroColumnExtension
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (eG : P.G ≃ Q.G) (eR : Option P.R ≃ Q.R)
    (hmatrix : relationMatrix Q = Matrix.reindex eG eR
      (Matrix.zeroColumnExtension (relationMatrix P))) (i : ℕ) :
    fittingIdeal P i = fittingIdeal Q i := by
  unfold fittingIdeal
  rw [hmatrix, Matrix.minorIdeal_reindex, ← Fintype.card_congr eG,
    Matrix.minorIdeal_zeroColumnExtension]

/-- Finite presentations using equivalent generator bases with the same images in the presented
module have the same Fitting ideals, independently of their chosen finite relation families.

The presentation axioms identify both relation spans with the kernel of the common free-module
surjection. Thus each relation matrix factors through the other on the right, and mutual matrix
factorization gives equality of all determinantal ideals. -/
theorem fittingIdeal_eq_of_same_generators
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (eG : P.G ≃ Q.G)
    (hvar : ∀ g : P.G, P.var g = Q.var (eG g)) (i : ℕ) :
    fittingIdeal P i = fittingIdeal Q i := by
  let E : (P.G →₀ A) ≃ₗ[A] (Q.G →₀ A) := Finsupp.domLCongr eG
  have hpi : Q.toSolution.π.comp E.toLinearMap = P.toSolution.π := by
    ext g
    simp [E, hvar]
  have hPspan : LinearMap.ker P.toSolution.π =
      Submodule.span A (Set.range P.relation) :=
    (P.toSolution.isPresentation_iff.mp P.toIsPresentation).2
  have hQspan : LinearMap.ker Q.toSolution.π =
      Submodule.span A (Set.range Q.relation) :=
    (Q.toSolution.isPresentation_iff.mp Q.toIsPresentation).2
  have hPrange : LinearMap.range P.map = LinearMap.ker P.toSolution.π := by
    rw [P.range_map, hPspan]
  have hQrange : LinearMap.range Q.map = LinearMap.ker Q.toSolution.π := by
    rw [Q.range_map, hQspan]
  have hPmem (r : P.R) : E (P.relation r) ∈ LinearMap.range Q.map := by
    rw [hQrange, LinearMap.mem_ker]
    change (Q.toSolution.π.comp E.toLinearMap) (P.relation r) = 0
    rw [hpi]
    exact P.toSolution.π_relation r
  have hQmem (r : Q.R) : E.symm (Q.relation r) ∈ LinearMap.range P.map := by
    rw [hPrange, LinearMap.mem_ker]
    have hz := Q.toSolution.π_relation r
    calc
      P.toSolution.π (E.symm (Q.relation r)) =
          (Q.toSolution.π.comp E.toLinearMap) (E.symm (Q.relation r)) := by
            rw [hpi]
      _ = Q.toSolution.π (Q.relation r) := by simp
      _ = 0 := hz
  choose u hu using hPmem
  choose v hv using hQmem
  let B : Matrix P.G Q.R A := fun g r ↦ relationMatrix Q (eG g) r
  let U : Matrix Q.R P.R A := fun r s ↦ u s r
  let V : Matrix P.R Q.R A := fun r s ↦ v s r
  have hmatP : relationMatrix P = B * U := by
    ext g r
    have h := congrArg (fun z : Q.G →₀ A ↦ z (eG g)) (hu r)
    change (P.relation r) g = ∑ k, (Q.relation k) (eG g) * (u r) k
    simpa [Module.Relations.map, E, Finsupp.linearCombination_apply,
      Finsupp.sum_fintype, mul_comm] using h.symm
  have hmatQ : B = relationMatrix P * V := by
    ext g r
    have h := congrArg (fun z : P.G →₀ A ↦ z g) (hv r)
    change (Q.relation r) (eG g) = ∑ k, (P.relation k) g * (v r) k
    simpa [Module.Relations.map, E, Finsupp.linearCombination_apply,
      Finsupp.sum_fintype, mul_comm] using h.symm
  unfold fittingIdeal
  rw [← Fintype.card_congr eG]
  calc
    Matrix.minorIdeal (relationMatrix P) (Fintype.card P.G - i) =
        Matrix.minorIdeal B (Fintype.card P.G - i) :=
      Matrix.minorIdeal_eq_of_mutual_right_factorization
        (relationMatrix P) B U V hmatP hmatQ _
    _ = Matrix.minorIdeal (relationMatrix Q) (Fintype.card P.G - i) := by
      rw [show B = Matrix.reindex eG.symm (Equiv.refl Q.R) (relationMatrix Q) by rfl,
        Matrix.minorIdeal_reindex]

/-! ### Independence of arbitrary finite presentations -/

private theorem linearCombination_sumElim {G N : Type*}
    (f : G → M) (g : N → M) (x : G →₀ A) (y : N →₀ A) :
    Finsupp.linearCombination A (Sum.elim f g) (x.sumElim y) =
      Finsupp.linearCombination A f x + Finsupp.linearCombination A g y := by
  rw [Finsupp.sumElim_eq_add, map_add,
    Finsupp.linearCombination_mapDomain, Finsupp.linearCombination_mapDomain]
  rfl

private theorem linearCombination_linkRelations {G N : Type*}
    [Finite N] (a : N → G →₀ A) (q : N →₀ A) :
    Finsupp.linearCombination A
        (fun n ↦ (-a n).sumElim (Finsupp.single n 1)) q =
      (-(Finsupp.linearCombination A a q)).sumElim q := by
  classical
  let _ := Fintype.ofFinite N
  ext x
  rcases x with g | n
  · simp [Finsupp.linearCombination_apply, Finsupp.sum_fintype]
  · simp [Finsupp.linearCombination_apply, Finsupp.sum_fintype,
      Finsupp.single_apply]

private theorem linearCombination_oldRelations {G N T : Type*}
    [Finite T] (r : T → G →₀ A) (c : T →₀ A) :
    Finsupp.linearCombination A (fun t ↦ (r t).sumElim (0 : N →₀ A)) c =
      (Finsupp.linearCombination A r c).sumElim 0 := by
  classical
  let _ := Fintype.ofFinite T
  ext x
  rcases x with g | n <;>
    simp [Finsupp.linearCombination_apply, Finsupp.sum_fintype]

/-- Relations for adjoining a finite family of new generators. Each new generator is tied to a
chosen linear combination of the old generators. -/
abbrev adjoinGeneratorsRelations (P : Module.Presentation.{w, x} A M)
    (N : Type*) (a : N → P.G →₀ A) : Module.Relations A where
  G := P.G ⊕ N
  R := N ⊕ P.R
  relation
    | Sum.inl n => (-a n).sumElim (Finsupp.single n 1)
    | Sum.inr r => (P.relation r).sumElim 0

private theorem adjoinGeneratorsRelations_map_sumElim
    (P : Module.Presentation.{w, x} A M)
    (N : Type*) [Finite P.R] [Finite N]
    (a : N → P.G →₀ A) (q : N →₀ A) (r : P.R →₀ A) :
    (adjoinGeneratorsRelations P N a).map (q.sumElim r) =
      (-(Finsupp.linearCombination A a q) + P.map r).sumElim q := by
  unfold Module.Relations.map
  dsimp only [adjoinGeneratorsRelations]
  rw [show (fun x : N ⊕ P.R ↦ match x with
      | Sum.inl n => (-a n).sumElim (Finsupp.single n 1)
      | Sum.inr r => (P.relation r).sumElim 0) =
      Sum.elim
        (fun n ↦ (-a n).sumElim (Finsupp.single n 1))
        (fun r ↦ (P.relation r).sumElim 0) by
          funext x
          rcases x with x | x <;> rfl]
  rw [linearCombination_sumElim,
    linearCombination_linkRelations,
    linearCombination_oldRelations]
  change (-(Finsupp.linearCombination A a q)).sumElim q +
      (P.map r).sumElim 0 = _
  ext x
  rcases x with x | x <;> simp [Module.Relations.map]

/-- The evident solution after adjoining generators whose values are the specified old-generator
linear combinations. -/
def adjoinGeneratorsSolution (P : Module.Presentation.{w, x} A M)
    (N : Type*) (v : N → M) (a : N → P.G →₀ A)
    (ha : ∀ n, P.toSolution.π (a n) = v n) :
    (adjoinGeneratorsRelations P N a).Solution M where
  var := Sum.elim P.var v
  linearCombination_var_relation := by
    intro r
    rcases r with n | r
    · change Finsupp.linearCombination A (Sum.elim P.var v)
          ((-a n).sumElim (Finsupp.single n 1)) = 0
      rw [linearCombination_sumElim]
      rw [map_neg, Finsupp.linearCombination_single, one_smul]
      change -P.toSolution.π (a n) + v n = 0
      rw [ha]
      simp
    · change Finsupp.linearCombination A (Sum.elim P.var v)
          ((P.relation r).sumElim 0) = 0
      rw [linearCombination_sumElim]
      rw [map_zero, add_zero]
      exact P.toSolution.π_relation r

private theorem adjoinGeneratorsSolution_pi_sumElim
    (P : Module.Presentation.{w, x} A M)
    (N : Type*) (v : N → M) (a : N → P.G →₀ A)
    (ha : ∀ n, P.toSolution.π (a n) = v n)
    (p : P.G →₀ A) (q : N →₀ A) :
    (adjoinGeneratorsSolution P N v a ha).π (p.sumElim q) =
      P.toSolution.π p + Finsupp.linearCombination A v q := by
  change Finsupp.linearCombination A (Sum.elim P.var v) (p.sumElim q) = _
  rw [linearCombination_sumElim]
  rfl

/-- Adjoin any finite family of generators to a finite presentation, together with relations
identifying them with chosen old-generator expressions. The kernel computation proves that this
is genuinely another presentation of the same module. -/
abbrev adjoinGenerators (P : Module.Presentation.{w, x} A M)
    (N : Type*) [Fintype P.G] [Fintype P.R] [Fintype N]
    (v : N → M) (a : N → P.G →₀ A)
    (ha : ∀ n, P.toSolution.π (a n) = v n) : Module.Presentation A M where
  toRelations := adjoinGeneratorsRelations P N a
  toSolution := adjoinGeneratorsSolution P N v a ha
  toIsPresentation := by
    apply (adjoinGeneratorsSolution P N v a ha).isPresentation_mk
    · rw [← (adjoinGeneratorsSolution P N v a ha).surjective_π_iff_span_eq_top]
      intro z
      obtain ⟨p, hp⟩ := P.surjective_π z
      refine ⟨p.sumElim 0, ?_⟩
      rw [adjoinGeneratorsSolution_pi_sumElim]
      simpa using hp
    · apply le_antisymm
      · intro z hz
        rw [← (adjoinGeneratorsRelations P N a).range_map]
        let E : (P.G ⊕ N →₀ A) ≃ₗ[A] (P.G →₀ A) × (N →₀ A) :=
          Finsupp.sumFinsuppLEquivProdFinsupp A
        let p : P.G →₀ A := (E z).1
        let q : N →₀ A := (E z).2
        let c : P.G →₀ A := Finsupp.linearCombination A a q
        have hcomb : P.toSolution.π c = Finsupp.linearCombination A v q := by
          change (P.toSolution.π.comp (Finsupp.linearCombination A a)) q =
            Finsupp.linearCombination A v q
          have heq : P.toSolution.π.comp (Finsupp.linearCombination A a) =
              Finsupp.linearCombination A v := by
            ext n
            simp [ha]
          rw [heq]
        have hz' : P.toSolution.π (p + c) = 0 := by
          have hz0 : (adjoinGeneratorsSolution P N v a ha).π z = 0 := hz
          have hzsum : z = p.sumElim q := by
            apply E.injective
            simp [E, p, q]
          rw [hzsum, adjoinGeneratorsSolution_pi_sumElim] at hz0
          rw [map_add, hcomb]
          exact hz0
        have hpc : p + c ∈ LinearMap.range P.map := by
          rw [P.range_map, ← P.ker_π]
          exact hz'
        obtain ⟨r, hr⟩ := hpc
        refine ⟨q.sumElim r, ?_⟩
        have hmap : (adjoinGeneratorsRelations P N a).map (q.sumElim r) =
            (-c + P.map r).sumElim q :=
          adjoinGeneratorsRelations_map_sumElim P N a q r
        rw [hmap, hr]
        have hzsum : z = p.sumElim q := by
          apply E.injective
          simp [E, p, q]
        rw [hzsum]
        congr 2
        abel
      · exact (adjoinGeneratorsSolution P N v a ha).span_relation_le_ker_π

theorem adjoinGenerators_relationMatrix
    (P : Module.Presentation.{w, x} A M)
    (N : Type*) [Fintype P.G] [Fintype P.R] [Fintype N] [DecidableEq N]
    (v : N → M) (a : N → P.G →₀ A)
    (ha : ∀ n, P.toSolution.π (a n) = v n) :
    relationMatrix (adjoinGenerators P N v a ha) =
      Matrix.generatorExtension (relationMatrix P) (fun n g ↦ a n g) := by
  classical
  ext g r
  rcases g with g | g <;> rcases r with r | r <;>
    simp [relationMatrix, adjoinGenerators, adjoinGeneratorsSolution,
      adjoinGeneratorsRelations, Matrix.generatorExtension, Finsupp.single_apply, eq_comm]

/-- Adjoining any finite family of generators together with matching relations preserves every
Fitting ideal. -/
theorem fittingIdeal_adjoinGenerators
    (P : Module.Presentation.{w, x} A M)
    (N : Type*) [Fintype P.G] [Fintype P.R] [Fintype N]
    (v : N → M) (a : N → P.G →₀ A)
    (ha : ∀ n, P.toSolution.π (a n) = v n) (i : ℕ) :
    fittingIdeal (adjoinGenerators P N v a ha) i = fittingIdeal P i := by
  classical
  unfold fittingIdeal
  rw [adjoinGenerators_relationMatrix]
  have hcard : Fintype.card (adjoinGenerators P N v a ha).G =
      Fintype.card P.G + Fintype.card N := by
    change Fintype.card (P.G ⊕ N) = _
    simp
  rw [hcard]
  exact Matrix.minorIdeal_generatorExtension_fitting _ _ _

/-- The determinantal Fitting ideals of a finitely presented module are independent of the chosen
finite presentation. Both presentations are enlarged to the common union of their generator
families, after which `fittingIdeal_eq_of_same_generators` compares their relation kernels. -/
theorem fittingIdeal_eq
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (i : ℕ) : fittingIdeal P i = fittingIdeal Q i := by
  have hQ (q : Q.G) : ∃ a : P.G →₀ A, P.toSolution.π a = Q.var q :=
    P.surjective_π (Q.var q)
  choose a ha using hQ
  have hP (p : P.G) : ∃ b : Q.G →₀ A, Q.toSolution.π b = P.var p :=
    Q.surjective_π (P.var p)
  choose b hb using hP
  let P' := adjoinGenerators P Q.G Q.var a ha
  let Q' := adjoinGenerators Q P.G P.var b hb
  calc
    fittingIdeal P i = fittingIdeal P' i :=
      (fittingIdeal_adjoinGenerators P Q.G Q.var a ha i).symm
    _ = fittingIdeal Q' i := by
      apply fittingIdeal_eq_of_same_generators P' Q' (Equiv.sumComm P.G Q.G)
      intro g
      rcases g with g | g <;> rfl
    _ = fittingIdeal Q i := fittingIdeal_adjoinGenerators Q P.G P.var b hb i

/-! ### Affine ideal-sheaf realization -/

/-- A presentation Fitting ideal transported to global sections of `Spec A`. -/
def fittingIdealTop (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) : Ideal Γ(Spec (.of A), ⊤) :=
  (fittingIdeal P i).map (Scheme.ΓSpecIso (.of A)).inv.hom

/-- The quasi-coherent ideal sheaf on `Spec A` associated to a presentation Fitting ideal. -/
def fittingIdealSheaf (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) : (Spec (.of A)).IdealSheafData :=
  Scheme.IdealSheafData.ofIdealTop (fittingIdealTop P i)

/-- The ideal on global sections is independent of the chosen finite presentation. -/
theorem fittingIdealTop_eq
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (i : ℕ) : fittingIdealTop P i = fittingIdealTop Q i := by
  unfold fittingIdealTop
  rw [fittingIdeal_eq P Q i]

/-- The affine ideal sheaf attached to a finite presentation is presentation-independent. -/
theorem fittingIdealSheaf_eq
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (i : ℕ) : fittingIdealSheaf P i = fittingIdealSheaf Q i := by
  unfold fittingIdealSheaf
  rw [fittingIdealTop_eq P Q i]

/-- Transporting the global sections of the Fitting ideal sheaf back to `A` recovers the
original determinantal ideal. -/
theorem map_fittingIdealTop (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) :
    (fittingIdealTop P i).map (Scheme.ΓSpecIso (.of A)).hom.hom = fittingIdeal P i := by
  rw [fittingIdealTop, Ideal.map_map]
  have hcomp : (Scheme.ΓSpecIso (.of A)).hom.hom.comp
      (Scheme.ΓSpecIso (.of A)).inv.hom = RingHom.id A := by
    exact congrArg CommRingCat.Hom.hom (Scheme.ΓSpecIso (.of A)).inv_hom_id
  rw [hcomp, Ideal.map_id]

/-- On every affine open, the Fitting ideal sheaf is the extension of its global Fitting
ideal.  Mathlib's restriction map is a localization map for affine opens, so this is the
scheme-theoretic localization statement. -/
@[simp]
theorem fittingIdealSheaf_ideal (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) (U : (Spec (.of A)).affineOpens) :
    (fittingIdealSheaf P i).ideal U =
      Ideal.map ((Spec (.of A)).presheaf.map (homOfLE (show U.1 ≤ ⊤ from le_top)).op).hom
        (fittingIdealTop P i) := by
  exact Scheme.IdealSheafData.ofIdealTop_ideal _ _

@[simp]
theorem fittingIdealSheaf_ideal_top (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) :
    (fittingIdealSheaf P i).ideal ⟨⊤, isAffineOpen_top _⟩ = fittingIdealTop P i := by
  simp [fittingIdealSheaf]

/-- The top ideal of the sheaf recovers the original presentation Fitting ideal after the
canonical `Γ(Spec A) ≅ A` identification. -/
theorem map_fittingIdealSheaf_ideal_top (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) :
    ((fittingIdealSheaf P i).ideal ⟨⊤, isAffineOpen_top _⟩).map
      (Scheme.ΓSpecIso (.of A)).hom.hom = fittingIdeal P i := by
  rw [fittingIdealSheaf_ideal_top, map_fittingIdealTop]

/-- The support of the affine Fitting ideal sheaf is its scheme-theoretic zero locus. -/
@[simp]
theorem fittingIdealSheaf_support (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) :
    ((fittingIdealSheaf P i).support : Set (Spec (.of A))) =
      (Spec (.of A)).zeroLocus (fittingIdealTop P i : Set Γ(Spec (.of A), ⊤)) := by
  exact Scheme.IdealSheafData.coe_support_ofIdealTop _

end Module.Presentation

namespace AlgebraPresentation

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]
variable {ι : Type w} {σ : Type x}

/-- The differential presentation has the same generator type as the algebra presentation. -/
noncomputable instance differentialsGeneratorFintype
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype ι] :
    Fintype P.differentials.G :=
  Fintype.ofEquiv ι (Equiv.cast (by change ι = ι; rfl))

/-- The differential presentation has the same relation type as the algebra presentation. -/
noncomputable instance differentialsRelationFintype
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype σ] :
    Fintype P.differentials.R :=
  Fintype.ofEquiv σ (Equiv.cast (by change σ = σ; rfl))

@[simp]
theorem card_differentials_generators
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype ι] :
    Fintype.card P.differentials.G = Fintype.card ι := by
  have e : ι ≃ P.differentials.G := Equiv.cast (by change ι = ι; rfl)
  exact (Fintype.card_congr e).symm

@[simp]
theorem card_differentials_relations
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype σ] :
    Fintype.card P.differentials.R = Fintype.card σ := by
  have e : σ ≃ P.differentials.R := Equiv.cast (by change σ = σ; rfl)
  exact (Fintype.card_congr e).symm

/-- The `i`th Fitting ideal of Kähler differentials computed from a chosen finite algebra
presentation.  For `i = 0`, this is the usual Jacobian/Fitting ideal cutting out the
non-smooth locus in the finite-presentation setting. -/
def differentialFittingIdeal (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) : Ideal S :=
  Module.Presentation.fittingIdeal P.differentials i

/-- Differential Fitting ideals are independent of the chosen finite algebra presentation,
because both differential presentations present the intrinsic module of Kähler differentials. -/
theorem differentialFittingIdeal_eq
    {i₁ : Type w} {s₁ : Type x} {i₂ s₂ : Type*}
    (P : _root_.Algebra.Presentation R S i₁ s₁)
    (Q : _root_.Algebra.Presentation R S i₂ s₂)
    [Fintype i₁] [Fintype s₁] [Fintype i₂] [Fintype s₂]
    (i : ℕ) : differentialFittingIdeal P i = differentialFittingIdeal Q i :=
  Module.Presentation.fittingIdeal_eq P.differentials Q.differentials i

/-- The zeroth differential Fitting ideal is the unit ideal exactly when the algebra is formally
unramified. This identifies the determinant criterion with the intrinsic vanishing of Kähler
differentials, independently of the chosen finite algebra presentation. -/
theorem differentialFittingIdeal_zero_eq_top_iff_formallyUnramified
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] :
    differentialFittingIdeal P 0 = ⊤ ↔ _root_.Algebra.FormallyUnramified R S := by
  rw [differentialFittingIdeal,
    Module.Presentation.fittingIdeal_zero_eq_top_iff,
    _root_.Algebra.formallyUnramified_iff]

/-- The support of the intrinsic Kähler-differential module is exactly the zero locus of the
zeroth differential Fitting ideal. -/
theorem support_kaehlerDifferential_eq_zeroLocus_differentialFittingIdeal_zero
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] :
    Module.support S Ω[S⁄R] =
      PrimeSpectrum.zeroLocus (differentialFittingIdeal P 0) :=
  Module.Presentation.support_eq_zeroLocus_fittingIdeal_zero P.differentials

/-- The affine formally-unramified locus is the complement of the zeroth differential Fitting
zero locus. This turns the determinant construction into the intrinsic pointwise locus. -/
theorem unramifiedLocus_eq_compl_zeroLocus_differentialFittingIdeal_zero
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] :
    _root_.Algebra.unramifiedLocus R S =
      (PrimeSpectrum.zeroLocus (differentialFittingIdeal P 0))ᶜ := by
  rw [_root_.Algebra.unramifiedLocus_eq_compl_support,
    support_kaehlerDifferential_eq_zeroLocus_differentialFittingIdeal_zero P]

/-- The differential Fitting ideal on the global sections of `Spec S`. -/
abbrev differentialFittingIdealTop (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) : Ideal Γ(Spec (.of S), ⊤) :=
  Module.Presentation.fittingIdealTop P.differentials i

/-- The affine ideal sheaf associated to the `i`th differential Fitting ideal. -/
abbrev differentialFittingIdealSheaf (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) : (Spec (.of S)).IdealSheafData :=
  Module.Presentation.fittingIdealSheaf P.differentials i

/-- On an arbitrary affine open of `Spec S`, the differential Fitting ideal is obtained by
localizing its global determinantal ideal. -/
@[simp]
theorem differentialFittingIdealSheaf_ideal
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) (U : (Spec (.of S)).affineOpens) :
    (differentialFittingIdealSheaf P i).ideal U =
      Ideal.map ((Spec (.of S)).presheaf.map (homOfLE (show U.1 ≤ ⊤ from le_top)).op).hom
        (differentialFittingIdealTop P i) := by
  exact Module.Presentation.fittingIdealSheaf_ideal P.differentials i U

/-- The sheafified differential Fitting ideal recovers the original Jacobian/determinantal
ideal on global sections. -/
theorem map_differentialFittingIdealSheaf_ideal_top
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) :
    ((differentialFittingIdealSheaf P i).ideal ⟨⊤, isAffineOpen_top _⟩).map
      (Scheme.ΓSpecIso (.of S)).hom.hom = differentialFittingIdeal P i := by
  exact Module.Presentation.map_fittingIdealSheaf_ideal_top P.differentials i

/-- The support of the differential Fitting ideal sheaf is its affine zero locus. -/
@[simp]
theorem differentialFittingIdealSheaf_support
    (P : _root_.Algebra.Presentation R S ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) :
    ((differentialFittingIdealSheaf P i).support : Set (Spec (.of S))) =
      (Spec (.of S)).zeroLocus
        (differentialFittingIdealTop P i : Set Γ(Spec (.of S), ⊤)) := by
  exact Module.Presentation.fittingIdealSheaf_support P.differentials i

/-- The differential Fitting ideal is the unit ideal above the number of algebra generators. -/
theorem differentialFittingIdeal_eq_top_of_card_le
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype ι] [Fintype σ]
    (i : ℕ) (h : Fintype.card ι ≤ i) : differentialFittingIdeal P i = ⊤ := by
  exact Module.Presentation.fittingIdeal_eq_top_of_card_le P.differentials i (by simpa using h)

/-- If a chosen algebra presentation has fewer relations than generators, the zeroth
differential Fitting ideal vanishes. -/
theorem differentialFittingIdeal_zero_eq_bot_of_card_relations_lt_generators
    (P : _root_.Algebra.Presentation R S ι σ) [Fintype ι] [Fintype σ]
    (h : Fintype.card σ < Fintype.card ι) : differentialFittingIdeal P 0 = ⊥ := by
  exact Module.Presentation.fittingIdeal_zero_eq_bot_of_card_relations_lt_generators
    P.differentials (by simpa using h)

end AlgebraPresentation

namespace AffineFittingLocus

open _root_.AlgebraicGeometry

variable {A : Type u} [CommRing A]
variable {M : Type v} [AddCommGroup M] [Module A M]

/-- The affine closed scheme cut out by the `i`th Fitting ideal of a chosen finite module
presentation. -/
abbrev scheme (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) : Scheme :=
  Spec (.of (A ⧸ Module.Presentation.fittingIdeal P i))

/-- The affine Fitting closed scheme is literally independent of the chosen finite
presentation.  This is stronger than merely identifying its support: the quotient rings, and
hence their spectra, agree after rewriting by presentation independence. -/
theorem scheme_eq
    (P : Module.Presentation.{w, x} A M)
    (Q : Module.Presentation A M)
    [Fintype P.G] [Fintype P.R] [Fintype Q.G] [Fintype Q.R]
    (i : ℕ) : scheme P i = scheme Q i := by
  unfold scheme
  rw [Module.Presentation.fittingIdeal_eq P Q i]

/-- The closed immersion of a presentation Fitting locus into the ambient affine scheme. -/
def inclusion (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) :
    scheme P i ⟶ Spec (.of A) :=
  Spec.map (CommRingCat.ofHom
    (Ideal.Quotient.mk (Module.Presentation.fittingIdeal P i)))

instance inclusion_isClosedImmersion (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] (i : ℕ) : IsClosedImmersion (inclusion P i) := by
  apply IsClosedImmersion.spec_of_surjective
  exact Ideal.Quotient.mk_surjective

/-- The affine closed scheme cut out by a differential Fitting ideal of a finite algebra
presentation. -/
abbrev differentialScheme {R : Type*} [CommRing R] [Algebra R A]
    {ι : Type w} {σ : Type x} (P : _root_.Algebra.Presentation R A ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) : Scheme :=
  scheme P.differentials i

/-- Differential Fitting closed schemes computed from two finite algebra presentations agree. -/
theorem differentialScheme_eq {R : Type*} [CommRing R] [Algebra R A]
    {i₁ : Type w} {s₁ : Type x} {i₂ s₂ : Type*}
    (P : _root_.Algebra.Presentation R A i₁ s₁)
    (Q : _root_.Algebra.Presentation R A i₂ s₂)
    [Fintype i₁] [Fintype s₁] [Fintype i₂] [Fintype s₂]
    (i : ℕ) : differentialScheme P i = differentialScheme Q i := by
  exact scheme_eq P.differentials Q.differentials i

/-- The zeroth Fitting closed scheme is empty exactly when the finitely presented module is
zero. -/
theorem isEmpty_scheme_zero_iff
    (P : Module.Presentation.{w, x} A M)
    [Fintype P.G] [Fintype P.R] :
    IsEmpty (scheme P 0) ↔ Subsingleton M := by
  rw [show IsEmpty (scheme P 0) ↔
      Subsingleton (A ⧸ Module.Presentation.fittingIdeal P 0) from
    PrimeSpectrum.isEmpty_iff_subsingleton]
  rw [Ideal.Quotient.subsingleton_iff,
    Module.Presentation.fittingIdeal_zero_eq_top_iff]

/-- The actual zeroth differential Fitting scheme is empty exactly when the affine algebra is
formally unramified over its base. -/
theorem isEmpty_differentialScheme_zero_iff_formallyUnramified
    {R : Type*} [CommRing R] [Algebra R A]
    {ι : Type w} {σ : Type x} (P : _root_.Algebra.Presentation R A ι σ)
    [Fintype ι] [Fintype σ] :
    IsEmpty (differentialScheme P 0) ↔ _root_.Algebra.FormallyUnramified R A := by
  rw [isEmpty_scheme_zero_iff,
    ← _root_.Algebra.formallyUnramified_iff R A]

/-- The differential Fitting locus is a genuine closed subscheme of the affine algebra. -/
def differentialι {R : Type*} [CommRing R] [Algebra R A]
    {ι : Type w} {σ : Type x} (P : _root_.Algebra.Presentation R A ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) :
    differentialScheme P i ⟶ Spec (.of A) :=
  inclusion P.differentials i

instance differentialι_isClosedImmersion
    {R : Type*} [CommRing R] [Algebra R A]
    {ι : Type w} {σ : Type x} (P : _root_.Algebra.Presentation R A ι σ)
    [Fintype ι] [Fintype σ] (i : ℕ) :
    IsClosedImmersion (differentialι P i) := by
  change IsClosedImmersion (inclusion P.differentials i)
  infer_instance

end AffineFittingLocus

end

end GromovWitten.AlgebraicGeometry
