/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.AlgebraicGeometry.ProjectiveCompletionCharts
import GromovWitten.AlgebraicGeometry.ProjectiveCompletionTautological
import GromovWitten.AlgebraicGeometry.IntersectionTheory.PointOrder
import GromovWitten.AlgebraicGeometry.IntersectionTheory.FiniteTypeDimension
import GromovWitten.AlgebraicGeometry.IntersectionTheory.ChartPointOrder

/-!
# The hyperplane at infinity of the projective completion

For a graded vector bundle `𝓔 : GradedBundleData X ι` with projective completion
`P := P(E ⊕ 1) = 𝓔.projectiveCompletion`, this file studies the *coordinate points* of the
fibres of `q : P → X`: over a point `x` of a trivialising open `U_j` (with prime `𝔭 ⊆ A_j`),
and for a set `S` of homogeneous coordinates `x_s`, `s ∈ S ⊆ Option ι`, the generic point of the
coordinate subspace `{x_s = 0, s ∈ S}` of the fibre `P_x`.  In the affine chart `D₊(x_i)`,
`i ∉ S`, this point is the prime `𝔭 · A_j[x] + (x_s / x_i : s ∈ S)` of `A_j[x_k : k ∈ ι]`
(`coordIdeal`), and the chart description is proved in *every* chart `i ∉ S`.

The case `S = {none}` gives the generic point `hyperPoint 𝓔 x` of the hyperplane at infinity
`H_x = P(E)_x ⊆ P_x`.

## Main results

* `coordIdeal 𝔭 T = 𝔭 · A[x] + (x_k : k ∈ T)`, a prime ideal of `MvPolynomial ι A` for `𝔭`
  prime (`isPrime_coordIdeal`), with `X_mem_coordIdeal_iff`, `C_mem_coordIdeal_iff`;
  `pointOrd_coordIdeal` and `dim_coordIdealPoint_insert` transport the chart computations of
  `ChartPointOrder.lean` (over the domain `A ⧸ 𝔭`) to the chart `Spec A[x]`, `A` Noetherian.
* `projCoordPoint 𝔭 S i`: the coordinate point of `Proj A[x_j : j ∈ Option ι]` computed in
  the chart `D₊(x_i)`, `i ∉ S`; it is independent of the chart (`projCoordPoint_congr`), lies in
  `D₊(x_s)` iff `s ∉ S` (`projCoordPoint_mem_basicOpen_iff`), lies over `𝔭`
  (`projection_projCoordPoint`) and is the generic point of the coordinate subspace
  `projCoordSet 𝔭 S` of the fibre (`projCoordPoint_mem_projCoordSet`,
  `projCoordPoint_specializes`).
* `GradedBundleData.coordPoint 𝓔 j 𝔭 S i`: the same point in `P(E ⊕ 1)`, with the chart
  description `coordPoint_eq_completionChart`, chart independence `coordPoint_congr`, chart
  membership `coordPoint_mem_range_completionChart_iff`, specialisations
  `coordPoint_specializes`, `coordPoint_specializes_of_subset`, and `fibrePoint_eq_coordPoint`
  (`S = ∅` is the generic fibre point).
* `GradedBundleData.hyperPoint 𝓔 x`: the generic point of the hyperplane at infinity over `x`
  (`hyperPoint_specializes`, `hyperPoint_eq_of_specializes`, `hyperPoint_chart`,
  `completionToBase_hyperPoint`, `hyperPoint_mem_range_infinityDivisor`,
  `fibrePoint_specializes_hyperPoint`), of dimension `dim x + rank - 1`
  (`dimensionFunction_hyperPoint`).
* `GradedBundleData.dimensionFunction_fibrePoint_completionCharts`: the dimension shift
  `hshift` of the charted pullback along `P(E ⊕ 1) → X`.
* `GradedBundleData.tautTransition_val`, `tautTransition_none_none`,
  `residueFieldMap_sectionResidueUnit_tautTransition`: the transition unit `x_s / x_i` of
  `O(1)` is the coordinate `optionCoordVar i s` of the chart `(j, i)`, and its residue at a
  point of the chart is the residue of that polynomial.
* `GradedBundleData.firstChernClassOfField_tautological_fibrePoint`: **the hyperplane at
  infinity is the divisor of `x_none`**, `c₁(O(1)) ∩ [fibrePoint x] = [hyperPoint x]`.
* `GradedBundleData.pointOrd_coordPoint`, `dimensionFunction_coordPoint`,
  `residueDegree_coordPoint_univ`: orders of the coordinate functions `x_t / x_i` along the
  coordinate points of the trivial piece over `U_j`, their dimensions, and the residue degree
  one of `P(E ⊕ 1) → X` at the zero-section point (for the Segre identity).
-/

open CategoryTheory Limits AlgebraicGeometry TopologicalSpace HomogeneousLocalization

namespace GromovWitten.AlgebraicGeometry

open GromovWitten.Algebra MvPolynomial IntersectionTheory

universe u

noncomputable section

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ### Coordinate ideals of a polynomial ring -/

section CoordIdeal

variable {A : Type u} [CommRing A] {ι : Type u}

/-- The coordinate ideal `𝔭 · A[x] + (x_k : k ∈ T)` of `A[x_k : k ∈ ι]`. -/
def coordIdeal (𝔭 : Ideal A) (T : Set ι) : Ideal (MvPolynomial ι A) :=
  Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 ⊔ Ideal.span (X '' T)

/-- The ring map `A[x_k : k ∈ ι] → (A ⧸ 𝔭)[x_k : k ∉ T]` reducing the coefficients modulo `𝔭`
and killing the variables `x_k`, `k ∈ T`. -/
def coordIdealQuot (𝔭 : Ideal A) (T : Set ι) :
    MvPolynomial ι A →+* MvPolynomial {k : ι // k ∉ T} (A ⧸ 𝔭) :=
  (killCompl (Subtype.val_injective (p := fun k : ι ↦ k ∉ T))).toRingHom.comp
    (MvPolynomial.map (Ideal.Quotient.mk 𝔭))

/-- The ideal generated by the variables `x_k`, `k ∈ T`, is the kernel of `killCompl` for the
inclusion of the complement of `T`. -/
theorem span_X_image_eq_ker (T : Set ι) :
    Ideal.span (X '' T : Set (MvPolynomial ι A)) =
      RingHom.ker (killCompl (Subtype.val_injective (p := fun k : ι ↦ k ∉ T))).toRingHom := by
  ext p
  rw [mem_ideal_span_X_image, RingHom.mem_ker]
  constructor
  · intro h
    refine MvPolynomial.ext _ _ fun s ↦ ?_
    change coeff s (killCompl _ p) = coeff s 0
    rw [coeff_killCompl, coeff_zero]
    by_contra hne
    obtain ⟨k, hk, hk'⟩ := h _ (mem_support_iff.mpr hne)
    rw [Finsupp.mapDomain_of_notMem_range] at hk'
    · exact hk' rfl
    · rintro ⟨⟨k', hk'T⟩, rfl⟩
      exact hk'T hk
  · intro h m hm
    by_contra hne
    push Not at hne
    have hsub : (m.support : Set ι) ⊆ Set.range (Subtype.val : {k : ι // k ∉ T} → ι) := by
      intro k hk
      exact ⟨⟨k, fun hkT ↦ (Finsupp.mem_support_iff.mp hk) (hne k hkT)⟩, rfl⟩
    have h' := congrArg
      (coeff (Finsupp.comapDomain Subtype.val m Subtype.val_injective.injOn)) h
    change coeff _ (killCompl _ p) = coeff _ 0 at h'
    rw [coeff_killCompl, coeff_zero,
      Finsupp.mapDomain_comapDomain _ Subtype.val_injective _ hsub] at h'
    exact (mem_support_iff.mp hm) h'

/-- The coordinate ideal is the kernel of `coordIdealQuot`. -/
theorem coordIdeal_eq_ker (𝔭 : Ideal A) (T : Set ι) :
    coordIdeal 𝔭 T = RingHom.ker (coordIdealQuot 𝔭 T) := by
  classical
  rw [coordIdealQuot, ← RingHom.comap_ker, ← span_X_image_eq_ker]
  apply le_antisymm
  · refine sup_le ?_ ?_
    · rw [Ideal.map_le_iff_le_comap]
      intro a ha
      rw [Ideal.mem_comap, Ideal.mem_comap, map_C, Ideal.Quotient.eq_zero_iff_mem.mpr ha, map_zero]
      exact zero_mem _
    · rw [Ideal.span_le]
      rintro _ ⟨k, hk, rfl⟩
      rw [SetLike.mem_coe, Ideal.mem_comap, map_X]
      exact Ideal.subset_span ⟨k, hk, rfl⟩
  · intro p hp
    rw [Ideal.mem_comap, mem_ideal_span_X_image] at hp
    rw [as_sum p]
    refine Ideal.sum_mem _ fun m _ ↦ ?_
    by_cases h : ∃ k ∈ T, m k ≠ 0
    · refine Ideal.mem_sup_right (mem_ideal_span_X_image.mpr fun m' hm' ↦ ?_)
      rw [support_monomial] at hm'
      split_ifs at hm' with h0
      · exact absurd hm' (Finset.notMem_empty _)
      · rw [Finset.mem_singleton] at hm'
        exact hm' ▸ h
    · have h0 : coeff m (MvPolynomial.map (Ideal.Quotient.mk 𝔭) p) = 0 := by
        by_contra h'
        exact h (hp m (mem_support_iff.mpr h'))
      rw [coeff_map, Ideal.Quotient.eq_zero_iff_mem] at h0
      refine Ideal.mem_sup_left (mem_map_C_iff.mpr fun m' ↦ ?_)
      rw [coeff_monomial]
      split_ifs
      · exact h0
      · exact zero_mem _

/-- The coordinate ideal of a prime is prime. -/
theorem isPrime_coordIdeal (𝔭 : Ideal A) [𝔭.IsPrime] (T : Set ι) :
    (coordIdeal 𝔭 T).IsPrime := by
  rw [coordIdeal_eq_ker]
  exact RingHom.ker_isPrime _

/-- `coordIdealQuot` kills the variables `x_k`, `k ∈ T`. -/
theorem coordIdealQuot_X_of_mem (𝔭 : Ideal A) (T : Set ι) {k : ι} (hk : k ∈ T) :
    coordIdealQuot 𝔭 T (X k) = 0 := by
  change killCompl _ (MvPolynomial.map _ (X k)) = _
  rw [map_X, killCompl, aeval_X, dif_neg]
  rintro ⟨⟨k', hk'⟩, rfl⟩
  exact hk' hk

/-- `coordIdealQuot` sends the variable `x_k`, `k ∉ T`, to the variable `x_k`. -/
theorem coordIdealQuot_X_of_notMem (𝔭 : Ideal A) (T : Set ι) {k : ι} (hk : k ∉ T) :
    coordIdealQuot 𝔭 T (X k) = X ⟨k, hk⟩ := by
  change killCompl _ (MvPolynomial.map _ (X k)) = _
  rw [map_X, killCompl, aeval_X, dif_pos (show k ∈ Set.range Subtype.val from ⟨⟨k, hk⟩, rfl⟩)]
  congr 1
  rw [Equiv.symm_apply_eq]
  exact Subtype.ext rfl

/-- A variable lies in the coordinate ideal of a prime iff its index lies in `T`. -/
theorem X_mem_coordIdeal_iff (𝔭 : Ideal A) [𝔭.IsPrime] (T : Set ι) (k : ι) :
    X k ∈ coordIdeal 𝔭 T ↔ k ∈ T := by
  rw [coordIdeal_eq_ker, RingHom.mem_ker]
  by_cases hk : k ∈ T
  · rw [coordIdealQuot_X_of_mem 𝔭 T hk]
    exact iff_of_true rfl hk
  · rw [coordIdealQuot_X_of_notMem 𝔭 T hk]
    exact iff_of_false (X_ne_zero _) hk

/-- A constant lies in the coordinate ideal iff it lies in `𝔭`. -/
theorem C_mem_coordIdeal_iff (𝔭 : Ideal A) (T : Set ι) (a : A) :
    C a ∈ coordIdeal 𝔭 T ↔ a ∈ 𝔭 := by
  rw [coordIdeal_eq_ker, RingHom.mem_ker]
  change killCompl _ (MvPolynomial.map _ (C a)) = 0 ↔ _
  rw [map_C, killCompl_C, C_eq_zero, Ideal.Quotient.eq_zero_iff_mem]

/-- The contraction of the coordinate ideal to the coefficient ring is `𝔭`. -/
theorem comap_algebraMap_coordIdeal (𝔭 : Ideal A) (T : Set ι) :
    Ideal.comap (algebraMap A (MvPolynomial ι A)) (coordIdeal 𝔭 T) = 𝔭 := by
  ext a
  rw [Ideal.mem_comap, algebraMap_eq, C_mem_coordIdeal_iff]

/-- The coordinate ideal is monotone in the set of variables. -/
theorem coordIdeal_mono (𝔭 : Ideal A) {T T' : Set ι} (h : T ⊆ T') :
    coordIdeal 𝔭 T ≤ coordIdeal 𝔭 T' :=
  sup_le_sup_left (Ideal.span_mono (Set.image_mono h)) _

/-- The coordinate ideal of the empty set is `𝔭 · A[x]`. -/
theorem coordIdeal_empty (𝔭 : Ideal A) :
    coordIdeal 𝔭 (∅ : Set ι) = Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 := by
  rw [coordIdeal, Set.image_empty, Ideal.span_empty, sup_bot_eq]

/-- `coordIdeal 𝔭 T ≤ 𝔮` for a prime `𝔮` lying over `𝔭` and containing the variables of `T`. -/
theorem coordIdeal_le_of_le (𝔭 : Ideal A) (T : Set ι) (𝔮 : Ideal (MvPolynomial ι A))
    (h𝔭 : 𝔭 ≤ Ideal.comap (algebraMap A (MvPolynomial ι A)) 𝔮) (hT : ∀ k ∈ T, X k ∈ 𝔮) :
    coordIdeal 𝔭 T ≤ 𝔮 := by
  refine sup_le (Ideal.map_le_iff_le_comap.mpr h𝔭) (Ideal.span_le.mpr ?_)
  rintro _ ⟨k, hk, rfl⟩
  exact hT k hk

/-- The coordinate ideal as a point of `Spec A[x_k : k ∈ ι]`. -/
def coordIdealPoint (𝔭 : Ideal A) [𝔭.IsPrime] (T : Set ι) :
    ↥(Spec (CommRingCat.of (MvPolynomial ι A))) :=
  ⟨coordIdeal 𝔭 T, isPrime_coordIdeal 𝔭 T⟩

/-- The ideal of `coordIdealPoint`. -/
@[simp]
theorem coordIdealPoint_asIdeal (𝔭 : Ideal A) [𝔭.IsPrime] (T : Set ι) :
    (coordIdealPoint 𝔭 T).asIdeal = coordIdeal 𝔭 T := rfl

end CoordIdeal

/-! ### Orders of coordinate functions in a chart `Spec A[x]`, `A` not a domain -/

section ChartOrder

variable {A : Type u} [CommRing A] {ι : Type u}

/-- The coordinate ideal is the contraction of the coordinate prime `(x_k : k ∈ T)` of
`(A ⧸ 𝔭)[x]` along the reduction of coefficients. -/
theorem coordIdeal_eq_comap (𝔭 : Ideal A) (T : Set ι) :
    coordIdeal 𝔭 T = Ideal.comap (MvPolynomial.map (Ideal.Quotient.mk 𝔭))
      (coordPrime (B := A ⧸ 𝔭) T) := by
  rw [coordIdeal_eq_ker, coordIdealQuot, ← RingHom.comap_ker, ← span_X_image_eq_ker]
  rfl

/-- The closed immersion `Spec (A ⧸ 𝔭)[x] ⟶ Spec A[x]`. -/
abbrev specMapQuotient (𝔭 : Ideal A) :
    Spec (CommRingCat.of (MvPolynomial ι (A ⧸ 𝔭))) ⟶ Spec (CommRingCat.of (MvPolynomial ι A)) :=
  Spec.map (CommRingCat.ofHom (MvPolynomial.map (Ideal.Quotient.mk 𝔭)))

/-- Reduction of coefficients is surjective. -/
theorem map_mk_surjective (𝔭 : Ideal A) :
    Function.Surjective (MvPolynomial.map (Ideal.Quotient.mk 𝔭) : MvPolynomial ι A →+* _) :=
  MvPolynomial.map_surjective _ Ideal.Quotient.mk_surjective

/-- `specMapQuotient` is a closed immersion. -/
instance isClosedImmersion_specMapQuotient (𝔭 : Ideal A) :
    IsClosedImmersion (specMapQuotient (ι := ι) 𝔭) :=
  IsClosedImmersion.spec_of_surjective _ (map_mk_surjective 𝔭)

/-- `specMapQuotient` sends the coordinate prime of `(A ⧸ 𝔭)[x]` to the coordinate point. -/
theorem specMapQuotient_coordPrimePt (𝔭 : Ideal A) [𝔭.IsPrime] (T : Set ι) :
    (specMapQuotient 𝔭).base (coordPrimePt (B := A ⧸ 𝔭) T) = coordIdealPoint 𝔭 T :=
  PrimeSpectrum.ext (coordIdeal_eq_comap 𝔭 T).symm

/-- The kernel of the reduction of coefficients `A[x] → (A ⧸ 𝔭)[x]` is `𝔭 · A[x]`. -/
theorem ker_map_mk (𝔭 : Ideal A) :
    RingHom.ker (MvPolynomial.map (Ideal.Quotient.mk 𝔭) : MvPolynomial ι A →+* _) =
      Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 := by
  rw [MvPolynomial.ker_map, Ideal.mk_ker]

/-- A prime of `A[x]` containing `𝔭 · A[x]`, as a prime of `(A ⧸ 𝔭)[x]`. -/
def liftPrime (𝔭 : Ideal A) (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι A))))
    (h : Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 ≤ 𝔮.asIdeal) :
    ↥(Spec (CommRingCat.of (MvPolynomial ι (A ⧸ 𝔭)))) :=
  ⟨Ideal.map (MvPolynomial.map (Ideal.Quotient.mk 𝔭)) 𝔮.asIdeal,
    Ideal.map_isPrime_of_surjective (map_mk_surjective 𝔭) (by rw [ker_map_mk]; exact h)⟩

/-- `specMapQuotient` sends `liftPrime 𝔭 𝔮 h` to `𝔮`. -/
theorem specMapQuotient_liftPrime (𝔭 : Ideal A) (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι A))))
    (h : Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 ≤ 𝔮.asIdeal) :
    (specMapQuotient 𝔭).base (liftPrime 𝔭 𝔮 h) = 𝔮 := by
  refine PrimeSpectrum.ext ?_
  change Ideal.comap (MvPolynomial.map (Ideal.Quotient.mk 𝔭))
    (Ideal.map (MvPolynomial.map (Ideal.Quotient.mk 𝔭)) 𝔮.asIdeal) = 𝔮.asIdeal
  rw [Ideal.comap_map_of_surjective _ (map_mk_surjective 𝔭), ← RingHom.ker_eq_comap_bot,
    ker_map_mk, sup_eq_left.mpr h]

/-- `liftPrime` of `𝔮` is the coordinate prime iff `𝔮` is the coordinate point. -/
theorem liftPrime_eq_coordPrimePt_iff (𝔭 : Ideal A) [𝔭.IsPrime]
    (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι A))))
    (h : Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 ≤ 𝔮.asIdeal) (T : Set ι) :
    liftPrime 𝔭 𝔮 h = coordPrimePt (B := A ⧸ 𝔭) T ↔ 𝔮 = coordIdealPoint 𝔭 T := by
  constructor
  · intro e
    rw [← specMapQuotient_liftPrime 𝔭 𝔮 h, e, specMapQuotient_coordPrimePt]
  · intro e
    subst e
    refine PrimeSpectrum.ext ?_
    change Ideal.map _ (coordIdeal 𝔭 T) = coordPrime T
    rw [coordIdeal_eq_comap, Ideal.map_comap_of_surjective _ (map_mk_surjective 𝔭)]

/-- Naturality of residues of global sections along `Spec` of a ring map. -/
theorem residueFieldMap_specMap_residue_specGerm {R S : CommRingCat.{u}} (f : R ⟶ S)
    (x : ↥(Spec S)) (c : R) :
    (Spec.map f).residueFieldMap x ((Spec R).residue _ (specGerm ((Spec.map f).base x) c)) =
      (Spec S).residue x (specGerm x (f c)) := by
  rw [← CommRingCat.comp_apply, Scheme.residue_residueFieldMap, CommRingCat.comp_apply]
  congr 1
  change (Spec.map f).stalkMap x ((Spec R).presheaf.germ ⊤ _ (Opens.mem_top _)
    ((Scheme.ΓSpecIso R).inv c)) =
    (Spec S).presheaf.germ ⊤ x (Opens.mem_top _) ((Scheme.ΓSpecIso S).inv (f c))
  rw [Scheme.Hom.germ_stalkMap_apply]
  exact congrArg _ (ConcreteCategory.congr_hom (Scheme.ΓSpecIso_inv_naturality f) c).symm

open scoped Classical in
/-- **Orders of coordinate functions in a chart `Spec A[x] ⟶ Y`** (`A` Noetherian, not
necessarily a domain, `𝔭 ⊆ A` prime): along `ψ(coordIdealPoint 𝔭 S) ⤳ ψ 𝔮`, the order of a unit
`u` of `κ(ψ(coordIdealPoint 𝔭 S))` whose image in the chart is the residue of the variable `X t`
(`t ∉ S`) is `1` if `𝔮` is the coordinate point of `insert t S` and `0` otherwise.  Derived from
`pointOrd_coordPrime` over the domain `A ⧸ 𝔭` through the closed immersion `specMapQuotient`. -/
theorem pointOrd_coordIdeal {Y : Scheme.{u}} [IsLocallyNoetherian Y] [IsNoetherianRing A]
    [Finite ι] (ψ : Spec (CommRingCat.of (MvPolynomial ι A)) ⟶ Y) [IsPreimmersion ψ]
    (𝔭 : Ideal A) [𝔭.IsPrime] {S : Set ι} {t : ι} (ht : t ∉ S)
    (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι A)))) (h𝔮 : coordIdeal 𝔭 S ≤ 𝔮.asIdeal)
    (h : ψ.base (coordIdealPoint 𝔭 S) ⤳ ψ.base 𝔮)
    (u : (Y.residueField (ψ.base (coordIdealPoint 𝔭 S)))ˣ)
    (hu : ψ.residueFieldMap (coordIdealPoint 𝔭 S) u =
      (Spec (CommRingCat.of (MvPolynomial ι A))).residue _ (specGerm (coordIdealPoint 𝔭 S) (X t))) :
    pointOrd h u = if 𝔮 = coordIdealPoint 𝔭 (insert t S) then 1 else 0 := by
  have h𝔮' : Ideal.map (C : A →+* MvPolynomial ι A) 𝔭 ≤ 𝔮.asIdeal :=
    (le_sup_left.trans h𝔮)
  obtain ⟨𝔮', rfl⟩ : ∃ 𝔮', (specMapQuotient 𝔭).base 𝔮' = 𝔮 :=
    ⟨_, specMapQuotient_liftPrime 𝔭 𝔮 h𝔮'⟩
  have e1 := specMapQuotient_coordPrimePt 𝔭 S
  generalize hw : coordIdealPoint 𝔭 S = w at h u hu e1 ⊢
  subst e1
  rw [← specMapQuotient_coordPrimePt 𝔭 (insert t S),
    (specMapQuotient (ι := ι) 𝔭).isClosedEmbedding.injective.eq_iff]
  refine pointOrd_coordPrime (specMapQuotient 𝔭 ≫ ψ) ht 𝔮' h u ?_
  rw [Scheme.residueFieldMap_comp]
  change (specMapQuotient 𝔭).residueFieldMap (coordPrimePt S)
    (ψ.residueFieldMap ((specMapQuotient 𝔭).base (coordPrimePt S)) u) = _
  rw [hu, residueFieldMap_specMap_residue_specGerm]
  change (Spec (CommRingCat.of (MvPolynomial ι (A ⧸ 𝔭)))).residue (coordPrimePt S)
    (specGerm (coordPrimePt S) (MvPolynomial.map (Ideal.Quotient.mk 𝔭) (X t))) = _
  rw [map_X]

/-- **Dimension of coordinate points**: in any `CovByDimension` dimension function, the
coordinate point of `insert t S` has dimension one less than that of `S`. -/
theorem dim_coordIdealPoint_insert {Y : Scheme.{u}} [IsNoetherianRing A] [Finite ι]
    (ψ : Spec (CommRingCat.of (MvPolynomial ι A)) ⟶ Y) [IsPreimmersion ψ]
    (dim : DimensionFunction Y) (hcov : HomogeneityLocal.CovByDimension dim) (𝔭 : Ideal A)
    [𝔭.IsPrime] {S : Set ι} {t : ι} (ht : t ∉ S) :
    dim (ψ.base (coordIdealPoint 𝔭 (insert t S))) = dim (ψ.base (coordIdealPoint 𝔭 S)) - 1 := by
  rw [← specMapQuotient_coordPrimePt 𝔭, ← specMapQuotient_coordPrimePt 𝔭]
  exact dim_coordPrime_insert (specMapQuotient 𝔭 ≫ ψ) dim hcov ht

end ChartOrder

/-! ### Coordinate points of `Proj R[x_j : j ∈ Option ι]` -/

section ProjCoord

open ProjBaseChange

variable {R : Type u} [CommRing R] {ι : Type u}

open Classical in
/-- The indices `k : ι` of the variables of the chart `D₊(x_i)` which are quotients `x_s / x_i`
with `s ∈ S`: the variable `X k` of the chart `D₊(x_i)` is `x_{σ(k)} / x_i` where `σ` exchanges
`none` and `i`. -/
def chartSet (i : Option ι) (S : Set (Option ι)) : Set ι :=
  {k | Equiv.swap none i (some k) ∈ S}

open Classical in
/-- Membership in `chartSet`. -/
theorem mem_chartSet_iff (i : Option ι) (S : Set (Option ι)) (k : ι) :
    k ∈ chartSet i S ↔ Equiv.swap none i (some k) ∈ S :=
  Iff.rfl

/-- The chart at `x_none` does not exchange variables. -/
theorem mem_chartSet_none_iff (S : Set (Option ι)) (k : ι) :
    k ∈ chartSet none S ↔ some k ∈ S := by
  classical
  rw [mem_chartSet_iff, Equiv.swap_self, Equiv.refl_apply]

/-- In the chart at `x_i`, `i : ι`, the variable `X k`, `k ≠ i`, is `x_k / x_i`. -/
theorem mem_chartSet_some_iff_of_ne (S : Set (Option ι)) {i k : ι} (h : k ≠ i) :
    k ∈ chartSet (some i) S ↔ some k ∈ S := by
  classical
  rw [mem_chartSet_iff, Equiv.swap_apply_of_ne_of_ne (Option.some_ne_none k)
    (fun h' ↦ h (Option.some_injective _ h'))]

/-- In the chart at `x_i`, `i : ι`, the variable `X i` is `x_none / x_i`. -/
theorem mem_chartSet_some_self_iff (S : Set (Option ι)) (i : ι) :
    i ∈ chartSet (some i) S ↔ none ∈ S := by
  classical
  rw [mem_chartSet_iff, Equiv.swap_apply_right]

/-- `chartSet` of the empty set. -/
theorem chartSet_empty (i : Option ι) : chartSet i (∅ : Set (Option ι)) = ∅ :=
  Set.eq_empty_of_forall_notMem fun _ h ↦ h

/-- `chartSet` of a set of finite coordinates, in the chart at `x_none`. -/
theorem chartSet_none_image (S₀ : Set ι) : chartSet none (some '' S₀) = S₀ := by
  ext k
  rw [mem_chartSet_none_iff, Set.mem_image]
  exact ⟨fun ⟨_, hk', e⟩ ↦ Option.some_injective _ e ▸ hk', fun h ↦ ⟨k, h, rfl⟩⟩

/-- `chartSet` of a set of finite coordinates, in the chart at `x_i` with `i ∉ S₀`. -/
theorem chartSet_some_image (S₀ : Set ι) {i : ι} (hi : i ∉ S₀) :
    chartSet (some i) (some '' S₀) = S₀ := by
  ext k
  by_cases hk : k = i
  · subst hk
    rw [mem_chartSet_some_self_iff]
    exact iff_of_false (fun ⟨_, _, h⟩ ↦ Option.some_ne_none _ h) hi
  · rw [mem_chartSet_some_iff_of_ne _ hk, Set.mem_image]
    exact ⟨fun ⟨_, hk', e⟩ ↦ Option.some_injective _ e ▸ hk', fun h ↦ ⟨k, h, rfl⟩⟩

/-- `chartSet` of the hyperplane at infinity `{x_none = 0}`, in the chart at `x_i`. -/
theorem chartSet_some_singleton_none (i : ι) :
    chartSet (some i) ({none} : Set (Option ι)) = {i} := by
  ext k
  by_cases hk : k = i
  · subst hk
    rw [mem_chartSet_some_self_iff]
    simp
  · rw [mem_chartSet_some_iff_of_ne _ hk]
    simp [hk]

/-- In a chart `i ≠ some t`, the variable `X t` is `x_t / x_i`. -/
theorem mem_chartSet_iff_of_ne (S : Set (Option ι)) {i : Option ι} {t : ι} (h : i ≠ some t) :
    t ∈ chartSet i S ↔ some t ∈ S := by
  classical
  rw [mem_chartSet_iff, Equiv.swap_apply_of_ne_of_ne (Option.some_ne_none t) (Ne.symm h)]

/-- `chartSet` of `insert (some t) S` in a chart `i ≠ some t`. -/
theorem chartSet_insert_some (S : Set (Option ι)) {i : Option ι} {t : ι} (h : i ≠ some t) :
    chartSet i (insert (some t) S) = insert t (chartSet i S) := by
  classical
  ext k
  rw [mem_chartSet_iff, Set.mem_insert_iff, Set.mem_insert_iff, mem_chartSet_iff,
    Equiv.swap_apply_eq_iff, Equiv.swap_apply_of_ne_of_ne (Option.some_ne_none t) (Ne.symm h),
    Option.some_inj]

open Classical in
/-- The coordinate `x_s / x_i` of the chart `D₊(x_i)`, as a polynomial in the variables of the
chart: `1` for `s = i`, and the variable `X k` with `σ(k) = s` otherwise (`σ` the exchange of
`none` and `i`). -/
def optionCoordVar (i s : Option ι) : MvPolynomial ι R :=
  (Equiv.swap none i s).elim 1 X

open Classical in
/-- `dehomAt i (x_s / x_i) = optionCoordVar i s`. -/
theorem dehomAt_mk_X (i s : Option ι) :
    dehomAt R i (Away.mk _ (X_mem_homogeneousSubmodule_one i) 1 (X s)
      (X_mem_homogeneousSubmodule_one_smul s)) = optionCoordVar i s := by
  rw [dehomAt_mk, rename_X, optionCoordVar]
  generalize Equiv.swap none i s = t
  cases t with
  | none => rw [optionEquivLeft_X_none, Polynomial.eval_X]; rfl
  | some k => rw [optionEquivLeft_X_some, Polynomial.eval_C]; rfl

open Classical in
/-- `dehomAt i (x_s / x_i) = optionCoordVar i s`, with the numerator written `x_s ^ 1` (the form
of `Away.isLocalizationElem`). -/
theorem dehomAt_mk_X_pow_one (i s : Option ι)
    (h : X s ^ 1 ∈ homogeneousSubmodule (Option ι) R (1 • 1)) :
    dehomAt R i (Away.mk _ (X_mem_homogeneousSubmodule_one i) 1 (X s ^ 1) h) =
      optionCoordVar i s := by
  rw [dehomAt_mk, map_pow, pow_one, rename_X, optionCoordVar]
  generalize Equiv.swap none i s = t
  cases t with
  | none => rw [optionEquivLeft_X_none, Polynomial.eval_X]; rfl
  | some k => rw [optionEquivLeft_X_some, Polynomial.eval_C]; rfl

/-- `optionCoordVar i i = 1`. -/
theorem optionCoordVar_self (i : Option ι) : optionCoordVar (R := R) i i = 1 := by
  classical
  rw [optionCoordVar, Equiv.swap_apply_right]
  rfl

open Classical in
/-- `optionCoordVar i (σ k) = X k`. -/
theorem optionCoordVar_swap (i : Option ι) (k : ι) :
    optionCoordVar (R := R) i (Equiv.swap none i (some k)) = X k := by
  rw [optionCoordVar, Equiv.swap_apply_self]
  rfl

/-- The coordinate `x_none / x_i` of the chart `D₊(x_i)`, `i : ι`, is the variable `X i`. -/
theorem optionCoordVar_some_none (i : ι) : optionCoordVar (R := R) (some i) none = X i := by
  classical
  rw [optionCoordVar, Equiv.swap_apply_left]
  rfl

/-- The coordinate `x_s / x_i` of the chart `D₊(x_i)`, for `s : ι` with `some s ≠ i`, is the
variable `X s`. -/
theorem optionCoordVar_some_of_ne {i : Option ι} {s : ι} (h : i ≠ some s) :
    optionCoordVar (R := R) i (some s) = X s := by
  classical
  rw [optionCoordVar, Equiv.swap_apply_of_ne_of_ne (Option.some_ne_none s) (Ne.symm h)]
  rfl

/-- A point of the chart `D₊(x_i)` lies in `D₊(x_s)` iff the coordinate `x_s / x_i` does not lie
in its prime. -/
theorem projOptionChart_mem_basicOpen_iff (i s : Option ι)
    (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι R)))) :
    (projOptionChart R ι i).base 𝔮 ∈ Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X s) ↔
      optionCoordVar i s ∉ 𝔮.asIdeal := by
  have h1 : (projOptionChart R ι i).base 𝔮 ∈
      Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X s) ↔
      (Spec.map (CommRingCat.ofHom (dehomAt R i).toRingHom)).base 𝔮 ∈
        Proj.awayι _ (X i) (X_mem_homogeneousSubmodule_one i) one_pos ⁻¹ᵁ
          Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X s) := Iff.rfl
  rw [h1, Proj.awayι_preimage_basicOpen _ _ _ (X_mem_homogeneousSubmodule_one s) one_pos]
  change Away.isLocalizationElem _ _ ∉ Ideal.comap (dehomAt R i).toRingHom 𝔮.asIdeal ↔ _
  rw [Ideal.mem_comap]
  change dehomAt R i (Away.mk _ (X_mem_homogeneousSubmodule_one i) 1 (X s ^ 1) _) ∉ _ ↔ _
  rw [dehomAt_mk_X_pow_one]

/-- The structure map of `Proj R[x_j : j ∈ Option ι]` on points of the chart `D₊(x_i)`:
contraction of primes. -/
theorem projection_projOptionChart (i : Option ι)
    (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι R)))) :
    (projection (homogeneousSubmodule (Option ι) R)).base ((projOptionChart R ι i).base 𝔮) =
      PrimeSpectrum.comap (algebraMap R (MvPolynomial ι R)) 𝔮 := by
  change (projOptionChart R ι i ≫ projection (homogeneousSubmodule (Option ι) R)).base 𝔮 = _
  rw [projOptionChart_projection]
  rfl

/-- Specialisation inside the chart `D₊(x_i)` is inclusion of primes. -/
theorem projOptionChart_specializes_iff (i : Option ι)
    (𝔮 𝔮' : ↥(Spec (CommRingCat.of (MvPolynomial ι R)))) :
    (projOptionChart R ι i).base 𝔮 ⤳ (projOptionChart R ι i).base 𝔮' ↔
      𝔮.asIdeal ≤ 𝔮'.asIdeal := by
  rw [(projOptionChart R ι i).isOpenEmbedding.isInducing.specializes_iff]
  exact (PrimeSpectrum.le_iff_specializes 𝔮 𝔮').symm

/-- The coordinate subspace `{x_s = 0 : s ∈ S}` of the fibre of `Proj R[x_j : j ∈ Option ι]`
over a prime `𝔭` of `R`. -/
def projCoordSet (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι)) :
    Set (Proj (homogeneousSubmodule (Option ι) R)) :=
  {z | (∀ s ∈ S, z ∉ Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X s)) ∧
    (projection (homogeneousSubmodule (Option ι) R)).base z = 𝔭}

/-- `projCoordSet` is antitone in `S`. -/
theorem projCoordSet_anti (𝔭 : ↥(Spec (CommRingCat.of R))) {S S' : Set (Option ι)}
    (h : S ⊆ S') : projCoordSet 𝔭 S' ⊆ projCoordSet 𝔭 S :=
  fun _ hz ↦ ⟨fun s hs ↦ hz.1 s (h hs), hz.2⟩

/-- The coordinate point of `Proj R[x_j : j ∈ Option ι]` over `𝔭` for the set of coordinates
`S`, computed in the chart `D₊(x_i)` (meaningful for `i ∉ S`): the image of the prime
`𝔭 · R[x] + (x_s / x_i : s ∈ S)`. Independence of `i ∉ S` is `projCoordPoint_congr`. -/
def projCoordPoint (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι)) (i : Option ι) :
    Proj (homogeneousSubmodule (Option ι) R) :=
  (projOptionChart R ι i).base (coordIdealPoint 𝔭.asIdeal (chartSet i S))

/-- The coordinate point lies over `𝔭`. -/
theorem projection_projCoordPoint (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    (i : Option ι) :
    (projection (homogeneousSubmodule (Option ι) R)).base (projCoordPoint 𝔭 S i) = 𝔭 := by
  rw [projCoordPoint, projection_projOptionChart]
  exact PrimeSpectrum.ext (comap_algebraMap_coordIdeal _ _)

/-- The coordinate point computed in the chart `D₊(x_i)`, `i ∉ S`, lies in `D₊(x_s)` iff
`s ∉ S`. -/
theorem projCoordPoint_mem_basicOpen_iff (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) (s : Option ι) :
    projCoordPoint 𝔭 S i ∈ Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X s) ↔
      s ∉ S := by
  classical
  rw [projCoordPoint, projOptionChart_mem_basicOpen_iff, coordIdealPoint_asIdeal]
  rcases h : Equiv.swap none i s with _ | k
  · have hs : s = i := by
      rw [Equiv.swap_apply_eq_iff] at h
      rw [h, Equiv.swap_apply_left]
    subst hs
    rw [optionCoordVar_self]
    exact iff_of_true
      (fun h1 ↦ (isPrime_coordIdeal _ _).ne_top ((Ideal.eq_top_iff_one _).mpr h1)) hi
  · have hs : s = Equiv.swap none i (some k) := by rwa [Equiv.swap_apply_eq_iff] at h
    rw [hs, optionCoordVar_swap, X_mem_coordIdeal_iff, mem_chartSet_iff]

/-- The coordinate point lies in the coordinate subspace. -/
theorem projCoordPoint_mem_projCoordSet (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) : projCoordPoint 𝔭 S i ∈ projCoordSet 𝔭 S :=
  ⟨fun s hs h ↦ (projCoordPoint_mem_basicOpen_iff 𝔭 S hi s).mp h hs,
    projection_projCoordPoint 𝔭 S i⟩

/-- The coordinate point computed in `D₊(x_i)` specialises to every point of the coordinate
subspace lying in `D₊(x_i)`. -/
theorem projCoordPoint_specializes_of_mem_basicOpen (𝔭 : ↥(Spec (CommRingCat.of R)))
    (S : Set (Option ι)) (i : Option ι)
    {z : Proj (homogeneousSubmodule (Option ι) R)} (hz : z ∈ projCoordSet 𝔭 S)
    (hzi : z ∈ Proj.basicOpen (homogeneousSubmodule (Option ι) R) (X i)) :
    projCoordPoint 𝔭 S i ⤳ z := by
  classical
  have hzi' : z ∈ Set.range (projOptionChart R ι i).base := by
    rw [range_projOptionChart]
    exact hzi
  obtain ⟨𝔷, rfl⟩ := hzi'
  rw [projCoordPoint, projOptionChart_specializes_iff, coordIdealPoint_asIdeal]
  refine coordIdeal_le_of_le _ _ _ ?_ ?_
  · have h2 := hz.2
    rw [projection_projOptionChart] at h2
    rw [← h2]
    exact le_rfl
  · intro k hk
    have hs := hz.1 _ hk
    rw [projOptionChart_mem_basicOpen_iff, not_not, optionCoordVar_swap] at hs
    exact hs

/-- The coordinate point is the generic point of the coordinate subspace: it specialises to every
point of `projCoordSet 𝔭 S`. -/
theorem projCoordPoint_specializes (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) {z : Proj (homogeneousSubmodule (Option ι) R)}
    (hz : z ∈ projCoordSet 𝔭 S) : projCoordPoint 𝔭 S i ⤳ z := by
  obtain ⟨i', hi'⟩ := exists_mem_range_projOptionChart z
  rw [range_projOptionChart] at hi'
  have hi'S : i' ∉ S := fun h ↦ hz.1 i' h hi'
  refine Specializes.trans ?_ (projCoordPoint_specializes_of_mem_basicOpen 𝔭 S i' hz hi')
  exact projCoordPoint_specializes_of_mem_basicOpen 𝔭 S i
    (projCoordPoint_mem_projCoordSet 𝔭 S hi'S)
    ((projCoordPoint_mem_basicOpen_iff 𝔭 S hi'S i).mpr hi)

/-- The coordinate point does not depend on the chart `i ∉ S` used to compute it. -/
theorem projCoordPoint_congr (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    {i i' : Option ι} (hi : i ∉ S) (hi' : i' ∉ S) :
    projCoordPoint 𝔭 S i = projCoordPoint 𝔭 S i' :=
  ((projCoordPoint_specializes 𝔭 S hi (projCoordPoint_mem_projCoordSet 𝔭 S hi')).antisymm
    (projCoordPoint_specializes 𝔭 S hi' (projCoordPoint_mem_projCoordSet 𝔭 S hi))).eq

/-- Coordinate points specialise along inclusions of the sets of coordinates. -/
theorem projCoordPoint_specializes_of_subset (𝔭 : ↥(Spec (CommRingCat.of R)))
    {S S' : Set (Option ι)} (hSS' : S ⊆ S') {i i' : Option ι} (hi : i ∉ S) (hi' : i' ∉ S') :
    projCoordPoint 𝔭 S i ⤳ projCoordPoint 𝔭 S' i' :=
  projCoordPoint_specializes 𝔭 S hi
    (projCoordSet_anti 𝔭 hSS' (projCoordPoint_mem_projCoordSet 𝔭 S' hi'))

/-- A point of the coordinate subspace which specialises to the coordinate point is the
coordinate point. -/
theorem eq_projCoordPoint_of_specializes (𝔭 : ↥(Spec (CommRingCat.of R))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) {z : Proj (homogeneousSubmodule (Option ι) R)}
    (hz : z ∈ projCoordSet 𝔭 S) (h : z ⤳ projCoordPoint 𝔭 S i) : z = projCoordPoint 𝔭 S i :=
  (h.antisymm (projCoordPoint_specializes 𝔭 S hi hz)).eq

end ProjCoord

/-! ### Coordinate points of the projective completion -/

namespace GradedBundleData

open RelativeProj ProjBaseChange VectorBundleTotalSpace IntersectionTheory
open GlobalBlowup (isAffineOpen)

variable {X : Scheme.{u}} {ι : Type u} (𝓔 : GradedBundleData X ι)

/-- The open immersion `Proj Γ(U_j)[x_i : i ∈ Option ι] ⟶ P(E ⊕ 1)` onto the part of
`P(E ⊕ 1)` over the trivialising open `U_j`. -/
def chartProjι (j : 𝓔.bundle.J) :
    Proj (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1)) ⟶
      𝓔.projectiveCompletion :=
  (𝓔.chartProjIso j).hom ≫ affineι X 𝓔.homogData (𝓔.bundle.chart j)

/-- `chartProjι` is an open immersion. -/
instance isOpenImmersion_chartProjι (j : 𝓔.bundle.J) : IsOpenImmersion (𝓔.chartProjι j) := by
  unfold chartProjι
  infer_instance

/-- The chart `(j, i)` of `P(E ⊕ 1)` is the standard chart `D₊(x_i)` followed by
`chartProjι j`. -/
theorem completionChart_eq_projOptionChart_comp (k : 𝓔.bundle.J × Option ι) :
    𝓔.completionChart k = projOptionChart _ ι k.2 ≫ 𝓔.chartProjι k.1 :=
  rfl

/-- The image of `chartProjι j` is the part of `P(E ⊕ 1)` over `U_j`. -/
theorem range_chartProjι (j : 𝓔.bundle.J) :
    Set.range (𝓔.chartProjι j).base =
      𝓔.completionToBase.base ⁻¹' ((𝓔.bundle.chart j).1 : Set X) := by
  have h := Scheme.range_fst_of_isPullback (𝓔.isPullback_chartProjIso j).flip
  rw [Scheme.Opens.range_ι] at h
  exact h

/-- `chartProjι j` lies over `U_j`: the structure map of `P(E ⊕ 1)` restricted to it is the
projection of `Proj Γ(U_j)[x_i]` to `Spec Γ(U_j)`, followed by the identification with `U_j`. -/
theorem chartProjι_completionToBase (j : 𝓔.bundle.J) :
    𝓔.chartProjι j ≫ 𝓔.completionToBase =
      projection (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1)) ≫
        (isAffineOpen X (𝓔.bundle.chart j)).isoSpec.inv ≫ (𝓔.bundle.chart j).1.ι := by
  rw [chartProjι, ← (𝓔.isPullback_chartProjIso j).w, Category.assoc]

/-- The structure map of `P(E ⊕ 1)` on points of `chartProjι j`. -/
theorem completionToBase_chartProjι_apply (j : 𝓔.bundle.J)
    (z : Proj (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1))) :
    𝓔.completionToBase.base ((𝓔.chartProjι j).base z) =
      ((isAffineOpen X (𝓔.bundle.chart j)).isoSpec.inv ≫ (𝓔.bundle.chart j).1.ι).base
        ((projection (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1))).base z) := by
  change (𝓔.chartProjι j ≫ 𝓔.completionToBase).base z = _
  rw [chartProjι_completionToBase]
  rfl

/-- The point of `U_j` underlying a point of `Spec Γ(U_j)`, under the chart `j`. -/
abbrev chartBaseι (j : 𝓔.bundle.J) :
    Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)) ⟶ X :=
  (isAffineOpen X (𝓔.bundle.chart j)).isoSpec.inv ≫ (𝓔.bundle.chart j).1.ι

/-- `chartBaseι` is an open immersion, in particular injective. -/
instance isOpenImmersion_chartBaseι (j : 𝓔.bundle.J) : IsOpenImmersion (𝓔.chartBaseι j) := by
  unfold chartBaseι
  infer_instance

/-- `chartBaseι j` sends the prime of a point `x ∈ U_j` back to `x`. -/
theorem chartBaseι_chartBasePoint (j : 𝓔.bundle.J) (x : (𝓔.bundle.chart j).1.toScheme) :
    (𝓔.chartBaseι j).base (𝓔.bundle.chartBasePoint j x) = (𝓔.bundle.chart j).1.ι.base x := by
  change ((isAffineOpen X (𝓔.bundle.chart j)).isoSpec.hom ≫
    (isAffineOpen X (𝓔.bundle.chart j)).isoSpec.inv ≫ (𝓔.bundle.chart j).1.ι).base x = _
  rw [Iso.hom_inv_id_assoc]

/-- A point of `P(E ⊕ 1)` lying over `U_j` is in the image of `chartProjι j`. -/
theorem mem_range_chartProjι_of_mem (j : 𝓔.bundle.J) {z : 𝓔.projectiveCompletion}
    (hz : 𝓔.completionToBase.base z ∈ (𝓔.bundle.chart j).1) :
    z ∈ Set.range (𝓔.chartProjι j).base := by
  rw [range_chartProjι]
  exact hz

/-- The coordinate point of `P(E ⊕ 1)` over the point `𝔭` of `Spec Γ(U_j)`, for the set of
homogeneous coordinates `S ⊆ Option ι`, computed in the chart `(j, i)` (meaningful for `i ∉ S`,
see `coordPoint_congr`): the generic point of the coordinate subspace `{x_s = 0 : s ∈ S}` of the
fibre. -/
def coordPoint (j : 𝓔.bundle.J) (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1))))
    (S : Set (Option ι)) (i : Option ι) : 𝓔.projectiveCompletion :=
  (𝓔.chartProjι j).base (projCoordPoint 𝔭 S i)

/-- The chart description of the coordinate point: in the chart `(j, i)` it is the prime
`𝔭 · Γ(U_j)[x] + (x_s / x_i : s ∈ S)` (whose variables are indexed by `chartSet i S`). -/
theorem coordPoint_eq_completionChart (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    (i : Option ι) :
    𝓔.coordPoint j 𝔭 S i =
      (𝓔.completionChart (j, i)).base (coordIdealPoint 𝔭.asIdeal (chartSet i S)) :=
  rfl

/-- The coordinate point does not depend on the chart `i ∉ S` used to compute it. -/
theorem coordPoint_congr (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i i' : Option ι} (hi : i ∉ S) (hi' : i' ∉ S) :
    𝓔.coordPoint j 𝔭 S i = 𝓔.coordPoint j 𝔭 S i' := by
  rw [coordPoint, coordPoint, projCoordPoint_congr 𝔭 S hi hi']

/-- The coordinate point lies over `𝔭`. -/
theorem completionToBase_coordPoint (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    (i : Option ι) :
    𝓔.completionToBase.base (𝓔.coordPoint j 𝔭 S i) = (𝓔.chartBaseι j).base 𝔭 := by
  rw [coordPoint, completionToBase_chartProjι_apply, projection_projCoordPoint]

/-- The coordinate point over `x ∈ U_j` lies over `x`. -/
theorem completionToBase_coordPoint_chartBasePoint (j : 𝓔.bundle.J)
    (x : (𝓔.bundle.chart j).1.toScheme) (S : Set (Option ι)) (i : Option ι) :
    𝓔.completionToBase.base (𝓔.coordPoint j (𝓔.bundle.chartBasePoint j x) S i) =
      (𝓔.bundle.chart j).1.ι.base x := by
  rw [completionToBase_coordPoint, chartBaseι_chartBasePoint]

/-- The coordinate point lies in `chartProjι j`. -/
theorem coordPoint_mem_range_chartProjι (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    (i : Option ι) : 𝓔.coordPoint j 𝔭 S i ∈ Set.range (𝓔.chartProjι j).base :=
  ⟨_, rfl⟩

/-- A point of `chartProjι j` lies in the chart `(j, s)` iff its preimage lies in `D₊(x_s)`. -/
theorem chartProjι_mem_range_completionChart_iff (j : 𝓔.bundle.J) (s : Option ι)
    (z : Proj (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1))) :
    (𝓔.chartProjι j).base z ∈ Set.range (𝓔.completionChart (j, s)).base ↔
      z ∈ Proj.basicOpen (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1))
        (MvPolynomial.X s) := by
  have h : z ∈ Proj.basicOpen (homogeneousSubmodule (Option ι) Γ(X, (𝓔.bundle.chart j).1))
      (MvPolynomial.X s) ↔ z ∈ Set.range (projOptionChart _ ι s).base := by
    rw [range_projOptionChart]
    exact Iff.rfl
  rw [h]
  constructor
  · rintro ⟨y, hy⟩
    refine ⟨y, (𝓔.chartProjι j).isOpenEmbedding.injective ?_⟩
    rw [← hy]
    rfl
  · rintro ⟨y, rfl⟩
    exact ⟨y, rfl⟩

/-- The coordinate point computed in the chart `(j, i)`, `i ∉ S`, lies in the chart `(j, s)` iff
`s ∉ S`. -/
theorem coordPoint_mem_range_completionChart_iff (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) (s : Option ι) :
    𝓔.coordPoint j 𝔭 S i ∈ Set.range (𝓔.completionChart (j, s)).base ↔ s ∉ S := by
  rw [coordPoint, chartProjι_mem_range_completionChart_iff, projCoordPoint_mem_basicOpen_iff 𝔭 S hi]

/-- The coordinate subspace `{x_s = 0 : s ∈ S}` of the fibre of `P(E ⊕ 1)` over the point `𝔭`
of `U_j`: the points of `P(E ⊕ 1)` over `𝔭` lying in none of the charts `(j, s)`, `s ∈ S`. -/
def coordSet (j : 𝓔.bundle.J) (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1))))
    (S : Set (Option ι)) : Set 𝓔.projectiveCompletion :=
  {z | (∀ s ∈ S, z ∉ Set.range (𝓔.completionChart (j, s)).base) ∧
    𝓔.completionToBase.base z = (𝓔.chartBaseι j).base 𝔭}

/-- `coordSet` is antitone in `S`. -/
theorem coordSet_anti (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) {S S' : Set (Option ι)}
    (h : S ⊆ S') : 𝓔.coordSet j 𝔭 S' ⊆ 𝓔.coordSet j 𝔭 S :=
  fun _ hz ↦ ⟨fun s hs ↦ hz.1 s (h hs), hz.2⟩

/-- A point of the coordinate subspace of `P(E ⊕ 1)` comes from a point of the coordinate
subspace of `Proj Γ(U_j)[x]`. -/
theorem exists_of_mem_coordSet (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {z : 𝓔.projectiveCompletion} (hz : z ∈ 𝓔.coordSet j 𝔭 S) :
    ∃ z' ∈ projCoordSet 𝔭 S, (𝓔.chartProjι j).base z' = z := by
  have hz' : z ∈ Set.range (𝓔.chartProjι j).base := by
    refine 𝓔.mem_range_chartProjι_of_mem j ?_
    rw [hz.2]
    exact Subtype.property _
  obtain ⟨z', rfl⟩ := hz'
  refine ⟨z', ⟨fun s hs h ↦ hz.1 s hs ?_, ?_⟩, rfl⟩
  · exact (𝓔.chartProjι_mem_range_completionChart_iff j s z').mpr h
  · have h2 := hz.2
    rw [completionToBase_chartProjι_apply] at h2
    exact (𝓔.chartBaseι j).isOpenEmbedding.injective h2

/-- The coordinate point lies in the coordinate subspace. -/
theorem coordPoint_mem_coordSet (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) : 𝓔.coordPoint j 𝔭 S i ∈ 𝓔.coordSet j 𝔭 S :=
  ⟨fun s hs h ↦ (𝓔.coordPoint_mem_range_completionChart_iff j 𝔭 S hi s).mp h hs,
    𝓔.completionToBase_coordPoint j 𝔭 S i⟩

/-- **The coordinate point is the generic point of the coordinate subspace**: it specialises to
every point of `coordSet j 𝔭 S`. -/
theorem coordPoint_specializes (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) {z : 𝓔.projectiveCompletion} (hz : z ∈ 𝓔.coordSet j 𝔭 S) :
    𝓔.coordPoint j 𝔭 S i ⤳ z := by
  obtain ⟨z', hz', rfl⟩ := 𝓔.exists_of_mem_coordSet j 𝔭 S hz
  exact (projCoordPoint_specializes 𝔭 S hi hz').map (𝓔.chartProjι j).continuous

/-- A point of the coordinate subspace which specialises to the coordinate point is the
coordinate point. -/
theorem eq_coordPoint_of_specializes (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) {z : 𝓔.projectiveCompletion} (hz : z ∈ 𝓔.coordSet j 𝔭 S)
    (h : z ⤳ 𝓔.coordPoint j 𝔭 S i) : z = 𝓔.coordPoint j 𝔭 S i :=
  (h.antisymm (𝓔.coordPoint_specializes j 𝔭 S hi hz)).eq

/-- Coordinate points specialise along inclusions of the sets of coordinates. -/
theorem coordPoint_specializes_of_subset (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) {S S' : Set (Option ι)}
    (hSS' : S ⊆ S') {i i' : Option ι} (hi : i ∉ S) (hi' : i' ∉ S') :
    𝓔.coordPoint j 𝔭 S i ⤳ 𝓔.coordPoint j 𝔭 S' i' :=
  𝓔.coordPoint_specializes j 𝔭 S hi
    (𝓔.coordSet_anti j 𝔭 hSS' (𝓔.coordPoint_mem_coordSet j 𝔭 S' hi'))

/-- The coordinate point for `S = ∅` is the generic point of the fibre. -/
theorem fibrePoint_eq_coordPoint (j : 𝓔.bundle.J) (x : (𝓔.bundle.chart j).1.toScheme)
    (i : Option ι) :
    AffineCharts.fibrePoint 𝓔.completionCharts ((𝓔.bundle.chart j).1.ι.base x) =
      𝓔.coordPoint j (𝓔.bundle.chartBasePoint j x) ∅ i := by
  rw [AffineCharts.fibrePoint_chart 𝓔.completionCharts (j, i) x, AffineCharts.chartPoint,
    coordPoint_eq_completionChart, completionCharts_chartι]
  congr 1
  refine PrimeSpectrum.ext ?_
  change Ideal.map (algebraMap Γ(X, (𝓔.bundle.chart j).1)
      (MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1))) (𝓔.bundle.chartBasePoint j x).asIdeal =
    coordIdeal (𝓔.bundle.chartBasePoint j x).asIdeal (chartSet i ∅)
  rw [chartSet_empty, coordIdeal_empty, algebraMap_eq]

/-! ### The hyperplane at infinity -/

/-- A point of `P(E ⊕ 1)` over `U_j` lies in `E` iff it lies in the chart `(j, none)`. -/
theorem mem_range_bundleOpenEmbedding_iff (j : 𝓔.bundle.J) {z : 𝓔.projectiveCompletion}
    (hz : 𝓔.completionToBase.base z ∈ (𝓔.bundle.chart j).1) :
    z ∈ Set.range 𝓔.bundleOpenEmbedding.base ↔
      z ∈ Set.range (𝓔.completionChart (j, none)).base := by
  rw [← bundleOpenEmbedding_chartι_none]
  constructor
  · rintro ⟨e, rfl⟩
    have he : e ∈ (𝓔.bundle.chartι j).opensRange := by
      rw [𝓔.bundle.opensRange_chartι]
      change 𝓔.bundle.proj.base e ∈ (𝓔.bundle.chart j).1
      have h : 𝓔.bundle.proj.base e =
          𝓔.completionToBase.base (𝓔.bundleOpenEmbedding.base e) := by
        rw [← bundleOpenEmbedding_toBase]
        rfl
      rw [h]
      exact hz
    obtain ⟨y, hy⟩ := he
    refine ⟨y, ?_⟩
    change 𝓔.bundleOpenEmbedding.base ((𝓔.bundle.chartι j).base y) = _
    rw [hy]
  · rintro ⟨y, rfl⟩
    exact ⟨(𝓔.bundle.chartι j).base y, rfl⟩

/-- The chart `(j, none)` lies in `E`. -/
theorem range_completionChart_none_subset (j : 𝓔.bundle.J) :
    Set.range (𝓔.completionChart (j, none)).base ⊆ Set.range 𝓔.bundleOpenEmbedding.base := by
  rw [← bundleOpenEmbedding_chartι_none]
  rintro _ ⟨y, rfl⟩
  exact ⟨(𝓔.bundle.chartι j).base y, rfl⟩

/-- The hyperplane at infinity of the fibre over `x`: the points of `P(E ⊕ 1)` over `x` not in
`E`. -/
def hyperSet (x : X) : Set 𝓔.projectiveCompletion :=
  {z | z ∉ Set.range 𝓔.bundleOpenEmbedding.base ∧ 𝓔.completionToBase.base z = x}

/-- `chartBaseι j` sends the prime of a point `x ∈ U_j` back to `x`. -/
theorem chartBaseι_chartBasePoint' (j : 𝓔.bundle.J) {x : X} (hx : x ∈ (𝓔.bundle.chart j).1) :
    (𝓔.chartBaseι j).base (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) = x :=
  𝓔.chartBaseι_chartBasePoint j ⟨x, hx⟩

/-- Over `x ∈ U_j`, the hyperplane at infinity of the fibre is the coordinate subspace
`{x_none = 0}`. -/
theorem coordSet_singleton_none (j : 𝓔.bundle.J) {x : X} (hx : x ∈ (𝓔.bundle.chart j).1) :
    𝓔.coordSet j (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) {none} = 𝓔.hyperSet x := by
  ext z
  constructor
  · rintro ⟨h1, h2⟩
    rw [chartBaseι_chartBasePoint'] at h2
    refine ⟨fun h ↦ h1 none rfl ?_, h2⟩
    rwa [← 𝓔.mem_range_bundleOpenEmbedding_iff j (by rw [h2]; exact hx)]
  · rintro ⟨h1, h2⟩
    refine ⟨fun s hs h ↦ h1 ?_, ?_⟩
    · rw [Set.mem_singleton_iff] at hs
      subst hs
      rwa [𝓔.mem_range_bundleOpenEmbedding_iff j (by rw [h2]; exact hx)]
    · rw [chartBaseι_chartBasePoint']
      exact h2

/-- The coordinate point `{x_none = 0}` over `x ∈ U_j` lies in the hyperplane at infinity. -/
theorem coordPoint_singleton_none_mem_hyperSet (j : 𝓔.bundle.J) {x : X}
    (hx : x ∈ (𝓔.bundle.chart j).1) (i : ι) :
    𝓔.coordPoint j (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) {none} (some i) ∈ 𝓔.hyperSet x := by
  rw [← coordSet_singleton_none]
  exact 𝓔.coordPoint_mem_coordSet j _ _ (by simp)

/-- The coordinate point `{x_none = 0}` over `x ∈ U_j` specialises to every point of the
hyperplane at infinity over `x`. -/
theorem coordPoint_singleton_none_specializes (j : 𝓔.bundle.J) {x : X}
    (hx : x ∈ (𝓔.bundle.chart j).1) (i : ι) {z : 𝓔.projectiveCompletion}
    (hz : z ∈ 𝓔.hyperSet x) :
    𝓔.coordPoint j (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) {none} (some i) ⤳ z := by
  rw [← coordSet_singleton_none 𝓔 j hx] at hz
  exact 𝓔.coordPoint_specializes j _ _ (by simp) hz

section HyperPoint

variable [Nonempty ι]

/-- The generic point of the hyperplane at infinity `P(E)_x ⊆ P(E ⊕ 1)_x` of the fibre over
`x`: the coordinate point `{x_none = 0}` computed in a chart `(j, some i)` with `x ∈ U_j`
(independence of the choices is `hyperPoint_eq_coordPoint`). -/
def hyperPoint (x : X) : 𝓔.projectiveCompletion :=
  𝓔.coordPoint (BundlePullbackGlobal.chartIndex 𝓔.bundle x)
    (𝓔.bundle.chartBasePoint _ ⟨x, BundlePullbackGlobal.mem_chart_chartIndex 𝓔.bundle x⟩)
    {none} (some (Classical.arbitrary ι))

/-- `hyperPoint x` is the coordinate point `{x_none = 0}` in every chart `(j, some i)` with
`x ∈ U_j`. -/
theorem hyperPoint_eq_coordPoint {x : X} {j : 𝓔.bundle.J} (hx : x ∈ (𝓔.bundle.chart j).1)
    (i : ι) :
    𝓔.hyperPoint x = 𝓔.coordPoint j (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) {none} (some i) := by
  have h1 := 𝓔.coordPoint_singleton_none_mem_hyperSet j hx i
  have h2 := 𝓔.coordPoint_singleton_none_mem_hyperSet _
    (BundlePullbackGlobal.mem_chart_chartIndex 𝓔.bundle x) (Classical.arbitrary ι)
  exact ((𝓔.coordPoint_singleton_none_specializes _ _ _ h1).antisymm
    (𝓔.coordPoint_singleton_none_specializes _ _ _ h2)).eq

/-- `hyperPoint x` lies in the hyperplane at infinity over `x`. -/
theorem hyperPoint_mem_hyperSet (x : X) : 𝓔.hyperPoint x ∈ 𝓔.hyperSet x :=
  𝓔.coordPoint_singleton_none_mem_hyperSet _ (BundlePullbackGlobal.mem_chart_chartIndex _ x) _

/-- `hyperPoint x` lies over `x`. -/
theorem completionToBase_hyperPoint (x : X) :
    𝓔.completionToBase.base (𝓔.hyperPoint x) = x :=
  (𝓔.hyperPoint_mem_hyperSet x).2

/-- `hyperPoint x` is not in `E`. -/
theorem hyperPoint_notMem_range_bundleOpenEmbedding (x : X) :
    𝓔.hyperPoint x ∉ Set.range 𝓔.bundleOpenEmbedding.base :=
  (𝓔.hyperPoint_mem_hyperSet x).1

/-- `hyperPoint x` lies on the divisor at infinity `P(E)`. -/
theorem hyperPoint_mem_range_infinityDivisor (x : X) :
    𝓔.hyperPoint x ∈ Set.range 𝓔.infinityDivisor.base := by
  have h := 𝓔.hyperPoint_notMem_range_bundleOpenEmbedding x
  rw [range_bundleOpenEmbedding] at h
  simpa using h

/-- **`hyperPoint x` is the generic point of the hyperplane at infinity over `x`**: it
specialises to every point of `P(E ⊕ 1)` over `x` which is not in `E`. -/
theorem hyperPoint_specializes {x : X} {z : 𝓔.projectiveCompletion}
    (hz : z ∉ Set.range 𝓔.bundleOpenEmbedding.base) (hqz : 𝓔.completionToBase.base z = x) :
    𝓔.hyperPoint x ⤳ z :=
  𝓔.coordPoint_singleton_none_specializes _ _ _ ⟨hz, hqz⟩

/-- A point of the hyperplane at infinity over `x` which specialises to `hyperPoint x` is
`hyperPoint x`. -/
theorem hyperPoint_eq_of_specializes {x : X} {z : 𝓔.projectiveCompletion}
    (hz : z ∉ Set.range 𝓔.bundleOpenEmbedding.base) (hqz : 𝓔.completionToBase.base z = x)
    (h : z ⤳ 𝓔.hyperPoint x) : z = 𝓔.hyperPoint x :=
  (h.antisymm (𝓔.hyperPoint_specializes hz hqz)).eq

/-- **Chart description of `hyperPoint`**: for `x ∈ U_j` with prime `𝔭_x ⊆ Γ(U_j)` and `i : ι`,
`hyperPoint x` is the image under the chart `(j, some i)` of the prime
`𝔭_x · Γ(U_j)[x] + (X i)` (the variable `X i` of this chart being `x_none / x_i`). -/
theorem hyperPoint_chart {x : X} {j : 𝓔.bundle.J} (hx : x ∈ (𝓔.bundle.chart j).1) (i : ι) :
    𝓔.hyperPoint x = (𝓔.completionChart (j, some i)).base
      (coordIdealPoint (𝓔.bundle.chartBasePoint j ⟨x, hx⟩).asIdeal {i}) := by
  rw [hyperPoint_eq_coordPoint 𝓔 hx i, coordPoint_eq_completionChart,
    chartSet_some_singleton_none]

/-- `hyperPoint x` lies in every chart `(j, some i)` with `x ∈ U_j`. -/
theorem hyperPoint_mem_range_completionChart_some {x : X} {j : 𝓔.bundle.J}
    (hx : x ∈ (𝓔.bundle.chart j).1) (i : ι) :
    𝓔.hyperPoint x ∈ Set.range (𝓔.completionChart (j, some i)).base :=
  ⟨_, (𝓔.hyperPoint_chart hx i).symm⟩

/-- `hyperPoint x` lies in no chart `(j, none)`. -/
theorem hyperPoint_notMem_range_completionChart_none (x : X) (j : 𝓔.bundle.J) :
    𝓔.hyperPoint x ∉ Set.range (𝓔.completionChart (j, none)).base :=
  fun h ↦ 𝓔.hyperPoint_notMem_range_bundleOpenEmbedding x
    (𝓔.range_completionChart_none_subset j h)

/-- The generic point of the fibre over `x` specialises to `hyperPoint x`. -/
theorem fibrePoint_specializes_hyperPoint (x : X) :
    AffineCharts.fibrePoint 𝓔.completionCharts x ⤳ 𝓔.hyperPoint x := by
  rw [AffineCharts.fibrePoint_specializes_iff, completionToBase_hyperPoint]

/-- The generic point of the fibre over `x` is not `hyperPoint x`. -/
theorem fibrePoint_ne_hyperPoint (x : X) :
    AffineCharts.fibrePoint 𝓔.completionCharts x ≠ 𝓔.hyperPoint x := by
  intro h
  refine 𝓔.hyperPoint_notMem_range_bundleOpenEmbedding x ?_
  rw [← h, fibrePoint_completionCharts]
  exact ⟨_, rfl⟩

/-- `hyperPoint` is injective. -/
theorem hyperPoint_injective : Function.Injective 𝓔.hyperPoint := fun x y h ↦ by
  rw [← 𝓔.completionToBase_hyperPoint x, ← 𝓔.completionToBase_hyperPoint y, h]

end HyperPoint

/-! ### The dimension shift of the charted pullback along `P(E ⊕ 1) → X` -/

section Dimension

variable {k : Type u} [Field k] (f : X ⟶ Spec (CommRingCat.of k)) [LocallyOfFiniteType f]

/-- The canonical dimension function only depends on the structure morphism. -/
theorem dimensionFunction_congr_hom
    {Y : Scheme.{u}} {g g' : Y ⟶ Spec (CommRingCat.of k)} [LocallyOfFiniteType g]
    [LocallyOfFiniteType g'] (h : g = g') (y : Y) :
    FiniteTypeDimension.dimensionFunction g y = FiniteTypeDimension.dimensionFunction g' y := by
  subst h
  rfl

/-- **The dimension shift along `P(E ⊕ 1) → X`**: the generic point of the fibre over `x` has
dimension `dim x + rank`. This is the hypothesis `hshift` of `chowPullbackCharted` for the charts
`completionCharts`. -/
theorem dimensionFunction_fibrePoint_completionCharts [Finite ι] (x : X) :
    FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f)
        (AffineCharts.fibrePoint 𝓔.completionCharts x) =
      FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) := by
  rw [fibrePoint_completionCharts,
    ← FiniteTypeDimension.dimensionFunction_comp (𝓔.completionToBase ≫ f) 𝓔.bundleOpenEmbedding,
    dimensionFunction_congr_hom (g' := 𝓔.bundle.proj ≫ f)
      (by rw [← Category.assoc, bundleOpenEmbedding_toBase])]
  exact FiniteTypeDimension.dimensionFunction_bundlePoint f 𝓔.bundle x

end Dimension

/-! ### The transition units of `O(1)` through the charts -/

section Transition

/-- The homogeneous coordinate `x_none` over any chart is the homogenising variable `t`. -/
theorem homogCoord_none (j : 𝓔.bundle.J) :
    𝓔.homogCoord j none =
      (Polynomial.X : Polynomial (𝓔.bundle.algebra.ring (𝓔.bundle.chart j))) := by
  rw [homogCoord, ← chartGraded_X]
  exact GradedRingHom.congr_fun (𝓔.chartGradedInv_comp_chartGraded j) _

/-- The restricted homogeneous coordinate `x_none` is the homogenising variable `t`. -/
theorem homogCoordAt_none (j : 𝓔.bundle.J) (V : X.affineOpens) (h : V ≤ 𝓔.bundle.chart j) :
    𝓔.homogCoordAt (j, none) V h = (Polynomial.X : Polynomial (𝓔.bundle.algebra.ring V)) := by
  rw [homogCoordAt, homogCoord_none]
  change homogMap _ Polynomial.X = _
  rw [homogMap_apply, Polynomial.map_X]
  rfl

/-- `ratioUnit` of two equal elements is `1`. -/
theorem ratioUnit_eq_one_of_eq {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    {𝒢 : ℕ → Submodule R S} [GradedAlgebra 𝒢] {s t : S} (hs : s ∈ 𝒢 1) (ht : t ∈ 𝒢 1)
    (h : s = t) : ratioUnit hs ht = 1 := by
  subst h
  exact ratioUnit_self hs ht

variable (hX : ∀ U V : X.affineOpens, IsAffineOpen (U.1 ⊓ V.1))

set_option backward.isDefEq.respectTransparency false in
/-- The transition unit of `O(1)` between two charts at `x_none` is `1`: both coordinates are
the homogenising variable `t`. -/
theorem tautTransition_none_none (j j' : 𝓔.bundle.J) :
    𝓔.tautTransition hX (j', none) (j, none) = 1 := by
  rw [tautTransition, ratioUnit_eq_one_of_eq _ _ (by rw [homogCoordAt_none, homogCoordAt_none]),
    map_one]

/-- `chartGraded j` sends the homogeneous coordinate `x_i` to the variable `X i`. -/
theorem chartGraded_homogCoord (j : 𝓔.bundle.J) (i : Option ι) :
    𝓔.chartGraded j (𝓔.homogCoord j i) = MvPolynomial.X i :=
  GradedRingHom.congr_fun (𝓔.chartGraded_comp_chartGradedInv j) _

/-- The identification of the coordinate ring `(𝒜[t](U_j))_(x_i)` of the chart `D₊(x_i)` with
the polynomial ring `Γ(U_j)[x_k : k ∈ ι]`: the graded identification `chartGraded j` followed by
the dehomogenisation `dehomAt` at `x_i`. -/
def chartAwayEquiv (j : 𝓔.bundle.J) (i : Option ι) :
    Away (𝓔.homogData.grading (𝓔.bundle.chart j)) (𝓔.homogCoord j i) ≃+*
      MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1) :=
  RingEquiv.ofBijective ((dehomAt Γ(X, (𝓔.bundle.chart j).1) i).toRingHom.comp
      (awayMapOfEq (𝓔.chartGraded j) (𝓔.homogCoord j i) (MvPolynomial.X i)
        (𝓔.chartGraded_homogCoord j i)))
    ((dehomAt Γ(X, (𝓔.bundle.chart j).1) i).bijective.comp
      (awayMapOfEq_bijective (𝓔.chartGraded j) (𝓔.chartGradedInv j)
      (fun a ↦ GradedRingHom.congr_fun (𝓔.chartGradedInv_comp_chartGraded j) a)
      (fun b ↦ GradedRingHom.congr_fun (𝓔.chartGraded_comp_chartGradedInv j) b) _
      (𝓔.homogCoord_mem j i) _ _))

/-- The value of `chartAwayEquiv`. -/
theorem chartAwayEquiv_apply (j : 𝓔.bundle.J) (i : Option ι)
    (z : Away (𝓔.homogData.grading (𝓔.bundle.chart j)) (𝓔.homogCoord j i)) :
    𝓔.chartAwayEquiv j i z = dehomAt Γ(X, (𝓔.bundle.chart j).1) i
      (awayMapOfEq (𝓔.chartGraded j) (𝓔.homogCoord j i)
      (MvPolynomial.X i) (𝓔.chartGraded_homogCoord j i) z) :=
  rfl

/-- The chart `(j, i)` of `P(E ⊕ 1)` is `Spec` of `chartAwayEquiv` followed by the chart
`D₊(x_i)` of the tautological bundle. -/
theorem completionChart_eq_specMap_tautChart (j : 𝓔.bundle.J) (i : Option ι) :
    𝓔.completionChart (j, i) =
      Spec.map (CommRingCat.ofHom (𝓔.chartAwayEquiv j i).toRingHom) ≫ 𝓔.tautChart (j, i) := by
  rw [completionChart, projOptionChart, tautChart, awayChart]
  change (Spec.map (CommRingCat.ofHom (dehomAt Γ(X, (𝓔.bundle.chart j).1) i).toRingHom) ≫
    Proj.awayι _ (MvPolynomial.X i) (X_mem_homogeneousSubmodule_one i) one_pos) ≫
      Proj.map (𝓔.chartGraded j) _ ≫ affineι X 𝓔.homogData (𝓔.bundle.chart j) = _
  rw [Category.assoc, reassoc_of% (awayι_comp_projMap_of_eq (𝓔.chartGraded j) _ one_pos
    (𝓔.homogCoord j i) (𝓔.homogCoord_mem j i) (MvPolynomial.X i) (𝓔.chartGraded_homogCoord j i)
    (X_mem_homogeneousSubmodule_one i)), ← Category.assoc, ← Spec.map_comp]
  rfl

/-- The chart `D₊(x_i)` of the tautological bundle is `Spec` of the inverse of `chartAwayEquiv`
followed by the chart `(j, i)` of `P(E ⊕ 1)`. -/
theorem tautChart_eq_specMap_completionChart (j : 𝓔.bundle.J) (i : Option ι) :
    𝓔.tautChart (j, i) =
      Spec.map (CommRingCat.ofHom (𝓔.chartAwayEquiv j i).symm.toRingHom) ≫
        𝓔.completionChart (j, i) := by
  rw [completionChart_eq_specMap_tautChart, ← Category.assoc, ← Spec.map_comp]
  have h : CommRingCat.ofHom (𝓔.chartAwayEquiv j i).toRingHom ≫
      CommRingCat.ofHom (𝓔.chartAwayEquiv j i).symm.toRingHom = 𝟙 _ := by
    refine CommRingCat.hom_ext (RingHom.ext fun z ↦ ?_)
    exact (𝓔.chartAwayEquiv j i).symm_apply_apply z
  rw [h, Spec.map_id, Category.id_comp]

/-- `x_a x_b` is `x_a|_{U_j ∩ U_{j'}}` times `x_b|_{U_j ∩ U_{j'}}`, in the form needed by
`awayChart_map_mul`. -/
theorem overlapElem_eq_map_mul (a b : 𝓔.TautIndex) :
    𝓔.overlapElem hX a b = 𝓔.homogData.map (𝓔.overlapBase_le_left hX a b) (𝓔.homogCoord a.1 a.2) *
      𝓔.homogCoordAt b _ (𝓔.overlapBase_le_right hX a b) :=
  rfl

/-- The ring map `Γ(U_j)[x_k : k ∈ ι] → (𝒜[t](U_j ∩ U_j))_(x_i x_{i'})` from the coordinate
ring of the chart `(j, i)` to that of the overlap chart `D₊(x_i x_{i'})`: the inverse of
`chartAwayEquiv`, restriction to `U_j ∩ U_j`, and localisation at `x_{i'} / x_i`. -/
def overlapToChart (j : 𝓔.bundle.J) (i i' : Option ι) :
    MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1) →+*
      Away (𝓔.homogData.grading (𝓔.overlapBase hX (j, i) (j, i')))
        (𝓔.overlapElem hX (j, i) (j, i')) :=
  ((awayMap _ (𝓔.homogCoordAt_mem (j, i') _ (𝓔.overlapBase_le_right hX (j, i) (j, i')))
      (𝓔.overlapElem_eq_map_mul hX (j, i) (j, i'))).comp
    (Away.map (𝓔.homogData.map (𝓔.overlapBase_le_left hX (j, i) (j, i'))) (𝓔.homogCoord j i))).comp
      (𝓔.chartAwayEquiv j i).symm.toRingHom

/-- The overlap chart `D₊(x_i x_{i'})` over `U_j ∩ U_j` factors through the chart `(j, i)` of
`P(E ⊕ 1)` via `overlapToChart`. -/
theorem overlapChart_eq_specMap_completionChart (j : 𝓔.bundle.J) (i i' : Option ι) :
    𝓔.overlapChart hX (j, i) (j, i') =
      Spec.map (CommRingCat.ofHom (𝓔.overlapToChart hX j i i')) ≫ 𝓔.completionChart (j, i) := by
  rw [overlapChart, awayChart_map_mul 𝓔.homogData (𝓔.overlapBase_le_left hX (j, i) (j, i'))
    (𝓔.homogCoord j i) (𝓔.homogCoord_mem j i) one_pos _
    (𝓔.homogCoordAt_mem (j, i') _ (𝓔.overlapBase_le_right hX (j, i) (j, i'))) _
    (𝓔.overlapElem_eq_map_mul hX (j, i) (j, i'))]
  change _ ≫ 𝓔.tautChart (j, i) = _
  rw [tautChart_eq_specMap_completionChart, ← Category.assoc, ← Spec.map_comp]
  rfl

open Classical in
/-- The inverse of `chartAwayEquiv j i` sends the coordinate `optionCoordVar i s` (which is
`x_s / x_i`) to `x_s / x_i`. -/
theorem chartAwayEquiv_symm_optionCoordVar (j : 𝓔.bundle.J) (i s : Option ι) :
    (𝓔.chartAwayEquiv j i).symm (optionCoordVar i s) =
      Away.mk _ (𝓔.homogCoord_mem j i) 1 (𝓔.homogCoord j s)
        (by rw [one_smul]; exact 𝓔.homogCoord_mem j s) := by
  rw [RingEquiv.symm_apply_eq, chartAwayEquiv_apply,
    awayMapOfEq_mk _ _ _ _ (𝓔.homogCoord_mem j i) (X_mem_homogeneousSubmodule_one i),
    dehomAt_mk, chartGraded_homogCoord, rename_X, optionCoordVar]
  generalize Equiv.swap none i s = t
  cases t with
  | none => rw [optionEquivLeft_X_none, Polynomial.eval_X]; rfl
  | some k => rw [optionEquivLeft_X_some, Polynomial.eval_C]; rfl

/-- `overlapToChart` for the charts `(j, i)` and `(j, s)` sends the coordinate
`optionCoordVar i s` (which is `x_s / x_i`) to `x_s² / (x_i x_s)`, the value of the transition
unit. -/
theorem overlapToChart_optionCoordVar (j : 𝓔.bundle.J) (i s : Option ι) :
    𝓔.overlapToChart hX j i s (optionCoordVar i s) =
      Away.mk _ (𝓔.overlapElem_mem hX (j, i) (j, s)) 1
        (𝓔.homogCoordAt (j, s) _ (𝓔.overlapBase_le_right hX (j, i) (j, s)) ^ 2)
        (sq_mem_one_smul_two (𝓔.homogCoordAt_mem (j, s) _ _)) := by
  rw [overlapToChart, RingHom.comp_apply, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingHom.coe_coe, chartAwayEquiv_symm_optionCoordVar, Away.map_mk, awayMap_mk]
  apply HomogeneousLocalization.val_injective
  rw [Away.val_mk, Away.val_mk, Localization.mk_eq_mk_iff, Localization.r_iff_exists]
  refine ⟨1, ?_⟩
  simp only [OneMemClass.coe_one, one_mul, pow_one, homogCoordAt]
  ring

set_option backward.isDefEq.respectTransparency false in
/-- **The transition unit `x_s / x_i` of `O(1)`** between the charts `(j, i)` and `(j, s)` is
the restriction to the overlap of the coordinate `optionCoordVar i s` of the chart `(j, i)`
(read as a section over `D₊(x_i)` through `sectionsEquiv`): the variable `X k` with `σ(k) = s`
for `s ≠ i`, and `1` for `s = i`. -/
theorem tautTransition_val (j : 𝓔.bundle.J) (i s : Option ι) :
    (𝓔.tautTransition hX (j, i) (j, s) : Γ(𝓔.projectiveCompletion, _)) =
      𝓔.projectiveCompletion.presheaf.map (homOfLE (inf_le_left :
        (𝓔.tautOpen (j, i) : 𝓔.projectiveCompletion.Opens) ⊓
          (𝓔.tautOpen (j, s) : 𝓔.projectiveCompletion.Opens) ≤
          (𝓔.tautOpen (j, i) : 𝓔.projectiveCompletion.Opens))).op
        ((sectionsEquiv (𝓔.completionChart (j, i)) _
          (𝓔.opensRange_completionChart (j, i))).symm (optionCoordVar i s)) := by
  apply (sectionsToRing_bijective (𝓔.overlapChart hX (j, i) (j, s)) _
    (𝓔.opensRange_overlapChart hX (j, i) (j, s))).injective
  rw [sectionsToRing_tautTransition, sectionsToRing_res (𝓔.completionChart (j, i))
    (𝓔.overlapChart hX (j, i) (j, s)) _
    (𝓔.overlapChart_eq_specMap_completionChart hX j i s)
    (𝓔.opensRange_completionChart (j, i)).le (𝓔.opensRange_overlapChart hX _ _).le
    inf_le_left]
  change _ = 𝓔.overlapToChart hX j i s
    (sectionsEquiv _ _ (𝓔.opensRange_completionChart (j, i)) ((sectionsEquiv _ _
      (𝓔.opensRange_completionChart (j, i))).symm (optionCoordVar i s)))
  rw [RingEquiv.apply_symm_apply, overlapToChart_optionCoordVar]

end Transition

end GradedBundleData

/-! ### Residues of sections through an affine chart -/

/-- The residue at a point `ψ 𝔮` of the image of an affine open immersion `ψ : Spec A ⟶ P` of a
section `s` over an open `O ⊇ ψ(Spec A)`, transported to `κ(𝔮)` along `ψ`, is the residue at `𝔮`
of the element `sectionsToRing ψ O s` of `A`. -/
theorem residueFieldMap_residue_germ_sectionsToRing {P : Scheme.{u}} {A : CommRingCat.{u}}
    (ψ : Spec A ⟶ P) [IsOpenImmersion ψ] (O : P.Opens) (hO : ψ.opensRange ≤ O) (𝔮 : Spec A)
    (hq : ψ.base 𝔮 ∈ O) (s : Γ(P, O)) :
    ψ.residueFieldMap 𝔮 (P.residue (ψ.base 𝔮) (P.presheaf.germ O (ψ.base 𝔮) hq s)) =
      (Spec A).residue 𝔮 ((Spec A).presheaf.germ ⊤ 𝔮 (Opens.mem_top 𝔮)
        ((Scheme.ΓSpecIso A).inv (sectionsToRing ψ O hO s))) := by
  have h1 : (Scheme.ΓSpecIso A).inv (sectionsToRing ψ O hO s) =
      (Spec A).presheaf.map (homOfLE (top_le_preimage_of_opensRange_le ψ hO)).op (ψ.app O s) := by
    change (Scheme.ΓSpecIso A).inv ((Scheme.ΓSpecIso A).hom _) = _
    rw [Iso.hom_inv_id_apply]
    rfl
  rw [h1, TopCat.Presheaf.germ_res_apply, ← CommRingCat.comp_apply,
    Scheme.residue_residueFieldMap, CommRingCat.comp_apply, Scheme.Hom.germ_stalkMap_apply]

namespace GradedBundleData

open IntersectionTheory VectorBundleTotalSpace
open GlobalBlowup (isAffineOpen)

variable {X : Scheme.{u}} {ι : Type u} (𝓔 : GradedBundleData X ι)
  (hX : ∀ U V : X.affineOpens, IsAffineOpen (U.1 ⊓ V.1))

set_option backward.isDefEq.respectTransparency false in
/-- **The residue of the transition unit `x_s / x_i`** at a point `w` of the chart `(j, i)` with
prime `𝔮`, transported to `κ(𝔮)`, is the residue of the coordinate `optionCoordVar i s` at
`𝔮`. -/
theorem residueFieldMap_sectionResidueUnit_tautTransition (j : 𝓔.bundle.J) (i s : Option ι)
    (𝔮 : ↥(Spec (CommRingCat.of (MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1)))))
    (hw : (𝓔.completionChart (j, i)).base 𝔮 ∈
      (𝓔.tautOpen (j, i) : 𝓔.projectiveCompletion.Opens) ⊓
        (𝓔.tautOpen (j, s) : 𝓔.projectiveCompletion.Opens)) :
    (𝓔.completionChart (j, i)).residueFieldMap 𝔮
        (sectionResidueUnit hw (𝓔.tautTransition hX (j, i) (j, s)) :
          𝓔.projectiveCompletion.residueField _) =
      (Spec (CommRingCat.of (MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1)))).residue 𝔮
        ((Spec (CommRingCat.of (MvPolynomial ι Γ(X, (𝓔.bundle.chart j).1)))).presheaf.germ ⊤ 𝔮
          (Opens.mem_top 𝔮) ((Scheme.ΓSpecIso _).inv (optionCoordVar i s))) := by
  rw [sectionResidueUnit_val, tautTransition_val, TopCat.Presheaf.germ_res_apply,
    residueFieldMap_residue_germ_sectionsToRing (𝓔.completionChart (j, i)) _
      (𝓔.opensRange_completionChart (j, i)).le 𝔮]
  have h : sectionsToRing (𝓔.completionChart (j, i)) _
      (𝓔.opensRange_completionChart (j, i)).le
      ((sectionsEquiv (𝓔.completionChart (j, i)) _
        (𝓔.opensRange_completionChart (j, i))).symm (optionCoordVar i s)) =
      optionCoordVar i s :=
    (sectionsEquiv _ _ _).apply_symm_apply _
  rw [h]

/-! ### Orders of the transition unit `x_none / x_i` along the generic fibre point -/

omit hX in
/-- Specialisation inside the chart `(j, i)` is inclusion of primes. -/
theorem completionChart_specializes_iff (k : 𝓔.bundle.J × Option ι)
    (𝔮 𝔮' : ↥(Spec (CommRingCat.of (MvPolynomial ι Γ(X, (𝓔.bundle.chart k.1).1))))) :
    (𝓔.completionChart k).base 𝔮 ⤳ (𝓔.completionChart k).base 𝔮' ↔ 𝔮.asIdeal ≤ 𝔮'.asIdeal := by
  rw [(𝓔.completionChart k).isOpenEmbedding.isInducing.specializes_iff]
  exact (PrimeSpectrum.le_iff_specializes 𝔮 𝔮').symm

/-- `sectionResidueUnit` is multiplicative. -/
theorem sectionResidueUnit_mul {Y : Scheme.{u}} {U : Y.Opens} {y : Y} (hy : y ∈ U)
    (u v : Γ(Y, U)ˣ) :
    sectionResidueUnit hy (u * v) = sectionResidueUnit hy u * sectionResidueUnit hy v :=
  map_mul (Units.map _) u v

/-- `sectionResidueUnit` of `1`. -/
theorem sectionResidueUnit_one {Y : Scheme.{u}} {U : Y.Opens} {y : Y} (hy : y ∈ U) :
    sectionResidueUnit hy (1 : Γ(Y, U)ˣ) = 1 :=
  map_one (Units.map _)

/-- `sectionResidueUnit` of a restricted unit. -/
theorem sectionResidueUnit_resUnit {Y : Scheme.{u}} {U V : Y.Opens} (h : U ≤ V) {y : Y}
    (hy : y ∈ U) (u : Γ(Y, V)ˣ) :
    sectionResidueUnit hy (resUnit h u) = sectionResidueUnit (h hy) u := by
  apply Units.ext
  rw [sectionResidueUnit_val, sectionResidueUnit_val]
  change Y.residue y (Y.presheaf.germ U y hy (Y.presheaf.map (homOfLE h).op u)) = _
  rw [TopCat.Presheaf.germ_res_apply]

set_option backward.isDefEq.respectTransparency false in
/-- The residue at a point `w` of the transition unit `x_none / x^{(j')}_i` between the charts
`(j', some i)` and `(j, none)` is the residue of the transition unit `x_none / x^{(j')}_i`
between the charts `(j', some i)` and `(j', none)`: the two coordinates `x_none` agree. -/
theorem sectionResidueUnit_tautTransition_some_none (j j' : 𝓔.bundle.J) (i : ι)
    {w : 𝓔.projectiveCompletion}
    (hw : w ∈ (𝓔.tautOpen (j', some i) : 𝓔.projectiveCompletion.Opens) ⊓
      (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens))
    (hw' : w ∈ (𝓔.tautOpen (j', some i) : 𝓔.projectiveCompletion.Opens) ⊓
      (𝓔.tautOpen (j', none) : 𝓔.projectiveCompletion.Opens)) :
    sectionResidueUnit hw (𝓔.tautTransition hX (j', some i) (j, none)) =
      sectionResidueUnit hw' (𝓔.tautTransition hX (j', some i) (j', none)) := by
  have hw'' : w ∈ ((𝓔.tautOpen (j', some i) : 𝓔.projectiveCompletion.Opens) ⊓
      (𝓔.tautOpen (j', none) : 𝓔.projectiveCompletion.Opens)) ⊓
      (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens) := ⟨hw', hw.2⟩
  have hc := 𝓔.tautTransition_cocycle hX (j', some i) (j', none) (j, none)
  have h1 := sectionResidueUnit_resUnit (inf_le_inf inf_le_left (le_refl
    (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens))) hw''
    (𝓔.tautTransition hX (j', some i) (j, none))
  rw [← hc, sectionResidueUnit_mul, sectionResidueUnit_resUnit, sectionResidueUnit_resUnit,
    tautTransition_none_none, sectionResidueUnit_one, mul_one] at h1
  exact h1.symm

open Classical in
set_option backward.isDefEq.respectTransparency false in
/-- **Orders of `x_none / x_i` along the generic fibre point**: for `x ∈ U_j`, `i : ι` and a
point `Q` of the chart `(j, some i)` specialised by the generic fibre point `w` over `x`, the
order along `w ⤳ Q` of the residue at `w` of the transition unit `x_none / x_i` of `O(1)` is `1`
if `Q = hyperPoint x` and `0` otherwise. -/
theorem pointOrd_tautTransition_fibrePoint [IsLocallyNoetherian 𝓔.projectiveCompletion]
    [Finite ι] [Nonempty ι] (j : 𝓔.bundle.J) [IsNoetherianRing Γ(X, (𝓔.bundle.chart j).1)]
    {x : X} (hx : x ∈ (𝓔.bundle.chart j).1) (i : ι) {Q : 𝓔.projectiveCompletion}
    (hQ : Q ∈ Set.range (𝓔.completionChart (j, some i)).base)
    (hwQ : AffineCharts.fibrePoint 𝓔.completionCharts x ⤳ Q)
    (hw : AffineCharts.fibrePoint 𝓔.completionCharts x ∈
      (𝓔.tautOpen (j, some i) : 𝓔.projectiveCompletion.Opens) ⊓
        (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens)) :
    pointOrd hwQ (sectionResidueUnit hw (𝓔.tautTransition hX (j, some i) (j, none))) =
      if Q = 𝓔.hyperPoint x then 1 else 0 := by
  obtain ⟨𝔮, rfl⟩ := hQ
  have e : AffineCharts.fibrePoint 𝓔.completionCharts x = (𝓔.completionChart (j, some i)).base
      (coordIdealPoint (𝓔.bundle.chartBasePoint j ⟨x, hx⟩).asIdeal ∅) := by
    have := 𝓔.fibrePoint_eq_coordPoint j ⟨x, hx⟩ (some i)
    rwa [coordPoint_eq_completionChart, chartSet_empty] at this
  rw [hyperPoint_chart 𝓔 hx i, Set.singleton_def,
    (𝓔.completionChart (j, some i)).isOpenEmbedding.injective.eq_iff]
  generalize hw' : AffineCharts.fibrePoint 𝓔.completionCharts x = w at hwQ hw e ⊢
  subst e
  refine pointOrd_coordIdeal (𝓔.completionChart (j, some i)) _ (Set.notMem_empty i) 𝔮
    ((𝓔.completionChart_specializes_iff (j, some i) _ _).mp hwQ) hwQ _ ?_
  have := 𝓔.residueFieldMap_sectionResidueUnit_tautTransition hX j (some i) none _ hw
  rwa [optionCoordVar_some_none] at this

/-! ### Coordinate subspaces of the trivial piece over `U_j` (for the Segre identity) -/

section TrivialPiece

/-- The coordinate point computed in the chart `(j, i)`, `i ∉ S`, lies in `D₊(x_s)` iff
`s ∉ S`. -/
theorem coordPoint_mem_tautOpen_iff (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) (S : Set (Option ι))
    {i : Option ι} (hi : i ∉ S) (s : Option ι) :
    𝓔.coordPoint j 𝔭 S i ∈ (𝓔.tautOpen (j, s) : 𝓔.projectiveCompletion.Opens) ↔ s ∉ S := by
  rw [← coordPoint_mem_range_completionChart_iff 𝓔 j 𝔭 S hi s, ← opensRange_completionChart]
  exact Iff.rfl

open Classical in
set_option backward.isDefEq.respectTransparency false in
/-- **Orders of the coordinate function `x_t / x_i` along a coordinate point** (the chart-level
ingredient of the Segre identity): for `S ⊆ Option ι`, `some t ∉ S`, a chart `(j, i)` with
`i ≠ some t`, the coordinate point `w` of `S` (computed in the chart `(j, i)`, meaningful for
`i ∉ S`) and a point `Q` of the chart `(j, i)`
specialised by `w`, the order along `w ⤳ Q` of the residue at `w` of the transition unit
`x_t / x_i` of `O(1)` (the coordinate in the chart `(j, i)` of the frame section of the chart
`(j, some t)`) is `1` if `Q` is the coordinate point of `insert (some t) S` and `0` otherwise. -/
theorem pointOrd_coordPoint [IsLocallyNoetherian 𝓔.projectiveCompletion] [Finite ι]
    (j : 𝓔.bundle.J) [IsNoetherianRing Γ(X, (𝓔.bundle.chart j).1)]
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) {S : Set (Option ι)} {t : ι}
    (ht : some t ∉ S) {i : Option ι} (hit : i ≠ some t)
    {w Q : 𝓔.projectiveCompletion} (hw₀ : w = 𝓔.coordPoint j 𝔭 S i)
    (hQ : Q ∈ Set.range (𝓔.completionChart (j, i)).base) (hwQ : w ⤳ Q)
    (hmem : w ∈ (𝓔.tautOpen (j, i) : 𝓔.projectiveCompletion.Opens) ⊓
      (𝓔.tautOpen (j, some t) : 𝓔.projectiveCompletion.Opens)) :
    pointOrd hwQ (sectionResidueUnit hmem ((𝓔.tautological hX).g (j, i) (j, some t))) =
      if Q = 𝓔.coordPoint j 𝔭 (insert (some t) S) i then 1 else 0 := by
  obtain ⟨𝔮, rfl⟩ := hQ
  subst hw₀
  have ht' : t ∉ chartSet i S := fun h ↦ ht ((mem_chartSet_iff_of_ne S hit).mp h)
  have h1 := pointOrd_coordIdeal (𝓔.completionChart (j, i)) 𝔭.asIdeal ht' 𝔮
    ((𝓔.completionChart_specializes_iff (j, i) _ _).mp hwQ) hwQ
    (sectionResidueUnit hmem ((𝓔.tautological hX).g (j, i) (j, some t))) (by
      have := 𝓔.residueFieldMap_sectionResidueUnit_tautTransition hX j i (some t) _ hmem
      rwa [optionCoordVar_some_of_ne hit] at this)
  rw [h1, coordPoint_eq_completionChart, chartSet_insert_some S hit,
    (𝓔.completionChart (j, i)).isOpenEmbedding.injective.eq_iff]

variable {k : Type u} [Field k] (f : X ⟶ Spec (CommRingCat.of k)) [LocallyOfFiniteType f]

omit hX in
/-- **The dimension of the coordinate points of the trivial piece**: the coordinate point of a
finite set `S₀ ⊆ ι` of coordinates over `x` has dimension `dim x + rank - |S₀|`. -/
theorem dimensionFunction_coordPoint [Finite ι] (j : 𝓔.bundle.J) {x : X}
    (hx : x ∈ (𝓔.bundle.chart j).1) (S₀ : Finset ι) {i : Option ι}
    (hi : i ∉ some '' (S₀ : Set ι)) :
    FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f)
        (𝓔.coordPoint j (𝓔.bundle.chartBasePoint j ⟨x, hx⟩) (some '' (S₀ : Set ι)) i) =
      FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - S₀.card := by
  classical
  have _ := FiniteTypeDimension.isNoetherianRing_sections f (𝓔.bundle.chart j).1
    (𝓔.bundle.chart j).2
  rw [coordPoint_congr 𝓔 j _ _ hi (fun ⟨_, _, h⟩ ↦ Option.some_ne_none _ h)]
  clear hi
  induction S₀ using Finset.induction_on with
  | empty =>
    rw [Finset.coe_empty, Set.image_empty, Finset.card_empty, Nat.cast_zero, sub_zero]
    have := 𝓔.fibrePoint_eq_coordPoint j ⟨x, hx⟩ none
    rw [← this]
    exact dimensionFunction_fibrePoint_completionCharts 𝓔 f x
  | insert t S₀ ht ih =>
    rw [Finset.coe_insert, Set.image_insert_eq, Finset.card_insert_of_notMem ht]
    have h1 := dim_coordIdealPoint_insert (𝓔.completionChart (j, none))
      (FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f))
      (covByDimension_finiteTypeDimension _) (𝓔.bundle.chartBasePoint j ⟨x, hx⟩).asIdeal
      (S := (S₀ : Set ι)) ht
    rw [coordPoint_eq_completionChart, chartSet_none_image] at ih
    rw [coordPoint_eq_completionChart, chartSet_insert_some _ (Option.some_ne_none t).symm,
      chartSet_none_image, h1, ih]
    push_cast
    ring

/-- The coordinate ideal of all the variables is the preimage of `𝔭` under the constant
coefficient. -/
theorem coordIdeal_univ_eq_comap_constantCoeff {A : Type u} [CommRing A] (𝔭 : Ideal A) :
    coordIdeal 𝔭 (Set.univ : Set ι) = Ideal.comap (constantCoeff : MvPolynomial ι A →+* A) 𝔭 := by
  apply le_antisymm
  · refine coordIdeal_le_of_le 𝔭 _ _ ?_ ?_
    · intro a ha
      rw [Ideal.mem_comap, Ideal.mem_comap, algebraMap_eq, constantCoeff_C]
      exact ha
    · intro k _
      rw [Ideal.mem_comap, constantCoeff_X]
      exact zero_mem _
  · intro p hp
    rw [Ideal.mem_comap] at hp
    have h2 : p - C (constantCoeff p) ∈ Ideal.span (X '' (Set.univ : Set ι)) := by
      rw [mem_ideal_span_X_image]
      intro m hm
      by_contra h
      push Not at h
      have hm0 : m = 0 := Finsupp.ext fun k ↦ h k (Set.mem_univ k)
      rw [mem_support_iff, hm0, coeff_sub, coeff_zero_C, ← constantCoeff_eq, sub_self] at hm
      exact hm rfl
    have h3 : p = C (constantCoeff p) + (p - C (constantCoeff p)) := by ring
    rw [h3]
    exact Ideal.add_mem _ (Ideal.mem_sup_left (Ideal.mem_map_of_mem _ hp))
      (Ideal.mem_sup_right h2)

omit hX in
/-- The coordinate point of all the coordinates `x_k`, `k : ι`, over `𝔭` is the image in
`P(E ⊕ 1)` of the zero section of `E` at the point of `U_j` under `𝔭`. -/
theorem coordPoint_univ_eq_zeroSection (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) :
    𝓔.coordPoint j 𝔭 (some '' Set.univ) none =
      𝓔.bundleOpenEmbedding.base (𝓔.bundle.zeroSection.base ((𝓔.chartBaseι j).base 𝔭)) := by
  have h := 𝓔.bundle.zeroSection_chart j
  have h' : 𝓔.bundle.zeroSection.base ((𝓔.chartBaseι j).base 𝔭) =
      (𝓔.bundle.chartι j).base ((GradedCone.vertexSection (𝓔.bundle.chartAugmentation j)).base
        𝔭) := by
    change ((isAffineOpen X (𝓔.bundle.chart j)).isoSpec.inv ≫ (𝓔.bundle.chart j).1.ι ≫
      𝓔.bundle.zeroSection).base 𝔭 = _
    rw [h]
    rfl
  rw [h']
  change _ = (𝓔.bundle.chartι j ≫ 𝓔.bundleOpenEmbedding).base _
  rw [bundleOpenEmbedding_chartι_none, coordPoint_eq_completionChart, chartSet_none_image]
  congr 1
  refine PrimeSpectrum.ext ?_
  rw [coordIdealPoint_asIdeal, coordIdeal_univ_eq_comap_constantCoeff]
  change _ = Ideal.comap (𝓔.bundle.chartAugmentation j).toRingHom 𝔭.asIdeal
  ext p
  rw [Ideal.mem_comap, Ideal.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
    BundleData.chartAugmentation, aeval_zero', Algebra.algebraMap_self, RingHom.id_apply]

omit hX in
/-- A morphism inducing a bijection on residue fields has residue degree one. -/
theorem residueDegree_eq_one_of_bijective {Y Z : Scheme.{u}} (g : Y ⟶ Z) (y : Y)
    (hg : Function.Bijective (g.residueFieldMap y)) : g.residueDegree y = 1 := by
  unfold Scheme.Hom.residueDegree
  let _ := (g.residueFieldMap y).hom.toAlgebra
  exact Algebra.finrank_eq_one_iff_bijective_algebraMap.mpr hg

omit hX in
/-- **The residue degree of `P(E ⊕ 1) → X` at a zero-section point is one**: the coordinate point
of all the coordinates over `𝔭 ∈ U_j` has the same residue field as its image in `X`. -/
theorem residueDegree_coordPoint_univ (j : 𝓔.bundle.J)
    (𝔭 : ↥(Spec (CommRingCat.of Γ(X, (𝓔.bundle.chart j).1)))) :
    𝓔.completionToBase.residueDegree (𝓔.coordPoint j 𝔭 (some '' Set.univ) none) = 1 := by
  rw [coordPoint_univ_eq_zeroSection]
  set y := (𝓔.chartBaseι j).base 𝔭
  have h1 := residueDegree_comp 𝓔.bundleOpenEmbedding 𝓔.completionToBase
    (𝓔.bundle.zeroSection.base y)
  have h2 := residueDegree_comp 𝓔.bundle.zeroSection (𝓔.bundleOpenEmbedding ≫
    𝓔.completionToBase) y
  rw [bundleOpenEmbedding_toBase, 𝓔.bundle.zeroSection_proj, residueDegree_eq_one_of_bijective _ _
    (by rw [Scheme.residueFieldMap_id]; exact (RingEquiv.refl _).bijective)] at h2
  rw [bundleOpenEmbedding_toBase] at h1
  rw [residueDegree_eq_one_of_bijective _ _
    (asIso (𝓔.bundleOpenEmbedding.residueFieldMap _)).commRingCatIsoToRingEquiv.bijective,
    mul_one] at h1
  rw [← h1]
  exact Nat.eq_one_of_mul_eq_one_right h2.symm

end TrivialPiece

/-! ### Noetherian hypotheses on `P(E ⊕ 1)` and the dimension of `hyperPoint` -/

section Divisor

open LineBundleInjective

variable {k : Type u} [Field k] (f : X ⟶ Spec (CommRingCat.of k)) [LocallyOfFiniteType f]

omit hX in
include f in
/-- `P(E ⊕ 1)` is locally Noetherian when `X` is locally of finite type over a field. -/
theorem isLocallyNoetherian_projectiveCompletion : IsLocallyNoetherian 𝓔.projectiveCompletion :=
  LocallyOfFiniteType.isLocallyNoetherian (𝓔.completionToBase ≫ f)

omit hX in
include f in
/-- `P(E ⊕ 1)` is a Noetherian space when `X` is a Noetherian space locally of finite type over
a field. -/
theorem noetherianSpace_projectiveCompletion [NoetherianSpace X] :
    NoetherianSpace 𝓔.projectiveCompletion :=
  have _ := 𝓔.isLocallyNoetherian_projectiveCompletion f
  have _ := QuasiCompact.compactSpace_of_compactSpace 𝓔.completionToBase
  inferInstance

variable [Finite ι] [Nonempty ι]

omit hX in
/-- **The dimension of `hyperPoint x`** is `dim x + rank - 1`. -/
theorem dimensionFunction_hyperPoint (x : X) :
    FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f) (𝓔.hyperPoint x) =
      FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - 1 := by
  have hx := BundlePullbackGlobal.mem_chart_chartIndex 𝓔.bundle x
  set j := BundlePullbackGlobal.chartIndex 𝓔.bundle x
  obtain ⟨i⟩ := ‹Nonempty ι›
  have _ := FiniteTypeDimension.isNoetherianRing_sections f (𝓔.bundle.chart j).1
    (𝓔.bundle.chart j).2
  have h1 := dim_coordIdealPoint_insert (𝓔.completionChart (j, some i))
    (FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f))
    (covByDimension_finiteTypeDimension _) (𝓔.bundle.chartBasePoint j ⟨x, hx⟩).asIdeal
    (S := ∅) (Set.notMem_empty i)
  have h2 : (𝓔.completionChart (j, some i)).base
      (coordIdealPoint (𝓔.bundle.chartBasePoint j ⟨x, hx⟩).asIdeal ∅) =
      AffineCharts.fibrePoint 𝓔.completionCharts x := by
    have := (𝓔.fibrePoint_eq_coordPoint j ⟨x, hx⟩ (some i)).symm
    rwa [coordPoint_eq_completionChart, chartSet_empty] at this
  rw [hyperPoint_chart 𝓔 hx i, Set.singleton_def, h1, h2,
    dimensionFunction_fibrePoint_completionCharts]

variable [Infinite k] [NoetherianSpace X]

set_option backward.isDefEq.respectTransparency false in
/-- **The hyperplane at infinity is the divisor of `x_none`** (Fulton, §3.3, the first Chern class
of `O(1)` on `P(E ⊕ 1)` capped with a fibre):  for `x : X` with generic fibre point `w` (of
dimension `dim x + r`) and generic hyperplane point `ζ = hyperPoint x` (of dimension
`dim x + r - 1`), `c₁(O(1)) ∩ [w] = [ζ]` in `A_{dim x + r - 1}(P(E ⊕ 1))`. -/
theorem firstChernClassOfField_tautological_fibrePoint (x : X) :
    haveI := 𝓔.isLocallyNoetherian_projectiveCompletion f
    haveI := 𝓔.noetherianSpace_projectiveCompletion f
    firstChernClassOfField (𝓔.completionToBase ≫ f) (𝓔.tautological hX)
        (FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - 1)
        ((chowSystem (FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f))
          (FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - 1 + 1)).quotientMap
          (cyclesOfDimension.point (AffineCharts.fibrePoint 𝓔.completionCharts x)
            (by rw [dimensionFunction_fibrePoint_completionCharts]; ring))) =
      (chowSystem (FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f))
          (FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - 1)).quotientMap
        (cyclesOfDimension.point (𝓔.hyperPoint x) (𝓔.dimensionFunction_hyperPoint f x)) := by
  classical
  have _ := 𝓔.isLocallyNoetherian_projectiveCompletion f
  have _ := 𝓔.noetherianSpace_projectiveCompletion f
  set w := AffineCharts.fibrePoint 𝓔.completionCharts x with hwdef
  set dimP := FiniteTypeDimension.dimensionFunction (𝓔.completionToBase ≫ f)
  have hx := BundlePullbackGlobal.mem_chart_chartIndex 𝓔.bundle x
  set j := BundlePullbackGlobal.chartIndex 𝓔.bundle x
  have hwmem : w ∈ ((𝓔.tautological hX).U (j, none) : 𝓔.projectiveCompletion.Opens) := by
    change w ∈ (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens)
    rw [← opensRange_completionChart]
    exact AffineCharts.fibrePoint_mem_range 𝓔.completionCharts (j, none) x hx
  have hj : (pointSubscheme w).eta ∈
      ((𝓔.tautological hX).U (j, none) : 𝓔.projectiveCompletion.Opens) :=
    eta_pointSubscheme_mem specializes_rfl hwmem
  let s : (𝓔.tautological hX).RationalSection (pointSubscheme w) := ⟨(j, none), hj, 1⟩
  have hw : dimP w = FiniteTypeDimension.dimensionFunction f x + (Nat.card ι : ℤ) - 1 + 1 := by
    rw [hwdef, dimensionFunction_fibrePoint_completionCharts]
    ring
  unfold firstChernClassOfField
  rw [firstChernClass_quotientMap, c1Cycle_single (covByDimension_finiteTypeDimension _) hw s]
  congr 1
  apply Subtype.ext
  apply Function.locallyFinsuppWithin.ext
  intro Q
  change (s.divisor dimP : 𝓔.projectiveCompletion → ℚ) Q = _
  by_cases hwQ : w ⤳ Q
  · obtain ⟨a, ha⟩ := 𝓔.exists_mem_tautOpen Q
    have hxa : x ∈ (𝓔.bundle.chart a.1).1 := by
      have hQa : 𝓔.completionToBase.base Q ∈ (𝓔.bundle.chart a.1).1 := by
        refine AffineCharts.q_mem_base_of_mem_range 𝓔.completionCharts a ?_
        rw [completionCharts_chartι, ← Scheme.Hom.coe_opensRange, opensRange_completionChart]
        exact ha
      have hxq : x ⤳ 𝓔.completionToBase.base Q := by
        have := hwQ.map 𝓔.completionToBase.continuous
        rwa [hwdef, AffineCharts.q_fibrePoint] at this
      exact hxq.mem_open (𝓔.bundle.chart a.1).1.isOpen hQa
    have hwa : w ∈ ((𝓔.tautological hX).U a : 𝓔.projectiveCompletion.Opens) := by
      change w ∈ (𝓔.tautOpen a : 𝓔.projectiveCompletion.Opens)
      rw [← opensRange_completionChart]
      exact AffineCharts.fibrePoint_mem_range 𝓔.completionCharts a x hxa
    rw [LineBundleData.divisor_frame_apply (𝓔.tautological hX) dimP w (j, none) a hj hwQ ha
      ⟨hwa, hwmem⟩]
    obtain ⟨j', i'⟩ := a
    cases i' with
    | none =>
      have h1 : (𝓔.tautological hX).g (j', none) (j, none) = 1 := 𝓔.tautTransition_none_none hX j j'
      rw [h1, sectionResidueUnit_one, pointOrd_one, Int.cast_zero]
      have hQE : Q ∈ Set.range 𝓔.bundleOpenEmbedding.base := by
        refine 𝓔.range_completionChart_none_subset j' ?_
        rw [← Scheme.Hom.coe_opensRange, opensRange_completionChart]
        exact ha
      rw [cyclesOfDimension.point_apply_of_ne (𝓔.hyperPoint x) Q _
        (fun h ↦ 𝓔.hyperPoint_notMem_range_bundleOpenEmbedding x (h ▸ hQE))]
    | some i =>
      have hwa' : w ∈ (𝓔.tautOpen (j', some i) : 𝓔.projectiveCompletion.Opens) ⊓
          (𝓔.tautOpen (j', none) : 𝓔.projectiveCompletion.Opens) := by
        refine ⟨hwa, ?_⟩
        change w ∈ (𝓔.tautOpen (j', none) : 𝓔.projectiveCompletion.Opens)
        rw [← opensRange_completionChart]
        exact AffineCharts.fibrePoint_mem_range 𝓔.completionCharts (j', none) x hxa
      have hQ' : Q ∈ Set.range (𝓔.completionChart (j', some i)).base := by
        rw [← Scheme.Hom.coe_opensRange, opensRange_completionChart]
        exact ha
      have _ := FiniteTypeDimension.isNoetherianRing_sections f (𝓔.bundle.chart j').1
        (𝓔.bundle.chart j').2
      change (pointOrd hwQ (sectionResidueUnit (⟨hwa, hwmem⟩ : w ∈
        (𝓔.tautOpen (j', some i) : 𝓔.projectiveCompletion.Opens) ⊓
          (𝓔.tautOpen (j, none) : 𝓔.projectiveCompletion.Opens))
        (𝓔.tautTransition hX (j', some i) (j, none))) : ℚ) = _
      rw [𝓔.sectionResidueUnit_tautTransition_some_none hX j j' i ⟨hwa, hwmem⟩ hwa',
        𝓔.pointOrd_tautTransition_fibrePoint hX j' hxa i hQ' hwQ hwa']
      by_cases hQζ : Q = 𝓔.hyperPoint x
      · rw [if_pos hQζ, hQζ, cyclesOfDimension.point_apply_self, Int.cast_one]
      · rw [if_neg hQζ, cyclesOfDimension.point_apply_of_ne _ _ _ hQζ, Int.cast_zero]
  · rw [LineBundleData.RationalSection.divisor_apply_eq_zero_of_not_specializes s dimP hwQ,
      cyclesOfDimension.point_apply_of_ne (𝓔.hyperPoint x) Q _
        (fun h ↦ hwQ (h ▸ 𝓔.fibrePoint_specializes_hyperPoint x))]

end Divisor

end GradedBundleData

end

end GromovWitten.AlgebraicGeometry
