/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/

import GromovWitten.AlgebraicGeometry.Curves.LineBundles
import GromovWitten.AlgebraicGeometry.Curves.Sections
import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Mathlib.AlgebraicGeometry.Morphisms.Flat
import Mathlib.CategoryTheory.Limits.Preserves.Shapes.Kernels
import Mathlib.RingTheory.Polynomial.Ideal
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.TensorProduct.Quotient

/-!
# Effective Cartier divisors on schemes

Mathlib's `Scheme.IdealSheafData` records the affine ideals and their localization coherence and
constructs the corresponding closed subscheme.  An effective Cartier ideal is one which is,
locally around every point, generated by a regular element.  This file packages that intrinsic
condition with the genuine ideal sheaf and exposes its closed subscheme, immersion, and support.

The ideal module is constructed canonically as the kernel of `O_X → i_* O_D`.  Multiplication
by a regular local equation identifies it locally with the structure sheaf, which proves that it
is invertible and supplies the associated line bundles `O_X(-D)` and `O_X(D)`.
-/

open CategoryTheory
open _root_.AlgebraicGeometry
open TopologicalSpace

namespace GromovWitten.AlgebraicGeometry.Curves

universe u

noncomputable section

variable {X : Scheme.{u}}

/-- In a pushout of rings along a quotient `B → B/J`, the kernel of the map from the
other factor is the extension of `J`. -/
private lemma ker_pushout_inr_quotient {B A : Type u} [CommRing B] [CommRing A]
    (J : Ideal B) (f : B →+* A) :
    RingHom.ker (Limits.pushout.inr
      (CommRingCat.ofHom (Ideal.Quotient.mk J)) (CommRingCat.ofHom f)).hom = J.map f := by
  let _ := f.toAlgebra
  let H := CommRingCat.isPushout_tensorProduct B (B ⧸ J) A
  let e := Algebra.TensorProduct.quotIdealMapEquivQuotTensor A J
  have he : e.toRingHom.comp (Ideal.Quotient.mk (J.map f)) =
      (Algebra.TensorProduct.includeRight :
        A →ₐ[B] TensorProduct B (B ⧸ J) A).toRingHom := by
    ext a
    exact Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk A J a
  have hpush :
      (Algebra.TensorProduct.includeRight :
        A →ₐ[B] TensorProduct B (B ⧸ J) A).toRingHom =
        H.isoPushout.commRingCatIsoToRingEquiv.symm.toRingHom.comp
          (Limits.pushout.inr (CommRingCat.ofHom (Ideal.Quotient.mk J))
            (CommRingCat.ofHom f)).hom := by
    have hcat :
        CommRingCat.ofHom
            (Algebra.TensorProduct.includeRight :
              A →ₐ[B] TensorProduct B (B ⧸ J) A).toRingHom =
          Limits.pushout.inr (CommRingCat.ofHom (Ideal.Quotient.mk J))
              (CommRingCat.ofHom f) ≫ H.isoPushout.inv := by
      rw [← H.inr_isoPushout_hom, Category.assoc, Iso.hom_inv_id, Category.comp_id]
    exact congrArg CommRingCat.Hom.hom hcat
  rw [← RingHom.ker_equiv_comp _ H.isoPushout.commRingCatIsoToRingEquiv.symm]
  rw [← hpush, ← he, RingHom.ker_equiv_comp, Ideal.mk_ker]

/-- The preceding pushout-kernel calculation is unchanged if the quotient algebra is replaced by
an isomorphic ring. -/
private lemma ker_pushout_inr_comp_iso {B A : Type u} [CommRing B] [CommRing A]
    {C : CommRingCat.{u}} (J : Ideal B) (f : B →+* A)
    (e : CommRingCat.of (B ⧸ J) ≅ C) :
    let q₀ := CommRingCat.ofHom (Ideal.Quotient.mk J)
    let φ := CommRingCat.ofHom f
    let q := q₀ ≫ e.hom
    RingHom.ker (Limits.pushout.inr q φ).hom = J.map f := by
  dsimp only
  let q₀ := CommRingCat.ofHom (Ideal.Quotient.mk J)
  let φ := CommRingCat.ofHom f
  let q := q₀ ≫ e.hom
  let m : Limits.pushout q₀ φ ⟶ Limits.pushout q φ :=
    Limits.pushout.map q₀ φ q φ e.hom (𝟙 _) (𝟙 _) (by simp [q]) (by simp)
  have hm : IsIso m := by dsimp [m]; infer_instance
  have hleg : Limits.pushout.inr q₀ φ ≫ m = Limits.pushout.inr q φ := by
    dsimp [m, Limits.pushout.map]
    exact Limits.pushout.inr_desc _ _ _
  have hring := congrArg CommRingCat.Hom.hom hleg
  rw [CommRingCat.hom_comp] at hring
  calc
    RingHom.ker (Limits.pushout.inr q φ).hom =
        RingHom.ker (m.hom.comp (Limits.pushout.inr q₀ φ).hom) :=
      congrArg RingHom.ker hring.symm
    _ = RingHom.ker (Limits.pushout.inr q₀ φ).hom :=
      RingHom.ker_comp_of_injective _ (ConcreteCategory.bijective_of_isIso m).1
    _ = J.map f := ker_pushout_inr_quotient J f

set_option backward.isDefEq.respectTransparency false in
/-- On affine opens, scheme-theoretic inverse image of an ideal sheaf is ordinary extension of
the corresponding ideal of sections. -/
theorem idealSheaf_comap_ideal {Y : Scheme.{u}} (I : Y.IdealSheafData) (f : X ⟶ Y)
    (U : Y.affineOpens) (V : X.affineOpens) (h : V.1 ≤ f ⁻¹ᵁ U.1) :
    (I.comap f).ideal V = (I.ideal U).map (f.appLE U V h).hom := by
  rw [Scheme.IdealSheafData.comap, Scheme.Hom.ker_apply]
  let Z := I.subscheme
  let i : Z ⟶ Y := I.subschemeι
  let P := Limits.pullback f i
  let p : P ⟶ X := Limits.pullback.fst f i
  let g : P ⟶ Z := Limits.pullback.snd f i
  let H : IsPullback g p i f := (IsPullback.of_hasPullback f i).flip
  let UX : Z.Opens := i ⁻¹ᵁ U.1
  have hUX : IsAffineOpen UX := by
    dsimp [UX]
    exact U.2.preimage i
  let UP : P.Opens := p ⁻¹ᵁ V.1
  let hP : UP = g ⁻¹ᵁ UX ⊓ p ⁻¹ᵁ V.1 := by
    apply le_antisymm
    · intro x hx
      refine ⟨?_, hx⟩
      change i (g x) ∈ U.1
      rw [← Scheme.Hom.comp_apply, H.w, Scheme.Hom.comp_apply]
      exact h hx
    · exact inf_le_right
  let q := i.appLE U.1 UX le_rfl
  let φ := f.appLE U.1 V.1 h
  let s :=
    pushoutSection H (US := U.1) (UT := V.1) (UX := UX) (UY := UP)
      h le_rfl hP
  have hs : IsIso s := by
    dsimp [s]
    exact isIso_pushoutSection_of_isAffineOpen H h le_rfl hP U.2 V.2 hUX
  have hψ : Limits.pushout.inr q φ ≫ s = p.app V.1 := by
    dsimp [s, pushoutSection, q, φ, UP]
    rw [Limits.pushout.inr_desc]
    exact p.appLE_eq_app
  have hψring := congrArg CommRingCat.Hom.hom hψ
  rw [CommRingCat.hom_comp] at hψring
  rw [← hψring, RingHom.ker_comp_of_injective (f := s.hom)
    (Limits.pushout.inr q φ).hom (ConcreteCategory.bijective_of_isIso s).1]
  let e : CommRingCat.of (Γ(Y, U.1) ⧸ I.ideal U) ≅ Γ(Z, UX) :=
    (I.subschemeObjIso U).symm
  have hq : q = CommRingCat.ofHom (Ideal.Quotient.mk (I.ideal U)) ≫ e.hom := by
    calc
      q = i.app U.1 := by
        dsimp [q]
        exact i.appLE_eq_app
      _ = CommRingCat.ofHom (Ideal.Quotient.mk (I.ideal U)) ≫ e.hom := by
        dsimp [i, e, Z, UX]
        exact I.subschemeι_app U
  rw [hq]
  simpa only [CommRingCat.ofHom_hom] using
    ker_pushout_inr_comp_iso (I.ideal U) (f.appLE U V h).hom e

/-- Scheme-theoretic inverse image preserves products of ideal sheaves.  This is checked on an
affine cover of the source subordinate to inverse images of affine opens of the target, where it
is the ordinary identity `map (I * J) = map I * map J` for ideals. -/
theorem idealSheaf_comap_mul {Y : Scheme.{u}}
    (I J : Y.IdealSheafData) (f : X ⟶ Y) :
    (I * J).comap f = I.comap f * J.comap f := by
  classical
  let ι := { p : Y.affineOpens × X.affineOpens // p.2.1 ≤ f ⁻¹ᵁ p.1.1 }
  let V : ι → X.affineOpens := fun i ↦ i.1.2
  have hV : ⨆ i, (V i).1 = ⊤ := by
    apply top_unique
    intro x hx
    obtain ⟨_, ⟨U, hU, rfl⟩, hfxU, -⟩ :=
      Y.isBasis_affineOpens.exists_subset_of_mem_open
        (show f x ∈ (⊤ : Y.Opens) from Set.mem_univ (f x)) isOpen_univ
    obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWpre⟩ :=
      X.isBasis_affineOpens.exists_subset_of_mem_open
        (show x ∈ f ⁻¹ᵁ U from hfxU) (f ⁻¹ᵁ U).2
    let i : ι := ⟨(⟨U, hU⟩, ⟨W, hW⟩), hWpre⟩
    exact TopologicalSpace.Opens.mem_iSup.mpr ⟨i, hxW⟩
  apply Scheme.IdealSheafData.ext_of_iSup_eq_top V hV
  rintro ⟨⟨U, W⟩, h⟩
  change ((I * J).comap f).ideal W =
    (I.comap f).ideal W * (J.comap f).ideal W
  rw [idealSheaf_comap_ideal (I * J) f U W h,
    idealSheaf_comap_ideal I f U W h,
    idealSheaf_comap_ideal J f U W h]
  exact Ideal.map_mul _ _ _

/-- Scheme-theoretic inverse image preserves every power of an ideal sheaf. -/
theorem idealSheaf_comap_pow {Y : Scheme.{u}}
    (I : Y.IdealSheafData) (f : X ⟶ Y) (n : ℕ) :
    (I ^ n).comap f = (I.comap f) ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, idealSheaf_comap_mul, ih, pow_succ]

/-- Restricting a quasi-compact morphism to an open of its target pulls back its kernel ideal
sheaf. -/
theorem ker_morphismRestrict {Y Z : Scheme.{u}} (f : Z ⟶ Y) [QuasiCompact f]
    (U : Y.Opens) :
    (f ∣_ U).ker = f.ker.comap U.ι := by
  apply Scheme.IdealSheafData.ext
  funext V
  rw [Scheme.ker_morphismRestrict_ideal]
  rw [Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion]
  simp only [Scheme.Opens.ι_appIso, Iso.refl_inv]
  change _ = Ideal.comap (RingHom.id _) _
  rw [Ideal.comap_id]

/-- If one closed immersion factors through a monomorphism, its kernel is the pullback of the
original closed immersion's kernel. -/
theorem ker_factorThrough_mono {Y Z : Scheme.{u}}
    (f : Z ⟶ X) [IsClosedImmersion f] (i : Y ⟶ X) [Mono i]
    (g : Z ⟶ Y) [IsClosedImmersion g] (h : g ≫ i = f) :
    g.ker = f.ker.comap i := by
  let H : IsPullback g (𝟙 Z) i f :=
    isPullback_factorThrough_mono f i g h
  let e : Z ≅ Limits.pullback i f :=
    H.isoIsPullback _ _ (IsPullback.of_hasPullback i f)
  have he : e.hom ≫ Limits.pullback.fst i f = g :=
    H.isoIsPullback_hom_fst _ _ (IsPullback.of_hasPullback i f)
  rw [← he, Scheme.Hom.ker_comp_of_isIso]
  exact Scheme.IdealSheafData.ker_fst_of_isClosedImmersion f i

/-- If a closed immersion factors through an open subscheme, the kernel of the factored immersion
is the restriction of the original kernel to that open. -/
theorem ker_factorThrough_open {Z : Scheme.{u}}
    (f : Z ⟶ X) [IsClosedImmersion f] (U : X.Opens)
    (g : Z ⟶ U.toScheme) [IsClosedImmersion g] (h : g ≫ U.ι = f) :
    g.ker = f.ker.comap U.ι :=
  ker_factorThrough_mono f U.ι g h

/-- Away from the image of a closed immersion, its kernel ideal restricts to the unit ideal. -/
theorem ker_comap_complementOfClosedImmersion_eq_top {Z : Scheme.{u}}
    (f : Z ⟶ X) [IsClosedImmersion f] :
    f.ker.comap (complementOfClosedImmersion f).ι = ⊤ := by
  apply (Scheme.IdealSheafData.support_eq_bot_iff
    (I := f.ker.comap (complementOfClosedImmersion f).ι)).mp
  rw [Scheme.IdealSheafData.support_comap]
  ext x
  constructor
  · intro hx
    change (complementOfClosedImmersion f).ι x ∈ f.ker.support at hx
    have hsupp : (f.ker.support : Set X) = Set.range f := by
      rw [Scheme.Hom.support_ker,
        f.isClosedEmbedding.isClosed_range.closure_eq]
    have hxrange : (complementOfClosedImmersion f).ι x ∈ Set.range f := hsupp ▸ hx
    have hxW : (complementOfClosedImmersion f).ι x ∉ Set.range f := by
      exact x.property
    exact (hxW hxrange).elim
  · intro hx
    simp at hx

/-- A flat ring map sends non-zero-divisors to non-zero-divisors. -/
theorem isRegular_map_of_flat {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (hf : f.Flat) {r : R} (hr : IsRegular r) : IsRegular (f r) := by
  algebraize [f]
  apply (Commute.isRegular_iff (fun _ ↦ Commute.all _ _)).2
  intro a b hab
  apply Module.Flat.isSMulRegular_of_isRegular (M := S) hr
  simpa only [Algebra.smul_def, RingHom.algebraMap_toAlgebra] using hab

/-- Restriction between two affine opens of a scheme is flat. -/
theorem flat_affineOpenRestriction (U V : X.affineOpens) (h : V.1 ≤ U.1) :
    (X.presheaf.map (homOfLE h).op).hom.Flat := by
  set_option backward.isDefEq.respectTransparency false in
    have hf : Flat (𝟙 X) := inferInstance
    rw [HasRingHomProperty.iff_appLE (P := @Flat)] at hf
    have hf' := hf U V (by simpa using h)
    simpa [Scheme.Hom.appLE] using hf'

/-- An ideal sheaf is effective Cartier when every point has an affine neighborhood on which
the ideal is generated by one non-zero-divisor. -/
def IsEffectiveCartierIdealSheaf (I : X.IdealSheafData) : Prop :=
  ∀ x : X, ∃ U : X.affineOpens, x ∈ U.1 ∧
    ∃ r : Γ(X, U.1), IsRegular r ∧ I.ideal U = Ideal.span {r}

/-- Pullback along a flat morphism preserves effective Cartier ideal sheaves.  The local equation
is obtained by applying the section map, and remains regular by flatness. -/
theorem comap_isEffectiveCartierIdealSheaf_of_flat
    {Y : Scheme.{u}} (I : Y.IdealSheafData) (f : X ⟶ Y) [Flat f]
    (hI : IsEffectiveCartierIdealSheaf I) :
    IsEffectiveCartierIdealSheaf (I.comap f) := by
  intro x
  obtain ⟨U, hfxU, r, hr, hIr⟩ := hI (f x)
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVpre⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open
      (show x ∈ f ⁻¹ᵁ U.1 from hfxU) (f ⁻¹ᵁ U.1).2
  let V' : X.affineOpens := ⟨V, hV⟩
  let rV : Γ(X, V) := f.appLE U V' hVpre r
  have hflat : (f.appLE U V' hVpre).hom.Flat :=
    HasRingHomProperty.appLE (P := @Flat) f (inferInstance : Flat f) U V' hVpre
  have hrV : IsRegular rV := isRegular_map_of_flat _ hflat hr
  refine ⟨V', hxV, rV, hrV, ?_⟩
  rw [idealSheaf_comap_ideal I f U V' hVpre, hIr, Ideal.map_span,
    Set.image_singleton]

/-- A covering family of affine opens with regular principal equations certifies an effective
Cartier ideal sheaf. -/
theorem isEffectiveCartierIdealSheaf_of_iSup_eq_top {i : Type*}
    (I : X.IdealSheafData) (U : i → X.affineOpens)
    (hU : ⨆ j, (U j).1 = ⊤)
    (h : ∀ j, ∃ r : Γ(X, (U j).1), IsRegular r ∧
      I.ideal (U j) = Ideal.span {r}) :
    IsEffectiveCartierIdealSheaf I := by
  intro x
  have hx : x ∈ ⨆ j, (U j).1 := hU.symm ▸ Set.mem_univ x
  obtain ⟨j, hxj⟩ := TopologicalSpace.Opens.mem_iSup.mp hx
  obtain ⟨r, hr, hIr⟩ := h j
  exact ⟨U j, hxj, r, hr, hIr⟩

/-- The unit ideal is the ideal of the empty effective Cartier divisor. -/
theorem top_isEffectiveCartierIdealSheaf :
    IsEffectiveCartierIdealSheaf (⊤ : X.IdealSheafData) := by
  intro x
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open
      (Set.mem_univ x) isOpen_univ
  refine ⟨⟨U, hU⟩, hxU, 1, isRegular_one, ?_⟩
  simp

/-- Every power of an effective Cartier ideal is effective Cartier.  Locally its equation is the
corresponding power of the original regular equation. -/
theorem pow_isEffectiveCartierIdealSheaf (I : X.IdealSheafData)
    (hI : IsEffectiveCartierIdealSheaf I) (n : ℕ) :
    IsEffectiveCartierIdealSheaf (I ^ n) := by
  intro x
  obtain ⟨U, hxU, r, hr, hIr⟩ := hI x
  refine ⟨U, hxU, r ^ n, hr.pow n, ?_⟩
  change (I.ideal U) ^ n = Ideal.span {r ^ n}
  rw [hIr, Ideal.span_singleton_pow]

/-- The product of two effective Cartier ideals is effective Cartier.  The proof refines the two
local equation neighborhoods to a common affine open and uses flatness of affine-open restriction
to preserve regularity of both equations. -/
theorem mul_isEffectiveCartierIdealSheaf (I J : X.IdealSheafData)
    (hI : IsEffectiveCartierIdealSheaf I)
    (hJ : IsEffectiveCartierIdealSheaf J) :
    IsEffectiveCartierIdealSheaf (I * J) := by
  intro x
  obtain ⟨U, hxU, r, hr, hIr⟩ := hI x
  obtain ⟨V, hxV, s, hs, hJs⟩ := hJ x
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWUV⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open
      (show x ∈ U.1 ⊓ V.1 from ⟨hxU, hxV⟩) (U.1 ⊓ V.1).2
  let W' : X.affineOpens := ⟨W, hW⟩
  have hWU : W ≤ U.1 := hWUV.trans inf_le_left
  have hWV : W ≤ V.1 := hWUV.trans inf_le_right
  let rW : Γ(X, W) := X.presheaf.map (homOfLE hWU).op r
  let sW : Γ(X, W) := X.presheaf.map (homOfLE hWV).op s
  have hrW : IsRegular rW :=
    isRegular_map_of_flat _ (flat_affineOpenRestriction U W' hWU) hr
  have hsW : IsRegular sW :=
    isRegular_map_of_flat _ (flat_affineOpenRestriction V W' hWV) hs
  refine ⟨W', hxW, rW * sW, hrW.mul hsW, ?_⟩
  change I.ideal W' * J.ideal W' = Ideal.span {rW * sW}
  have hIW : I.ideal W' = Ideal.span {rW} := by
    rw [← I.map_ideal hWU, hIr, Ideal.map_span, Set.image_singleton]
    rfl
  have hJW : J.ideal W' = Ideal.span {sW} := by
    rw [← J.map_ideal hWV, hJs, Ideal.map_span, Set.image_singleton]
    rfl
  rw [hIW, hJW, Ideal.span_singleton_mul_span_singleton]

/-- Pullback of an effective Cartier ideal along an open immersion is effective Cartier. -/
theorem comap_isEffectiveCartierIdealSheaf_of_isOpenImmersion
    {Y : Scheme.{u}} (I : Y.IdealSheafData) (f : X ⟶ Y) [IsOpenImmersion f]
    (hI : IsEffectiveCartierIdealSheaf I) :
    IsEffectiveCartierIdealSheaf (I.comap f) := by
  intro x
  obtain ⟨U, hfxU, r, hr, hIr⟩ := hI (f x)
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVpre⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open
      (show x ∈ f ⁻¹ᵁ U.1 from hfxU) (f ⁻¹ᵁ U.1).2
  let V' : X.affineOpens := ⟨V, hV⟩
  let fV : Y.affineOpens := ⟨f ''ᵁ V, hV.image_of_isOpenImmersion f⟩
  have hfVU : f ''ᵁ V ≤ U.1 := Set.image_subset_iff.mpr hVpre
  let rV : Γ(Y, f ''ᵁ V) := Y.presheaf.map (homOfLE hfVU).op r
  have hrV : IsRegular rV :=
    isRegular_map_of_flat _ (flat_affineOpenRestriction U fV hfVU) hr
  have hIfV : I.ideal fV = Ideal.span {rV} := by
    rw [← I.map_ideal hfVU, hIr, Ideal.map_span, Set.image_singleton]
    rfl
  let e := f.appIso V
  let rX : Γ(X, V) := e.hom rV
  have heflat : e.hom.hom.Flat := RingHom.Flat.of_bijective
    (ConcreteCategory.bijective_of_isIso e.hom)
  have hrX : IsRegular rX := isRegular_map_of_flat e.hom.hom heflat hrV
  refine ⟨V', hxV, rX, hrX, ?_⟩
  rw [Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion, hIfV]
  change (Ideal.span {rV}).comap e.commRingCatIsoToRingEquiv.symm = Ideal.span {rX}
  rw [Ideal.comap_symm e.commRingCatIsoToRingEquiv, Ideal.map_span, Set.image_singleton]
  rfl

/-- Effective Cartier ideal sheaves descend from an open cover. -/
theorem isEffectiveCartierIdealSheaf_of_openCover {i : Type*}
    (I : X.IdealSheafData) (U : i → X.Opens) (hU : ⨆ j, U j = ⊤)
    (h : ∀ j, IsEffectiveCartierIdealSheaf (I.comap (U j).ι)) :
    IsEffectiveCartierIdealSheaf I := by
  set_option backward.isDefEq.respectTransparency false in
    intro x
    have hx : x ∈ ⨆ j, U j := hU.symm ▸ Set.mem_univ x
    obtain ⟨j, hxj⟩ := TopologicalSpace.Opens.mem_iSup.mp hx
    let xj : U j := ⟨x, hxj⟩
    obtain ⟨V, hxV, r, hr, hIr⟩ := h j xj
    let W : X.affineOpens :=
      ⟨(U j).ι ''ᵁ V.1, V.2.image_of_isOpenImmersion (U j).ι⟩
    have hxW : x ∈ W.1 := ⟨xj, hxV, rfl⟩
    let e : Γ(X, W.1) ≃+* Γ(U j, V.1) :=
      ((U j).ι.appIso V.1).commRingCatIsoToRingEquiv
    let rW : Γ(X, W.1) := e.symm r
    have heflat : e.symm.toRingHom.Flat := RingHom.Flat.of_bijective e.symm.bijective
    have hrW : IsRegular rW := isRegular_map_of_flat e.symm.toRingHom heflat hr
    refine ⟨W, hxW, rW, hrW, ?_⟩
    have heq : (I.ideal W).comap e.symm = Ideal.span {r} := by
      rw [← hIr]
      exact (Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion I (U j).ι V).symm
    rw [Ideal.comap_symm e] at heq
    calc
      I.ideal W = ((I.ideal W).map e).map e.symm := by
        rw [Ideal.map_symm]
        exact (Ideal.comap_map_of_bijective e e.bijective).symm
      _ = (Ideal.span {r}).map e.symm := congrArg (Ideal.map e.symm) heq
      _ = Ideal.span {rW} := by
        rw [Ideal.map_span, Set.image_singleton]

/-- Being an effective Cartier ideal sheaf is local on an arbitrary open cover. -/
theorem isEffectiveCartierIdealSheaf_iff_openCover {i : Type*}
    (I : X.IdealSheafData) (U : i → X.Opens) (hU : ⨆ j, U j = ⊤) :
    IsEffectiveCartierIdealSheaf I ↔
      ∀ j, IsEffectiveCartierIdealSheaf (I.comap (U j).ι) :=
  ⟨fun h j ↦ comap_isEffectiveCartierIdealSheaf_of_isOpenImmersion I (U j).ι h,
    isEffectiveCartierIdealSheaf_of_openCover I U hU⟩

/-- Pullback of ideal sheaves along an open immersion preserves products. -/
theorem idealSheaf_comap_mul_of_isOpenImmersion {Y : Scheme.{u}}
    (I J : Y.IdealSheafData) (f : X ⟶ Y) [IsOpenImmersion f] :
    (I * J).comap f = I.comap f * J.comap f := by
  set_option backward.isDefEq.respectTransparency false in
    apply Scheme.IdealSheafData.ext
    funext U
    let V : Y.affineOpens := ⟨f ''ᵁ U.1, U.2.image_of_isOpenImmersion f⟩
    let e : Γ(Y, V.1) ≃+* Γ(X, U.1) := (f.appIso U.1).commRingCatIsoToRingEquiv
    rw [Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion]
    change ((I * J).ideal _).comap _ =
      (I.comap f).ideal U * (J.comap f).ideal U
    rw [Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion,
      Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion]
    change (I.ideal V * J.ideal V).comap e.symm =
      (I.ideal V).comap e.symm * (J.ideal V).comap e.symm
    rw [Ideal.comap_symm, Ideal.map_mul, ← Ideal.comap_symm, ← Ideal.comap_symm]

/-- Pullback of ideal sheaves along an open immersion preserves powers. -/
theorem idealSheaf_comap_pow_of_isOpenImmersion {Y : Scheme.{u}}
    (I : Y.IdealSheafData) (f : X ⟶ Y) [IsOpenImmersion f] (n : ℕ) :
    (I ^ n).comap f = (I.comap f) ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, idealSheaf_comap_mul_of_isOpenImmersion, ih, pow_succ]

/-- An effective Cartier divisor, represented by its genuine coherent affine ideal data and the
local non-zero-divisor condition. -/
structure EffectiveCartierDivisor (X : Scheme.{u}) where
  idealSheaf : X.IdealSheafData
  isEffectiveCartier : IsEffectiveCartierIdealSheaf idealSheaf

namespace EffectiveCartierDivisor

/-- Effective Cartier divisors are determined by their ideal sheaves. -/
@[ext]
theorem ext {D E : EffectiveCartierDivisor X} (h : D.idealSheaf = E.idealSheaf) : D = E := by
  cases D
  cases E
  cases h
  rfl

/-- The empty effective Cartier divisor. -/
def empty (X : Scheme.{u}) : EffectiveCartierDivisor X where
  idealSheaf := ⊤
  isEffectiveCartier := top_isEffectiveCartierIdealSheaf

/-- A regular global equation on an affine scheme defines an effective Cartier divisor. -/
def ofGlobalEquation (X : Scheme.{u}) [IsAffine X]
    (r : Γ(X, ⊤)) (hr : IsRegular r) : EffectiveCartierDivisor X where
  idealSheaf := Scheme.IdealSheafData.ofIdealTop (Ideal.span {r})
  isEffectiveCartier := by
    intro x
    refine ⟨⟨⊤, isAffineOpen_top X⟩, Set.mem_univ x, r, hr, ?_⟩
    simp

@[simp]
theorem ofGlobalEquation_ideal_top (X : Scheme.{u}) [IsAffine X]
    (r : Γ(X, ⊤)) (hr : IsRegular r) :
    (ofGlobalEquation X r hr).idealSheaf.ideal ⟨⊤, isAffineOpen_top X⟩ =
      Ideal.span {r} := by
  simp [ofGlobalEquation]

/-! ### Graph divisors in the affine line -/

/-- The graph of an element `a : R` as a section of the affine line over `Spec R`. -/
def affineLineGraphSection (R : Type u) [CommRing R] (a : R) :
    Spec (.of R) ⟶ Spec (.of (Polynomial R)) :=
  Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom a))

instance affineLineGraphSection_isClosedImmersion
    (R : Type u) [CommRing R] (a : R) :
    IsClosedImmersion (affineLineGraphSection R a) := by
  apply IsClosedImmersion.spec_of_surjective
  intro r
  exact ⟨Polynomial.C r, by simp⟩

/-- The affine-line graph really is a section of the structural morphism. -/
@[reassoc (attr := simp)]
theorem affineLineGraphSection_toBase (R : Type u) [CommRing R] (a : R) :
    affineLineGraphSection R a ≫
      Spec.map (CommRingCat.ofHom (algebraMap R (Polynomial R))) = 𝟙 (Spec (.of R)) := by
  rw [affineLineGraphSection, ← Spec.map_comp, ← Spec.map_id, Spec.map_inj]
  apply CommRingCat.hom_ext
  ext r
  simp

/-- The global equation `T - a` of the graph section, transported through
`Γ(Spec R[T]) ≅ R[T]`. -/
def affineLineGraphEquation (R : Type u) [CommRing R] (a : R) :
    Γ(Spec (.of (Polynomial R)), ⊤) :=
  (Scheme.ΓSpecIso (.of (Polynomial R))).inv (Polynomial.X - Polynomial.C a)

/-- The graph equation is a non-zero-divisor over an arbitrary coefficient ring. -/
theorem affineLineGraphEquation_isRegular (R : Type u) [CommRing R] (a : R) :
    IsRegular (affineLineGraphEquation R a) := by
  apply isRegular_map_of_flat (Scheme.ΓSpecIso (.of (Polynomial R))).inv.hom
    (RingHom.Flat.of_bijective
      (ConcreteCategory.bijective_of_isIso (Scheme.ΓSpecIso (.of (Polynomial R))).inv))
  exact (Polynomial.monic_X_sub_C a).isRegular

/-- The graph `T = a` in the affine line, as a genuine effective Cartier divisor. -/
def affineLineGraph (R : Type u) [CommRing R] (a : R) :
    EffectiveCartierDivisor (Spec (.of (Polynomial R))) :=
  ofGlobalEquation _ (affineLineGraphEquation R a)
    (affineLineGraphEquation_isRegular R a)

@[simp]
theorem affineLineGraph_ideal_top (R : Type u) [CommRing R] (a : R) :
    (affineLineGraph R a).idealSheaf.ideal
        ⟨⊤, isAffineOpen_top (Spec (.of (Polynomial R)))⟩ =
      Ideal.span {affineLineGraphEquation R a} := by
  exact ofGlobalEquation_ideal_top _ _ _

/-- On global sections, the kernel of the graph section is generated by its equation `T - a`. -/
theorem affineLineGraphSection_ker_appTop (R : Type u) [CommRing R] (a : R) :
    RingHom.ker (affineLineGraphSection R a).appTop.hom =
      Ideal.span {affineLineGraphEquation R a} := by
  let P := Polynomial R
  let eP := Scheme.ΓSpecIso (.of P)
  let eR := Scheme.ΓSpecIso (.of R)
  let q := CommRingCat.ofHom (Polynomial.evalRingHom a)
  have hnat : q ≫ eR.inv = eP.inv ≫ (affineLineGraphSection R a).appTop := by
    exact Scheme.ΓSpecIso_inv_naturality q
  have happ : (affineLineGraphSection R a).appTop = eP.hom ≫ q ≫ eR.inv := by
    rw [← cancel_epi eP.inv]
    simpa only [Category.assoc, Iso.inv_hom_id_assoc] using hnat.symm
  have happRing := congrArg CommRingCat.Hom.hom happ
  rw [CommRingCat.hom_comp, CommRingCat.hom_comp] at happRing
  rw [happRing]
  change RingHom.ker (eR.commRingCatIsoToRingEquiv.symm.toRingHom.comp
    (q.hom.comp eP.hom.hom)) = _
  rw [RingHom.ker_equiv_comp, ← RingHom.comap_ker]
  change Ideal.comap eP.commRingCatIsoToRingEquiv.toRingHom
    (RingHom.ker q.hom) = _
  calc
    _ = Ideal.map eP.commRingCatIsoToRingEquiv.symm.toRingHom
        (RingHom.ker q.hom) :=
      (Ideal.map_symm eP.commRingCatIsoToRingEquiv).symm
    _ = Ideal.map eP.commRingCatIsoToRingEquiv.symm.toRingHom
        (Ideal.span {Polynomial.X - Polynomial.C a}) := by
      congr 1
      exact Polynomial.ker_evalRingHom a
    _ = Ideal.span {affineLineGraphEquation R a} := by
      rw [Ideal.map_span, Set.image_singleton]
      rfl

/-- The canonical ideal sheaf of the graph section is exactly the effective Cartier ideal just
constructed from `T - a`. -/
theorem affineLineGraphSection_ker (R : Type u) [CommRing R] (a : R) :
    (affineLineGraphSection R a).ker = (affineLineGraph R a).idealSheaf := by
  rw [Scheme.ker_of_isAffine, affineLineGraphSection_ker_appTop]
  rfl

/-- The closed subscheme cut out by an effective Cartier divisor. -/
def subscheme (D : EffectiveCartierDivisor X) : Scheme.{u} :=
  D.idealSheaf.subscheme

/-- The canonical closed immersion of an effective Cartier divisor. -/
def ι (D : EffectiveCartierDivisor X) : D.subscheme ⟶ X :=
  D.idealSheaf.subschemeι

/-- A closed immersion is canonically isomorphic to the subscheme cut out by any ideal sheaf
identified with its kernel. -/
def closedImmersionSubschemeIsoOfKerEq
    {Y Z : Scheme.{u}} (f : Z ⟶ Y) [IsClosedImmersion f]
    (I : Y.IdealSheafData) (h : f.ker = I) : Z ≅ I.subscheme :=
  asIso f.toImage ≪≫ eqToIso (congrArg Scheme.IdealSheafData.subscheme h)

/-- The canonical isomorphism from a closed immersion to the subscheme defined by its kernel
commutes with the immersions into the ambient scheme. -/
@[reassoc (attr := simp)]
theorem closedImmersionSubschemeIsoOfKerEq_hom_subschemeι
    {Y Z : Scheme.{u}} (f : Z ⟶ Y) [IsClosedImmersion f]
    (I : Y.IdealSheafData) (h : f.ker = I) :
    (closedImmersionSubschemeIsoOfKerEq f I h).hom ≫ I.subschemeι = f := by
  subst I
  change f.toImage ≫ f.imageι = f
  exact Scheme.Hom.toImage_imageι f

/-- The graph divisor's closed subscheme is canonically the base scheme. -/
def affineLineGraphSubschemeIso (R : Type u) [CommRing R] (a : R) :
    Spec (.of R) ≅ (affineLineGraph R a).subscheme :=
  closedImmersionSubschemeIsoOfKerEq (affineLineGraphSection R a)
    (affineLineGraph R a).idealSheaf (affineLineGraphSection_ker R a)

/-- The graph-divisor subscheme identification intertwines its canonical immersion with the
usual evaluation section of the affine line. -/
@[reassoc (attr := simp)]
theorem affineLineGraphSubschemeIso_hom_ι (R : Type u) [CommRing R] (a : R) :
    (affineLineGraphSubschemeIso R a).hom ≫ (affineLineGraph R a).ι =
      affineLineGraphSection R a :=
  closedImmersionSubschemeIsoOfKerEq_hom_subschemeι
    (affineLineGraphSection R a) (affineLineGraph R a).idealSheaf
      (affineLineGraphSection_ker R a)

instance (D : EffectiveCartierDivisor X) : IsClosedImmersion D.ι := by
  change IsClosedImmersion D.idealSheaf.subschemeι
  infer_instance

instance empty_subscheme_isEmpty (X : Scheme.{u}) : IsEmpty (empty X).subscheme := by
  change IsEmpty (⊤ : X.IdealSheafData).subscheme
  infer_instance

/-- The closed support of an effective Cartier divisor. -/
def support (D : EffectiveCartierDivisor X) : Closeds X :=
  D.idealSheaf.support

/-- The underlying image of the divisor subscheme is exactly its closed support. -/
theorem range_ι (D : EffectiveCartierDivisor X) :
    Set.range D.ι = D.support :=
  Scheme.IdealSheafData.range_subschemeι D.idealSheaf

/-! ### The invertible ideal module and associated line bundles -/

/-- The canonical map `O_X → i_* O_D` whose kernel is the ideal module of `D`. -/
def idealModuleMap (D : EffectiveCartierDivisor X) :
    SheafOfModules.unit X.ringCatSheaf ⟶
      (Scheme.Modules.pushforward D.ι).obj
        (SheafOfModules.unit D.subscheme.ringCatSheaf) :=
  SheafOfModules.unitToPushforwardObjUnit D.ι.toRingCatSheafHom

/-- The genuine ideal module `O_X(-D)`, defined as `ker(O_X → i_* O_D)`. -/
def idealModule (D : EffectiveCartierDivisor X) : X.Modules :=
  Limits.kernel D.idealModuleMap

/-- The canonical inclusion of the ideal module into the structure sheaf. -/
def idealModuleInclusion (D : EffectiveCartierDivisor X) :
    D.idealModule ⟶ SheafOfModules.unit X.ringCatSheaf :=
  Limits.kernel.ι D.idealModuleMap

/-- Multiplication by a section on an open subset, as a morphism of module sheaves on the
corresponding over-site. -/
def localEquationMul (U : X.Opens) (r : Γ(X, U)) :
    (SheafOfModules.unit X.ringCatSheaf).over U ⟶
      (SheafOfModules.unit X.ringCatSheaf).over U where
  val.app A :=
    let M := ((SheafOfModules.unit X.ringCatSheaf).over U).val.obj A
    let a : (X.ringCatSheaf.over U).obj.obj A :=
      X.presheaf.map A.unop.hom.op r
    ModuleCat.homMk (M.smul a)
    (fun s ↦ by
      apply AddCommGrpCat.hom_ext
      ext x
      change s • (a • (show M from x)) = a • (s • (show M from x))
      rw [smul_smul, smul_smul]
      have hsa : (show Γ(X, A.unop.left) from s) *
          (show Γ(X, A.unop.left) from a) =
          (show Γ(X, A.unop.left) from a) *
            (show Γ(X, A.unop.left) from s) := mul_comm _ _
      exact congrArg (fun z : (X.ringCatSheaf.over U).obj.obj A ↦
        z • (show M from x)) hsa)
  val.naturality {A B} g := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro x
    let aA : (X.ringCatSheaf.over U).obj.obj A :=
      X.presheaf.map A.unop.hom.op r
    let aB : (X.ringCatSheaf.over U).obj.obj B :=
      X.presheaf.map B.unop.hom.op r
    change aB •
        ((SheafOfModules.unit X.ringCatSheaf).over U).val.map g x =
      ((SheafOfModules.unit X.ringCatSheaf).over U).val.map g (aA • x)
    rw [PresheafOfModules.map_smul]
    congr 1
    change X.presheaf.map B.unop.hom.op r =
      X.presheaf.map g.unop.left.op (X.presheaf.map A.unop.hom.op r)
    rw [← Functor.map_comp_apply, ← op_comp, g.unop.w]

theorem localEquationMul_comp_idealModuleMap_over
    (D : EffectiveCartierDivisor X) (U : X.affineOpens)
    (r : Γ(X, U.1)) (hr : D.idealSheaf.ideal U = Ideal.span {r}) :
    localEquationMul U.1 r ≫
      (SheafOfModules.overFunctor X.ringCatSheaf U.1).map D.idealModuleMap = 0 := by
  apply SheafOfModules.hom_ext
  apply PresheafOfModules.hom_ext
  intro A
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  change D.ι.app A.unop.left
      (X.presheaf.map A.unop.hom.op r *
        (show Γ(X, A.unop.left) from x)) = 0
  rw [map_mul]
  have hr0 : D.ι.app U.1 r = 0 := by
    change D.idealSheaf.subschemeι.app U.1 r = 0
    have hrmem : r ∈ D.idealSheaf.ideal U := by
      rw [hr]
      exact Ideal.mem_span_singleton_self r
    exact (show r ∈ RingHom.ker (D.idealSheaf.subschemeι.app U.1).hom by
      rw [D.idealSheaf.ker_subschemeι_app U]
      exact hrmem)
  have hnat := congrArg (fun k ↦ ModuleCat.Hom.hom k r)
    (D.idealModuleMap.val.naturality A.unop.hom.op)
  change D.ι.app A.unop.left
      (X.presheaf.map A.unop.hom.op r) =
    ((Scheme.Modules.pushforward D.ι).obj
        (SheafOfModules.unit D.subscheme.ringCatSheaf)).val.map
      A.unop.hom.op (D.ι.app U.1 r) at hnat
  have hres : D.ι.app A.unop.left
      (X.presheaf.map A.unop.hom.op r) = 0 := by
    rw [hr0] at hnat
    exact hnat.trans <|
      (((Scheme.Modules.pushforward D.ι).obj
          (SheafOfModules.unit D.subscheme.ringCatSheaf)).val.map
            A.unop.hom.op).hom.map_zero
  rw [hres, zero_mul]

/-- Multiplication by a local equation, factored through the kernel defining the ideal module. -/
def localEquationLift (D : EffectiveCartierDivisor X) (U : X.affineOpens)
    (r : Γ(X, U.1)) (hr : D.idealSheaf.ideal U = Ideal.span {r}) :
    (SheafOfModules.unit X.ringCatSheaf).over U.1 ⟶
      Limits.kernel ((SheafOfModules.overFunctor X.ringCatSheaf U.1).map
        D.idealModuleMap) :=
  Limits.kernel.lift _ (localEquationMul U.1 r)
    (localEquationMul_comp_idealModuleMap_over D U r hr)

@[reassoc (attr := simp)]
theorem localEquationLift_comp_ι (D : EffectiveCartierDivisor X)
    (U : X.affineOpens) (r : Γ(X, U.1))
    (hr : D.idealSheaf.ideal U = Ideal.span {r}) :
    localEquationLift D U r hr ≫
      Limits.kernel.ι ((SheafOfModules.overFunctor X.ringCatSheaf U.1).map
        D.idealModuleMap) = localEquationMul U.1 r := by
  simp [localEquationLift]

/-- On every affine subopen, multiplication by a regular local equation maps bijectively onto
the kernel defining the ideal module. -/
theorem localEquationLift_app_bijective (D : EffectiveCartierDivisor X)
    (U : X.affineOpens) (r : Γ(X, U.1))
    (hr : D.idealSheaf.ideal U = Ideal.span {r}) (hreg : IsRegular r)
    (A : (Over U.1)ᵒᵖ) (hA : IsAffineOpen A.unop.left) :
    Function.Bijective ((localEquationLift D U r hr).val.app A) := by
  let W : X.affineOpens := ⟨A.unop.left, hA⟩
  let rW : Γ(X, W.1) := X.presheaf.map A.unop.hom.op r
  have hregW : IsRegular rW :=
    isRegular_map_of_flat _ (flat_affineOpenRestriction U W A.unop.hom.le) hreg
  have hideal : D.idealSheaf.ideal W = Ideal.span {rW} := by
    rw [← D.idealSheaf.map_ideal A.unop.hom.le, hr, Ideal.map_span,
      Set.image_singleton]
    rfl
  let qU := (SheafOfModules.overFunctor X.ringCatSheaf U.1).map D.idealModuleMap
  let kι := Limits.kernel.ι qU
  have hfac : localEquationLift D U r hr ≫ kι = localEquationMul U.1 r := by
    exact localEquationLift_comp_ι D U r hr
  have heval (t) : kι.val.app A ((localEquationLift D U r hr).val.app A t) =
      (localEquationMul U.1 r).val.app A t := by
    exact congrArg (fun h ↦ ModuleCat.Hom.hom (h.val.app A) t) hfac
  have hkιinj : Function.Injective (kι.val.app A) := by
    apply (ModuleCat.mono_iff_injective (kι.val.app A)).mp
    change Mono ((SheafOfModules.evaluation
      (X.ringCatSheaf.over U.1) A).map kι)
    infer_instance
  constructor
  · intro x y hxy
    have hinc := congrArg (fun z ↦ kι.val.app A z) hxy
    rw [heval x, heval y] at hinc
    change rW * (show Γ(X, W.1) from x) =
      rW * (show Γ(X, W.1) from y) at hinc
    exact hregW.left hinc
  · intro z
    let y : Γ(X, W.1) := kι.val.app A z
    have hyker : D.ι.app W.1 y = 0 := by
      have hk := congrArg (fun h ↦ ModuleCat.Hom.hom (h.val.app A) z)
        (Limits.kernel.condition qU)
      change D.ι.app W.1 y = 0 at hk
      exact hk
    have hyI : y ∈ D.idealSheaf.ideal W := by
      rw [← D.idealSheaf.ker_subschemeι_app W]
      exact hyker
    rw [hideal, Ideal.mem_span_singleton] at hyI
    obtain ⟨x, hx⟩ := hyI
    refine ⟨x, ?_⟩
    apply hkιinj
    rw [heval x]
    change rW * (show Γ(X, W.1) from x) = y
    exact hx.symm

/-- The underlying additive-presheaf map of `localEquationLift`. -/
abbrev localEquationLiftAdd (D : EffectiveCartierDivisor X)
    (U : X.affineOpens) (r : Γ(X, U.1))
    (hr : D.idealSheaf.ideal U = Ideal.span {r}) :=
  (PresheafOfModules.toPresheaf (X.ringCatSheaf.over U.1).obj).map
    (localEquationLift D U r hr).val

theorem localEquationLiftAdd_isLocallyInjective
    (D : EffectiveCartierDivisor X) (U : X.affineOpens)
    (r : Γ(X, U.1)) (hr : D.idealSheaf.ideal U = Ideal.span {r})
    (hreg : IsRegular r) :
    Presheaf.IsLocallyInjective ((Opens.grothendieckTopology X).over U.1)
      (localEquationLiftAdd D U r hr) := by
  constructor
  intro A x y hxy
  rw [GrothendieckTopology.mem_over_iff, Opens.mem_grothendieckTopology]
  intro p hp
  obtain ⟨_, ⟨W : X.Opens, hW, rfl⟩, hpW, hWA⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hp A.unop.left.isOpen
  let B : Over U.1 := Over.mk (homOfLE (hWA.trans A.unop.hom.le))
  let g : B ⟶ A.unop := Over.homMk (homOfLE hWA)
  refine ⟨W, homOfLE hWA, ?_, hpW⟩
  rw [Sieve.overEquiv_iff]
  dsimp only [Presheaf.equalizerSieve]
  change (((SheafOfModules.unit X.ringCatSheaf).over U.1).val.map g.op x) =
    (((SheafOfModules.unit X.ringCatSheaf).over U.1).val.map g.op y)
  apply (localEquationLift_app_bijective D U r hr hreg (Opposite.op B) hW).1
  exact (NatTrans.naturality_apply (localEquationLiftAdd D U r hr) g.op x).trans
    ((congrArg (fun z ↦
      ((PresheafOfModules.toPresheaf (X.ringCatSheaf.over U.1).obj).obj
        (Limits.kernel ((SheafOfModules.overFunctor X.ringCatSheaf U.1).map
          D.idealModuleMap)).val).map g.op z) hxy).trans
      (NatTrans.naturality_apply (localEquationLiftAdd D U r hr) g.op y).symm)

theorem localEquationLiftAdd_isLocallySurjective
    (D : EffectiveCartierDivisor X) (U : X.affineOpens)
    (r : Γ(X, U.1)) (hr : D.idealSheaf.ideal U = Ideal.span {r})
    (hreg : IsRegular r) :
    Presheaf.IsLocallySurjective ((Opens.grothendieckTopology X).over U.1)
      (localEquationLiftAdd D U r hr) := by
  constructor
  intro A s
  rw [GrothendieckTopology.mem_over_iff, Opens.mem_grothendieckTopology]
  intro p hp
  obtain ⟨_, ⟨W : X.Opens, hW, rfl⟩, hpW, hWA⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hp A.left.isOpen
  let B : Over U.1 := Over.mk (homOfLE (hWA.trans A.hom.le))
  let g : B ⟶ A := Over.homMk (homOfLE hWA)
  refine ⟨W, homOfLE hWA, ?_, hpW⟩
  rw [Sieve.overEquiv_iff]
  change Presheaf.imageSieve (localEquationLiftAdd D U r hr) s g
  exact (localEquationLift_app_bijective D U r hr hreg (Opposite.op B) hW).2
    (((PresheafOfModules.toPresheaf (X.ringCatSheaf.over U.1).obj).obj
      (Limits.kernel ((SheafOfModules.overFunctor X.ringCatSheaf U.1).map
        D.idealModuleMap)).val).map g.op s)

set_option linter.style.haveILetI false in
/-- Multiplication by a regular local equation is an isomorphism onto the local kernel. -/
theorem localEquationLift_isIso (D : EffectiveCartierDivisor X)
    (U : X.affineOpens) (r : Γ(X, U.1))
    (hr : D.idealSheaf.ideal U = Ideal.span {r}) (hreg : IsRegular r) :
    IsIso (localEquationLift D U r hr) := by
  letI : ((Opens.grothendieckTopology X).over U.1).HasSheafCompose
      (forget AddCommGrpCat.{u}) := by
    apply CategoryTheory.hasSheafCompose_of_preservesLimitsOfSize
  rw [← isIso_iff_of_reflects_iso _
    (SheafOfModules.toSheaf (X.ringCatSheaf.over U.1))]
  apply (Sheaf.isLocallyBijective_iff_isIso
    (J := (Opens.grothendieckTopology X).over U.1)
    (A := AddCommGrpCat.{u})
    ((SheafOfModules.toSheaf (X.ringCatSheaf.over U.1)).map
      (localEquationLift D U r hr))).mp
  constructor
  · change Presheaf.IsLocallyInjective
      ((Opens.grothendieckTopology X).over U.1)
      (localEquationLiftAdd D U r hr)
    exact localEquationLiftAdd_isLocallyInjective D U r hr hreg
  · change Presheaf.IsLocallySurjective
      ((Opens.grothendieckTopology X).over U.1)
      (localEquationLiftAdd D U r hr)
    exact localEquationLiftAdd_isLocallySurjective D U r hr hreg

/-- A regular local equation gives an explicit free rank-one trivialization of the ideal module. -/
def localEquationIdealModuleIso (D : EffectiveCartierDivisor X)
    (U : X.affineOpens) (r : Γ(X, U.1))
    (hr : D.idealSheaf.ideal U = Ideal.span {r}) (hreg : IsRegular r) :
    SheafOfModules.free (R := X.ringCatSheaf.over U.1) (ULift.{u, 0} PUnit) ≅
      D.idealModule.over U.1 := by
  let eLift : (SheafOfModules.unit X.ringCatSheaf).over U.1 ≅
      Limits.kernel ((SheafOfModules.overFunctor X.ringCatSheaf U.1).map
        D.idealModuleMap) := by
    haveI : IsIso (localEquationLift D U r hr) :=
      localEquationLift_isIso D U r hr hreg
    exact asIso (localEquationLift D U r hr)
  letI hZero : Limits.HasZeroMorphisms X.Modules :=
    Preadditive.preadditiveHasZeroMorphisms
  let F := SheafOfModules.overFunctor X.ringCatSheaf U.1
  letI hPresLimit : Limits.PreservesLimit (Limits.parallelPair D.idealModuleMap
      (0 : (show X.Modules from SheafOfModules.unit X.ringCatSheaf) ⟶
        (show X.Modules from (Scheme.Modules.pushforward D.ι).obj
          (SheafOfModules.unit D.subscheme.ringCatSheaf)))) F :=
    ⟨fun {c} hc ↦ ⟨by
      apply Limits.isLimitOfReflects (SheafOfModules.forget (X.ringCatSheaf.over U.1))
      apply PresheafOfModules.evaluationJointlyReflectsLimits
      intro V
      exact Limits.isLimitOfPreserves
        (SheafOfModules.evaluation X.ringCatSheaf (Opposite.op V.unop.left)) hc⟩⟩
  letI hPresZero : Functor.PreservesZeroMorphisms F :=
    ⟨fun A B ↦ by
      apply SheafOfModules.hom_ext
      apply PresheafOfModules.hom_ext
      intro V
      rfl⟩
  let eKernel := @Limits.PreservesKernel.iso
    X.Modules _ hZero
    (SheafOfModules.{u} (X.ringCatSheaf.over U.1)) _ _
    F hPresZero _ _ D.idealModuleMap _ _ hPresLimit
  exact freePUnitOverIsoUnit U.1 ≪≫ eLift ≪≫ eKernel.symm

/-- A chosen affine local-equation neighbourhood around a point of `D`. -/
def localEquationOpen (D : EffectiveCartierDivisor X) (x : X) : X.affineOpens :=
  (D.isEffectiveCartier x).choose

theorem mem_localEquationOpen (D : EffectiveCartierDivisor X) (x : X) :
    x ∈ (D.localEquationOpen x).1 :=
  (D.isEffectiveCartier x).choose_spec.1

/-- A chosen regular equation for `D` around a point. -/
def localEquation (D : EffectiveCartierDivisor X) (x : X) :
    Γ(X, (D.localEquationOpen x).1) :=
  (D.isEffectiveCartier x).choose_spec.2.choose

theorem localEquation_isRegular (D : EffectiveCartierDivisor X) (x : X) :
    IsRegular (D.localEquation x) :=
  (D.isEffectiveCartier x).choose_spec.2.choose_spec.1

theorem ideal_localEquationOpen (D : EffectiveCartierDivisor X) (x : X) :
    D.idealSheaf.ideal (D.localEquationOpen x) =
      Ideal.span {D.localEquation x} :=
  (D.isEffectiveCartier x).choose_spec.2.choose_spec.2

theorem localEquationOpen_coversTop (D : EffectiveCartierDivisor X) :
    (Opens.grothendieckTopology X).CoversTop
      (fun x : X ↦ (D.localEquationOpen x).1) := by
  rw [Opens.coversTop_iff]
  apply top_unique
  intro x hx
  exact Opens.mem_iSup.mpr ⟨x, D.mem_localEquationOpen x⟩

/-- The ideal module of an effective Cartier divisor is locally free of rank one. -/
theorem idealModule_hasRankOneTrivialization (D : EffectiveCartierDivisor X) :
    HasRankOneTrivialization D.idealModule :=
  HasRankOneTrivialization.of_freePUnitIso
    (fun x : X ↦ (D.localEquationOpen x).1)
    D.localEquationOpen_coversTop
    (fun x ↦ localEquationIdealModuleIso D (D.localEquationOpen x)
      (D.localEquation x) (D.ideal_localEquationOpen x)
      (D.localEquation_isRegular x))

/-- The ideal module of an effective Cartier divisor is invertible. -/
theorem idealModule_isInvertible (D : EffectiveCartierDivisor X) :
    IsInvertible D.idealModule :=
  ⟨D.idealModule, D.idealModule_hasRankOneTrivialization, ⟨Iso.refl _⟩⟩

/-- The invertible ideal module `O_X(-D)` associated to an effective Cartier divisor. -/
def idealLineBundle (D : EffectiveCartierDivisor X) : LineBundle X where
  obj := D.idealModule
  isInvertible := D.idealModule_isInvertible

@[simp]
theorem idealLineBundle_obj (D : EffectiveCartierDivisor X) :
    D.idealLineBundle.obj = D.idealModule := rfl

/-- The associated line bundle `O_X(D)`, dual to the invertible ideal module `O_X(-D)`. -/
def associatedLineBundle (D : EffectiveCartierDivisor X) : LineBundle X :=
  D.idealLineBundle.dual

@[simp]
theorem associatedLineBundle_obj (D : EffectiveCartierDivisor X) :
    D.associatedLineBundle.obj = moduleDual D.idealModule := rfl

/-- Pullback of an effective Cartier divisor along an open immersion. -/
def pullbackOpen {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] : EffectiveCartierDivisor X where
  idealSheaf := D.idealSheaf.comap f
  isEffectiveCartier :=
    comap_isEffectiveCartierIdealSheaf_of_isOpenImmersion D.idealSheaf f D.isEffectiveCartier

@[simp]
theorem pullbackOpen_idealSheaf {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] :
    (D.pullbackOpen f).idealSheaf = D.idealSheaf.comap f := rfl

/-- The subscheme of an open pullback is canonically the scheme-theoretic fiber product. -/
def pullbackOpenSubschemeIso {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] :
    (D.pullbackOpen f).subscheme ≅ CategoryTheory.Limits.pullback f D.ι :=
  D.idealSheaf.comapIso f

/-- Pullback along the identity leaves an effective Cartier divisor unchanged. -/
@[simp]
theorem pullbackOpen_id (D : EffectiveCartierDivisor X) : D.pullbackOpen (𝟙 X) = D := by
  apply ext
  exact D.idealSheaf.comap_id

/-- The empty divisor pulls back to the empty divisor along an open immersion. -/
@[simp]
theorem pullbackOpen_empty {Y : Scheme.{u}} (f : X ⟶ Y) [IsOpenImmersion f] :
    (empty Y).pullbackOpen f = empty X := by
  apply ext
  simp [pullbackOpen, empty]

/-- Open pullback is coherent under composition. -/
theorem pullbackOpen_comp {Y Z : Scheme.{u}} (D : EffectiveCartierDivisor Z)
    (f : X ⟶ Y) (g : Y ⟶ Z) [IsOpenImmersion f] [IsOpenImmersion g] :
    D.pullbackOpen (f ≫ g) = (D.pullbackOpen g).pullbackOpen f := by
  apply ext
  exact D.idealSheaf.comap_comp f g

/-- The support of an open pullback is the inverse image of the original support. -/
theorem pullbackOpen_support {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] :
    (D.pullbackOpen f).support = D.support.preimage f.continuous := by
  exact D.idealSheaf.support_comap f

/-- Scheme-theoretic inverse image of an effective Cartier divisor along a flat morphism. -/
def pullbackFlat {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] : EffectiveCartierDivisor X where
  idealSheaf := D.idealSheaf.comap f
  isEffectiveCartier :=
    comap_isEffectiveCartierIdealSheaf_of_flat D.idealSheaf f D.isEffectiveCartier

@[simp]
theorem pullbackFlat_idealSheaf {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] :
    (D.pullbackFlat f).idealSheaf = D.idealSheaf.comap f := rfl

/-- The subscheme of a flat pullback is canonically the scheme-theoretic fiber product. -/
def pullbackFlatSubschemeIso {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] :
    (D.pullbackFlat f).subscheme ≅ CategoryTheory.Limits.pullback f D.ι :=
  D.idealSheaf.comapIso f

/-- After an effective Cartier graph is pulled back through an étale separated coordinate and its
distinguished component is isolated, the kernel of that component section is exactly the
restricted pulled-back Cartier ideal. -/
theorem isolatedSection_ker_eq_cartierIdeal
    {A : Scheme.{u}} (D : EffectiveCartierDivisor A)
    (q : X ⟶ A) [Etale q] [IsSeparated q]
    (s : D.subscheme ⟶ X) (h : s ≫ q = D.ι) :
    (sectionToAmbientOpenOfEtaleGraph q D.ι s h).ker =
      ((D.pullbackFlat q).pullbackOpen
        (ambientOpenOfEtaleGraph q D.ι s h).ι).idealSheaf := by
  rw [← isolatedPullbackComponentIso_hom_restrict q D.ι s h]
  rw [Scheme.Hom.ker_comp_of_isIso]
  rw [ker_morphismRestrict]
  rw [Scheme.IdealSheafData.ker_fst_of_isClosedImmersion]
  change ((D.idealSheaf.subschemeι).ker.comap q).comap _ =
    (D.idealSheaf.comap q).comap _
  rw [Scheme.IdealSheafData.ker_subschemeι]

/-- Consequently, the isolated component section of an étale pullback of a Cartier graph is itself
an effective Cartier divisor. -/
theorem isolatedSection_ker_isEffectiveCartierIdealSheaf
    {A : Scheme.{u}} (D : EffectiveCartierDivisor A)
    (q : X ⟶ A) [Etale q] [IsSeparated q]
    (s : D.subscheme ⟶ X) (h : s ≫ q = D.ι) :
    IsEffectiveCartierIdealSheaf
      (sectionToAmbientOpenOfEtaleGraph q D.ι s h).ker := by
  rw [isolatedSection_ker_eq_cartierIdeal D q s h]
  exact ((D.pullbackFlat q).pullbackOpen
    (ambientOpenOfEtaleGraph q D.ι s h).ι).isEffectiveCartier

/-- The section defined by a retraction of a standard-smooth relative-dimension-one affine ring
map is an effective Cartier divisor.  An étale coordinate identifies the section locally with an
affine-line graph; its distinguished graph component supplies the Cartier equation near the
section, while the kernel is the unit ideal on the complementary open. -/
theorem affineSection_ker_isEffectiveCartierIdealSheaf_of_isStandardSmoothOfRelativeDimension
    {R T : Type u} [CommRing R] [CommRing T]
    (f : R →+* T) (hf : f.IsStandardSmoothOfRelativeDimension 1)
    (r : T →+* R) (hr : r.comp f = RingHom.id R) :
    IsEffectiveCartierIdealSheaf
      (Spec.map (CommRingCat.ofHom r)).ker := by
  obtain ⟨g, hgf, hg⟩ :=
    exists_etale_polynomial_coordinate_of_isStandardSmoothOfRelativeDimension hf
  let q : Spec (.of T) ⟶ Spec (.of (Polynomial R)) :=
    Spec.map (CommRingCat.ofHom g)
  let _ : Etale q := (HasRingHomProperty.Spec_iff (P := @Etale)
    (Q := @RingHom.Etale)).2 hg
  let s : Spec (.of R) ⟶ Spec (.of T) :=
    Spec.map (CommRingCat.ofHom r)
  have hr_surjective : Function.Surjective r := by
    intro x
    refine ⟨f x, ?_⟩
    have hx := DFunLike.congr_fun hr x
    simpa only [RingHom.comp_apply, RingHom.id_apply] using hx
  let _ : IsClosedImmersion s :=
    IsClosedImmersion.spec_of_surjective (CommRingCat.ofHom r) hr_surjective
  let a : R := r (g Polynomial.X)
  let t := affineLineGraphSection R a
  have hsq : s ≫ q = t := by
    dsimp only [s, q, t, affineLineGraphSection]
    rw [← Spec.map_comp, Spec.map_inj]
    apply CommRingCat.hom_ext
    change r.comp g = Polynomial.evalRingHom a
    apply Polynomial.ringHom_ext
    · intro x
      have hconst : g (Polynomial.C x) = f x := by
        simpa [RingHom.comp_apply] using DFunLike.congr_fun hgf x
      have hret := DFunLike.congr_fun hr x
      simpa [RingHom.comp_apply] using congrArg r hconst |>.trans hret
    · simp [RingHom.comp_apply, a]
  let D := affineLineGraph R a
  let e := affineLineGraphSubschemeIso R a
  let sD : D.subscheme ⟶ Spec (.of T) := e.inv ≫ s
  have hsDq : sD ≫ q = D.ι := by
    rw [← cancel_epi e.hom]
    dsimp only [sD, e, D]
    simp only [Category.assoc, Iso.hom_inv_id_assoc,
      affineLineGraphSubschemeIso_hom_ι]
    exact hsq
  let V : (Spec (.of T)).Opens := ambientOpenOfEtaleGraph q D.ι sD hsDq
  let sV : D.subscheme ⟶ V.toScheme :=
    sectionToAmbientOpenOfEtaleGraph q D.ι sD hsDq
  have hcartierV : IsEffectiveCartierIdealSheaf sV.ker :=
    isolatedSection_ker_isEffectiveCartierIdealSheaf D q sD hsDq
  let sV₀ : Spec (.of R) ⟶ V.toScheme := e.hom ≫ sV
  have hsV₀ : sV₀ ≫ V.ι = s := by
    dsimp only [sV₀, sV]
    rw [Category.assoc, sectionToAmbientOpenOfEtaleGraph_ι]
    dsimp only [sD]
    simp
  have hkerV₀ : sV₀.ker = sV.ker :=
    Scheme.Hom.ker_comp_of_isIso e.hom sV
  have hcartierV₀ : IsEffectiveCartierIdealSheaf sV₀.ker := by
    rw [hkerV₀]
    exact hcartierV
  have hrestrictV : s.ker.comap V.ι = sV₀.ker :=
    (ker_factorThrough_open s V sV₀ hsV₀).symm
  let W : (Spec (.of T)).Opens := complementOfClosedImmersion s
  have htopW : s.ker.comap W.ι = ⊤ :=
    ker_comap_complementOfClosedImmersion_eq_top s
  let U : Bool → (Spec (.of T)).Opens := fun b ↦ if b then V else W
  have hU : ⨆ b, U b = ⊤ := by
    apply top_unique
    intro x _
    by_cases hx : x ∈ Set.range s
    · apply TopologicalSpace.Opens.mem_iSup.mpr
      refine ⟨true, ?_⟩
      change x ∈ V
      obtain ⟨z, rfl⟩ := hx
      exact range_subset_ambientOpenOfEtaleGraph q D.ι sD hsDq
        ⟨e.hom z, by simp [sD]⟩
    · apply TopologicalSpace.Opens.mem_iSup.mpr
      refine ⟨false, ?_⟩
      exact hx
  change IsEffectiveCartierIdealSheaf s.ker
  apply isEffectiveCartierIdealSheaf_of_openCover s.ker U hU
  intro b
  cases b
  · change IsEffectiveCartierIdealSheaf (s.ker.comap W.ι)
    rw [htopW]
    exact top_isEffectiveCartierIdealSheaf
  · change IsEffectiveCartierIdealSheaf (s.ker.comap V.ι)
    rw [hrestrictV]
    exact hcartierV₀

/-- An affine closed section is an effective Cartier divisor whenever the induced map on global
sections is standard smooth of relative dimension one. -/
theorem affineSchemeSection_ker_isEffectiveCartierIdealSheaf
    {S : Scheme.{u}} (f : X ⟶ S) [IsAffine X] [IsAffine S]
    (s : S ⟶ X) [IsClosedImmersion s]
    (h : s ≫ f = 𝟙 S)
    (hf : f.appTop.hom.IsStandardSmoothOfRelativeDimension 1) :
    IsEffectiveCartierIdealSheaf s.ker := by
  have hr : s.appTop.hom.comp f.appTop.hom = RingHom.id Γ(S, ⊤) := by
    calc
      s.appTop.hom.comp f.appTop.hom = (f.appTop ≫ s.appTop).hom := rfl
      _ = (s ≫ f).appTop.hom :=
        congrArg CommRingCat.Hom.hom (Scheme.Hom.comp_appTop s f).symm
      _ = (Scheme.Hom.appTop (𝟙 S)).hom :=
        congrArg (fun k : S ⟶ S ↦ k.appTop.hom) h
      _ = RingHom.id Γ(S, ⊤) := rfl
  let sSpec : Spec Γ(S, ⊤) ⟶ Spec Γ(X, ⊤) := Spec.map s.appTop
  have hcartierSpec : IsEffectiveCartierIdealSheaf sSpec.ker :=
    affineSection_ker_isEffectiveCartierIdealSheaf_of_isStandardSmoothOfRelativeDimension
      f.appTop.hom hf s.appTop.hom hr
  let s' : Spec Γ(S, ⊤) ⟶ X := S.isoSpec.inv ≫ s
  have hs' : s' ≫ X.isoSpec.hom = sSpec := by
    rw [← cancel_epi S.isoSpec.hom]
    dsimp only [s', sSpec]
    simp only [Category.assoc, Iso.hom_inv_id_assoc,
      Scheme.isoSpec_hom_naturality]
  let _ : IsClosedImmersion sSpec := by
    rw [← hs']
    infer_instance
  have hker' : s'.ker = s.ker :=
    Scheme.Hom.ker_comp_of_isIso S.isoSpec.inv s
  have hcomap : sSpec.ker.comap X.isoSpec.hom = s.ker := by
    rw [← hker']
    exact (ker_factorThrough_mono sSpec X.isoSpec.hom s' hs').symm
  rw [← hcomap]
  exact comap_isEffectiveCartierIdealSheaf_of_flat sSpec.ker X.isoSpec.hom hcartierSpec

/-- The effective Cartier divisor defined by an affine closed section of a standard-smooth
relative-dimension-one morphism. -/
def ofAffineSection {S : Scheme.{u}} (f : X ⟶ S) [IsAffine X] [IsAffine S]
    (s : S ⟶ X) [IsClosedImmersion s]
    (h : s ≫ f = 𝟙 S)
    (hf : f.appTop.hom.IsStandardSmoothOfRelativeDimension 1) :
    EffectiveCartierDivisor X where
  idealSheaf := s.ker
  isEffectiveCartier :=
    affineSchemeSection_ker_isEffectiveCartierIdealSheaf f s h hf

@[simp]
theorem ofAffineSection_idealSheaf {S : Scheme.{u}}
    (f : X ⟶ S) [IsAffine X] [IsAffine S]
    (s : S ⟶ X) [IsClosedImmersion s]
    (h : s ≫ f = 𝟙 S)
    (hf : f.appTop.hom.IsStandardSmoothOfRelativeDimension 1) :
    (ofAffineSection f s h hf).idealSheaf = s.ker := rfl

/-- The divisor subscheme of an affine standard-smooth section is canonically its source. -/
def ofAffineSectionSubschemeIso {S : Scheme.{u}}
    (f : X ⟶ S) [IsAffine X] [IsAffine S]
    (s : S ⟶ X) [IsClosedImmersion s]
    (h : s ≫ f = 𝟙 S)
    (hf : f.appTop.hom.IsStandardSmoothOfRelativeDimension 1) :
    S ≅ (ofAffineSection f s h hf).subscheme :=
  closedImmersionSubschemeIsoOfKerEq s (ofAffineSection f s h hf).idealSheaf rfl

@[reassoc (attr := simp)]
theorem ofAffineSectionSubschemeIso_hom_ι {S : Scheme.{u}}
    (f : X ⟶ S) [IsAffine X] [IsAffine S]
    (s : S ⟶ X) [IsClosedImmersion s]
    (h : s ≫ f = 𝟙 S)
    (hf : f.appTop.hom.IsStandardSmoothOfRelativeDimension 1) :
    (ofAffineSectionSubschemeIso f s h hf).hom ≫ (ofAffineSection f s h hf).ι = s :=
  closedImmersionSubschemeIsoOfKerEq_hom_subschemeι
    s (ofAffineSection f s h hf).idealSheaf rfl

/-- Flat pullback along the identity leaves an effective Cartier divisor unchanged. -/
@[simp]
theorem pullbackFlat_id (D : EffectiveCartierDivisor X) :
    D.pullbackFlat (𝟙 X) = D := by
  apply ext
  exact D.idealSheaf.comap_id

/-- The empty divisor pulls back to the empty divisor along a flat morphism. -/
@[simp]
theorem pullbackFlat_empty {Y : Scheme.{u}} (f : X ⟶ Y) [Flat f] :
    (empty Y).pullbackFlat f = empty X := by
  apply ext
  simp [pullbackFlat, empty]

/-- Flat pullback is coherent under composition. -/
theorem pullbackFlat_comp {Y Z : Scheme.{u}} (D : EffectiveCartierDivisor Z)
    (f : X ⟶ Y) (g : Y ⟶ Z) [Flat f] [Flat g] :
    D.pullbackFlat (f ≫ g) = (D.pullbackFlat g).pullbackFlat f := by
  apply ext
  exact D.idealSheaf.comap_comp f g

/-- The support of a flat pullback is the inverse image of the original support. -/
theorem pullbackFlat_support {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] :
    (D.pullbackFlat f).support = D.support.preimage f.continuous := by
  exact D.idealSheaf.support_comap f

/-- For an open immersion, the general flat pullback agrees with open pullback. -/
theorem pullbackFlat_eq_pullbackOpen {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] :
    D.pullbackFlat f = D.pullbackOpen f := by
  rfl

/-- On an affine scheme, the divisor defined by a global regular equation has the expected
set-theoretic zero locus. -/
theorem range_ofGlobalEquation_ι (X : Scheme.{u}) [IsAffine X]
    (r : Γ(X, ⊤)) (hr : IsRegular r) :
    Set.range (ofGlobalEquation X r hr).ι =
      X.zeroLocus (U := ⊤) (Ideal.span {r}) := by
  rw [range_ι]
  rfl

/-- Flat inverse image of a globally principal effective Cartier divisor between affine schemes.
The pulled-back equation stays regular by flatness. -/
def inverseImageGlobalEquation {X Y : Scheme.{u}} [IsAffine X] [IsAffine Y]
    (f : X ⟶ Y) [Flat f] (r : Γ(Y, ⊤)) (hr : IsRegular r) :
    EffectiveCartierDivisor X :=
  ofGlobalEquation X (f.appTop r) <|
    isRegular_map_of_flat f.appTop.hom
      ((HasRingHomProperty.iff_of_isAffine (P := @Flat)).mp (inferInstance : Flat f)) hr

@[simp]
theorem inverseImageGlobalEquation_ideal_top {X Y : Scheme.{u}} [IsAffine X] [IsAffine Y]
    (f : X ⟶ Y) [Flat f] (r : Γ(Y, ⊤)) (hr : IsRegular r) :
    (inverseImageGlobalEquation f r hr).idealSheaf.ideal
      ⟨⊤, isAffineOpen_top X⟩ = Ideal.span {f.appTop r} := by
  simp [inverseImageGlobalEquation]

/-- The general flat pullback agrees with extension of a global equation in the affine case. -/
theorem pullbackFlat_ofGlobalEquation {Y : Scheme.{u}} [IsAffine X] [IsAffine Y]
    (f : X ⟶ Y) [Flat f] (r : Γ(Y, ⊤)) (hr : IsRegular r) :
    (ofGlobalEquation Y r hr).pullbackFlat f = inverseImageGlobalEquation f r hr := by
  apply ext
  apply Scheme.IdealSheafData.ext_of_isAffine
  rw [pullbackFlat_idealSheaf,
    idealSheaf_comap_ideal (ofGlobalEquation Y r hr).idealSheaf f
      ⟨⊤, isAffineOpen_top Y⟩ ⟨⊤, isAffineOpen_top X⟩ (by simp),
    ofGlobalEquation_ideal_top, Ideal.map_span, Set.image_singleton,
    inverseImageGlobalEquation_ideal_top]
  simp [Scheme.Hom.appTop, Scheme.Hom.app_eq_appLE]

/-- Pulling a globally principal Cartier divisor back along the identity changes nothing. -/
theorem inverseImageGlobalEquation_id (X : Scheme.{u}) [IsAffine X]
    (r : Γ(X, ⊤)) (hr : IsRegular r) :
    inverseImageGlobalEquation (𝟙 X) r hr = ofGlobalEquation X r hr := by
  apply ext
  apply Scheme.IdealSheafData.ext_of_isAffine
  simp [inverseImageGlobalEquation]

/-- Flat inverse image of globally principal Cartier divisors is coherent under composition. -/
theorem inverseImageGlobalEquation_comp {X Y Z : Scheme.{u}}
    [IsAffine X] [IsAffine Y] [IsAffine Z]
    (f : X ⟶ Y) (g : Y ⟶ Z) [Flat f] [Flat g]
    (r : Γ(Z, ⊤)) (hr : IsRegular r) :
    inverseImageGlobalEquation (f ≫ g) r hr =
      inverseImageGlobalEquation f (g.appTop r)
        (isRegular_map_of_flat g.appTop.hom
          ((HasRingHomProperty.iff_of_isAffine (P := @Flat)).mp
            (inferInstance : Flat g)) hr) := by
  apply ext
  apply Scheme.IdealSheafData.ext_of_isAffine
  simp only [inverseImageGlobalEquation, ofGlobalEquation_ideal_top]
  congr 2

/-- The sum of two effective Cartier divisors given by global equations on an affine scheme is
cut out by the product of those equations. -/
def addGlobalEquations (X : Scheme.{u}) [IsAffine X]
    (r s : Γ(X, ⊤)) (hr : IsRegular r) (hs : IsRegular s) :
    EffectiveCartierDivisor X :=
  ofGlobalEquation X (r * s) (hr.mul hs)

/-- On ideal sheaves, addition of globally principal effective Cartier divisors is multiplication
of their defining ideals. -/
theorem addGlobalEquations_idealSheaf (X : Scheme.{u}) [IsAffine X]
    (r s : Γ(X, ⊤)) (hr : IsRegular r) (hs : IsRegular s) :
    (addGlobalEquations X r s hr hs).idealSheaf =
      (ofGlobalEquation X r hr).idealSheaf *
        (ofGlobalEquation X s hs).idealSheaf := by
  apply Scheme.IdealSheafData.ext_of_isAffine
  simp [addGlobalEquations, Ideal.span_singleton_mul_span_singleton]

/-- The support of a sum of globally principal effective Cartier divisors is the union of their
supports. -/
theorem addGlobalEquations_support (X : Scheme.{u}) [IsAffine X]
    (r s : Γ(X, ⊤)) (hr : IsRegular r) (hs : IsRegular s) :
    (addGlobalEquations X r s hr hs).support =
      (ofGlobalEquation X r hr).support ⊔
        (ofGlobalEquation X s hs).support := by
  change (addGlobalEquations X r s hr hs).idealSheaf.support =
    (ofGlobalEquation X r hr).idealSheaf.support ⊔
      (ofGlobalEquation X s hs).idealSheaf.support
  rw [addGlobalEquations_idealSheaf]
  exact Scheme.IdealSheafData.support_mul _ _

/-- Sum of arbitrary effective Cartier divisors, represented by the product of their ideal
sheaves. -/
def sum (D E : EffectiveCartierDivisor X) : EffectiveCartierDivisor X where
  idealSheaf := D.idealSheaf * E.idealSheaf
  isEffectiveCartier := mul_isEffectiveCartierIdealSheaf D.idealSheaf E.idealSheaf
    D.isEffectiveCartier E.isEffectiveCartier

@[simp]
theorem sum_idealSheaf (D E : EffectiveCartierDivisor X) :
    (D.sum E).idealSheaf = D.idealSheaf * E.idealSheaf := rfl

/-- The support of a sum of effective Cartier divisors is the union of their supports. -/
theorem sum_support (D E : EffectiveCartierDivisor X) :
    (D.sum E).support = D.support ⊔ E.support := by
  exact Scheme.IdealSheafData.support_mul _ _

@[simp]
theorem empty_sum (D : EffectiveCartierDivisor X) : (empty X).sum D = D := by
  apply ext
  simp [sum, empty]

@[simp]
theorem sum_empty (D : EffectiveCartierDivisor X) : D.sum (empty X) = D := by
  apply ext
  simp [sum, empty]

theorem sum_assoc (D E F : EffectiveCartierDivisor X) :
    (D.sum E).sum F = D.sum (E.sum F) := by
  apply ext
  simp [sum, mul_assoc]

theorem sum_comm (D E : EffectiveCartierDivisor X) : D.sum E = E.sum D := by
  apply ext
  simp [sum, mul_comm]

/-- Pullback along an open immersion preserves addition of effective Cartier divisors. -/
theorem pullbackOpen_sum {Y : Scheme.{u}} (D E : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] :
    (D.sum E).pullbackOpen f = (D.pullbackOpen f).sum (E.pullbackOpen f) := by
  apply ext
  exact idealSheaf_comap_mul_of_isOpenImmersion D.idealSheaf E.idealSheaf f

/-- Flat pullback preserves addition of arbitrary effective Cartier divisors. -/
theorem pullbackFlat_sum {Y : Scheme.{u}} (D E : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] :
    (D.sum E).pullbackFlat f = (D.pullbackFlat f).sum (E.pullbackFlat f) := by
  apply ext
  exact idealSheaf_comap_mul D.idealSheaf E.idealSheaf f

/-- The general divisor sum agrees with multiplying global equations in the globally principal
affine case. -/
theorem sum_ofGlobalEquation (X : Scheme.{u}) [IsAffine X]
    (r s : Γ(X, ⊤)) (hr : IsRegular r) (hs : IsRegular s) :
    (ofGlobalEquation X r hr).sum (ofGlobalEquation X s hs) =
      addGlobalEquations X r s hr hs := by
  apply ext
  exact (addGlobalEquations_idealSheaf X r s hr hs).symm

/-- Flat inverse image of globally principal affine divisors preserves their sum. -/
theorem inverseImageGlobalEquation_add {X Y : Scheme.{u}} [IsAffine X] [IsAffine Y]
    (f : X ⟶ Y) [Flat f] (r s : Γ(Y, ⊤)) (hr : IsRegular r) (hs : IsRegular s) :
    inverseImageGlobalEquation f (r * s) (hr.mul hs) =
      (inverseImageGlobalEquation f r hr).sum (inverseImageGlobalEquation f s hs) := by
  apply ext
  apply Scheme.IdealSheafData.ext_of_isAffine
  set_option backward.isDefEq.respectTransparency false in
    simp only [sum, inverseImageGlobalEquation_ideal_top,
      Scheme.IdealSheafData.ideal_mul]
  set_option backward.isDefEq.respectTransparency false in
    change Ideal.span {f.appTop (r * s)} =
      (inverseImageGlobalEquation f r hr).idealSheaf.ideal
          ⟨⊤, isAffineOpen_top X⟩ *
        (inverseImageGlobalEquation f s hs).idealSheaf.ideal
          ⟨⊤, isAffineOpen_top X⟩
  rw [inverseImageGlobalEquation_ideal_top, inverseImageGlobalEquation_ideal_top]
  rw [Ideal.span_singleton_mul_span_singleton]
  congr 2
  exact map_mul f.appTop.hom r s

/-- The `n`-fold multiple of an effective Cartier divisor. -/
def multiple (D : EffectiveCartierDivisor X) (n : ℕ) : EffectiveCartierDivisor X where
  idealSheaf := D.idealSheaf ^ n
  isEffectiveCartier :=
    pow_isEffectiveCartierIdealSheaf D.idealSheaf D.isEffectiveCartier n

@[simp]
theorem multiple_idealSheaf (D : EffectiveCartierDivisor X) (n : ℕ) :
    (D.multiple n).idealSheaf = D.idealSheaf ^ n := rfl

/-- A positive multiple has the same closed support as its underlying divisor. -/
theorem multiple_support (D : EffectiveCartierDivisor X) (n : ℕ) (hn : n ≠ 0) :
    (D.multiple n).support = D.support := by
  exact Scheme.IdealSheafData.support_pow D.idealSheaf n hn

@[simp]
theorem multiple_zero (D : EffectiveCartierDivisor X) : D.multiple 0 = empty X := by
  apply ext
  simp [multiple, empty]

@[simp]
theorem multiple_one (D : EffectiveCartierDivisor X) : D.multiple 1 = D := by
  apply ext
  simp [multiple]

theorem multiple_succ (D : EffectiveCartierDivisor X) (n : ℕ) :
    D.multiple (n + 1) = (D.multiple n).sum D := by
  apply ext
  simp [multiple, sum, pow_succ]

theorem multiple_add (D : EffectiveCartierDivisor X) (m n : ℕ) :
    D.multiple (m + n) = (D.multiple m).sum (D.multiple n) := by
  apply ext
  simp [multiple, sum, pow_add]

/-- Pullback along an open immersion preserves multiples of effective Cartier divisors. -/
theorem pullbackOpen_multiple {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [IsOpenImmersion f] (n : ℕ) :
    (D.multiple n).pullbackOpen f = (D.pullbackOpen f).multiple n := by
  apply ext
  exact idealSheaf_comap_pow_of_isOpenImmersion D.idealSheaf f n

/-- Flat pullback preserves every multiple of an effective Cartier divisor. -/
theorem pullbackFlat_multiple {Y : Scheme.{u}} (D : EffectiveCartierDivisor Y)
    (f : X ⟶ Y) [Flat f] (n : ℕ) :
    (D.multiple n).pullbackFlat f = (D.pullbackFlat f).multiple n := by
  apply ext
  exact idealSheaf_comap_pow D.idealSheaf f n

/-- Flat inverse image of a globally principal affine divisor preserves its multiples. -/
theorem inverseImageGlobalEquation_pow {Y : Scheme.{u}} [IsAffine X] [IsAffine Y]
    (f : X ⟶ Y) [Flat f] (r : Γ(Y, ⊤)) (hr : IsRegular r) (n : ℕ) :
    inverseImageGlobalEquation f (r ^ n) (hr.pow n) =
      (inverseImageGlobalEquation f r hr).multiple n := by
  apply ext
  apply Scheme.IdealSheafData.ext_of_isAffine
  set_option backward.isDefEq.respectTransparency false in
    simp only [multiple, inverseImageGlobalEquation_ideal_top,
      Scheme.IdealSheafData.ideal_pow]
  set_option backward.isDefEq.respectTransparency false in
    change Ideal.span {f.appTop (r ^ n)} =
      ((inverseImageGlobalEquation f r hr).idealSheaf.ideal
        ⟨⊤, isAffineOpen_top X⟩) ^ n
  rw [inverseImageGlobalEquation_ideal_top]
  rw [Ideal.span_singleton_pow]
  congr 2
  exact map_pow f.appTop.hom r n

/-- Effective Cartier divisors form an additive commutative monoid: zero is the empty divisor and
addition multiplies ideal sheaves. -/
instance addCommMonoid : AddCommMonoid (EffectiveCartierDivisor X) := by
  letI : Add (EffectiveCartierDivisor X) := ⟨sum⟩
  letI : Zero (EffectiveCartierDivisor X) := ⟨empty X⟩
  exact
    { add := sum
      add_assoc := sum_assoc
      zero := empty X
      zero_add := empty_sum
      add_zero := sum_empty
      add_comm := sum_comm
      nsmul := nsmulRec }

/-- Additive scalar multiplication is the previously constructed ideal-sheaf power. -/
theorem nsmul_eq_multiple (n : ℕ) (D : EffectiveCartierDivisor X) :
    n • D = D.multiple n := by
  induction n with
  | zero =>
      change empty X = D.multiple 0
      exact (multiple_zero D).symm
  | succ n ih =>
      rw [succ_nsmul, ih, multiple_succ]
      rfl

/-- Restriction along an open immersion as an additive homomorphism of effective Cartier
divisors. -/
def pullbackOpenHom {Y : Scheme.{u}} (f : X ⟶ Y) [IsOpenImmersion f] :
    EffectiveCartierDivisor Y →+ EffectiveCartierDivisor X where
  toFun := fun D ↦ D.pullbackOpen f
  map_zero' := pullbackOpen_empty f
  map_add' := fun D E ↦ pullbackOpen_sum D E f

/-- Flat pullback as an additive homomorphism of effective Cartier divisors. -/
def pullbackFlatHom {Y : Scheme.{u}} (f : X ⟶ Y) [Flat f] :
    EffectiveCartierDivisor Y →+ EffectiveCartierDivisor X where
  toFun := fun D ↦ D.pullbackFlat f
  map_zero' := pullbackFlat_empty f
  map_add' := fun D E ↦ pullbackFlat_sum D E f

end EffectiveCartierDivisor

end

end GromovWitten.AlgebraicGeometry.Curves
