/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Curves.SmoothPureDimensionNoetherian

/-!
# The fibre local ring is the local ring of the scheme-theoretic fibre

`GromovWitten/AlgebraicGeometry/Curves/SmoothPureDimensionNoetherian.lean` proves the dimension
formula for a flat morphism `q : W ⟶ U` of locally Noetherian schemes in terms of
`fibreCodim q x`, the Krull dimension of the *algebraically defined* fibre local ring
`fibreStalk q x = O_{W, x} ⧸ 𝔪_{q x} · O_{W, x}`.  This file identifies that number with a
*geometric* one: the coheight of `x`, viewed as a point of the scheme-theoretic fibre
`q.fiber (q x)`.

Mathlib computes no stalks of pullbacks, so the identification is not obtained by comparing
`fibreStalk q x` with `(q.fiber (q x)).presheaf.stalk (q.asFiber x)` directly.  Instead we build
the canonical morphism
`fibreStalkToFiber q x : Spec (fibreStalk q x) ⟶ q.fiber (q x)`
out of the universal property of the pullback, observe that it is a preimmersion whose image is
exactly the set of points of the fibre specializing to `q.asFiber x`, and conclude with
`Order.coheight_eq_of_strictMono`.  The point is that the coheight of a point only sees the
generizations of that point, and those are all visible in `Spec` of the local ring.

## Main results

* `fibreCodim_eq_coheight_asFiber`: `fibreCodim q x = Order.coheight (q.asFiber x)`, with no
  hypothesis on `q` whatsoever, and `ringKrullDim_stalk_fiber`, the same statement read as an
  equality of Krull dimensions of the two candidate "local rings of the fibre".
* `coheight_eq_coheight_apply_add_coheight_asFiber`: Stacks 00ON in purely geometric form.
* `fibreCodim_le_of_topologicalKrullDim_fiber_le`, `fibreCodim_fiberι`, `exists_le_coheight`: the
  two hypotheses of `topologicalKrullDim_eq_add_of_fibreCodim` in terms of the fibre dimensions.
* `topologicalKrullDim_eq_add_of_pureRelativeDimension`: for `q` flat, surjective, of pure
  relative dimension `r` between locally Noetherian schemes with `U` non-empty and pure of
  dimension `a`, `topologicalKrullDim W = a + r`.
* `totalDimensionFormulaAt_of_isLocallyNoetherian`, `AtlasLocallyNoetherian`,
  `overlapTotalDimensionFormula_of_atlasLocallyNoetherian`,
  `stackDimensionIndependent_of_atlasLocallyNoetherian`,
  `AlgebraicStack.dim_eq_of_atlasLocallyNoetherian`: the stack-level consequences, removing the
  hypothesis "locally of finite type over a field" from
  `stackDimensionIndependent_of_atlasLocallyOfFiniteTypeOver`.
-/

universe u

open CategoryTheory Limits Topology TopologicalSpace
open _root_.AlgebraicGeometry

namespace GromovWitten.AlgebraicGeometry.Curves

noncomputable section

section Bridge

variable {W U : Scheme.{u}}

/-- The ideal of `O_{W, x}` generated by the image of the maximal ideal of `O_{U, q x}`: the
fibre local ring `fibreStalk q x` is the quotient of `O_{W, x}` by it. -/
abbrev fibreIdeal (q : W ⟶ U) (x : W) : Ideal (W.presheaf.stalk x) :=
  (IsLocalRing.maximalIdeal (U.presheaf.stalk (q x))).map (q.stalkMap x).hom

/-- The fibre local ring `fibreStalk q x`, packaged as an object of `CommRingCat`. -/
abbrev fibreStalkCat (q : W ⟶ U) (x : W) : CommRingCat.{u} :=
  CommRingCat.of (fibreStalk q x)

/-- The quotient map from the local ring of `W` at `x` onto the fibre local ring. -/
def fibreStalkMk (q : W ⟶ U) (x : W) : W.presheaf.stalk x ⟶ fibreStalkCat q x :=
  CommRingCat.ofHom (Ideal.Quotient.mk (fibreIdeal q x))

/-- The quotient map onto the fibre local ring is surjective. -/
theorem fibreStalkMk_surjective (q : W ⟶ U) (x : W) :
    Function.Surjective (fibreStalkMk q x) :=
  Ideal.Quotient.mk_surjective

/-- The fibre local ring is an algebra over the residue field of `U` at `q x`: the stalk map
kills the maximal ideal of `O_{U, q x}` after passing to the quotient. -/
def fibreStalkResidue (q : W ⟶ U) (x : W) : U.residueField (q x) ⟶ fibreStalkCat q x :=
  CommRingCat.ofHom
    (Ideal.Quotient.lift (IsLocalRing.maximalIdeal (U.presheaf.stalk (q x)))
      ((Ideal.Quotient.mk (fibreIdeal q x)).comp (q.stalkMap x).hom)
      (fun _ ha => Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_map_of_mem _ ha)))

/-- Reducing the stalk map modulo the fibre ideal factors through the residue field. -/
theorem residue_comp_fibreStalkResidue (q : W ⟶ U) (x : W) :
    q.stalkMap x ≫ fibreStalkMk q x = U.residue (q x) ≫ fibreStalkResidue q x := rfl

/-- The canonical morphism `Spec (fibreStalk q x) ⟶ W`: the closed subscheme of
`Spec O_{W, x}` cut out by the fibre ideal, mapped into `W`. -/
def fibreStalkToSource (q : W ⟶ U) (x : W) : Spec (fibreStalkCat q x) ⟶ W :=
  Spec.map (fibreStalkMk q x) ≫ W.fromSpecStalk x

/-- The canonical morphism `Spec (fibreStalk q x) ⟶ Spec κ(q x)`. -/
def fibreStalkToResidue (q : W ⟶ U) (x : W) :
    Spec (fibreStalkCat q x) ⟶ Spec (U.residueField (q x)) :=
  Spec.map (fibreStalkResidue q x)

/-- `Spec (fibreStalk q x)` sits in the defining square of the scheme-theoretic fibre. -/
theorem fibreStalk_comm (q : W ⟶ U) (x : W) :
    fibreStalkToSource q x ≫ q
      = fibreStalkToResidue q x ≫ U.fromSpecResidueField (q x) := by
  rw [fibreStalkToSource, fibreStalkToResidue, Scheme.fromSpecResidueField, Category.assoc,
    ← Scheme.SpecMap_stalkMap_fromSpecStalk, ← Spec.map_comp_assoc, ← Spec.map_comp_assoc,
    residue_comp_fibreStalkResidue]

/-- The canonical morphism from `Spec` of the fibre local ring to the scheme-theoretic fibre. -/
def fibreStalkToFiber (q : W ⟶ U) (x : W) : Spec (fibreStalkCat q x) ⟶ q.fiber (q x) :=
  pullback.lift (fibreStalkToSource q x) (fibreStalkToResidue q x) (fibreStalk_comm q x)

/-- `fibreStalkToFiber` is compatible with the embedding of the fibre into the source. -/
@[reassoc]
theorem fibreStalkToFiber_fiberι (q : W ⟶ U) (x : W) :
    fibreStalkToFiber q x ≫ q.fiberι (q x) = fibreStalkToSource q x :=
  pullback.lift_fst _ _ _

/-- The fibre local ring is a local ring. -/
instance isLocalRing_fibreStalk (q : W ⟶ U) (x : W) : IsLocalRing (fibreStalk q x) :=
  have : Nontrivial (fibreStalk q x) :=
    Ideal.Quotient.nontrivial_iff.mpr (map_maximalIdeal_stalkMap_ne_top q x)
  IsLocalRing.of_surjective' (Ideal.Quotient.mk (fibreIdeal q x)) Ideal.Quotient.mk_surjective

/-- The quotient map onto the fibre local ring is a local ring homomorphism. -/
instance isLocalHom_fibreStalkMk (q : W ⟶ U) (x : W) :
    IsLocalHom (Ideal.Quotient.mk (fibreIdeal q x)) :=
  IsLocalHom.of_surjective _ Ideal.Quotient.mk_surjective

/-- The closed point of `Spec` of the fibre local ring. -/
def fibreStalkClosedPoint (q : W ⟶ U) (x : W) : Spec (fibreStalkCat q x) :=
  IsLocalRing.closedPoint (fibreStalk q x)

/-- `Spec` of the quotient map sends the closed point of `Spec (fibreStalk q x)` to the closed
point of `Spec O_{W, x}`. -/
theorem specMap_fibreStalkMk_closedPoint (q : W ⟶ U) (x : W) :
    Spec.map (fibreStalkMk q x) (fibreStalkClosedPoint q x)
      = IsLocalRing.closedPoint (W.presheaf.stalk x) :=
  (IsLocalRing.isLocalHom_iff_comap_closedPoint
    (Ideal.Quotient.mk (fibreIdeal q x))).mp inferInstance

/-- `Spec` of the fibre local ring is a preimmersion into `W`. -/
instance isPreimmersion_fibreStalkToSource (q : W ⟶ U) (x : W) :
    IsPreimmersion (fibreStalkToSource q x) := by
  have : IsClosedImmersion (Spec.map (fibreStalkMk q x)) :=
    IsClosedImmersion.spec_of_surjective _ (fibreStalkMk_surjective q x)
  rw [fibreStalkToSource]
  infer_instance

/-- `Spec` of the fibre local ring is a preimmersion into the scheme-theoretic fibre. -/
instance isPreimmersion_fibreStalkToFiber (q : W ⟶ U) (x : W) :
    IsPreimmersion (fibreStalkToFiber q x) := by
  have : IsPreimmersion (fibreStalkToFiber q x ≫ q.fiberι (q x)) := by
    rw [fibreStalkToFiber_fiberι]
    infer_instance
  exact IsPreimmersion.of_comp _ (q.fiberι (q x))

/-- The closed point of `Spec` of the fibre local ring is sent to `x`. -/
theorem fibreStalkToSource_closedPoint (q : W ⟶ U) (x : W) :
    fibreStalkToSource q x (fibreStalkClosedPoint q x) = x := by
  rw [fibreStalkToSource, Scheme.Hom.comp_apply, specMap_fibreStalkMk_closedPoint,
    Scheme.fromSpecStalk_closedPoint]

/-- Every point in the image of `Spec` of the fibre local ring specializes to `x`. -/
theorem fibreStalkToSource_specializes (q : W ⟶ U) (x : W)
    (P : Spec (fibreStalkCat q x)) : fibreStalkToSource q x P ⤳ x := by
  have h : fibreStalkToSource q x P ∈ Set.range (W.fromSpecStalk x) :=
    ⟨Spec.map (fibreStalkMk q x) P, (Scheme.Hom.comp_apply _ _ _).symm⟩
  rwa [Scheme.range_fromSpecStalk] at h

/-- Every prime containing an ideal `I` is the contraction of a prime of `R ⧸ I`. -/
theorem exists_comap_quotientMk_eq {R : Type*} [CommRing R] (I : Ideal R)
    (Q : PrimeSpectrum R) (hQ : I ≤ Q.asIdeal) :
    ∃ P : PrimeSpectrum (R ⧸ I), PrimeSpectrum.comap (Ideal.Quotient.mk I) P = Q := by
  rw [← Set.mem_range, range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective,
    PrimeSpectrum.mem_zeroLocus, Ideal.mk_ker]
  exact hQ

/-- Primes of `O_{W, x}` containing the fibre ideal come from primes of the fibre local ring. -/
theorem exists_specMap_fibreStalkMk_eq (q : W ⟶ U) (x : W)
    (Q : Spec (W.presheaf.stalk x)) (hQ : fibreIdeal q x ≤ Q.asIdeal) :
    ∃ P : Spec (fibreStalkCat q x), Spec.map (fibreStalkMk q x) P = Q := by
  obtain ⟨P, hP⟩ := exists_comap_quotientMk_eq (fibreIdeal q x) Q hQ
  exact ⟨P, hP⟩

/-- Every point of `W` which specializes to `x` and lies in the same fibre as `x` lies in the
image of `Spec` of the fibre local ring. -/
theorem exists_fibreStalkToSource_eq (q : W ⟶ U) (x : W) {w : W} (hw : w ⤳ x)
    (hqw : q w = q x) :
    ∃ P : Spec (fibreStalkCat q x), fibreStalkToSource q x P = w := by
  obtain ⟨Q, hQ⟩ : w ∈ Set.range (W.fromSpecStalk x) := by
    rw [Scheme.range_fromSpecStalk]; exact hw
  have hclosed : Spec.map (q.stalkMap x) Q
      = IsLocalRing.closedPoint (U.presheaf.stalk (q x)) := by
    refine (U.fromSpecStalk (q x)).isEmbedding.injective ?_
    rw [Scheme.fromSpecStalk_closedPoint, ← Scheme.Hom.comp_apply,
      Scheme.SpecMap_stalkMap_fromSpecStalk, Scheme.Hom.comp_apply, hQ, hqw]
  have hle : fibreIdeal q x ≤ Q.asIdeal := by
    rw [Ideal.map_le_iff_le_comap]
    exact le_of_eq (congrArg PrimeSpectrum.asIdeal hclosed).symm
  obtain ⟨P, hP⟩ := exists_specMap_fibreStalkMk_eq q x Q hle
  exact ⟨P, by rw [fibreStalkToSource, Scheme.Hom.comp_apply, hP, hQ]⟩

/-- A preimmersion of schemes reflects and preserves the specialization preorder. -/
theorem le_iff_le_of_isPreimmersion {A B : Scheme.{u}} (f : A ⟶ B) [IsPreimmersion f]
    (a b : A) : f a ≤ f b ↔ a ≤ b := by
  change f b ⤳ f a ↔ b ⤳ a
  exact f.isEmbedding.isInducing.specializes_iff

/-- A preimmersion of schemes is strictly monotone for the specialization preorders. -/
theorem strictMono_of_isPreimmersion {A B : Scheme.{u}} (f : A ⟶ B) [IsPreimmersion f] :
    StrictMono (fun a : A => f a) :=
  strictMono_of_le_iff_le (fun a b => (le_iff_le_of_isPreimmersion f a b).symm)

/-- A preimmersion of schemes reflects and preserves strict specialization. -/
theorem lt_iff_lt_of_isPreimmersion {A B : Scheme.{u}} (f : A ⟶ B) [IsPreimmersion f]
    (a b : A) : f a < f b ↔ a < b :=
  lt_iff_lt_of_le_iff_le' (le_iff_le_of_isPreimmersion f b a)
    (le_iff_le_of_isPreimmersion f a b)

/-- The closed point of `Spec` of the fibre local ring is the point `x` of the fibre. -/
theorem fibreStalkToFiber_closedPoint (q : W ⟶ U) (x : W) :
    fibreStalkToFiber q x (fibreStalkClosedPoint q x) = q.asFiber x := by
  refine (q.fiberι (q x)).isEmbedding.injective ?_
  rw [← Scheme.Hom.comp_apply, fibreStalkToFiber_fiberι, fibreStalkToSource_closedPoint,
    Scheme.Hom.fiberι_asFiber]

/-- Points of the fibre through `x` are mapped into the fibre of `q` through `x`. -/
theorem apply_fiberι (q : W ⟶ U) (u : U) (z : q.fiber u) : q (q.fiberι u z) = u := by
  rw [← Scheme.Hom.comp_apply, q.fiber_fac, Scheme.Hom.comp_apply,
    Scheme.fromSpecResidueField_apply]

/-- **Every generization inside the fibre of a point of the image of `Spec` of the fibre local
ring is again in that image.**  This is the lifting condition of
`Order.coheight_eq_of_strictMono`. -/
theorem exists_lt_fibreStalkToFiber_eq (q : W ⟶ U) (x : W) (P : Spec (fibreStalkCat q x))
    (z : q.fiber (q x)) (h : fibreStalkToFiber q x P < z) :
    ∃ P' : Spec (fibreStalkCat q x), P < P' ∧ fibreStalkToFiber q x P' = z := by
  have hz : z ⤳ fibreStalkToFiber q x P := h.le
  have hwz : q.fiberι (q x) z ⤳ fibreStalkToSource q x P := by
    have := hz.map (q.fiberι (q x)).continuous
    rwa [← Scheme.Hom.comp_apply, fibreStalkToFiber_fiberι] at this
  obtain ⟨P', hP'⟩ := exists_fibreStalkToSource_eq q x
    (hwz.trans (fibreStalkToSource_specializes q x P)) (apply_fiberι q (q x) z)
  have hzP' : fibreStalkToFiber q x P' = z := by
    refine (q.fiberι (q x)).isEmbedding.injective ?_
    rw [← Scheme.Hom.comp_apply, fibreStalkToFiber_fiberι, hP']
  exact ⟨P', (lt_iff_lt_of_isPreimmersion (fibreStalkToFiber q x) P P').mp (hzP' ▸ h), hzP'⟩

/-- `fibreCodim q x` is the coheight of the closed point of `Spec` of the fibre local ring. -/
theorem fibreCodim_eq_coheight_closedPoint (q : W ⟶ U) (x : W) :
    fibreCodim q x = Order.coheight (fibreStalkClosedPoint q x) := by
  have hmax : (IsLocalRing.maximalIdeal (W.presheaf.stalk x)).map
      (Ideal.Quotient.mk (fibreIdeal q x)) = IsLocalRing.maximalIdeal (fibreStalk q x) :=
    IsLocalRing.map_maximalIdeal_of_surjective _ Ideal.Quotient.mk_surjective
  have h1 : fibreCodim q x = (IsLocalRing.maximalIdeal (fibreStalk q x)).height := by
    rw [← hmax]
    rfl
  rw [h1]
  exact idealHeight_eq_coheight (fibreStalkCat q x) (fibreStalkClosedPoint q x)

/-- **The fibre codimension is the coheight in the scheme-theoretic fibre.**  For any morphism of
schemes `q : W ⟶ U` and any `x : W`, the Krull dimension of the fibre local ring
`fibreStalk q x = O_{W, x} ⧸ 𝔪_{q x} · O_{W, x}` equals the coheight of `x` viewed as a point of
the scheme-theoretic fibre `q.fiber (q x)`; equivalently it is the dimension of the local ring of
that fibre at `x`.  No flatness, finiteness or Noetherian hypothesis is needed. -/
theorem fibreCodim_eq_coheight_asFiber (q : W ⟶ U) (x : W) :
    fibreCodim q x = Order.coheight (q.asFiber x) := by
  rw [fibreCodim_eq_coheight_closedPoint, ← fibreStalkToFiber_closedPoint q x]
  exact Order.coheight_eq_of_strictMono _ (strictMono_of_isPreimmersion (fibreStalkToFiber q x))
    (fun P z hlt => exists_lt_fibreStalkToFiber_eq q x P z hlt) _

/-- **The local ring of the scheme-theoretic fibre has the same Krull dimension as the fibre
local ring `O_{W, x} ⧸ 𝔪_{q x} · O_{W, x}`.**  This is the "stalk of a pullback" comparison in the
only form dimension theory needs; Mathlib provides no isomorphism of the two rings. -/
theorem ringKrullDim_stalk_fiber (q : W ⟶ U) (x : W) :
    ringKrullDim ((q.fiber (q x)).presheaf.stalk (q.asFiber x))
      = ringKrullDim (fibreStalk q x) := by
  rw [ringKrullDim_stalk_eq_coheight, ← fibreCodim_eq_coheight_asFiber]
  exact fibreCodim_eq_ringKrullDim_fibreStalk q x

end Bridge

/-! ### The dimension formula from the pure relative dimension -/

section Formula

variable {W U : Scheme.{u}}

/-- In a scheme whose total dimension is at least `r`, some point has coheight at least `r`. -/
theorem exists_le_coheight (X : Scheme.{u}) {r : ℕ}
    (h : (r : WithBot ℕ∞) ≤ topologicalKrullDim X) :
    ∃ z : X, (r : ℕ∞) ≤ Order.coheight z := by
  rw [topologicalKrullDim_eq_krullDim, Order.le_krullDim_iff] at h
  obtain ⟨l, hl⟩ := h
  exact ⟨l.head, hl ▸ Order.length_le_coheight_head⟩

/-- Coheight in a scheme-theoretic fibre does not depend on the name of the base point. -/
theorem coheight_fiber_congr (q : W ⟶ U) {u u' : U} (h : u = u')
    (z : q.fiber u) (z' : q.fiber u') (hz : q.fiberι u z = q.fiberι u' z') :
    Order.coheight z = Order.coheight z' := by
  subst h
  rw [(q.fiberι u).isEmbedding.injective hz]

/-- The fibre codimension at a point of the fibre over `u` is its coheight in that fibre. -/
theorem fibreCodim_fiberι (q : W ⟶ U) (u : U) (z : q.fiber u) :
    fibreCodim q (q.fiberι u z) = Order.coheight z := by
  rw [fibreCodim_eq_coheight_asFiber]
  exact coheight_fiber_congr q (apply_fiberι q u z) _ z (Scheme.Hom.fiberι_asFiber q _)

/-- The fibre codimension at `x` is bounded by the dimension of the fibre through `x`. -/
theorem fibreCodim_le_of_topologicalKrullDim_fiber_le (q : W ⟶ U) (x : W) {r : ℕ}
    (h : topologicalKrullDim (q.fiber (q x)) ≤ (r : WithBot ℕ∞)) :
    fibreCodim q x ≤ (r : ℕ∞) := by
  have h1 : ((fibreCodim q x : ℕ∞) : WithBot ℕ∞) ≤ (r : WithBot ℕ∞) := by
    rw [fibreCodim_eq_coheight_asFiber]
    refine le_trans (Order.coheight_le_krullDim _) ?_
    rwa [← topologicalKrullDim_eq_krullDim]
  exact_mod_cast h1

/-- **The local dimension formula for a flat morphism, in geometric form** (Stacks 00ON).  For a
flat morphism `q : W ⟶ U` of locally Noetherian schemes, the dimension of the local ring of `W` at
`x` is the dimension of the local ring of `U` at `q x` plus the codimension of `x` inside the
scheme-theoretic fibre `q.fiber (q x)`. -/
theorem coheight_eq_coheight_apply_add_coheight_asFiber (q : W ⟶ U) [Flat q]
    [IsLocallyNoetherian W] [IsLocallyNoetherian U] (x : W) :
    Order.coheight x = Order.coheight (q x) + Order.coheight (q.asFiber x) := by
  rw [coheight_eq_coheight_apply_add_fibreCodim q x, fibreCodim_eq_coheight_asFiber]

/-- A non-empty fibre of a morphism of pure relative dimension `r` has total dimension `r`. -/
theorem topologicalKrullDim_fiber_of_pureRelativeDimension (q : W ⟶ U) {r : ℕ}
    (hq : SchemeMorphismPureRelativeDimension q r) (u : U) (z : q.fiber u) :
    topologicalKrullDim (q.fiber u) = (r : WithBot ℕ∞) :=
  topologicalKrullDim_eq_of_pure ⟨z⟩ (hq.2 u)

/-- **The dimension formula over a locally Noetherian base.**  Let `q : W ⟶ U` be a flat,
surjective morphism of locally Noetherian schemes of pure relative dimension `r` (in particular
locally of finite type), and let `U` be non-empty and pure of dimension `a`.  Then
`topologicalKrullDim W = a + r`.  Only the *total* dimension of `W` is asserted: the
pure-dimension statement is false in this generality, see the module docstring of
`Curves/SmoothPureDimensionNoetherian.lean`. -/
theorem topologicalKrullDim_eq_add_of_pureRelativeDimension (q : W ⟶ U) [Flat q]
    [IsLocallyNoetherian W] [IsLocallyNoetherian U] {a r : ℕ}
    (hsurj : _root_.AlgebraicGeometry.Surjective q)
    (hq : SchemeMorphismPureRelativeDimension q r) (hne : Nonempty U)
    (hU : SchemePureDimension U a) :
    topologicalKrullDim W = ((a + r : ℕ) : WithBot ℕ∞) := by
  refine topologicalKrullDim_eq_of_schemePureDimension q hne hU (fun x => ?_) (fun u => ?_)
  · exact fibreCodim_le_of_topologicalKrullDim_fiber_le q x
      (le_of_eq (topologicalKrullDim_fiber_of_pureRelativeDimension q hq _ (q.asFiber x)))
  · obtain ⟨x₀, hx₀⟩ := hsurj.surj u
    have hfib : topologicalKrullDim (q.fiber (q x₀)) = (r : WithBot ℕ∞) :=
      topologicalKrullDim_fiber_of_pureRelativeDimension q hq _ (q.asFiber x₀)
    obtain ⟨z, hz⟩ := exists_le_coheight (q.fiber (q x₀)) (le_of_eq hfib.symm)
    refine ⟨q.fiberι (q x₀) z, ?_, ?_⟩
    · rw [apply_fiberι q (q x₀) z, hx₀]
    · rw [fibreCodim_fiberι]
      exact hz

/-- **Upper bound for the dimension of the source of a flat morphism with fibres of bounded
dimension**, over a locally Noetherian base.  `RelativeDimensionLE r q` already contains
`LocallyOfFiniteType q`, so `W` is automatically locally Noetherian. -/
theorem topologicalKrullDim_le_add_of_relativeDimensionLE (q : W ⟶ U) [Flat q]
    [IsLocallyNoetherian U] {r : ℕ} (hq : RelativeDimensionLE r q) :
    topologicalKrullDim W ≤ topologicalKrullDim U + (r : WithBot ℕ∞) := by
  have hft : _root_.AlgebraicGeometry.LocallyOfFiniteType q := hq.1
  have hW : IsLocallyNoetherian W := LocallyOfFiniteType.isLocallyNoetherian q
  exact topologicalKrullDim_le_add_of_fibreCodim_le q
    (fun x => fibreCodim_le_of_topologicalKrullDim_fiber_le q x (hq.2 (q x)))

/-- **Lower bound for the dimension of the source of a flat surjection whose fibres have
dimension at least `r`**, over a locally Noetherian base. -/
theorem add_le_topologicalKrullDim_of_le_topologicalKrullDim_fiber (q : W ⟶ U) [Flat q]
    [IsLocallyNoetherian W] [IsLocallyNoetherian U] {r : ℕ}
    (hsurj : _root_.AlgebraicGeometry.Surjective q)
    (h : ∀ u : U, (r : WithBot ℕ∞) ≤ topologicalKrullDim (q.fiber u)) :
    topologicalKrullDim U + (r : WithBot ℕ∞) ≤ topologicalKrullDim W := by
  refine add_le_topologicalKrullDim_of_le_fibreCodim q (fun u => ?_)
  obtain ⟨x₀, hx₀⟩ := hsurj.surj u
  have h' := h u
  rw [← hx₀] at h'
  obtain ⟨z, hz⟩ := exists_le_coheight (q.fiber (q x₀)) h'
  refine ⟨q.fiberι (q x₀) z, by rw [apply_fiberι q (q x₀) z, hx₀], ?_⟩
  rw [fibreCodim_fiberι]
  exact hz

/-- The dimension formula phrased with the repository's `PureRelativeDimension` and
`PureTopologicalDimension` (the predicates used by the field case in
`Curves/SmoothPureDimension.lean`). -/
theorem topologicalKrullDim_eq_add_of_pureRelativeDimension' (q : W ⟶ U) [Flat q]
    [IsLocallyNoetherian W] [IsLocallyNoetherian U] {a r : ℕ}
    (hsurj : _root_.AlgebraicGeometry.Surjective q) (hq : PureRelativeDimension r q)
    (hne : Nonempty U) (hU : PureTopologicalDimension a U) :
    topologicalKrullDim W = ((a + r : ℕ) : WithBot ℕ∞) :=
  topologicalKrullDim_eq_add_of_pureRelativeDimension q hsurj hq hne hU

/-- The total-dimension formula of `Curves/SmoothPureDimensionNoetherian.lean` holds for every
morphism of schemes whose target is non-empty and locally Noetherian.  No finiteness hypothesis
over a field is needed: the source is automatically locally Noetherian because a morphism of pure
relative dimension is locally of finite type. -/
theorem totalDimensionFormulaAt_of_isLocallyNoetherian (q : W ⟶ U) [IsLocallyNoetherian U]
    (hne : Nonempty U) : TotalDimensionFormulaAt q := by
  intro r a hsm hsurj hq hU
  have hsmooth : _root_.AlgebraicGeometry.Smooth q := hsm
  have hft : _root_.AlgebraicGeometry.LocallyOfFiniteType q := hq.1
  have hW : IsLocallyNoetherian W := LocallyOfFiniteType.isLocallyNoetherian q
  exact topologicalKrullDim_eq_add_of_pureRelativeDimension q hsurj hq hne hU

end Formula

/-! ### Atlas independence of the dimension of a stack with locally Noetherian atlases -/

section Stack

/-- An algebraic stack has locally Noetherian atlases when the scheme of every atlas dimension
presentation is locally Noetherian.  This is much weaker than being locally of finite type over
a field. -/
def AtlasLocallyNoetherian (X : AlgebraicStack.{u}) : Prop :=
  ∀ A : StackDimensionPresentation X, IsLocallyNoetherian A.atlas.scheme

/-- For a stack with non-empty locally Noetherian atlases, the total-dimension formula holds for
both projections of the overlap of any two atlas dimension presentations. -/
theorem overlapTotalDimensionFormula_of_atlasLocallyNoetherian {X : AlgebraicStack.{u}}
    (hX : AtlasLocallyNoetherian X)
    (hne : ∀ A : StackDimensionPresentation X, Nonempty A.atlas.scheme) :
    OverlapTotalDimensionFormula X := by
  intro A B
  have hA : IsLocallyNoetherian A.atlas.scheme := hX A
  have hB : IsLocallyNoetherian B.atlas.scheme := hX B
  exact ⟨totalDimensionFormulaAt_of_isLocallyNoetherian (A.overlap B).fst (hne B),
    totalDimensionFormulaAt_of_isLocallyNoetherian (A.overlap B).snd (hne A)⟩

/-- **Atlas independence of the dimension of an algebraic stack over a general base.**  If the
scheme of every atlas dimension presentation of `X` is non-empty and locally Noetherian, then all
atlas dimension presentations give the same corrected dimension.  This removes the hypothesis
"locally of finite type over a field" of
`stackDimensionIndependent_of_atlasLocallyOfFiniteTypeOver`. -/
theorem stackDimensionIndependent_of_atlasLocallyNoetherian {X : AlgebraicStack.{u}}
    (hX : AtlasLocallyNoetherian X)
    (hne : ∀ A : StackDimensionPresentation X, Nonempty A.atlas.scheme) :
    StackDimensionIndependent X :=
  stackDimensionIndependent_of_overlapTotalDimensionFormula
    (overlapTotalDimensionFormula_of_atlasLocallyNoetherian hX hne)

/-- The dimension of a stack with non-empty locally Noetherian atlases is computed by any single
atlas dimension presentation. -/
theorem AlgebraicStack.dim_eq_of_atlasLocallyNoetherian {X : AlgebraicStack.{u}}
    (hX : AtlasLocallyNoetherian X)
    (hne : ∀ A : StackDimensionPresentation X, Nonempty A.atlas.scheme)
    (A : StackDimensionPresentation X) :
    X.dim = StackDim.ofInt A.correctedDimension :=
  AlgebraicStack.dim_eq_of_independent
    (stackDimensionIndependent_of_atlasLocallyNoetherian hX hne) A

end Stack

end

end GromovWitten.AlgebraicGeometry.Curves
