/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/
import Mathlib.RingTheory.FinitePresentation

/-!
# Finite presentation of algebra retracts

For a retraction `p : A →ₐ[R] B` with section `i`, the kernel of `p` is generated by
`a - i (p a)` as `a` ranges over any algebra generating set of `A`.  This proves finite
presentation of `B` from finite presentation of `A`, without a Noetherian hypothesis.
-/

namespace GromovWitten.Algebra

variable {R A B : Type*} [CommRing R] [CommRing A] [CommRing B]
  [Algebra R A] [Algebra R B]

/-- The kernel of an algebra retraction is generated by the differences between algebra
generators and their images under the associated idempotent endomorphism. -/
theorem ker_retraction_eq_span (p : A →ₐ[R] B) (i : B →ₐ[R] A)
    (h : p.comp i = AlgHom.id R B) (s : Set A) (hs : Algebra.adjoin R s = ⊤) :
    RingHom.ker p.toRingHom = Ideal.span ((fun a ↦ a - i (p a)) '' s) := by
  let J := Ideal.span ((fun a ↦ a - i (p a)) '' s)
  have hp (b : B) : p (i b) = b := AlgHom.congr_fun h b
  have hle : J ≤ RingHom.ker p.toRingHom := by
    apply Ideal.span_le.mpr
    rintro _ ⟨a, _, rfl⟩
    change p (a - i (p a)) = 0
    rw [map_sub, hp, sub_self]
  have hq : Ideal.Quotient.mkₐ R J = (Ideal.Quotient.mkₐ R J).comp (i.comp p) := by
    apply AlgHom.ext_of_adjoin_eq_top hs
    intro a ha
    change Ideal.Quotient.mk J a = Ideal.Quotient.mk J (i (p a))
    exact Ideal.Quotient.eq.mpr (Ideal.subset_span ⟨a, ha, rfl⟩)
  apply le_antisymm _ hle
  intro a ha
  have hpa : p a = 0 := ha
  have hqa := AlgHom.congr_fun hq a
  have hz : Ideal.Quotient.mk J a = 0 := by
    simpa only [AlgHom.comp_apply, hpa, map_zero] using! hqa
  exact (Ideal.Quotient.eq_zero_iff_mem).mp hz

/-- An algebra retract of a finitely presented algebra is finitely presented. -/
theorem finitePresentation_of_retraction [Algebra.FinitePresentation R A]
    (p : A →ₐ[R] B) (i : B →ₐ[R] A) (h : p.comp i = AlgHom.id R B) :
    Algebra.FinitePresentation R B := by
  classical
  obtain ⟨s, hs⟩ := (inferInstance : Algebra.FiniteType R A).out
  have hker : (RingHom.ker p.toRingHom).FG := by
    rw [ker_retraction_eq_span p i h s hs]
    refine ⟨s.image (fun a ↦ a - i (p a)), ?_⟩
    simp only [Finset.coe_image]
  apply Algebra.FinitePresentation.of_surjective (f := p) _ hker
  intro b
  exact ⟨i b, AlgHom.congr_fun h b⟩

end GromovWitten.Algebra
