/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude Sonnet 5
-/

import GromovWitten.Algebra.OrderSemilocal

/-!
# The order along a finite birational extension (Fulton, Example A.3.1)

Let `A` be a Noetherian local domain of Krull dimension `≤ 1`, and `B` a domain, module-finite
over `A`, such that every element of `B` is, up to a nonzero scalar of `A`, in the image of `A`
(`hrank`; equivalently `B` has generic rank one over `A`, i.e. `FractionRing A ≃ FractionRing B`).
This file proves Fulton's Example A.3.1: for `a ≠ 0` in `A`,

`Ring.ord A a = ∑ᶠ q : MaximalSpectrum B, OrderSemilocal.summand (A := A) (B ⧸ Ideal.span
{algebraMap A B a}) q`

(`OrderBirational.ord_eq_finsum_summand`), and its readable form

`Ring.ord A a = ∑ᶠ q, [κ(q) : κ_A] · Ring.ord (Localization.AtPrime q.asIdeal) (algebraMap A _ a)`

(`OrderBirational.ord_eq_finsum`).

## Design note

`OrderSemilocal.length_eq_finsum` needs its module argument `N` to carry a *genuine* `B`-module
structure. The submodule `a • (⊤ : Submodule A B)` used in `OrderFiniteExtension`/`OrderSemilocal`
is only packaged as an `A`-submodule of `B`, even though (since it is literally the principal
ideal generated by `algebraMap A B a`) it is also `B`-stable; Lean does not synthesise a `Module B`
instance for its quotient automatically. We therefore work throughout with the *ideal*
`J a := Ideal.span {algebraMap A B a} : Ideal B`, whose quotient `B ⧸ J a` is tautologically a
`B`-module (and, via `IsScalarTower A B (B ⧸ J a)`, also carries a compatible `A`-module
structure). `OrderBirational.smul_top_eq_restrictScalars_span` records the (purely `A`-submodule
level) identification `a • ⊤ = (J a).restrictScalars A`, which transports the `OrderFiniteExtension`
free/torsion computations for `a • ⊤` onto `J a`.

## Main declarations

* `OrderBirational.length_quotient_span_eq_ord`: `Module.length A (B ⧸ Ideal.span
  {algebraMap A B a}) = Ring.ord A a`, Part (a) of Fulton A.3.1.
* `OrderBirational.summand_quotient_span_eq`: the identification of each summand of
  `OrderSemilocal.summand` for `N = B ⧸ Ideal.span {algebraMap A B a}` with `[κ(q):κ_A] ·
  Ring.ord (Localization.AtPrime q.asIdeal) (algebraMap A _ a)`.
* `OrderBirational.ord_eq_finsum_summand`, `OrderBirational.ord_eq_finsum`: the two forms of
  Fulton A.3.1 described above.
-/

open scoped Pointwise

namespace OrderBirational

section NoZeroSMulDivisors

variable {A B : Type*} [CommRing A] [CommRing B] [IsDomain B] [Algebra A B]

/-- If `algebraMap A B` is injective and `B` is a domain, then `B` is torsion-free as an
`A`-module: `A` acts on `B` through the injective ring homomorphism `algebraMap A B`, and a
product of nonzero elements in a domain is nonzero. -/
theorem noZeroSMulDivisors_of_injective (hinj : Function.Injective (algebraMap A B)) :
    NoZeroSMulDivisors A B where
  eq_zero_or_eq_zero_of_smul_eq_zero {c x} h := by
    rw [Algebra.smul_def] at h
    rcases mul_eq_zero.mp h with h1 | h1
    · exact Or.inl (hinj (by rw [h1, map_zero]))
    · exact Or.inr h1

end NoZeroSMulDivisors

section SmulTop

variable {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]

/-- The `A`-submodule `a • (⊤ : Submodule A B)` of multiples of `a` coincides, after restricting
scalars, with the principal ideal of `B` generated by `algebraMap A B a`. -/
theorem smul_top_eq_restrictScalars_span (a : A) :
    a • (⊤ : Submodule A B) =
      (Ideal.span {algebraMap A B a} : Ideal B).restrictScalars A := by
  rw [← Submodule.ideal_span_singleton_smul, Ideal.smul_top_eq_map, Ideal.map_span,
    Set.image_singleton]

end SmulTop

section FiniteLengthQuotientRange

variable {A B : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A] [Ring.KrullDimLE 1 A]
  [CommRing B] [Algebra A B] [Module.Finite A B]

instance moduleFinite_quotient_range_algebraMap :
    Module.Finite A (B ⧸ LinearMap.range (Algebra.linearMap A B)) :=
  Module.Finite.of_surjective (Submodule.mkQ _) (Submodule.Quotient.mk_surjective _)

/-- **The torsion input to Fulton A.3.1.** If every element of `B` is, up to a nonzero scalar of
`A`, in the image of `algebraMap A B` (`hrank`, "generic rank one"), then `A · 1 ⊆ B` (the range
of `Algebra.linearMap A B`) has finite-length cokernel: a single nonzero scalar `c` (the product
of the finitely many scalars witnessing `hrank` for a finite generating set of `B`) already sends
every generator, hence every element, of `B` into `A · 1`. -/
theorem isFiniteLength_quotient_range_algebraMap
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a) :
    IsFiniteLength A (B ⧸ LinearMap.range (Algebra.linearMap A B)) := by
  classical
  obtain ⟨s, hs⟩ := (Module.Finite.fg_top : (⊤ : Submodule A B).FG)
  choose sg ag hsg_ne hsg using fun g : s => hrank (g : B)
  set c : A := ∏ g : s, sg g with hcdef
  have hc_ne : c ≠ 0 := Finset.prod_ne_zero_iff.mpr fun g _ => hsg_ne g
  have hc_mem : ∀ g : s, c • (g : B) ∈ LinearMap.range (Algebra.linearMap A B) := by
    intro g
    have hfactor : c = (∏ h ∈ Finset.univ.erase g, sg h) * sg g := by
      rw [hcdef]
      exact (Finset.prod_erase_mul Finset.univ (fun h => sg h) (Finset.mem_univ g)).symm
    have hstep : c • (g : B) = (∏ h ∈ Finset.univ.erase g, sg h) • algebraMap A B (ag g) := by
      rw [hfactor, mul_smul, hsg g]
    rw [hstep, Algebra.smul_def]
    exact ⟨(∏ h ∈ Finset.univ.erase g, sg h) * ag g, map_mul (algebraMap A B) _ _⟩
  have hMc : ∀ x : B, c • x ∈ LinearMap.range (Algebra.linearMap A B) := by
    have hle : (⊤ : Submodule A B) ≤ Submodule.comap (LinearMap.lsmul A B c)
        (LinearMap.range (Algebra.linearMap A B)) := by
      rw [← hs]
      refine Submodule.span_le.mpr ?_
      rintro x hx
      exact hc_mem ⟨x, hx⟩
    intro x
    have := hle (Submodule.mem_top (x := x))
    simpa using this
  have hquot : ∀ y : B ⧸ LinearMap.range (Algebra.linearMap A B), c • y = 0 := by
    intro y
    obtain ⟨x, rfl⟩ :=
      Submodule.Quotient.mk_surjective (LinearMap.range (Algebra.linearMap A B)) y
    rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
    exact hMc x
  exact OrderFiniteExtension.isFiniteLength_of_smul_eq_zero hc_ne hquot

end FiniteLengthQuotientRange

section OrdEqLength

open GromovWitten.AlgebraicGeometry.IntersectionTheory

variable {A B : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A] [Ring.KrullDimLE 1 A]
  [CommRing B] [IsDomain B] [Algebra A B] [Module.Finite A B]

omit [IsDomain A] [IsNoetherianRing A] [Ring.KrullDimLE 1 A] in
/-- The range of `LinearMap.lsmul A A a` is the principal ideal `Ideal.span {a}`, as a submodule
of `A`. -/
theorem range_lsmul_self (a : A) :
    LinearMap.range (LinearMap.lsmul A A a) = Ideal.span {a} := by
  ext x
  simp only [LinearMap.mem_range, LinearMap.lsmul_apply, Ideal.mem_span_singleton']
  constructor
  · rintro ⟨y, rfl⟩; exact ⟨y, mul_comm y a⟩
  · rintro ⟨y, rfl⟩; exact ⟨y, mul_comm a y⟩

/-- **Fulton, Example A.3.1, Part (a).** If `algebraMap A B` is injective and every element of
`B` is, up to a nonzero scalar of `A`, in the image of `algebraMap A B` (`hrank`), then for
`a ≠ 0` the length of `B ⧸ a • B` (over `A`) equals `Ring.ord A a`: `B` and its free-of-rank-one
submodule `A · 1` have the same `chiCoker`, since their common cokernel `B ⧸ (A · 1)` has finite
length (`isFiniteLength_quotient_range_algebraMap`) and multiplication by `a` is injective both
on the domain `B` and on `A · 1 ≅ A`. -/
theorem length_smulTop_eq_ord (hinj : Function.Injective (algebraMap A B))
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a)
    {a : A} (ha : a ≠ 0) :
    Module.length A (B ⧸ (a • (⊤ : Submodule A B))) = Ring.ord A a := by
  have := noZeroSMulDivisors_of_injective (A := A) (B := B) hinj
  set N1 : Submodule A B := LinearMap.range (Algebra.linearMap A B) with hN1def
  have hinjLin : Function.Injective (Algebra.linearMap A B) := hinj
  have e : A ≃ₗ[A] N1 :=
    LinearEquiv.ofBijective (Algebra.linearMap A B).rangeRestrict
      ⟨(Algebra.linearMap A B).injective_rangeRestrict_iff.2 hinjLin,
        (Algebra.linearMap A B).surjective_rangeRestrict⟩
  have hkA : LocalOrdSymmetry.chiKer a A = 0 := by
    rw [LocalOrdSymmetry.chiKer, LinearMap.ker_eq_bot.2 (smul_right_injective A ha)]
    exact Module.length_eq_zero
  have hcA : LocalOrdSymmetry.chiCoker a A = Ring.ord A a := by
    change Module.length A (A ⧸ LinearMap.range (LinearMap.lsmul A A a))
      = Module.length A (A ⧸ Ideal.span {a})
    rw [range_lsmul_self]
  have hkN1 : LocalOrdSymmetry.chiKer a (↥N1) = 0 := by
    rw [← LocalOrdSymmetry.chiKer_congr a e]; exact hkA
  have hcN1 : LocalOrdSymmetry.chiCoker a (↥N1) = Ring.ord A a := by
    rw [← LocalOrdSymmetry.chiCoker_congr a e]; exact hcA
  have hkB : LocalOrdSymmetry.chiKer a B = 0 := by
    rw [LocalOrdSymmetry.chiKer, LinearMap.ker_eq_bot.2 (smul_right_injective B ha)]
    exact Module.length_eq_zero
  have hlen : Module.length A (B ⧸ N1) ≠ ⊤ :=
    Module.length_ne_top_iff.mpr (isFiniteLength_quotient_range_algebraMap hrank)
  have hkQ : LocalOrdSymmetry.chiKer a (B ⧸ N1) = LocalOrdSymmetry.chiCoker a (B ⧸ N1) :=
    OrderFiniteExtension.chiKer_eq_chiCoker_of_lengthNeTop a hlen
  have hcQ_le : LocalOrdSymmetry.chiCoker a (B ⧸ N1) ≤ Module.length A (B ⧸ N1) := by
    rw [LocalOrdSymmetry.chiCoker]
    exact Module.length_le_of_surjective (Submodule.mkQ _) (Submodule.mkQ_surjective _)
  have hne2 : LocalOrdSymmetry.chiCoker a (B ⧸ N1) ≠ ⊤ := ne_top_of_le_ne_top hlen hcQ_le
  have key := LocalOrdSymmetry.chi_add_submodule a N1
  rw [hkN1, hkB, add_zero, zero_add, hkQ] at key
  have hcoker_eq : LocalOrdSymmetry.chiCoker a B = LocalOrdSymmetry.chiCoker a (↥N1) :=
    LocalOrdSymmetry.enat_add_right_cancel hne2 key
  rw [← OrderFiniteExtension.range_lsmul_eq_smul_top]
  change LocalOrdSymmetry.chiCoker a B = Ring.ord A a
  rw [hcoker_eq, hcN1]

/-- **Fulton, Example A.3.1, Part (a), ideal form.** The `A`-length of `B ⧸ Ideal.span
{algebraMap A B a}` equals `Ring.ord A a`. -/
theorem length_quotient_span_eq_ord (hinj : Function.Injective (algebraMap A B))
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a)
    {a : A} (ha : a ≠ 0) :
    Module.length A (B ⧸ (Ideal.span {algebraMap A B a} : Ideal B).restrictScalars A)
      = Ring.ord A a := by
  rw [← smul_top_eq_restrictScalars_span]
  exact length_smulTop_eq_ord hinj hrank ha

/-- **Fulton, Example A.3.1, Part (a), ideal form (literal ideal quotient).** The `A`-length of
`B ⧸ Ideal.span {algebraMap A B a}` (a genuine `B`-module, unlike the `A`-submodule-quotient forms
above) equals `Ring.ord A a`. -/
theorem length_quotient_ideal_eq_ord (hinj : Function.Injective (algebraMap A B))
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a)
    {a : A} (ha : a ≠ 0) :
    Module.length A (B ⧸ (Ideal.span {algebraMap A B a} : Ideal B)) = Ring.ord A a := by
  rw [← (Submodule.Quotient.restrictScalarsEquiv A
    (Ideal.span {algebraMap A B a} : Ideal B)).length_eq]
  exact length_quotient_span_eq_ord hinj hrank ha

end OrdEqLength

section FiniteBLength

variable {A B : Type*} [CommRing A] [IsLocalRing A] [IsNoetherianRing A] [Ring.KrullDimLE 1 A]
  [CommRing B] [IsDomain B] [Algebra A B] [Module.Finite A B]

omit [IsLocalRing A] [IsNoetherianRing A] [Ring.KrullDimLE 1 A] [IsDomain B] [Module.Finite A B] in
/-- **Finite length descends along the scalar tower `A → B`.** If `B ⧸ J` (`J` an ideal of `B`)
has finite length as an `A`-module, it also has finite length as a `B`-module: any ascending or
descending chain of `B`-submodules is, via `IsScalarTower A B (B⧸J)`, also a chain of
`A`-submodules, so the Noetherian/Artinian conditions transfer from the finer `A`-module structure
to the coarser `B`-module structure (`isNoetherian_of_tower`, `isArtinian_of_tower`). -/
theorem isFiniteLength_of_isFiniteLength_restrictScalars (J : Ideal B)
    (hA : IsFiniteLength A (B ⧸ J)) : IsFiniteLength B (B ⧸ J) := by
  obtain ⟨hN, hArt⟩ := isFiniteLength_iff_isNoetherian_isArtinian.mp hA
  exact isFiniteLength_iff_isNoetherian_isArtinian.mpr
    ⟨isNoetherian_of_tower A inferInstance, isArtinian_of_tower A inferInstance⟩

end FiniteBLength

section FinalAssembly

variable {A B : Type*} [CommRing A] [IsDomain A] [IsLocalRing A] [IsNoetherianRing A]
  [Ring.KrullDimLE 1 A] [CommRing B] [IsDomain B] [Algebra A B] [Module.Finite A B]

/-- **Fulton, Example A.3.1.** For `A` a Noetherian local domain of Krull dimension `≤ 1`, `B` a
domain module-finite over `A` with `algebraMap A B` injective and of "generic rank one" (`hrank`:
every element of `B` is, up to a nonzero scalar of `A`, in the image of `algebraMap A B`), and
`a ≠ 0`:

`Ring.ord A a = ∑ᶠ q : MaximalSpectrum B, OrderSemilocal.summand (A := A) (B ⧸ Ideal.span
{algebraMap A B a}) q`.

Combines the semilocal length formula (`OrderSemilocal.length_eq_finsum`, applied to `N = B ⧸
Ideal.span {algebraMap A B a}`, using `isFiniteLength_of_isFiniteLength_restrictScalars` for the
needed `IsFiniteLength B N`) with Part (a) (`length_quotient_ideal_eq_ord`). -/
theorem ord_eq_finsum_summand (hinj : Function.Injective (algebraMap A B))
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a)
    {a : A} (ha : a ≠ 0) :
    Ring.ord A a = ∑ᶠ q : MaximalSpectrum B,
      OrderSemilocal.summand (A := A) (B ⧸ (Ideal.span {algebraMap A B a} : Ideal B)) q := by
  set J : Ideal B := Ideal.span {algebraMap A B a} with hJdef
  have hA : IsFiniteLength A (B ⧸ J) := by
    rw [← Module.length_ne_top_iff, length_quotient_ideal_eq_ord hinj hrank ha]
    exact Ring.ord_ne_top (mem_nonZeroDivisors_iff_ne_zero.mpr ha)
  have hB : IsFiniteLength B (B ⧸ J) := isFiniteLength_of_isFiniteLength_restrictScalars J hA
  rw [← length_quotient_ideal_eq_ord hinj hrank ha]
  exact OrderSemilocal.length_eq_finsum (A := A) hB

end FinalAssembly

section LocalizedQuotient

variable {A B : Type*} [CommRing A] [IsLocalRing A] [CommRing B] [Algebra A B]
  [Module.Finite A B]

attribute [local instance] LocalizedModule.moduleOfIsLocalization

omit [IsLocalRing A] [Module.Finite A B] in
/-- **Localization commutes with quotienting by a principal ideal.** For `q` a maximal ideal of
`B` and `J = Ideal.span {c}` a principal ideal of `B`, localizing `B ⧸ J` at `q.primeCompl` gives
`Localization.AtPrime q ⧸ Ideal.span {algebraMap B (Localization.AtPrime q) c}`. Proved by
uniqueness of localized modules: both `LocalizedModule.mkLinearMap` and the natural quotient map
`B ⧸ J → (Localization.AtPrime q) ⧸ (image ideal)` (`Submodule.toLocalizedQuotient'`, an
automatic `IsLocalizedModule` instance) realise `B ⧸ J` localized at `q.primeCompl`. -/
noncomputable def localizedModule_quotient_span_equiv (q : Ideal B) [q.IsMaximal] (c : B) :
    LocalizedModule q.primeCompl (B ⧸ (Ideal.span {c} : Ideal B)) ≃ₗ[Localization.AtPrime q]
      Localization.AtPrime q ⧸ (Ideal.span {algebraMap B (Localization.AtPrime q) c} :
        Ideal (Localization.AtPrime q)) := by
  have hloc :
      (Ideal.span {c} : Ideal B).localized' (Localization.AtPrime q) q.primeCompl
          (Algebra.linearMap B (Localization.AtPrime q))
        = (Ideal.span {algebraMap B (Localization.AtPrime q) c}
            : Ideal (Localization.AtPrime q)) := by
    rw [(Ideal.span {c} : Ideal B).localized'_eq_span (Localization.AtPrime q) q.primeCompl
      (Algebra.linearMap B (Localization.AtPrime q))]
    change Ideal.map (algebraMap B (Localization.AtPrime q)) (Ideal.span {c}) = _
    rw [Ideal.map_span, Set.image_singleton]
  have e1 : (LocalizedModule q.primeCompl (B ⧸ (Ideal.span {c} : Ideal B))) ≃ₗ[B]
      (Localization.AtPrime q ⧸
        (Ideal.span {c} : Ideal B).localized' (Localization.AtPrime q) q.primeCompl
          (Algebra.linearMap B (Localization.AtPrime q))) :=
    IsLocalizedModule.linearEquiv q.primeCompl
      (LocalizedModule.mkLinearMap q.primeCompl (B ⧸ (Ideal.span {c} : Ideal B)))
      ((Ideal.span {c} : Ideal B).toLocalizedQuotient' (Localization.AtPrime q) q.primeCompl
        (Algebra.linearMap B (Localization.AtPrime q)))
  have e2 : (Localization.AtPrime q ⧸
      (Ideal.span {c} : Ideal B).localized' (Localization.AtPrime q) q.primeCompl
        (Algebra.linearMap B (Localization.AtPrime q)))
      ≃ₗ[Localization.AtPrime q]
      (Localization.AtPrime q ⧸
        (Ideal.span {algebraMap B (Localization.AtPrime q) c}
          : Ideal (Localization.AtPrime q))) :=
    Submodule.quotEquivOfEq _ _ hloc
  exact (e1.trans (e2.restrictScalars B)).extendScalarsOfIsLocalization q.primeCompl
    (Localization.AtPrime q)

/-- **Part (c): identifying each summand.** For `q : MaximalSpectrum B`, the `q`-summand of
`OrderSemilocal.summand` for `N = B ⧸ Ideal.span {algebraMap A B a}` is `[κ(q):κ_A] · Ring.ord
(Localization.AtPrime q.asIdeal) (algebraMap A _ a)`, the readable Fulton A.3.1 form. -/
theorem summand_quotient_ideal_eq {A B : Type*} [CommRing A] [IsLocalRing A] [CommRing B]
    [Algebra A B] [Module.Finite A B] (q : MaximalSpectrum B) (a : A) :
    OrderSemilocal.summand (A := A) (B ⧸ (Ideal.span {algebraMap A B a} : Ideal B)) q =
      (Module.finrank (IsLocalRing.ResidueField A) q.asIdeal.ResidueField : ℕ∞) *
        Ring.ord (Localization.AtPrime q.asIdeal)
          (algebraMap A (Localization.AtPrime q.asIdeal) a) := by
  have hc : algebraMap B (Localization.AtPrime q.asIdeal) (algebraMap A B a)
      = algebraMap A (Localization.AtPrime q.asIdeal) a :=
    (IsScalarTower.algebraMap_apply A B (Localization.AtPrime q.asIdeal) a).symm
  unfold OrderSemilocal.summand
  congr 1
  rw [(localizedModule_quotient_span_equiv q.asIdeal (algebraMap A B a)).length_eq, hc, Ring.ord]

end LocalizedQuotient

section ReadableForm

variable {A B : Type*} [CommRing A] [IsDomain A] [IsLocalRing A] [IsNoetherianRing A]
  [Ring.KrullDimLE 1 A] [CommRing B] [IsDomain B] [Algebra A B] [Module.Finite A B]

/-- **Fulton, Example A.3.1, readable form.** For `A` a Noetherian local domain of Krull
dimension `≤ 1`, `B` a domain module-finite over `A` with `algebraMap A B` injective and of
"generic rank one" (`hrank`), and `a ≠ 0`:

`Ring.ord A a = ∑ᶠ q : MaximalSpectrum B, [κ(q) : κ_A] · Ring.ord (Localization.AtPrime q.asIdeal)
(algebraMap A _ a)`,

where `[κ(q):κ_A] = Module.finrank (IsLocalRing.ResidueField A) q.asIdeal.ResidueField`. Combines
`ord_eq_finsum_summand` with the per-summand identification `summand_quotient_ideal_eq`. -/
theorem ord_eq_finsum (hinj : Function.Injective (algebraMap A B))
    (hrank : ∀ b : B, ∃ (s : A) (a : A), s ≠ 0 ∧ s • b = algebraMap A B a)
    {a : A} (ha : a ≠ 0) :
    Ring.ord A a = ∑ᶠ q : MaximalSpectrum B,
      (Module.finrank (IsLocalRing.ResidueField A) q.asIdeal.ResidueField : ℕ∞) *
        Ring.ord (Localization.AtPrime q.asIdeal)
          (algebraMap A (Localization.AtPrime q.asIdeal) a) := by
  rw [ord_eq_finsum_summand hinj hrank ha]
  exact finsum_congr fun q => summand_quotient_ideal_eq q a

end ReadableForm

end OrderBirational
