/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import Mathlib.RingTheory.Regular.RegularSequence
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.Tactic.LinearCombination

/-!
# Regular sequences are quasi-regular

This file contains the commutative-algebra input for the comparison between the normal cone and
the normal bundle of a regular closed immersion.  Nothing in this file mentions cones, schemes or
normal sheaves: it is a statement about ideals generated by a finite regular sequence.

For a family `x : ι → R` write `I = span (range x)`.  Substituting `x` into a homogeneous
polynomial of degree `d` always lands in `I ^ d`.  The family is *quasi-regular*
(`GromovWitten.Algebra.IsQuasiregular`) when the converse comparison holds degreewise: whenever a
homogeneous polynomial of degree `d` evaluates into `I ^ (d + 1)`, all of its coefficients already
lie in `I`.  Equivalently, the canonical surjection `(R/I)[X_i] → ⨁ I^n/I^(n+1)` is injective.

The main result is `GromovWitten.Algebra.isQuasiregular_of_isWeaklyRegular`: a finite weakly
regular sequence in Mathlib's sense (`RingTheory.Sequence.IsWeaklyRegular`) is quasi-regular.
The proof is the classical induction on the length of the sequence:

* `IsQuasiregular.option` — the inductive step, adjoining to a quasi-regular family an element
  `f` which is a non-zerodivisor modulo `J = span (range x')`.  Two intermediate steps are proved
  inline in that theorem: `f` is a non-zerodivisor modulo every power `J ^ m`, and the colon
  computation `I ^ (d+1) : f = I ^ d` follows from it;
* `isQuasiregular_of_isWeaklyRegular` — the induction on the length of the sequence.

No part of the argument assumes anything about the associated graded ring; the polynomial
comparison is constructed by hand.
-/

open MvPolynomial

namespace GromovWitten.Algebra

variable {R : Type*} [CommRing R]

/-- A family `x : ι → R` is **quasi-regular** when, writing `I = span (range x)`, every
homogeneous polynomial of degree `d` whose value at `x` lies in `I ^ (d + 1)` has all of its
coefficients in `I`.

This is exactly injectivity of the canonical map from the polynomial ring over `R/I` to the
associated graded ring of `I`, expressed without mentioning the associated graded ring. -/
def IsQuasiregular {ι : Type*} (x : ι → R) : Prop :=
  ∀ (d : ℕ) (F : MvPolynomial ι R), F.IsHomogeneous d →
    MvPolynomial.eval x F ∈ (Ideal.span (Set.range x)) ^ (d + 1) →
      ∀ α, F.coeff α ∈ Ideal.span (Set.range x)

section Auxiliary

variable {ι : Type*}

/-- Substituting a family into a homogeneous polynomial of degree `d` lands in the `d`-th power
of the ideal it generates. -/
theorem eval_mem_span_pow (x : ι → R) {d : ℕ} {F : MvPolynomial ι R}
    (hF : F.IsHomogeneous d) : MvPolynomial.eval x F ∈ (Ideal.span (Set.range x)) ^ d :=
  (Ideal.mem_span_pow_iff_exists_isHomogeneous x _).2 ⟨F, hF, rfl⟩

/-- A refinement of `eval_mem_span_pow`: if moreover all coefficients lie in an ideal `K`, then
the value lies in `K * I ^ d`. -/
theorem eval_mem_mul_span_pow (x : ι → R) (K : Ideal R) {d : ℕ} {F : MvPolynomial ι R}
    (hF : F.IsHomogeneous d) (hc : ∀ α, F.coeff α ∈ K) :
    MvPolynomial.eval x F ∈ K * (Ideal.span (Set.range x)) ^ d := by
  classical
  have hsum : MvPolynomial.eval x F =
      ∑ α ∈ F.support, MvPolynomial.eval x (monomial α (F.coeff α)) := by
    conv_lhs => rw [F.as_sum]
    rw [map_sum]
  rw [hsum]
  refine Ideal.sum_mem _ fun α hα => ?_
  have hdeg : α.degree = d := by
    by_contra h
    exact (mem_support_iff.mp hα) (hF.coeff_eq_zero h)
  have hmon : MvPolynomial.eval x (monomial α (1 : R)) ∈ (Ideal.span (Set.range x)) ^ d :=
    eval_mem_span_pow x (isHomogeneous_monomial _ hdeg)
  rw [eval_monomial, one_mul] at hmon
  rw [eval_monomial]
  exact Ideal.mul_mem_mul (hc α) hmon

/-- Coefficients of a product lie in `K` as soon as the coefficients of one factor do. -/
theorem coeff_mul_mem (K : Ideal R) (p q : MvPolynomial ι R)
    (hq : ∀ α, q.coeff α ∈ K) (β) : (p * q).coeff β ∈ K := by
  classical
  rw [coeff_mul]
  exact Ideal.sum_mem _ fun _ _ => K.mul_mem_left _ (hq _)

/-- Renaming variables along an injection preserves the property of having all coefficients in an
ideal `K`. -/
theorem coeff_rename_mem {τ : Type*} (K : Ideal R) (e : ι → τ) (he : Function.Injective e)
    (p : MvPolynomial ι R) (hp : ∀ α, p.coeff α ∈ K) (β) : (rename e p).coeff β ∈ K := by
  classical
  by_cases h : ∃ α, Finsupp.mapDomain e α = β
  · obtain ⟨α, rfl⟩ := h
    rw [coeff_rename_mapDomain e he]
    exact hp α
  · rw [coeff_rename_eq_zero e p β (fun u hu => absurd ⟨u, hu⟩ h)]
    exact K.zero_mem

/-- The degree-zero half of quasi-regularity, valid for every family. -/
theorem coeff_mem_of_isHomogeneous_zero (x : ι → R) (F : MvPolynomial ι R)
    (hF : F.IsHomogeneous 0)
    (hval : MvPolynomial.eval x F ∈ Ideal.span (Set.range x)) (α) :
    F.coeff α ∈ Ideal.span (Set.range x) := by
  classical
  have hC : F = C (F.coeff 0) :=
    (MvPolynomial.totalDegree_eq_zero_iff_eq_C).1
      (MvPolynomial.totalDegree_zero_iff_isHomogeneous (σ := ι) |>.2 hF)
  have hv : F.coeff 0 ∈ Ideal.span (Set.range x) := by
    rw [hC] at hval
    simpa using hval
  rcases eq_or_ne α 0 with rfl | hα
  · exact hv
  · rw [hC, coeff_C, if_neg (Ne.symm hα)]
    exact Submodule.zero_mem _

/-- A family indexed by an empty type is vacuously quasi-regular. -/
theorem isQuasiregular_of_isEmpty [IsEmpty ι] (x : ι → R) : IsQuasiregular x := by
  intro d F hF hval α
  rcases eq_or_ne F 0 with rfl | hFne
  · simp
  · have hd : d = 0 := hF.inj_right (MvPolynomial.isHomogeneous_of_isEmpty (f := F)) hFne
    subst hd
    exact coeff_mem_of_isHomogeneous_zero x F hF (by simpa using hval) α

/-- Quasi-regularity is invariant under reindexing the family along an equivalence. -/
theorem IsQuasiregular.comp_equiv {κ : Type*} {x : ι → R} (h : IsQuasiregular x) (e : κ ≃ ι) :
    IsQuasiregular (x ∘ e) := by
  have hrange : Set.range (x ∘ e) = Set.range x := by
    rw [Set.range_comp, e.range_eq_univ, Set.image_univ]
  intro d F hF hval α
  rw [hrange]
  have hF' : (rename (e : κ → ι) F).IsHomogeneous d := hF.rename_isHomogeneous
  have hval' : MvPolynomial.eval x (rename (e : κ → ι) F) ∈
      (Ideal.span (Set.range x)) ^ (d + 1) := by
    rw [eval_rename]
    rw [hrange] at hval
    exact hval
  have := h d _ hF' hval' (Finsupp.mapDomain (e : κ → ι) α)
  rwa [coeff_rename_mapDomain _ e.injective] at this

/-- Characterisation of homogeneity in terms of `Finsupp.degree`. -/
theorem isHomogeneous_iff_degree {F : MvPolynomial ι R} {n : ℕ} :
    F.IsHomogeneous n ↔ ∀ β, F.coeff β ≠ 0 → β.degree = n := by
  constructor
  · intro h β hβ
    by_contra hd
    exact hβ (h.coeff_eq_zero hd)
  · intro h β hβ
    rw [Pi.one_def, ← Finsupp.degree_eq_weight_one]
    exact h β hβ

/-- Monotonicity of ideal powers. -/
theorem pow_le_pow_of_le {I J : Ideal R} (h : I ≤ J) (n : ℕ) : I ^ n ≤ J ^ n := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ, pow_succ]; exact Ideal.mul_mono ih h

end Auxiliary

section Step

variable {σ : Type*}

/-- The inverse of `optionEquivLeft` turns a constant polynomial into the corresponding
polynomial in the remaining variables. -/
theorem optionEquivLeft_symm_C (q : MvPolynomial σ R) :
    (optionEquivLeft R σ).symm (Polynomial.C q) = rename some q := by
  simp [optionEquivLeft]

/-- Splitting off the distinguished variable `none`: a homogeneous polynomial of degree `d + 1`
in the variables `Option σ` is the sum of a homogeneous polynomial of degree `d + 1` in the
remaining variables and `X none` times a homogeneous polynomial of degree `d`. -/
theorem exists_split_of_isHomogeneous_succ [Finite σ] {d : ℕ}
    {F : MvPolynomial (Option σ) R} (hF : F.IsHomogeneous (d + 1)) :
    ∃ (F₀ : MvPolynomial σ R) (G : MvPolynomial (Option σ) R),
      F = rename some F₀ + X none * G ∧ F₀.IsHomogeneous (d + 1) ∧ G.IsHomogeneous d := by
  classical
  set p := optionEquivLeft R σ F with hp
  set F₀ : MvPolynomial σ R := p.coeff 0 with hF₀
  set G : MvPolynomial (Option σ) R := (optionEquivLeft R σ).symm p.divX with hG
  have hsymm : (optionEquivLeft R σ).symm p = F := by rw [hp, AlgEquiv.symm_apply_apply]
  have hsplit : F = rename some F₀ + X none * G := by
    have h1 : (optionEquivLeft R σ).symm (Polynomial.X * p.divX + Polynomial.C F₀) = F := by
      rw [hF₀, Polynomial.X_mul_divX_add, hsymm]
    rw [← h1, map_add, map_mul, optionEquivLeft_symm_X, optionEquivLeft_symm_C, hG]
    ring
  have hhom0 : F₀.IsHomogeneous (d + 1) :=
    MvPolynomial.IsHomogeneous.coeff_isHomogeneous_of_optionEquivLeft_symm
      (p := p) (by rw [hsymm]; exact hF) 0 (d + 1) (by ring)
  have hXG : (X none * G : MvPolynomial (Option σ) R).IsHomogeneous (d + 1) := by
    have hsub : (X none * G : MvPolynomial (Option σ) R) = F - rename some F₀ := by
      rw [hsplit]; ring
    rw [hsub]
    exact hF.sub hhom0.rename_isHomogeneous
  have hhomG : G.IsHomogeneous d := by
    rw [isHomogeneous_iff_degree]
    intro β hβ
    have hne : (X none * G : MvPolynomial (Option σ) R).coeff
        (Finsupp.single none 1 + β) ≠ 0 := by
      rwa [coeff_X_mul]
    have hdeg := (isHomogeneous_iff_degree.1 hXG) _ hne
    rw [map_add, Finsupp.degree_single] at hdeg
    omega
  exact ⟨F₀, G, hsplit, hhom0, hhomG⟩

/-- **The inductive step.**  Adjoining to a quasi-regular family an element which is a
non-zerodivisor modulo the ideal generated by that family again gives a quasi-regular family. -/
theorem IsQuasiregular.option [Finite σ] {x' : σ → R} (hx' : IsQuasiregular x') (f : R)
    (hf : ∀ a : R, f * a ∈ Ideal.span (Set.range x') → a ∈ Ideal.span (Set.range x')) :
    IsQuasiregular (fun o : Option σ => o.elim f x') := by
  classical
  set x : Option σ → R := fun o => o.elim f x' with hxdef
  set J : Ideal R := Ideal.span (Set.range x') with hJdef
  set I : Ideal R := Ideal.span (Set.range x) with hIdef
  have hrange : Set.range x = insert f (Set.range x') := by
    ext r
    constructor
    · rintro ⟨o, rfl⟩
      cases o with
      | none => exact Set.mem_insert _ _
      | some i => exact Set.mem_insert_of_mem _ ⟨i, rfl⟩
    · rintro (rfl | ⟨i, rfl⟩)
      · exact ⟨none, rfl⟩
      · exact ⟨some i, rfl⟩
  have hI : I = Ideal.span {f} ⊔ J := by rw [hIdef, hrange, Ideal.span_insert]
  have hJI : J ≤ I := by rw [hI]; exact le_sup_right
  have hfI : f ∈ I := by
    rw [hI]
    exact Ideal.mem_sup_left (Ideal.subset_span rfl)
  -- `f` is a non-zerodivisor modulo every power of `J`.
  have L1 : ∀ (m : ℕ) (a : R), f * a ∈ J ^ m → a ∈ J ^ m := by
    intro m
    induction m with
    | zero => intro a _; simp
    | succ m ih =>
      intro a ha
      have ha' : a ∈ J ^ m := ih a (Ideal.pow_le_pow_right (Nat.le_succ m) ha)
      obtain ⟨A, hA, rfl⟩ :=
        (Ideal.mem_span_pow_iff_exists_isHomogeneous (n := m) x' a).1 ha'
      have hvalCA : MvPolynomial.eval x' (C f * A) ∈ J ^ (m + 1) := by
        rw [map_mul, eval_C]
        exact ha
      have hcoeff : ∀ α, (C f * A).coeff α ∈ J := hx' m _ (hA.C_mul f) hvalCA
      have hAcoeff : ∀ α, A.coeff α ∈ J := by
        intro α
        refine hf _ ?_
        have hα := hcoeff α
        rwa [coeff_C_mul] at hα
      have hfin := eval_mem_mul_span_pow x' J hA hAcoeff
      rwa [← pow_succ'] at hfin
  -- Expanding a power of `I = J + (f)`.
  have L2 : ∀ e : ℕ, I ^ (e + 1) ≤ J ^ (e + 1) ⊔ Ideal.span {f} * I ^ e := by
    intro e
    induction e with
    | zero =>
      have e1 : I ^ (0 + 1) = Ideal.span {f} ⊔ J := by
        simp only [zero_add, pow_one]
        exact hI
      have e2 : J ^ (0 + 1) ⊔ Ideal.span {f} * I ^ 0 = J ⊔ Ideal.span {f} := by simp
      rw [e1, e2]
      exact sup_le le_sup_right le_sup_left
    | succ e ih =>
      rw [pow_succ' I (e + 1)]
      refine le_trans (Ideal.mul_mono le_rfl ih) ?_
      rw [Ideal.mul_sup]
      refine sup_le ?_ ?_
      · conv_lhs => rw [hI]
        rw [Ideal.sup_mul]
        refine sup_le ?_ ?_
        · exact le_sup_of_le_right (Ideal.mul_mono le_rfl (pow_le_pow_of_le hJI _))
        · refine le_sup_of_le_left ?_
          rw [← pow_succ']
      · refine le_sup_of_le_right ?_
        rw [← mul_assoc, mul_comm I (Ideal.span {f}), mul_assoc, ← pow_succ']
  -- The colon computation `I ^ (d + 1) : f = I ^ d`.
  have L3 : ∀ (d : ℕ) (a : R), f * a ∈ I ^ (d + 1) → a ∈ I ^ d := by
    intro d a ha
    obtain ⟨u, hu, w, hw, huw⟩ := Submodule.mem_sup.1 (L2 d ha)
    obtain ⟨v, hv, rfl⟩ := Ideal.mem_span_singleton_mul.1 hw
    have key : f * (a - v) = u := by linear_combination -huw
    have h1 : a - v ∈ J ^ (d + 1) := L1 _ _ (by rw [key]; exact hu)
    have hav : a = a - v + v := by ring
    rw [hav]
    exact Ideal.add_mem _
      (Ideal.pow_le_pow_right (Nat.le_succ d) (pow_le_pow_of_le hJI _ h1)) hv
  intro d
  induction d with
  | zero =>
    intro F hF hval α
    exact coeff_mem_of_isHomogeneous_zero x F hF (by simpa using hval) α
  | succ d ih =>
    intro F hF hval α
    obtain ⟨F₀, G, hsplit, hhom0, hhomG⟩ := exists_split_of_isHomogeneous_succ hF
    have hxsome : x ∘ (some : σ → Option σ) = x' := rfl
    have hevalsplit : MvPolynomial.eval x F
        = MvPolynomial.eval x' F₀ + f * MvPolynomial.eval x G := by
      rw [hsplit, map_add, eval_rename, hxsome, map_mul, eval_X]
      rfl
    have hF0val : MvPolynomial.eval x' F₀ ∈ J ^ (d + 1) := eval_mem_span_pow x' hhom0
    obtain ⟨u, hu, w, hw, huw⟩ := Submodule.mem_sup.1 (L2 (d + 1) hval)
    obtain ⟨v, hv, rfl⟩ := Ideal.mem_span_singleton_mul.1 hw
    rw [hevalsplit] at huw
    have h4 : f * (v - MvPolynomial.eval x G) ∈ J ^ (d + 1) := by
      have heq : f * (v - MvPolynomial.eval x G) = MvPolynomial.eval x' F₀ - u := by
        linear_combination huw
      rw [heq]
      exact Ideal.sub_mem _ hF0val (Ideal.pow_le_pow_right (Nat.le_succ _) hu)
    have h5 : v - MvPolynomial.eval x G ∈ J ^ (d + 1) := L1 _ _ h4
    obtain ⟨W, hW, hWval⟩ :=
      (Ideal.mem_span_pow_iff_exists_isHomogeneous (n := d + 1) x' _).1 h5
    have h6 : ∀ β, (F₀ - C f * W).coeff β ∈ J := by
      refine hx' (d + 1) _ (hhom0.sub (hW.C_mul f)) ?_
      have hev : MvPolynomial.eval x' (F₀ - C f * W) = u := by
        rw [map_sub, map_mul, eval_C, hWval]
        linear_combination -huw
      rw [hev]
      exact hu
    have h7 : ∀ β, F₀.coeff β ∈ I := by
      intro β
      have hexp : F₀.coeff β = (F₀ - C f * W).coeff β + f * W.coeff β := by
        rw [coeff_sub, coeff_C_mul]; ring
      rw [hexp]
      exact Ideal.add_mem _ (hJI (h6 β)) (Ideal.mul_mem_right _ _ hfI)
    have h8 : MvPolynomial.eval x' F₀ ∈ I ^ (d + 1 + 1) := by
      have h := eval_mem_mul_span_pow x' I hhom0 h7
      have hle : I * J ^ (d + 1) ≤ I ^ (d + 1 + 1) := by
        calc I * J ^ (d + 1) ≤ I * I ^ (d + 1) :=
              Ideal.mul_mono le_rfl (pow_le_pow_of_le hJI _)
          _ = I ^ (d + 1 + 1) := (pow_succ' I (d + 1)).symm
      exact hle h
    have h9 : f * MvPolynomial.eval x G ∈ I ^ (d + 1 + 1) := by
      have hfg : f * MvPolynomial.eval x G
          = MvPolynomial.eval x F - MvPolynomial.eval x' F₀ := by
        rw [hevalsplit]; ring
      rw [hfg]
      exact Ideal.sub_mem _ hval h8
    have h10 : MvPolynomial.eval x G ∈ I ^ (d + 1) := L3 (d + 1) _ h9
    have h11 : ∀ β, G.coeff β ∈ I := ih G hhomG h10
    rw [hsplit, coeff_add]
    exact Ideal.add_mem _ (coeff_rename_mem I some (Option.some_injective σ) F₀ h7 α)
      (coeff_mul_mem I _ G h11 α)

end Step


section Regular

open RingTheory.Sequence

/-- The ideal generated by the entries of `List.ofFn x` is the ideal generated by the range. -/
theorem ofList_ofFn {n : ℕ} (x : Fin n → R) :
    Ideal.ofList (List.ofFn x) = Ideal.span (Set.range x) := by
  have hset : {r : R | r ∈ List.ofFn x} = Set.range x := by
    ext r; simp
  exact congrArg Ideal.span hset

/-- **Finite weakly regular sequences are quasi-regular.**

This is the classical theorem that for an ideal generated by a regular sequence the canonical
surjection from the polynomial ring over `R/I` onto the associated graded ring is injective,
phrased purely in terms of coefficients of homogeneous polynomials. -/
theorem isQuasiregular_of_isWeaklyRegular :
    ∀ (n : ℕ) (x : Fin n → R), IsWeaklyRegular R (List.ofFn x) → IsQuasiregular x := by
  intro n
  induction n with
  | zero => intro x _; exact isQuasiregular_of_isEmpty x
  | succ n ih =>
    intro x hx
    set x' : Fin n → R := fun i => x i.castSucc with hx'def
    set f : R := x (Fin.last n) with hfdef
    have hlist : List.ofFn x = List.ofFn x' ++ [f] := by
      rw [List.ofFn_succ']
      simp only [List.concat_eq_append]
      exact congrArg (· ++ [f]) (congrArg List.ofFn hx'def.symm)
    rw [hlist, isWeaklyRegular_append_iff] at hx
    obtain ⟨hx1, hx2⟩ := hx
    have hQ : IsQuasiregular x' := ih x' hx1
    have hJ : (Ideal.ofList (List.ofFn x') • ⊤ : Submodule R R)
        = Ideal.span (Set.range x') := by
      rw [ofList_ofFn, Ideal.smul_eq_mul, Ideal.mul_top]
    rw [isWeaklyRegular_singleton_iff] at hx2
    have hfreg : ∀ a : R, f * a ∈ Ideal.span (Set.range x') →
        a ∈ Ideal.span (Set.range x') := by
      intro a ha
      have hz : f • (Submodule.Quotient.mk a :
          R ⧸ (Ideal.ofList (List.ofFn x') • ⊤ : Submodule R R)) = f • 0 := by
        rw [smul_zero, ← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero, hJ]
        exact ha
      have h0 := hx2 hz
      rw [Submodule.Quotient.mk_eq_zero, hJ] at h0
      exact h0
    have hopt : IsQuasiregular (fun o : Option (Fin n) => o.elim f x') := hQ.option f hfreg
    have hcomp : (fun o : Option (Fin n) => o.elim f x') ∘
        (finSuccEquivLast : Fin (n + 1) ≃ Option (Fin n)) = x := by
      funext i
      refine Fin.lastCases ?_ ?_ i
      · simpa using hfdef
      · intro j; simpa using congrFun hx'def j
    have hfin := hopt.comp_equiv (finSuccEquivLast : Fin (n + 1) ≃ Option (Fin n))
    rwa [hcomp] at hfin

end Regular

end GromovWitten.Algebra
