/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.AlgebraicGeometry.Cones.DeformationSpace
import GromovWitten.AlgebraicGeometry.Cones.Quotient
import Mathlib.AlgebraicGeometry.Pullbacks
import Mathlib.LinearAlgebra.DirectSum.Finsupp
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.Polynomial.Ideal

/-!
# Geometry of the affine Rees deformation space

This file completes the geometric package around the affine deformation space
`M° = Spec R[It, t⁻¹]` constructed in `GromovWitten.AlgebraicGeometry.Cones.DeformationSpace`.

## Main results

### Cartesian squares of fibre identifications

* `isPushout_of_surjective`: a pushout criterion for squares of commutative rings whose two
  right-hand maps are surjective, used for all the closed-fibre squares below.
* `specialFibre_isPullback`, `normalCone_isPullback`: the fibre of `M° → 𝔸¹` over the origin is
  the affine normal cone `Spec (gr_I R)`.
* `fibreOne_isPullback`, `fibreOne_isPullback_spec`: the fibre over `u = 1` is `Spec R`.
* `genericFibre_isPullback`: the part of `M°` lying over `𝔾ₘ ⊆ 𝔸¹` is the trivial family
  `Spec R × 𝔾ₘ = Spec R[t, t⁻¹]`.

### The deformation of the closed subscheme

* `subschemeHom`, `subschemeι`: the closed immersion
  `Spec (R/I) × 𝔸¹ = Spec ((R/I)[u]) → M°` deforming `Spec (R/I) ⊆ Spec R`, with
  `subschemeι_isClosedImmersion` and `subschemeι_comp_toLine` (compatibility with the
  projection to `𝔸¹`).
* `origin_comp_subschemeι`: its special fibre is the vertex of the affine normal cone.

### Base change

* `mapLaurent`: coefficientwise base change of Laurent polynomials.
* `reesTensorMap`, `reesTensorMap_surjective`: the canonical comparison map
  `R[It, t⁻¹] ⊗_R B → B[(IB)t, t⁻¹]` is surjective for an arbitrary `R`-algebra `B`.
* `reesTensorEquiv`, `isPushout_reesBaseChange`, `reesBaseChange_isPullback`: it is an
  isomorphism when `B` is flat over `R`, and the resulting square of affine schemes is
  cartesian.  `reesBaseChange_isPullback_isLocalization` is the localization case.

### The tangent action

* `ConeQuotient.bundleTranslationAction`: the action of the vector bundle `Spec Sym(F)` on the
  vector bundle `Spec Sym(N)` attached to a linear map `d : N →ₗ F`, with all the `ConeAction`
  laws proved.  For `d = id` it is the translation action of a bundle on itself
  (`bundleTranslationCoaction_id`).
* `AffineNormalCone.conormalMap`: the conormal map `I/I² → (R/I) ⊗_R Ω[R⁄k]`.
* `AffineNormalCone.normalSheafTangentAction`: the resulting action of the restricted tangent
  bundle `Spec Sym_{R/I}((R/I) ⊗_R Ω[R⁄k])` on the affine normal *sheaf*
  `Spec Sym_{R/I}(I/I²)`, together with the affine action morphism
  `normalSheafActionMap` and its unit law.

## Remaining work

The tangent action is constructed on the normal *sheaf* `C(I/I²)` only.  Transporting it along
the closed immersion `coneToNormalSheaf : Spec (gr_I R) → C(I/I²)` to an action on the normal
*cone* requires knowing that the surjection `Sym_{R/I}(I/I²) → gr_I R` has a kernel stable
under the translation coaction; this is true when the ambient scheme is smooth over `k`
(Vistoli's lemma, used to build the intrinsic normal cone) and is not proved here.
-/

open CategoryTheory Limits AlgebraicGeometry LaurentPolynomial
open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

universe u

noncomputable section

namespace AffineDeformationSpace

/-! ### A pushout criterion for quotient squares -/

section PushoutCriterion

variable {A B C P : CommRingCat.{u}}

/-- A commutative square of commutative rings whose bottom map `g` and right map `i` are
surjective and in which `ker i` is contained in the ideal generated by the image of `ker g`
is a pushout square.  This is the algebraic form of "the fibre of `Spec B → Spec A` over a
closed point `Spec C ⊆ Spec A` is `Spec P`". -/
theorem isPushout_of_surjective (f : A ⟶ B) (g : A ⟶ C) (i : B ⟶ P) (j : C ⟶ P)
    (w : f ≫ i = g ≫ j) (hg : Function.Surjective g.hom) (hi : Function.Surjective i.hom)
    (hker : RingHom.ker i.hom ≤ Ideal.map f.hom (RingHom.ker g.hom)) :
    IsPushout f g i j := by
  have hw : ∀ a, i.hom (f.hom a) = j.hom (g.hom a) := fun a ↦ congrArg (fun φ ↦ φ.hom a) w
  have key : ∀ s : PushoutCocone f g, ∃ m : P ⟶ s.pt, i ≫ m = s.inl ∧ j ≫ m = s.inr := by
    intro s
    have hcond : ∀ a, s.inl.hom (f.hom a) = s.inr.hom (g.hom a) := fun a ↦
      congrArg (fun φ : A ⟶ s.pt ↦ φ.hom a) s.condition
    have hkill : ∀ x ∈ RingHom.ker i.hom, s.inl.hom x = 0 := by
      intro x hx
      have hle : Ideal.map f.hom (RingHom.ker g.hom) ≤ RingHom.ker s.inl.hom := by
        rw [Ideal.map_le_iff_le_comap]
        intro y hy
        rw [Ideal.mem_comap, RingHom.mem_ker, hcond, RingHom.mem_ker.mp hy, map_zero]
      exact RingHom.mem_ker.mp (hle (hker hx))
    refine ⟨CommRingCat.ofHom ((Ideal.Quotient.lift _ s.inl.hom hkill).comp
      (RingHom.quotientKerEquivOfSurjective hi).symm.toRingHom), ?_, ?_⟩
    · refine CommRingCat.hom_ext (RingHom.ext fun b ↦ ?_)
      change (Ideal.Quotient.lift _ s.inl.hom hkill)
        ((RingHom.quotientKerEquivOfSurjective hi).symm (i.hom b)) = s.inl.hom b
      rw [RingHom.quotientKerEquivOfSurjective_symm_apply, Ideal.Quotient.lift_mk]
    · refine CommRingCat.hom_ext (RingHom.ext fun c ↦ ?_)
      obtain ⟨a, rfl⟩ := hg c
      change (Ideal.Quotient.lift _ s.inl.hom hkill)
        ((RingHom.quotientKerEquivOfSurjective hi).symm (j.hom (g.hom a))) = s.inr.hom (g.hom a)
      rw [← hw a, RingHom.quotientKerEquivOfSurjective_symm_apply, Ideal.Quotient.lift_mk,
        hcond]
  refine ⟨⟨w⟩, ⟨PushoutCocone.IsColimit.mk w (fun s ↦ (key s).choose)
    (fun s ↦ (key s).choose_spec.1) (fun s ↦ (key s).choose_spec.2) ?_⟩⟩
  intro s m h₁ _
  refine CommRingCat.hom_ext (RingHom.ext fun p ↦ ?_)
  obtain ⟨b, rfl⟩ := hi p
  have e₁ : m.hom (i.hom b) = s.inl.hom b := congrArg (fun φ : B ⟶ s.pt ↦ φ.hom b) h₁
  have e₂ : (key s).choose.hom (i.hom b) = s.inl.hom b :=
    congrArg (fun φ : B ⟶ s.pt ↦ φ.hom b) (key s).choose_spec.1
  rw [e₁, e₂]

end PushoutCriterion


/-! ### The special fibre as a cartesian square -/

section Fibres

variable (R : Type u) [CommRing R] (I : Ideal R)

/-- The origin `Spec R ⟶ 𝔸¹_R = Spec R[u]` of the affine line. -/
def origin : Spec (.of R) ⟶ Spec (.of (Polynomial R)) :=
  Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : R)))

/-- The point `u = 1` of the affine line. -/
def pointOne : Spec (.of R) ⟶ Spec (.of (Polynomial R)) :=
  Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (1 : R)))

/-- The structure map of the special fibre down to `Spec R`. -/
def specialFibreBaseHom : R →+* specialFibreRing R I :=
  (Ideal.Quotient.mk (parameterIdeal R I)).comp (algebraMap R (extendedRees R I))

/-- The structure map of the fibre over `u = 1` down to `Spec R`. -/
def fibreOneBaseHom : R →+* extendedRees R I ⧸ fibreOneIdeal R I :=
  (Ideal.Quotient.mk (fibreOneIdeal R I)).comp (algebraMap R (extendedRees R I))

theorem mk_comp_structureMap :
    (Ideal.Quotient.mk (parameterIdeal R I)).comp (structureMap R I).toRingHom =
      (specialFibreBaseHom R I).comp (Polynomial.evalRingHom (0 : R)) := by
  refine Polynomial.ringHom_ext (fun a ↦ ?_) ?_
  · have h : (structureMap R I).toRingHom (Polynomial.C a) =
        algebraMap R (extendedRees R I) a := by
      rw [Polynomial.C_eq_algebraMap]
      exact (structureMap R I).commutes a
    rw [RingHom.comp_apply, RingHom.comp_apply, h]
    simp [specialFibreBaseHom]
  · rw [RingHom.comp_apply, RingHom.comp_apply, show
      (Polynomial.evalRingHom (0 : R)) Polynomial.X = 0 by simp, map_zero]
    change Ideal.Quotient.mk _ (structureMap R I Polynomial.X) = 0
    rw [structureMap_X, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.subset_span rfl

theorem map_ker_evalRingHom_zero :
    Ideal.map (structureMap R I).toRingHom (RingHom.ker (Polynomial.evalRingHom (0 : R))) =
      parameterIdeal R I := by
  rw [Polynomial.ker_evalRingHom, Ideal.map_span, Set.image_singleton]
  congr 1
  change {(structureMap R I) (Polynomial.X - Polynomial.C 0)} = _
  rw [map_zero, sub_zero, structureMap_X]

theorem mk_comp_structureMap_one :
    (Ideal.Quotient.mk (fibreOneIdeal R I)).comp (structureMap R I).toRingHom =
      (fibreOneBaseHom R I).comp (Polynomial.evalRingHom (1 : R)) := by
  refine Polynomial.ringHom_ext (fun a ↦ ?_) ?_
  · have h : (structureMap R I).toRingHom (Polynomial.C a) =
        algebraMap R (extendedRees R I) a := by
      rw [Polynomial.C_eq_algebraMap]
      exact (structureMap R I).commutes a
    rw [RingHom.comp_apply, RingHom.comp_apply, h]
    simp [fibreOneBaseHom]
  · rw [RingHom.comp_apply, RingHom.comp_apply, show
      (Polynomial.evalRingHom (1 : R)) Polynomial.X = 1 by simp, map_one]
    change Ideal.Quotient.mk _ (structureMap R I Polynomial.X) = 1
    rw [structureMap_X, ← map_one (Ideal.Quotient.mk (fibreOneIdeal R I)),
      Ideal.Quotient.mk_eq_mk_iff_sub_mem]
    exact Ideal.subset_span rfl

theorem map_ker_evalRingHom_one :
    Ideal.map (structureMap R I).toRingHom (RingHom.ker (Polynomial.evalRingHom (1 : R))) =
      fibreOneIdeal R I := by
  rw [Polynomial.ker_evalRingHom, Ideal.map_span, Set.image_singleton]
  congr 1
  change {(structureMap R I) (Polynomial.X - Polynomial.C 1)} = _
  rw [map_sub, structureMap_X, Polynomial.C_eq_algebraMap, AlgHom.commutes, map_one]

/-- The projection of the special fibre of the deformation space to `Spec R`. -/
def specialFibreToBase : specialFibre R I ⟶ Spec (.of R) :=
  Spec.map (CommRingCat.ofHom (specialFibreBaseHom R I))

/-- The projection of the fibre over `u = 1` to `Spec R`. -/
def fibreOneToBase : fibreOne R I ⟶ Spec (.of R) :=
  Spec.map (CommRingCat.ofHom (fibreOneBaseHom R I))

/-- The special fibre of `M° → 𝔸¹` over the origin is `Spec (gr_I R)`: the defining cartesian
square of the deformation to the normal cone. -/
theorem specialFibre_isPullback :
    IsPullback (specialFibreι R I) (specialFibreToBase R I) (toLine R I) (origin R) :=
  isPullback_SpecMap_of_isPushout _ _ _ _
    (isPushout_of_surjective _ _ _ _
      (CommRingCat.hom_ext (mk_comp_structureMap R I))
      (fun r ↦ ⟨Polynomial.C r, by simp⟩) Ideal.Quotient.mk_surjective
      (by
        simp only [CommRingCat.hom_ofHom, Ideal.mk_ker]
        exact (map_ker_evalRingHom_zero R I).ge))

/-- The fibre of `M° → 𝔸¹` over the point `u = 1` is `Spec R`. -/
theorem fibreOne_isPullback :
    IsPullback (fibreOneι R I) (fibreOneToBase R I) (toLine R I) (pointOne R) :=
  isPullback_SpecMap_of_isPushout _ _ _ _
    (isPushout_of_surjective _ _ _ _
      (CommRingCat.hom_ext (mk_comp_structureMap_one R I))
      (fun r ↦ ⟨Polynomial.C r, by simp⟩) Ideal.Quotient.mk_surjective
      (by
        simp only [CommRingCat.hom_ofHom, Ideal.mk_ker]
        exact (map_ker_evalRingHom_one R I).ge))

/-- The projection of the affine normal cone, viewed as the special fibre, to `Spec R`. -/
def normalConeToBase : AffineNormalCone.scheme R I ⟶ Spec (.of R) :=
  (normalConeIsoSpecialFibre R I).hom ≫ specialFibreToBase R I

/-- The cartesian square identifying the affine normal cone with the fibre of the deformation
space over the origin of the affine line. -/
theorem normalCone_isPullback :
    IsPullback (normalConeι R I) (normalConeToBase R I) (toLine R I) (origin R) := by
  refine (specialFibre_isPullback R I).of_iso (normalConeIsoSpecialFibre R I).symm
    (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_ (by simp) (by simp)
  · simp [normalConeι]
  · simp [normalConeToBase]

/-- The cartesian square identifying the fibre of the deformation space over `u = 1` with
`Spec R` itself. -/
theorem fibreOne_isPullback_spec :
    IsPullback ((fibreOneIso R I).inv ≫ fibreOneι R I)
      ((fibreOneIso R I).inv ≫ fibreOneToBase R I) (toLine R I) (pointOne R) := by
  refine (fibreOne_isPullback R I).of_iso (fibreOneIso R I) (Iso.refl _) (Iso.refl _)
    (Iso.refl _) (by simp) (by simp) (by simp) (by simp)

end Fibres


/-! ### The generic fibre as a cartesian square -/

section GenericFibre

variable (R : Type u) [CommRing R] (I : Ideal R)

/-- The open immersion `𝔾ₘ = Spec R[u, u⁻¹] ⟶ 𝔸¹_R = Spec R[u]`. -/
def gmToLine : Spec (.of R[T;T⁻¹]) ⟶ Spec (.of (Polynomial R)) :=
  Spec.map (CommRingCat.ofHom (algebraMap (Polynomial R) R[T;T⁻¹]))

/-- The projection of the trivial family `Spec R × 𝔾ₘ = Spec R[t, t⁻¹]` to `𝔾ₘ`, given by
`u = t⁻¹`. -/
def genericFibreToGm : genericFibre R ⟶ Spec (.of R[T;T⁻¹]) :=
  Spec.map (CommRingCat.ofHom (invert (R := R)).toRingHom)

theorem map_powers_structureMap :
    Submonoid.map ((structureMap R I).toRingHom : Polynomial R →+* extendedRees R I)
        (Submonoid.powers (Polynomial.X : Polynomial R)) =
      Submonoid.powers (parameter R I) := by
  rw [Submonoid.map_powers]
  exact congrArg Submonoid.powers (structureMap_X R I)

/-- The part of the deformation space lying over `𝔾ₘ ⊆ 𝔸¹` is the trivial family
`Spec R × 𝔾ₘ`: the second defining cartesian square of the deformation to the normal cone. -/
theorem genericFibre_isPullback :
    IsPullback (genericFibreι R I) (genericFibreToGm R) (toLine R I) (gmToLine R) := by
  have h : Submonoid.map ((structureMap R I).toRingHom : Polynomial R →+* extendedRees R I)
      (Submonoid.powers (Polynomial.X : Polynomial R)) = Submonoid.powers (parameter R I) :=
    map_powers_structureMap R I
  have hloc : IsLocalization (Submonoid.map
      ((structureMap R I).toRingHom : Polynomial R →+* extendedRees R I)
      (Submonoid.powers (Polynomial.X : Polynomial R))) R[T;T⁻¹] := by
    rw [h]
    exact isLocalization_parameter R I
  have hcomm : (invert (R := R)).toRingHom.comp (algebraMap (Polynomial R) R[T;T⁻¹]) =
      (algebraMap (extendedRees R I) R[T;T⁻¹]).comp (structureMap R I).toRingHom := by
    refine RingHom.ext fun p ↦ ?_
    exact (coe_structureMap R I p).symm
  exact isPullback_SpecMap_of_isPushout _ _ _ _
    (CommRingCat.isPushout_of_isLocalization (structureMap R I).toRingHom
      (invert (R := R)).toRingHom hcomm (Submonoid.powers (Polynomial.X : Polynomial R)))

end GenericFibre



/-! ### Coefficientwise base change of Laurent polynomials -/

section MapLaurent

variable {R S : Type u} [CommRing R] [CommRing S] (φ : R →+* S)

/-- Coefficientwise extension of Laurent polynomials along a ring homomorphism. -/
def mapLaurent : R[T;T⁻¹] →+* S[T;T⁻¹] :=
  IsLocalization.map (M := Submonoid.powers (Polynomial.X : Polynomial R)) _
    (Polynomial.mapRingHom φ)
    (by
      rw [Submonoid.powers_le, Submonoid.mem_comap, Polynomial.coe_mapRingHom,
        Polynomial.map_X]
      exact Submonoid.mem_powers _)

theorem mapLaurent_toLaurent (p : Polynomial R) :
    mapLaurent φ (Polynomial.toLaurent p) = Polynomial.toLaurent (p.map φ) :=
  IsLocalization.map_eq (M := Submonoid.powers (Polynomial.X : Polynomial R))
    (S := R[T;T⁻¹]) (Q := S[T;T⁻¹]) (g := Polynomial.mapRingHom φ) _ p

theorem mapLaurent_T (m : ℕ) : mapLaurent φ (T (m : ℤ)) = T (m : ℤ) := by
  rw [← Polynomial.toLaurent_X_pow, mapLaurent_toLaurent, Polynomial.map_pow,
    Polynomial.map_X, Polynomial.toLaurent_X_pow]

theorem mapLaurent_C_mul_T (a : R) (n : ℤ) :
    mapLaurent φ (LaurentPolynomial.C a * T n) = LaurentPolynomial.C (φ a) * T n := by
  obtain ⟨m, hm⟩ : ∃ m : ℕ, 0 ≤ n + (m : ℤ) := ⟨n.natAbs, by omega⟩
  obtain ⟨k, hk⟩ : ∃ k : ℕ, n + (m : ℤ) = (k : ℤ) := ⟨(n + m).toNat, by omega⟩
  have hL : mapLaurent φ (LaurentPolynomial.C a * T n) * T (m : ℤ) =
      LaurentPolynomial.C (φ a) * T (k : ℤ) := by
    rw [← mapLaurent_T φ m, ← map_mul, mul_T_assoc, hk, ← Polynomial.toLaurent_C_mul_T,
      mapLaurent_toLaurent, Polynomial.map_monomial, Polynomial.toLaurent_C_mul_T]
  have hR : LaurentPolynomial.C (φ a) * T n * T (m : ℤ) =
      LaurentPolynomial.C (φ a) * T (k : ℤ) := by
    rw [mul_T_assoc, hk]
  exact (isUnit_T (m : ℤ)).mul_right_cancel (hL.trans hR.symm)

theorem mapLaurent_C (a : R) :
    mapLaurent φ (LaurentPolynomial.C a) = LaurentPolynomial.C (φ a) := by
  simpa using mapLaurent_C_mul_T φ a 0

theorem coeff_mapLaurent (g : R[T;T⁻¹]) (n : ℤ) :
    (mapLaurent φ g).coeff n = φ (g.coeff n) := by
  induction g using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [map_add, AddMonoidAlgebra.coeff_add, AddMonoidAlgebra.coeff_add,
      Finsupp.add_apply, Finsupp.add_apply, hp, hq, map_add]
  | C_mul_T m a =>
    rw [mapLaurent_C_mul_T, ← single_eq_C_mul_T, ← single_eq_C_mul_T,
      AddMonoidAlgebra.coeff_single, AddMonoidAlgebra.coeff_single, Finsupp.single_apply,
      Finsupp.single_apply]
    split_ifs with h
    · rfl
    · exact (map_zero _).symm

end MapLaurent

/-! ### Polynomials in `u = t⁻¹` inside the Laurent polynomials -/

section NonPos

variable (S : Type u) [CommRing S]

/-- The embedding of `S[u]` into `S[t, t⁻¹]` as the non-positive part, `u ↦ t⁻¹`. -/
def nonPosHom : Polynomial S →+* S[T;T⁻¹] :=
  ((invert (R := S)).toRingEquiv.toRingHom).comp Polynomial.toLaurent

/-- The additive retraction of `nonPosHom`, keeping only the non-positive powers of `t`. -/
def nonPosRetract : S[T;T⁻¹] →+ Polynomial S :=
  LaurentPolynomial.trunc.comp
    (((invert (R := S)).toRingEquiv.toRingHom : S[T;T⁻¹] →+* S[T;T⁻¹]).toAddMonoidHom)

theorem nonPosHom_apply (p : Polynomial S) :
    nonPosHom S p = invert (Polynomial.toLaurent p) := rfl

theorem nonPosRetract_apply (g : S[T;T⁻¹]) :
    nonPosRetract S g = LaurentPolynomial.trunc (invert g) := rfl

@[simp]
theorem nonPosRetract_nonPosHom (p : Polynomial S) : nonPosRetract S (nonPosHom S p) = p := by
  rw [nonPosRetract_apply, nonPosHom_apply, involutive_invert _, Polynomial.trunc_toLaurent]

theorem nonPosHom_injective : Function.Injective (nonPosHom S) :=
  Function.LeftInverse.injective (g := nonPosRetract S) (nonPosRetract_nonPosHom S)

theorem nonPosHom_monomial (m : ℕ) (c : S) :
    nonPosHom S (Polynomial.monomial m c) = LaurentPolynomial.C c * T (-(m : ℤ)) := by
  rw [nonPosHom_apply, Polynomial.toLaurent_C_mul_T, map_mul, invert_C, invert_T]

theorem nonPosRetract_C_mul_T (c : S) (n : ℤ) :
    nonPosRetract S (LaurentPolynomial.C c * T n) =
      if 0 ≤ -n then Polynomial.monomial (-n).toNat c else 0 := by
  rw [nonPosRetract_apply, map_mul, invert_C, invert_T, trunc_C_mul_T]

end NonPos

/-! ### The deformation of the closed subscheme -/

section Subscheme

variable (R : Type u) [CommRing R] (I : Ideal R)

/-- Reduction of the coefficients of a Laurent polynomial modulo the ideal `I`. -/
def reduceLaurent : R[T;T⁻¹] →+* (R ⧸ I)[T;T⁻¹] := mapLaurent (Ideal.Quotient.mk I)

theorem reduceLaurent_C_mul_T (a : R) (n : ℤ) :
    reduceLaurent R I (LaurentPolynomial.C a * T n) =
      LaurentPolynomial.C (Ideal.Quotient.mk I a) * T n :=
  mapLaurent_C_mul_T _ a n

theorem coeff_reduceLaurent (g : R[T;T⁻¹]) (n : ℤ) :
    (reduceLaurent R I g).coeff n = Ideal.Quotient.mk I (g.coeff n) :=
  coeff_mapLaurent _ g n

/-- The image of the extended Rees algebra under reduction modulo `I` consists of polynomials
in `u = t⁻¹`. -/
theorem nonPosHom_nonPosRetract_reduceLaurent {g : R[T;T⁻¹]} (hg : g ∈ extendedRees R I) :
    nonPosHom (R ⧸ I) (nonPosRetract (R ⧸ I) (reduceLaurent R I g)) = reduceLaurent R I g := by
  rw [eq_sum_support R g]
  simp only [map_sum]
  refine Finset.sum_congr rfl fun n _ ↦ ?_
  rw [reduceLaurent_C_mul_T]
  rcases le_or_gt n 0 with hn | hn
  · rw [nonPosRetract_C_mul_T, if_pos (by omega), nonPosHom_monomial,
      show (-((-n).toNat : ℤ)) = n by omega]
  · have h0 : Ideal.Quotient.mk I (g.coeff n) = 0 := by
      rw [Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.pow_le_self (by omega) (coeff_mem_of_mem R I hg n)
    rw [h0, map_zero, zero_mul, map_zero, map_zero]

/-- The coordinate ring map of the deformation `Spec (R/I) × 𝔸¹ ⊆ M°` of the closed subscheme
`Spec (R/I) ⊆ Spec R`: reduce the coefficients modulo `I` and keep the powers of `u = t⁻¹`. -/
def subschemeHom : extendedRees R I →+* Polynomial (R ⧸ I) where
  toFun f := nonPosRetract (R ⧸ I) (reduceLaurent R I (f : R[T;T⁻¹]))
  map_one' := by
    refine nonPosHom_injective (R ⧸ I) ?_
    rw [nonPosHom_nonPosRetract_reduceLaurent R I (1 : extendedRees R I).2,
      OneMemClass.coe_one, map_one, map_one]
  map_mul' f g := by
    refine nonPosHom_injective (R ⧸ I) ?_
    rw [map_mul, nonPosHom_nonPosRetract_reduceLaurent R I (f * g).2,
      nonPosHom_nonPosRetract_reduceLaurent R I f.2,
      nonPosHom_nonPosRetract_reduceLaurent R I g.2, MulMemClass.coe_mul, map_mul]
  map_zero' := by
    change nonPosRetract (R ⧸ I) (reduceLaurent R I ((0 : extendedRees R I) : R[T;T⁻¹])) = 0
    rw [ZeroMemClass.coe_zero, map_zero, map_zero]
  map_add' f g := by
    change nonPosRetract (R ⧸ I)
      (reduceLaurent R I ((f + g : extendedRees R I) : R[T;T⁻¹])) = _
    rw [AddMemClass.coe_add, map_add, map_add]

theorem subschemeHom_apply (f : extendedRees R I) :
    subschemeHom R I f = nonPosRetract (R ⧸ I) (reduceLaurent R I (f : R[T;T⁻¹])) := rfl

theorem nonPosHom_subschemeHom (f : extendedRees R I) :
    nonPosHom (R ⧸ I) (subschemeHom R I f) = reduceLaurent R I (f : R[T;T⁻¹]) :=
  nonPosHom_nonPosRetract_reduceLaurent R I f.2

theorem subschemeHom_surjective : Function.Surjective (subschemeHom R I) := by
  intro p
  induction p using Polynomial.induction_on' with
  | add p q hp hq =>
    obtain ⟨f, rfl⟩ := hp
    obtain ⟨g, rfl⟩ := hq
    exact ⟨f + g, map_add _ _ _⟩
  | monomial m c =>
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective c
    refine ⟨⟨LaurentPolynomial.C a * T (-(m : ℤ)),
      isExtendedRees_of_nonpos R I (by omega)⟩, ?_⟩
    rw [subschemeHom_apply]
    change nonPosRetract (R ⧸ I) (reduceLaurent R I (LaurentPolynomial.C a * T (-(m : ℤ)))) = _
    rw [reduceLaurent_C_mul_T, nonPosRetract_C_mul_T, if_pos (by omega),
      show (-(-(m : ℤ))).toNat = m by omega]

/-- The deformation `Spec (R/I) × 𝔸¹ = Spec ((R/I)[u])` of the closed subscheme. -/
abbrev subschemeSpace : Scheme.{u} := Spec (.of (Polynomial (R ⧸ I)))

/-- The closed immersion of the deformation of the closed subscheme into the deformation
space. -/
def subschemeι : subschemeSpace R I ⟶ space R I :=
  Spec.map (CommRingCat.ofHom (subschemeHom R I))

instance subschemeι_isClosedImmersion : IsClosedImmersion (subschemeι R I) :=
  IsClosedImmersion.spec_of_surjective _ (subschemeHom_surjective R I)

/-- The deformation of the closed subscheme is compatible with the projections to `𝔸¹`. -/
theorem subschemeHom_comp_structureMap :
    (subschemeHom R I).comp (structureMap R I).toRingHom =
      Polynomial.mapRingHom (Ideal.Quotient.mk I) := by
  refine Polynomial.ringHom_ext (fun a ↦ ?_) ?_
  · refine nonPosHom_injective (R ⧸ I) ?_
    rw [RingHom.comp_apply, nonPosHom_subschemeHom]
    have h : (((structureMap R I).toRingHom (Polynomial.C a) : extendedRees R I) : R[T;T⁻¹]) =
        LaurentPolynomial.C a * T 0 := by
      have h1 : (structureMap R I) (Polynomial.C a) = algebraMap R (extendedRees R I) a := by
        rw [Polynomial.C_eq_algebraMap]
        exact (structureMap R I).commutes a
      change ((structureMap R I) (Polynomial.C a) : R[T;T⁻¹]) = _
      rw [h1, T_zero, mul_one]
      exact (C_eq_algebraMap a).symm
    rw [h, reduceLaurent_C_mul_T, Polynomial.coe_mapRingHom, Polynomial.map_C,
      nonPosHom_apply, Polynomial.toLaurent_C, T_zero, mul_one, invert_C]
  · refine nonPosHom_injective (R ⧸ I) ?_
    rw [RingHom.comp_apply, nonPosHom_subschemeHom]
    have hX : (((structureMap R I).toRingHom Polynomial.X : extendedRees R I) : R[T;T⁻¹]) =
        LaurentPolynomial.C 1 * T (-1) := by
      change ((structureMap R I) Polynomial.X : R[T;T⁻¹]) = _
      rw [structureMap_X, coe_parameter, map_one, one_mul]
    rw [hX, reduceLaurent_C_mul_T, Polynomial.coe_mapRingHom, Polynomial.map_X,
      nonPosHom_apply, Polynomial.toLaurent_X, invert_T]
    simp

/-- The projection of the deformation of the closed subscheme to the affine line. -/
theorem subschemeι_comp_toLine :
    subschemeι R I ≫ toLine R I =
      Spec.map (CommRingCat.ofHom (Polynomial.mapRingHom (Ideal.Quotient.mk I))) := by
  rw [subschemeι, toLine, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
    subschemeHom_comp_structureMap]


/-! ### The special fibre of the deformed subscheme is the vertex of the normal cone -/

theorem coeff_zero_toLaurent (p : Polynomial R) :
    (Polynomial.toLaurent p).coeff (0 : ℤ) = p.coeff 0 := by
  have h : (Polynomial.toLaurent p).coeff ((0 : ℕ) : ℤ) = p.coeff 0 := by
    rw [LaurentPolynomial.coeff_toLaurent]
    exact Finsupp.mapDomain_apply Nat.castEmbedding.injective _ 0
  simpa using h

theorem coeff_zero_subschemeHom (f : extendedRees R I) :
    (subschemeHom R I f).coeff 0 = Ideal.Quotient.mk I ((f : R[T;T⁻¹]).coeff 0) := by
  have h := nonPosHom_subschemeHom R I f
  have h0 : (nonPosHom (R ⧸ I) (subschemeHom R I f)).coeff (0 : ℤ) =
      (subschemeHom R I f).coeff 0 := by
    rw [nonPosHom_apply, invert_apply, neg_zero]
    exact coeff_zero_toLaurent (R ⧸ I) _
  rw [← h0, h, coeff_reduceLaurent]

theorem evalZero_subschemeHom (f : extendedRees R I) :
    Polynomial.evalRingHom (0 : R ⧸ I) (subschemeHom R I f) =
      Ideal.Quotient.mk I ((f : R[T;T⁻¹]).coeff 0) := by
  rw [Polynomial.coe_evalRingHom, ← Polynomial.coeff_zero_eq_eval_zero]
  exact coeff_zero_subschemeHom R I f

/-- The augmentation of the special fibre of the deformation space, transported from the
augmentation of the associated graded ring along the special-fibre identification. -/
def specialFibreAugmentation : specialFibreRing R I →+* R ⧸ I :=
  (AffineNormalCone.associatedGradedAugmentation R I).comp
    (specialFibreEquiv R I).toRingEquiv.symm.toRingHom

theorem specialFibreAugmentation_rees (q : reesAlgebra I) :
    specialFibreAugmentation R I (reesToSpecialFibre R I q) =
      Ideal.Quotient.mk I ((q : Polynomial R).coeff 0) := by
  have h : (specialFibreEquiv R I).symm (reesToSpecialFibre R I q) =
      Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I) q := by
    rw [← specialFibreEquiv_mk R I q, AlgEquiv.symm_apply_apply]
  change AffineNormalCone.associatedGradedAugmentation R I ((specialFibreEquiv R I).symm _) = _
  rw [h, AffineNormalCone.associatedGradedAugmentation_mk]

/-- The coordinate-ring identity expressing that the special fibre of the deformed closed
subscheme is the vertex of the normal cone. -/
theorem subschemeHom_specialFibre :
    (Polynomial.evalRingHom (0 : R ⧸ I)).comp (subschemeHom R I) =
      (specialFibreAugmentation R I).comp (Ideal.Quotient.mk (parameterIdeal R I)) := by
  have hp : (parameter R I : R[T;T⁻¹]).coeff 0 = 0 := by
    rw [coe_parameter, ← one_mul (T (-1) : R[T;T⁻¹]), ← map_one (LaurentPolynomial.C (R := R)),
      ← single_eq_C_mul_T, AddMonoidAlgebra.coeff_single, Finsupp.single_apply, if_neg (by decide)]
  have hpar : Polynomial.evalRingHom (0 : R ⧸ I) (subschemeHom R I (parameter R I)) = 0 := by
    rw [evalZero_subschemeHom, hp, map_zero]
  have hkill : ∀ x ∈ parameterIdeal R I,
      Polynomial.evalRingHom (0 : R ⧸ I) (subschemeHom R I x) = 0 := by
    intro x hx
    obtain ⟨y, rfl⟩ := Ideal.mem_span_singleton'.mp hx
    rw [map_mul, map_mul, hpar, mul_zero]
  refine RingHom.ext fun f ↦ ?_
  obtain ⟨q, hq⟩ := reesToSpecialFibre_surjective R I (Ideal.Quotient.mk (parameterIdeal R I) f)
  have hsub : f - reesToExtended R I q ∈ parameterIdeal R I := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, sub_eq_zero]
    rw [← reesToSpecialFibre_apply R I q, hq]
  have hzero := hkill _ hsub
  rw [map_sub, map_sub, sub_eq_zero] at hzero
  rw [RingHom.comp_apply, RingHom.comp_apply, hzero, evalZero_subschemeHom, coe_reesToExtended,
    coeff_zero_toLaurent, ← hq, specialFibreAugmentation_rees]

/-- The vertex of the special fibre of the deformation space. -/
def specialFibreVertex : Spec (.of (R ⧸ I)) ⟶ specialFibre R I :=
  Spec.map (CommRingCat.ofHom (specialFibreAugmentation R I))

/-- The special-fibre identification carries the vertex of the affine normal cone to the
vertex of the special fibre. -/
theorem vertex_comp_normalConeIso :
    AffineNormalCone.vertex R I ≫ (normalConeIsoSpecialFibre R I).hom =
      specialFibreVertex R I := by
  rw [normalConeIsoSpecialFibre, specialFibreVertex]
  simp only [Functor.mapIso_hom, Iso.op_hom, Iso.symm_hom, RingEquiv.toCommRingCatIso_inv,
    Scheme.Spec_map, Quiver.Hom.unop_op, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
  rfl

/-- The deformation of the closed subscheme meets the special fibre in the vertex of the
affine normal cone. -/
theorem origin_comp_subschemeι :
    origin (R ⧸ I) ≫ subschemeι R I =
      AffineNormalCone.vertex R I ≫ normalConeι R I := by
  rw [normalConeι, ← Category.assoc, vertex_comp_normalConeIso, origin, subschemeι,
    specialFibreVertex, specialFibreι, ← Spec.map_comp, ← Spec.map_comp,
    ← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp, subschemeHom_specialFibre]

end Subscheme


/-! ### Flat base change of the deformation space -/

section BaseChange

variable (R : Type u) [CommRing R] (I : Ideal R) (B : Type u) [CommRing B] [Algebra R B]

/-- Coefficientwise base change of Laurent polynomials, as an `R`-algebra map. -/
def mapLaurentAlg : R[T;T⁻¹] →ₐ[R] B[T;T⁻¹] where
  __ := mapLaurent (algebraMap R B)
  commutes' r := by
    rw [← C_eq_algebraMap]
    change mapLaurent (algebraMap R B) (LaurentPolynomial.C r) = _
    rw [mapLaurent_C, IsScalarTower.algebraMap_apply R B B[T;T⁻¹], ← C_eq_algebraMap]

theorem mapLaurentAlg_apply (g : R[T;T⁻¹]) :
    mapLaurentAlg R B g = mapLaurent (algebraMap R B) g := rfl

/-- The comparison map from the scalar extension of the Laurent polynomials. -/
def laurentTensorMap : R[T;T⁻¹] ⊗[R] B →ₐ[R] B[T;T⁻¹] :=
  Algebra.TensorProduct.lift (mapLaurentAlg R B)
    ((Algebra.ofId B B[T;T⁻¹]).restrictScalars R) fun _ _ ↦ Commute.all _ _

theorem laurentTensorMap_tmul (g : R[T;T⁻¹]) (b : B) :
    laurentTensorMap R B (g ⊗ₜ[R] b) =
      mapLaurent (algebraMap R B) g * LaurentPolynomial.C b := by
  rw [laurentTensorMap, Algebra.TensorProduct.lift_tmul]
  rfl

/-- The scalar extension of the Laurent polynomials, as an `R`-linear equivalence, through the
identification of `R[t, t⁻¹]` with the finitely supported functions `ℤ →₀ R`. -/
def laurentTensorEquiv : R[T;T⁻¹] ⊗[R] B ≃ₗ[R] B[T;T⁻¹] :=
  (TensorProduct.congr (AddMonoidAlgebra.coeffLinearEquiv R) (LinearEquiv.refl R B)) ≪≫ₗ
    TensorProduct.finsuppScalarLeft R B ℤ ≪≫ₗ (AddMonoidAlgebra.coeffLinearEquiv R).symm

theorem laurentTensorMap_eq :
    (laurentTensorMap R B).toLinearMap = (laurentTensorEquiv R B).toLinearMap := by
  refine TensorProduct.ext' fun g b ↦ ?_
  refine AddMonoidAlgebra.coeff_injective ?_
  ext i
  have hl : (laurentTensorMap R B (g ⊗ₜ[R] b)).coeff i =
      b * algebraMap R B (g.coeff i) := by
    rw [laurentTensorMap_tmul, mul_comm, ← smul_eq_C_mul, AddMonoidAlgebra.coeff_smul_apply,
      coeff_mapLaurent, smul_eq_mul]
  have hr : (laurentTensorEquiv R B (g ⊗ₜ[R] b)).coeff i = g.coeff i • b := by
    rw [laurentTensorEquiv]
    change ((AddMonoidAlgebra.coeffLinearEquiv R).symm
      (TensorProduct.finsuppScalarLeft R B ℤ (g.coeff ⊗ₜ[R] b))).coeff i = _
    rw [AddMonoidAlgebra.coeffLinearEquiv_symm_apply,
      TensorProduct.finsuppScalarLeft_apply_tmul_apply]
  change (laurentTensorMap R B (g ⊗ₜ[R] b)).coeff i = (laurentTensorEquiv R B (g ⊗ₜ[R] b)).coeff i
  rw [hl, hr, Algebra.smul_def, mul_comm]

theorem laurentTensorMap_injective : Function.Injective (laurentTensorMap R B) := by
  have h : ⇑(laurentTensorMap R B) = ⇑(laurentTensorEquiv R B) :=
    congrArg (fun f : (R[T;T⁻¹] ⊗[R] B) →ₗ[R] B[T;T⁻¹] ↦ ⇑f) (laurentTensorMap_eq R B)
  rw [h]
  exact (laurentTensorEquiv R B).injective


theorem mapLaurent_mem_extendedRees {g : R[T;T⁻¹]} (hg : g ∈ extendedRees R I) :
    mapLaurent (algebraMap R B) g ∈ extendedRees B (I.map (algebraMap R B)) := by
  intro n
  rw [coeff_mapLaurent, ← Ideal.map_pow]
  exact Ideal.mem_map_of_mem _ (hg n)

/-- Coefficientwise base change of the extended Rees algebra. -/
def reesBaseChangeHom : extendedRees R I →+* extendedRees B (I.map (algebraMap R B)) :=
  RingHom.codRestrict ((mapLaurent (algebraMap R B)).comp (extendedRees R I).val.toRingHom) _
    fun f ↦ mapLaurent_mem_extendedRees R I B f.2

/-- The comparison map from the scalar extension of the extended Rees algebra to the Laurent
polynomials over `B`. -/
def reesTensorToLaurent : (extendedRees R I) ⊗[R] B →ₐ[R] B[T;T⁻¹] :=
  Algebra.TensorProduct.lift ((mapLaurentAlg R B).comp (extendedRees R I).val)
    ((Algebra.ofId B B[T;T⁻¹]).restrictScalars R) fun _ _ ↦ Commute.all _ _

theorem reesTensorToLaurent_tmul (x : extendedRees R I) (b : B) :
    reesTensorToLaurent R I B (x ⊗ₜ[R] b) =
      mapLaurent (algebraMap R B) (x : R[T;T⁻¹]) * LaurentPolynomial.C b := by
  rw [reesTensorToLaurent, Algebra.TensorProduct.lift_tmul]
  rfl

theorem reesTensorToLaurent_eq (z : (extendedRees R I) ⊗[R] B) :
    reesTensorToLaurent R I B z =
      laurentTensorMap R B (LinearMap.rTensor B (extendedRees R I).val.toLinearMap z) := by
  induction z using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero, map_zero]
  | tmul x b => rw [reesTensorToLaurent_tmul, LinearMap.rTensor_tmul, laurentTensorMap_tmul]; rfl
  | add x y hx hy => rw [map_add, map_add, map_add, hx, hy]

theorem reesTensorToLaurent_mem (z : (extendedRees R I) ⊗[R] B) :
    reesTensorToLaurent R I B z ∈ extendedRees B (I.map (algebraMap R B)) := by
  induction z using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact zero_mem _
  | tmul x b =>
    rw [reesTensorToLaurent_tmul, C_eq_algebraMap]
    exact mul_mem (mapLaurent_mem_extendedRees R I B x.2)
      ((extendedRees B (I.map (algebraMap R B))).algebraMap_mem b)
  | add x y hx hy => rw [map_add]; exact add_mem hx hy

theorem monomial_mem_range_reesTensorToLaurent (n : ℤ) {a : B}
    (ha : a ∈ Ideal.map (algebraMap R B) (I ^ n.toNat)) :
    LaurentPolynomial.C a * T n ∈ (reesTensorToLaurent R I B).range := by
  refine Submodule.span_induction
    (p := fun a _ ↦ LaurentPolynomial.C a * T n ∈ (reesTensorToLaurent R I B).range)
    ?_ ?_ ?_ ?_ ha
  · rintro _ ⟨c, hc, rfl⟩
    have hmem : LaurentPolynomial.C c * T n ∈ extendedRees R I :=
      (mem_extendedRees_iff R I _).mpr (isExtendedRees_C_mul_T R I hc)
    refine ⟨(⟨LaurentPolynomial.C c * T n, hmem⟩ : extendedRees R I) ⊗ₜ[R] (1 : B), ?_⟩
    change reesTensorToLaurent R I B
      ((⟨LaurentPolynomial.C c * T n, hmem⟩ : extendedRees R I) ⊗ₜ[R] (1 : B)) = _
    rw [reesTensorToLaurent_tmul]
    change mapLaurent (algebraMap R B) (LaurentPolynomial.C c * T n) * LaurentPolynomial.C 1 = _
    rw [mapLaurent_C_mul_T, map_one, mul_one]
  · rw [map_zero, zero_mul]
    exact zero_mem _
  · intro x y _ _ hx hy
    rw [map_add, add_mul]
    exact add_mem hx hy
  · intro c x _ hx
    have h : LaurentPolynomial.C (c • x) * T n =
        reesTensorToLaurent R I B ((1 : extendedRees R I) ⊗ₜ[R] c) *
          (LaurentPolynomial.C x * T n) := by
      rw [reesTensorToLaurent_tmul, OneMemClass.coe_one, map_one, one_mul, smul_eq_mul, map_mul,
        mul_assoc]
    rw [h]
    exact mul_mem (Set.mem_range_self _) hx

theorem extendedRees_le_range_reesTensorToLaurent {g : B[T;T⁻¹]}
    (hg : g ∈ extendedRees B (I.map (algebraMap R B))) :
    g ∈ (reesTensorToLaurent R I B).range := by
  rw [eq_sum_support B g]
  refine sum_mem fun n _ ↦ ?_
  refine monomial_mem_range_reesTensorToLaurent R I B n ?_
  rw [Ideal.map_pow]
  exact hg n

theorem reesTensorToLaurent_injective [Module.Flat R B] :
    Function.Injective (reesTensorToLaurent R I B) := by
  have h : Function.Injective (LinearMap.rTensor B (extendedRees R I).val.toLinearMap) :=
    Module.Flat.rTensor_preserves_injective_linearMap _ Subtype.val_injective
  intro z w hzw
  refine h ?_
  refine laurentTensorMap_injective R B ?_
  rw [← reesTensorToLaurent_eq, ← reesTensorToLaurent_eq, hzw]

/-- The comparison map from the scalar extension `R[It, t⁻¹] ⊗_R B` of the extended Rees algebra
to the extended Rees algebra `B[(IB)t, t⁻¹]` of the extended ideal. -/
def reesTensorMap : (extendedRees R I) ⊗[R] B →+* extendedRees B (I.map (algebraMap R B)) :=
  RingHom.codRestrict (reesTensorToLaurent R I B).toRingHom _ (reesTensorToLaurent_mem R I B)

theorem coe_reesTensorMap (z : (extendedRees R I) ⊗[R] B) :
    ((reesTensorMap R I B z : extendedRees B (I.map (algebraMap R B))) : B[T;T⁻¹]) =
      reesTensorToLaurent R I B z := rfl

/-- The comparison map is surjective for an arbitrary base change. -/
theorem reesTensorMap_surjective : Function.Surjective (reesTensorMap R I B) := by
  intro y
  obtain ⟨z, hz⟩ := extendedRees_le_range_reesTensorToLaurent R I B y.2
  exact ⟨z, Subtype.ext hz⟩

theorem reesTensorMap_bijective [Module.Flat R B] :
    Function.Bijective (reesTensorMap R I B) :=
  ⟨fun _ _ h ↦ reesTensorToLaurent_injective R I B (congrArg Subtype.val h),
    reesTensorMap_surjective R I B⟩

/-- Flat base change for the extended Rees algebra: for a flat `R`-algebra `B`, the scalar
extension of `R[It, t⁻¹]` is the extended Rees algebra of the extended ideal `IB`. -/
def reesTensorEquiv [Module.Flat R B] :
    (extendedRees R I) ⊗[R] B ≃+* extendedRees B (I.map (algebraMap R B)) :=
  RingEquiv.ofBijective (reesTensorMap R I B) (reesTensorMap_bijective R I B)

theorem reesTensorEquiv_apply [Module.Flat R B] (z : (extendedRees R I) ⊗[R] B) :
    reesTensorEquiv R I B z = reesTensorMap R I B z := rfl

/-- The base-change square of extended Rees algebras is a pushout of commutative rings. -/
theorem isPushout_reesBaseChange [Module.Flat R B] :
    IsPushout (CommRingCat.ofHom (algebraMap R (extendedRees R I)))
      (CommRingCat.ofHom (algebraMap R B))
      (CommRingCat.ofHom (reesBaseChangeHom R I B))
      (CommRingCat.ofHom (algebraMap B (extendedRees B (I.map (algebraMap R B))))) := by
  refine (CommRingCat.isPushout_tensorProduct R (extendedRees R I) B).of_iso (Iso.refl _)
    (Iso.refl _) (Iso.refl _) (reesTensorEquiv R I B).toCommRingCatIso (by simp) (by simp)
    ?_ ?_
  · refine CommRingCat.hom_ext (RingHom.ext fun x ↦ ?_)
    refine Subtype.ext ?_
    change (reesTensorToLaurent R I B (x ⊗ₜ[R] (1 : B)) : B[T;T⁻¹]) = _
    rw [reesTensorToLaurent_tmul, map_one, mul_one]
    rfl
  · refine CommRingCat.hom_ext (RingHom.ext fun b ↦ ?_)
    refine Subtype.ext ?_
    change (reesTensorToLaurent R I B ((1 : extendedRees R I) ⊗ₜ[R] b) : B[T;T⁻¹]) = _
    rw [reesTensorToLaurent_tmul, OneMemClass.coe_one, map_one, one_mul, C_eq_algebraMap]
    rfl

/-- Flat base change for the affine deformation space: the deformation space of `(B, IB)` is
the base change along `Spec B → Spec R` of the deformation space of `(R, I)`. -/
theorem reesBaseChange_isPullback [Module.Flat R B] :
    IsPullback (Spec.map (CommRingCat.ofHom (reesBaseChangeHom R I B)))
      (Spec.map (CommRingCat.ofHom
        (algebraMap B (extendedRees B (I.map (algebraMap R B))))))
      (Spec.map (CommRingCat.ofHom (algebraMap R (extendedRees R I))))
      (Spec.map (CommRingCat.ofHom (algebraMap R B))) :=
  isPullback_SpecMap_of_isPushout _ _ _ _ (isPushout_reesBaseChange R I B)

/-- Base change of the deformation space along a localization of the base, for instance
`B = R[1/f]`: this is the special case of flat base change that is used to globalise the
construction over an affine cover. -/
theorem reesBaseChange_isPullback_isLocalization (M : Submonoid R) [IsLocalization M B] :
    IsPullback (Spec.map (CommRingCat.ofHom (reesBaseChangeHom R I B)))
      (Spec.map (CommRingCat.ofHom
        (algebraMap B (extendedRees B (I.map (algebraMap R B))))))
      (Spec.map (CommRingCat.ofHom (algebraMap R (extendedRees R I))))
      (Spec.map (CommRingCat.ofHom (algebraMap R B))) :=
  have : Module.Flat R B := IsLocalization.flat B M
  reesBaseChange_isPullback R I B

end BaseChange

end AffineDeformationSpace

end


namespace ConeQuotient

open GradedCone

/-! ### Translation actions of a vector bundle along a bundle map -/

section BundleTranslation

variable {A N F : Type u} [CommRing A] [AddCommGroup N] [Module A N]
  [AddCommGroup F] [Module A F]

/-- The coaction of the vector bundle `E = Spec Sym(F)` on the vector bundle `Spec Sym(N)`
induced by a linear map `d : N →ₗ[A] F`: it is translation along the morphism of bundles
`E → Spec Sym(N)` determined by `d`. -/
noncomputable def bundleTranslationCoaction (d : N →ₗ[A] F) :
    SymmetricAlgebra A N →ₐ[A] SymmetricAlgebra A N ⊗[A] SymmetricAlgebra A F :=
  SymmetricAlgebra.lift
    ((Algebra.TensorProduct.includeLeft (R := A)
        (A := SymmetricAlgebra A N) (B := SymmetricAlgebra A F)).toLinearMap.comp
        (SymmetricAlgebra.ι A N) +
      (Algebra.TensorProduct.includeRight (R := A)
        (A := SymmetricAlgebra A N) (B := SymmetricAlgebra A F)).toLinearMap.comp
        ((SymmetricAlgebra.ι A F).comp d))

@[simp]
theorem bundleTranslationCoaction_ι (d : N →ₗ[A] F) (m : N) :
    bundleTranslationCoaction d (SymmetricAlgebra.ι A N m) =
      SymmetricAlgebra.ι A N m ⊗ₜ[A] 1 + 1 ⊗ₜ[A] SymmetricAlgebra.ι A F (d m) := by
  rw [bundleTranslationCoaction, SymmetricAlgebra.lift_ι_apply]
  rfl

variable {B : Type u} [CommRing B] [Algebra A B]

theorem translate_bundleTranslationCoaction_lift (d : N →ₗ[A] F) (m : N →ₗ[A] B)
    (l : F →ₗ[A] B) :
    translate (bundleTranslationCoaction d) (SymmetricAlgebra.lift m) l =
      SymmetricAlgebra.lift (m + l.comp d) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun x => ?_)
  simp [translate]

theorem translate_bundleTranslationCoaction (d : N →ₗ[A] F)
    (φ : SymmetricAlgebra A N →ₐ[A] B) (l : F →ₗ[A] B) :
    translate (bundleTranslationCoaction d) φ l =
      SymmetricAlgebra.lift (SymmetricAlgebra.lift.symm φ + l.comp d) := by
  conv_lhs => rw [← SymmetricAlgebra.lift.apply_symm_apply φ]
  exact translate_bundleTranslationCoaction_lift d _ l

/-- The action of the vector bundle `E = Spec Sym(F)` on the vector bundle `Spec Sym(N)`
attached to a linear map `d : N →ₗ[A] F`.  On `B`-points it sends a point `m : N →ₗ[A] B` and
a translation `l : F →ₗ[A] B` to `m + l ∘ d`.  For `d = id` it is the translation action of a
vector bundle on itself. -/
noncomputable def bundleTranslationAction (d : N →ₗ[A] F) :
    ConeAction A (SymmetricAlgebra A N) F where
  coaction := symCoaction A N
  isCone := isConeCoaction_symCoaction A N
  act := bundleTranslationCoaction d
  act_zero := by
    intro B _ _ φ
    rw [translate_bundleTranslationCoaction, LinearMap.zero_comp, add_zero,
      SymmetricAlgebra.lift.apply_symm_apply]
  act_add := by
    intro B _ _ φ l l'
    rw [translate_bundleTranslationCoaction, translate_bundleTranslationCoaction,
      translate_bundleTranslationCoaction, SymmetricAlgebra.lift.symm_apply_apply,
      LinearMap.add_comp, add_assoc]
  conic := by
    refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m => ?_)
    have hL : Polynomial.mapAlgHom (bundleTranslationCoaction d)
          (symCoaction A N (SymmetricAlgebra.ι A N m)) =
        Polynomial.C (bundleTranslationCoaction d (SymmetricAlgebra.ι A N m)) *
          Polynomial.X := by
      rw [symCoaction_ι, map_mul]
      simp
    have hR : tensorCoaction (symCoaction A N) (symCoaction A F)
          (bundleTranslationCoaction d (SymmetricAlgebra.ι A N m)) =
        Polynomial.C (bundleTranslationCoaction d (SymmetricAlgebra.ι A N m)) *
          Polynomial.X := by
      rw [bundleTranslationCoaction_ι, map_add, tensorCoaction_tmul, tensorCoaction_tmul,
        symCoaction_ι, symCoaction_ι, map_one]
      simp [add_mul]
    exact hL.trans hR.symm

@[simp]
theorem bundleTranslationAction_act (d : N →ₗ[A] F) :
    (bundleTranslationAction d).act = bundleTranslationCoaction d := rfl

@[simp]
theorem bundleTranslationAction_coaction (d : N →ₗ[A] F) :
    (bundleTranslationAction d).coaction = symCoaction A N := rfl

/-- The translation action of a vector bundle on itself is the case `d = id`. -/
theorem bundleTranslationCoaction_id :
    bundleTranslationCoaction (LinearMap.id : N →ₗ[A] N) = symComul A N := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m => ?_)
  change bundleTranslationCoaction (LinearMap.id : N →ₗ[A] N) (SymmetricAlgebra.ι A N m) =
    symComul A N (SymmetricAlgebra.ι A N m)
  rw [bundleTranslationCoaction_ι, symComul_ι]
  rfl

/-- The vertex of `Spec Sym(N)` is a fixed point of the contractions of the action. -/
theorem bundleTranslationAction_isConeVertex (d : N →ₗ[A] F) :
    IsConeVertex (bundleTranslationAction d).coaction
      (SymmetricAlgebra.algebraMapInv (R := A) (M := N)) :=
  isConeVertex_symCoaction A N

end BundleTranslation

end ConeQuotient

namespace AffineNormalCone

/-! ### The tangent action on the affine normal sheaf -/

section TangentAction

variable (k R : Type u) [CommRing k] [CommRing R] [Algebra k R] (I : Ideal R)

/-- The `R`-linear map `I → (R/I) ⊗_R Ω[R⁄k]` sending `x` to `1 ⊗ dx`. -/
noncomputable def conormalToKaehlerAux : I →ₗ[R] (R ⧸ I) ⊗[R] Ω[R⁄k] where
  toFun x := 1 ⊗ₜ KaehlerDifferential.D k R (x : R)
  map_add' x y := by simp only [Submodule.coe_add, map_add, TensorProduct.tmul_add]
  map_smul' r x := by
    simp only [SetLike.val_smul, smul_eq_mul, Derivation.leibniz, TensorProduct.tmul_add,
      TensorProduct.tmul_smul, TensorProduct.smul_tmul', ← Algebra.algebraMap_eq_smul_one,
      RingHom.id_apply]
    rw [show (algebraMap R (R ⧸ I)) (x : R) = 0 from Ideal.Quotient.eq_zero_iff_mem.mpr x.2,
      TensorProduct.zero_tmul, add_zero]

@[simp]
theorem conormalToKaehlerAux_apply (x : I) :
    conormalToKaehlerAux k R I x = 1 ⊗ₜ KaehlerDifferential.D k R (x : R) := rfl

/-- The conormal map `d : I/I² → (R/I) ⊗_R Ω[R⁄k]`, sending the class of `x ∈ I` to `1 ⊗ dx`. -/
noncomputable def conormalToKaehler : I.Cotangent →ₗ[R] (R ⧸ I) ⊗[R] Ω[R⁄k] :=
  Submodule.liftQ _ (conormalToKaehlerAux k R I) <| by
    rw [Submodule.smul_eq_map₂]
    apply iSup_le_iff.mpr
    simp only [Submodule.map_le_iff_le_comap, Subtype.forall]
    rintro x hx y -
    simp only [Submodule.mem_comap, LinearMap.lsmul_apply, LinearMap.mem_ker, map_smul,
      conormalToKaehlerAux_apply, TensorProduct.smul_tmul', ← Algebra.algebraMap_eq_smul_one]
    rw [show (algebraMap R (R ⧸ I)) x = 0 from Ideal.Quotient.eq_zero_iff_mem.mpr hx,
      TensorProduct.zero_tmul]

@[simp]
theorem conormalToKaehler_toCotangent (x : I) :
    conormalToKaehler k R I (Ideal.toCotangent I x) =
      1 ⊗ₜ KaehlerDifferential.D k R (x : R) := rfl

/-- The conormal map as a morphism of `R/I`-modules. -/
noncomputable def conormalMap : I.Cotangent →ₗ[R ⧸ I] (R ⧸ I) ⊗[R] Ω[R⁄k] :=
  LinearMap.extendScalarsOfSurjective Ideal.Quotient.mk_surjective (conormalToKaehler k R I)

@[simp]
theorem conormalMap_toCotangent (x : I) :
    conormalMap k R I (Ideal.toCotangent I x) = 1 ⊗ₜ KaehlerDifferential.D k R (x : R) := rfl

/-- The action of the restricted tangent bundle `Spec Sym_{R/I}((R/I) ⊗_R Ω[R⁄k])` on the
affine normal sheaf `Spec Sym_{R/I}(I/I²)`, by translation along the conormal map.  On
`B`-points it sends a point `m : I/I² →ₗ B` of the normal sheaf and a tangent vector
`l : (R/I) ⊗ Ω →ₗ B` to `m + l ∘ d`. -/
noncomputable def normalSheafTangentAction :
    ConeQuotient.ConeAction (R ⧸ I) (normalSheafCoordinateRing R I) ((R ⧸ I) ⊗[R] Ω[R⁄k]) :=
  ConeQuotient.bundleTranslationAction (conormalMap k R I)

variable {B : Type u} [CommRing B] [Algebra (R ⧸ I) B]

/-- The tangent action on `B`-points of the affine normal sheaf. -/
theorem translate_normalSheafTangentAction
    (m : I.Cotangent →ₗ[R ⧸ I] B) (l : ((R ⧸ I) ⊗[R] Ω[R⁄k]) →ₗ[R ⧸ I] B) :
    ConeQuotient.translate (normalSheafTangentAction k R I).act (SymmetricAlgebra.lift m) l =
      SymmetricAlgebra.lift (m + l.comp (conormalMap k R I)) :=
  ConeQuotient.translate_bundleTranslationCoaction_lift _ m l

/-- The action morphism `C(I/I²) ×_{Spec (R/I)} T → C(I/I²)` of affine schemes. -/
noncomputable def normalSheafActionMap :
    _root_.AlgebraicGeometry.Spec
        (.of (normalSheafCoordinateRing R I ⊗[R ⧸ I]
          SymmetricAlgebra (R ⧸ I) ((R ⧸ I) ⊗[R] Ω[R⁄k]))) ⟶ normalSheaf R I :=
  ConeQuotient.actionMap (normalSheafTangentAction k R I)

/-- The zero tangent vector acts trivially on the affine normal sheaf. -/
theorem zeroSection_comp_normalSheafActionMap :
    ConeQuotient.zeroSectionMap (R ⧸ I) (normalSheafCoordinateRing R I)
        ((R ⧸ I) ⊗[R] Ω[R⁄k]) ≫ normalSheafActionMap k R I =
      CategoryTheory.CategoryStruct.id (normalSheaf R I) :=
  ConeQuotient.zeroSectionMap_comp_actionMap (normalSheafTangentAction k R I)

end TangentAction

end AffineNormalCone

end GromovWitten.AlgebraicGeometry
