/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.DeformationSpaceGeometry
import GromovWitten.AlgebraicGeometry.Curves.RelativeDimension
import GromovWitten.Algebra.FiniteTypeKrullDimension
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.KrullDimension.NonZeroDivisors
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.Ideal.MinimalPrime.Localization

/-!
# Purity of the dimension of the affine normal cone

Behrend–Fantechi's intrinsic normal cone `𝔠_X = [C_{U/M} / T_M|_U]` is pure of dimension zero
because the normal cone `C_{U/M}` of a closed subscheme `U ⊆ M` of a pure `n`-dimensional
scheme `M` is pure of dimension `n` (Fulton, *Intersection Theory*, B.6.6), while `T_M|_U` has
rank `n`.  This file proves the affine algebraic form of Fulton's statement, by deformation to
the normal cone.

Let `k` be a field, `R` a finitely generated `k`-algebra which is a domain of Krull dimension
`n`, and `I ⊆ R` a proper ideal.  Write `A = R[It, t⁻¹] = extendedRees R I` for the extended
Rees algebra and `u = t⁻¹ = parameter R I`.  Then:

* `A` is a Noetherian domain of finite type over `k` (`fg_extendedRees`,
  `finiteType_extendedRees`, `isNoetherianRing_extendedRees`);
* `dim A = n + 1` (`ringKrullDim_extendedRees`), proved through transcendence degrees:
  `R[X] ↪ A ↪ R[T;T⁻¹]` and `R[T;T⁻¹]` is algebraic over `R[X]`;
* `u` is a nonzerodivisor and not a unit, and `A / (u) ≅ gr_I(R)` is the coordinate ring of the
  affine normal cone (`specialFibreEquiv` from `Cones/DeformationSpace.lean`);
* every prime of `A` minimal over `(u)` has height exactly `1`
  (`height_eq_one_of_mem_minimalPrimes_parameterIdeal`), by Krull's principal ideal theorem;
* hence, granting the dimension formula `dim (A ⧸ p) + ht p = dim A` for `A`
  (`HasDimensionFormula`), every minimal prime `q` of `gr_I(R)` satisfies
  `dim (gr_I(R) ⧸ q) = n` (`ringKrullDim_quotient_eq_of_mem_minimalPrimes`), and
  `dim gr_I(R) = n` (`ringKrullDim_associatedGradedRing`).

## The one conditional input

The dimension formula `dim (A ⧸ p) + ht p = dim A` for a finitely generated domain `A` over a
field (equivalently: finite type algebras over a field are catenary and equidimensional) is not
available in Mathlib.  It is therefore isolated as the explicit predicate
`GromovWitten.AlgebraicGeometry.HasDimensionFormula` and appears as a hypothesis of exactly
those statements that need it.  Everything else in this file is unconditional; in particular
the upper bounds `dim gr_I(R) ≤ n` and `dim (gr_I(R) ⧸ q) ≤ n` are proved without it
(`ringKrullDim_associatedGradedRing_le`, `ringKrullDim_quotient_le_of_ideal`), as is the zero
ideal case `dim gr_⊥(R) = dim R` (`ringKrullDim_associatedGradedRing_bot`).
-/

open CategoryTheory AlgebraicGeometry LaurentPolynomial
open scoped nonZeroDivisors

namespace GromovWitten.AlgebraicGeometry

universe u

/-- The **dimension formula** for a commutative ring `A`: for every prime `p`,
`dim (A ⧸ p) + ht p = dim A`.

This holds for every finitely generated domain over a field (it is the combination of
catenarity and equidimensionality of finite type algebras over a field), but is not yet
available in Mathlib.  Results that need it take it as an explicit hypothesis. -/
def HasDimensionFormula (A : Type u) [CommRing A] : Prop :=
  ∀ p : Ideal A, p.IsPrime →
    ringKrullDim (A ⧸ p) + ((p.height : ℕ∞) : WithBot ℕ∞) = ringKrullDim A

namespace AffineDeformationSpace

variable (R : Type u) [CommRing R] (I : Ideal R)

/-! ### The extended Rees algebra is a Noetherian algebra of finite type -/

section FiniteType

/-- Every element of the extended Rees algebra lies in the `R`-subalgebra generated by the
parameter `t⁻¹` together with the image of any generating set of the Rees algebra: splitting a
Laurent polynomial into its nonnegative and its negative part, the first part comes from the
Rees algebra and the second is a polynomial in `t⁻¹`. -/
theorem mem_adjoin_insert_parameter_image {t : Set (Polynomial R)}
    (ht : Algebra.adjoin R t = reesAlgebra I) {f : R[T;T⁻¹]} (hf : f ∈ extendedRees R I) :
    f ∈ Algebra.adjoin R (insert (T (-1) : R[T;T⁻¹]) (Polynomial.toLaurent '' t)) := by
  classical
  set B := Algebra.adjoin R (insert (T (-1) : R[T;T⁻¹]) (Polynomial.toLaurent '' t)) with hBdef
  set s := f.coeff.support with hsdef
  set p₀ : Polynomial R := ∑ n ∈ s with 0 ≤ n, Polynomial.monomial n.toNat (f.coeff n) with hp₀def
  have hp₀ : p₀ ∈ reesAlgebra I := by
    refine Subalgebra.sum_mem _ fun n _ ↦ ?_
    exact reesAlgebra.monomial_mem.mpr (hf n)
  have hpos : Polynomial.toLaurent p₀ ∈ B := by
    have h1 : p₀ ∈ Algebra.adjoin R t := by rw [ht]; exact hp₀
    have h2 : Polynomial.toLaurent p₀ ∈
        Subalgebra.map (Polynomial.toLaurentAlg (R := R)) (Algebra.adjoin R t) := ⟨p₀, h1, rfl⟩
    rw [← Algebra.adjoin_image] at h2
    exact Algebra.adjoin_mono (Set.subset_insert _ _) h2
  have hneg : (∑ n ∈ s with ¬ 0 ≤ n, LaurentPolynomial.C (f.coeff n) * T n) ∈ B := by
    refine Subalgebra.sum_mem _ fun n hn ↦ ?_
    have hn' : ¬ (0 : ℤ) ≤ n := (Finset.mem_filter.mp hn).2
    have hTn : (T n : R[T;T⁻¹]) = (T (-1) : R[T;T⁻¹]) ^ n.natAbs := by
      rw [T_pow]
      congr 1
      omega
    rw [hTn, C_eq_algebraMap]
    exact Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _)
      (Subalgebra.pow_mem _ (Algebra.subset_adjoin (Set.mem_insert _ _)) _)
  have e1 : Polynomial.toLaurent p₀ =
      ∑ n ∈ s with 0 ≤ n, LaurentPolynomial.C (f.coeff n) * T n := by
    simp only [hp₀def, map_sum]
    refine Finset.sum_congr rfl fun n hn ↦ ?_
    have hn' : 0 ≤ n := (Finset.mem_filter.mp hn).2
    rw [← Polynomial.C_mul_X_pow_eq_monomial, Polynomial.toLaurent_C_mul_X_pow,
      Int.toNat_of_nonneg hn']
  have hsplit : f = Polynomial.toLaurent p₀ +
      ∑ n ∈ s with ¬ 0 ≤ n, LaurentPolynomial.C (f.coeff n) * T n := by
    rw [e1, Finset.sum_filter_add_sum_filter_not]
    exact eq_sum_support R f
  rw [hsplit]
  exact Subalgebra.add_mem _ hpos hneg

/-- The extended Rees algebra of an ideal of a Noetherian ring is a finitely generated
`R`-subalgebra of the Laurent polynomial ring. -/
theorem fg_extendedRees [IsNoetherianRing R] : (extendedRees R I).FG := by
  obtain ⟨t, htfin, ht⟩ := Subalgebra.fg_def.mp (reesAlgebra.fg (IsNoetherian.noetherian I))
  refine Subalgebra.fg_def.mpr ⟨insert (T (-1) : R[T;T⁻¹]) (Polynomial.toLaurent '' t),
    (htfin.image _).insert _, le_antisymm ?_ ?_⟩
  · rw [Algebra.adjoin_le_iff]
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | hx'
    · exact (parameter R I).2
    · obtain ⟨y, hy, rfl⟩ := hx'
      exact isExtendedRees_toLaurent R I (by rw [← ht]; exact Algebra.subset_adjoin hy)
  · intro f hf
    exact mem_adjoin_insert_parameter_image R I ht hf

/-- The extended Rees algebra of an ideal of a Noetherian ring is of finite type over `R`. -/
instance finiteType_extendedRees [IsNoetherianRing R] :
    Algebra.FiniteType R (extendedRees R I) :=
  ⟨(Subalgebra.fg_top _).mpr (fg_extendedRees R I)⟩

/-- The extended Rees algebra of an ideal of a Noetherian ring is Noetherian. -/
instance isNoetherianRing_extendedRees [IsNoetherianRing R] :
    IsNoetherianRing (extendedRees R I) :=
  Algebra.FiniteType.isNoetherianRing R _

end FiniteType

/-! ### The parameter is a nonzerodivisor and not a unit -/

section Parameter

/-- The extended Rees algebra of an ideal of a domain is a domain. -/
instance isDomain_extendedRees [IsDomain R] : IsDomain (extendedRees R I) :=
  Subalgebra.isDomain _

/-- The parameter `t⁻¹` is nonzero. -/
theorem parameter_ne_zero [Nontrivial R] : parameter R I ≠ 0 := by
  intro h
  have h' : (T (-1) : R[T;T⁻¹]) = 0 := congrArg Subtype.val h
  exact (isUnit_T (R := R) (-1)).ne_zero h'

/-- The parameter `t⁻¹` is a nonzerodivisor of the extended Rees algebra. -/
theorem parameter_mem_nonZeroDivisors [IsDomain R] :
    parameter R I ∈ (extendedRees R I)⁰ :=
  mem_nonZeroDivisors_of_ne_zero (parameter_ne_zero R I)

/-- The parameter `t⁻¹` is a unit of the extended Rees algebra only if `I` is the unit ideal:
its inverse would be `t`, whose degree one coefficient `1` has to lie in `I`. -/
theorem not_isUnit_parameter (hI : I ≠ ⊤) : ¬ IsUnit (parameter R I) := by
  intro hu
  obtain ⟨w, hw⟩ := hu.exists_right_inv
  have hw' : (T (-1) : R[T;T⁻¹]) * (w : R[T;T⁻¹]) = 1 := congrArg Subtype.val hw
  have h1 : (T 1 : R[T;T⁻¹]) * (T (-1) : R[T;T⁻¹]) = 1 := by
    rw [← T_add]
    simp
  have hwT : (w : R[T;T⁻¹]) = T 1 := by
    calc (w : R[T;T⁻¹]) = 1 * (w : R[T;T⁻¹]) := (one_mul _).symm
      _ = (T 1 * T (-1)) * (w : R[T;T⁻¹]) := by rw [h1]
      _ = T 1 * ((T (-1)) * (w : R[T;T⁻¹])) := mul_assoc _ _ _
      _ = T 1 := by rw [hw', mul_one]
  have hmem := coeff_mem_of_mem R I w.2 1
  rw [hwT] at hmem
  have hcoeff : (T 1 : R[T;T⁻¹]).coeff 1 = 1 := by
    have hone : (T 1 : R[T;T⁻¹]) = LaurentPolynomial.C (1 : R) * T 1 := by simp
    rw [hone, ← single_eq_C_mul_T, AddMonoidAlgebra.coeff_single, Finsupp.single_apply]
    simp
  rw [hcoeff] at hmem
  simp only [Int.toNat_one, pow_one] at hmem
  exact hI ((Ideal.eq_top_iff_one I).mpr hmem)

/-- The ideal generated by the parameter is proper as soon as `I` is. -/
theorem parameterIdeal_ne_top (hI : I ≠ ⊤) : parameterIdeal R I ≠ ⊤ := by
  intro h
  exact not_isUnit_parameter R I hI (Ideal.span_singleton_eq_top.mp h)

/-- Every prime of the extended Rees algebra that is minimal over the parameter has height
exactly one: at most one by Krull's principal ideal theorem, at least one because the
parameter is a nonzero element of a domain. -/
theorem height_eq_one_of_mem_minimalPrimes_parameterIdeal [IsDomain R] [IsNoetherianRing R]
    (hI : I ≠ ⊤) {p : Ideal (extendedRees R I)} (hp : p ∈ (parameterIdeal R I).minimalPrimes) :
    p.height = 1 := by
  have hprinc : (parameterIdeal R I).IsPrincipal := ⟨⟨parameter R I, rfl⟩⟩
  have hle : p.height ≤ 1 :=
    Ideal.height_le_one_of_isPrincipal_of_mem_minimalPrimes _ p hp
  have hspan : (parameterIdeal R I).height = 1 :=
    Ideal.height_span_singleton_eq_one_of_mem_nonZeroDivisors
      (parameter_mem_nonZeroDivisors R I) (not_isUnit_parameter R I hI)
  have hge : (1 : ℕ∞) ≤ p.height := hspan ▸ Ideal.height_mono hp.1.2
  exact le_antisymm hle hge

end Parameter

/-! ### The dimension of the extended Rees algebra -/

section Dimension

/-- The Laurent polynomial ring is algebraic over the polynomial ring: every Laurent
polynomial `f` satisfies `Tⁿ · Y - f'` for a suitable polynomial `f'`. -/
instance isAlgebraic_laurent [Nontrivial R] :
    Algebra.IsAlgebraic (Polynomial R) R[T;T⁻¹] := by
  constructor
  intro f
  obtain ⟨n, f', hf'⟩ := LaurentPolynomial.exists_T_pow f
  refine ⟨Polynomial.C ((Polynomial.X : Polynomial R) ^ n) * Polynomial.X -
    Polynomial.C f', ?_, ?_⟩
  · intro hzero
    have hc : ((Polynomial.C ((Polynomial.X : Polynomial R) ^ n) * Polynomial.X -
        Polynomial.C f').coeff 1) = (Polynomial.X : Polynomial R) ^ n := by
      rw [Polynomial.coeff_sub, Polynomial.coeff_C_mul, Polynomial.coeff_X_one,
        Polynomial.coeff_C, if_neg one_ne_zero, mul_one, sub_zero]
    rw [hzero] at hc
    exact (Polynomial.monic_X_pow (R := R) n).ne_zero hc.symm
  · rw [map_sub, map_mul, Polynomial.aeval_C, Polynomial.aeval_X, Polynomial.aeval_C,
      LaurentPolynomial.algebraMap_eq_toLaurent, LaurentPolynomial.algebraMap_eq_toLaurent,
      map_pow, Polynomial.toLaurent_X, hf', T_pow, mul_one]
    ring

variable (k : Type u) [Field k] [Algebra k R]

/-- The structure map `R[u] → R[It, t⁻¹]`, `u ↦ t⁻¹`, is injective: it is the composition of
`Polynomial.toLaurent` with the inversion automorphism of the Laurent polynomial ring. -/
theorem structureMap_injective : Function.Injective (structureMap R I) := by
  intro p q hpq
  have h : (invert (R := R)) (Polynomial.toLaurent p) = invert (Polynomial.toLaurent q) := by
    rw [← coe_structureMap R I p, ← coe_structureMap R I q, hpq]
  exact Polynomial.toLaurent_injective ((invert (R := R)).injective h)

/-- The Krull dimension of the extended Rees algebra is one more than that of `R`.

The proof compares transcendence degrees: `R[u] ↪ R[It, t⁻¹] ↪ R[t, t⁻¹]`, and `R[t, t⁻¹]` is
algebraic over `R[t]`, so all three rings have the same transcendence degree over `k`; for
finitely generated domains over a field the Krull dimension is the transcendence degree. -/
theorem ringKrullDim_extendedRees [IsDomain R] [IsNoetherianRing R] [Algebra.FiniteType k R] :
    ringKrullDim (extendedRees R I) = ringKrullDim R + 1 := by
  have hfaith : FaithfulSMul k R :=
    (faithfulSMul_iff_algebraMap_injective k R).mpr (algebraMap k R).injective
  have halgX : ∀ x : k, algebraMap k (Polynomial R) x = Polynomial.C (algebraMap k R x) := by
    intro x
    rw [IsScalarTower.algebraMap_apply k R (Polynomial R)]
    rfl
  have hfaithX : FaithfulSMul k (Polynomial R) := by
    rw [faithfulSMul_iff_algebraMap_injective]
    intro a b hab
    apply (faithfulSMul_iff_algebraMap_injective k R).mp hfaith
    rw [halgX, halgX] at hab
    exact Polynomial.C_injective hab
  have hfaithL : FaithfulSMul (Polynomial R) R[T;T⁻¹] :=
    (faithfulSMul_iff_algebraMap_injective _ _).mpr Polynomial.toLaurent_injective
  have htower : IsScalarTower k (Polynomial R) R[T;T⁻¹] :=
    IsScalarTower.of_algebraMap_eq fun x ↦ by
      rw [halgX, LaurentPolynomial.algebraMap_eq_toLaurent, Polynomial.toLaurent_C,
        LaurentPolynomial.C_eq_algebraMap]
      exact IsScalarTower.algebraMap_apply k R R[T;T⁻¹] x
  have hFTX : Algebra.FiniteType k (Polynomial R) :=
    Algebra.FiniteType.trans (S := R) inferInstance inferInstance
  have hFTA : Algebra.FiniteType k (extendedRees R I) :=
    Algebra.FiniteType.trans (S := R) inferInstance inferInstance
  have h1 : Algebra.trdeg k (Polynomial R) ≤ Algebra.trdeg k (extendedRees R I) :=
    _root_.trdeg_le_of_injective ((structureMap R I).restrictScalars k)
      (structureMap_injective R I)
  have h2 : Algebra.trdeg k (extendedRees R I) ≤ Algebra.trdeg k R[T;T⁻¹] :=
    _root_.trdeg_le_of_injective ((Subalgebra.val (extendedRees R I)).restrictScalars k)
      Subtype.val_injective
  have h3 : Algebra.trdeg k R[T;T⁻¹] = Algebra.trdeg k (Polynomial R) :=
    GromovWitten.Algebra.trdeg_eq_of_isAlgebraic k (Polynomial R) R[T;T⁻¹]
  have heq : Algebra.trdeg k (extendedRees R I) = Algebra.trdeg k (Polynomial R) :=
    le_antisymm (h3 ▸ h2) h1
  rw [GromovWitten.Algebra.ringKrullDim_eq_toENat_trdeg k (extendedRees R I), heq,
    ← GromovWitten.Algebra.ringKrullDim_eq_toENat_trdeg k (Polynomial R),
    Polynomial.ringKrullDim_of_isNoetherianRing]

end Dimension

/-! ### The normal cone as a quotient of the deformation space -/

section Quotient

/-- The canonical surjection from the extended Rees algebra onto the associated graded ring:
reduction modulo the parameter, followed by the identification of the special fibre. -/
noncomputable def toAssociatedGraded :
    extendedRees R I →+* AffineNormalCone.associatedGradedRing R I :=
  ((specialFibreEquiv R I).symm.toAlgHom.toRingHom).comp
    (Ideal.Quotient.mk (parameterIdeal R I))

/-- The reduction map onto the associated graded ring is surjective. -/
theorem toAssociatedGraded_surjective : Function.Surjective (toAssociatedGraded R I) :=
  (specialFibreEquiv R I).symm.surjective.comp Ideal.Quotient.mk_surjective

/-- The kernel of the reduction map is the ideal generated by the parameter. -/
theorem ker_toAssociatedGraded :
    RingHom.ker (toAssociatedGraded R I) = parameterIdeal R I := by
  ext x
  rw [RingHom.mem_ker]
  constructor
  · intro hx
    have hx' : (specialFibreEquiv R I).symm (Ideal.Quotient.mk (parameterIdeal R I) x) = 0 := hx
    have h := congrArg (specialFibreEquiv R I) hx'
    rw [AlgEquiv.apply_symm_apply, map_zero] at h
    exact Ideal.Quotient.eq_zero_iff_mem.mp h
  · intro hx
    change (specialFibreEquiv R I).symm (Ideal.Quotient.mk (parameterIdeal R I) x) = 0
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr hx, map_zero]

/-- A minimal prime of the associated graded ring contracts to a prime of the extended Rees
algebra that is minimal over the parameter. -/
theorem comap_mem_minimalPrimes_parameterIdeal
    {q : Ideal (AffineNormalCone.associatedGradedRing R I)}
    (hq : q ∈ minimalPrimes (AffineNormalCone.associatedGradedRing R I)) :
    q.comap (toAssociatedGraded R I) ∈ (parameterIdeal R I).minimalPrimes := by
  have h := Ideal.minimalPrimes_comap_of_surjective (toAssociatedGraded_surjective R I) hq
  rwa [← RingHom.ker_eq_comap_bot, ker_toAssociatedGraded] at h

/-- The kernel of the reduction of the extended Rees algebra modulo a preimage ideal. -/
theorem ker_quotientMk_comp_toAssociatedGraded
    (q : Ideal (AffineNormalCone.associatedGradedRing R I)) :
    RingHom.ker ((Ideal.Quotient.mk q).comp (toAssociatedGraded R I)) =
      q.comap (toAssociatedGraded R I) := by
  ext x
  rw [RingHom.mem_ker, Ideal.mem_comap, RingHom.comp_apply, Ideal.Quotient.eq_zero_iff_mem]

/-- Quotienting the associated graded ring by an ideal is the same as quotienting the extended
Rees algebra by its contraction. -/
noncomputable def quotientEquivQuotientComap
    (q : Ideal (AffineNormalCone.associatedGradedRing R I)) :
    (extendedRees R I ⧸ q.comap (toAssociatedGraded R I)) ≃+*
      (AffineNormalCone.associatedGradedRing R I ⧸ q) :=
  (Ideal.quotEquivOfEq (ker_quotientMk_comp_toAssociatedGraded R I q).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (Ideal.Quotient.mk_surjective.comp (toAssociatedGraded_surjective R I)))

end Quotient

/-! ### Purity of the dimension of the affine normal cone -/

section Purity

variable (k : Type u) [Field k] [Algebra k R]

/-- Unconditional upper bound: the Krull dimension of the associated graded ring is at most
`dim R`, because the parameter is a nonzerodivisor of the extended Rees algebra. -/
theorem ringKrullDim_associatedGradedRing_le [IsDomain R] [IsNoetherianRing R]
    [Algebra.FiniteType k R] (n : ℕ) (hn : ringKrullDim R = (n : ℕ∞)) :
    ringKrullDim (AffineNormalCone.associatedGradedRing R I) ≤ (n : ℕ∞) := by
  have hquot : ringKrullDim (extendedRees R I ⧸ parameterIdeal R I) + 1 ≤
      ringKrullDim (extendedRees R I) :=
    ringKrullDim_quotient_succ_le_of_nonZeroDivisor (parameter_mem_nonZeroDivisors R I)
  rw [ringKrullDim_extendedRees R I k, hn] at hquot
  have hiso : ringKrullDim (AffineNormalCone.associatedGradedRing R I) =
      ringKrullDim (extendedRees R I ⧸ parameterIdeal R I) :=
    ringKrullDim_eq_of_ringEquiv (specialFibreEquiv R I).toRingEquiv
  rw [hiso]
  rcases eq_or_ne (ringKrullDim (extendedRees R I ⧸ parameterIdeal R I)) ⊥ with hd | hd
  · rw [hd]
    exact bot_le
  obtain ⟨y, hy⟩ := WithBot.ne_bot_iff_exists.mp hd
  rw [← hy] at hquot ⊢
  have hy' : y + 1 ≤ (n : ℕ∞) + 1 := by exact_mod_cast hquot
  have hyn : y ≤ (n : ℕ∞) := (ENat.add_le_add_iff_right (by simp)).mp hy'
  exact_mod_cast hyn

/-- Unconditional upper bound for every quotient: no closed subscheme of the affine normal
cone, in particular no irreducible component of it, has dimension bigger than `dim R`. -/
theorem ringKrullDim_quotient_le_of_ideal [IsDomain R] [IsNoetherianRing R]
    [Algebra.FiniteType k R] (n : ℕ) (hn : ringKrullDim R = (n : ℕ∞))
    (q : Ideal (AffineNormalCone.associatedGradedRing R I)) :
    ringKrullDim (AffineNormalCone.associatedGradedRing R I ⧸ q) ≤ (n : ℕ∞) :=
  (ringKrullDim_quotient_le q).trans (ringKrullDim_associatedGradedRing_le R I k n hn)

/-- Sanity check for the zero ideal: `gr_⊥(R) = R`, so the affine normal cone of the identity
closed immersion has the dimension of `R`, unconditionally. -/
theorem ringKrullDim_associatedGradedRing_bot :
    ringKrullDim (AffineNormalCone.associatedGradedRing R (⊥ : Ideal R)) = ringKrullDim R :=
  ringKrullDim_eq_of_ringEquiv (AffineNormalCone.associatedGradedRingBotEquiv R)

/-- **Purity of the affine normal cone (deformation space form).**  Granting the dimension
formula for the extended Rees algebra `A = R[It, t⁻¹]`, every prime of `A` minimal over the
parameter has `dim (A ⧸ p) = dim R`.

The dimension formula is the only nonconstructive input: it is used exactly once, in the shape
`dim (A ⧸ p) + ht p = dim A`, together with `ht p = 1` and `dim A = dim R + 1`. -/
theorem ringKrullDim_quotient_eq_of_mem_minimalPrimes_parameterIdeal
    [IsDomain R] [IsNoetherianRing R] [Algebra.FiniteType k R] (hI : I ≠ ⊤) (n : ℕ)
    (hn : ringKrullDim R = (n : ℕ∞)) (hdf : HasDimensionFormula (extendedRees R I))
    {p : Ideal (extendedRees R I)} (hp : p ∈ (parameterIdeal R I).minimalPrimes) :
    ringKrullDim (extendedRees R I ⧸ p) = (n : ℕ∞) := by
  have hprime : p.IsPrime := hp.isPrime
  have hht : p.height = 1 := height_eq_one_of_mem_minimalPrimes_parameterIdeal R I hI hp
  have hform := hdf p hprime
  rw [hht, ringKrullDim_extendedRees R I k, hn] at hform
  have hnontriv : Nontrivial (extendedRees R I ⧸ p) :=
    Ideal.Quotient.nontrivial_iff.mpr hprime.ne_top
  have hbot : ringKrullDim (extendedRees R I ⧸ p) ≠ ⊥ := by
    intro h
    have h0 := ringKrullDim_nonneg_of_nontrivial (R := extendedRees R I ⧸ p)
    rw [h] at h0
    simp at h0
  obtain ⟨y, hy⟩ := WithBot.ne_bot_iff_exists.mp hbot
  rw [← hy] at hform ⊢
  have hform' : y + 1 = (n : ℕ∞) + 1 := by exact_mod_cast hform
  have hyn : y = (n : ℕ∞) :=
    le_antisymm ((ENat.add_le_add_iff_right (by simp)).mp hform'.le)
      ((ENat.add_le_add_iff_right (by simp)).mp hform'.ge)
  rw [hyn]

/-- **Purity of the affine normal cone.**  Granting the dimension formula for the extended Rees
algebra, every irreducible component of `Spec (gr_I R)` has dimension `dim R`: for every
minimal prime `q` of `gr_I(R)`, `dim (gr_I(R) ⧸ q) = dim R`.

This is the affine algebraic form of Fulton, *Intersection Theory*, B.6.6, which Behrend and
Fantechi use to see that the intrinsic normal cone is pure of dimension zero. -/
theorem ringKrullDim_quotient_eq_of_mem_minimalPrimes
    [IsDomain R] [IsNoetherianRing R] [Algebra.FiniteType k R] (hI : I ≠ ⊤) (n : ℕ)
    (hn : ringKrullDim R = (n : ℕ∞)) (hdf : HasDimensionFormula (extendedRees R I))
    {q : Ideal (AffineNormalCone.associatedGradedRing R I)}
    (hq : q ∈ minimalPrimes (AffineNormalCone.associatedGradedRing R I)) :
    ringKrullDim (AffineNormalCone.associatedGradedRing R I ⧸ q) = (n : ℕ∞) := by
  rw [← ringKrullDim_eq_of_ringEquiv (quotientEquivQuotientComap R I q)]
  exact ringKrullDim_quotient_eq_of_mem_minimalPrimes_parameterIdeal R I k hI n hn hdf
    (comap_mem_minimalPrimes_parameterIdeal R I hq)

/-- The associated graded ring of a proper ideal is nontrivial. -/
theorem nontrivial_associatedGradedRing (hI : I ≠ ⊤) :
    Nontrivial (AffineNormalCone.associatedGradedRing R I) := by
  have h : Nontrivial (specialFibreRing R I) :=
    Ideal.Quotient.nontrivial_iff.mpr (parameterIdeal_ne_top R I hI)
  exact (specialFibreEquiv R I).toEquiv.nontrivial

/-- Granting the dimension formula, the affine normal cone of a proper ideal of an
`n`-dimensional finitely generated domain over a field has Krull dimension exactly `n`. -/
theorem ringKrullDim_associatedGradedRing [IsDomain R] [IsNoetherianRing R]
    [Algebra.FiniteType k R] (hI : I ≠ ⊤) (n : ℕ) (hn : ringKrullDim R = (n : ℕ∞))
    (hdf : HasDimensionFormula (extendedRees R I)) :
    ringKrullDim (AffineNormalCone.associatedGradedRing R I) = (n : ℕ∞) := by
  have hnt : Nontrivial (AffineNormalCone.associatedGradedRing R I) :=
    nontrivial_associatedGradedRing R I hI
  refine le_antisymm (ringKrullDim_associatedGradedRing_le R I k n hn) ?_
  obtain ⟨⟨q, hq⟩⟩ := Ideal.nonempty_minimalPrimes (I := (⊥ : Ideal
    (AffineNormalCone.associatedGradedRing R I))) bot_ne_top
  have hdim := ringKrullDim_quotient_eq_of_mem_minimalPrimes R I k hI n hn hdf hq
  rw [← hdim]
  exact ringKrullDim_quotient_le _

end Purity

/-! ### The scheme-theoretic form: purity of `Spec (gr_I R)` -/

section Scheme

/-- The closed subset `V(J) ⊆ Spec B` is homeomorphic to `Spec (B ⧸ J)`, so its topological
Krull dimension is the Krull dimension of `B ⧸ J`. -/
theorem topologicalKrullDim_zeroLocus {B : Type u} [CommRing B] (J : Ideal B) :
    topologicalKrullDim (PrimeSpectrum.zeroLocus (J : Set B)) = ringKrullDim (B ⧸ J) := by
  have hemb : Topology.IsEmbedding (PrimeSpectrum.comap (Ideal.Quotient.mk J)) :=
    PrimeSpectrum.isEmbedding_comap_of_surjective _ _ Ideal.Quotient.mk_surjective
  have hrange : Set.range (PrimeSpectrum.comap (Ideal.Quotient.mk J)) =
      PrimeSpectrum.zeroLocus (J : Set B) := by
    rw [range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective, Ideal.mk_ker]
  let e : PrimeSpectrum (B ⧸ J) ≃ₜ PrimeSpectrum.zeroLocus (J : Set B) :=
    hemb.toHomeomorph.trans (Homeomorph.setCongr hrange)
  rw [← IsHomeomorph.topologicalKrullDim_eq e e.isHomeomorph,
    PrimeSpectrum.topologicalKrullDim_eq_ringKrullDim]

/-- A criterion for purity of an affine scheme: if every minimal prime of `B` has
`dim (B ⧸ q) = n`, then every irreducible component of `Spec B` has dimension `n`. -/
theorem pureTopologicalDimension_spec {B : Type u} [CommRing B] {n : ℕ}
    (h : ∀ q ∈ minimalPrimes B, ringKrullDim (B ⧸ q) = (n : ℕ∞)) :
    Curves.PureTopologicalDimension n (Spec (CommRingCat.of B)) := by
  intro Z hZ
  have hZ' : Z ∈ irreducibleComponents (PrimeSpectrum B) := hZ
  rw [← PrimeSpectrum.zeroLocus_minimalPrimes] at hZ'
  obtain ⟨q, hq, rfl⟩ := hZ'
  have hdim : topologicalKrullDim (PrimeSpectrum.zeroLocus (q : Set B)) = ringKrullDim (B ⧸ q) :=
    topologicalKrullDim_zeroLocus q
  change topologicalKrullDim (PrimeSpectrum.zeroLocus (q : Set B)) = _
  rw [hdim, h q hq]
  rfl

variable (k : Type u) [Field k] [Algebra k R]

/-- **Purity of the affine normal cone, scheme form.**  Granting the dimension formula for the
extended Rees algebra, every irreducible component of the affine normal cone
`Spec (gr_I R)` of a proper ideal `I` of an `n`-dimensional finitely generated domain `R` over
a field has topological Krull dimension `n`. -/
theorem pureTopologicalDimension_normalCone [IsDomain R] [IsNoetherianRing R]
    [Algebra.FiniteType k R] (hI : I ≠ ⊤) (n : ℕ) (hn : ringKrullDim R = (n : ℕ∞))
    (hdf : HasDimensionFormula (extendedRees R I)) :
    Curves.PureTopologicalDimension n (AffineNormalCone.scheme R I) :=
  pureTopologicalDimension_spec fun _q hq ↦
    ringKrullDim_quotient_eq_of_mem_minimalPrimes R I k hI n hn hdf hq

end Scheme

end AffineDeformationSpace

end GromovWitten.AlgebraicGeometry
