/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.NormalConeProductInj3
import GromovWitten.AlgebraicGeometry.Cones.RefinementNormalSheaf

/-!
# The product formula for the affine normal sheaf

`Cones/NormalConeProduct.lean` and `Cones/NormalConeProductInj3.lean` prove the product formula
for the affine normal *cone* over a field `k`: for `k`-algebras `R`, `R'` with ideals `I`, `I'`
and `J = productIdeal k R R' I I' = I ⊗ R' + R ⊗ I'`, the comparison map
`grTensorToGr : gr_I(R) ⊗[k] gr_{I'}(R') →ₐ[k] gr_J(R ⊗[k] R')` is an isomorphism
(`grTensorEquivOfField`), that is `C_{U×U'/M×M'} ≅ C_{U/M} × C_{U'/M'}`.  This file proves the
analogous statement for the normal *sheaf* `N_{U/M} = Sym_{R/I}(I/I²) =
normalSheafRing R I = Sym_R(I)/I·Sym_R(I)`.

## The comparison map

`nsMapOfMapLe` is functoriality of the normal-sheaf ring for a ring map `f : A →+* B` with
`f(I) ⊆ J`; applied to the two inclusions of a tensor product it gives `nsLeftHom`, `nsRightHom`
and hence, by the universal property of a tensor product of algebras,

`nsTensorToNs : N_{U/M} ⊗[k] N_{U'/M'} →ₐ[k] N_{U×U'/M×M'}`,

characterised on generators by `nsTensorToNs (nsClass x ⊗ 1) = nsClass (x ⊗ 1)` and
`nsTensorToNs (1 ⊗ nsClass y) = nsClass (1 ⊗ y)` (`nsTensorToNs_nsClass_left`,
`nsTensorToNs_nsClass_right`).

## The two halves of the isomorphism

* `nsTensorToNs_surjective` holds over an arbitrary commutative base ring `k`: the product ideal
  is generated by `I ⊗ 1` and `1 ⊗ I'` (`productIdeal_eq_span`), so degree-zero and degree-one
  elements are hit, and `ConeRefinement.ns_surjective` concludes.
* `nsTensorToNs_injective` uses that `k` is a field.  The point is to construct a ring map
  backwards (`exists_nsInverse`).  Over a field the ideals `I ⊆ R` and `I' ⊆ R'` are direct
  summands as `k`-vector spaces, so there are `k`-linear retractions `π : R → I`, `π' : R' → I'`;
  the `k`-linear map `Λ (a ⊗ b) = nsClass (π a) ⊗ [b] + [a] ⊗ nsClass (π' b)` on `R ⊗[k] R'` is
  `nsBase`-semilinear along the product ideal (`hsemi` in the proof, from the computations `hA`,
  `hB` on the two families of generators), which is exactly the input of the universal property
  `ConeRefinement.exists_nsRingHom` of the normal-sheaf ring.  The choice of `π`, `π'` is
  irrelevant on `J`, where `Λ` is pinned down by `Λ (x ⊗ 1) = nsClass x ⊗ 1` and
  `Λ (1 ⊗ y) = 1 ⊗ nsClass y`.

Together they give the product formula `nsTensorEquiv : N_{U/M} ⊗[k] N_{U'/M'} ≃ₐ[k]
N_{U×U'/M×M'}`, that is `N_{U×U'/M×M'} ≅ N_{U/M} × N_{U'/M'}`.

## Compatibility with the normal cone

`nsToGrK_comp_nsTensorToNs` (pointwise: `nsToGr_nsTensorToNs`) is the commuting square relating
`nsTensorToNs`, `grTensorToGr` and the closed immersions `nsToGr : N → C`; since both horizontal
maps are isomorphisms over a field, the closed immersion `C_{U×U'/M×M'} ⊆ N_{U×U'/M×M'}` is the
product of the closed immersions `C_{U/M} ⊆ N_{U/M}` and `C_{U'/M'} ⊆ N_{U'/M'}`.

What is *not* proved here: the passage from the affine model to a non-affine base or to a general
smooth ambient space, and the sheafified statement for the intrinsic normal sheaf.
-/

open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

namespace AffineNormalSheafProduct

universe u

noncomputable section

open AffineNormalCone ConeRefinement AffineNormalConeProduct

/-! ### Functoriality of the normal-sheaf ring for a map of pairs -/

section Functoriality

variable {A B : Type u} [CommRing A] [CommRing B] (I : Ideal A) (f : A →+* B) (J : Ideal B)
  (h : Ideal.map f I ≤ J)

/-- Functoriality of the normal-sheaf ring for a ring map `f : A →+* B` with `f(I) ⊆ J`:
the induced map `N_{V(I)/Spec A} → N_{V(J)/Spec B}` of coordinate rings. -/
def nsMapOfMapLe : normalSheafRing A I →+* normalSheafRing B J :=
  (nsMapOfLe (Ideal.map f I) J h).comp (nsMapOfEq I f (Ideal.map f I) rfl)

/-- The functoriality map is the map induced by `f` in degree zero. -/
theorem nsMapOfMapLe_algebraMap (a : A) :
    nsMapOfMapLe I f J h (algebraMap A (normalSheafRing A I) a) =
      algebraMap B (normalSheafRing B J) (f a) := by
  rw [nsMapOfMapLe, RingHom.comp_apply]
  change nsMapOfLe _ _ _ (nsMapOfEq I f _ rfl
    (Ideal.Quotient.mk _ (algebraMap A (SymmetricAlgebra A I) a))) = _
  rw [nsMapOfEq_mk, symMapOfEq_algebraMap, nsMapOfLe_mk]
  change Ideal.Quotient.mk _ (symMapOfLe _ _ _ (algebraMap _ _ (f a))) = _
  rw [AlgHom.commutes]
  rfl

/-- The functoriality map sends the degree-one class of `x ∈ I` to that of `f x ∈ J`. -/
theorem nsMapOfMapLe_nsClass (x : I) :
    nsMapOfMapLe I f J h (nsClass I x) =
      nsClass J ⟨f (x : A), h (Ideal.mem_map_of_mem f x.2)⟩ := by
  rw [nsMapOfMapLe, RingHom.comp_apply, nsClass_eq_mk, nsMapOfEq_mk, symMapOfEq_ι, nsMapOfLe_mk,
    symMapOfLe_ι, nsClass_eq_mk]

end Functoriality

/-! ### The comparison map -/

section Comparison

variable (k : Type u) [CommRing k] (R : Type u) [CommRing R] [Algebra k R]
  (R' : Type u) [CommRing R'] [Algebra k R'] (I : Ideal R) (I' : Ideal R')

/-- The extension of `I` along the left inclusion lands in the product ideal. -/
theorem map_inl_le_productIdeal :
    Ideal.map ((inl k R R' : R →ₐ[k] R ⊗[k] R') : R →+* R ⊗[k] R') I ≤
      productIdeal k R R' I I' :=
  Ideal.map_le_iff_le_comap.mpr fun _ hx ↦ inl_mem_productIdeal k R R' I I' hx

/-- The extension of `I'` along the right inclusion lands in the product ideal. -/
theorem map_inr_le_productIdeal :
    Ideal.map ((inr k R R' : R' →ₐ[k] R ⊗[k] R') : R' →+* R ⊗[k] R') I' ≤
      productIdeal k R R' I I' :=
  Ideal.map_le_iff_le_comap.mpr fun _ hy ↦ inr_mem_productIdeal k R R' I I' hy

/-- The map `N_{U/M} → N_{U×U'/M×M'}` of normal-sheaf coordinate rings induced by the left
inclusion. -/
def nsLeftHom :
    normalSheafRing R I →+* normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  nsMapOfMapLe I ((inl k R R' : R →ₐ[k] R ⊗[k] R') : R →+* R ⊗[k] R') _
    (map_inl_le_productIdeal k R R' I I')

/-- The map `N_{U'/M'} → N_{U×U'/M×M'}` of normal-sheaf coordinate rings induced by the right
inclusion. -/
def nsRightHom :
    normalSheafRing R' I' →+* normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  nsMapOfMapLe I' ((inr k R R' : R' →ₐ[k] R ⊗[k] R') : R' →+* R ⊗[k] R') _
    (map_inr_le_productIdeal k R R' I I')

/-- `nsLeftHom` in degree zero. -/
theorem nsLeftHom_algebraMap (r : R) :
    nsLeftHom k R R' I I' (algebraMap R (normalSheafRing R I) r) =
      algebraMap (R ⊗[k] R') (normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I'))
        (r ⊗ₜ[k] 1) :=
  nsMapOfMapLe_algebraMap I _ _ (map_inl_le_productIdeal k R R' I I') r

/-- `nsRightHom` in degree zero. -/
theorem nsRightHom_algebraMap (r : R') :
    nsRightHom k R R' I I' (algebraMap R' (normalSheafRing R' I') r) =
      algebraMap (R ⊗[k] R') (normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I'))
        (1 ⊗ₜ[k] r) :=
  nsMapOfMapLe_algebraMap I' _ _ (map_inr_le_productIdeal k R R' I I') r

/-- `nsLeftHom` on degree-one classes. -/
theorem nsLeftHom_nsClass (x : I) :
    nsLeftHom k R R' I I' (nsClass I x) =
      nsClass (productIdeal k R R' I I')
        ⟨(x : R) ⊗ₜ[k] 1, inl_mem_productIdeal k R R' I I' x.2⟩ :=
  nsMapOfMapLe_nsClass I _ _ (map_inl_le_productIdeal k R R' I I') x

/-- `nsRightHom` on degree-one classes. -/
theorem nsRightHom_nsClass (y : I') :
    nsRightHom k R R' I I' (nsClass I' y) =
      nsClass (productIdeal k R R' I I')
        ⟨1 ⊗ₜ[k] (y : R'), inr_mem_productIdeal k R R' I I' y.2⟩ :=
  nsMapOfMapLe_nsClass I' _ _ (map_inr_le_productIdeal k R R' I I') y

/-- The left map is a `k`-algebra map. -/
def nsLeft : normalSheafRing R I →ₐ[k]
    normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  { nsLeftHom k R R' I I' with
    commutes' := fun a ↦ by
      rw [IsScalarTower.algebraMap_apply k R (normalSheafRing R I)]
      change nsLeftHom k R R' I I' (algebraMap R (normalSheafRing R I) (algebraMap k R a)) = _
      rw [nsLeftHom_algebraMap]
      change algebraMap (R ⊗[k] R') _ (inl k R R' (algebraMap k R a)) = _
      rw [AlgHom.commutes, ← IsScalarTower.algebraMap_apply] }

/-- The right map is a `k`-algebra map. -/
def nsRight : normalSheafRing R' I' →ₐ[k]
    normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  { nsRightHom k R R' I I' with
    commutes' := fun a ↦ by
      rw [IsScalarTower.algebraMap_apply k R' (normalSheafRing R' I')]
      change nsRightHom k R R' I I' (algebraMap R' (normalSheafRing R' I') (algebraMap k R' a)) = _
      rw [nsRightHom_algebraMap]
      change algebraMap (R ⊗[k] R') _ (inr k R R' (algebraMap k R' a)) = _
      rw [AlgHom.commutes, ← IsScalarTower.algebraMap_apply] }

/-- **The comparison map for the affine normal sheaf of a product**: the `k`-algebra map
`N_{U/M} ⊗[k] N_{U'/M'} → N_{U×U'/M×M'}` sending `nsClass x ⊗ 1` to `nsClass (x ⊗ 1)` and
`1 ⊗ nsClass y` to `nsClass (1 ⊗ y)`. -/
def nsTensorToNs :
    normalSheafRing R I ⊗[k] normalSheafRing R' I' →ₐ[k]
      normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  Algebra.TensorProduct.lift (nsLeft k R R' I I') (nsRight k R R' I I') fun _ _ ↦ Commute.all _ _

@[simp]
theorem nsTensorToNs_tmul (u : normalSheafRing R I) (v : normalSheafRing R' I') :
    nsTensorToNs k R R' I I' (u ⊗ₜ[k] v) =
      nsLeftHom k R R' I I' u * nsRightHom k R R' I I' v :=
  Algebra.TensorProduct.lift_tmul _ _ _ _ _

/-- The comparison map on the left-hand degree-one generators. -/
theorem nsTensorToNs_nsClass_left (x : I) :
    nsTensorToNs k R R' I I' (nsClass I x ⊗ₜ[k] 1) =
      nsClass (productIdeal k R R' I I')
        ⟨(x : R) ⊗ₜ[k] 1, inl_mem_productIdeal k R R' I I' x.2⟩ := by
  rw [nsTensorToNs_tmul, map_one, mul_one, nsLeftHom_nsClass]

/-- The comparison map on the right-hand degree-one generators. -/
theorem nsTensorToNs_nsClass_right (y : I') :
    nsTensorToNs k R R' I I' (1 ⊗ₜ[k] nsClass I' y) =
      nsClass (productIdeal k R R' I I')
        ⟨1 ⊗ₜ[k] (y : R'), inr_mem_productIdeal k R R' I I' y.2⟩ := by
  rw [nsTensorToNs_tmul, map_one, one_mul, nsRightHom_nsClass]

/-! ### Surjectivity -/

/-- Degree-zero elements of the normal sheaf of the product are in the image of the
comparison map. -/
theorem algebraMap_mem_range (c : R ⊗[k] R') :
    algebraMap (R ⊗[k] R') (normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I')) c ∈
      RingHom.range (nsTensorToNs k R R' I I').toRingHom := by
  induction c using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact zero_mem _
  | tmul a b =>
    refine ⟨algebraMap R (normalSheafRing R I) a ⊗ₜ[k]
      algebraMap R' (normalSheafRing R' I') b, ?_⟩
    change nsTensorToNs k R R' I I' (_ ⊗ₜ[k] _) = _
    rw [nsTensorToNs_tmul, nsLeftHom_algebraMap, nsRightHom_algebraMap, ← map_mul,
      Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
  | add u v hu hv => rw [map_add]; exact add_mem hu hv

/-- Degree-one classes of the normal sheaf of the product are in the image of the comparison
map: the product ideal is generated by `I ⊗ 1` and `1 ⊗ I'`. -/
theorem nsClass_mem_range (x : productIdeal k R R' I I') :
    nsClass (productIdeal k R R' I I') x ∈
      RingHom.range (nsTensorToNs k R R' I I').toRingHom := by
  have hsub : Ideal.span ((inl k R R' '' (I : Set R)) ∪ (inr k R R' '' (I' : Set R'))) ≤
      productIdeal k R R' I I' := (productIdeal_eq_span k R R' I I').ge
  have key : ∀ c ∈ Ideal.span ((inl k R R' '' (I : Set R)) ∪ (inr k R R' '' (I' : Set R'))),
      ∀ hc : c ∈ productIdeal k R R' I I',
        nsClass (productIdeal k R R' I I') ⟨c, hc⟩ ∈
          RingHom.range (nsTensorToNs k R R' I I').toRingHom := by
    intro c hc
    induction hc using Submodule.span_induction with
    | mem z hz =>
      intro hc
      rcases hz with ⟨w, hw, rfl⟩ | ⟨w, hw, rfl⟩
      · refine ⟨nsClass I ⟨w, hw⟩ ⊗ₜ[k] 1, ?_⟩
        change nsTensorToNs k R R' I I' (nsClass I ⟨w, hw⟩ ⊗ₜ[k] 1) = _
        rw [nsTensorToNs_tmul, map_one, mul_one, nsLeftHom_nsClass]
        congr 1
      · refine ⟨1 ⊗ₜ[k] nsClass I' ⟨w, hw⟩, ?_⟩
        change nsTensorToNs k R R' I I' (1 ⊗ₜ[k] nsClass I' ⟨w, hw⟩) = _
        rw [nsTensorToNs_tmul, map_one, one_mul, nsRightHom_nsClass]
        congr 1
    | zero =>
      intro hc
      have hz : (⟨0, hc⟩ : productIdeal k R R' I I') = 0 := rfl
      rw [hz, map_zero]
      exact zero_mem _
    | add u v hu hv ihu ihv =>
      intro hc
      have hz : (⟨u + v, hc⟩ : productIdeal k R R' I I') = ⟨u, hsub hu⟩ + ⟨v, hsub hv⟩ := rfl
      rw [hz, map_add]
      exact add_mem (ihu _) (ihv _)
    | smul d u hu ihu =>
      intro hc
      have hz : (⟨d • u, hc⟩ : productIdeal k R R' I I') = d • ⟨u, hsub hu⟩ := rfl
      rw [hz, nsClass_smul]
      exact mul_mem (algebraMap_mem_range k R R' I I' d) (ihu _)
  exact key (x : R ⊗[k] R') ((productIdeal_eq_span k R R' I I') ▸ x.2) x.2

/-- **The comparison map for the normal sheaf of a product is surjective.** -/
theorem nsTensorToNs_surjective : Function.Surjective (nsTensorToNs k R R' I I') :=
  ns_surjective (productIdeal k R R' I I') (nsTensorToNs k R R' I I').toRingHom
    (algebraMap_mem_range k R R' I I')
    (nsClass_mem_range k R R' I I')

/-! ### Compatibility with the closed immersion of the normal cone -/

/-- The closed immersion `C_{U/M} ⊆ N_{U/M}` of the affine normal cone into the normal sheaf,
read as a map of `k`-algebras. -/
def nsToGrK : normalSheafRing R I →ₐ[k] AffineNormalCone.associatedGradedRing R I :=
  (nsToGr R I).restrictScalars k

@[simp]
theorem nsToGrK_apply (u : normalSheafRing R I) : nsToGrK k R I u = nsToGr R I u := rfl

/-- The left cone map in degree zero. -/
theorem grLeft_algebraMap (r : R) :
    grLeft k R R' I I' (algebraMap R (AffineNormalCone.associatedGradedRing R I) r) =
      algebraMap (R ⊗[k] R')
        (AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I'))
        (r ⊗ₜ[k] 1) := by
  change grLeft k R R' I I' (Ideal.Quotient.mk _ (algebraMap R (reesAlgebra I) r)) = _
  rw [grLeft_mk, reesLeftAlg_algebraMap]
  rfl

/-- The right cone map in degree zero. -/
theorem grRight_algebraMap (r : R') :
    grRight k R R' I I' (algebraMap R' (AffineNormalCone.associatedGradedRing R' I') r) =
      algebraMap (R ⊗[k] R')
        (AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I'))
        (1 ⊗ₜ[k] r) := by
  change grRight k R R' I I' (Ideal.Quotient.mk _ (algebraMap R' (reesAlgebra I') r)) = _
  rw [grRight_mk, reesRightAlg_algebraMap]
  rfl

/-- The left inclusion commutes with the closed immersion `C ⊆ N`. -/
theorem nsToGr_nsLeftHom (u : normalSheafRing R I) :
    nsToGr (R ⊗[k] R') (productIdeal k R R' I I') (nsLeftHom k R R' I I' u) =
      grLeft k R R' I I' (nsToGr R I u) := by
  have hcomp : (nsToGr (R ⊗[k] R') (productIdeal k R R' I I')).toRingHom.comp
      (nsLeftHom k R R' I I') =
        (grLeft k R R' I I').toRingHom.comp (nsToGr R I).toRingHom := by
    refine ns_ringHom_ext I (fun r ↦ ?_) (fun x ↦ ?_)
    · change nsToGr (R ⊗[k] R') (productIdeal k R R' I I')
          (nsLeftHom k R R' I I' (algebraMap R (normalSheafRing R I) r)) =
        grLeft k R R' I I' (nsToGr R I (algebraMap R (normalSheafRing R I) r))
      rw [nsLeftHom_algebraMap, AlgHom.commutes, AlgHom.commutes, grLeft_algebraMap]
    · change nsToGr (R ⊗[k] R') (productIdeal k R R' I I')
          (nsLeftHom k R R' I I' (nsClass I x)) =
        grLeft k R R' I I' (nsToGr R I (nsClass I x))
      rw [nsLeftHom_nsClass, nsToGr_nsClass, nsToGr_nsClass]
      have h := grTensorToGr_degreeOne_left k R R' I I' x
      rw [grTensorToGr_tmul, map_one (grRight k R R' I I'), mul_one,
        AffineNormalCone.conormalToAssociatedGraded_toCotangent,
        AffineNormalCone.conormalToAssociatedGraded_toCotangent] at h
      rw [degreeOneRaw_eq_mk, degreeOneRaw_eq_mk, h]
      rfl
  exact RingHom.congr_fun hcomp u

/-- The right inclusion commutes with the closed immersion `C ⊆ N`. -/
theorem nsToGr_nsRightHom (v : normalSheafRing R' I') :
    nsToGr (R ⊗[k] R') (productIdeal k R R' I I') (nsRightHom k R R' I I' v) =
      grRight k R R' I I' (nsToGr R' I' v) := by
  have hcomp : (nsToGr (R ⊗[k] R') (productIdeal k R R' I I')).toRingHom.comp
      (nsRightHom k R R' I I') =
        (grRight k R R' I I').toRingHom.comp (nsToGr R' I').toRingHom := by
    refine ns_ringHom_ext I' (fun r ↦ ?_) (fun y ↦ ?_)
    · change nsToGr (R ⊗[k] R') (productIdeal k R R' I I')
          (nsRightHom k R R' I I' (algebraMap R' (normalSheafRing R' I') r)) =
        grRight k R R' I I' (nsToGr R' I' (algebraMap R' (normalSheafRing R' I') r))
      rw [nsRightHom_algebraMap, AlgHom.commutes, AlgHom.commutes, grRight_algebraMap]
    · change nsToGr (R ⊗[k] R') (productIdeal k R R' I I')
          (nsRightHom k R R' I I' (nsClass I' y)) =
        grRight k R R' I I' (nsToGr R' I' (nsClass I' y))
      rw [nsRightHom_nsClass, nsToGr_nsClass, nsToGr_nsClass]
      have h := grTensorToGr_degreeOne_right k R R' I I' y
      rw [grTensorToGr_tmul, map_one (grLeft k R R' I I'), one_mul,
        AffineNormalCone.conormalToAssociatedGraded_toCotangent,
        AffineNormalCone.conormalToAssociatedGraded_toCotangent] at h
      rw [degreeOneRaw_eq_mk, degreeOneRaw_eq_mk, h]
      rfl
  exact RingHom.congr_fun hcomp v

/-- **The product decomposition is compatible with the closed immersion `C ⊆ N`.**  The square
formed by `nsTensorToNs`, `grTensorToGr` and the two closed immersions `nsToGr` commutes. -/
theorem nsToGrK_comp_nsTensorToNs :
    (nsToGrK k (R ⊗[k] R') (productIdeal k R R' I I')).comp (nsTensorToNs k R R' I I') =
      (grTensorToGr k R R' I I').comp
        (Algebra.TensorProduct.map (nsToGrK k R I) (nsToGrK k R' I')) := by
  refine Algebra.TensorProduct.ext' fun u v ↦ ?_
  rw [AlgHom.comp_apply, AlgHom.comp_apply, nsTensorToNs_tmul, Algebra.TensorProduct.map_tmul,
    grTensorToGr_tmul]
  change nsToGr (R ⊗[k] R') (productIdeal k R R' I I')
      (nsLeftHom k R R' I I' u * nsRightHom k R R' I I' v) = _
  rw [map_mul (nsToGr (R ⊗[k] R') (productIdeal k R R' I I')), nsToGr_nsLeftHom,
    nsToGr_nsRightHom]
  rfl

/-- The commuting square of `nsToGrK_comp_nsTensorToNs`, read pointwise. -/
theorem nsToGr_nsTensorToNs (z : normalSheafRing R I ⊗[k] normalSheafRing R' I') :
    nsToGr (R ⊗[k] R') (productIdeal k R R' I I') (nsTensorToNs k R R' I I' z) =
      grTensorToGr k R R' I I'
        (Algebra.TensorProduct.map (nsToGrK k R I) (nsToGrK k R' I') z) :=
  AlgHom.congr_fun (nsToGrK_comp_nsTensorToNs k R R' I I') z

end Comparison

/-! ### Injectivity -/

section Injectivity

variable (k : Type u) [Field k] (R : Type u) [CommRing R] [Algebra k R]
  (R' : Type u) [CommRing R'] [Algebra k R'] (I : Ideal R) (I' : Ideal R')

/-- The degree-zero part of the inverse comparison map: the tensor product of the two
projections `R → N_{U/M}`, `R' → N_{U'/M'}`. -/
def nsBase : R ⊗[k] R' →ₐ[k] normalSheafRing R I ⊗[k] normalSheafRing R' I' :=
  Algebra.TensorProduct.map (IsScalarTower.toAlgHom k R (normalSheafRing R I))
    (IsScalarTower.toAlgHom k R' (normalSheafRing R' I'))

@[simp]
theorem nsBase_tmul (a : R) (b : R') :
    nsBase k R R' I I' (a ⊗ₜ[k] b) =
      algebraMap R (normalSheafRing R I) a ⊗ₜ[k] algebraMap R' (normalSheafRing R' I') b :=
  Algebra.TensorProduct.map_tmul _ _ _ _

/-- The degree-zero part of the inverse kills the product ideal. -/
theorem nsBase_eq_zero_of_mem {c : R ⊗[k] R'} (hc : c ∈ productIdeal k R R' I I') :
    nsBase k R R' I I' c = 0 := by
  have hle : productIdeal k R R' I I' ≤ RingHom.ker (nsBase k R R' I I').toRingHom := by
    rw [productIdeal_eq_span]
    refine Ideal.span_le.mpr ?_
    rintro z (⟨w, hw, rfl⟩ | ⟨w, hw, rfl⟩)
    · change nsBase k R R' I I' (w ⊗ₜ[k] (1 : R')) = 0
      rw [nsBase_tmul, algebraMap_ns_eq_zero I hw, TensorProduct.zero_tmul]
    · change nsBase k R R' I I' ((1 : R) ⊗ₜ[k] w) = 0
      rw [nsBase_tmul, algebraMap_ns_eq_zero I' hw, TensorProduct.tmul_zero]
  exact RingHom.mem_ker.mp (hle hc)

set_option maxHeartbeats 1000000 in
-- The unifier has to see through `Sym_A(J)/J·Sym_A(J)` (a quotient of a `RingCon` quotient of a
-- tensor algebra) tensored with another such quotient; the rewriting steps below are slow.
/-- **The inverse of the comparison map exists.**  Over a field, choosing `k`-linear
retractions `R → I` and `R' → I'` (the ideals are `k`-subspaces, so they are direct summands)
produces a `k`-linear map `Λ` on `R ⊗[k] R'` whose restriction to `J = I ⊗ R' + R ⊗ I'` is
`nsBase`-semilinear; `ConeRefinement.exists_nsRingHom` then yields a ring map backwards.  The
formula is `Λ (a ⊗ b) = [π a] ⊗ [b] + [a] ⊗ [π' b]`, which is independent of the retractions on
`J` because `Λ` is determined there by `Λ (x ⊗ 1) = nsClass x ⊗ 1` and
`Λ (1 ⊗ y) = 1 ⊗ nsClass y`. -/
theorem exists_nsInverse :
    ∃ ψ : normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') →+*
        normalSheafRing R I ⊗[k] normalSheafRing R' I',
      (∀ c : R ⊗[k] R', ψ (algebraMap (R ⊗[k] R')
            (normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I')) c) =
          nsBase k R R' I I' c) ∧
        (∀ x : I, ψ (nsClass (productIdeal k R R' I I')
            ⟨(x : R) ⊗ₜ[k] 1, inl_mem_productIdeal k R R' I I' x.2⟩) =
          nsClass I x ⊗ₜ[k] 1) ∧
        (∀ y : I', ψ (nsClass (productIdeal k R R' I I')
            ⟨1 ⊗ₜ[k] (y : R'), inr_mem_productIdeal k R R' I I' y.2⟩) =
          1 ⊗ₜ[k] nsClass I' y) := by
  classical
  obtain ⟨π, hπ⟩ := (LinearMap.restrictScalars k I.subtype).exists_leftInverse_of_injective
    (LinearMap.ker_eq_bot.mpr fun _ _ h ↦ Subtype.ext h)
  obtain ⟨π', hπ'⟩ := (LinearMap.restrictScalars k I'.subtype).exists_leftInverse_of_injective
    (LinearMap.ker_eq_bot.mpr fun _ _ h ↦ Subtype.ext h)
  have hπa : ∀ u : I, π (u : R) = u := fun u ↦ LinearMap.congr_fun hπ u
  have hπa' : ∀ u : I', π' (u : R') = u := fun u ↦ LinearMap.congr_fun hπ' u
  let Λ : R ⊗[k] R' →ₗ[k] normalSheafRing R I ⊗[k] normalSheafRing R' I' :=
    TensorProduct.map ((LinearMap.restrictScalars k (nsClass I)).comp π)
        (IsScalarTower.toAlgHom k R' (normalSheafRing R' I')).toLinearMap +
      TensorProduct.map (IsScalarTower.toAlgHom k R (normalSheafRing R I)).toLinearMap
        ((LinearMap.restrictScalars k (nsClass I')).comp π')
  have hΛ : ∀ (a : R) (b : R'), Λ (a ⊗ₜ[k] b) =
      nsClass I (π a) ⊗ₜ[k] algebraMap R' (normalSheafRing R' I') b +
        algebraMap R (normalSheafRing R I) a ⊗ₜ[k] nsClass I' (π' b) := by
    intro a b
    change TensorProduct.map ((LinearMap.restrictScalars k (nsClass I)).comp π)
        (IsScalarTower.toAlgHom k R' (normalSheafRing R' I')).toLinearMap (a ⊗ₜ[k] b) +
      TensorProduct.map (IsScalarTower.toAlgHom k R (normalSheafRing R I)).toLinearMap
        ((LinearMap.restrictScalars k (nsClass I')).comp π') (a ⊗ₜ[k] b) = _
    rw [TensorProduct.map_tmul, TensorProduct.map_tmul]
    rfl
  -- the key computation on the left-hand generators
  have hA : ∀ (c : R ⊗[k] R') (x : I),
      Λ (c * ((x : R) ⊗ₜ[k] (1 : R'))) =
        nsBase k R R' I I' c * (nsClass I x ⊗ₜ[k] (1 : normalSheafRing R' I')) := by
    intro c x
    induction c using TensorProduct.induction_on with
    | zero =>
      rw [zero_mul, LinearMap.map_zero Λ, map_zero (nsBase k R R' I I'), zero_mul]
    | tmul a b =>
      have hr : nsBase k R R' I I' (a ⊗ₜ[k] b) *
          (nsClass I x ⊗ₜ[k] (1 : normalSheafRing R' I')) =
            (algebraMap R (normalSheafRing R I) a * nsClass I x) ⊗ₜ[k]
              algebraMap R' (normalSheafRing R' I') b := by
        rw [nsBase_tmul, Algebra.TensorProduct.tmul_mul_tmul,
          mul_one (algebraMap R' (normalSheafRing R' I') b)]
      rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one b, hΛ, hr]
      have hx : a * (x : R) = ((a • x : I) : R) := rfl
      have h1 : nsClass I (π (a * (x : R))) =
          algebraMap R (normalSheafRing R I) a * nsClass I x := by
        rw [hx, hπa, nsClass_smul]
      have h2 : algebraMap R (normalSheafRing R I) (a * (x : R)) = 0 :=
        algebraMap_ns_eq_zero I (Ideal.mul_mem_left I a x.2)
      rw [h1, h2, TensorProduct.zero_tmul, add_zero]
    | add c d hc hd =>
      rw [add_mul, LinearMap.map_add Λ, hc, hd, map_add (nsBase k R R' I I'), add_mul]
  -- the key computation on the right-hand generators
  have hB : ∀ (c : R ⊗[k] R') (y : I'),
      Λ (c * ((1 : R) ⊗ₜ[k] (y : R'))) =
        nsBase k R R' I I' c * ((1 : normalSheafRing R I) ⊗ₜ[k] nsClass I' y) := by
    intro c y
    induction c using TensorProduct.induction_on with
    | zero =>
      rw [zero_mul, LinearMap.map_zero Λ, map_zero (nsBase k R R' I I'), zero_mul]
    | tmul a b =>
      have hr : nsBase k R R' I I' (a ⊗ₜ[k] b) *
          ((1 : normalSheafRing R I) ⊗ₜ[k] nsClass I' y) =
            algebraMap R (normalSheafRing R I) a ⊗ₜ[k]
              (algebraMap R' (normalSheafRing R' I') b * nsClass I' y) := by
        rw [nsBase_tmul, Algebra.TensorProduct.tmul_mul_tmul,
          mul_one (algebraMap R (normalSheafRing R I) a)]
      rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one a, hΛ, hr]
      have hy : b * (y : R') = ((b • y : I') : R') := rfl
      have h1 : nsClass I' (π' (b * (y : R'))) =
          algebraMap R' (normalSheafRing R' I') b * nsClass I' y := by
        rw [hy, hπa', nsClass_smul]
      have h2 : algebraMap R' (normalSheafRing R' I') (b * (y : R')) = 0 :=
        algebraMap_ns_eq_zero I' (Ideal.mul_mem_left I' b y.2)
      rw [h1, h2, TensorProduct.tmul_zero, zero_add]
    | add c d hc hd =>
      rw [add_mul, LinearMap.map_add Λ, hc, hd, map_add (nsBase k R R' I I'), add_mul]
  -- semilinearity of `Λ` restricted to the product ideal
  have hsemi : ∀ z ∈ productIdeal k R R' I I', ∀ c : R ⊗[k] R',
      Λ (c * z) = nsBase k R R' I I' c * Λ z := by
    have hspan : ∀ z ∈ Ideal.span ((inl k R R' '' (I : Set R)) ∪ (inr k R R' '' (I' : Set R'))),
        ∀ c : R ⊗[k] R', Λ (c * z) = nsBase k R R' I I' c * Λ z := by
      intro z hz
      induction hz using Submodule.span_induction with
      | mem w hw =>
        rcases hw with ⟨v, hv, rfl⟩ | ⟨v, hv, rfl⟩
        · have hval : Λ (((⟨v, hv⟩ : I) : R) ⊗ₜ[k] (1 : R')) =
              nsClass I ⟨v, hv⟩ ⊗ₜ[k] (1 : normalSheafRing R' I') := by
            have h := hA 1 ⟨v, hv⟩
            rwa [one_mul, map_one (nsBase k R R' I I'), one_mul] at h
          intro c
          change Λ (c * (((⟨v, hv⟩ : I) : R) ⊗ₜ[k] (1 : R'))) =
            nsBase k R R' I I' c * Λ (((⟨v, hv⟩ : I) : R) ⊗ₜ[k] (1 : R'))
          rw [hA c ⟨v, hv⟩, hval]
        · have hval : Λ ((1 : R) ⊗ₜ[k] ((⟨v, hv⟩ : I') : R')) =
              (1 : normalSheafRing R I) ⊗ₜ[k] nsClass I' ⟨v, hv⟩ := by
            have h := hB 1 ⟨v, hv⟩
            rwa [one_mul, map_one (nsBase k R R' I I'), one_mul] at h
          intro c
          change Λ (c * ((1 : R) ⊗ₜ[k] ((⟨v, hv⟩ : I') : R'))) =
            nsBase k R R' I I' c * Λ ((1 : R) ⊗ₜ[k] ((⟨v, hv⟩ : I') : R'))
          rw [hB c ⟨v, hv⟩, hval]
      | zero => intro c; rw [mul_zero, LinearMap.map_zero Λ, mul_zero]
      | add u v _ _ ihu ihv =>
        intro c
        rw [mul_add, LinearMap.map_add Λ, LinearMap.map_add Λ, ihu, ihv, mul_add]
      | smul d u _ ihu =>
        intro c
        rw [smul_eq_mul, ← mul_assoc, ihu, ihu, map_mul (nsBase k R R' I I'), mul_assoc]
    intro z hz
    exact hspan z ((productIdeal_eq_span k R R' I I') ▸ hz)
  obtain ⟨ψ, hψ0, hψ1⟩ := exists_nsRingHom (productIdeal k R R' I I')
    (nsBase k R R' I I').toRingHom (fun z ↦ Λ (z : R ⊗[k] R'))
    (fun z w ↦ by
      change Λ ((z : R ⊗[k] R') + (w : R ⊗[k] R')) = _
      rw [LinearMap.map_add Λ])
    (fun c z ↦ by
      change Λ (c * (z : R ⊗[k] R')) = _
      exact hsemi (z : R ⊗[k] R') z.2 c)
    (fun _ hc ↦ nsBase_eq_zero_of_mem k R R' I I' hc)
  refine ⟨ψ, hψ0, fun x ↦ ?_, fun y ↦ ?_⟩
  · rw [hψ1]
    have h := hA 1 x
    rwa [one_mul, map_one (nsBase k R R' I I'), one_mul] at h
  · rw [hψ1]
    have h := hB 1 y
    rwa [one_mul, map_one (nsBase k R R' I I'), one_mul] at h

/-- **The comparison map for the normal sheaf of a product is injective** over a field. -/
theorem nsTensorToNs_injective : Function.Injective (nsTensorToNs k R R' I I') := by
  obtain ⟨ψ, h0, h1, h2⟩ := exists_nsInverse k R R' I I'
  have hleft : ∀ u : normalSheafRing R I, ψ (nsLeftHom k R R' I I' u) = u ⊗ₜ[k] 1 := by
    have hcomp : ψ.comp (nsLeftHom k R R' I I') =
        (Algebra.TensorProduct.includeLeft : normalSheafRing R I →ₐ[k]
          normalSheafRing R I ⊗[k] normalSheafRing R' I').toRingHom := by
      refine ns_ringHom_ext I (fun r ↦ ?_) (fun x ↦ ?_)
      · change ψ (nsLeftHom k R R' I I' (algebraMap R (normalSheafRing R I) r)) = _
        rw [nsLeftHom_algebraMap, h0, nsBase_tmul, map_one]
        rfl
      · change ψ (nsLeftHom k R R' I I' (nsClass I x)) = _
        rw [nsLeftHom_nsClass, h1]
        rfl
    intro u
    exact RingHom.congr_fun hcomp u
  have hright : ∀ v : normalSheafRing R' I', ψ (nsRightHom k R R' I I' v) = 1 ⊗ₜ[k] v := by
    have hcomp : ψ.comp (nsRightHom k R R' I I') =
        (Algebra.TensorProduct.includeRight : normalSheafRing R' I' →ₐ[k]
          normalSheafRing R I ⊗[k] normalSheafRing R' I').toRingHom := by
      refine ns_ringHom_ext I' (fun r ↦ ?_) (fun y ↦ ?_)
      · change ψ (nsRightHom k R R' I I' (algebraMap R' (normalSheafRing R' I') r)) = _
        rw [nsRightHom_algebraMap, h0, nsBase_tmul, map_one]
        rfl
      · change ψ (nsRightHom k R R' I I' (nsClass I' y)) = _
        rw [nsRightHom_nsClass, h2]
        rfl
    intro v
    exact RingHom.congr_fun hcomp v
  have hkey : ∀ z : normalSheafRing R I ⊗[k] normalSheafRing R' I',
      ψ (nsTensorToNs k R R' I I' z) = z := by
    intro z
    induction z using TensorProduct.induction_on with
    | zero => rw [map_zero (nsTensorToNs k R R' I I'), map_zero ψ]
    | tmul u v =>
      rw [nsTensorToNs_tmul, map_mul ψ, hleft, hright, Algebra.TensorProduct.tmul_mul_tmul,
        mul_one, one_mul]
    | add u v hu hv => rw [map_add (nsTensorToNs k R R' I I'), map_add ψ, hu, hv]
  exact Function.LeftInverse.injective hkey

/-- **The product formula for the affine normal sheaf over a field**:
`N_{U/M} ⊗[k] N_{U'/M'} ≃ N_{U×U'/M×M'}`, that is, `N_{U×U'/M×M'} ≅ N_{U/M} × N_{U'/M'}`. -/
def nsTensorEquiv :
    normalSheafRing R I ⊗[k] normalSheafRing R' I' ≃ₐ[k]
      normalSheafRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  AlgEquiv.ofBijective (nsTensorToNs k R R' I I')
    ⟨nsTensorToNs_injective k R R' I I', nsTensorToNs_surjective k R R' I I'⟩

@[simp]
theorem nsTensorEquiv_apply (z : normalSheafRing R I ⊗[k] normalSheafRing R' I') :
    nsTensorEquiv k R R' I I' z = nsTensorToNs k R R' I I' z := rfl

/-- Under the two product decompositions `nsTensorEquiv` and `grTensorEquivOfField`, the closed
immersion `C_{U×U'/M×M'} ⊆ N_{U×U'/M×M'}` is the product of the closed immersions
`C_{U/M} ⊆ N_{U/M}` and `C_{U'/M'} ⊆ N_{U'/M'}`. -/
theorem nsToGr_nsTensorEquiv (z : normalSheafRing R I ⊗[k] normalSheafRing R' I') :
    nsToGr (R ⊗[k] R') (productIdeal k R R' I I') (nsTensorEquiv k R R' I I' z) =
      grTensorEquivOfField k R R' I I'
        (Algebra.TensorProduct.map (nsToGrK k R I) (nsToGrK k R' I') z) :=
  nsToGr_nsTensorToNs k R R' I I' z

end Injectivity

end

end AffineNormalSheafProduct

end GromovWitten.AlgebraicGeometry
