/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.NormalConeGlobal
import GromovWitten.AlgebraicGeometry.Cones.RegularSequence

/-!
# The normal cone of a regular immersion of schemes

Let `I` be a quasi-coherent ideal sheaf on a scheme `X` which, on every affine open `U`, is
generated by a quasi-regular (for instance, a regular) sequence.  This file proves that the
canonical closed immersion

`C_{Z/X} = Spec_X gr_I 𝒪_X ⟶ N_{Z/X} = Spec_X Sym(I/I²)`

of `GromovWitten.AlgebraicGeometry.NormalCone.toNormalSheaf` is an isomorphism.

## Main results

* `AffineNormalCone.QuasiregularGenerators`: a finite quasi-regular sequence generating an
  ideal.  The affine results of `Cones/RegularSequence.lean` are re-proved from quasi-regularity
  alone (that file's proof of injectivity only uses `RegularGenerators.isQuasiregular`), and
  `AffineNormalCone.RegularGenerators.toQuasiregular` shows a regular sequence is an instance.
* `AffineNormalCone.QuasiregularGenerators.nsToGr_bijective`: the affine comparison
  `Sym_A(I)/I·Sym_A(I) ⟶ gr_I(A)` used in the global gluing is bijective.
* `NormalCone.IsQuasiregularIdealSheaf`, `NormalCone.IsRegularIdealSheaf`: the two global
  predicates, on *all* affine opens.
* `NormalCone.isIso_toNormalSheaf`: under either predicate the global closed immersion
  `C_{Z/X} ⟶ N_{Z/X}` is an isomorphism, and `NormalCone.isoNormalSheaf` is the resulting
  isomorphism of schemes over `X`.
* `AffineNormalCone.nsToGr_bijective_of_flat`: the affine comparison is stable under flat base
  change, so the affine-open-wise bijectivity condition is inherited by smaller affine opens
  (`NormalCone.bijective_nsToGr_of_le`).
* `NormalCone.bijective_nsToGr_of_cover`: the condition also *descends* along an affine open
  cover, so `NormalCone.isIso_toNormalSheaf_of_cover` and
  `NormalCone.isIso_toNormalSheaf_of_forall_mem_cover` only need quasi-regular generators on the
  members of one affine open cover of `X`.
* `AffineNormalCone.homogeneous_one_eq_range`, `AffineNormalCone.abelianHull_symCongr`: the
  degree-one part of the cone `Spec gr_I(R)` over its base `Spec (R/I)` is the conormal module
  `I/I²`, and the canonical map `Sym_{R/I}(I/I²) → gr_I(R)` is the abelian hull map of
  `Cones/Graded.lean`; globally, `NormalCone.isPullback_abelianHull` exhibits the abelian hull
  over every affine open.
* `RelativeSpec.toSubscheme`: a relative `Spec` whose structure maps are killed by `I` maps to
  the closed subscheme `Z = V(I)`; `NormalCone.toSubscheme` and `NormalSheaf.toSubscheme` are
  the resulting factorizations of `C_{Z/X} ⟶ X` and `N_{Z/X} ⟶ X` through `Z`.

-/

open CategoryTheory Limits AlgebraicGeometry TopologicalSpace
open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

open GlobalBlowup RelativeSpec

universe u

noncomputable section

/-! ### An elementary localisation criterion -/

/-- A module element which is killed by a power of each member of a family spanning the unit
ideal is zero.  This is the elementary form of "vanishing is local on the base" used for the
descent of the regular-immersion comparison along an affine open cover. -/
theorem eq_zero_of_forall_exists_pow_smul_eq_zero {A : Type*} [CommRing A] {M : Type*}
    [AddCommGroup M] [Module A M] {s : Set A} (hs : Ideal.span s = ⊤) {z : M}
    (h : ∀ r ∈ s, ∃ n : ℕ, r ^ n • z = 0) : z = 0 := by
  suffices hsuff : Module.eqIdeal A z 0 = ⊤ by
    simpa [Module.eqIdeal] using (Ideal.eq_top_iff_one _).mp hsuff
  by_contra hne
  obtain ⟨r, hrs, hdisj⟩ := Ideal.exists_disjoint_powers_of_span_eq_top s hs _ hne
  obtain ⟨n, hn⟩ := h r hrs
  exact Set.disjoint_left.mp hdisj (by simpa [Module.eqIdeal] using hn) ⟨n, rfl⟩

namespace AffineNormalCone

/-! ### Quasi-regular generators -/

section Quasiregular

open MvPolynomial

/-- Input data for the regular-immersion comparison, in its weakest useful form: a finite family
of elements of `R` which is *quasi-regular* in the sense of `GromovWitten.Algebra.IsQuasiregular`
and which generates `I`.

This is the hypothesis which the proofs of `Cones/RegularSequence.lean` actually use; a genuine
regular sequence gives one through `AffineNormalCone.RegularGenerators.toQuasiregular`. -/
structure QuasiregularGenerators (R : Type u) [CommRing R] (I : Ideal R) where
  /-- The number of generators. -/
  length : ℕ
  /-- The generators themselves. -/
  gen : Fin length → R
  /-- They form a quasi-regular sequence. -/
  isQuasiregular : GromovWitten.Algebra.IsQuasiregular gen
  /-- They generate `I`. -/
  span_eq : Ideal.span (Set.range gen) = I

/-- A regular sequence generating `I` is in particular a quasi-regular one. -/
def RegularGenerators.toQuasiregular {R : Type u} [CommRing R] {I : Ideal R}
    (x : RegularGenerators R I) : QuasiregularGenerators R I where
  length := x.length
  gen := x.gen
  isQuasiregular := x.isQuasiregular
  span_eq := x.span_eq

namespace QuasiregularGenerators

variable {R : Type u} [CommRing R] {I : Ideal R} (x : QuasiregularGenerators R I)

theorem gen_mem (i : Fin x.length) : x.gen i ∈ I := by
  have h : x.gen i ∈ Ideal.span (Set.range x.gen) := Ideal.subset_span ⟨i, rfl⟩
  rwa [x.span_eq] at h

/-- A generator, viewed as an element of the ideal `I`. -/
def genMem (i : Fin x.length) : I := ⟨x.gen i, x.gen_mem i⟩

/-- The conormal class of a generator. -/
def conormalGen (i : Fin x.length) : I.Cotangent :=
  I.toCotangent (x.genMem i)

/-- The canonical map from the polynomial ring onto the normal-sheaf coordinate ring, sending
`X i` to the conormal class of the `i`-th generator. -/
def symLift :
    MvPolynomial (Fin x.length) R →+* normalSheafCoordinateRing R I :=
  MvPolynomial.eval₂Hom
    ((algebraMap (R ⧸ I) (normalSheafCoordinateRing R I)).comp (Ideal.Quotient.mk I))
    (fun i => SymmetricAlgebra.ι (R ⧸ I) I.Cotangent (x.conormalGen i))

@[simp]
theorem symLift_C (r : R) :
    x.symLift (C r) =
      algebraMap (R ⧸ I) (normalSheafCoordinateRing R I) (Ideal.Quotient.mk I r) :=
  eval₂Hom_C _ _ r

@[simp]
theorem symLift_X (i : Fin x.length) :
    x.symLift (X i) = SymmetricAlgebra.ι (R ⧸ I) I.Cotangent (x.conormalGen i) :=
  eval₂Hom_X' _ _ i

/-- The canonical map from the polynomial ring into the Rees algebra, sending `X i` to the
degree-one Rees element `gen i * t`. -/
def reesLift :
    MvPolynomial (Fin x.length) R →+* reesAlgebra I :=
  MvPolynomial.eval₂Hom (algebraMap R (reesAlgebra I))
    (fun i => degreeOneRees R I (x.genMem i))

@[simp]
theorem reesLift_C (r : R) : x.reesLift (C r) = algebraMap R (reesAlgebra I) r :=
  eval₂Hom_C _ _ r

@[simp]
theorem reesLift_X (i : Fin x.length) :
    x.reesLift (X i) = degreeOneRees R I (x.genMem i) :=
  eval₂Hom_X' _ _ i

/-- The same substitution, but landing in the ambient polynomial ring. -/
def polyLift : MvPolynomial (Fin x.length) R →+* Polynomial R :=
  MvPolynomial.eval₂Hom Polynomial.C
    (fun i => Polynomial.C (x.gen i) * Polynomial.X)

@[simp]
theorem polyLift_C (r : R) : x.polyLift (C r) = Polynomial.C r := eval₂Hom_C _ _ r

@[simp]
theorem polyLift_X (i : Fin x.length) :
    x.polyLift (X i) = Polynomial.C (x.gen i) * Polynomial.X := eval₂Hom_X' _ _ i

/-- The Rees lift is the polynomial lift, read inside `R[X]`. -/
theorem coe_reesLift (p : MvPolynomial (Fin x.length) R) :
    ((x.reesLift p : reesAlgebra I) : Polynomial R) = x.polyLift p := by
  have hcomp : ((reesAlgebra I).val.toRingHom).comp x.reesLift = x.polyLift := by
    refine MvPolynomial.ringHom_ext (fun r => ?_) (fun i => ?_)
    · rw [RingHom.comp_apply, reesLift_C, polyLift_C]
      rfl
    · rw [RingHom.comp_apply, reesLift_X, polyLift_X]
      change (Polynomial.monomial 1 (x.gen i) : Polynomial R) = _
      rw [← Polynomial.C_mul_X_pow_eq_monomial, pow_one]
  exact congrArg (fun f => f p) hcomp

/-- The canonical map onto the normal-sheaf coordinate ring is surjective: the symmetric algebra
is generated over `R/I` by the conormal classes of the chosen generators. -/
theorem symLift_surjective : Function.Surjective x.symLift := by
  intro z
  induction z using SymmetricAlgebra.induction with
  | algebraMap r =>
      obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
      exact ⟨C r, x.symLift_C r⟩
  | ι m =>
      obtain ⟨y, rfl⟩ := I.toCotangent_surjective m
      have hy : (y : R) ∈ Ideal.span (Set.range x.gen) := by
        rw [x.span_eq]
        exact y.2
      obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun R).1 hy
      refine ⟨∑ i, C (c i) * X i, ?_⟩
      have hy' : y = ∑ i, c i • x.genMem i := by
        apply Subtype.ext
        simpa [genMem] using hc.symm
      have hcot : I.toCotangent y
          = ∑ i, (algebraMap R (R ⧸ I) (c i)) • x.conormalGen i := by
        rw [hy', map_sum]
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [map_smul, algebraMap_smul]
        rfl
      rw [map_sum, hcot, map_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [map_mul, symLift_C, symLift_X, ← Algebra.smul_def, map_smul,
        Ideal.Quotient.algebraMap_eq]
  | mul a b ha hb =>
      obtain ⟨p, rfl⟩ := ha
      obtain ⟨q, rfl⟩ := hb
      exact ⟨p * q, map_mul _ _ _⟩
  | add a b ha hb =>
      obtain ⟨p, rfl⟩ := ha
      obtain ⟨q, rfl⟩ := hb
      exact ⟨p + q, map_add _ _ _⟩

/-- The canonical normal-sheaf coordinate map, precomposed with the polynomial presentation of
the symmetric algebra, is the Rees substitution followed by the quotient map. -/
theorem normalSheafCoordinateMap_comp_symLift :
    (normalSheafCoordinateMap R I).comp x.symLift
      = (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)).comp x.reesLift := by
  refine MvPolynomial.ringHom_ext (fun r => ?_) (fun i => ?_)
  · rw [RingHom.comp_apply, RingHom.comp_apply, symLift_C, reesLift_C,
      normalSheafCoordinateMap_base]
    rfl
  · rw [RingHom.comp_apply, RingHom.comp_apply, symLift_X, reesLift_X,
      normalSheafCoordinateMap_ι, conormalGen, conormalToAssociatedGraded_toCotangent]

/-- The `m`-th coefficient of the Rees substitution of `p` is the value at the generators of the
degree-`m` homogeneous component of `p`. -/
theorem polyLift_coeff (p : MvPolynomial (Fin x.length) R) (m : ℕ) :
    (x.polyLift p).coeff m = MvPolynomial.eval x.gen (homogeneousComponent m p) := by
  classical
  induction p using MvPolynomial.induction_on' with
  | monomial β c =>
      have hprod : (β.prod fun i k => (Polynomial.C (x.gen i) * Polynomial.X) ^ k)
          = Polynomial.C (β.prod fun i k => x.gen i ^ k) * Polynomial.X ^ β.degree := by
        rw [Finsupp.prod, Finsupp.prod, Finsupp.degree_apply, map_prod,
          ← Finset.prod_pow_eq_pow_sum, ← Finset.prod_mul_distrib]
        refine Finset.prod_congr rfl fun i _ => ?_
        rw [mul_pow, ← Polynomial.C_pow]
      have hL : x.polyLift (monomial β c)
          = Polynomial.C (c * β.prod fun i k => x.gen i ^ k) * Polynomial.X ^ β.degree := by
        change MvPolynomial.eval₂ Polynomial.C _ (monomial β c) = _
        rw [MvPolynomial.eval₂_monomial, hprod, Polynomial.C_mul, mul_assoc]
      rw [hL, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
        homogeneousComponent_of_mem
          ((mem_homogeneousSubmodule _ _).2 (isHomogeneous_monomial c rfl))]
      split_ifs with h
      · simp [eval_monomial]
      · simp
  | add p q hp hq =>
      rw [map_add, Polynomial.coeff_add, hp, hq, map_add, map_add]

/-- A polynomial all of whose coefficients lie in `I` maps to zero in the symmetric algebra. -/
theorem symLift_eq_zero_of_coeff_mem {p : MvPolynomial (Fin x.length) R}
    (hp : ∀ β, p.coeff β ∈ I) : x.symLift p = 0 := by
  classical
  conv_lhs => rw [p.as_sum]
  rw [map_sum]
  refine Finset.sum_eq_zero fun β _ => ?_
  rw [MvPolynomial.monomial_eq, map_mul, symLift_C,
    Ideal.Quotient.eq_zero_iff_mem.2 (hp β), map_zero, zero_mul]

/-- **The key step.**  A polynomial killed by the canonical normal-sheaf coordinate map has all
of its coefficients in `I`.  This is where quasi-regularity of the sequence is used. -/
theorem coeff_mem_of_symLift_eq_zero {p : MvPolynomial (Fin x.length) R}
    (hp : normalSheafCoordinateMap R I (x.symLift p) = 0) (β) : p.coeff β ∈ I := by
  have happ := congrArg (fun f => f p) (normalSheafCoordinateMap_comp_symLift x)
  simp only [RingHom.comp_apply] at happ
  have hmem : x.reesLift p ∈ Ideal.map (algebraMap R (reesAlgebra I)) I := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, ← happ]
    exact hp
  have hQ : ∀ (d : ℕ) (F : MvPolynomial (Fin x.length) R), F.IsHomogeneous d →
      MvPolynomial.eval x.gen F ∈ I ^ (d + 1) → ∀ α, F.coeff α ∈ I := by
    intro d F hF hval α
    have hc := x.isQuasiregular d F hF (by rw [x.span_eq]; exact hval) α
    rwa [x.span_eq] at hc
  have hcomp : ∀ m, MvPolynomial.eval x.gen (homogeneousComponent m p) ∈ I ^ (m + 1) := by
    intro m
    rw [← polyLift_coeff, ← coe_reesLift]
    exact coeff_mem_pow_succ_of_mem_map_rees R I hmem m
  have hcoeff := hQ β.degree (homogeneousComponent β.degree p)
    (homogeneousComponent_isHomogeneous _ _) (hcomp _) β
  rwa [coeff_homogeneousComponent, if_pos rfl] at hcoeff

include x in
/-- **The canonical map `Sym_{R/I}(I/I²) → gr_I(R)` is injective when `I` is generated by a
finite quasi-regular sequence.** -/
theorem normalSheafCoordinateMap_injective :
    Function.Injective (normalSheafCoordinateMap R I) := by
  intro a b hab
  obtain ⟨p, rfl⟩ := x.symLift_surjective a
  obtain ⟨q, rfl⟩ := x.symLift_surjective b
  have hzero : normalSheafCoordinateMap R I (x.symLift (p - q)) = 0 := by
    rw [map_sub, map_sub, hab, sub_self]
  have hsub := x.symLift_eq_zero_of_coeff_mem (x.coeff_mem_of_symLift_eq_zero hzero)
  rw [map_sub, sub_eq_zero] at hsub
  exact hsub

include x in
/-- Together with the already available surjectivity, the canonical map is bijective. -/
theorem normalSheafCoordinateMap_bijective :
    Function.Bijective (normalSheafCoordinateMap R I) :=
  ⟨x.normalSheafCoordinateMap_injective, normalSheafCoordinateMap_surjective R I⟩

include x in
/-- **The affine comparison map used in the global gluing is bijective.**  This is
`normalSheafCoordinateMap` read through the identification `normalSheafRingEquiv` of the two
presentations `Sym_A(I)/I·Sym_A(I)` and `Sym_{A/I}(I/I²)` of the normal-sheaf coordinate ring. -/
theorem nsToGr_bijective : Function.Bijective (nsToGr R I) := by
  have key : ∀ z : normalSheafRing R I,
      nsToGr R I z = normalSheafCoordinateMap R I (normalSheafRingEquiv R I z) := fun z =>
    (DFunLike.congr_fun (normalSheafCoordinateMap_comp_equiv R I) z).symm
  refine ⟨fun a b hab => ?_, fun z => ?_⟩
  · apply (normalSheafRingEquiv R I).injective
    apply x.normalSheafCoordinateMap_injective
    rw [← key, ← key]
    exact hab
  · obtain ⟨w, hw⟩ := (normalSheafCoordinateMap_surjective R I) z
    refine ⟨(normalSheafRingEquiv R I).symm w, ?_⟩
    rw [key, AlgEquiv.apply_symm_apply, hw]

include x in
/-- The affine normal cone of a quasi-regular immersion is its normal sheaf: the affine closed
immersion of `Cones/Affine.lean` is an isomorphism. -/
theorem coneToNormalSheaf_isIso : IsIso (coneToNormalSheaf R I) := by
  have hiso : IsIso (Spec.map (CommRingCat.ofHom (normalSheafCoordinateMap R I))) := by
    rw [isIso_SpecMap_iff]
    exact x.normalSheafCoordinateMap_bijective
  exact hiso

end QuasiregularGenerators

end Quasiregular

/-! ### Flat base change of the affine comparison map -/

section FlatBaseChange

variable {A B : Type u} [CommRing A] [CommRing B] [Algebra A B] [Module.Flat A B]
  (I : Ideal A) (J : Ideal B) (hJ : I.map (algebraMap A B) = J)

/-- The affine comparison map commutes with flat base change: `nsToGr A I` and `nsToGr B J` are
intertwined by the base-change isomorphisms `nsTensorEquiv` and `grTensorEquiv`. -/
theorem nsToGr_nsTensorEquiv (z : B ⊗[A] normalSheafRing A I) :
    nsToGr B J (nsTensorEquiv I J hJ z) =
      grTensorEquiv I J hJ (Algebra.TensorProduct.map (AlgHom.id B B) (nsToGr A I) z) := by
  induction z using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero, map_zero, map_zero]
  | tmul b w =>
      have hbw : (b ⊗ₜ[A] w : B ⊗[A] normalSheafRing A I) = b • ((1 : B) ⊗ₜ[A] w) := by
        rw [TensorProduct.smul_tmul', smul_eq_mul, mul_one]
      rw [hbw]
      simp only [map_smul, Algebra.TensorProduct.map_tmul, AlgHom.coe_id, id_eq,
        nsTensorEquiv_one_tmul, grTensorEquiv_one_tmul]
      exact congrArg (fun y ↦ b • y)
        (DFunLike.congr_fun (nsToGr_naturality I (algebraMap A B) J hJ) w)
  | add z₁ z₂ h₁ h₂ => rw [map_add, map_add, map_add, map_add, h₁, h₂]

include hJ in
/-- **Flat base change of the regular-immersion comparison.**  If the affine comparison map is
bijective for `I ⊆ A`, it is bijective for the extension of `I` to any flat `A`-algebra. -/
theorem nsToGr_bijective_of_flat (h : Function.Bijective (nsToGr A I)) :
    Function.Bijective (nsToGr B J) := by
  have hmap : Function.Bijective
      (Algebra.TensorProduct.map (AlgHom.id B B) (nsToGr A I)) := by
    have he : ⇑(Algebra.TensorProduct.map (AlgHom.id B B) (nsToGr A I)) =
        ⇑(Algebra.TensorProduct.congr (AlgEquiv.refl : B ≃ₐ[B] B)
          (AlgEquiv.ofBijective (nsToGr A I) h)) := rfl
    rw [he]
    exact (Algebra.TensorProduct.congr (AlgEquiv.refl : B ≃ₐ[B] B)
      (AlgEquiv.ofBijective (nsToGr A I) h)).bijective
  refine ⟨fun a₁ a₂ hab => ?_, fun y => ?_⟩
  · obtain ⟨z₁, rfl⟩ := (nsTensorEquiv I J hJ).surjective a₁
    obtain ⟨z₂, rfl⟩ := (nsTensorEquiv I J hJ).surjective a₂
    rw [nsToGr_nsTensorEquiv, nsToGr_nsTensorEquiv] at hab
    exact congrArg _ (hmap.injective ((grTensorEquiv I J hJ).injective hab))
  · obtain ⟨w, hw⟩ := hmap.surjective ((grTensorEquiv I J hJ).symm y)
    refine ⟨nsTensorEquiv I J hJ w, ?_⟩
    rw [nsToGr_nsTensorEquiv, hw, AlgEquiv.apply_symm_apply]

end FlatBaseChange

/-! ### The normal cone as a cone, and its abelian hull -/

section AbelianHull

variable (R : Type u) [CommRing R] (I : Ideal R)

/-- The coefficients of the Rees coaction: the degree-`n` coefficient of `q` is multiplied by
`tⁿ`. -/
theorem coe_coeff_reesCoaction (q : reesAlgebra I) (n : ℕ) :
    ((GradedCone.reesCoaction R I q).coeff n : Polynomial R) =
      Polynomial.monomial n ((q : Polynomial R).coeff n) := by
  have h := congrArg (fun p => Polynomial.coeff p n)
    (AlgHom.congr_fun (GradedCone.isConeHom_reesVal R I) q)
  simp only [AlgHom.comp_apply, Polynomial.coe_mapAlgHom, Polynomial.coeff_map,
    GradedCone.comul_coeff, Polynomial.C_mul_X_pow_eq_monomial] at h
  exact h

/-- The Rees coaction scales the degree-one element `y t` by the contraction parameter. -/
theorem reesCoaction_degreeOneRees (y : I) :
    GradedCone.reesCoaction R I (degreeOneRees R I y) =
      Polynomial.C (degreeOneRees R I y) * Polynomial.X := by
  rw [← pow_one (Polynomial.X : Polynomial (reesAlgebra I)),
    Polynomial.C_mul_X_pow_eq_monomial]
  refine Polynomial.ext fun n => ?_
  rw [Polynomial.coeff_monomial]
  split_ifs with h
  · subst h
    apply Subtype.ext
    rw [coe_coeff_reesCoaction]
    change Polynomial.monomial 1 ((Polynomial.monomial 1 (y : R)).coeff 1) = _
    rw [Polynomial.coeff_monomial, if_pos rfl]
    rfl
  · apply Subtype.ext
    rw [coe_coeff_reesCoaction]
    change Polynomial.monomial n ((Polynomial.monomial 1 (y : R)).coeff n) = _
    rw [Polynomial.coeff_monomial, if_neg h]
    simp

/-- The coaction of the affine normal cone `Spec gr_I(R)`, read over its degree-zero ring `R/I`.
It has the same underlying map as `GradedCone.normalConeCoaction`; only the base ring of the
cone changes, and it is the base ring `R/I` which makes the abelian hull of the cone the normal
sheaf. -/
def grQuotCoaction :
    associatedGradedRing R I →ₐ[R ⧸ I] Polynomial (associatedGradedRing R I) where
  toRingHom := (GradedCone.normalConeCoaction R I).toRingHom
  commutes' r := by
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective r
    have ha : algebraMap (R ⧸ I) (associatedGradedRing R I) (Ideal.Quotient.mk I a)
        = algebraMap R (associatedGradedRing R I) a := by
      rw [← Ideal.Quotient.algebraMap_eq, ← IsScalarTower.algebraMap_apply]
    change GradedCone.normalConeCoaction R I
      (algebraMap (R ⧸ I) (associatedGradedRing R I) (Ideal.Quotient.mk I a)) = _
    rw [ha, AlgHom.commutes, Polynomial.algebraMap_apply, Polynomial.algebraMap_apply, ha]

@[simp]
theorem grQuotCoaction_apply (z : associatedGradedRing R I) :
    grQuotCoaction R I z = GradedCone.normalConeCoaction R I z := rfl

/-- The coaction of the normal cone is computed on the Rees algebra. -/
theorem normalConeCoaction_mk (q : reesAlgebra I) :
    GradedCone.normalConeCoaction R I
        (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I) q) =
      Polynomial.map (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I))
        (GradedCone.reesCoaction R I q) := by
  have h := AlgHom.congr_fun (GradedCone.isConeHom_normalConeCoaction R I) q
  simp only [AlgHom.comp_apply, Polynomial.coe_mapAlgHom, Ideal.Quotient.mkₐ_eq_mk] at h
  exact h.symm

theorem coeff_grQuotCoaction_mk (q : reesAlgebra I) (n : ℕ) :
    (grQuotCoaction R I
        (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I) q)).coeff n =
      Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)
        ((GradedCone.reesCoaction R I q).coeff n) := by
  rw [grQuotCoaction_apply, normalConeCoaction_mk, Polynomial.coeff_map]

/-- The conormal classes are homogeneous of degree one in the normal cone. -/
theorem conormal_mem_homogeneous_one (m : I.Cotangent) :
    conormalToAssociatedGraded R I m ∈ GradedCone.homogeneous (grQuotCoaction R I) 1 := by
  obtain ⟨y, rfl⟩ := I.toCotangent_surjective m
  rw [GradedCone.mem_homogeneous, conormalToAssociatedGraded_toCotangent, grQuotCoaction_apply,
    normalConeCoaction_mk, reesCoaction_degreeOneRees, pow_one, Polynomial.map_mul,
    Polynomial.map_C, Polynomial.map_X]

/-- Conversely, every degree-one element of the normal cone is the class of a conormal
element: the degree-one part of `gr_I(R)` is `I/I²`. -/
theorem mem_range_of_mem_homogeneous_one {z : associatedGradedRing R I}
    (hz : z ∈ GradedCone.homogeneous (grQuotCoaction R I) 1) :
    z ∈ LinearMap.range (conormalToAssociatedGraded R I) := by
  obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective z
  have hcoeff : (q : Polynomial R).coeff 1 ∈ I := by
    have h1 := (mem_reesAlgebra_iff I (q : Polynomial R)).mp q.2 1
    rwa [pow_one] at h1
  refine ⟨I.toCotangent ⟨(q : Polynomial R).coeff 1, hcoeff⟩, ?_⟩
  rw [conormalToAssociatedGraded_toCotangent]
  rw [GradedCone.mem_homogeneous] at hz
  have h1 : Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)
      ((GradedCone.reesCoaction R I q).coeff 1) =
      Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I) q := by
    rw [← coeff_grQuotCoaction_mk, hz]
    simp
  have hval : (GradedCone.reesCoaction R I q).coeff 1
      = degreeOneRees R I ⟨(q : Polynomial R).coeff 1, hcoeff⟩ :=
    Subtype.ext (by rw [coe_coeff_reesCoaction]; rfl)
  rw [hval] at h1
  exact h1

/-- **The degree-one part of the normal cone is the conormal module.** -/
theorem homogeneous_one_eq_range :
    GradedCone.homogeneous (grQuotCoaction R I) 1 =
      LinearMap.range (conormalToAssociatedGraded R I) := by
  refine le_antisymm (fun z hz => mem_range_of_mem_homogeneous_one R I hz) ?_
  rintro _ ⟨m, rfl⟩
  exact conormal_mem_homogeneous_one R I m

/-- The canonical map `I/I² → gr_I(R)` is injective: an element of `I` whose degree-one Rees
class dies in `gr_I(R)` lies in `I²`. -/
theorem conormalToAssociatedGraded_injective :
    Function.Injective (conormalToAssociatedGraded R I) := by
  rw [injective_iff_map_eq_zero]
  intro m hm
  obtain ⟨y, rfl⟩ := I.toCotangent_surjective m
  rw [conormalToAssociatedGraded_toCotangent, Ideal.Quotient.eq_zero_iff_mem] at hm
  have h2 := coeff_mem_pow_succ_of_mem_map_rees R I hm 1
  rw [Ideal.toCotangent_eq_zero]
  have hco : ((degreeOneRees R I y : reesAlgebra I) : Polynomial R).coeff 1 = (y : R) := by
    rw [degreeOneRees_coe, Polynomial.coeff_monomial, if_pos rfl]
  rwa [hco] at h2

/-- The conormal module is the degree-one part of the normal cone, as `R/I`-modules. -/
def conormalEquivDegreeOne :
    I.Cotangent ≃ₗ[R ⧸ I] GradedCone.homogeneous (grQuotCoaction R I) 1 :=
  (LinearEquiv.ofInjective _ (conormalToAssociatedGraded_injective R I)).trans
    (LinearEquiv.ofEq _ _ (homogeneous_one_eq_range R I).symm)

@[simp]
theorem coe_conormalEquivDegreeOne (m : I.Cotangent) :
    ((conormalEquivDegreeOne R I m : GradedCone.homogeneous (grQuotCoaction R I) 1) :
        associatedGradedRing R I) = conormalToAssociatedGraded R I m := by
  rw [conormalEquivDegreeOne, LinearEquiv.trans_apply, LinearEquiv.coe_ofEq_apply]
  rfl

/-- **The normal sheaf is the abelian hull of the normal cone.**  Through the identification of
the conormal module with the degree-one part of `gr_I(R)`, the canonical map
`Sym_{R/I}(I/I²) → gr_I(R)` of `Cones/Affine.lean` is the abelian hull map of the cone
`Spec gr_I(R)` over `Spec (R/I)` in the sense of `Cones/Graded.lean`. -/
theorem abelianHull_symCongr (z : normalSheafCoordinateRing R I) :
    GradedCone.abelianHull (grQuotCoaction R I) (symCongr (conormalEquivDegreeOne R I) z) =
      normalSheafCoordinateMap R I z := by
  induction z using SymmetricAlgebra.induction with
  | algebraMap r =>
      rw [AlgEquiv.commutes, AlgHom.commutes, normalSheafCoordinateMap_base]
      rfl
  | ι m =>
      rw [symCongr_ι, GradedCone.abelianHull_ι, normalSheafCoordinateMap_ι,
        coe_conormalEquivDegreeOne]
  | mul a b ha hb => rw [map_mul, map_mul, ha, hb, map_mul]
  | add a b ha hb => rw [map_add, map_add, ha, hb, map_add]

/-- The normal cone is generated in degree one over its base `R/I`. -/
theorem isGeneratedInDegreeOne_grQuotCoaction :
    GradedCone.IsGeneratedInDegreeOne (grQuotCoaction R I) := by
  rw [GradedCone.IsGeneratedInDegreeOne, eq_top_iff]
  rintro z -
  obtain ⟨w, rfl⟩ := (normalSheafCoordinateMap_surjective R I) z
  rw [← abelianHull_symCongr]
  generalize symCongr (conormalEquivDegreeOne R I) w = v
  induction v using SymmetricAlgebra.induction with
  | algebraMap r => rw [AlgHom.commutes]; exact Subalgebra.algebraMap_mem _ r
  | ι x =>
      rw [GradedCone.abelianHull_ι]
      exact Algebra.subset_adjoin x.2
  | mul a b ha hb => rw [map_mul]; exact Subalgebra.mul_mem _ ha hb
  | add a b ha hb => rw [map_add]; exact Subalgebra.add_mem _ ha hb

/-- The affine comparison map `Sym_A(I)/I·Sym_A(I) → gr_I(A)` used in the global gluing,
presented as the abelian hull of the normal cone. -/
def abelianHullComparison : normalSheafRing R I →+* associatedGradedRing R I :=
  (GradedCone.abelianHull (grQuotCoaction R I)).toRingHom.comp
    ((symCongr (conormalEquivDegreeOne R I)).toAlgHom.toRingHom.comp
      (normalSheafRingEquiv R I).toRingEquiv.toRingHom)

/-- The abelian-hull presentation really is the comparison map of the global gluing. -/
theorem abelianHullComparison_eq : abelianHullComparison R I = (nsToGr R I).toRingHom := by
  rw [← normalSheafCoordinateMap_comp_equiv]
  refine RingHom.ext fun z => ?_
  exact abelianHull_symCongr R I ((normalSheafRingEquiv R I) z)

end AbelianHull

/-! ### The base rings of the two affine cones are killed by the ideal -/

section BaseRingHom

variable (A : Type u) [CommRing A] (I : Ideal A)

/-- The degree-zero structure map `A/I → Sym_A(I)/I·Sym_A(I)` of the affine normal sheaf: the
ideal `I` kills the coordinate ring of the normal sheaf, so the structure map factors through
`A/I`. -/
def nsBaseRingHom : A ⧸ I →+* normalSheafRing A I :=
  Ideal.Quotient.lift I (algebraMap A (normalSheafRing A I)) (by
    intro a ha
    change Ideal.Quotient.mk (Ideal.map (algebraMap A (SymmetricAlgebra A I)) I)
      (algebraMap A (SymmetricAlgebra A I) a) = 0
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_map_of_mem _ ha)

@[simp]
theorem nsBaseRingHom_mk (a : A) :
    nsBaseRingHom A I (Ideal.Quotient.mk I a) = algebraMap A (normalSheafRing A I) a := rfl

end BaseRingHom

end AffineNormalCone

/-! ### Factorization of a relative `Spec` through a closed subscheme -/

namespace RelativeSpec

/- The index type of Mathlib's directed affine cover is definitionally, but not reducibly, the
type of affine opens; as in Mathlib's own development of that cover, the unifier is told not to
respect transparency in this section. -/
set_option backward.isDefEq.respectTransparency false

variable (X : Scheme.{u}) (𝒜 : AlgebraData X) (I : X.IdealSheafData)
  (ψ : ∀ U : X.affineOpens, (Γ(X, U.1) ⧸ I.ideal U) →+* 𝒜.ring U)
  (hψ : ∀ (U : X.affineOpens) (a : Γ(X, U.1)),
    ψ U (Ideal.Quotient.mk (I.ideal U) a) = algebraMap Γ(X, U.1) (𝒜.ring U) a)

/-- The affine chart of the relative `Spec`, mapped to the closed subscheme cut out by `I`.
This uses that the structure map of the chart is killed by `I(U)`, in the form of the
factorization `ψ U` through `Γ(X, U)/I(U)`. -/
def subschemeApp (U : X.affineOpens) : Spec (.of (𝒜.ring U)) ⟶ I.subscheme :=
  Spec.map (CommRingCat.ofHom (ψ U)) ≫ I.subschemeCover.f U

include hψ in
theorem subschemeApp_subschemeι (U : X.affineOpens) :
    subschemeApp X 𝒜 I ψ U ≫ I.subschemeι = projection X 𝒜 U ≫ U.1.ι := by
  have hcomp : (ψ U).comp (Ideal.Quotient.mk (I.ideal U)) = algebraMap Γ(X, U.1) (𝒜.ring U) :=
    RingHom.ext (hψ U)
  rw [subschemeApp, Category.assoc, Scheme.IdealSheafData.subschemeCover_map_subschemeι,
    Scheme.IdealSheafData.glueDataObjι, ← Category.assoc, ← Category.assoc, ← Spec.map_comp,
    ← CommRingCat.ofHom_comp, hcomp]

include hψ in
theorem subschemeApp_naturality {U V : X.affineOpens} (h : U ⟶ V) :
    (gluingData X 𝒜).functor.map h ≫ subschemeApp X 𝒜 I ψ V = subschemeApp X 𝒜 I ψ U := by
  rw [← cancel_mono I.subschemeι, Category.assoc, subschemeApp_subschemeι X 𝒜 I ψ hψ,
    subschemeApp_subschemeι X 𝒜 I ψ hψ, ← affineι_toBase, ← affineι_toBase, ← Category.assoc]
  congr 1
  exact colimit.w (gluingData X 𝒜).functor h

/-- The affine charts, mapped to the closed subscheme, form a cocone on the gluing functor. -/
def subschemeCocone : Cocone (gluingData X 𝒜).functor where
  pt := I.subscheme
  ι :=
    { app := subschemeApp X 𝒜 I ψ
      naturality := fun U V h => by
        simpa using subschemeApp_naturality X 𝒜 I ψ hψ h }

/-- **The relative `Spec` of a quasi-coherent algebra killed by `I` lives over the closed
subscheme `V(I)`.** -/
def toSubscheme : relativeSpec X 𝒜 ⟶ I.subscheme :=
  colimit.desc (gluingData X 𝒜).functor (subschemeCocone X 𝒜 I ψ hψ)

theorem affineι_toSubscheme (U : X.affineOpens) :
    affineι X 𝒜 U ≫ toSubscheme X 𝒜 I ψ hψ = subschemeApp X 𝒜 I ψ U :=
  colimit.ι_desc _ _

/-- The factorization is compatible with the structure morphism to `X`. -/
theorem toSubscheme_subschemeι : toSubscheme X 𝒜 I ψ hψ ≫ I.subschemeι = toBase X 𝒜 := by
  refine colimit.hom_ext fun U => ?_
  rw [← Category.assoc]
  change (affineι X 𝒜 U ≫ toSubscheme X 𝒜 I ψ hψ) ≫ I.subschemeι = _
  rw [affineι_toSubscheme, subschemeApp_subschemeι X 𝒜 I ψ hψ]
  exact (affineι_toBase X 𝒜 U).symm

end RelativeSpec

/-! ### Regular ideal sheaves and the global comparison -/

namespace NormalCone

open AffineNormalCone

variable (X : Scheme.{u}) (I : X.IdealSheafData)

/-- A quasi-coherent ideal sheaf is **quasi-regular** if on every affine open it is generated by
a finite quasi-regular sequence.

The condition is imposed on all affine opens.  This is not a restriction on the geometry: by
`NormalCone.bijective_nsToGr_of_cover` the *conclusion* `NormalCone.isIso_toNormalSheaf` already
follows from quasi-regular generators on the members of one affine open cover
(`NormalCone.isIso_toNormalSheaf_of_forall_mem_cover`); it is only the existence of a *global*
quasi-regular generating sequence on every affine open which is a genuinely stronger demand. -/
def IsQuasiregularIdealSheaf : Prop :=
  ∀ U : X.affineOpens, Nonempty (QuasiregularGenerators Γ(X, U.1) (I.ideal U))

/-- A quasi-coherent ideal sheaf is **regular** if on every affine open it is generated by a
finite regular sequence (Mathlib's `RingTheory.Sequence.IsWeaklyRegular`). -/
def IsRegularIdealSheaf : Prop :=
  ∀ U : X.affineOpens, Nonempty (RegularGenerators Γ(X, U.1) (I.ideal U))

theorem IsRegularIdealSheaf.isQuasiregular (h : IsRegularIdealSheaf X I) :
    IsQuasiregularIdealSheaf X I :=
  fun U => (h U).map RegularGenerators.toQuasiregular

/-- **The normal cone of a quasi-regular immersion is its normal sheaf**, in the form: the
canonical closed immersion `C_{Z/X} ⟶ N_{Z/X}` is an isomorphism as soon as the affine
comparison maps are bijective. -/
theorem isIso_toNormalSheaf_of_forall_bijective
    (h : ∀ U : X.affineOpens, Function.Bijective (nsToGr Γ(X, U.1) (I.ideal U))) :
    IsIso (toNormalSheaf X I) :=
  (toNormalSheafHom X I).isIso_map h

/-- **The normal cone of a quasi-regular immersion is its normal sheaf.** -/
theorem isIso_toNormalSheaf (h : IsQuasiregularIdealSheaf X I) : IsIso (toNormalSheaf X I) :=
  isIso_toNormalSheaf_of_forall_bijective X I fun U =>
    (h U).elim fun x => x.nsToGr_bijective

/-- **The normal cone of a regular immersion is its normal sheaf.** -/
theorem isIso_toNormalSheaf_of_regular (h : IsRegularIdealSheaf X I) :
    IsIso (toNormalSheaf X I) :=
  isIso_toNormalSheaf X I (h.isQuasiregular X I)

/-- The resulting isomorphism `C_{Z/X} ≅ N_{Z/X}`; its forward map is the canonical closed
immersion, not an independently chosen isomorphism. -/
def isoNormalSheaf (h : IsQuasiregularIdealSheaf X I) :
    normalCone X I ≅ NormalSheaf.normalSheaf X I :=
  @asIso _ _ _ _ (toNormalSheaf X I) (isIso_toNormalSheaf X I h)

@[simp]
theorem isoNormalSheaf_hom (h : IsQuasiregularIdealSheaf X I) :
    (isoNormalSheaf X I h).hom = toNormalSheaf X I := rfl

/-- The isomorphism is an isomorphism of schemes over `X`. -/
theorem isoNormalSheaf_hom_toBase (h : IsQuasiregularIdealSheaf X I) :
    (isoNormalSheaf X I h).hom ≫ NormalSheaf.toBase X I = toBase X I :=
  toNormalSheaf_toBase X I

/-! ### Locality of the affine comparison condition -/

/-- The bijectivity of the affine comparison map passes to smaller affine opens: the restriction
maps of an affine open inside an affine open are flat, and both the normal cone and the normal
sheaf commute with that flat base change.

This is the easy half of the locality question: the condition on an affine open `V` implies the
condition on every affine open `U ≤ V`.  The converse, descent along an affine open cover, is
`NormalCone.bijective_nsToGr_of_cover`. -/
theorem bijective_nsToGr_of_le {U V : X.affineOpens} (h : U ≤ V)
    (hV : Function.Bijective (nsToGr Γ(X, V.1) (I.ideal V))) :
    Function.Bijective (nsToGr Γ(X, U.1) (I.ideal U)) := by
  let _ := (res X h).toAlgebra
  have hflat : Module.Flat Γ(X, V.1) Γ(X, U.1) := res_flat X h
  exact nsToGr_bijective_of_flat (I.ideal V) (I.ideal U) (I.map_ideal h) hV

/-- An element of the kernel of the affine comparison map over an affine open `V` is killed by
a power of any section `r` for which the comparison map is bijective over the basic open `D(r)`:
the normal-sheaf coordinate ring commutes with the flat base change `Γ(X, V) → Γ(X, D(r))`
(`nsTensorEquiv`), and `Γ(X, D(r))` is the localisation of `Γ(X, V)` away from `r`. -/
theorem exists_pow_smul_eq_zero {V : X.affineOpens} (r : Γ(X, V.1))
    (hbijr : Function.Bijective
      (nsToGr Γ(X, X.basicOpen r) (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩)))
    {z : normalSheafRing Γ(X, V.1) (I.ideal V)}
    (hz : nsToGr Γ(X, V.1) (I.ideal V) z = 0) : ∃ n : ℕ, r ^ n • z = 0 := by
  have inst : IsLocalization.Away r Γ(X, X.basicOpen r) := V.2.isLocalization_basicOpen r
  have hJ : (I.ideal V).map (algebraMap Γ(X, V.1) Γ(X, X.basicOpen r))
      = I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩ :=
    I.map_ideal (U := ⟨X.basicOpen r, V.2.basicOpen r⟩) (V := V) (X.basicOpen_le r)
  have hflat : Module.Flat Γ(X, V.1) Γ(X, X.basicOpen r) :=
    IsLocalization.flat _ (Submonoid.powers r)
  have h0 : nsMapOfEq (I.ideal V) (algebraMap Γ(X, V.1) Γ(X, X.basicOpen r))
      (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩) hJ z = 0 := by
    apply hbijr.1
    have hnat : nsToGr Γ(X, X.basicOpen r) (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩)
          (nsMapOfEq (I.ideal V) (algebraMap Γ(X, V.1) Γ(X, X.basicOpen r))
            (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩) hJ z) =
        grMapOfEq (I.ideal V) (algebraMap Γ(X, V.1) Γ(X, X.basicOpen r))
            (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩) hJ (nsToGr Γ(X, V.1) (I.ideal V) z) :=
      DFunLike.congr_fun (nsToGr_naturality (I.ideal V)
        (algebraMap Γ(X, V.1) Γ(X, X.basicOpen r))
        (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩) hJ) z
    rw [hnat, hz, map_zero]
    exact (map_zero _).symm
  have h1 : (1 : Γ(X, X.basicOpen r)) ⊗ₜ[Γ(X, V.1)] z = 0 := by
    apply (nsTensorEquiv (I.ideal V) (I.ideal ⟨X.basicOpen r, V.2.basicOpen r⟩) hJ).injective
    rw [nsTensorEquiv_one_tmul, h0, map_zero]
  obtain ⟨⟨_, n, rfl⟩, hn⟩ :=
    (IsLocalizedModule.eq_zero_iff (Submonoid.powers r)
      (f := TensorProduct.mk Γ(X, V.1) Γ(X, X.basicOpen r)
        (normalSheafRing Γ(X, V.1) (I.ideal V)) 1)).mp h1
  exact ⟨n, hn⟩

/-- **Descent of the affine comparison condition along an affine open cover.**  If the affine
comparison map is bijective on the members of an affine open cover of `X`, it is bijective on
*every* affine open.

The map is always surjective, and an element of its kernel over an affine open `V` is killed by
a power of every section `r` whose basic open sits inside a member of the cover
(`exists_pow_smul_eq_zero`, using `bijective_nsToGr_of_le` over `D(r)`); those sections span the
unit ideal because the corresponding basic opens cover `V`. -/
theorem bijective_nsToGr_of_cover {ι : Type*} (U : ι → X.affineOpens)
    (hU : ⨆ i, (U i).1 = ⊤)
    (hbij : ∀ i, Function.Bijective (nsToGr Γ(X, (U i).1) (I.ideal (U i))))
    (V : X.affineOpens) :
    Function.Bijective (nsToGr Γ(X, V.1) (I.ideal V)) := by
  have hspan : Ideal.span {r : Γ(X, V.1) | ∃ i, X.basicOpen r ≤ (U i).1} = ⊤ := by
    rw [← V.2.self_le_iSup_basicOpen_iff]
    intro x hxV
    obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp (hU.ge (Set.mem_univ x))
    obtain ⟨r, hr₁, hr₂⟩ := V.2.exists_basicOpen_le (V := (U i).1) ⟨x, hi⟩ hxV
    exact TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨r, ⟨i, hr₁⟩⟩, hr₂⟩
  have key : ∀ z : normalSheafRing Γ(X, V.1) (I.ideal V),
      nsToGr Γ(X, V.1) (I.ideal V) z = 0 → z = 0 := by
    intro z hz
    refine eq_zero_of_forall_exists_pow_smul_eq_zero hspan ?_
    rintro r ⟨i, hri⟩
    exact exists_pow_smul_eq_zero X I r
      (bijective_nsToGr_of_le X I (U := ⟨X.basicOpen r, V.2.basicOpen r⟩) (V := U i) hri
        (hbij i)) hz
  refine ⟨fun a b hab => ?_, nsToGr_surjective _ _⟩
  exact sub_eq_zero.mp (key (a - b) (by rw [map_sub, hab, sub_self]))

/-- **The regular-immersion equality is local on an affine cover.**  If the affine comparison
map is bijective on the members of one affine open cover, the global closed immersion
`C_{Z/X} ⟶ N_{Z/X}` is an isomorphism. -/
theorem isIso_toNormalSheaf_of_cover {ι : Type*} (U : ι → X.affineOpens)
    (hU : ⨆ i, (U i).1 = ⊤)
    (hbij : ∀ i, Function.Bijective (nsToGr Γ(X, (U i).1) (I.ideal (U i)))) :
    IsIso (toNormalSheaf X I) :=
  isIso_toNormalSheaf_of_forall_bijective X I (bijective_nsToGr_of_cover X I U hU hbij)

/-- **The normal cone of a quasi-regular immersion is its normal sheaf**, with the quasi-regular
generators required only on the members of one affine open cover. -/
theorem isIso_toNormalSheaf_of_forall_mem_cover {ι : Type*} (U : ι → X.affineOpens)
    (hU : ⨆ i, (U i).1 = ⊤)
    (h : ∀ i, Nonempty (QuasiregularGenerators Γ(X, (U i).1) (I.ideal (U i)))) :
    IsIso (toNormalSheaf X I) :=
  isIso_toNormalSheaf_of_cover X I U hU fun i => (h i).elim fun x => x.nsToGr_bijective

/-- **The normal cone of a regular immersion is its normal sheaf**, with the regular sequences
required only on the members of one affine open cover. -/
theorem isIso_toNormalSheaf_of_regular_cover {ι : Type*} (U : ι → X.affineOpens)
    (hU : ⨆ i, (U i).1 = ⊤)
    (h : ∀ i, Nonempty (RegularGenerators Γ(X, (U i).1) (I.ideal (U i)))) :
    IsIso (toNormalSheaf X I) :=
  isIso_toNormalSheaf_of_forall_mem_cover X I U hU fun i =>
    (h i).map RegularGenerators.toQuasiregular

/-- Under the cover hypothesis, the affine comparison is bijective on every affine open, so the
isomorphism of `NormalCone.isoNormalSheaf` is available in this generality as well. -/
def isoNormalSheafOfCover {ι : Type*} (U : ι → X.affineOpens) (hU : ⨆ i, (U i).1 = ⊤)
    (hbij : ∀ i, Function.Bijective (nsToGr Γ(X, (U i).1) (I.ideal (U i)))) :
    normalCone X I ≅ NormalSheaf.normalSheaf X I :=
  @asIso _ _ _ _ (toNormalSheaf X I) (isIso_toNormalSheaf_of_cover X I U hU hbij)

@[simp]
theorem isoNormalSheafOfCover_hom {ι : Type*} (U : ι → X.affineOpens) (hU : ⨆ i, (U i).1 = ⊤)
    (hbij : ∀ i, Function.Bijective (nsToGr Γ(X, (U i).1) (I.ideal (U i)))) :
    (isoNormalSheafOfCover X I U hU hbij).hom = toNormalSheaf X I := rfl

/-! ### The global abelian hull -/

/-- **Over every affine open, the closed immersion `C_{Z/X} ⟶ N_{Z/X}` is the abelian hull of
the normal cone.**  The square is the affine chart square of `RelativeSpec`, and the affine map
in it is the abelian-hull map of the cone `Spec gr_I` over `Spec (Γ(X, U)/I(U))`, transported
through the identification of the two presentations of the normal-sheaf coordinate ring. -/
theorem isPullback_abelianHull (U : X.affineOpens) :
    IsPullback
      (Spec.map (CommRingCat.ofHom (abelianHullComparison Γ(X, U.1) (I.ideal U))))
      (affineι X I U) (NormalSheaf.affineι X I U) (toNormalSheaf X I) := by
  rw [abelianHullComparison_eq]
  exact isPullback_toNormalSheaf X I U

/-! ### Factorization through the closed subscheme -/

/-- **The normal cone lives over the closed subscheme `Z = V(I)`**: the ideal `I` kills
`gr_I 𝒪_X`, so the structure morphism `C_{Z/X} ⟶ X` factors through `Z`. -/
def toSubscheme : normalCone X I ⟶ I.subscheme :=
  RelativeSpec.toSubscheme X (algebraData X I) I
    (fun U => associatedGradedBaseRingHom Γ(X, U.1) (I.ideal U)) (fun _ _ => rfl)

@[reassoc]
theorem toSubscheme_subschemeι : toSubscheme X I ≫ I.subschemeι = toBase X I :=
  RelativeSpec.toSubscheme_subschemeι X (algebraData X I) I _ _

end NormalCone

namespace NormalSheaf

open AffineNormalCone

variable (X : Scheme.{u}) (I : X.IdealSheafData)

/-- **The normal sheaf lives over the closed subscheme `Z = V(I)`**: the ideal `I` kills
`Sym(I/I²)`, so the structure morphism `N_{Z/X} ⟶ X` factors through `Z`. -/
def toSubscheme : normalSheaf X I ⟶ I.subscheme :=
  RelativeSpec.toSubscheme X (algebraData X I) I
    (fun U => nsBaseRingHom Γ(X, U.1) (I.ideal U)) (fun _ _ => rfl)

@[reassoc]
theorem toSubscheme_subschemeι : toSubscheme X I ≫ I.subschemeι = toBase X I :=
  RelativeSpec.toSubscheme_subschemeι X (algebraData X I) I _ _

end NormalSheaf

namespace NormalCone

variable (X : Scheme.{u}) (I : X.IdealSheafData)

/-- The closed immersion of the normal cone into the normal sheaf is a morphism over the closed
subscheme `Z = V(I)`. -/
theorem toNormalSheaf_toSubscheme :
    toNormalSheaf X I ≫ NormalSheaf.toSubscheme X I = toSubscheme X I := by
  rw [← cancel_mono I.subschemeι, Category.assoc, NormalSheaf.toSubscheme_subschemeι,
    toSubscheme_subschemeι]
  exact toNormalSheaf_toBase X I

end NormalCone

end

end GromovWitten.AlgebraicGeometry
