/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.Affine
import Mathlib.RingTheory.TensorProduct.Basic

/-!
# The product formula for the affine normal cone

For `k`-algebras `R`, `R'` with ideals `I ⊆ R`, `I' ⊆ R'`, the ideal of `U × U'` inside
`M × M'` is `J = I ⊗ R' + R ⊗ I' ⊆ R ⊗[k] R'` (`productIdeal`).  This file constructs the
canonical comparison map

`gr_I(R) ⊗[k] gr_{I'}(R') → gr_J(R ⊗[k] R')`,

that is, `C_{U×U'/M×M'} → C_{U/M} × C_{U'/M'}` on coordinate rings, and proves that it is
surjective, so that the induced morphism of affine normal cones is a closed immersion.

## Contents

* `productIdeal`, `inl_mem_productIdeal`, `inr_mem_productIdeal`, `productIdeal_eq_span` and
  `le_productIdeal_pow` (`I^a · I'^b ⊆ J^{a+b}`): the ideal of `U × U'` and its basic properties.
* `reesLeftAlg`, `reesRightAlg`: the two maps of Rees algebras induced by the inclusions of the
  factors.
* `grLeft`, `grRight` and `grTensorToGr`: the comparison map on associated graded rings.
* `grTensorToGr_surjective`: the comparison map is surjective, so the induced morphism of affine
  normal cones is a closed immersion.  The proof uses that the Rees algebra of `J` is generated
  over `R ⊗[k] R'` by the degree-one monomials attached to the generators `I ⊗ 1` and `1 ⊗ I'`
  of `J` (`adjoin_productGenerators`).
* `grTensorToGr_degreeOne_left`, `grTensorToGr_degreeOne_right`: compatibility with the canonical
  degree-one generators `AffineNormalCone.conormalToAssociatedGraded`.
* `ringKrullDim_productIdeal_le`: the unconditional dimension inequality coming from
  surjectivity.
* `grTensorEquiv` and `ringKrullDim_associatedGradedRing_productIdeal`: the isomorphism and the
  resulting dimension equality, both with the injectivity of `grTensorToGr` as an explicit
  hypothesis.

## What is conditional, and what is not done here

Only the injectivity of `grTensorToGr` is not proved.  Over a field it holds, by the
identification `J^n/J^{n+1} ≅ ⊕_{a+b=n} (I^a/I^{a+1}) ⊗_k (I'^b/I'^{b+1})`, which rests on the
fact that the subspaces `I^a ⊗_k I'^b` of `R ⊗_k R'` form a distributive lattice; that argument
is not formalised, and injectivity appears as an explicit hypothesis of the two results that
need it.  Everything else is unconditional and holds over an arbitrary base ring `k`.

The corresponding statement for the normal sheaf rings, `N_{U×U'/M×M'} ≅ N_{U/M} × N_{U'/M'}`,
is *not* proved here: it would need `J/J² ≅ (I/I²) ⊗_k (R'/I') ⊕ (R/I) ⊗_k (I'/I'²)` (the same
distributivity input) together with base change for symmetric algebras, on top of
`NormalSheafPicard.symProdEquiv`.  What is recorded here is the degree-one compatibility
`grTensorToGr_degreeOne_left` / `grTensorToGr_degreeOne_right`, which is the part of that
comparison that `AffineNormalCone.normalSheafCoordinateMap` sees.
-/

open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

namespace AffineNormalConeProduct

universe u

variable (k : Type u) [CommRing k] (R : Type u) [CommRing R] [Algebra k R]
  (R' : Type u) [CommRing R'] [Algebra k R'] (I : Ideal R) (I' : Ideal R')

/-- The inclusion of the left factor `R → R ⊗[k] R'`. -/
abbrev inl : R →ₐ[k] R ⊗[k] R' := Algebra.TensorProduct.includeLeft

/-- The inclusion of the right factor `R' → R ⊗[k] R'`. -/
abbrev inr : R' →ₐ[k] R ⊗[k] R' := Algebra.TensorProduct.includeRight

/-- The ideal of `U × U'` inside `M × M'`: the sum of the two extended ideals. -/
def productIdeal : Ideal (R ⊗[k] R') := I.map (inl k R R') ⊔ I'.map (inr k R R')

/-- An element of `I` lands in the product ideal. -/
theorem inl_mem_productIdeal {x : R} (hx : x ∈ I) :
    inl k R R' x ∈ productIdeal k R R' I I' :=
  Ideal.mem_sup_left (Ideal.mem_map_of_mem _ hx)

/-- An element of `I'` lands in the product ideal. -/
theorem inr_mem_productIdeal {y : R'} (hy : y ∈ I') :
    inr k R R' y ∈ productIdeal k R R' I I' :=
  Ideal.mem_sup_right (Ideal.mem_map_of_mem _ hy)

/-- The product ideal is generated by the images of `I` and of `I'`. -/
theorem productIdeal_eq_span :
    productIdeal k R R' I I' =
      Ideal.span ((inl k R R' '' I) ∪ (inr k R R' '' I')) := by
  rw [productIdeal, Ideal.span_union, Ideal.map, Ideal.map]

/-- The `n`-th power of the extended ideal of `I` is contained in the `n`-th power of the
product ideal. -/
theorem map_pow_le_productIdeal_pow (n : ℕ) :
    Ideal.map (inl k R R') (I ^ n) ≤ productIdeal k R R' I I' ^ n := by
  rw [Ideal.map_pow]
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, pow_succ]
    exact Ideal.mul_mono ih le_sup_left

/-- The right-hand analogue of `map_pow_le_productIdeal_pow`. -/
theorem map_pow_le_productIdeal_pow' (n : ℕ) :
    Ideal.map (inr k R R') (I' ^ n) ≤ productIdeal k R R' I I' ^ n := by
  rw [Ideal.map_pow]
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, pow_succ]
    exact Ideal.mul_mono ih le_sup_right

/-- Products of powers of the two ideals lie in the corresponding power of the product ideal:
this is the easy half of `J^n = Σ_{a+b=n} I^a I'^b`. -/
theorem le_productIdeal_pow (a b : ℕ) :
    Ideal.map (inl k R R') (I ^ a) * Ideal.map (inr k R R') (I' ^ b) ≤
      productIdeal k R R' I I' ^ (a + b) := by
  rw [pow_add]
  exact Ideal.mul_mono (map_pow_le_productIdeal_pow k R R' I I' a)
    (map_pow_le_productIdeal_pow' k R R' I I' b)

/-! ### The induced maps of Rees algebras -/

/-- Extending scalars along `R → R ⊗[k] R'` sends the Rees algebra of `I` into the Rees algebra
of the product ideal. -/
theorem map_mem_reesAlgebra_left {p : Polynomial R} (hp : p ∈ reesAlgebra I) :
    Polynomial.map (inl k R R' : R →+* R ⊗[k] R') p ∈
      reesAlgebra (productIdeal k R R' I I') := by
  rw [mem_reesAlgebra_iff]
  intro i
  rw [Polynomial.coeff_map]
  exact map_pow_le_productIdeal_pow k R R' I I' i
    (Ideal.mem_map_of_mem _ ((mem_reesAlgebra_iff I p).mp hp i))

/-- The right-hand analogue of `map_mem_reesAlgebra_left`. -/
theorem map_mem_reesAlgebra_right {p : Polynomial R'} (hp : p ∈ reesAlgebra I') :
    Polynomial.map (inr k R R' : R' →+* R ⊗[k] R') p ∈
      reesAlgebra (productIdeal k R R' I I') := by
  rw [mem_reesAlgebra_iff]
  intro i
  rw [Polynomial.coeff_map]
  exact map_pow_le_productIdeal_pow' k R R' I I' i
    (Ideal.mem_map_of_mem _ ((mem_reesAlgebra_iff I' p).mp hp i))

/-- The map of Rees algebras induced by the inclusion of the left factor. -/
noncomputable def reesLeftAlg :
    reesAlgebra I →ₐ[k] reesAlgebra (productIdeal k R R' I I') where
  toFun p := ⟨Polynomial.map (inl k R R' : R →+* R ⊗[k] R') (p : Polynomial R),
    map_mem_reesAlgebra_left k R R' I I' p.2⟩
  map_one' := by apply Subtype.ext; simp
  map_mul' p q := by apply Subtype.ext; simp
  map_zero' := by apply Subtype.ext; simp
  map_add' p q := by apply Subtype.ext; simp
  commutes' c := by
    apply Subtype.ext
    change Polynomial.map (inl k R R' : R →+* R ⊗[k] R')
        ((algebraMap k (reesAlgebra I) c : reesAlgebra I) : Polynomial R)
      = ((algebraMap k (reesAlgebra (productIdeal k R R' I I')) c :
          reesAlgebra (productIdeal k R R' I I')) : Polynomial (R ⊗[k] R'))
    simp

/-- The map of Rees algebras induced by the inclusion of the right factor. -/
noncomputable def reesRightAlg :
    reesAlgebra I' →ₐ[k] reesAlgebra (productIdeal k R R' I I') where
  toFun p := ⟨Polynomial.map (inr k R R' : R' →+* R ⊗[k] R') (p : Polynomial R'),
    map_mem_reesAlgebra_right k R R' I I' p.2⟩
  map_one' := by apply Subtype.ext; simp
  map_mul' p q := by apply Subtype.ext; simp
  map_zero' := by apply Subtype.ext; simp
  map_add' p q := by apply Subtype.ext; simp
  commutes' c := by
    apply Subtype.ext
    change Polynomial.map (inr k R R' : R' →+* R ⊗[k] R')
        ((algebraMap k (reesAlgebra I') c : reesAlgebra I') : Polynomial R')
      = ((algebraMap k (reesAlgebra (productIdeal k R R' I I')) c :
          reesAlgebra (productIdeal k R R' I I')) : Polynomial (R ⊗[k] R'))
    simp

@[simp]
theorem coe_reesLeftAlg (p : reesAlgebra I) :
    ((reesLeftAlg k R R' I I' p : reesAlgebra (productIdeal k R R' I I')) : Polynomial (R ⊗[k] R'))
      = Polynomial.map (inl k R R' : R →+* R ⊗[k] R') (p : Polynomial R) := rfl

@[simp]
theorem coe_reesRightAlg (p : reesAlgebra I') :
    ((reesRightAlg k R R' I I' p : reesAlgebra (productIdeal k R R' I I')) :
        Polynomial (R ⊗[k] R'))
      = Polynomial.map (inr k R R' : R' →+* R ⊗[k] R') (p : Polynomial R') := rfl

/-! ### The comparison map on associated graded rings -/

/-- The defining ideal of the associated graded ring of the product ideal. -/
noncomputable abbrev productGradedIdeal : Ideal (reesAlgebra (productIdeal k R R' I I')) :=
  Ideal.map (algebraMap (R ⊗[k] R') (reesAlgebra (productIdeal k R R' I I')))
    (productIdeal k R R' I I')

/-- The left Rees map takes constants to constants. -/
theorem reesLeftAlg_algebraMap (x : R) :
    reesLeftAlg k R R' I I' (algebraMap R (reesAlgebra I) x) =
      algebraMap (R ⊗[k] R') (reesAlgebra (productIdeal k R R' I I')) (inl k R R' x) := by
  apply Subtype.ext
  simp

/-- The right Rees map takes constants to constants. -/
theorem reesRightAlg_algebraMap (y : R') :
    reesRightAlg k R R' I I' (algebraMap R' (reesAlgebra I') y) =
      algebraMap (R ⊗[k] R') (reesAlgebra (productIdeal k R R' I I')) (inr k R R' y) := by
  apply Subtype.ext
  simp

/-- The composite of the left Rees map with the reduction defining `gr_J` kills the ideal
defining `gr_I`. -/
theorem grLeft_aux : ∀ a ∈ Ideal.map (algebraMap R (reesAlgebra I)) I,
    ((Ideal.Quotient.mkₐ k (productGradedIdeal k R R' I I')).comp
      (reesLeftAlg k R R' I I')) a = 0 := by
  intro a ha
  rw [Ideal.map] at ha
  induction ha using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨x, hx, rfl⟩ := hz
    change Ideal.Quotient.mk _ (reesLeftAlg k R R' I I' (algebraMap R (reesAlgebra I) x)) = 0
    rw [reesLeftAlg_algebraMap, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_map_of_mem _ (inl_mem_productIdeal k R R' I I' hx)
  | zero => exact map_zero _
  | add z w _ _ hz hw => rw [map_add, hz, hw, add_zero]
  | smul c z _ hz =>
    rw [smul_eq_mul, map_mul, hz, mul_zero]

/-- The composite of the right Rees map with the reduction defining `gr_J` kills the ideal
defining `gr_{I'}`. -/
theorem grRight_aux : ∀ a ∈ Ideal.map (algebraMap R' (reesAlgebra I')) I',
    ((Ideal.Quotient.mkₐ k (productGradedIdeal k R R' I I')).comp
      (reesRightAlg k R R' I I')) a = 0 := by
  intro a ha
  rw [Ideal.map] at ha
  induction ha using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨y, hy, rfl⟩ := hz
    change Ideal.Quotient.mk _ (reesRightAlg k R R' I I' (algebraMap R' (reesAlgebra I') y)) = 0
    rw [reesRightAlg_algebraMap, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_map_of_mem _ (inr_mem_productIdeal k R R' I I' hy)
  | zero => exact map_zero _
  | add z w _ _ hz hw => rw [map_add, hz, hw, add_zero]
  | smul c z _ hz =>
    rw [smul_eq_mul, map_mul, hz, mul_zero]

/-- The map `gr_I(R) → gr_J(R ⊗[k] R')` induced by the inclusion of the left factor. -/
noncomputable def grLeft :
    AffineNormalCone.associatedGradedRing R I →ₐ[k]
      AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  Ideal.Quotient.liftₐ (Ideal.map (algebraMap R (reesAlgebra I)) I)
    ((Ideal.Quotient.mkₐ k (productGradedIdeal k R R' I I')).comp (reesLeftAlg k R R' I I'))
    (grLeft_aux k R R' I I')

/-- The map `gr_{I'}(R') → gr_J(R ⊗[k] R')` induced by the inclusion of the right factor. -/
noncomputable def grRight :
    AffineNormalCone.associatedGradedRing R' I' →ₐ[k]
      AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  Ideal.Quotient.liftₐ (Ideal.map (algebraMap R' (reesAlgebra I')) I')
    ((Ideal.Quotient.mkₐ k (productGradedIdeal k R R' I I')).comp (reesRightAlg k R R' I I'))
    (grRight_aux k R R' I I')

@[simp]
theorem grLeft_mk (p : reesAlgebra I) :
    grLeft k R R' I I' (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I) p) =
      Ideal.Quotient.mk (productGradedIdeal k R R' I I') (reesLeftAlg k R R' I I' p) := rfl

@[simp]
theorem grRight_mk (p : reesAlgebra I') :
    grRight k R R' I I' (Ideal.Quotient.mk (Ideal.map (algebraMap R' (reesAlgebra I')) I') p) =
      Ideal.Quotient.mk (productGradedIdeal k R R' I I') (reesRightAlg k R R' I I' p) := rfl

/-- **The comparison map for the affine normal cone of a product.**  On coordinate rings, the
canonical morphism `C_{U×U'/M×M'} → C_{U/M} × C_{U'/M'}`. -/
noncomputable def grTensorToGr :
    AffineNormalCone.associatedGradedRing R I ⊗[k]
        AffineNormalCone.associatedGradedRing R' I' →ₐ[k]
      AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  Algebra.TensorProduct.lift (grLeft k R R' I I') (grRight k R R' I I')
    fun _ _ ↦ Commute.all _ _

@[simp]
theorem grTensorToGr_tmul (a : AffineNormalCone.associatedGradedRing R I)
    (b : AffineNormalCone.associatedGradedRing R' I') :
    grTensorToGr k R R' I I' (a ⊗ₜ[k] b) =
      grLeft k R R' I I' a * grRight k R R' I I' b := by
  rw [grTensorToGr, Algebra.TensorProduct.lift_tmul]

/-! ### Surjectivity -/

/-- The degree-one generators of the Rees algebra of the product ideal. -/
noncomputable def productGenerators : Set (Polynomial (R ⊗[k] R')) :=
  (Polynomial.monomial 1) '' ((inl k R R' '' I) ∪ (inr k R R' '' I'))

/-- The Rees algebra of the product ideal is generated over `R ⊗[k] R'` by the degree-one
monomials attached to the generators of the product ideal. -/
theorem adjoin_productGenerators :
    Algebra.adjoin (R ⊗[k] R') (productGenerators k R R' I I') =
      reesAlgebra (productIdeal k R R' I I') := by
  refine le_antisymm ?_ ?_
  · rw [Algebra.adjoin_le_iff]
    rintro p ⟨j, hj, rfl⟩
    refine reesAlgebra.monomial_mem.mpr ?_
    rw [pow_one]
    rcases hj with ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
    · exact inl_mem_productIdeal k R R' I I' hx
    · exact inr_mem_productIdeal k R R' I I' hy
  · rw [← adjoin_monomial_eq_reesAlgebra (productIdeal k R R' I I'), Algebra.adjoin_le_iff]
    rintro p ⟨j, hj, rfl⟩
    rw [productIdeal_eq_span] at hj
    induction hj using Submodule.span_induction with
    | mem z hz => exact Algebra.subset_adjoin ⟨z, hz, rfl⟩
    | zero =>
      rw [map_zero]
      exact Subalgebra.zero_mem _
    | add z w _ _ hz hw =>
      rw [map_add]
      exact Subalgebra.add_mem _ hz hw
    | smul c z _ hz =>
      rw [smul_eq_mul, ← Polynomial.C_mul_monomial, Polynomial.C_eq_algebraMap]
      exact Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ c) hz

set_option synthInstance.maxHeartbeats 800000 in
-- Instance search for `AddHomClass` on algebra maps out of the tensor product of two
-- associated graded rings is slow; the default limit is not enough.
/-- Elements of `R ⊗[k] R'`, viewed as constants of the Rees algebra of the product ideal, are
in the image of the comparison map. -/
theorem exists_grTensorToGr_algebraMap (c : R ⊗[k] R') :
    ∃ s, grTensorToGr k R R' I I' s =
      Ideal.Quotient.mk (productGradedIdeal k R R' I I')
        (algebraMap (R ⊗[k] R') (reesAlgebra (productIdeal k R R' I I')) c) := by
  induction c using TensorProduct.induction_on with
  | zero => exact ⟨0, by simp⟩
  | tmul x y =>
    refine ⟨(Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)
        (algebraMap R (reesAlgebra I) x)) ⊗ₜ[k]
      (Ideal.Quotient.mk (Ideal.map (algebraMap R' (reesAlgebra I')) I')
        (algebraMap R' (reesAlgebra I') y)), ?_⟩
    rw [grTensorToGr_tmul, grLeft_mk, grRight_mk, reesLeftAlg_algebraMap,
      reesRightAlg_algebraMap, ← map_mul, ← map_mul]
    congr 2
    change (x ⊗ₜ[k] (1 : R')) * ((1 : R) ⊗ₜ[k] y) = x ⊗ₜ[k] y
    rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
  | add c₁ c₂ h₁ h₂ =>
    obtain ⟨s₁, hs₁⟩ := h₁
    obtain ⟨s₂, hs₂⟩ := h₂
    refine ⟨s₁ + s₂, ?_⟩
    simp only [map_add, hs₁, hs₂]

set_option synthInstance.maxHeartbeats 800000 in
-- Instance search for `AddHomClass` on algebra maps out of the tensor product of two
-- associated graded rings is slow; the default limit is not enough.
/-- **The comparison map is surjective.**  Equivalently, the induced morphism of affine normal
cones `C_{U×U'/M×M'} → C_{U/M} × C_{U'/M'}` is a closed immersion. -/
theorem grTensorToGr_surjective : Function.Surjective (grTensorToGr k R R' I I') := by
  intro z
  obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective z
  have hgen := adjoin_productGenerators k R R' I I'
  have toRees : ∀ {p : Polynomial (R ⊗[k] R')},
      p ∈ Algebra.adjoin (R ⊗[k] R') (productGenerators k R R' I I') →
      p ∈ reesAlgebra (productIdeal k R R' I I') := by
    intro p hp
    rw [← hgen]
    exact hp
  have hq : (q : Polynomial (R ⊗[k] R')) ∈
      Algebra.adjoin (R ⊗[k] R') (productGenerators k R R' I I') := by
    rw [hgen]
    exact q.2
  have hP : ∀ (a : Polynomial (R ⊗[k] R'))
      (ha : a ∈ Algebra.adjoin (R ⊗[k] R') (productGenerators k R R' I I')),
      ∃ s, grTensorToGr k R R' I I' s =
        Ideal.Quotient.mk (productGradedIdeal k R R' I I') ⟨a, toRees ha⟩ := by
    intro a ha
    induction ha using Algebra.adjoin_induction with
    | mem a ha =>
      obtain ⟨j, hj, rfl⟩ := ha
      rcases hj with ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
      · refine ⟨(Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)
          (AffineNormalCone.degreeOneRees R I ⟨x, hx⟩)) ⊗ₜ[k] 1, ?_⟩
        rw [grTensorToGr_tmul, map_one, mul_one, grLeft_mk]
        congr 1
        apply Subtype.ext
        simp
      · refine ⟨1 ⊗ₜ[k] (Ideal.Quotient.mk (Ideal.map (algebraMap R' (reesAlgebra I')) I')
          (AffineNormalCone.degreeOneRees R' I' ⟨y, hy⟩)), ?_⟩
        rw [grTensorToGr_tmul, map_one, one_mul, grRight_mk]
        congr 1
        apply Subtype.ext
        simp
    | algebraMap c =>
      obtain ⟨s, hs⟩ := exists_grTensorToGr_algebraMap k R R' I I' c
      refine ⟨s, hs.trans ?_⟩
      congr 1
    | add x y _ _ ihx ihy =>
      obtain ⟨sx, hsx⟩ := ihx
      obtain ⟨sy, hsy⟩ := ihy
      refine ⟨sx + sy, ?_⟩
      rw [map_add, hsx, hsy, ← map_add]
      rfl
    | mul x y _ _ ihx ihy =>
      obtain ⟨sx, hsx⟩ := ihx
      obtain ⟨sy, hsy⟩ := ihy
      refine ⟨sx * sy, ?_⟩
      rw [map_mul, hsx, hsy, ← map_mul]
      rfl
  obtain ⟨s, hs⟩ := hP (q : Polynomial (R ⊗[k] R')) hq
  exact ⟨s, hs⟩

/-! ### Compatibility with the degree-one generators -/

/-- The comparison map sends the degree-one class of `x ∈ I` to the degree-one class of
`x ⊗ 1 ∈ J`. -/
theorem grTensorToGr_degreeOne_left (x : I) :
    grTensorToGr k R R' I I'
        (AffineNormalCone.conormalToAssociatedGraded R I (I.toCotangent x) ⊗ₜ[k] 1) =
      AffineNormalCone.conormalToAssociatedGraded (R ⊗[k] R') (productIdeal k R R' I I')
        ((productIdeal k R R' I I').toCotangent
          ⟨inl k R R' (x : R), inl_mem_productIdeal k R R' I I' x.2⟩) := by
  rw [grTensorToGr_tmul, map_one, mul_one,
    AffineNormalCone.conormalToAssociatedGraded_toCotangent,
    AffineNormalCone.conormalToAssociatedGraded_toCotangent, grLeft_mk]
  congr 1
  apply Subtype.ext
  simp

/-- The comparison map sends the degree-one class of `y ∈ I'` to the degree-one class of
`1 ⊗ y ∈ J`. -/
theorem grTensorToGr_degreeOne_right (y : I') :
    grTensorToGr k R R' I I'
        (1 ⊗ₜ[k] AffineNormalCone.conormalToAssociatedGraded R' I' (I'.toCotangent y)) =
      AffineNormalCone.conormalToAssociatedGraded (R ⊗[k] R') (productIdeal k R R' I I')
        ((productIdeal k R R' I I').toCotangent
          ⟨inr k R R' (y : R'), inr_mem_productIdeal k R R' I I' y.2⟩) := by
  rw [grTensorToGr_tmul, map_one, one_mul,
    AffineNormalCone.conormalToAssociatedGraded_toCotangent,
    AffineNormalCone.conormalToAssociatedGraded_toCotangent, grRight_mk]
  congr 1
  apply Subtype.ext
  simp

/-! ### The isomorphism, conditionally on injectivity -/

/-- **The product formula for the affine normal cone**, granted injectivity of the comparison
map (which holds over a field; see the module docstring).  Then
`gr_J(R ⊗[k] R') ≅ gr_I(R) ⊗[k] gr_{I'}(R')`, that is,
`C_{U×U'/M×M'} ≅ C_{U/M} × C_{U'/M'}`. -/
noncomputable def grTensorEquiv (hinj : Function.Injective (grTensorToGr k R R' I I')) :
    AffineNormalCone.associatedGradedRing R I ⊗[k]
        AffineNormalCone.associatedGradedRing R' I' ≃ₐ[k]
      AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I') :=
  AlgEquiv.ofBijective (grTensorToGr k R R' I I')
    ⟨hinj, grTensorToGr_surjective k R R' I I'⟩

@[simp]
theorem grTensorEquiv_apply (hinj : Function.Injective (grTensorToGr k R R' I I')) (s) :
    grTensorEquiv k R R' I I' hinj s = grTensorToGr k R R' I I' s := rfl

/-- Unconditionally, the Krull dimension of the affine normal cone of the product is at most
that of the product of the affine normal cones. -/
theorem ringKrullDim_productIdeal_le :
    ringKrullDim (AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I'))
      ≤ ringKrullDim (AffineNormalCone.associatedGradedRing R I ⊗[k]
          AffineNormalCone.associatedGradedRing R' I') :=
  ringKrullDim_le_of_surjective _ (grTensorToGr_surjective k R R' I I')

/-- Granted injectivity, the affine normal cone of the product has the Krull dimension of the
product of the two affine normal cones. -/
theorem ringKrullDim_associatedGradedRing_productIdeal
    (hinj : Function.Injective (grTensorToGr k R R' I I')) :
    ringKrullDim (AffineNormalCone.associatedGradedRing (R ⊗[k] R') (productIdeal k R R' I I'))
      = ringKrullDim (AffineNormalCone.associatedGradedRing R I ⊗[k]
          AffineNormalCone.associatedGradedRing R' I') :=
  (ringKrullDim_eq_of_ringEquiv (grTensorEquiv k R R' I I' hinj).toRingEquiv).symm

end AffineNormalConeProduct

end GromovWitten.AlgebraicGeometry
