/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.AlgebraicGeometry.Cones.RegularSequence
import GromovWitten.AlgebraicGeometry.Cones.NormalConeGlobal
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis

/-!
# The principal regular normal cone

For a principal ideal generated by a non-zerodivisor, the conormal module is a free
rank-one module and the associated graded algebra is a polynomial algebra in the
class of the generator.  The statements in this file retain the specified generator;
they do not choose a generator of the ideal abstractly.
-/

open CategoryTheory AlgebraicGeometry

namespace GromovWitten.AlgebraicGeometry.AffineNormalCone

universe u

variable {R : Type u} [CommRing R]

section Conormal

variable (a : R) (ha : ∀ b : R, a * b = 0 → b = 0)

private abbrev I : Ideal R := Ideal.span {a}
private abbrev B : Type u := R ⧸ I a
private abbrev C : Type u := (I a).Cotangent

/-- The class of the displayed generator in the conormal module. -/
noncomputable def principalConormalGenerator : C a :=
  (I a).toCotangent ⟨a, Ideal.mem_span_singleton_self a⟩

@[simp]
theorem principalConormalGenerator_eq (r : R) :
    (I a).toCotangent ⟨r * a, Ideal.mem_span_singleton.mpr ⟨r, by ring⟩⟩ =
      r • principalConormalGenerator a := by
  change (I a).toCotangent (r • ⟨a, Ideal.mem_span_singleton_self a⟩) = _
  exact (I a).toCotangent.map_smul r ⟨a, Ideal.mem_span_singleton_self a⟩

private noncomputable def principalConormalMap : B a →ₗ[B a] C a :=
  LinearMap.toSpanSingleton (B a) (C a) (principalConormalGenerator a)

private theorem principalConormalMap_injective (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    Function.Injective (principalConormalMap a) := by
  intro x y hxy
  obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective x
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective y
  rw [← sub_eq_zero, ← map_sub, Ideal.Quotient.eq_zero_iff_mem]
  have hcot : (I a).toCotangent ⟨(r - s) * a, by
      rw [Ideal.mem_span_singleton]
      exact ⟨r - s, by ring⟩⟩ = 0 := by
    simp only [principalConormalMap, LinearMap.toSpanSingleton_apply] at hxy
    rw [← sub_eq_zero, ← sub_smul] at hxy
    change (Ideal.Quotient.mk (I a) r - Ideal.Quotient.mk (I a) s) •
      principalConormalGenerator a = 0 at hxy
    rw [sub_smul] at hxy
    rw [← Ideal.Quotient.algebraMap_eq (I a),
      IsScalarTower.algebraMap_smul (B a) r,
      IsScalarTower.algebraMap_smul (B a) s] at hxy
    rw [← sub_smul] at hxy
    change (r - s) • (I a).toCotangent
      ⟨a, Ideal.mem_span_singleton_self a⟩ = 0 at hxy
    rw [← (I a).toCotangent.map_smul] at hxy
    simpa [principalConormalGenerator, mul_comm] using hxy
  rw [Ideal.toCotangent_eq_zero] at hcot
  rw [Ideal.span_singleton_pow] at hcot
  rw [Ideal.mem_span_singleton] at hcot ⊢
  obtain ⟨t, ht⟩ := hcot
  refine ⟨t, ?_⟩
  apply sub_eq_zero.mp
  apply ha
  change (r - s) * a = a ^ 2 * t at ht
  calc
    a * ((r - s) - a * t) = (r - s) * a - a ^ 2 * t := by ring
    _ = 0 := by rw [ht]; ring

private theorem principalConormalMap_surjective (a : R) :
    Function.Surjective (principalConormalMap a) := by
  intro z
  obtain ⟨y, rfl⟩ := (I a).toCotangent_surjective z
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton.mp y.2
  refine ⟨Ideal.Quotient.mk (I a) r, ?_⟩
  change (Ideal.Quotient.mk (I a) r) • principalConormalGenerator a =
    (I a).toCotangent y
  rw [← Ideal.Quotient.algebraMap_eq (I a),
    IsScalarTower.algebraMap_smul (B a) r]
  have hy : (r • (⟨a, Ideal.mem_span_singleton_self a⟩ : I a)) = y := by
    apply Subtype.ext
    simp [hr, mul_comm]
  rw [← hy]
  rw [(I a).toCotangent.map_smul]
  rfl

/-- Explicit rank-one equivalence for the conormal module of a principal regular ideal.

The equivalence sends the class of `r` to the class of `r * a`. -/
noncomputable def principalConormalEquiv (a : R) (ha : ∀ b : R, a * b = 0 → b = 0) :
    B a ≃ₗ[B a] C a :=
  LinearEquiv.ofBijective (principalConormalMap a)
    ⟨principalConormalMap_injective a ha, principalConormalMap_surjective a⟩

@[simp]
theorem principalConormalEquiv_apply (r : B a) :
    principalConormalEquiv a ha r = r • principalConormalGenerator a :=
  rfl

@[simp]
theorem principalConormalEquiv_mk (r : R) :
    principalConormalEquiv a ha (Ideal.Quotient.mk (I a) r) =
      (I a).toCotangent ⟨r * a, by
        rw [Ideal.mem_span_singleton]
        exact ⟨r, by ring⟩⟩ := by
  rw [principalConormalEquiv_apply, ← Ideal.Quotient.algebraMap_eq (I a),
    IsScalarTower.algebraMap_smul (B a) r]
  exact (principalConormalGenerator_eq a r).symm

end Conormal

section PolynomialPresentation

variable (a : R) (ha : ∀ b : R, a * b = 0 → b = 0)

/-- The singleton basis obtained from the explicit conormal generator. -/
noncomputable def principalConormalBasis :
    Module.Basis (PUnit.{1}) (B a) (C a) :=
  (Module.Basis.singleton (PUnit.{1}) (B a)).map (principalConormalEquiv a ha)

@[simp]
theorem principalConormalBasis_apply (i : PUnit.{1}) :
    principalConormalBasis a ha i = principalConormalGenerator a := by
  rw [principalConormalBasis, Module.Basis.map_apply]
  simp [principalConormalEquiv_apply]

/-- The normal-sheaf coordinate algebra is a polynomial algebra in the conormal generator. -/
noncomputable def principalNormalSheafPolynomialEquiv (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    SymmetricAlgebra (B a) (C a) ≃ₐ[B a] Polynomial (B a) :=
  (SymmetricAlgebra.equivMvPolynomial (principalConormalBasis a ha)).trans
    (MvPolynomial.uniqueAlgEquiv (B a) (PUnit.{1}))

@[simp]
theorem principalNormalSheafPolynomialEquiv_generator :
    principalNormalSheafPolynomialEquiv a ha
        (SymmetricAlgebra.ι (B a) (C a) (principalConormalGenerator a)) =
      Polynomial.X := by
  rw [principalNormalSheafPolynomialEquiv, AlgEquiv.trans_apply,
    ← principalConormalBasis_apply a ha PUnit.unit]
  rw [SymmetricAlgebra.equivMvPolynomial_ι_apply,
    MvPolynomial.uniqueAlgEquiv_apply]
  simp

/-- The associated graded algebra of a principal regular ideal is a polynomial algebra. -/
noncomputable def principalNormalConePolynomialEquiv :
    associatedGradedRing R (I a) ≃ₐ[B a] Polynomial (B a) :=
  (RegularGenerators.principal a ha rfl).normalSheafCoordinateAlgEquiv.symm.trans
    (principalNormalSheafPolynomialEquiv a ha)

@[simp]
theorem principalNormalConePolynomialEquiv_base (r : B a) :
    principalNormalConePolynomialEquiv a ha
        (associatedGradedBaseRingHom R (I a) r) = Polynomial.C r := by
  let x := RegularGenerators.principal a ha rfl
  change principalNormalSheafPolynomialEquiv a ha
      (x.normalSheafCoordinateAlgEquiv.symm (algebraMap (B a)
        (associatedGradedRing R (I a)) r)) = Polynomial.C r
  rw [← x.normalSheafCoordinateEquiv_base r]
  change principalNormalSheafPolynomialEquiv a ha
      (x.normalSheafCoordinateAlgEquiv.symm
        (x.normalSheafCoordinateAlgEquiv
          (algebraMap (B a) (normalSheafCoordinateRing R (I a)) r))) = _
  rw [x.normalSheafCoordinateAlgEquiv.symm_apply_apply]
  exact (principalNormalSheafPolynomialEquiv a ha).commutes r

@[simp]
theorem principalNormalConePolynomialEquiv_generator :
    principalNormalConePolynomialEquiv a ha
        (conormalToAssociatedGraded R (I a)
          ((I a).toCotangent ⟨a, Ideal.mem_span_singleton_self a⟩)) =
      Polynomial.X := by
  let x := RegularGenerators.principal a ha rfl
  have hx := x.normalSheafCoordinateEquiv_ι
    ((I a).toCotangent ⟨a, Ideal.mem_span_singleton_self a⟩)
  change x.normalSheafCoordinateAlgEquiv
      (SymmetricAlgebra.ι (B a) (C a)
        ((I a).toCotangent ⟨a, Ideal.mem_span_singleton_self a⟩)) = _ at hx
  rw [principalNormalConePolynomialEquiv, AlgEquiv.trans_apply]
  rw [hx.symm]
  rw [x.normalSheafCoordinateAlgEquiv.symm_apply_apply]
  exact principalNormalSheafPolynomialEquiv_generator a ha

end PolynomialPresentation

section SchemePresentation

variable (a : R) (ha : ∀ b : R, a * b = 0 → b = 0)

/-- The polynomial presentation of the trivial affine line over `R/(a)`. -/
noncomputable def principalAffineLinePolynomialEquiv (a : R) :
    SymmetricAlgebra (B a) (B a) ≃ₐ[B a] Polynomial (B a) :=
  (SymmetricAlgebra.equivMvPolynomial
      (Module.Basis.singleton (PUnit.{1}) (B a))).trans
    (MvPolynomial.uniqueAlgEquiv (B a) (PUnit.{1}))

@[simp]
theorem principalAffineLinePolynomialEquiv_generator :
    principalAffineLinePolynomialEquiv a
        (SymmetricAlgebra.ι (B a) (B a) 1) = Polynomial.X := by
  rw [principalAffineLinePolynomialEquiv, AlgEquiv.trans_apply,
    ← Module.Basis.singleton_apply (PUnit.{1}) (B a) PUnit.unit]
  rw [SymmetricAlgebra.equivMvPolynomial_ι_apply,
    MvPolynomial.uniqueAlgEquiv_apply]
  simp

/-- The normal sheaf is canonically the affine line associated to the displayed generator. -/
noncomputable def principalNormalSheafLineIso (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    normalSheaf R (I a) ≅ AffineCone.scheme (B a) (B a) :=
  Scheme.Spec.mapIso (symCongr (principalConormalEquiv a ha)).toCommRingCatIso.op

set_option maxHeartbeats 200000 in
-- The affine-scheme composition expands through opposite commutative-ring categories.
@[simp]
theorem principalNormalSheafLineIso_hom_comp_projection :
    (principalNormalSheafLineIso a ha).hom ≫ AffineCone.projection (B a) (B a) =
      AffineCone.projection (B a) (C a) := by
  change _root_.AlgebraicGeometry.Spec.map _ ≫
      _root_.AlgebraicGeometry.Spec.map _ = _root_.AlgebraicGeometry.Spec.map _
  rw [← _root_.AlgebraicGeometry.Spec.map_comp,
    _root_.AlgebraicGeometry.Spec.map_inj]
  ext r
  exact (symCongr (principalConormalEquiv a ha)).commutes r

set_option maxHeartbeats 200000 in
-- The affine-scheme composition expands through opposite commutative-ring categories.
@[simp]
theorem vertex_comp_principalNormalSheafLineIso_hom :
    AffineCone.vertex (B a) (C a) ≫ (principalNormalSheafLineIso a ha).hom =
      AffineCone.vertex (B a) (B a) := by
  change _root_.AlgebraicGeometry.Spec.map _ ≫
      _root_.AlgebraicGeometry.Spec.map _ = _root_.AlgebraicGeometry.Spec.map _
  rw [← _root_.AlgebraicGeometry.Spec.map_comp,
    _root_.AlgebraicGeometry.Spec.map_inj]
  apply CommRingCat.hom_ext
  apply RingHom.ext
  intro z
  induction z using SymmetricAlgebra.induction with
  | algebraMap r => simp
  | ι m =>
      change AffineCone.augmentation (B a) (C a)
          (symCongr (principalConormalEquiv a ha)
            (SymmetricAlgebra.ι (B a) (B a) m)) =
        AffineCone.augmentation (B a) (B a)
          (SymmetricAlgebra.ι (B a) (B a) m)
      rw [symCongr_ι]
      change SymmetricAlgebra.algebraMapInv
          (SymmetricAlgebra.ι (B a) (C a) (principalConormalEquiv a ha m)) =
        SymmetricAlgebra.algebraMapInv
          (SymmetricAlgebra.ι (B a) (B a) m)
      rw [SymmetricAlgebra.algebraMapInv_ι,
        SymmetricAlgebra.algebraMapInv_ι]
  | mul x y hx hy =>
      simpa only [map_mul] using congrArg₂ (· * ·) hx hy
  | add x y hx hy =>
      simpa only [map_add] using congrArg₂ (· + ·) hx hy

/-- The normal cone is canonically the affine line associated to the displayed generator. -/
noncomputable def principalNormalConeLineIso (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    scheme R (I a) ≅ AffineCone.scheme (B a) (B a) :=
  (principalSchemeIsoNormalSheaf a ha).trans
    (principalNormalSheafLineIso a ha)

@[simp]
theorem principalNormalConeLineIso_hom_comp_projection :
    (principalNormalConeLineIso a ha).hom ≫ AffineCone.projection (B a) (B a) =
      projection R (I a) := by
  rw [principalNormalConeLineIso, Iso.trans_hom, Category.assoc,
    principalNormalSheafLineIso_hom_comp_projection]
  exact RegularGenerators.schemeIsoNormalSheaf_hom_comp_projection
    (RegularGenerators.principal a ha rfl)

@[simp]
theorem vertex_comp_principalNormalConeLineIso_hom :
    vertex R (I a) ≫ (principalNormalConeLineIso a ha).hom =
      AffineCone.vertex (B a) (B a) := by
  rw [principalNormalConeLineIso, Iso.trans_hom, ← Category.assoc]
  change (vertex R (I a) ≫
      (RegularGenerators.principal a ha rfl).schemeIsoNormalSheaf.hom) ≫
      (principalNormalSheafLineIso a ha).hom = _
  rw [RegularGenerators.vertex_comp_schemeIsoNormalSheaf_hom
    (RegularGenerators.principal a ha rfl)]
  exact vertex_comp_principalNormalSheafLineIso_hom a ha

end SchemePresentation

end GromovWitten.AlgebraicGeometry.AffineNormalCone
