/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.NormalSheafPicard
import Mathlib.RingTheory.Finiteness.Projective
import Mathlib.RingTheory.Flat.EquationalCriterion

/-!
# Products and fibre products of affine cones, and the vector bundle criterion

This file completes Layer 1 of the virtual fundamental class roadmap over an affine base
`Spec R`: products and fibre products of affine cones and of cone actions, and the criterion
recognising `C(F) = Spec Sym(F)` as a vector bundle.

## Contents

* Algebra retracts: `AlgebraRetract.formallySmooth`, `AlgebraRetract.fg_ker`,
  `AlgebraRetract.finitePresentation` and `AlgebraRetract.smooth`.  A retract of a formally
  smooth (resp. finitely presented, resp. smooth) `R`-algebra is again one.  The kernel of the
  retraction is computed explicitly (`AlgebraRetract.ker_eq_span`).
* Products of cones: `GradedCone.isConeHom_tensorLift` is the universal property of the product
  cone `Spec (S ⊗[R] S')` in the category of cones, and `GradedCone.isConeHom_tensorMap` says
  that a product of cone morphisms is a cone morphism.  `GradedCone.isPullback_projection`
  records that `Spec (S ⊗[R] S')` is the fibre product of `Spec S` and `Spec S'` over `Spec R`.
* `C(M × N) = C(M) ×_{Spec R} C(N)`: `GradedCone.isConeHom_symProdEquiv` and
  `GradedCone.isConeHom_symProdEquiv_symm` show that `NormalSheafPicard.symProdEquiv` is an
  isomorphism of cones, and `GradedCone.isPullback_symProd` is the resulting fibre product
  square of schemes, whose projections are induced by `LinearMap.inl` and `LinearMap.inr`.
* The vector bundle criterion: `GradedCone.smooth_symmetricAlgebra_of_projective` proves
  `Algebra.Smooth R (Sym F)` for every finite projective `R`-module `F`, whence
  `GradedCone.smooth_projection_of_projective`, the smoothness of `C(F) → Spec R`.  The
  converse `GradedCone.projective_of_flat_symmetricAlgebra` deduces projectivity of a finitely
  presented `F` from flatness of `Sym F`.
* Products of cone actions: `ConeQuotient.ConeAction.prod` is the action of `E × E'` on
  `C ×_{Spec R} C'`, `ConeQuotient.ConeAction.pullback` transports an action along a morphism
  of vector bundles, and `ConeQuotient.ConeAction.diagonal` is the diagonal action of `E` on
  `C ×_{Spec R} C'`.  The projections are equivariant
  (`ConeQuotient.isEquivariant_prod_left`, `ConeQuotient.isEquivariant_diagonal_left`, and
  their right-hand analogues).
* The `R/I`-linear vertex of the affine normal cone:
  `GradedCone.normalConeCoactionQuot` is the contraction coaction of `gr_I(R)` viewed over its
  own degree-zero part `R/I`, `GradedCone.normalConeVertexHom` is the degree-zero augmentation
  as an `R/I`-algebra map, and `GradedCone.isConeVertex_normalConeCoactionQuot` proves that it
  is a cone vertex in the sense of `GradedCone.IsConeVertex` over the base `R/I`.

Everything is at the level of `R`-algebras with coactions; the scheme-level statements are
obtained by applying `Spec`.  No non-affine base is treated here, and the comparison of
`Spec Sym F` with the `VectorBundleStack` of `Cones/Stack.lean` is not attempted.
-/

open CategoryTheory AlgebraicGeometry Polynomial

open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

universe u

/-! ## Retracts of algebras -/

namespace AlgebraRetract

variable {R P A : Type*} [CommRing R] [CommRing P] [CommRing A] [Algebra R P] [Algebra R A]

/-- A retraction is surjective. -/
theorem surjective_of_comp_eq_id {i : A →ₐ[R] P} {p : P →ₐ[R] A}
    (h : p.comp i = AlgHom.id R A) : Function.Surjective p :=
  fun a => ⟨i a, AlgHom.congr_fun h a⟩

/-- The kernel of a retraction `p : P →ₐ[R] A` with section `i` is generated by the elements
`x - i (p x)` for `x` running through any set of algebra generators of `P`. -/
theorem ker_eq_span {i : A →ₐ[R] P} {p : P →ₐ[R] A} (h : p.comp i = AlgHom.id R A)
    (s : Set P) (hs : Algebra.adjoin R s = ⊤) :
    RingHom.ker p.toRingHom = Ideal.span ((fun x => x - i (p x)) '' s) := by
  set J : Ideal P := Ideal.span ((fun x => x - i (p x)) '' s) with hJ
  have hpi : ∀ a : A, p (i a) = a := AlgHom.congr_fun h
  have key : ∀ x : P, x - i (p x) ∈ J := by
    intro x
    have hx : x ∈ Algebra.adjoin R s := hs ▸ Algebra.mem_top
    induction hx using Algebra.adjoin_induction with
    | mem y hy => exact Ideal.subset_span ⟨y, hy, rfl⟩
    | algebraMap r => simp
    | add y z _ _ hy hz =>
      have e : y + z - i (p (y + z)) = (y - i (p y)) + (z - i (p z)) := by
        rw [map_add, map_add]; ring
      rw [e]
      exact J.add_mem hy hz
    | mul y z _ _ hy hz =>
      have e : y * z - i (p (y * z)) =
          (y - i (p y)) * z + i (p y) * (z - i (p z)) := by
        rw [map_mul, map_mul]; ring
      rw [e]
      exact J.add_mem (J.mul_mem_right _ hy) (J.mul_mem_left _ hz)
  refine le_antisymm (fun x hx => ?_) ?_
  · have hx0 : p x = 0 := hx
    simpa [hx0] using key x
  · rw [hJ, Ideal.span_le]
    rintro _ ⟨y, -, rfl⟩
    change p (y - i (p y)) = 0
    rw [map_sub, hpi, sub_self]

/-- The kernel of a retraction of a finite type algebra is finitely generated. -/
theorem fg_ker [Algebra.FiniteType R P] {i : A →ₐ[R] P} {p : P →ₐ[R] A}
    (h : p.comp i = AlgHom.id R A) : (RingHom.ker p.toRingHom).FG := by
  obtain ⟨s, hs⟩ := (Algebra.FiniteType.out : (⊤ : Subalgebra R P).FG)
  rw [ker_eq_span h (s : Set P) hs]
  exact Submodule.fg_span (s.finite_toSet.image _)

/-- A retract of a finitely presented algebra is finitely presented. -/
theorem finitePresentation [Algebra.FinitePresentation R P] {i : A →ₐ[R] P} {p : P →ₐ[R] A}
    (h : p.comp i = AlgHom.id R A) : Algebra.FinitePresentation R A :=
  Algebra.FinitePresentation.of_surjective (surjective_of_comp_eq_id h) (fg_ker h)

end AlgebraRetract

namespace AlgebraRetract

variable {R P A : Type u} [CommRing R] [CommRing P] [CommRing A] [Algebra R P] [Algebra R A]

/-- A retract of a formally smooth algebra is formally smooth: lift along the ambient algebra
and restrict along the section. -/
theorem formallySmooth [Algebra.FormallySmooth R P] {i : A →ₐ[R] P} {p : P →ₐ[R] A}
    (h : p.comp i = AlgHom.id R A) : Algebra.FormallySmooth R A := by
  rw [Algebra.FormallySmooth.iff_comp_surjective]
  intro B _ _ I hI f
  obtain ⟨g, hg⟩ := Algebra.FormallySmooth.comp_surjective R P I hI (f.comp p)
  refine ⟨g.comp i, ?_⟩
  rw [← AlgHom.comp_assoc, hg, AlgHom.comp_assoc, h, AlgHom.comp_id]

/-- A retract of a smooth algebra is smooth. -/
theorem smooth [Algebra.Smooth R P] {i : A →ₐ[R] P} {p : P →ₐ[R] A}
    (h : p.comp i = AlgHom.id R A) : Algebra.Smooth R A where
  formallySmooth := formallySmooth h
  finitePresentation := finitePresentation h

end AlgebraRetract

/-! ## Products of cones: the universal property -/

namespace GradedCone

section ProductUniversal

variable {R S S' S'' T T' : Type*} [CommRing R] [CommRing S] [Algebra R S]
  [CommRing S'] [Algebra R S'] [CommRing S''] [Algebra R S''] [CommRing T] [Algebra R T]
  [CommRing T'] [Algebra R T']

/-- Coefficientwise application of the identity is the identity. -/
@[simp]
theorem mapAlgHom_id : Polynomial.mapAlgHom (AlgHom.id R S) = AlgHom.id R (Polynomial S) :=
  Polynomial.algHom_ext' (AlgHom.ext fun s => by simp) (by simp)

/-- The inverse of an isomorphism of cones is an isomorphism of cones. -/
theorem isConeHom_symm {ψ : S →ₐ[R] Polynomial S} {ψ' : S' →ₐ[R] Polynomial S'}
    {e : S ≃ₐ[R] S'} (h : IsConeHom ψ ψ' (e : S →ₐ[R] S')) :
    IsConeHom ψ' ψ (e.symm : S' →ₐ[R] S) := by
  have hcomp : ((e.symm : S' →ₐ[R] S).comp (e : S →ₐ[R] S')) = AlgHom.id R S :=
    AlgHom.ext fun s => e.symm_apply_apply s
  have key : ((Polynomial.mapAlgHom (e.symm : S' →ₐ[R] S)).comp ψ').comp (e : S →ₐ[R] S') =
      (ψ.comp (e.symm : S' →ₐ[R] S)).comp (e : S →ₐ[R] S') := by
    rw [AlgHom.comp_assoc, ← h, ← AlgHom.comp_assoc, mapAlgHom_comp, hcomp, mapAlgHom_id,
      AlgHom.id_comp, AlgHom.comp_assoc, hcomp, AlgHom.comp_id]
  refine AlgHom.ext fun s' => ?_
  simpa using AlgHom.congr_fun key (e.symm s')

/-- **The universal property of the product of two cones.**  A pair of cone morphisms
`T → C` and `T → C'` (that is, `R`-algebra maps `S → T` and `S' → T` intertwining the
coactions) induces a cone morphism `T → C ×_{Spec R} C'`, namely the canonical map out of the
tensor product. -/
theorem isConeHom_tensorLift {ψ : S →ₐ[R] Polynomial S} {ψ' : S' →ₐ[R] Polynomial S'}
    {ψT : T →ₐ[R] Polynomial T} {f : S →ₐ[R] T} {g : S' →ₐ[R] T}
    (hf : IsConeHom ψ ψT f) (hg : IsConeHom ψ' ψT g) :
    IsConeHom (tensorCoaction ψ ψ') ψT
      (Algebra.TensorProduct.lift f g fun _ _ => Commute.all _ _) := by
  refine tensor_ext ?_ ?_
  · rw [AlgHom.comp_assoc, ← isConeHom_includeLeft ψ ψ', ← AlgHom.comp_assoc, mapAlgHom_comp,
      AlgHom.comp_assoc, Algebra.TensorProduct.lift_comp_includeLeft]
    exact hf
  · rw [AlgHom.comp_assoc, ← isConeHom_includeRight ψ ψ', ← AlgHom.comp_assoc, mapAlgHom_comp,
      AlgHom.comp_assoc, Algebra.TensorProduct.lift_comp_includeRight']
    exact hg

/-- Two cone morphisms into a product cone agreeing on both factors are equal: the morphism
produced by `isConeHom_tensorLift` is the unique one. -/
theorem tensorLift_unique {f g : (S ⊗[R] S') →ₐ[R] T}
    (hL : f.comp Algebra.TensorProduct.includeLeft = g.comp Algebra.TensorProduct.includeLeft)
    (hR : f.comp Algebra.TensorProduct.includeRight =
      g.comp Algebra.TensorProduct.includeRight) : f = g :=
  tensor_ext hL hR

/-- The map of tensor products induced by two algebra maps, written as the canonical map out of
the tensor product. -/
theorem tensorMap_eq_lift (f : S →ₐ[R] T) (g : S' →ₐ[R] T') :
    Algebra.TensorProduct.map f g =
      Algebra.TensorProduct.lift
        ((Algebra.TensorProduct.includeLeft : T →ₐ[R] T ⊗[R] T').comp f)
        ((Algebra.TensorProduct.includeRight : T' →ₐ[R] T ⊗[R] T').comp g)
        fun _ _ => Commute.all _ _ := by
  refine tensor_ext ?_ ?_
  · rw [Algebra.TensorProduct.map_comp_includeLeft,
      Algebra.TensorProduct.lift_comp_includeLeft]
  · rw [Algebra.TensorProduct.map_comp_includeRight,
      Algebra.TensorProduct.lift_comp_includeRight']

/-- The product of two morphisms of cones is a morphism of the product cones. -/
theorem isConeHom_tensorMap {ψ : S →ₐ[R] Polynomial S} {ψ' : S' →ₐ[R] Polynomial S'}
    {χ : T →ₐ[R] Polynomial T} {χ' : T' →ₐ[R] Polynomial T'} {f : S →ₐ[R] T} {g : S' →ₐ[R] T'}
    (hf : IsConeHom ψ χ f) (hg : IsConeHom ψ' χ' g) :
    IsConeHom (tensorCoaction ψ ψ') (tensorCoaction χ χ')
      (Algebra.TensorProduct.map f g) := by
  rw [tensorMap_eq_lift]
  exact isConeHom_tensorLift (hf.comp (isConeHom_includeLeft χ χ'))
    (hg.comp (isConeHom_includeRight χ χ'))

end ProductUniversal

section ProductScheme

variable (R S S' : Type u) [CommRing R] [CommRing S] [Algebra R S] [CommRing S'] [Algebra R S']

/-- **The product of two affine cones over `Spec R`.**  `Spec (S ⊗[R] S')` together with the
two projections induced by `includeLeft` and `includeRight` is the fibre product of `Spec S`
and `Spec S'` over `Spec R`. -/
theorem isPullback_projection :
    IsPullback
      (Spec.map (CommRingCat.ofHom
        (Algebra.TensorProduct.includeLeftRingHom : S →+* S ⊗[R] S')))
      (Spec.map (CommRingCat.ofHom
        (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S').toRingHom))
      (projection R S) (projection R S') :=
  AlgebraicGeometry.isPullback_SpecMap_of_isPushout _ _ _ _
    (CommRingCat.isPushout_tensorProduct R S S')

end ProductScheme

end GradedCone

/-! ## Functoriality of the symmetric algebra -/

namespace ConeQuotient

variable {R : Type u} [CommRing R]
variable {F F' F'' : Type u} [AddCommGroup F] [Module R F] [AddCommGroup F'] [Module R F']
  [AddCommGroup F''] [Module R F'']

/-- `symMap` is functorial: it turns composition of linear maps into composition of algebra
maps. -/
theorem symMap_comp (u : F →ₗ[R] F') (u' : F' →ₗ[R] F'') :
    symMap (u'.comp u) = (symMap u').comp (symMap u) :=
  SymmetricAlgebra.algHom_ext (LinearMap.ext fun m => by simp)

/-- `symMap` sends the identity to the identity. -/
@[simp]
theorem symMap_id : symMap (LinearMap.id : F →ₗ[R] F) = AlgHom.id R (SymmetricAlgebra R F) := by
  rw [symMap, LinearMap.comp_id, SymmetricAlgebra.lift_ι]

end ConeQuotient

/-! ## The vector bundle criterion for `Spec Sym F` -/

namespace GradedCone

open ConeQuotient

variable (R : Type u) [CommRing R] (F : Type u) [AddCommGroup F] [Module R F]

/-- A module retract `F → G → F` induces an algebra retract `Sym F → Sym G → Sym F`. -/
theorem symMap_comp_symMap_of_comp_eq_id {G : Type u} [AddCommGroup G] [Module R G]
    {i : F →ₗ[R] G} {q : G →ₗ[R] F} (h : q.comp i = LinearMap.id) :
    (symMap q).comp (symMap i) = AlgHom.id R (SymmetricAlgebra R F) := by
  rw [← symMap_comp, h, symMap_id]

/-- **The vector bundle criterion.**  For a finite projective `R`-module `F` the coordinate
algebra `Sym F` of the cone `C(F) = Spec Sym F` is a smooth `R`-algebra: `F` is a retract of a
finite free module, hence `Sym F` is a retract of a polynomial algebra. -/
theorem smooth_symmetricAlgebra_of_projective [Module.Finite R F] [Module.Projective R F] :
    Algebra.Smooth R (SymmetricAlgebra R F) := by
  obtain ⟨n, f, g, -, -, hfg⟩ := Module.Finite.exists_comp_eq_id_of_projective R F
  have _ : Algebra.Smooth R (SymmetricAlgebra R (Fin n → R)) :=
    smooth_symmetricAlgebra R (Fin n → R)
  exact AlgebraRetract.smooth (symMap_comp_symMap_of_comp_eq_id R F hfg)

/-- The vector bundle `C(F) = Spec Sym F` of a finite projective module is smooth over its
base `Spec R`. -/
theorem smooth_projection_of_projective [Module.Finite R F] [Module.Projective R F] :
    AlgebraicGeometry.Smooth (projection R (SymmetricAlgebra R F)) := by
  refine AlgebraicGeometry.HasRingHomProperty.Spec_iff.2 ?_
  exact RingHom.smooth_algebraMap.2 (smooth_symmetricAlgebra_of_projective R F)

/-- The module `F` is a retract of its symmetric algebra, as an `R`-module. -/
theorem symIInv_comp_ι : (symIInv R F).comp (SymmetricAlgebra.ι R F) = LinearMap.id :=
  LinearMap.ext (symIInv_ι R F)

/-- **Converse to the vector bundle criterion.**  If the coordinate algebra `Sym F` of the cone
`C(F)` is a flat `R`-module and `F` is finitely presented, then `F` is projective, so `C(F)` is
an honest vector bundle.  Indeed `F` is an `R`-module retract of `Sym F`, hence flat, and a
finitely presented flat module is projective. -/
theorem projective_of_flat_symmetricAlgebra [Module.FinitePresentation R F]
    (h : Module.Flat R (SymmetricAlgebra R F)) : Module.Projective R F := by
  have _ : Module.Flat R F :=
    h.of_retract (SymmetricAlgebra.ι R F) (symIInv R F) (symIInv_comp_ι R F)
  exact Module.Flat.projective_of_finitePresentation

/-- The relative dimension of the vector bundle `C(F)` over a finite free module: the
degree-one part of `Sym F` is `F`, so it has the expected rank. -/
theorem finrank_homogeneous_one_eq [Module.Free R F] [Module.Finite R F] :
    Module.finrank R (homogeneous (symCoaction R F) 1) = Module.finrank R F :=
  finrank_homogeneous_one R F

end GradedCone

/-! ## `C(M × N)` is the product of `C(M)` and `C(N)` -/

namespace GradedCone

open ConeQuotient

variable (R : Type u) [CommRing R] (M N : Type u) [AddCommGroup M] [Module R M]
  [AddCommGroup N] [Module R N]

/-- A linear map induces a morphism of the associated affine cones. -/
theorem isConeHom_symMap (u : M →ₗ[R] N) :
    IsConeHom (symCoaction R M) (symCoaction R N) (symMap u) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m => ?_)
  change Polynomial.mapAlgHom (symMap u) (symCoaction R M (SymmetricAlgebra.ι R M m)) =
    symCoaction R N (symMap u (SymmetricAlgebra.ι R M m))
  rw [symMap_ι, symCoaction_ι, symCoaction_ι, map_mul]
  simp

/-- **`Sym(M × N) ≃ Sym M ⊗ Sym N` is an isomorphism of cones.**  Together with
`isConeHom_symProdEquiv_symm` this identifies `C(M × N)` with the product cone
`C(M) ×_{Spec R} C(N)`, compatibly with the contractions. -/
theorem isConeHom_symProdEquiv :
    IsConeHom (symCoaction R (M × N))
      (tensorCoaction (symCoaction R M) (symCoaction R N))
      ((NormalSheafPicard.symProdEquiv R M N :
        SymmetricAlgebra R (M × N) ≃ₐ[R] _) : SymmetricAlgebra R (M × N) →ₐ[R] _) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun x => ?_)
  have hL : Polynomial.mapAlgHom
      ((NormalSheafPicard.symProdEquiv R M N : SymmetricAlgebra R (M × N) ≃ₐ[R] _) :
        SymmetricAlgebra R (M × N) →ₐ[R] _)
      (symCoaction R (M × N) (SymmetricAlgebra.ι R (M × N) x)) =
      Polynomial.C (NormalSheafPicard.symProdEquiv R M N
        (SymmetricAlgebra.ι R (M × N) x)) * Polynomial.X := by
    rw [symCoaction_ι, map_mul]
    simp
  have hR : tensorCoaction (symCoaction R M) (symCoaction R N)
      (NormalSheafPicard.symProdEquiv R M N (SymmetricAlgebra.ι R (M × N) x)) =
      Polynomial.C (NormalSheafPicard.symProdEquiv R M N
        (SymmetricAlgebra.ι R (M × N) x)) * Polynomial.X := by
    rw [show x = (x.1, x.2) from rfl, NormalSheafPicard.symProdEquiv_ι, map_add,
      tensorCoaction_tmul, tensorCoaction_tmul]
    simp [add_mul]
  exact hL.trans hR.symm

/-- The inverse isomorphism `Sym M ⊗ Sym N ≃ Sym(M × N)` is also an isomorphism of cones. -/
theorem isConeHom_symProdEquiv_symm :
    IsConeHom (tensorCoaction (symCoaction R M) (symCoaction R N))
      (symCoaction R (M × N))
      ((NormalSheafPicard.symProdEquiv R M N).symm :
        SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N →ₐ[R] SymmetricAlgebra R (M × N)) :=
  isConeHom_symm (isConeHom_symProdEquiv R M N)

/-- The projection `C(M × N) → C(M)` corresponds, on the two descriptions of the product, to
the inclusion of the first factor. -/
theorem symProdEquiv_comp_symMap_inl :
    ((NormalSheafPicard.symProdEquiv R M N :
        SymmetricAlgebra R (M × N) ≃ₐ[R] _) : SymmetricAlgebra R (M × N) →ₐ[R] _).comp
        (symMap (LinearMap.inl R M N)) =
      (Algebra.TensorProduct.includeLeft :
        SymmetricAlgebra R M →ₐ[R] SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m => ?_)
  change NormalSheafPicard.symProdEquiv R M N
    (symMap (LinearMap.inl R M N) (SymmetricAlgebra.ι R M m)) = _
  rw [symMap_ι, LinearMap.inl_apply, NormalSheafPicard.symProdEquiv_ι]
  simp

/-- The projection `C(M × N) → C(N)` corresponds to the inclusion of the second factor. -/
theorem symProdEquiv_comp_symMap_inr :
    ((NormalSheafPicard.symProdEquiv R M N :
        SymmetricAlgebra R (M × N) ≃ₐ[R] _) : SymmetricAlgebra R (M × N) →ₐ[R] _).comp
        (symMap (LinearMap.inr R M N)) =
      (Algebra.TensorProduct.includeRight :
        SymmetricAlgebra R N →ₐ[R] SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun n => ?_)
  change NormalSheafPicard.symProdEquiv R M N
    (symMap (LinearMap.inr R M N) (SymmetricAlgebra.ι R N n)) = _
  rw [symMap_ι, LinearMap.inr_apply, NormalSheafPicard.symProdEquiv_ι]
  simp

/-- `Sym(inl)` is carried to `includeLeft` by the comparison isomorphism. -/
theorem symProdEquiv_symm_includeLeft (s : SymmetricAlgebra R M) :
    (NormalSheafPicard.symProdEquiv R M N).symm
        ((Algebra.TensorProduct.includeLeft : SymmetricAlgebra R M →ₐ[R]
          SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N) s) =
      symMap (LinearMap.inl R M N) s := by
  rw [AlgEquiv.symm_apply_eq]
  exact (AlgHom.congr_fun (symProdEquiv_comp_symMap_inl R M N) s).symm

/-- `Sym(inr)` is carried to `includeRight` by the comparison isomorphism. -/
theorem symProdEquiv_symm_includeRight (t : SymmetricAlgebra R N) :
    (NormalSheafPicard.symProdEquiv R M N).symm
        (Algebra.TensorProduct.includeRight t) = symMap (LinearMap.inr R M N) t := by
  rw [AlgEquiv.symm_apply_eq]
  exact (AlgHom.congr_fun (symProdEquiv_comp_symMap_inr R M N) t).symm

/-- The square of symmetric algebras attached to `M × N` is a pushout of commutative rings. -/
theorem isPushout_symMap :
    IsPushout (CommRingCat.ofHom (algebraMap R (SymmetricAlgebra R M)))
      (CommRingCat.ofHom (algebraMap R (SymmetricAlgebra R N)))
      (CommRingCat.ofHom (symMap (LinearMap.inl R M N)).toRingHom)
      (CommRingCat.ofHom (symMap (LinearMap.inr R M N)).toRingHom) :=
  (CommRingCat.isPushout_tensorProduct R (SymmetricAlgebra R M)
      (SymmetricAlgebra R N)).of_iso (Iso.refl _) (Iso.refl _) (Iso.refl _)
    (NormalSheafPicard.symProdEquiv R M N).symm.toRingEquiv.toCommRingCatIso
    (by simp) (by simp)
    (by
      ext s
      change (NormalSheafPicard.symProdEquiv R M N).symm
        ((Algebra.TensorProduct.includeLeft : SymmetricAlgebra R M →ₐ[R]
          SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N) s) =
        symMap (LinearMap.inl R M N) s
      exact symProdEquiv_symm_includeLeft R M N s)
    (by
      ext t
      change (NormalSheafPicard.symProdEquiv R M N).symm
        (Algebra.TensorProduct.includeRight t) = symMap (LinearMap.inr R M N) t
      exact symProdEquiv_symm_includeRight R M N t)

/-- **`C(M × N) = C(M) ×_{Spec R} C(N)`.**  The vector-bundle-like cone of a product module is
the fibre product of the two cones over the base, with projections induced by `LinearMap.inl`
and `LinearMap.inr`. -/
theorem isPullback_symProd :
    IsPullback
      (Spec.map (CommRingCat.ofHom (symMap (LinearMap.inl R M N)).toRingHom))
      (Spec.map (CommRingCat.ofHom (symMap (LinearMap.inr R M N)).toRingHom))
      (projection R (SymmetricAlgebra R M)) (projection R (SymmetricAlgebra R N)) :=
  AlgebraicGeometry.isPullback_SpecMap_of_isPushout _ _ _ _ (isPushout_symMap R M N)

end GradedCone

/-! ## Products and fibre products of cone actions -/

namespace ConeQuotient

open GradedCone

section ActionProducts

variable {R S S' F F' : Type u} [CommRing R] [CommRing S] [Algebra R S]
  [CommRing S'] [Algebra R S'] [AddCommGroup F] [Module R F] [AddCommGroup F'] [Module R F']
variable {B : Type u} [CommRing B] [Algebra R B]

/-- The universal map out of `S ⊗ Sym F` precomposed with a product of a cone map and a bundle
map.  This is the computation underlying the compatibility of translations with equivariant
maps, stated without reference to a `ConeAction`. -/
theorem tensorLift_comp_map (φ : S' →ₐ[R] B) (l : F' →ₗ[R] B) (f : S →ₐ[R] S')
    (u : F →ₗ[R] F') :
    (Algebra.TensorProduct.lift φ (SymmetricAlgebra.lift l)
        fun _ _ => Commute.all _ _).comp (Algebra.TensorProduct.map f (symMap u)) =
      Algebra.TensorProduct.lift (φ.comp f) (SymmetricAlgebra.lift (l.comp u))
        fun _ _ => Commute.all _ _ := by
  refine tensor_ext ?_ ?_
  · rw [AlgHom.comp_assoc, Algebra.TensorProduct.map_comp_includeLeft, ← AlgHom.comp_assoc,
      Algebra.TensorProduct.lift_comp_includeLeft,
      Algebra.TensorProduct.lift_comp_includeLeft]
  · rw [AlgHom.comp_assoc, Algebra.TensorProduct.map_comp_includeRight, ← AlgHom.comp_assoc,
      Algebra.TensorProduct.lift_comp_includeRight',
      Algebra.TensorProduct.lift_comp_includeRight', symLift_comp_symMap]

/-- Translations are intertwined by any pair `(f, u)` of a map of coordinate algebras and a map
of bundles satisfying the equivariance equation.  This is `ConeQuotient.translate_comp` stated
for bare coactions, so that it may be used while *constructing* a `ConeAction`. -/
theorem translate_comp_of_intertwine {act : S →ₐ[R] S ⊗[R] SymmetricAlgebra R F}
    {act' : S' →ₐ[R] S' ⊗[R] SymmetricAlgebra R F'} {f : S →ₐ[R] S'} {u : F →ₗ[R] F'}
    (h : (Algebra.TensorProduct.map f (symMap u)).comp act = act'.comp f)
    (x : S' →ₐ[R] B) (l : F' →ₗ[R] B) :
    (translate act' x l).comp f = translate act (x.comp f) (l.comp u) := by
  rw [translate, translate, AlgHom.comp_assoc, ← h, ← AlgHom.comp_assoc, tensorLift_comp_map]

variable (A : ConeAction R S F) (A' : ConeAction R S' F')

/-- The coaction of the product bundle `E × E'` on the product cone `C ×_{Spec R} C'`. -/
noncomputable def prodAct :
    (S ⊗[R] S') →ₐ[R] (S ⊗[R] S') ⊗[R] SymmetricAlgebra R (F × F') :=
  Algebra.TensorProduct.lift
    ((Algebra.TensorProduct.map
        (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S')
        (symMap (LinearMap.inl R F F'))).comp A.act)
    ((Algebra.TensorProduct.map
        (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S')
        (symMap (LinearMap.inr R F F'))).comp A'.act)
    fun _ _ => Commute.all _ _

/-- The product coaction restricted to the first factor. -/
theorem prodAct_comp_includeLeft :
    (prodAct A A').comp (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S') =
      (Algebra.TensorProduct.map
        (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S')
        (symMap (LinearMap.inl R F F'))).comp A.act :=
  Algebra.TensorProduct.lift_comp_includeLeft _ _ _

/-- The product coaction restricted to the second factor. -/
theorem prodAct_comp_includeRight :
    (prodAct A A').comp (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S') =
      (Algebra.TensorProduct.map
        (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S')
        (symMap (LinearMap.inr R F F'))).comp A'.act :=
  Algebra.TensorProduct.lift_comp_includeRight' _ _ _

/-- Translating a point of the product cone and restricting to the first factor is translating
the restricted point by the restricted translation. -/
theorem translate_prodAct_comp_includeLeft (φ : (S ⊗[R] S') →ₐ[R] B)
    (l : (F × F') →ₗ[R] B) :
    (translate (prodAct A A') φ l).comp
        (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S') =
      translate A.act (φ.comp (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S'))
        (l.comp (LinearMap.inl R F F')) :=
  translate_comp_of_intertwine (prodAct_comp_includeLeft A A').symm φ l

/-- Translating a point of the product cone and restricting to the second factor. -/
theorem translate_prodAct_comp_includeRight (φ : (S ⊗[R] S') →ₐ[R] B)
    (l : (F × F') →ₗ[R] B) :
    (translate (prodAct A A') φ l).comp
        (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S') =
      translate A'.act (φ.comp (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S'))
        (l.comp (LinearMap.inr R F F')) :=
  translate_comp_of_intertwine (prodAct_comp_includeRight A A').symm φ l

/-- **The product of two cone actions.**  The vector bundle `E × E' = Spec Sym(F × F')` acts on
the product cone `C ×_{Spec R} C' = Spec (S ⊗[R] S')`, componentwise on points. -/
noncomputable def ConeAction.prod : ConeAction R (S ⊗[R] S') (F × F') where
  coaction := tensorCoaction A.coaction A'.coaction
  isCone := isConeCoaction_tensorCoaction A.isCone A'.isCone
  act := prodAct A A'
  act_zero := by
    intro B _ _ φ
    refine tensor_ext ?_ ?_
    · rw [translate_prodAct_comp_includeLeft, LinearMap.zero_comp, A.act_zero]
    · rw [translate_prodAct_comp_includeRight, LinearMap.zero_comp, A'.act_zero]
  act_add := by
    intro B _ _ φ l l'
    refine tensor_ext ?_ ?_
    · rw [translate_prodAct_comp_includeLeft, translate_prodAct_comp_includeLeft,
        translate_prodAct_comp_includeLeft, A.act_add, LinearMap.add_comp]
    · rw [translate_prodAct_comp_includeRight, translate_prodAct_comp_includeRight,
        translate_prodAct_comp_includeRight, A'.act_add, LinearMap.add_comp]
  conic :=
    isConeHom_tensorLift
      (A.conic.comp (isConeHom_tensorMap (isConeHom_includeLeft A.coaction A'.coaction)
        (isConeHom_symMap R F (F × F') (LinearMap.inl R F F'))))
      (A'.conic.comp (isConeHom_tensorMap (isConeHom_includeRight A.coaction A'.coaction)
        (isConeHom_symMap R F' (F × F') (LinearMap.inr R F F'))))

@[simp]
theorem ConeAction.prod_act : (A.prod A').act = prodAct A A' := rfl

@[simp]
theorem ConeAction.prod_coaction :
    (A.prod A').coaction = tensorCoaction A.coaction A'.coaction := rfl

/-- The first projection of a product of cones with actions is equivariant. -/
theorem isEquivariant_prod_left :
    IsEquivariant A (A.prod A') (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S')
      (LinearMap.inl R F F') :=
  (prodAct_comp_includeLeft A A').symm

/-- The second projection of a product of cones with actions is equivariant. -/
theorem isEquivariant_prod_right :
    IsEquivariant A' (A.prod A') (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S')
      (LinearMap.inr R F F') :=
  (prodAct_comp_includeRight A A').symm

end ActionProducts

section ActionPullback

variable {R S F F' : Type u} [CommRing R] [CommRing S] [Algebra R S]
  [AddCommGroup F] [Module R F] [AddCommGroup F'] [Module R F']
variable {B : Type u} [CommRing B] [Algebra R B]

/-- Translating for the coaction pulled back along a morphism of vector bundles. -/
theorem translate_pullbackAct (A : ConeAction R S F) (u : F →ₗ[R] F') (x : S →ₐ[R] B)
    (l : F' →ₗ[R] B) :
    translate ((Algebra.TensorProduct.map (AlgHom.id R S) (symMap u)).comp A.act) x l =
      translate A.act x (l.comp u) := by
  rw [translate, ← AlgHom.comp_assoc, tensorLift_comp_map, AlgHom.comp_id]
  rfl

/-- **Restriction of a cone action along a morphism of vector bundles.**  A linear map
`u : F →ₗ[R] F'` is the same thing as a morphism of vector bundles `E' = Spec Sym F' → E`, and
an action of `E` on the cone `C` restricts to an action of `E'`. -/
noncomputable def ConeAction.pullback (A : ConeAction R S F) (u : F →ₗ[R] F') :
    ConeAction R S F' where
  coaction := A.coaction
  isCone := A.isCone
  act := (Algebra.TensorProduct.map (AlgHom.id R S) (symMap u)).comp A.act
  act_zero := by
    intro B _ _ φ
    rw [translate_pullbackAct, LinearMap.zero_comp, A.act_zero]
  act_add := by
    intro B _ _ φ l l'
    rw [translate_pullbackAct, translate_pullbackAct, translate_pullbackAct, A.act_add,
      LinearMap.add_comp]
  conic :=
    A.conic.comp (isConeHom_tensorMap (isConeHom_id A.coaction)
      (isConeHom_symMap R F F' u))

@[simp]
theorem ConeAction.pullback_act (A : ConeAction R S F) (u : F →ₗ[R] F') :
    (A.pullback u).act = (Algebra.TensorProduct.map (AlgHom.id R S) (symMap u)).comp A.act :=
  rfl

@[simp]
theorem ConeAction.pullback_coaction (A : ConeAction R S F) (u : F →ₗ[R] F') :
    (A.pullback u).coaction = A.coaction := rfl

end ActionPullback

section ActionDiagonal

variable {R S S' F : Type u} [CommRing R] [CommRing S] [Algebra R S]
  [CommRing S'] [Algebra R S'] [AddCommGroup F] [Module R F]
variable (A : ConeAction R S F) (A' : ConeAction R S' F)

/-- The addition map `F × F → F`, the bundle map inducing the diagonal of `E`. -/
def diagonalMap : (F × F) →ₗ[R] F :=
  LinearMap.coprod LinearMap.id LinearMap.id

@[simp]
theorem diagonalMap_apply (x : F × F) : diagonalMap (R := R) x = x.1 + x.2 := by
  simp [diagonalMap]

/-- The addition map is a retraction of the first inclusion. -/
theorem diagonalMap_comp_inl :
    (diagonalMap (R := R) (F := F)).comp (LinearMap.inl R F F) = LinearMap.id := by
  refine LinearMap.ext fun m => ?_
  simp

/-- The addition map is a retraction of the second inclusion. -/
theorem diagonalMap_comp_inr :
    (diagonalMap (R := R) (F := F)).comp (LinearMap.inr R F F) = LinearMap.id := by
  refine LinearMap.ext fun m => ?_
  simp

/-- **The diagonal action.**  If the same vector bundle `E = Spec Sym F` acts on two cones `C`
and `C'` over `Spec R`, it acts diagonally on the fibre product `C ×_{Spec R} C'`: on points,
`e · (c, c') = (e · c, e · c')`. -/
noncomputable def ConeAction.diagonal : ConeAction R (S ⊗[R] S') F :=
  (A.prod A').pullback (diagonalMap (R := R) (F := F))

@[simp]
theorem ConeAction.diagonal_coaction :
    (A.diagonal A').coaction = tensorCoaction A.coaction A'.coaction := rfl

/-- The first projection of the diagonal action is equivariant for the identity of `E`. -/
theorem isEquivariant_diagonal_left :
    IsEquivariant A (A.diagonal A')
      (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S') LinearMap.id := by
  have hcomp : (symMap (diagonalMap (R := R) (F := F))).comp
      (symMap (LinearMap.inl R F F)) = AlgHom.id R (SymmetricAlgebra R F) := by
    rw [← symMap_comp, diagonalMap_comp_inl, symMap_id]
  change (Algebra.TensorProduct.map
      (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S')
      (symMap (LinearMap.id : F →ₗ[R] F))).comp A.act =
    ((Algebra.TensorProduct.map (AlgHom.id R (S ⊗[R] S'))
      (symMap (diagonalMap (R := R) (F := F)))).comp (prodAct A A')).comp
      (Algebra.TensorProduct.includeLeft : S →ₐ[R] S ⊗[R] S')
  rw [AlgHom.comp_assoc, prodAct_comp_includeLeft, ← AlgHom.comp_assoc,
    ← Algebra.TensorProduct.map_comp, hcomp, AlgHom.id_comp, symMap_id]

/-- The second projection of the diagonal action is equivariant for the identity of `E`. -/
theorem isEquivariant_diagonal_right :
    IsEquivariant A' (A.diagonal A')
      (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S') LinearMap.id := by
  have hcomp : (symMap (diagonalMap (R := R) (F := F))).comp
      (symMap (LinearMap.inr R F F)) = AlgHom.id R (SymmetricAlgebra R F) := by
    rw [← symMap_comp, diagonalMap_comp_inr, symMap_id]
  change (Algebra.TensorProduct.map
      (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S')
      (symMap (LinearMap.id : F →ₗ[R] F))).comp A'.act =
    ((Algebra.TensorProduct.map (AlgHom.id R (S ⊗[R] S'))
      (symMap (diagonalMap (R := R) (F := F)))).comp (prodAct A A')).comp
      (Algebra.TensorProduct.includeRight : S' →ₐ[R] S ⊗[R] S')
  rw [AlgHom.comp_assoc, prodAct_comp_includeRight, ← AlgHom.comp_assoc,
    ← Algebra.TensorProduct.map_comp, hcomp, AlgHom.id_comp, symMap_id]

end ActionDiagonal

end ConeQuotient

/-! ## The `R/I`-linear vertex of the affine normal cone -/

namespace GradedCone

section NormalConeVertex

open AffineNormalCone

variable (R : Type u) [CommRing R] (I : Ideal R)

/-- Contracting by `0` extracts the degree-zero coefficient of the coaction. -/
theorem contraction_zero_apply {S : Type*} [CommRing S] [Algebra R S]
    (ψ : S →ₐ[R] Polynomial S) (s : S) : contraction ψ (0 : R) s = (ψ s).coeff 0 := by
  change evalHom (AlgHom.id R S) (algebraMap R S (0 : R)) (ψ s) = _
  rw [map_zero]
  change Polynomial.eval₂ ((AlgHom.id R S) : S →+* S) 0 (ψ s) = _
  rw [Polynomial.eval₂_at_zero]
  rfl

/-- Scaling the Rees algebra by `0` retains only the constant coefficient. -/
theorem reesScaleAux_zero (p : Polynomial R) :
    reesScaleAux R (0 : R) p = Polynomial.C (p.coeff 0) := by
  refine Polynomial.ext fun n => ?_
  rw [reesScaleAux_coeff, Polynomial.coeff_C]
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · simp
  · rw [zero_pow hn.ne', zero_mul, if_neg hn.ne']

/-- Scaling a Rees element by `0` gives the constant Rees element with the same constant term. -/
theorem reesScale_zero (q : reesAlgebra I) :
    reesScale R I (0 : R) q = algebraMap R (reesAlgebra I) ((q : Polynomial R).coeff 0) := by
  refine Subtype.ext ?_
  rw [reesScale_coe, reesScaleAux_zero]
  rfl

/-- Scaling the associated graded ring by `0` is the vertex: it is the degree-zero augmentation
followed by the structural map of the `R/I`-algebra `gr_I(R)`. -/
theorem associatedGradedScale_zero (x : associatedGradedRing R I) :
    associatedGradedScale R I (0 : R) x =
      algebraMap (R ⧸ I) (associatedGradedRing R I) (associatedGradedAugmentation R I x) := by
  obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [associatedGradedScale_mk, reesScale_zero, associatedGradedAugmentation_mk]
  rfl

/-- **The vertex of the affine normal cone is `R/I`-linear.**  The degree-zero augmentation
`gr_I(R) → R/I` is a map of `R/I`-algebras, because it is a retraction of the structural map
`R/I → gr_I(R)`. -/
noncomputable def normalConeVertexHom :
    associatedGradedRing R I →ₐ[R ⧸ I] R ⧸ I where
  toRingHom := associatedGradedAugmentation R I
  commutes' r := associatedGradedAugmentation_base R I r

@[simp]
theorem normalConeVertexHom_apply (x : associatedGradedRing R I) :
    normalConeVertexHom R I x = associatedGradedAugmentation R I x := rfl

/-- The contraction coaction of the affine normal cone, as a map of `R/I`-algebras: the cone
`Spec gr_I(R)` lives over its own degree-zero part `Spec (R/I)`, not merely over `Spec R`. -/
noncomputable def normalConeCoactionQuot :
    associatedGradedRing R I →ₐ[R ⧸ I] Polynomial (associatedGradedRing R I) where
  toRingHom := (normalConeCoaction R I : associatedGradedRing R I →+* _)
  commutes' r := by
    obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
    have hr : algebraMap (R ⧸ I) (associatedGradedRing R I) (Ideal.Quotient.mk I r) =
        algebraMap R (associatedGradedRing R I) r :=
      (IsScalarTower.algebraMap_apply R (R ⧸ I) (associatedGradedRing R I) r).symm
    have hp : algebraMap (R ⧸ I) (Polynomial (associatedGradedRing R I))
          (Ideal.Quotient.mk I r) =
        algebraMap R (Polynomial (associatedGradedRing R I)) r := by
      rw [Polynomial.algebraMap_apply, Polynomial.algebraMap_apply, hr]
    change normalConeCoaction R I _ = _
    rw [hr, hp, AlgHom.commutes]

@[simp]
theorem normalConeCoactionQuot_apply (x : associatedGradedRing R I) :
    normalConeCoactionQuot R I x = normalConeCoaction R I x := rfl

/-- The `R/I`-linear coaction of the affine normal cone still satisfies the cone axioms. -/
theorem isConeCoaction_normalConeCoactionQuot :
    IsConeCoaction (normalConeCoactionQuot R I) where
  counit := AlgHom.ext fun x =>
    AlgHom.congr_fun (isConeCoaction_normalConeCoaction R I).counit x
  coassoc := AlgHom.ext fun x =>
    AlgHom.congr_fun (isConeCoaction_normalConeCoaction R I).coassoc x

/-- **The degree-zero augmentation is the vertex of the affine normal cone over `Spec (R/I)`.**
Contracting `Spec gr_I(R)` by `0` is the projection to `Spec (R/I)` followed by the vertex
section, in the sense of `GradedCone.IsConeVertex` over the base `R/I`. -/
theorem isConeVertex_normalConeCoactionQuot :
    IsConeVertex (normalConeCoactionQuot R I) (normalConeVertexHom R I) := by
  refine AlgHom.ext fun x => ?_
  have h0 : contraction (normalConeCoactionQuot R I) (0 : R ⧸ I) x =
      contraction (normalConeCoaction R I) (0 : R) x := by
    rw [contraction_zero_apply, contraction_zero_apply]
    rfl
  rw [h0, contraction_normalConeCoaction, associatedGradedScale_zero]
  rfl

end NormalConeVertex

end GradedCone

end GromovWitten.AlgebraicGeometry
