/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GromovWitten Contributors
-/

import GromovWitten.Algebra.QuasiRegular
import GromovWitten.AlgebraicGeometry.Cones.Affine

/-!
# The affine normal cone of a regular immersion

Let `I ⊆ R` be an ideal generated by a finite regular sequence.  This file proves that the
canonical graded algebra map

`Sym_{R/I}(I/I²) ⟶ gr_I(R)`

of `GromovWitten.AlgebraicGeometry.AffineNormalCone.normalSheafCoordinateMap` is injective, hence
(together with the already available surjectivity) an isomorphism, and deduces that the canonical
closed immersion of the affine normal cone into the affine normal sheaf is an isomorphism.

The commutative-algebra input is `GromovWitten.Algebra.isQuasiregular_of_isWeaklyRegular`.
-/

open CategoryTheory AlgebraicGeometry MvPolynomial

namespace GromovWitten.AlgebraicGeometry

universe u

namespace AffineNormalCone

/-- Input data for the regular-immersion comparison: a finite family of elements of `R` which is
a regular sequence in Mathlib's sense and which generates `I`.

This structure records only the input geometry.  None of the conclusions of this file (injectivity
of the canonical map, the algebra isomorphism, the scheme isomorphism) appear as fields. -/
structure RegularGenerators (R : Type u) [CommRing R] (I : Ideal R) where
  /-- The number of generators. -/
  length : ℕ
  /-- The generators themselves. -/
  gen : Fin length → R
  /-- They form a weakly regular sequence in the sense of `RingTheory.Sequence.IsWeaklyRegular`. -/
  isWeaklyRegular : RingTheory.Sequence.IsWeaklyRegular R (List.ofFn gen)
  /-- They generate `I`. -/
  span_eq : Ideal.span (Set.range gen) = I

namespace RegularGenerators

variable {R : Type u} [CommRing R] {I : Ideal R} (x : RegularGenerators R I)

theorem gen_mem (i : Fin x.length) : x.gen i ∈ I := by
  have h : x.gen i ∈ Ideal.span (Set.range x.gen) := Ideal.subset_span ⟨i, rfl⟩
  rwa [x.span_eq] at h

/-- A generator, viewed as an element of the ideal `I`. -/
def genMem (i : Fin x.length) : I := ⟨x.gen i, x.gen_mem i⟩

/-- The conormal class of a generator. -/
noncomputable def conormalGen (i : Fin x.length) : I.Cotangent :=
  I.toCotangent (x.genMem i)

/-- The canonical map from the polynomial ring onto the normal-sheaf coordinate ring, sending
`X i` to the conormal class of the `i`-th generator. -/
noncomputable def symLift :
    MvPolynomial (Fin x.length) R →+* normalSheafCoordinateRing R I :=
  MvPolynomial.eval₂Hom
    ((algebraMap (R ⧸ I) (normalSheafCoordinateRing R I)).comp (Ideal.Quotient.mk I))
    (fun i => SymmetricAlgebra.ι (R ⧸ I) I.Cotangent (x.conormalGen i))

@[simp]
theorem symLift_C (r : R) :
    x.symLift (C r) =
      algebraMap (R ⧸ I) (normalSheafCoordinateRing R I) (Ideal.Quotient.mk I r) :=
  eval₂Hom_C _ _ r

@[simp]
theorem symLift_X (i : Fin x.length) :
    x.symLift (X i) = SymmetricAlgebra.ι (R ⧸ I) I.Cotangent (x.conormalGen i) :=
  eval₂Hom_X' _ _ i

/-- The canonical map from the polynomial ring into the Rees algebra, sending `X i` to the
degree-one Rees element `gen i * t`. -/
noncomputable def reesLift :
    MvPolynomial (Fin x.length) R →+* reesAlgebra I :=
  MvPolynomial.eval₂Hom (algebraMap R (reesAlgebra I))
    (fun i => degreeOneRees R I (x.genMem i))

@[simp]
theorem reesLift_C (r : R) : x.reesLift (C r) = algebraMap R (reesAlgebra I) r :=
  eval₂Hom_C _ _ r

@[simp]
theorem reesLift_X (i : Fin x.length) :
    x.reesLift (X i) = degreeOneRees R I (x.genMem i) :=
  eval₂Hom_X' _ _ i

/-- The same substitution, but landing in the ambient polynomial ring. -/
noncomputable def polyLift : MvPolynomial (Fin x.length) R →+* Polynomial R :=
  MvPolynomial.eval₂Hom Polynomial.C
    (fun i => Polynomial.C (x.gen i) * Polynomial.X)

@[simp]
theorem polyLift_C (r : R) : x.polyLift (C r) = Polynomial.C r := eval₂Hom_C _ _ r

@[simp]
theorem polyLift_X (i : Fin x.length) :
    x.polyLift (X i) = Polynomial.C (x.gen i) * Polynomial.X := eval₂Hom_X' _ _ i

/-- The Rees lift is the polynomial lift, read inside `R[X]`. -/
theorem coe_reesLift (p : MvPolynomial (Fin x.length) R) :
    ((x.reesLift p : reesAlgebra I) : Polynomial R) = x.polyLift p := by
  have hcomp : ((reesAlgebra I).val.toRingHom).comp x.reesLift = x.polyLift := by
    refine MvPolynomial.ringHom_ext (fun r => ?_) (fun i => ?_)
    · rw [RingHom.comp_apply, reesLift_C, polyLift_C]
      rfl
    · rw [RingHom.comp_apply, reesLift_X, polyLift_X]
      change (Polynomial.monomial 1 (x.gen i) : Polynomial R) = _
      rw [← Polynomial.C_mul_X_pow_eq_monomial, pow_one]
  exact congrArg (fun f => f p) hcomp

/-- The canonical map onto the normal-sheaf coordinate ring is surjective: the symmetric algebra
is generated over `R/I` by the conormal classes of the chosen generators. -/
theorem symLift_surjective : Function.Surjective x.symLift := by
  intro z
  induction z using SymmetricAlgebra.induction with
  | algebraMap r =>
      obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
      exact ⟨C r, x.symLift_C r⟩
  | ι m =>
      obtain ⟨y, rfl⟩ := I.toCotangent_surjective m
      have hy : (y : R) ∈ Ideal.span (Set.range x.gen) := by
        rw [x.span_eq]
        exact y.2
      obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun R).1 hy
      refine ⟨∑ i, C (c i) * X i, ?_⟩
      have hy' : y = ∑ i, c i • x.genMem i := by
        apply Subtype.ext
        simpa [genMem] using hc.symm
      have hcot : I.toCotangent y
          = ∑ i, (algebraMap R (R ⧸ I) (c i)) • x.conormalGen i := by
        rw [hy', map_sum]
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [map_smul, algebraMap_smul]
        rfl
      rw [map_sum, hcot, map_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [map_mul, symLift_C, symLift_X, ← Algebra.smul_def, map_smul,
        Ideal.Quotient.algebraMap_eq]
  | mul a b ha hb =>
      obtain ⟨p, rfl⟩ := ha
      obtain ⟨q, rfl⟩ := hb
      exact ⟨p * q, map_mul _ _ _⟩
  | add a b ha hb =>
      obtain ⟨p, rfl⟩ := ha
      obtain ⟨q, rfl⟩ := hb
      exact ⟨p + q, map_add _ _ _⟩

/-- The canonical normal-sheaf coordinate map, precomposed with the polynomial presentation of
the symmetric algebra, is the Rees substitution followed by the quotient map. -/
theorem normalSheafCoordinateMap_comp_symLift :
    (normalSheafCoordinateMap R I).comp x.symLift
      = (Ideal.Quotient.mk (Ideal.map (algebraMap R (reesAlgebra I)) I)).comp x.reesLift := by
  refine MvPolynomial.ringHom_ext (fun r => ?_) (fun i => ?_)
  · rw [RingHom.comp_apply, RingHom.comp_apply, symLift_C, reesLift_C,
      normalSheafCoordinateMap_base]
    rfl
  · rw [RingHom.comp_apply, RingHom.comp_apply, symLift_X, reesLift_X,
      normalSheafCoordinateMap_ι, conormalGen, conormalToAssociatedGraded_toCotangent]

/-- The `m`-th coefficient of the Rees substitution of `p` is the value at the generators of the
degree-`m` homogeneous component of `p`. -/
theorem polyLift_coeff (p : MvPolynomial (Fin x.length) R) (m : ℕ) :
    (x.polyLift p).coeff m = MvPolynomial.eval x.gen (homogeneousComponent m p) := by
  classical
  induction p using MvPolynomial.induction_on' with
  | monomial β c =>
      have hprod : (β.prod fun i k => (Polynomial.C (x.gen i) * Polynomial.X) ^ k)
          = Polynomial.C (β.prod fun i k => x.gen i ^ k) * Polynomial.X ^ β.degree := by
        rw [Finsupp.prod, Finsupp.prod, Finsupp.degree_apply, map_prod,
          ← Finset.prod_pow_eq_pow_sum, ← Finset.prod_mul_distrib]
        refine Finset.prod_congr rfl fun i _ => ?_
        rw [mul_pow, ← Polynomial.C_pow]
      have hL : x.polyLift (monomial β c)
          = Polynomial.C (c * β.prod fun i k => x.gen i ^ k) * Polynomial.X ^ β.degree := by
        change MvPolynomial.eval₂ Polynomial.C _ (monomial β c) = _
        rw [MvPolynomial.eval₂_monomial, hprod, Polynomial.C_mul, mul_assoc]
      rw [hL, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
        homogeneousComponent_of_mem
          ((mem_homogeneousSubmodule _ _).2 (isHomogeneous_monomial c rfl))]
      split_ifs with h
      · simp [eval_monomial]
      · simp
  | add p q hp hq =>
      rw [map_add, Polynomial.coeff_add, hp, hq, map_add, map_add]

/-- A polynomial all of whose coefficients lie in `I` maps to zero in the symmetric algebra. -/
theorem symLift_eq_zero_of_coeff_mem {p : MvPolynomial (Fin x.length) R}
    (hp : ∀ β, p.coeff β ∈ I) : x.symLift p = 0 := by
  classical
  conv_lhs => rw [p.as_sum]
  rw [map_sum]
  refine Finset.sum_eq_zero fun β _ => ?_
  rw [MvPolynomial.monomial_eq, map_mul, symLift_C,
    Ideal.Quotient.eq_zero_iff_mem.2 (hp β), map_zero, zero_mul]

/-- Mathlib's regular sequence hypothesis yields quasi-regularity of the generators. -/
theorem isQuasiregular : GromovWitten.Algebra.IsQuasiregular x.gen :=
  GromovWitten.Algebra.isQuasiregular_of_isWeaklyRegular x.length x.gen x.isWeaklyRegular

/-- **The key step.**  A polynomial killed by the canonical normal-sheaf coordinate map has all
of its coefficients in `I`.  This is where regularity of the sequence is used. -/
theorem coeff_mem_of_symLift_eq_zero {p : MvPolynomial (Fin x.length) R}
    (hp : normalSheafCoordinateMap R I (x.symLift p) = 0) (β) : p.coeff β ∈ I := by
  have happ := congrArg (fun f => f p) (normalSheafCoordinateMap_comp_symLift x)
  simp only [RingHom.comp_apply] at happ
  have hmem : x.reesLift p ∈ Ideal.map (algebraMap R (reesAlgebra I)) I := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, ← happ]
    exact hp
  have hQ : ∀ (d : ℕ) (F : MvPolynomial (Fin x.length) R), F.IsHomogeneous d →
      MvPolynomial.eval x.gen F ∈ I ^ (d + 1) → ∀ α, F.coeff α ∈ I := by
    intro d F hF hval α
    have hc := x.isQuasiregular d F hF (by rw [x.span_eq]; exact hval) α
    rwa [x.span_eq] at hc
  have hcomp : ∀ m, MvPolynomial.eval x.gen (homogeneousComponent m p) ∈ I ^ (m + 1) := by
    intro m
    rw [← polyLift_coeff, ← coe_reesLift]
    exact coeff_mem_pow_succ_of_mem_map_rees R I hmem m
  have hcoeff := hQ β.degree (homogeneousComponent β.degree p)
    (homogeneousComponent_isHomogeneous _ _) (hcomp _) β
  rwa [coeff_homogeneousComponent, if_pos rfl] at hcoeff

include x in
/-- **The canonical map `Sym_{R/I}(I/I²) → gr_I(R)` is injective when `I` is generated by a
finite regular sequence.** -/
theorem normalSheafCoordinateMap_injective :
    Function.Injective (normalSheafCoordinateMap R I) := by
  intro a b hab
  obtain ⟨p, rfl⟩ := x.symLift_surjective a
  obtain ⟨q, rfl⟩ := x.symLift_surjective b
  have hzero : normalSheafCoordinateMap R I (x.symLift (p - q)) = 0 := by
    rw [map_sub, map_sub, hab, sub_self]
  have hsub := x.symLift_eq_zero_of_coeff_mem (x.coeff_mem_of_symLift_eq_zero hzero)
  rw [map_sub, sub_eq_zero] at hsub
  exact hsub

include x in
/-- Together with the already available surjectivity, the canonical map is bijective. -/
theorem normalSheafCoordinateMap_bijective :
    Function.Bijective (normalSheafCoordinateMap R I) :=
  ⟨x.normalSheafCoordinateMap_injective, normalSheafCoordinateMap_surjective R I⟩

include x in
/-- **The canonical isomorphism `Sym_{R/I}(I/I²) ≃ gr_I(R)`** for an ideal generated by a finite
regular sequence.  Its forward map is the canonical map itself. -/
noncomputable def normalSheafCoordinateEquiv :
    normalSheafCoordinateRing R I ≃+* associatedGradedRing R I :=
  RingEquiv.ofBijective _ x.normalSheafCoordinateMap_bijective

@[simp]
theorem normalSheafCoordinateEquiv_apply (z : normalSheafCoordinateRing R I) :
    x.normalSheafCoordinateEquiv z = normalSheafCoordinateMap R I z := rfl

/-- The forward ring homomorphism of the isomorphism is literally the canonical map. -/
theorem normalSheafCoordinateEquiv_toRingHom :
    (x.normalSheafCoordinateEquiv : normalSheafCoordinateRing R I →+* associatedGradedRing R I)
      = normalSheafCoordinateMap R I := rfl

include x in
/-- **The affine normal cone of a regular immersion is its normal sheaf.**  The isomorphism is
induced by the canonical coordinate comparison, not chosen independently. -/
noncomputable def schemeIsoNormalSheaf : scheme R I ≅ normalSheaf R I :=
  Scheme.Spec.mapIso x.normalSheafCoordinateEquiv.toCommRingCatIso.op

/-- The isomorphism above has the existing canonical closed immersion as its forward map. -/
@[simp]
theorem schemeIsoNormalSheaf_hom :
    x.schemeIsoNormalSheaf.hom = coneToNormalSheaf R I := by
  change _root_.AlgebraicGeometry.Spec.map _ = _root_.AlgebraicGeometry.Spec.map _
  rw [_root_.AlgebraicGeometry.Spec.map_inj]
  rfl

include x in
/-- Consequently the canonical closed immersion of the normal cone into the normal sheaf is an
isomorphism. -/
theorem coneToNormalSheaf_isIso : IsIso (coneToNormalSheaf R I) := by
  rw [← x.schemeIsoNormalSheaf_hom]
  infer_instance

/-- The comparison respects the degree-one conormal generators. -/
@[simp]
theorem normalSheafCoordinateEquiv_ι (m : I.Cotangent) :
    x.normalSheafCoordinateEquiv (SymmetricAlgebra.ι (R ⧸ I) I.Cotangent m)
      = conormalToAssociatedGraded R I m :=
  normalSheafCoordinateMap_ι R I m

/-- The comparison respects the degree-zero structure maps; it is an isomorphism of
`R/I`-algebras. -/
theorem normalSheafCoordinateEquiv_base (r : R ⧸ I) :
    x.normalSheafCoordinateEquiv (algebraMap (R ⧸ I) (normalSheafCoordinateRing R I) r)
      = algebraMap (R ⧸ I) (associatedGradedRing R I) r :=
  normalSheafCoordinateMap_base R I r

include x in
/-- The comparison packaged as an isomorphism of `R/I`-algebras.  Its underlying ring
homomorphism is the existing canonical map. -/
noncomputable def normalSheafCoordinateAlgEquiv :
    normalSheafCoordinateRing R I ≃ₐ[R ⧸ I] associatedGradedRing R I :=
  AlgEquiv.ofRingEquiv (f := x.normalSheafCoordinateEquiv) x.normalSheafCoordinateEquiv_base

@[simp]
theorem normalSheafCoordinateAlgEquiv_apply (z : normalSheafCoordinateRing R I) :
    x.normalSheafCoordinateAlgEquiv z = normalSheafCoordinateMap R I z := rfl

/-- The forward ring homomorphism of the algebra isomorphism is the existing canonical map. -/
theorem normalSheafCoordinateAlgEquiv_toRingHom :
    (x.normalSheafCoordinateAlgEquiv :
        normalSheafCoordinateRing R I →+* associatedGradedRing R I) =
      normalSheafCoordinateMap R I := rfl

/-- The comparison respects the vertex augmentations. -/
theorem normalSheafCoordinateEquiv_augmentation (z : normalSheafCoordinateRing R I) :
    associatedGradedAugmentation R I (x.normalSheafCoordinateEquiv z)
      = AffineCone.augmentation (R ⧸ I) I.Cotangent z :=
  associatedGradedAugmentation_normalSheafCoordinateMap R I z

/-- The comparison respects the `𝔸¹`-scaling actions on the two cones. -/
theorem normalSheafCoordinateEquiv_contraction (r : R)
    (z : normalSheafCoordinateRing R I) :
    x.normalSheafCoordinateEquiv
        (AffineCone.contraction (R ⧸ I) I.Cotangent (Ideal.Quotient.mk I r) z)
      = associatedGradedScale R I r (x.normalSheafCoordinateEquiv z) :=
  normalSheafCoordinateMap_contraction R I r z

include x in
/-- Geometrically, the comparison is an isomorphism of cones over `Spec (R/I)`. -/
theorem schemeIsoNormalSheaf_hom_comp_projection :
    x.schemeIsoNormalSheaf.hom ≫ AffineCone.projection (R ⧸ I) I.Cotangent =
      projection R I := by
  rw [x.schemeIsoNormalSheaf_hom]
  exact coneToNormalSheaf_comp_projection R I

include x in
/-- The comparison identifies the two vertices. -/
theorem vertex_comp_schemeIsoNormalSheaf_hom :
    vertex R I ≫ x.schemeIsoNormalSheaf.hom = AffineCone.vertex (R ⧸ I) I.Cotangent := by
  rw [x.schemeIsoNormalSheaf_hom]
  exact vertex_comp_coneToNormalSheaf R I

/-- A single non-zerodivisor is a regular generating sequence for the principal ideal it
generates. -/
def principal {R : Type u} [CommRing R] (a : R) (ha : ∀ b : R, a * b = 0 → b = 0)
    {I : Ideal R} (hI : Ideal.span {a} = I) : RegularGenerators R I where
  length := 1
  gen := fun _ => a
  isWeaklyRegular := by
    have hlist : List.ofFn (fun _ : Fin 1 => a) = [a] := by simp
    rw [hlist, RingTheory.Sequence.isWeaklyRegular_singleton_iff]
    intro u v huv
    have h' : a * u = a * v := by simpa using huv
    exact sub_eq_zero.mp (ha _ (by linear_combination h'))
  span_eq := by
    rw [← hI]
    exact congrArg Ideal.span Set.range_const

end RegularGenerators

section Principal

variable {R : Type u} [CommRing R]

/-- **Length-one acceptance case.**  For a principal ideal generated by a non-zerodivisor the
canonical map `Sym(I/I²) → gr_I(R)` is injective. -/
theorem normalSheafCoordinateMap_injective_of_principal (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    Function.Injective (normalSheafCoordinateMap R (Ideal.span {a})) :=
  (RegularGenerators.principal a ha rfl).normalSheafCoordinateMap_injective

/-- The normal cone of a principal non-zerodivisor immersion is its normal sheaf. -/
noncomputable def principalSchemeIsoNormalSheaf (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    scheme R (Ideal.span {a}) ≅ normalSheaf R (Ideal.span {a}) :=
  (RegularGenerators.principal a ha rfl).schemeIsoNormalSheaf

@[simp]
theorem principalSchemeIsoNormalSheaf_hom (a : R) (ha : ∀ b : R, a * b = 0 → b = 0) :
    (principalSchemeIsoNormalSheaf a ha).hom = coneToNormalSheaf R (Ideal.span {a}) :=
  RegularGenerators.schemeIsoNormalSheaf_hom (RegularGenerators.principal a ha rfl)

/-- Hence the canonical closed immersion is an isomorphism in the principal case. -/
theorem coneToNormalSheaf_isIso_of_principal (a : R)
    (ha : ∀ b : R, a * b = 0 → b = 0) :
    IsIso (coneToNormalSheaf R (Ideal.span {a})) :=
  RegularGenerators.coneToNormalSheaf_isIso (RegularGenerators.principal a ha rfl)

end Principal

section AffineLine

variable (k : Type u) [Field k]

/-- The coordinate `t` is a non-zerodivisor in `k[t]`. -/
theorem polynomialX_nonZeroDivisor (b : Polynomial k) (hb : Polynomial.X * b = 0) : b = 0 := by
  rcases mul_eq_zero.1 hb with h | h
  · exact absurd h Polynomial.X_ne_zero
  · exact h

/-- **Concrete acceptance case.**  For the origin `(t) ⊆ k[t]` of the affine line the canonical
map is injective. -/
theorem affineLineOrigin_normalSheafCoordinateMap_injective :
    Function.Injective
      (normalSheafCoordinateMap (Polynomial k) (Ideal.span {Polynomial.X})) :=
  normalSheafCoordinateMap_injective_of_principal _ (polynomialX_nonZeroDivisor k)

/-- The normal cone of the origin of the affine line is its normal bundle. -/
noncomputable def affineLineOriginIso :
    scheme (Polynomial k) (Ideal.span {Polynomial.X}) ≅
      normalSheaf (Polynomial k) (Ideal.span {Polynomial.X}) :=
  principalSchemeIsoNormalSheaf _ (polynomialX_nonZeroDivisor k)

@[simp]
theorem affineLineOriginIso_hom :
    (affineLineOriginIso k).hom =
      coneToNormalSheaf (Polynomial k) (Ideal.span {Polynomial.X}) :=
  principalSchemeIsoNormalSheaf_hom _ _

end AffineLine

section AffinePlane

/-!
### A genuine length-two example

The origin of the affine plane, presented as `k[s][t]` with the regular sequence `t, s`.  This
exercises the inductive step of the regular-sequence theorem with a nonzero ideal of previous
generators.
-/

variable (k : Type u) [Field k]

/-- The coordinate ring `k[s][t]` of the affine plane. -/
abbrev PlaneRing := Polynomial (Polynomial k)

/-- The two coordinates `t` and `s` of the affine plane. -/
noncomputable def planeGen : Fin 2 → PlaneRing k :=
  ![Polynomial.X, Polynomial.C Polynomial.X]

theorem range_planeGen :
    Set.range (planeGen k) =
      {(Polynomial.X : PlaneRing k), Polynomial.C Polynomial.X} := by
  ext f
  simp only [planeGen, Set.mem_range, Fin.exists_fin_two, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val_fin_one, Set.mem_insert_iff, Set.mem_singleton_iff]
  tauto

/-- The ideal of the origin of the affine plane. -/
noncomputable def planeIdeal : Ideal (PlaneRing k) := Ideal.span (Set.range (planeGen k))

/-- Dividing out the first coordinate `t` identifies `k[s][t]/(t)` with `k[s]`. -/
noncomputable def planeQuotXEquiv :
    (PlaneRing k ⧸ Ideal.span {(Polynomial.X : PlaneRing k)}) ≃+* Polynomial k :=
  (Ideal.quotEquivOfEq (by simp :
      (Ideal.span {(Polynomial.X : PlaneRing k)}) =
        Ideal.span {Polynomial.X - Polynomial.C (0 : Polynomial k)})).trans
    (Polynomial.quotientSpanXSubCAlgEquiv (0 : Polynomial k)).toRingEquiv

@[simp]
theorem planeQuotXEquiv_mk (p : PlaneRing k) :
    planeQuotXEquiv k (Ideal.Quotient.mk _ p) = p.eval 0 := by
  rfl

/-- The second coordinate `s` is a non-zerodivisor modulo the first. -/
theorem planeC_X_regular (h : PlaneRing k)
    (hh : Polynomial.C Polynomial.X * h ∈ Ideal.span {(Polynomial.X : PlaneRing k)}) :
    h ∈ Ideal.span {(Polynomial.X : PlaneRing k)} := by
  rw [← Ideal.Quotient.eq_zero_iff_mem] at hh ⊢
  apply (planeQuotXEquiv k).injective
  rw [map_zero]
  have he : planeQuotXEquiv k
        (Ideal.Quotient.mk (Ideal.span {(Polynomial.X : PlaneRing k)})
          (Polynomial.C Polynomial.X)) *
      planeQuotXEquiv k
        (Ideal.Quotient.mk (Ideal.span {(Polynomial.X : PlaneRing k)}) h) = 0 := by
    rw [← map_mul, ← map_mul, hh, map_zero]
  rw [planeQuotXEquiv_mk, planeQuotXEquiv_mk, Polynomial.eval_C] at he
  rcases mul_eq_zero.1 he with h1 | h2
  · exact absurd h1 Polynomial.X_ne_zero
  · rw [planeQuotXEquiv_mk]
    exact h2

open scoped Pointwise in
/-- Pointwise scaling of the top submodule of a ring by `r` is the principal ideal `(r)`. -/
theorem smul_top_eq_span_singleton {A : Type*} [CommRing A] (r : A) :
    (r • (⊤ : Submodule A A)) = (Ideal.span {r} : Ideal A) := by
  rw [← Submodule.ideal_span_singleton_smul, Ideal.smul_eq_mul, Ideal.mul_top]

/-- A non-zerodivisor criterion on `QuotSMulTop` phrased with principal ideals. -/
theorem isSMulRegular_quotSMulTop {A : Type*} [CommRing A] (r r' : A)
    (h : ∀ a : A, r' * a ∈ Ideal.span {r} → a ∈ Ideal.span {r}) :
    IsSMulRegular (QuotSMulTop r A) r' := by
  intro u v huv
  obtain ⟨u, rfl⟩ := Submodule.Quotient.mk_surjective _ u
  obtain ⟨v, rfl⟩ := Submodule.Quotient.mk_surjective _ v
  have huv' : (Submodule.Quotient.mk (r' • u) : QuotSMulTop r A) =
      Submodule.Quotient.mk (r' • v) := huv
  rw [Submodule.Quotient.eq, smul_top_eq_span_singleton] at huv'
  rw [Submodule.Quotient.eq, smul_top_eq_span_singleton]
  refine h _ ?_
  have hsub : r' * (u - v) = r' • u - r' • v := by
    simp [smul_eq_mul, mul_sub]
  rw [hsub]
  exact huv'

/-- The two coordinates form a regular sequence in `k[s][t]`. -/
theorem planeGen_isWeaklyRegular :
    RingTheory.Sequence.IsWeaklyRegular (PlaneRing k) (List.ofFn (planeGen k)) := by
  have hl : List.ofFn (planeGen k) =
      [(Polynomial.X : PlaneRing k), Polynomial.C Polynomial.X] := by
    simp [planeGen, List.ofFn_succ]
  rw [hl, RingTheory.Sequence.isWeaklyRegular_cons_iff,
    RingTheory.Sequence.isWeaklyRegular_singleton_iff]
  refine ⟨?_, ?_⟩
  · intro f g hfg
    have h : (Polynomial.X : PlaneRing k) * f = Polynomial.X * g := hfg
    exact mul_left_cancel₀ Polynomial.X_ne_zero h
  · exact isSMulRegular_quotSMulTop _ _ (planeC_X_regular k)

/-- The origin of the affine plane, with its chosen regular generating sequence. -/
noncomputable def planeRegularGenerators : RegularGenerators (PlaneRing k) (planeIdeal k) where
  length := 2
  gen := planeGen k
  isWeaklyRegular := planeGen_isWeaklyRegular k
  span_eq := rfl

/-- **Length-two acceptance case.**  At the origin of the affine plane the canonical map is
injective. -/
theorem planeOrigin_normalSheafCoordinateMap_injective :
    Function.Injective (normalSheafCoordinateMap (PlaneRing k) (planeIdeal k)) :=
  (planeRegularGenerators k).normalSheafCoordinateMap_injective

/-- The normal cone of the origin of the affine plane is its normal bundle. -/
noncomputable def planeOriginIso :
    scheme (PlaneRing k) (planeIdeal k) ≅ normalSheaf (PlaneRing k) (planeIdeal k) :=
  (planeRegularGenerators k).schemeIsoNormalSheaf

@[simp]
theorem planeOriginIso_hom :
    (planeOriginIso k).hom = coneToNormalSheaf (PlaneRing k) (planeIdeal k) :=
  RegularGenerators.schemeIsoNormalSheaf_hom (planeRegularGenerators k)

end AffinePlane

end AffineNormalCone

end GromovWitten.AlgebraicGeometry
