/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.Cones.SmoothAmbientEtaleAction
import GromovWitten.AlgebraicGeometry.Cones.NormalConeAction
import Mathlib.RingTheory.Etale.Kaehler

/-!
# The tangent action on the normal cone of an étale chart, as a cone action

`Cones/SmoothAmbientEtale.lean` and `Cones/SmoothAmbientEtaleAction.lean` construct, for a
formally étale algebra `R` over the polynomial ambient ring `P = Amb A σ = A[x_σ]` and an
*arbitrary* ideal `J ⊆ R`, the tangent coaction

`EtaleAmbient.coactionEtale : gr_J(R) →+* gr_J(R)[z_σ]`

together with its counit law, coassociativity and the action axioms on points.  That coaction
lives in the coordinates `z_σ` of the chart, so it is not yet a `ConeQuotient.ConeAction`.
This file supplies the missing dictionary and packages the result.

## The bridge

The restricted tangent bundle is `T = Spec Sym_{R/J}(F)` with `F = (R/J) ⊗_R Ω[R⁄A]`, the bundle
of `AffineNormalCone.normalSheafTangentAction`.  For a formally étale chart the canonical map
`R ⊗_P Ω[P⁄A] → Ω[R⁄A]` is an isomorphism
(`KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale`), so `Ω[R⁄A]` is free on the
differentials `d(x_i)` of the coordinates (`EtaleConeAction.kaehlerBasis`) and `F` is free on
`EtaleConeAction.tangentBasis`.  Hence

* `EtaleConeAction.symEquiv : Sym_{R/J}(F) ≃ₐ[R/J] (R/J)[z_σ]`, and
* `EtaleConeAction.tensorEquiv : gr_J(R) ⊗_{R/J} Sym_{R/J}(F) ≃ₐ[R/J] gr_J(R)[z_σ]`.

## Main results

* `EtaleConeAction.kaehlerEquiv : R ⊗_P Ω[P⁄A] ≃ₗ[R] Ω[R⁄A]`, `EtaleConeAction.kaehlerBasis`
  and `EtaleConeAction.tangentEquiv : (R/J) ⊗_R Ω[R⁄A] ≃ₗ[R/J] (R/J)^σ`: `Ω[R⁄A]` is free on the
  coordinate differentials; hence `EtaleConeAction.derivation_ext`, two `A`-derivations of `R`
  agree as soon as they agree on the coordinates.
* `EtaleConeAction.taylorDer_eq_kaehlerDer`: the linear part of the first-order Taylor expansion
  of the chart is the universal derivation, whence
  `EtaleConeAction.tangentToPoly_conormalMap`: the conormal map `J/J² → (R/J) ⊗ Ω[R⁄A]` is the
  derivative appearing in `EtaleAmbient.coactionEtale_degreeOneRaw`.
* `EtaleConeAction.etaleNormalConeAction : ConeQuotient.ConeAction (R/J) (gr_J(R)) F`: the
  tangent action on the affine normal cone of an étale chart, with all four `ConeAction`
  axioms proved.  The `𝔸¹`-contraction is `GradedCone.normalConeCoactionQuot`, the unit and
  associativity laws are `EtaleAmbient.translatePointEtale_zero` and `_add`, and the
  `𝔾ₘ`-equivariance is `EtaleConeAction.conic_act`.
* `EtaleConeAction.isEquivariant_nsToGrAlg`: **Vistoli's lemma** in cone-action form for an
  étale chart — the closed immersion `C_{U/M} ↪ N_{U/M}` is equivariant.
* `EtaleConeAction.etaleNormalConeObstructionCone`: the obstruction cone
  `[C_{U/M}/T_M|_U](B) ⟶ h¹/h⁰(Eᵛ)(B)` attached to an obstruction theory on the conormal
  complex, fully faithful and injective on isomorphism classes.
* `EtaleConeAction.etaleNormalConeAction_eq`: for `R = P` the étale cone action is the
  polynomial-model cone action of `Cones/NormalConeAction.lean`.

Nothing is assumed beyond the standing setting: `R` is a formally étale `Amb A σ`-algebra which
is an `A`-algebra compatibly (`[Algebra A R]`, `[IsScalarTower A (Amb A σ) R]`), and `J ⊆ R` is
an arbitrary ideal.
-/

open CategoryTheory TensorProduct

namespace GromovWitten.AlgebraicGeometry

namespace EtaleConeAction

universe u

noncomputable section

open MvPolynomial ConeTranslation ConeRefinement AffineNormalCone ConeQuotient GradedCone
  EtaleAmbient

/-! ## Kähler differentials of a formally étale chart -/

section Kaehler

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R]

/-- **The Kähler differentials of a formally étale chart are a base change.**  For
`R` formally étale over `P = Amb A σ` the canonical map `R ⊗_P Ω[P⁄A] → Ω[R⁄A]` is an
isomorphism of `R`-modules. -/
def kaehlerEquiv : R ⊗[Amb A σ] Ω[Amb A σ⁄A] ≃ₗ[R] Ω[R⁄A] :=
  KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale A (Amb A σ) R

/-- **The differentials of a formally étale chart are freely generated by the coordinates.**
For a formally étale algebra `R` over the polynomial ring `P = A[x_σ]` the canonical map
`R ⊗_P Ω[P⁄A] → Ω[R⁄A]` is an isomorphism, and `Ω[P⁄A]` is free on the `dx_i`. -/
def kaehlerBasis : Module.Basis σ R Ω[R⁄A] :=
  ((KaehlerDifferential.mvPolynomialBasis A σ).baseChange R).map
    (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale A (Amb A σ) R)

@[simp]
theorem kaehlerBasis_apply (i : σ) :
    kaehlerBasis A σ R i =
      KaehlerDifferential.D A R (algebraMap (Amb A σ) R (MvPolynomial.X i)) := by
  rw [kaehlerBasis, Module.Basis.map_apply, Module.Basis.baseChange_apply,
    KaehlerDifferential.mvPolynomialBasis_apply,
    KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale_apply,
    KaehlerDifferential.mapBaseChange_tmul, one_smul, KaehlerDifferential.map_D]

variable {A σ R}

/-- **Extensionality for derivations of a formally étale chart**: two `A`-derivations of `R`
agree as soon as they agree on the images of the coordinates `x_i`, because `Ω[R⁄A]` is
generated by their differentials. -/
theorem derivation_ext {M : Type u} [AddCommGroup M] [Module A M] [Module R M]
    [IsScalarTower A R M] (D₁ D₂ : Derivation A R M)
    (h : ∀ i : σ, D₁ (algebraMap (Amb A σ) R (MvPolynomial.X i)) =
      D₂ (algebraMap (Amb A σ) R (MvPolynomial.X i))) : D₁ = D₂ := by
  have hlift : D₁.liftKaehlerDifferential = D₂.liftKaehlerDifferential := by
    refine Module.Basis.ext (kaehlerBasis A σ R) fun i ↦ ?_
    rw [kaehlerBasis_apply, Derivation.liftKaehlerDifferential_comp_D,
      Derivation.liftKaehlerDifferential_comp_D]
    exact h i
  rw [← D₁.liftKaehlerDifferential_comp, ← D₂.liftKaehlerDifferential_comp, hlift]

end Kaehler

/-! ## The restricted tangent bundle of an étale chart -/

section Tangent

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R] (J : Ideal R)

/-- The module of the restricted tangent bundle `T_M|_U = (R/J) ⊗_R Ω[R⁄A]`.  This is literally
the bundle of `AffineNormalCone.normalSheafTangentAction`. -/
abbrev Tangent : Type u := (R ⧸ J) ⊗[R] Ω[R⁄A]

/-- **The coordinate differentials form a basis of the restricted tangent bundle** of a formally
étale chart: freeness of `Ω[R⁄A]` is preserved by base change to `R/J`. -/
def tangentBasis : Module.Basis σ (R ⧸ J) (Tangent A R J) :=
  (kaehlerBasis A σ R).baseChange (R ⧸ J)

@[simp]
theorem tangentBasis_apply (i : σ) :
    tangentBasis A σ R J i =
      (1 : R ⧸ J) ⊗ₜ[R] KaehlerDifferential.D A R
        (algebraMap (Amb A σ) R (MvPolynomial.X i)) := by
  rw [tangentBasis, Module.Basis.baseChange_apply, kaehlerBasis_apply]

/-- **The restricted tangent bundle of an étale chart is free of rank `σ`**: the coordinate
differentials trivialise `(R/J) ⊗_R Ω[R⁄A] ≅ (R/J)^σ`. -/
def tangentEquiv : Tangent A R J ≃ₗ[R ⧸ J] (σ →₀ R ⧸ J) :=
  (tangentBasis A σ R J).repr

/-- **The symmetric algebra of the restricted tangent bundle is a polynomial algebra.** -/
def symEquiv :
    SymmetricAlgebra (R ⧸ J) (Tangent A R J) ≃ₐ[R ⧸ J] MvPolynomial σ (R ⧸ J) :=
  SymmetricAlgebra.equivMvPolynomial (tangentBasis A σ R J)

@[simp]
theorem symEquiv_ι (i : σ) :
    symEquiv A σ R J
        (SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J) (tangentBasis A σ R J i)) =
      MvPolynomial.X i :=
  SymmetricAlgebra.equivMvPolynomial_ι_apply _ i

/-- **The coordinate algebra of `C_{U/M} ×_U T_M|_U` is `gr_J(R)[z_σ]`.** -/
def tensorEquiv :
    associatedGradedRing R J ⊗[R ⧸ J] SymmetricAlgebra (R ⧸ J) (Tangent A R J) ≃ₐ[R ⧸ J]
      MvPolynomial σ (associatedGradedRing R J) :=
  (Algebra.TensorProduct.congr
      (AlgEquiv.refl : associatedGradedRing R J ≃ₐ[R ⧸ J] associatedGradedRing R J)
      (symEquiv A σ R J)).trans
    (AlgEquiv.restrictScalars (R ⧸ J)
      (MvPolynomial.algebraTensorAlgEquiv (σ := σ) (R ⧸ J) (associatedGradedRing R J)))

/-- The comparison is the composite of the two bridging isomorphisms. -/
theorem tensorEquiv_apply
    (x : associatedGradedRing R J ⊗[R ⧸ J] SymmetricAlgebra (R ⧸ J) (Tangent A R J)) :
    tensorEquiv A σ R J x =
      MvPolynomial.algebraTensorAlgEquiv (σ := σ) (R ⧸ J) (associatedGradedRing R J)
        (Algebra.TensorProduct.congr
          (AlgEquiv.refl : associatedGradedRing R J ≃ₐ[R ⧸ J] associatedGradedRing R J)
          (symEquiv A σ R J) x) :=
  rfl

/-- The comparison isomorphism on a pure tensor. -/
theorem tensorEquiv_tmul (g : associatedGradedRing R J)
    (s : SymmetricAlgebra (R ⧸ J) (Tangent A R J)) :
    tensorEquiv A σ R J (g ⊗ₜ[R ⧸ J] s) =
      g • MvPolynomial.map (algebraMap (R ⧸ J) (associatedGradedRing R J))
        (symEquiv A σ R J s) := by
  rw [tensorEquiv_apply, Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul,
    MvPolynomial.algebraTensorAlgEquiv_tmul]
  rfl

@[simp]
theorem tensorEquiv_left (g : associatedGradedRing R J) :
    tensorEquiv A σ R J (g ⊗ₜ[R ⧸ J] 1) = MvPolynomial.C g := by
  rw [tensorEquiv_tmul, map_one, map_one, MvPolynomial.smul_eq_C_mul, mul_one]

@[simp]
theorem tensorEquiv_right (i : σ) :
    tensorEquiv A σ R J ((1 : associatedGradedRing R J) ⊗ₜ[R ⧸ J]
        SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J) (tangentBasis A σ R J i)) =
      MvPolynomial.X i := by
  rw [tensorEquiv_tmul, symEquiv_ι, MvPolynomial.map_X, one_smul]

end Tangent

/-! ## The coaction over the base `R/J` -/

section Coaction

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R] (J : Ideal R)

/-- The tangent coaction of `Cones/SmoothAmbientEtale.lean`, read as a map of `R/J`-algebras.
The underlying ring map is unchanged; only the base of the algebra structure is the degree-zero
part `R/J` of `gr_J(R)` rather than the chart `R`. -/
def coactionQ :
    associatedGradedRing R J →ₐ[R ⧸ J] MvPolynomial σ (associatedGradedRing R J) where
  toRingHom := coactionEtale A σ R J
  commutes' r := by
    obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
    have hr : algebraMap (R ⧸ J) (associatedGradedRing R J) (Ideal.Quotient.mk J r) =
        algebraMap R (associatedGradedRing R J) r :=
      (IsScalarTower.algebraMap_apply R (R ⧸ J) (associatedGradedRing R J) r).symm
    have hp : algebraMap (R ⧸ J) (MvPolynomial σ (associatedGradedRing R J))
          (Ideal.Quotient.mk J r) =
        MvPolynomial.C (algebraMap R (associatedGradedRing R J) r) := by
      rw [MvPolynomial.algebraMap_apply, hr]
    change coactionEtale A σ R J _ = _
    rw [hr, hp, coactionEtale_algebraMap]

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
@[simp]
theorem coactionQ_apply (z : associatedGradedRing R J) :
    coactionQ A σ R J z = coactionEtale A σ R J z := rfl

/-- **The tangent translation coaction of the affine normal cone of an étale chart.**  Under the
identification `gr_J(R) ⊗_{R/J} Sym(F) ≅ gr_J(R)[z_σ]` it is `EtaleAmbient.coactionEtale`. -/
def act :
    associatedGradedRing R J →ₐ[R ⧸ J]
      associatedGradedRing R J ⊗[R ⧸ J] SymmetricAlgebra (R ⧸ J) (Tangent A R J) :=
  ((tensorEquiv A σ R J).symm : _ →ₐ[R ⧸ J] _).comp (coactionQ A σ R J)

@[simp]
theorem tensorEquiv_act (z : associatedGradedRing R J) :
    tensorEquiv A σ R J (act A σ R J z) = coactionEtale A σ R J z := by
  change tensorEquiv A σ R J ((tensorEquiv A σ R J).symm (coactionQ A σ R J z)) = _
  rw [AlgEquiv.apply_symm_apply, coactionQ_apply]

/-! ### The action on points -/

section Points

variable {B : Type u} [CommRing B] [Algebra (R ⧸ J) B]

/-- Composing the universal map out of `gr_J(R) ⊗ Sym(F)` with the comparison isomorphism gives
evaluation of the tangent coordinates at the vector `i ↦ l (dx_i)`. -/
theorem liftComp_tensorEquiv_symm (φ : associatedGradedRing R J →ₐ[R ⧸ J] B)
    (l : Tangent A R J →ₗ[R ⧸ J] B) :
    (Algebra.TensorProduct.lift φ (SymmetricAlgebra.lift l)
        (fun _ _ ↦ Commute.all _ _)).toRingHom.comp
        ((tensorEquiv A σ R J).symm : _ →ₐ[R ⧸ J] _).toRingHom =
      MvPolynomial.eval₂Hom (φ : associatedGradedRing R J →+* B)
        (fun i ↦ l (tangentBasis A σ R J i)) := by
  refine MvPolynomial.ringHom_ext (fun g ↦ ?_) fun i ↦ ?_
  · have hg : (tensorEquiv A σ R J).symm (MvPolynomial.C g) = g ⊗ₜ[R ⧸ J] 1 := by
      rw [AlgEquiv.symm_apply_eq, tensorEquiv_left]
    change Algebra.TensorProduct.lift φ (SymmetricAlgebra.lift l)
      (fun _ _ ↦ Commute.all _ _) ((tensorEquiv A σ R J).symm (MvPolynomial.C g)) = _
    rw [hg, Algebra.TensorProduct.lift_tmul, map_one, mul_one, MvPolynomial.eval₂Hom_C]
    rfl
  · have hi : (tensorEquiv A σ R J).symm (MvPolynomial.X i) =
        (1 : associatedGradedRing R J) ⊗ₜ[R ⧸ J]
          SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J) (tangentBasis A σ R J i) := by
      rw [AlgEquiv.symm_apply_eq, tensorEquiv_right]
    change Algebra.TensorProduct.lift φ (SymmetricAlgebra.lift l)
      (fun _ _ ↦ Commute.all _ _) ((tensorEquiv A σ R J).symm (MvPolynomial.X i)) = _
    rw [hi, Algebra.TensorProduct.lift_tmul, map_one, one_mul,
      SymmetricAlgebra.lift_ι_apply, MvPolynomial.eval₂Hom_X']

/-- **The action of the tangent bundle on the `B`-points of the affine normal cone of an étale
chart** is the translation `EtaleAmbient.translatePointEtale`. -/
theorem translate_act (φ : associatedGradedRing R J →ₐ[R ⧸ J] B)
    (l : Tangent A R J →ₗ[R ⧸ J] B) (z : associatedGradedRing R J) :
    translate (act A σ R J) φ l z =
      translatePointEtale A σ R J (φ : associatedGradedRing R J →+* B)
        (fun i ↦ l (tangentBasis A σ R J i)) z :=
  RingHom.congr_fun (liftComp_tensorEquiv_symm A σ R J φ l) (coactionEtale A σ R J z)

/-- The action on points, as an equality of ring homomorphisms. -/
theorem translate_act_ringHom (φ : associatedGradedRing R J →ₐ[R ⧸ J] B)
    (l : Tangent A R J →ₗ[R ⧸ J] B) :
    ((translate (act A σ R J) φ l : associatedGradedRing R J →ₐ[R ⧸ J] B) :
        associatedGradedRing R J →+* B) =
      translatePointEtale A σ R J (φ : associatedGradedRing R J →+* B)
        fun i ↦ l (tangentBasis A σ R J i) :=
  RingHom.ext (translate_act A σ R J φ l)

/-- Translating by the zero tangent vector does nothing. -/
theorem act_zero (φ : associatedGradedRing R J →ₐ[R ⧸ J] B) :
    translate (act A σ R J) φ 0 = φ := by
  refine AlgHom.ext fun z ↦ ?_
  rw [translate_act]
  have hv : (fun i ↦ (0 : Tangent A R J →ₗ[R ⧸ J] B) (tangentBasis A σ R J i)) = 0 := by
    funext i
    rfl
  rw [hv, translatePointEtale_zero]
  rfl

/-- Translating twice is translating by the sum. -/
theorem act_add (φ : associatedGradedRing R J →ₐ[R ⧸ J] B)
    (l l' : Tangent A R J →ₗ[R ⧸ J] B) :
    translate (act A σ R J) (translate (act A σ R J) φ l) l' =
      translate (act A σ R J) φ (l + l') := by
  refine AlgHom.ext fun z ↦ ?_
  rw [translate_act, translate_act_ringHom, translatePointEtale_add]
  have hv : (fun i ↦ (l + l') (tangentBasis A σ R J i)) =
      (fun i ↦ l (tangentBasis A σ R J i)) + fun i ↦ l' (tangentBasis A σ R J i) := by
    funext i
    rfl
  rw [translate_act, hv]

end Points

end Coaction

/-! ## The linear part of the first-order Taylor expansion -/

section Linear

open Pointwise

variable {S : Type u} [CommRing S] {τ : Type u}

/-- **A product of two polynomials without constant term has no linear part.** -/
theorem homogeneousComponent_one_mul_eq_zero {p q : MvPolynomial τ S}
    (hp : constantCoeff p = 0) (hq : constantCoeff q = 0) :
    homogeneousComponent 1 (p * q) = 0 := by
  classical
  refine homogeneousComponent_eq_zero' _ _ fun d hd ↦ ?_
  obtain ⟨a, ha, b, hb, rfl⟩ := Finset.mem_add.mp (support_mul p q hd)
  have ha0 : a ≠ 0 := by
    intro h
    rw [h, mem_support_iff, ← constantCoeff_eq, hp] at ha
    exact ha rfl
  have hb0 : b ≠ 0 := by
    intro h
    rw [h, mem_support_iff, ← constantCoeff_eq, hq] at hb
    exact hb rfl
  have ha1 : a.degree ≠ 0 := fun h ↦ ha0 ((Finsupp.degree_eq_zero_iff a).mp h)
  have hb1 : b.degree ≠ 0 := fun h ↦ hb0 ((Finsupp.degree_eq_zero_iff b).mp h)
  have hadd : (a + b).degree = a.degree + b.degree := map_add Finsupp.degree a b
  omega

/-- **The linear part of a product.**  In `S[τ]` the degree-one component of `p q` is
`p(0)·(linear part of q) + q(0)·(linear part of p)`: this is the Leibniz rule for the
derivative at the origin. -/
theorem homogeneousComponent_one_mul (p q : MvPolynomial τ S) :
    homogeneousComponent 1 (p * q) =
      C (constantCoeff p) * homogeneousComponent 1 q +
        C (constantCoeff q) * homogeneousComponent 1 p := by
  have hp0 : constantCoeff (p - C (constantCoeff p)) = 0 := by
    rw [map_sub, constantCoeff_C, sub_self]
  have hq0 : constantCoeff (q - C (constantCoeff q)) = 0 := by
    rw [map_sub, constantCoeff_C, sub_self]
  have hlp : homogeneousComponent 1 (p - C (constantCoeff p)) = homogeneousComponent 1 p := by
    rw [map_sub, ConeRefinement.homogeneousComponent_one_C, sub_zero]
  have hlq : homogeneousComponent 1 (q - C (constantCoeff q)) = homogeneousComponent 1 q := by
    rw [map_sub, ConeRefinement.homogeneousComponent_one_C, sub_zero]
  have hsplit : p * q = C (constantCoeff p) * C (constantCoeff q) +
      (C (constantCoeff p) * (q - C (constantCoeff q)) +
        (C (constantCoeff q) * (p - C (constantCoeff p)) +
          (p - C (constantCoeff p)) * (q - C (constantCoeff q)))) := by
    ring
  rw [hsplit, map_add, map_add, map_add, ← C_mul, ConeRefinement.homogeneousComponent_one_C,
    homogeneousComponent_C_mul, homogeneousComponent_C_mul,
    homogeneousComponent_one_mul_eq_zero hp0 hq0, hlp, hlq, zero_add, add_zero]

end Linear


/-! ## The Taylor derivation of an étale chart -/

section TaylorDer

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R]

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- **The square of the augmentation ideal has no linear part.**  This is what makes the linear
part of a lift of the first-order Taylor expansion well defined. -/
theorem homogeneousComponent_one_eq_zero_of_mem_sq {y : MvPolynomial σ R}
    (hy : y ∈ epsIdeal σ R ^ 2) : homogeneousComponent 1 y = 0 := by
  rw [pow_two] at hy
  refine Submodule.mul_induction_on hy (fun a ha b hb ↦ ?_) fun p q hp hq ↦ ?_
  · exact homogeneousComponent_one_mul_eq_zero (mem_epsIdeal_iff.mp ha) (mem_epsIdeal_iff.mp hb)
  · rw [map_add, hp, hq, add_zero]

/-- A chosen lift to `R[ε_σ]` of the first-order Taylor expansion of `x ∈ R`. -/
def taylorLift1 (x : R) : MvPolynomial σ R :=
  (shiftMk_surjective A σ R 1 (taylor A σ R 1 x)).choose

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The chosen lift does lift the first-order Taylor expansion. -/
theorem shiftMk_taylorLift1 (x : R) :
    shiftMk A σ R 1 (taylorLift1 A σ R x) = taylor A σ R 1 x :=
  (shiftMk_surjective A σ R 1 (taylor A σ R 1 x)).choose_spec

/-- **The linear part of the first-order Taylor expansion of `x`**: the "derivative" of `x` in
the coordinates of the chart, with values in `R[ε_σ]`. -/
def linPart (x : R) : MvPolynomial σ R := homogeneousComponent 1 (taylorLift1 A σ R x)

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The linear part is computed by *any* lift of the first-order Taylor expansion. -/
theorem linPart_eq (x : R) (y : MvPolynomial σ R) (hy : shiftMk A σ R 1 y = taylor A σ R 1 x) :
    homogeneousComponent 1 y = linPart A σ R x := by
  have h : shiftMk A σ R 1 (y - taylorLift1 A σ R x) = 0 := by
    rw [map_sub, hy, shiftMk_taylorLift1, sub_self]
  have hmem := (shiftMk_eq_zero_iff A σ R 1).mp h
  have hz := homogeneousComponent_one_eq_zero_of_mem_sq σ R hmem
  rw [map_sub, sub_eq_zero] at hz
  exact hz

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The constant term of the chosen lift is the element itself. -/
theorem constantCoeff_taylorLift1 (x : R) : constantCoeff (taylorLift1 A σ R x) = x :=
  constantCoeff_of_taylor A σ R 1 x _ (shiftMk_taylorLift1 A σ R x)

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The linear part is additive. -/
theorem linPart_add (x x' : R) :
    linPart A σ R (x + x') = linPart A σ R x + linPart A σ R x' := by
  rw [← linPart_eq A σ R (x + x') (taylorLift1 A σ R x + taylorLift1 A σ R x')
      (by rw [map_add, map_add, shiftMk_taylorLift1, shiftMk_taylorLift1]), map_add]
  rfl

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- **Leibniz rule for the linear part.** -/
theorem linPart_mul (x x' : R) :
    linPart A σ R (x * x') = C x * linPart A σ R x' + C x' * linPart A σ R x := by
  rw [← linPart_eq A σ R (x * x') (taylorLift1 A σ R x * taylorLift1 A σ R x')
      (by rw [map_mul, map_mul, shiftMk_taylorLift1, shiftMk_taylorLift1]),
    homogeneousComponent_one_mul, constantCoeff_taylorLift1, constantCoeff_taylorLift1]
  rfl

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The linear part of the image of an ambient polynomial is the linear part of its shift. -/
theorem linPart_algebraMap (p : Amb A σ) :
    linPart A σ R (algebraMap (Amb A σ) R p) = homogeneousComponent 1 (shiftHom A σ R p) := by
  refine (linPart_eq A σ R _ (shiftHom A σ R p) ?_).symm
  rw [(taylor A σ R 1).commutes p, algebraMap_shift_eq]

/-- Constants have no linear part. -/
theorem linPart_algebraMap_base (a : A) : linPart A σ R (algebraMap A R a) = 0 := by
  rw [IsScalarTower.algebraMap_apply A (Amb A σ) R, MvPolynomial.algebraMap_eq,
    linPart_algebraMap, shiftHom_C, ConeRefinement.homogeneousComponent_one_C]

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- **The linear part of a coordinate is the corresponding tangent coordinate.** -/
theorem linPart_X (i : σ) :
    linPart A σ R (algebraMap (Amb A σ) R (MvPolynomial.X i)) = MvPolynomial.X i := by
  rw [linPart_algebraMap, shiftHom_X, map_add, ConeRefinement.homogeneousComponent_one_C,
    ConeRefinement.homogeneousComponent_one_X, zero_add]

variable (J : Ideal R)

omit [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [IsScalarTower A (Amb A σ) R] in
/-- The `R`-module structure on `gr_J(R)[z_σ]` is multiplication by a constant. -/
theorem smul_poly (x : R) (m : MvPolynomial σ (associatedGradedRing R J)) :
    x • m = MvPolynomial.C (algebraMap R (associatedGradedRing R J) x) * m := by
  rw [Algebra.smul_def, MvPolynomial.algebraMap_apply]

omit [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [IsScalarTower A (Amb A σ) R] in
/-- The `A`-module structure on `gr_J(R)[z_σ]` factors through `R`. -/
theorem smul_poly_base (a : A) (m : MvPolynomial σ (associatedGradedRing R J)) :
    a • m =
      MvPolynomial.C (algebraMap R (associatedGradedRing R J) (algebraMap A R a)) * m := by
  rw [Algebra.smul_def, MvPolynomial.algebraMap_apply,
    ← IsScalarTower.algebraMap_apply A R (associatedGradedRing R J)]

/-- The linear part of the first-order Taylor expansion, with coefficients in `gr_J(R)`. -/
def grLinPart (x : R) : MvPolynomial σ (associatedGradedRing R J) :=
  MvPolynomial.map (algebraMap R (associatedGradedRing R J)) (linPart A σ R x)

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The graded linear part is additive. -/
theorem grLinPart_add (x x' : R) :
    grLinPart A σ R J (x + x') = grLinPart A σ R J x + grLinPart A σ R J x' := by
  rw [grLinPart, linPart_add, map_add]
  rfl

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- **Leibniz rule for the graded linear part.** -/
theorem grLinPart_mul (x x' : R) :
    grLinPart A σ R J (x * x') =
      MvPolynomial.C (algebraMap R (associatedGradedRing R J) x) * grLinPart A σ R J x' +
        MvPolynomial.C (algebraMap R (associatedGradedRing R J) x') * grLinPart A σ R J x := by
  rw [grLinPart, linPart_mul, map_add, map_mul, map_mul, MvPolynomial.map_C, MvPolynomial.map_C]
  rfl

/-- Constants have no graded linear part. -/
theorem grLinPart_algebraMap_base (a : A) : grLinPart A σ R J (algebraMap A R a) = 0 := by
  rw [grLinPart, linPart_algebraMap_base, map_zero]

/-- The graded linear part of `1` vanishes. -/
theorem grLinPart_one : grLinPart A σ R J 1 = 0 := by
  have h := grLinPart_algebraMap_base A σ R J 1
  rwa [map_one] at h

/-- The graded linear part is `A`-linear. -/
theorem grLinPart_smul (a : A) (x : R) :
    grLinPart A σ R J (a • x) = a • grLinPart A σ R J x := by
  rw [Algebra.smul_def a x, grLinPart_mul, grLinPart_algebraMap_base, mul_zero, add_zero,
    smul_poly_base]

/-- **The Taylor derivation of an étale chart**, with values in `gr_J(R)[z_σ]`: it sends `x` to
the linear part `Σ_i [∂_i x]·z_i` of its first-order Taylor expansion. -/
def taylorDer : Derivation A R (MvPolynomial σ (associatedGradedRing R J)) where
  toFun := grLinPart A σ R J
  map_add' := grLinPart_add A σ R J
  map_smul' a x := grLinPart_smul A σ R J a x
  map_one_eq_zero' := grLinPart_one A σ R J
  leibniz' x x' := by
    change grLinPart A σ R J (x * x') = x • grLinPart A σ R J x' + x' • grLinPart A σ R J x
    rw [grLinPart_mul, smul_poly, smul_poly]

@[simp]
theorem taylorDer_apply (x : R) : taylorDer A σ R J x = grLinPart A σ R J x := rfl

end TaylorDer

/-! ## The conormal map is the Taylor derivative -/

section Conormal

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R] (J : Ideal R)

/-- The `R/J`-linear map from the restricted tangent bundle to `gr_J(R)[z_σ]` sending a tangent
vector to the corresponding linear form in the `z`-coordinates. -/
def tangentToPoly : Tangent A R J →ₗ[R ⧸ J] MvPolynomial σ (associatedGradedRing R J) :=
  (MvPolynomial.mapAlgHom
    (Algebra.ofId (R ⧸ J) (associatedGradedRing R J))).toLinearMap.comp
      ((symEquiv A σ R J).toLinearMap.comp (SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J)))

/-- The linear form attached to a tangent vector, unfolded. -/
theorem tangentToPoly_apply (v : Tangent A R J) :
    tangentToPoly A σ R J v =
      MvPolynomial.map (algebraMap (R ⧸ J) (associatedGradedRing R J))
        (symEquiv A σ R J (SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J) v)) :=
  rfl

@[simp]
theorem tangentToPoly_basis (i : σ) :
    tangentToPoly A σ R J (tangentBasis A σ R J i) = MvPolynomial.X i := by
  rw [tangentToPoly_apply, symEquiv_ι, MvPolynomial.map_X]

/-- The universal derivation of the chart, composed with the tangent comparison. -/
def kaehlerDer : Derivation A R (MvPolynomial σ (associatedGradedRing R J)) :=
  (((tangentToPoly A σ R J).restrictScalars R).comp
    (TensorProduct.mk R (R ⧸ J) Ω[R⁄A] 1)).compDer (KaehlerDifferential.D A R)

/-- **The Taylor derivation of an étale chart is the universal derivation.**  Both are
`A`-derivations of `R` with values in `gr_J(R)[z_σ]` sending the coordinate `x_i` to `z_i`, and
`Ω[R⁄A]` is generated by the `d(x_i)`, so they agree. -/
theorem taylorDer_eq_kaehlerDer : taylorDer A σ R J = kaehlerDer A σ R J := by
  refine derivation_ext (σ := σ) _ _ fun i ↦ ?_
  rw [taylorDer_apply, grLinPart, linPart_X, MvPolynomial.map_X]
  change _ = tangentToPoly A σ R J ((1 : R ⧸ J) ⊗ₜ[R]
    KaehlerDifferential.D A R (algebraMap (Amb A σ) R (MvPolynomial.X i)))
  rw [← tangentBasis_apply, tangentToPoly_basis]

/-- **The linear part of the Taylor expansion is the image of the universal differential.** -/
theorem grLinPart_eq_tangentToPoly (x : R) :
    grLinPart A σ R J x =
      tangentToPoly A σ R J ((1 : R ⧸ J) ⊗ₜ[R] KaehlerDifferential.D A R x) :=
  Derivation.congr_fun (taylorDer_eq_kaehlerDer A σ R J) x

omit [Algebra A R] [IsScalarTower A (Amb A σ) R] in
/-- The graded linear part is computed by *any* lift of the first-order Taylor expansion; this
identifies it with `EtaleAmbient.grLinearPart`. -/
theorem grLinearPart_eq_grLinPart (x : R) (y : MvPolynomial σ R)
    (hy : shiftMk A σ R 1 y = taylor A σ R 1 x) :
    grLinearPart σ J y = grLinPart A σ R J x := by
  rw [grLinearPart, linPart_eq A σ R x y hy, grLinPart]

/-- **The conormal map of `Cones/DeformationSpaceGeometry.lean` is the Taylor derivative** of the
étale chart. -/
theorem tangentToPoly_conormalMap (x : J) :
    tangentToPoly A σ R J (AffineNormalCone.conormalMap A R J (Ideal.toCotangent J x)) =
      grLinPart A σ R J (x : R) := by
  rw [AffineNormalCone.conormalMap_toCotangent, grLinPart_eq_tangentToPoly]

end Conormal


/-! ## The closed immersion of the normal cone into the normal sheaf -/

section NsToGr

variable (R : Type u) [CommRing R] (J : Ideal R)

/-- The conormal class of `x ∈ J` is its degree-one class in `gr_J(R)`. -/
theorem conormalToAssociatedGraded_toCotangent_eq (x : J) :
    AffineNormalCone.conormalToAssociatedGraded R J (Ideal.toCotangent J x) =
      AffineNormalCone.degreeOneRaw R J x := by
  rw [AffineNormalCone.conormalToAssociatedGraded_toCotangent]
  rfl

/-- The surjection `Sym_{R/J}(J/J²) ↠ gr_J(R)` of coordinate algebras, as a map of
`R/J`-algebras.  On spectra it is the closed immersion `C_{U/M} ↪ N_{U/M}` of the affine normal
cone into the affine normal sheaf. -/
def nsToGrAlg :
    AffineNormalCone.normalSheafCoordinateRing R J →ₐ[R ⧸ J] associatedGradedRing R J where
  toRingHom := AffineNormalCone.normalSheafCoordinateMap R J
  commutes' r := AffineNormalCone.normalSheafCoordinateMap_base R J r

/-- The closed immersion of the normal cone into the normal sheaf is surjective on coordinate
algebras. -/
theorem nsToGrAlg_surjective : Function.Surjective (nsToGrAlg R J) :=
  AffineNormalCone.normalSheafCoordinateMap_surjective R J

@[simp]
theorem nsToGrAlg_ι (m : J.Cotangent) :
    nsToGrAlg R J (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent m) =
      AffineNormalCone.conormalToAssociatedGraded R J m :=
  AffineNormalCone.normalSheafCoordinateMap_ι R J m

/-- **The closed immersion `C_{U/M} ↪ N_{U/M}` is a morphism of cones.**  The conormal classes
are homogeneous of degree one in `gr_J(R)`. -/
theorem isConeHom_nsToGrAlg :
    IsConeHom (symCoaction (R ⧸ J) J.Cotangent)
      (normalConeCoactionQuot R J) (nsToGrAlg R J) := by
  refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m ↦ ?_)
  have hL : Polynomial.mapAlgHom (nsToGrAlg R J)
        (symCoaction (R ⧸ J) J.Cotangent (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent m)) =
      Polynomial.C (nsToGrAlg R J (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent m)) *
        Polynomial.X := by
    rw [symCoaction_ι, map_mul]
    simp
  have hR : normalConeCoactionQuot R J
        (nsToGrAlg R J (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent m)) =
      Polynomial.C (nsToGrAlg R J (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent m)) *
        Polynomial.X := by
    rw [nsToGrAlg_ι]
    have h := GradedCone.mem_homogeneous.1
      (AffineNormalCone.conormal_mem_homogeneous_one R J m)
    rw [pow_one] at h
    exact h
  exact hL.trans hR.symm

end NsToGr

/-! ## Equivariance of the closed immersion `C_{U/M} ↪ N_{U/M}` -/

section Equivariance

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R] (J : Ideal R)

/-- The image of a pure tangent tensor under the comparison isomorphism. -/
@[simp]
theorem tensorEquiv_one_tmul_ι (v : Tangent A R J) :
    tensorEquiv A σ R J ((1 : associatedGradedRing R J) ⊗ₜ[R ⧸ J]
        SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J) v) = tangentToPoly A σ R J v := by
  rw [tensorEquiv_tmul, one_smul, tangentToPoly_apply]

/-- **The tangent coaction on a conormal class of an étale chart.**  It is the sum of the class
itself and the linear form attached to the conormal differential. -/
theorem coactionEtale_conormal (x : J) :
    coactionEtale A σ R J
        (AffineNormalCone.conormalToAssociatedGraded R J (Ideal.toCotangent J x)) =
      MvPolynomial.C
          (AffineNormalCone.conormalToAssociatedGraded R J (Ideal.toCotangent J x)) +
        tangentToPoly A σ R J
          (AffineNormalCone.conormalMap A R J (Ideal.toCotangent J x)) := by
  obtain ⟨y, hy, hmk⟩ := exists_taylor_lift A σ R J 1 (x : R) (by rw [pow_one]; exact x.2)
  rw [pow_one] at hy
  rw [conormalToAssociatedGraded_toCotangent_eq, tangentToPoly_conormalMap,
    ← grLinearPart_eq_grLinPart A σ R J (x : R) y hmk]
  exact coactionEtale_degreeOneRaw A σ R J (x : R) x.2 y hy hmk

-- The comparison `tensorEquiv` is a composite of several algebra equivalences, so unfolding the
-- `AlgHom.comp` applications in the last step exceeds the default recursion depth.
set_option maxRecDepth 8000 in
/-- **Vistoli's lemma in cone-action form, for a formally étale chart.**  The closed immersion of
the affine normal cone into the affine normal sheaf intertwines the translation action of the
restricted tangent bundle on the normal sheaf with the tangent coaction
`EtaleAmbient.coactionEtale` on the normal cone.

Both sides are algebra maps out of `Sym_{R/J}(J/J²)`, so it suffices to compare them on a
conormal generator `[x]`; there the statement is
`EtaleConeAction.coactionEtale_conormal` together with the identification
`EtaleConeAction.tangentToPoly_conormalMap` of the conormal map with the Taylor derivative. -/
theorem map_comp_bundleTranslationCoaction :
    (Algebra.TensorProduct.map (nsToGrAlg R J)
        (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J))).comp
        (bundleTranslationCoaction (AffineNormalCone.conormalMap A R J)) =
      (act A σ R J).comp (nsToGrAlg R J) := by
  have key : ((tensorEquiv A σ R J).toAlgHom.comp
        ((Algebra.TensorProduct.map (nsToGrAlg R J)
          (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J))).comp
          (bundleTranslationCoaction (AffineNormalCone.conormalMap A R J)))) =
      ((tensorEquiv A σ R J).toAlgHom.comp ((act A σ R J).comp (nsToGrAlg R J))) := by
    refine SymmetricAlgebra.algHom_ext (LinearMap.ext fun m ↦ ?_)
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective J m
    have hL : (Algebra.TensorProduct.map (nsToGrAlg R J)
          (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J)))
          (bundleTranslationCoaction (AffineNormalCone.conormalMap A R J)
            (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent (Ideal.toCotangent J x))) =
        nsToGrAlg R J
            (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent (Ideal.toCotangent J x)) ⊗ₜ[R ⧸ J] 1 +
          (1 : associatedGradedRing R J) ⊗ₜ[R ⧸ J]
            SymmetricAlgebra.ι (R ⧸ J) (Tangent A R J)
              (AffineNormalCone.conormalMap A R J (Ideal.toCotangent J x)) := by
      rw [bundleTranslationCoaction_ι, map_add, Algebra.TensorProduct.map_tmul,
        Algebra.TensorProduct.map_tmul]
      simp only [symMap_id, AlgHom.id_apply, map_one]
    have hgoal : tensorEquiv A σ R J ((Algebra.TensorProduct.map (nsToGrAlg R J)
          (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J)))
          (bundleTranslationCoaction (AffineNormalCone.conormalMap A R J)
            (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent (Ideal.toCotangent J x)))) =
        tensorEquiv A σ R J (act A σ R J (nsToGrAlg R J
          (SymmetricAlgebra.ι (R ⧸ J) J.Cotangent (Ideal.toCotangent J x)))) := by
      rw [hL, map_add, tensorEquiv_left, tensorEquiv_one_tmul_ι, tensorEquiv_act, nsToGrAlg_ι,
        coactionEtale_conormal]
    exact hgoal
  exact AlgHom.ext fun s ↦ (tensorEquiv A σ R J).injective (AlgHom.congr_fun key s)

/-- The equivariance of the closed immersion, in the form required by
`ConeQuotient.IsEquivariant`, once the cone action has been packaged. -/
theorem isEquivariant_nsToGrAlg_aux :
    (Algebra.TensorProduct.map (nsToGrAlg R J)
        (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J))).comp
        (AffineNormalCone.normalSheafTangentAction A R J).act =
      (act A σ R J).comp (nsToGrAlg R J) :=
  map_comp_bundleTranslationCoaction A σ R J

/-- **The tangent action commutes with the `𝔸¹`-contractions.**  This is the last `ConeAction`
axiom; it follows from the corresponding statement for the normal sheaf, because the closed
immersion `Sym(J/J²) ↠ gr_J(R)` is surjective, equivariant and a morphism of cones. -/
theorem conic_act :
    IsConeHom (normalConeCoactionQuot R J)
      (tensorCoaction (normalConeCoactionQuot R J)
        (symCoaction (R ⧸ J) (Tangent A R J))) (act A σ R J) := by
  have hmap : IsConeHom
      (tensorCoaction (symCoaction (R ⧸ J) J.Cotangent) (symCoaction (R ⧸ J) (Tangent A R J)))
      (tensorCoaction (normalConeCoactionQuot R J) (symCoaction (R ⧸ J) (Tangent A R J)))
      (Algebra.TensorProduct.map (nsToGrAlg R J)
        (symMap (LinearMap.id : Tangent A R J →ₗ[R ⧸ J] Tangent A R J))) := by
    rw [symMap_id]
    exact isConeHom_tensorMap (isConeHom_nsToGrAlg R J)
      (isConeHom_id (symCoaction (R ⧸ J) (Tangent A R J)))
  have hbundle : IsConeHom (symCoaction (R ⧸ J) J.Cotangent)
      (tensorCoaction (symCoaction (R ⧸ J) J.Cotangent) (symCoaction (R ⧸ J) (Tangent A R J)))
      (bundleTranslationCoaction (AffineNormalCone.conormalMap A R J)) :=
    (AffineNormalCone.normalSheafTangentAction A R J).conic
  have heq := map_comp_bundleTranslationCoaction A σ R J
  have hpsi := isConeHom_nsToGrAlg R J
  have key : ((Polynomial.mapAlgHom (act A σ R J)).comp
        (normalConeCoactionQuot R J)).comp (nsToGrAlg R J) =
      ((tensorCoaction (normalConeCoactionQuot R J)
        (symCoaction (R ⧸ J) (Tangent A R J))).comp (act A σ R J)).comp (nsToGrAlg R J) := by
    rw [AlgHom.comp_assoc, ← hpsi, ← AlgHom.comp_assoc, mapAlgHom_comp, ← heq,
      ← mapAlgHom_comp, AlgHom.comp_assoc, hbundle, ← AlgHom.comp_assoc, hmap,
      AlgHom.comp_assoc, heq, ← AlgHom.comp_assoc]
  refine AlgHom.ext fun z ↦ ?_
  obtain ⟨s, rfl⟩ := nsToGrAlg_surjective R J z
  exact AlgHom.congr_fun key s

/-! ## The cone action -/

/-- **The tangent action of `T_M|_U` on the affine normal cone `C_{U/M}` of a formally étale
chart.**

The `𝔸¹`-contraction is the grading of `gr_J(R)` (`GradedCone.normalConeCoactionQuot`), the
coaction is `EtaleAmbient.coactionEtale`, and all four `ConeAction` axioms are proved: the unit
and associativity laws are `EtaleAmbient.translatePointEtale_zero` and `_add`, and the
`𝔾ₘ`-equivariance is `EtaleConeAction.conic_act`. -/
def etaleNormalConeAction :
    ConeAction (R ⧸ J) (associatedGradedRing R J) (Tangent A R J) where
  coaction := normalConeCoactionQuot R J
  isCone := isConeCoaction_normalConeCoactionQuot R J
  act := act A σ R J
  act_zero φ := act_zero A σ R J φ
  act_add φ l l' := act_add A σ R J φ l l'
  conic := conic_act A σ R J

@[simp]
theorem etaleNormalConeAction_act : (etaleNormalConeAction A σ R J).act = act A σ R J := rfl

@[simp]
theorem etaleNormalConeAction_coaction :
    (etaleNormalConeAction A σ R J).coaction = normalConeCoactionQuot R J := rfl

/-- **The closed immersion of the affine normal cone of an étale chart into the affine normal
sheaf is equivariant** for the tangent actions.  This is Vistoli's lemma: the translation action
of `T_M|_U` on `N_{U/M}` preserves the closed subcone `C_{U/M}`. -/
theorem isEquivariant_nsToGrAlg :
    IsEquivariant (AffineNormalCone.normalSheafTangentAction A R J)
      (etaleNormalConeAction A σ R J) (nsToGrAlg R J) LinearMap.id :=
  map_comp_bundleTranslationCoaction A σ R J

end Equivariance

/-! ## The obstruction cone of the normal cone of an étale chart -/

section ObstructionCone

open PicardCriteria NormalSheafPicard NormalSheafPicard.AffineIntrinsicNormalSheaf

variable (A : Type u) [CommRing A] (σ : Type u) (R : Type u) [CommRing R]
  [Algebra (Amb A σ) R] [Algebra.FormallyEtale (Amb A σ) R] [Algebra A R]
  [IsScalarTower A (Amb A σ) R] (J : Ideal R) {E : LinearTwoTermComplex (R ⧸ J)}

/-- **The obstruction cone of the affine normal cone of a formally étale chart.**

For an obstruction theory `φ : E ⟶ [J/J² → (R/J) ⊗ Ω[R⁄A]]` this is the morphism of cone stacks

`[C_{U/M}/T_M|_U](B) ⟶ h¹/h⁰(Eᵛ)(B)`

over every test algebra `B`, obtained by instantiating `PicardCriteria.obstructionCone` with the
equivariant closed immersion `EtaleConeAction.isEquivariant_nsToGrAlg`. -/
def etaleNormalConeObstructionCone
    (φ : LinearTwoTermComplex.Hom E (conormalComplex A R J))
    (B : Type u) [CommRing B] [Algebra (R ⧸ J) B] :
    QuotientGroupoid (etaleNormalConeAction A σ R J) B ⥤ (dualPoints E B).quotient :=
  PicardCriteria.obstructionCone φ (isEquivariant_nsToGrAlg A σ R J) B

/-- **The obstruction cone of an étale chart is a closed immersion, first half.** -/
def etaleNormalConeObstructionConeFullyFaithful
    {φ : LinearTwoTermComplex.Hom E (conormalComplex A R J)}
    (hφ : IsObstructionTheory φ) (B : Type u) [CommRing B] [Algebra (R ⧸ J) B] :
    (etaleNormalConeObstructionCone A σ R J φ B).FullyFaithful :=
  PicardCriteria.obstructionConeFullyFaithful hφ (isEquivariant_nsToGrAlg A σ R J)
    (nsToGrAlg_surjective R J) B

/-- **The obstruction cone of an étale chart is a closed immersion, second half.** -/
theorem etaleNormalConeObstructionCone_injective_isoClass
    {φ : LinearTwoTermComplex.Hom E (conormalComplex A R J)}
    (hφ : IsObstructionTheory φ) (B : Type u) [CommRing B] [Algebra (R ⧸ J) B]
    {c c' : QuotientGroupoid (etaleNormalConeAction A σ R J) B}
    (hiso : Nonempty ((etaleNormalConeObstructionCone A σ R J φ B).obj c
      ≅ (etaleNormalConeObstructionCone A σ R J φ B).obj c')) :
    Nonempty (c ≅ c') :=
  PicardCriteria.obstructionCone_injective_isoClass hφ (isEquivariant_nsToGrAlg A σ R J)
    (nsToGrAlg_surjective R J) B hiso

/-- **The obstruction cone for an obstruction theory on the presentation cotangent complex** of
`R → R/J`. -/
def presentationEtaleNormalConeObstructionCone
    (φ : LinearTwoTermComplex.Hom E
      (CotangentComplex.AffinePresentation.twoTerm A (R ⧸ J) (quotientExtension A R J)))
    (B : Type u) [CommRing B] [Algebra (R ⧸ J) B] :
    QuotientGroupoid (etaleNormalConeAction A σ R J) B ⥤ (dualPoints E B).quotient :=
  etaleNormalConeObstructionCone A σ R J (PicardCriteria.ofPresentation A R J φ) B

/-- The obstruction cone attached to an obstruction theory on the presentation complex is fully
faithful. -/
def presentationEtaleNormalConeObstructionConeFullyFaithful
    {φ : LinearTwoTermComplex.Hom E
      (CotangentComplex.AffinePresentation.twoTerm A (R ⧸ J) (quotientExtension A R J))}
    (hφ : IsObstructionTheory φ) (B : Type u) [CommRing B] [Algebra (R ⧸ J) B] :
    (presentationEtaleNormalConeObstructionCone A σ R J φ B).FullyFaithful :=
  etaleNormalConeObstructionConeFullyFaithful A σ R J
    (PicardCriteria.isObstructionTheory_ofPresentation A R J hφ) B

end ObstructionCone

/-! ## Agreement with the polynomial model -/

section Model

variable (A : Type u) [CommRing A] (σ : Type u) (I : Ideal (Amb A σ))

/-- In the polynomial model the two descriptions of the tangent basis agree. -/
theorem tangentBasis_eq :
    tangentBasis A σ (Amb A σ) I = NormalConeAction.tangentBasis I := by
  refine Module.Basis.eq_of_apply_eq fun i ↦ ?_
  rw [tangentBasis_apply, NormalConeAction.tangentBasis_apply, Algebra.algebraMap_self_apply]

/-- In the polynomial model the two polynomial presentations of `Sym(F)` agree. -/
theorem symEquiv_eq : symEquiv A σ (Amb A σ) I = NormalConeAction.symEquiv I := by
  unfold symEquiv NormalConeAction.symEquiv
  rw [tangentBasis_eq]

/-- In the polynomial model the two comparison isomorphisms agree. -/
theorem tensorEquiv_eq : tensorEquiv A σ (Amb A σ) I = NormalConeAction.tensorEquiv I := by
  unfold tensorEquiv NormalConeAction.tensorEquiv
  rw [symEquiv_eq]

/-- In the polynomial model the two coactions agree: this is
`EtaleAmbient.coactionEtale_eq_coaction`. -/
theorem coactionQ_eq : coactionQ A σ (Amb A σ) I = NormalConeAction.coactionQ I := by
  refine AlgHom.ext fun z ↦ ?_
  change coactionEtale A σ (Amb A σ) I z = ConeTranslation.coaction I z
  rw [coactionEtale_eq_coaction]
  rfl

/-- In the polynomial model the two tangent coactions agree. -/
theorem act_eq : act A σ (Amb A σ) I = NormalConeAction.act I := by
  unfold act NormalConeAction.act
  rw [tensorEquiv_eq, coactionQ_eq]

/-- Two cone actions with the same contraction and the same coaction are equal; the remaining
fields are propositions. -/
theorem coneAction_ext {S : Type u} [CommRing S] {T : Type u} [CommRing T] [Algebra S T]
    {F : Type u} [AddCommGroup F] [Module S F] {Ac Ac' : ConeAction S T F}
    (hc : Ac.coaction = Ac'.coaction) (ha : Ac.act = Ac'.act) : Ac = Ac' := by
  obtain ⟨c, hi, a, hz, had, hco⟩ := Ac
  obtain ⟨c', hi', a', hz', had', hco'⟩ := Ac'
  change c = c' at hc
  change a = a' at ha
  subst hc
  subst ha
  rfl

/-- **For the polynomial model the étale cone action is the cone action of
`Cones/NormalConeAction.lean`.** -/
theorem etaleNormalConeAction_eq :
    etaleNormalConeAction A σ (Amb A σ) I = NormalConeAction.normalConeAction I :=
  coneAction_ext rfl (act_eq A σ I)

end Model

end

end EtaleConeAction

end GromovWitten.AlgebraicGeometry
