/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude Opus 5
-/

import GromovWitten.AlgebraicGeometry.ObstructionTheory.AffineObstructionCone
import Mathlib.RingTheory.Kaehler.Polynomial
import Mathlib.LinearAlgebra.Basis.Prod

/-!
# The conormal complex of a product is the external sum of the conormal complexes

Let `k` be a field, let `I ⊆ k[x_σ]` and `I' ⊆ k[x_τ]` be ideals and let

* `R = k[x_σ]`, `R' = k[x_τ]`, `M = k[x_{σ ⊕ τ}]`,
* `ι = rename Sum.inl : R → M`, `ι' = rename Sum.inr : R' → M`,
* `J = I·M + I'·M = I.map ι ⊔ I'.map ι'` (`prodIdeal`),
* `S = R/I`, `S' = R'/I'`, `T = M/J` (`prodQuot`).

Geometrically `Spec T = Spec S × Spec S'` sits in `𝔸^{σ ⊕ τ} = 𝔸^σ × 𝔸^τ` as the product of the
two local embeddings `Spec S ↪ 𝔸^σ`, `Spec S' ↪ 𝔸^τ`.  This file proves that the conormal complex
`[J/J² → T ⊗_M Ω[M⁄k]]` of the product embedding
(`NormalSheafPicard.AffineIntrinsicNormalSheaf.conormalComplex k M J`) is isomorphic to the
external direct sum of the pullbacks of the conormal complexes of the two factors, the affine
model of `L_{X × Y} ≅ pr_X^* L_X ⊕ pr_Y^* L_Y`.  This is the identification that was left open in
`ObstructionTheory/ExternalSum.lean`.

## Main results

* `ExternalSumConormal.degreeZeroEquiv`:
  `(T ⊗_S I/I²) × (T ⊗_{S'} I'/I'²) ≃ₗ[T] J/J²`.  The map `degreeZeroHom` is built from the
  functoriality of the conormal module (`Ideal.mapCotangent`) by base change; it is surjective
  because `J` is generated by `ι(I) ∪ ι'(I')`, and injective because of an explicit retraction
  `retractInl`/`retractInr` onto each summand.  The retraction is the only place where the
  hypothesis that `k` is a *field* enters: one chooses a `k`-linear splitting `π : R → I` of the
  inclusion of the `k`-subspace `I ⊆ R` (`idealProj`, from `Submodule.exists_isCompl` through
  `LinearMap.exists_leftInverse_of_injective`) and forms the `k`-linear map
  `ψ : M ≅ R ⊗_k R' → T ⊗_S I/I²`, `p ⊗ p' ↦ [ι' p'] · (1 ⊗ [π p])`.  It satisfies
  `ψ (m · ι x) = [m] · (1 ⊗ [x])` for `x ∈ I` (`psi_mul_inlHom`) and `ψ (m · ι' x') = 0` for
  `x' ∈ I'` (`psi_mul_inrHom`), and it kills `J · J` (`psi_mul_mem_mem`), so it descends to
  `J/J²`.  No flatness argument and no computation of `I·M ∩ I'·M` is needed.
* `ExternalSumConormal.degreeOneEquiv`:
  `(T ⊗_S (S ⊗_R Ω[R⁄k])) × (T ⊗_{S'} (S' ⊗_{R'} Ω[R'⁄k])) ≃ₗ[T] T ⊗_M Ω[M⁄k]`.  All three
  modules are free over `T` on the classes of the `dX_i` (`KaehlerDifferential.mvPolynomialBasis`
  base changed twice, `Module.Basis.prod`), and the equivalence is the one matching the two bases
  along `Equiv.refl (σ ⊕ τ)`.  `degreeOneInl_D`/`degreeOneInr_D` are the compatibility with the
  universal derivation: `dp ⊞ 0 ↦ d(ι p)` for *every* polynomial `p`, proved by
  `MvPolynomial.induction_on` from the Leibniz rule.
* `ExternalSumConormal.conormalProdHom`, `ExternalSumConormal.conormalProdInv`,
  `ExternalSumConormal.conormalProdEquiv`: the two degreewise equivalences commute with the
  conormal differentials (`square_inl`, `square_inr`), hence assemble into mutually inverse chain
  maps and a `LinearTwoTermComplex.HomotopyEquivalence` (with zero chain homotopies) between
  `conormalSum I I'` — the external sum of the two conormal complexes, base changed to `T` — and
  `conormalComplex k M J`.
* `ExternalSumConormal.isObstructionTheory_externalSum_conormal`: if `φ` is an obstruction theory
  for `Spec S ↪ 𝔸^σ` and `φ'` one for `Spec S' ↪ 𝔸^τ`, then the external sum
  `(φ.baseChange T).sum (φ'.baseChange T)`, composed with `conormalProdEquiv`, is an obstruction
  theory for the product embedding `Spec T ↪ 𝔸^{σ ⊕ τ}`.
* `ExternalSumConormal.virtualRank_externalSum`: the virtual rank of the external sum of two
  perfect two-term complexes is the sum of the virtual ranks.

## Relation to `ObstructionTheory/ExternalSum.lean`

`ExternalSum.lean` constructs the external sum over the ring `S ⊗[k] S'`.  Here everything is
phrased over `T = M/J`, which avoids transporting a `LinearTwoTermComplex` along a ring
isomorphism.  The canonical `k`-algebra isomorphism `T ≃ₐ[k] S ⊗[k] S'` identifying the two base
rings *is* constructed, as `ExternalSumConormal.prodQuotAlgEquiv`; transporting the complexes
themselves along it (which would only reshuffle the base ring of every module involved) is not
carried out, because none of the statements above needs it.

## What is not done

* **Beyond polynomial presentations.**  Everything is stated for the standard presentations
  `R = k[x_σ]`, `R' = k[x_τ]` of the two factors.  The degree-zero statement `degreeZeroEquiv`
  only uses that `k` is a field and that `M` is the tensor product `R ⊗_k R'`; the degree-one
  statement uses freeness of `Ω[R⁄k]` on the `dX_i`, i.e. smoothness of the ambient spaces.  A
  version for an arbitrary smooth ambient scheme would need the corresponding basis-free
  argument.
* **`k` a field.**  The hypothesis is used exactly once, for the `k`-linear splitting of
  `I ⊆ R`; over a general base ring it should be replaced by flatness of `R/I` or by
  `Ideal.tensorCotangentEquiv`.
* **Non-affine products.**  The statement is about a product of two *affine* local embeddings;
  gluing it to a statement about a product `X × Y` of schemes or Deligne–Mumford stacks, and
  comparing with the global cotangent complex, is not addressed.
* **General (non-split) distinguished triangles** and pullback along a general morphism, listed
  as open in `ObstructionTheory/ExternalSum.lean`, are likewise not addressed here.
-/

open scoped TensorProduct

namespace GromovWitten.AlgebraicGeometry

namespace ExternalSumConormal

universe u

variable (k : Type u) [Field k] (σ τ : Type u)

/-- The inclusion `k[x_σ] → k[x_{σ ⊕ τ}]` of the first block of variables. -/
noncomputable abbrev inlHom : MvPolynomial σ k →ₐ[k] MvPolynomial (σ ⊕ τ) k :=
  MvPolynomial.rename Sum.inl

/-- The inclusion `k[x_τ] → k[x_{σ ⊕ τ}]` of the second block of variables. -/
noncomputable abbrev inrHom : MvPolynomial τ k →ₐ[k] MvPolynomial (σ ⊕ τ) k :=
  MvPolynomial.rename Sum.inr


/-! ## Comparison of `k[x_{σ ⊕ τ}]` with `k[x_σ] ⊗_k k[x_τ]` -/

/-- The multiplication map `k[x_σ] ⊗_k k[x_τ] → k[x_{σ ⊕ τ}]`. -/
noncomputable def ofTensor :
    MvPolynomial σ k ⊗[k] MvPolynomial τ k →ₐ[k] MvPolynomial (σ ⊕ τ) k :=
  Algebra.TensorProduct.lift (inlHom k σ τ) (inrHom k σ τ) fun _ _ => Commute.all _ _

/-- The comparison map `k[x_{σ ⊕ τ}] → k[x_σ] ⊗_k k[x_τ]`, sending the variables of the first
block to `X i ⊗ 1` and those of the second block to `1 ⊗ X j`. -/
noncomputable def toTensor :
    MvPolynomial (σ ⊕ τ) k →ₐ[k] MvPolynomial σ k ⊗[k] MvPolynomial τ k :=
  MvPolynomial.aeval
    (Sum.elim (fun i => MvPolynomial.X i ⊗ₜ[k] (1 : MvPolynomial τ k))
      (fun j => (1 : MvPolynomial σ k) ⊗ₜ[k] MvPolynomial.X j))

/-- `ofTensor` on a pure tensor. -/
@[simp]
theorem ofTensor_tmul (p : MvPolynomial σ k) (q : MvPolynomial τ k) :
    ofTensor k σ τ (p ⊗ₜ[k] q) = inlHom k σ τ p * inrHom k σ τ q :=
  Algebra.TensorProduct.lift_tmul _ _ _ _ _

/-- `toTensor` undoes the first inclusion. -/
@[simp]
theorem toTensor_inlHom (p : MvPolynomial σ k) :
    toTensor k σ τ (inlHom k σ τ p) = p ⊗ₜ[k] (1 : MvPolynomial τ k) := by
  have : (toTensor k σ τ).comp (inlHom k σ τ) =
      (Algebra.TensorProduct.includeLeft :
        MvPolynomial σ k →ₐ[k] MvPolynomial σ k ⊗[k] MvPolynomial τ k) := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [toTensor]
  exact congrArg (fun f => f p) (congrArg (fun f : MvPolynomial σ k →ₐ[k] _ => (f : _ → _)) this)

/-- `toTensor` undoes the second inclusion. -/
@[simp]
theorem toTensor_inrHom (q : MvPolynomial τ k) :
    toTensor k σ τ (inrHom k σ τ q) = (1 : MvPolynomial σ k) ⊗ₜ[k] q := by
  have : (toTensor k σ τ).comp (inrHom k σ τ) =
      (Algebra.TensorProduct.includeRight :
        MvPolynomial τ k →ₐ[k] MvPolynomial σ k ⊗[k] MvPolynomial τ k) := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [toTensor]
  exact congrArg (fun f => f q) (congrArg (fun f : MvPolynomial τ k →ₐ[k] _ => (f : _ → _)) this)

/-- `ofTensor` is a retraction of `toTensor`; in particular `ofTensor` is surjective. -/
@[simp]
theorem ofTensor_toTensor (p : MvPolynomial (σ ⊕ τ) k) :
    ofTensor k σ τ (toTensor k σ τ p) = p := by
  have : (ofTensor k σ τ).comp (toTensor k σ τ) = AlgHom.id k (MvPolynomial (σ ⊕ τ) k) := by
    apply MvPolynomial.algHom_ext
    rintro (i | j) <;> simp [toTensor, inlHom, inrHom]
  exact congrArg (fun f => f p)
    (congrArg (fun f : MvPolynomial (σ ⊕ τ) k →ₐ[k] _ => (f : _ → _)) this)

/-- Every polynomial in `k[x_{σ ⊕ τ}]` is the image of an element of `k[x_σ] ⊗_k k[x_τ]`. -/
theorem ofTensor_surjective : Function.Surjective (ofTensor k σ τ) :=
  fun p => ⟨toTensor k σ τ p, ofTensor_toTensor k σ τ p⟩


/-! ## Module structures on the conormal module of the product ideal -/

/-- `k[x_{σ ⊕ τ}]` as a `k[x_σ]`-algebra, via the first block of variables. -/
@[instance_reducible] noncomputable def algebraInl :
    Algebra (MvPolynomial σ k) (MvPolynomial (σ ⊕ τ) k) :=
  (inlHom k σ τ).toRingHom.toAlgebra

/-- `k[x_{σ ⊕ τ}]` as a `k[x_τ]`-algebra, via the second block of variables. -/
@[instance_reducible] noncomputable def algebraInr :
    Algebra (MvPolynomial τ k) (MvPolynomial (σ ⊕ τ) k) :=
  (inrHom k σ τ).toRingHom.toAlgebra

attribute [local instance] algebraInl algebraInr

/-- The structure map of `algebraInl`. -/
@[simp]
theorem algebraMap_inl (p : MvPolynomial σ k) :
    algebraMap (MvPolynomial σ k) (MvPolynomial (σ ⊕ τ) k) p = inlHom k σ τ p :=
  rfl

/-- The structure map of `algebraInr`. -/
@[simp]
theorem algebraMap_inr (p : MvPolynomial τ k) :
    algebraMap (MvPolynomial τ k) (MvPolynomial (σ ⊕ τ) k) p = inrHom k σ τ p :=
  rfl

/-- `k → k[x_σ] → k[x_{σ ⊕ τ}]` is a tower. -/
instance isScalarTower_inl : IsScalarTower k (MvPolynomial σ k) (MvPolynomial (σ ⊕ τ) k) :=
  .of_algebraMap_eq fun a => by simp [MvPolynomial.algebraMap_eq]

/-- `k → k[x_τ] → k[x_{σ ⊕ τ}]` is a tower. -/
instance isScalarTower_inr : IsScalarTower k (MvPolynomial τ k) (MvPolynomial (σ ⊕ τ) k) :=
  .of_algebraMap_eq fun a => by simp [MvPolynomial.algebraMap_eq]

variable {k σ τ}
variable (I : Ideal (MvPolynomial σ k)) (I' : Ideal (MvPolynomial τ k))

/-- The ideal `J = I · k[x_{σ ⊕ τ}] + I' · k[x_{σ ⊕ τ}]` of the product embedding
`Spec (k[x_σ]/I) × Spec (k[x_τ]/I') ↪ 𝔸^{σ ⊕ τ}`. -/
noncomputable def prodIdeal : Ideal (MvPolynomial (σ ⊕ τ) k) :=
  I.map (inlHom k σ τ) ⊔ I'.map (inrHom k σ τ)

/-- The image of `I` lies in the product ideal. -/
theorem inlHom_mem_prodIdeal {x : MvPolynomial σ k} (hx : x ∈ I) :
    inlHom k σ τ x ∈ prodIdeal I I' :=
  le_sup_left (α := Ideal (MvPolynomial (σ ⊕ τ) k)) (Ideal.mem_map_of_mem _ hx)

/-- The image of `I'` lies in the product ideal. -/
theorem inrHom_mem_prodIdeal {x : MvPolynomial τ k} (hx : x ∈ I') :
    inrHom k σ τ x ∈ prodIdeal I I' :=
  le_sup_right (α := Ideal (MvPolynomial (σ ⊕ τ) k)) (Ideal.mem_map_of_mem _ hx)

/-- `J` is generated by the images of `I` and of `I'`. -/
theorem prodIdeal_eq_span :
    prodIdeal I I' =
      Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I') := by
  rw [Ideal.span_union, prodIdeal, Ideal.map, Ideal.map]


/-! ## The two algebra structures on the product quotient ring -/

/-- The `k`-algebra map `k[x_σ]/I → k[x_{σ ⊕ τ}]/J` induced by the first block of variables. -/
noncomputable def toProdQuotLeft :
    (MvPolynomial σ k ⧸ I) →ₐ[k] (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') :=
  Ideal.Quotient.liftₐ I ((Ideal.Quotient.mkₐ k (prodIdeal I I')).comp (inlHom k σ τ))
    fun _ ha => Ideal.Quotient.eq_zero_iff_mem.mpr (inlHom_mem_prodIdeal I I' ha)

/-- The `k`-algebra map `k[x_τ]/I' → k[x_{σ ⊕ τ}]/J` induced by the second block of variables. -/
noncomputable def toProdQuotRight :
    (MvPolynomial τ k ⧸ I') →ₐ[k] (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') :=
  Ideal.Quotient.liftₐ I' ((Ideal.Quotient.mkₐ k (prodIdeal I I')).comp (inrHom k σ τ))
    fun _ ha => Ideal.Quotient.eq_zero_iff_mem.mpr (inrHom_mem_prodIdeal I I' ha)

/-- The `k[x_σ]/I`-algebra structure on `k[x_{σ ⊕ τ}]/J`: the first projection of the product. -/
@[instance_reducible] noncomputable def algebraProdQuotLeft :
    Algebra (MvPolynomial σ k ⧸ I) (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') :=
  (toProdQuotLeft I I').toRingHom.toAlgebra

/-- The `k[x_τ]/I'`-algebra structure on `k[x_{σ ⊕ τ}]/J`: the second projection of the
product. -/
@[instance_reducible] noncomputable def algebraProdQuotRight :
    Algebra (MvPolynomial τ k ⧸ I') (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') :=
  (toProdQuotRight I I').toRingHom.toAlgebra

attribute [local instance] algebraProdQuotLeft algebraProdQuotRight

/-- The structure map of `algebraProdQuotLeft` on classes of polynomials. -/
@[simp]
theorem algebraMap_prodQuot_left (p : MvPolynomial σ k) :
    algebraMap (MvPolynomial σ k ⧸ I) (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I')
        (Ideal.Quotient.mk I p) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) :=
  rfl

/-- The structure map of `algebraProdQuotRight` on classes of polynomials. -/
@[simp]
theorem algebraMap_prodQuot_right (p : MvPolynomial τ k) :
    algebraMap (MvPolynomial τ k ⧸ I') (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I')
        (Ideal.Quotient.mk I' p) =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ p) :=
  rfl

/-- The `k[x_σ]/I`-module structure on `J/J²`, restricted along the first projection
`k[x_σ]/I → k[x_{σ ⊕ τ}]/J` of the product. -/
@[instance_reducible] noncomputable def moduleQuotLeftCotangent :
    Module (MvPolynomial σ k ⧸ I) (prodIdeal I I').Cotangent :=
  Module.compHom _
    (algebraMap (MvPolynomial σ k ⧸ I) (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I'))

/-- The `k[x_τ]/I'`-module structure on `J/J²`, restricted along the second projection
`k[x_τ]/I' → k[x_{σ ⊕ τ}]/J` of the product. -/
@[instance_reducible] noncomputable def moduleQuotRightCotangent :
    Module (MvPolynomial τ k ⧸ I') (prodIdeal I I').Cotangent :=
  Module.compHom _
    (algebraMap (MvPolynomial τ k ⧸ I') (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I'))

attribute [local instance] moduleQuotLeftCotangent moduleQuotRightCotangent

/-- Unfolding the scalar action of `moduleQuotLeftCotangent`. -/
theorem smul_cotangent_left (s : MvPolynomial σ k ⧸ I) (c : (prodIdeal I I').Cotangent) :
    s • c = algebraMap (MvPolynomial σ k ⧸ I) (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') s • c :=
  rfl

/-- Unfolding the scalar action of `moduleQuotRightCotangent`. -/
theorem smul_cotangent_right (s : MvPolynomial τ k ⧸ I') (c : (prodIdeal I I').Cotangent) :
    s • c = algebraMap (MvPolynomial τ k ⧸ I') (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') s • c :=
  rfl

/-- `k[x_σ]/I → k[x_{σ ⊕ τ}]/J` acting on `J/J²` is a scalar tower. -/
theorem isScalarTower_quotLeft_cotangent :
    IsScalarTower (MvPolynomial σ k ⧸ I) (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I')
      (prodIdeal I I').Cotangent where
  smul_assoc s t c := by
    rw [smul_cotangent_left, Algebra.smul_def, mul_smul]

/-- `k[x_τ]/I' → k[x_{σ ⊕ τ}]/J` acting on `J/J²` is a scalar tower. -/
theorem isScalarTower_quotRight_cotangent :
    IsScalarTower (MvPolynomial τ k ⧸ I') (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I')
      (prodIdeal I I').Cotangent where
  smul_assoc s t c := by
    rw [smul_cotangent_right, Algebra.smul_def, mul_smul]

attribute [local instance] isScalarTower_quotLeft_cotangent isScalarTower_quotRight_cotangent

/-- The class of a polynomial acts on `J/J²` as the polynomial itself. -/
theorem mk_smul_cotangent (m : MvPolynomial (σ ⊕ τ) k) (c : (prodIdeal I I').Cotangent) :
    Ideal.Quotient.mk (prodIdeal I I') m • c = m • c :=
  algebraMap_smul (MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I') m c

/-- `k[x_σ] → k[x_σ]/I` acting on `J/J²` is a scalar tower. -/
theorem isScalarTower_polyLeft_cotangent :
    IsScalarTower (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) (prodIdeal I I').Cotangent where
  smul_assoc p s c := by
    have h1 : (p • s : MvPolynomial σ k ⧸ I) = Ideal.Quotient.mk I p * s := Algebra.smul_def p s
    rw [smul_cotangent_left, smul_cotangent_left, h1, map_mul, algebraMap_prodQuot_left, mul_smul,
      mk_smul_cotangent]
    exact (algebraMap_smul (MvPolynomial (σ ⊕ τ) k) p _).symm

/-- `k[x_τ] → k[x_τ]/I'` acting on `J/J²` is a scalar tower. -/
theorem isScalarTower_polyRight_cotangent :
    IsScalarTower (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') (prodIdeal I I').Cotangent where
  smul_assoc p s c := by
    have h1 : (p • s : MvPolynomial τ k ⧸ I') = Ideal.Quotient.mk I' p * s := Algebra.smul_def p s
    rw [smul_cotangent_right, smul_cotangent_right, h1, map_mul, algebraMap_prodQuot_right,
      mul_smul, mk_smul_cotangent]
    exact (algebraMap_smul (MvPolynomial (σ ⊕ τ) k) p _).symm

attribute [local instance] isScalarTower_polyLeft_cotangent isScalarTower_polyRight_cotangent


/-! ## The degree-zero comparison map -/

/-- Shorthand for the coordinate ring `k[x_{σ ⊕ τ}]/J` of the product. -/
abbrev prodQuot : Type u := MvPolynomial (σ ⊕ τ) k ⧸ prodIdeal I I'

/-- The comparison map `I/I² → J/J²`, `[x] ↦ [ι x]`, as a `k[x_σ]`-linear map. -/
noncomputable def cotangentInlAux :
    I.Cotangent →ₗ[MvPolynomial σ k] (prodIdeal I I').Cotangent :=
  Ideal.mapCotangent I (prodIdeal I I')
    (Algebra.ofId (MvPolynomial σ k) (MvPolynomial (σ ⊕ τ) k))
    fun _ hx => inlHom_mem_prodIdeal I I' hx

/-- The comparison map `I'/I'² → J/J²`, `[x] ↦ [ι' x]`, as a `k[x_τ]`-linear map. -/
noncomputable def cotangentInrAux :
    I'.Cotangent →ₗ[MvPolynomial τ k] (prodIdeal I I').Cotangent :=
  Ideal.mapCotangent I' (prodIdeal I I')
    (Algebra.ofId (MvPolynomial τ k) (MvPolynomial (σ ⊕ τ) k))
    fun _ hx => inrHom_mem_prodIdeal I I' hx

/-- `cotangentInlAux` on a generator. -/
@[simp]
theorem cotangentInlAux_toCotangent (x : I) :
    cotangentInlAux I I' (Ideal.toCotangent I x) =
      Ideal.toCotangent (prodIdeal I I')
        ⟨inlHom k σ τ (x : MvPolynomial σ k), inlHom_mem_prodIdeal I I' x.2⟩ :=
  rfl

/-- `cotangentInrAux` on a generator. -/
@[simp]
theorem cotangentInrAux_toCotangent (x : I') :
    cotangentInrAux I I' (Ideal.toCotangent I' x) =
      Ideal.toCotangent (prodIdeal I I')
        ⟨inrHom k σ τ (x : MvPolynomial τ k), inrHom_mem_prodIdeal I I' x.2⟩ :=
  rfl

/-- The comparison map `I/I² → J/J²` as a `k[x_σ]/I`-linear map. -/
noncomputable def cotangentInl :
    I.Cotangent →ₗ[MvPolynomial σ k ⧸ I] (prodIdeal I I').Cotangent :=
  LinearMap.extendScalarsOfSurjective Ideal.Quotient.mk_surjective (cotangentInlAux I I')

/-- The comparison map `I'/I'² → J/J²` as a `k[x_τ]/I'`-linear map. -/
noncomputable def cotangentInr :
    I'.Cotangent →ₗ[MvPolynomial τ k ⧸ I'] (prodIdeal I I').Cotangent :=
  LinearMap.extendScalarsOfSurjective Ideal.Quotient.mk_surjective (cotangentInrAux I I')

/-- `cotangentInl` on a generator. -/
@[simp]
theorem cotangentInl_toCotangent (x : I) :
    cotangentInl I I' (Ideal.toCotangent I x) =
      Ideal.toCotangent (prodIdeal I I')
        ⟨inlHom k σ τ (x : MvPolynomial σ k), inlHom_mem_prodIdeal I I' x.2⟩ :=
  rfl

/-- `cotangentInr` on a generator. -/
@[simp]
theorem cotangentInr_toCotangent (x : I') :
    cotangentInr I I' (Ideal.toCotangent I' x) =
      Ideal.toCotangent (prodIdeal I I')
        ⟨inrHom k σ τ (x : MvPolynomial τ k), inrHom_mem_prodIdeal I I' x.2⟩ :=
  rfl

/-- The first component of the degree-zero comparison map:
`(k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I² → J/J²`. -/
noncomputable def degZeroInl :
    (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) →ₗ[prodQuot I I']
      (prodIdeal I I').Cotangent :=
  LinearMap.liftBaseChange (prodQuot I I') (cotangentInl I I')

/-- The second component of the degree-zero comparison map:
`(k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'² → J/J²`. -/
noncomputable def degZeroInr :
    (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) →ₗ[prodQuot I I']
      (prodIdeal I I').Cotangent :=
  LinearMap.liftBaseChange (prodQuot I I') (cotangentInr I I')

/-- The degree-zero comparison map from the external sum of the two conormal modules to the
conormal module of the product ideal. -/
noncomputable def degreeZeroHom :
    ((prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) ×
      (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent)) →ₗ[prodQuot I I']
      (prodIdeal I I').Cotangent :=
  (degZeroInl I I').coprod (degZeroInr I I')

/-- `degreeZeroHom` is the sum of its two components. -/
theorem degreeZeroHom_apply (w : prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent)
    (w' : prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :
    degreeZeroHom I I' (w, w') = degZeroInl I I' w + degZeroInr I I' w' :=
  rfl

/-- `degZeroInl` on a generator. -/
@[simp]
theorem degZeroInl_tmul (t : prodQuot I I') (x : I) :
    degZeroInl I I' (t ⊗ₜ Ideal.toCotangent I x) =
      t • Ideal.toCotangent (prodIdeal I I')
        ⟨inlHom k σ τ (x : MvPolynomial σ k), inlHom_mem_prodIdeal I I' x.2⟩ := by
  simp [degZeroInl]

/-- `degZeroInr` on a generator. -/
@[simp]
theorem degZeroInr_tmul (t : prodQuot I I') (x : I') :
    degZeroInr I I' (t ⊗ₜ Ideal.toCotangent I' x) =
      t • Ideal.toCotangent (prodIdeal I I')
        ⟨inrHom k σ τ (x : MvPolynomial τ k), inrHom_mem_prodIdeal I I' x.2⟩ := by
  simp [degZeroInr]


/-- Membership in `J` from membership in the span of the two images. -/
theorem mem_prodIdeal_of_mem_span {z : MvPolynomial (σ ⊕ τ) k}
    (hz : z ∈ Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I')) : z ∈ prodIdeal I I' := by
  rwa [prodIdeal_eq_span]

/-- The class in `J/J²` of any element of `J` lies in the range of `degreeZeroHom`. -/
theorem toCotangent_mem_range_degreeZeroHom (y : MvPolynomial (σ ⊕ τ) k)
    (hy : y ∈ prodIdeal I I') :
    Ideal.toCotangent (prodIdeal I I') ⟨y, hy⟩ ∈ LinearMap.range (degreeZeroHom I I') := by
  have key : ∀ z ∈ Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I'),
      ∀ hz : z ∈ prodIdeal I I',
        Ideal.toCotangent (prodIdeal I I') ⟨z, hz⟩ ∈ LinearMap.range (degreeZeroHom I I') := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem w hw =>
      intro hw'
      rcases hw with ⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩
      · refine ⟨(1 ⊗ₜ Ideal.toCotangent I ⟨x, hx⟩, 0), ?_⟩
        rw [degreeZeroHom_apply, degZeroInl_tmul, map_zero, add_zero, one_smul]
      · refine ⟨(0, 1 ⊗ₜ Ideal.toCotangent I' ⟨x, hx⟩), ?_⟩
        rw [degreeZeroHom_apply, degZeroInr_tmul, map_zero, zero_add, one_smul]
    | zero =>
      intro h
      have h0 : (⟨0, h⟩ : (prodIdeal I I')) = 0 := rfl
      rw [h0, map_zero]
      exact Submodule.zero_mem _
    | add a b ha hb iha ihb =>
      intro hab
      have ha' : a ∈ prodIdeal I I' := mem_prodIdeal_of_mem_span I I' ha
      have hb' : b ∈ prodIdeal I I' := mem_prodIdeal_of_mem_span I I' hb
      have hsum : (⟨a + b, hab⟩ : (prodIdeal I I')) = ⟨a, ha'⟩ + ⟨b, hb'⟩ := rfl
      rw [hsum, map_add]
      exact Submodule.add_mem _ (iha ha') (ihb hb')
    | smul m a ha iha =>
      intro hma
      have ha' : a ∈ prodIdeal I I' := mem_prodIdeal_of_mem_span I I' ha
      have hsmul : (⟨m • a, hma⟩ : (prodIdeal I I')) = m • ⟨a, ha'⟩ := rfl
      rw [hsmul, map_smul, ← mk_smul_cotangent]
      exact Submodule.smul_mem _ _ (iha ha')
  refine key y ?_ hy
  rwa [prodIdeal_eq_span] at hy

/-- **The degree-zero comparison map is surjective.** -/
theorem degreeZeroHom_surjective : Function.Surjective (degreeZeroHom I I') := by
  intro c
  obtain ⟨y, rfl⟩ := Ideal.toCotangent_surjective _ c
  exact toCotangent_mem_range_degreeZeroHom I I' y.1 y.2


/-! ## The retraction of the degree-zero comparison map -/

/-- Over a field every submodule is complemented, so the inclusion `I ⊆ k[x_σ]` of `k`-vector
spaces has a `k`-linear left inverse.  This is the only place where the hypothesis that `k`
is a field is used. -/
theorem exists_idealProj :
    ∃ g : MvPolynomial σ k →ₗ[k] I, ∀ x : I, g (x : MvPolynomial σ k) = x := by
  obtain ⟨g, hg⟩ := LinearMap.exists_leftInverse_of_injective
    ((Submodule.subtype I).restrictScalars k)
    (by rw [LinearMap.ker_eq_bot]; exact Subtype.val_injective)
  exact ⟨g, fun x => LinearMap.congr_fun hg x⟩

/-- A `k`-linear projection `k[x_σ] → I` which is the identity on `I`. -/
noncomputable def idealProj : MvPolynomial σ k →ₗ[k] I := (exists_idealProj I).choose

/-- `idealProj` is the identity on `I`. -/
@[simp]
theorem idealProj_coe (x : I) : idealProj I (x : MvPolynomial σ k) = x :=
  (exists_idealProj I).choose_spec x

/-- Scalars from `k` pass through `1 ⊗ -` in `(k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I²`. -/
theorem one_tmul_smul_k (a : k) (c : I.Cotangent) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] (a • c) =
      a • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] c) := by
  have h1 : a • c = (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I)
      (algebraMap k (MvPolynomial σ k) a)) • c := by
    rw [algebraMap_smul, algebraMap_smul]
  have h2 : algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I)
      (algebraMap k (MvPolynomial σ k) a) • (1 : prodQuot I I') =
      algebraMap k (prodQuot I I') a := by
    rw [Algebra.smul_def, mul_one]
    change Ideal.Quotient.mk (prodIdeal I I')
      (inlHom k σ τ (algebraMap k (MvPolynomial σ k) a)) = _
    rw [(inlHom k σ τ).commutes a,
      IsScalarTower.algebraMap_apply k (MvPolynomial (σ ⊕ τ) k) (prodQuot I I')]
    rfl
  have h3 : a • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] c) =
      (a • (1 : prodQuot I I')) ⊗ₜ[MvPolynomial σ k ⧸ I] c :=
    (TensorProduct.smul_tmul' a 1 c).symm
  rw [h1, ← TensorProduct.smul_tmul, h2, h3, Algebra.algebraMap_eq_smul_one]


/-- Scalars from `k` pass through the quotient map `k[x_{σ ⊕ τ}] → k[x_{σ ⊕ τ}]/J`. -/
theorem mk_smul_k (a : k) (m : MvPolynomial (σ ⊕ τ) k) :
    Ideal.Quotient.mk (prodIdeal I I') (a • m) = a • Ideal.Quotient.mk (prodIdeal I I') m := by
  have h : Ideal.Quotient.mk (prodIdeal I I') (algebraMap k (MvPolynomial (σ ⊕ τ) k) a) =
      algebraMap k (prodQuot I I') a :=
    (IsScalarTower.algebraMap_apply k (MvPolynomial (σ ⊕ τ) k) (prodQuot I I') a).symm
  rw [Algebra.smul_def, map_mul, h, ← Algebra.smul_def]

/-- The `k`-linear map `k[x_σ] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I²`, `p ↦ 1 ⊗ [π p]`. -/
noncomputable def psiLeft :
    MvPolynomial σ k →ₗ[k] (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) where
  toFun p := (1 : prodQuot I I') ⊗ₜ Ideal.toCotangent I (idealProj I p)
  map_add' p q := by
    simp only [map_add, TensorProduct.tmul_add]
  map_smul' a p := by
    simp only [RingHom.id_apply, map_smul, LinearMap.map_smul_of_tower, one_tmul_smul_k]

/-- `psiLeft` unfolded. -/
theorem psiLeft_apply (p : MvPolynomial σ k) :
    psiLeft I I' p = (1 : prodQuot I I') ⊗ₜ Ideal.toCotangent I (idealProj I p) :=
  rfl

/-- The `k`-bilinear map used to build the retraction onto the first summand. -/
noncomputable def psiBilin :
    MvPolynomial σ k →ₗ[k] MvPolynomial τ k →ₗ[k]
      (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :=
  LinearMap.mk₂ k
    (fun p q => Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) • psiLeft I I' p)
    (fun _ _ _ => by rw [map_add, smul_add])
    (fun a p q => by rw [map_smul, smul_comm])
    (fun _ _ _ => by rw [map_add, map_add, add_smul])
    (fun a p q => by rw [map_smul, mk_smul_k, smul_assoc])

/-- The `k`-linear retraction `k[x_σ] ⊗_k k[x_τ] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I²`. -/
noncomputable def psiTensor :
    MvPolynomial σ k ⊗[k] MvPolynomial τ k →ₗ[k]
      (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :=
  TensorProduct.lift (psiBilin I I')

/-- The `k`-linear retraction `k[x_{σ ⊕ τ}] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I²`. -/
noncomputable def psi :
    MvPolynomial (σ ⊕ τ) k →ₗ[k] (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :=
  (psiTensor I I').comp (toTensor k σ τ).toLinearMap

/-- The retraction on a product of a polynomial in the first block and one in the second. -/
theorem psi_inlHom_mul_inrHom (p : MvPolynomial σ k) (q : MvPolynomial τ k) :
    psi I I' (inlHom k σ τ p * inrHom k σ τ q) =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) • psiLeft I I' p := by
  have h : toTensor k σ τ (inlHom k σ τ p * inrHom k σ τ q) = p ⊗ₜ[k] q := by
    rw [map_mul, toTensor_inlHom, toTensor_inrHom, Algebra.TensorProduct.tmul_mul_tmul,
      mul_one, one_mul]
  change (psiTensor I I') (toTensor k σ τ (inlHom k σ τ p * inrHom k σ τ q)) = _
  rw [h]
  rfl


/-- Moving a polynomial coefficient out of `1 ⊗ [p · x]`. -/
theorem one_tmul_toCotangent_mul (p : MvPolynomial σ k) (x : I) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I]
        Ideal.toCotangent I ⟨p * (x : MvPolynomial σ k), I.mul_mem_left p x.2⟩ =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) := by
  have e1 : Ideal.toCotangent I ⟨p * (x : MvPolynomial σ k), I.mul_mem_left p x.2⟩ =
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) • Ideal.toCotangent I x := by
    have h1 : (⟨p * (x : MvPolynomial σ k), I.mul_mem_left p x.2⟩ : I) = p • x := rfl
    rw [h1, map_smul]
    exact (algebraMap_smul (MvPolynomial σ k ⧸ I) p (Ideal.toCotangent I x)).symm
  have e2 : (1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I]
        ((algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) • Ideal.toCotangent I x) =
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) := by
    exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)
  have e3 : (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) := by
    exact (algebraMap_smul (prodQuot I I')
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) _).symm
  rw [e1, e2, e3]

/-- **The retraction property for the first summand.**  On `m · ι x` with `x ∈ I` the
retraction returns `[m] · (1 ⊗ [x])`. -/
theorem psi_mul_inlHom (m : MvPolynomial (σ ⊕ τ) k) (x : I) :
    psi I I' (m * inlHom k σ τ (x : MvPolynomial σ k)) =
      Ideal.Quotient.mk (prodIdeal I I') m •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) := by
  obtain ⟨z, rfl⟩ := ofTensor_surjective k σ τ m
  induction z using TensorProduct.induction_on with
  | zero =>
    have hz0 : (0 : prodQuot I I') •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) = 0 := by
      exact zero_smul (prodQuot I I')
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x)
    simp only [map_zero, zero_mul]
    exact hz0.symm
  | tmul p q =>
    have hrw : inlHom k σ τ p * inrHom k σ τ q * inlHom k σ τ (x : MvPolynomial σ k) =
        inlHom k σ τ (p * (x : MvPolynomial σ k)) * inrHom k σ τ q := by
      rw [map_mul]; ring
    rw [ofTensor_tmul, hrw, psi_inlHom_mul_inrHom, psiLeft_apply]
    have hproj : idealProj I (p * (x : MvPolynomial σ k)) =
        ⟨p * (x : MvPolynomial σ k), I.mul_mem_left p x.2⟩ :=
      idealProj_coe I ⟨p * (x : MvPolynomial σ k), I.mul_mem_left p x.2⟩
    rw [hproj, one_tmul_toCotangent_mul, map_mul]
    have hs : Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
        (Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
          ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x)) =
        (Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) *
            Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p)) •
          ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x) := by
      exact (mul_smul (Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q))
        (Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p))
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] Ideal.toCotangent I x)).symm
    rw [hs, mul_comm]
  | add z w hz hw =>
    rw [map_add, add_mul, map_add, hz, hw, map_add, add_smul]

/-- **The retraction property for the first summand, second case.**  The retraction kills
`m · ι' x'` for `x' ∈ I'`. -/
theorem psi_mul_inrHom (m : MvPolynomial (σ ⊕ τ) k) (x : I') :
    psi I I' (m * inrHom k σ τ (x : MvPolynomial τ k)) = 0 := by
  obtain ⟨z, rfl⟩ := ofTensor_surjective k σ τ m
  induction z using TensorProduct.induction_on with
  | zero => simp
  | tmul p q =>
    have hrw : inlHom k σ τ p * inrHom k σ τ q * inrHom k σ τ (x : MvPolynomial τ k) =
        inlHom k σ τ p * inrHom k σ τ (q * (x : MvPolynomial τ k)) := by
      rw [map_mul]; ring
    rw [ofTensor_tmul, hrw, psi_inlHom_mul_inrHom, map_mul, map_mul,
      Ideal.Quotient.eq_zero_iff_mem.mpr (inrHom_mem_prodIdeal I I' x.2), mul_zero]
    exact zero_smul (prodQuot I I') (psiLeft I I' p)
  | add z w hz hw =>
    rw [map_add, add_mul, map_add, hz, hw, add_zero]


/-- `zero_smul` restated for the base-changed conormal module (the scalar action there is
`TensorProduct.leftHasSMul`, which generic `smul` lemmas do not match syntactically). -/
theorem zero_smul_bc (v : prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :
    (0 : prodQuot I I') • v = 0 := by
  exact zero_smul (prodQuot I I') v

/-- The scalar action of a class of a polynomial on a pure tensor. -/
theorem smul_one_tmul_bc (t : prodQuot I I') (c : I.Cotangent) :
    t • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] c) = t ⊗ₜ[MvPolynomial σ k ⧸ I] c :=
  (TensorProduct.smul_tmul' t (1 : prodQuot I I') c).symm.trans
    (congrArg (fun u => u ⊗ₜ[MvPolynomial σ k ⧸ I] c) (mul_one t))

/-- **The retraction kills `J · J`.** -/
theorem psi_mul_mem_mem (m : MvPolynomial (σ ⊕ τ) k) (hm : m ∈ prodIdeal I I')
    (y : MvPolynomial (σ ⊕ τ) k) (hy : y ∈ prodIdeal I I') : psi I I' (m * y) = 0 := by
  have key : ∀ z ∈ Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I'),
      ∀ w ∈ prodIdeal I I', psi I I' (z * w) = 0 := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
      intro w hw
      rcases hu with ⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩
      · rw [mul_comm, psi_mul_inlHom I I' w ⟨x, hx⟩,
          Ideal.Quotient.eq_zero_iff_mem.mpr hw, zero_smul_bc]
      · rw [mul_comm]
        exact psi_mul_inrHom I I' w ⟨x, hx⟩
    | zero => intro w _; rw [zero_mul, map_zero]
    | add a b _ _ iha ihb =>
      intro w hw
      rw [add_mul, map_add, iha w hw, ihb w hw, add_zero]
    | smul c a _ iha =>
      intro w hw
      have hcomm : c • a * w = a * (c * w) := by rw [smul_eq_mul]; ring
      rw [hcomm]
      exact iha (c * w) (Ideal.mul_mem_left _ c hw)
  refine key m ?_ y hy
  rwa [prodIdeal_eq_span] at hm

/-- The `k`-linear retraction `J/J² → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_σ]/I} I/I²`. -/
noncomputable def retractInl :
    (prodIdeal I I').Cotangent →ₗ[k] (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :=
  Ideal.Cotangent.lift
    ((psi I I').comp ((Submodule.subtype (prodIdeal I I')).restrictScalars k))
    fun x y => psi_mul_mem_mem I I' x.1 x.2 y.1 y.2

/-- `retractInl` on a generator. -/
@[simp]
theorem retractInl_toCotangent (y : prodIdeal I I') :
    retractInl I I' (Ideal.toCotangent (prodIdeal I I') y) =
      psi I I' (y : MvPolynomial (σ ⊕ τ) k) :=
  Ideal.Cotangent.lift_toCotangent _ _ y

/-- The class of `m · ι x` in `J/J²`. -/
theorem toCotangent_mul_inlHom (m : MvPolynomial (σ ⊕ τ) k) (x : I) :
    Ideal.toCotangent (prodIdeal I I')
        ⟨m * inlHom k σ τ (x : MvPolynomial σ k),
          Ideal.mul_mem_left _ m (inlHom_mem_prodIdeal I I' x.2)⟩ =
      Ideal.Quotient.mk (prodIdeal I I') m •
        Ideal.toCotangent (prodIdeal I I')
          ⟨inlHom k σ τ (x : MvPolynomial σ k), inlHom_mem_prodIdeal I I' x.2⟩ := by
  have h : (⟨m * inlHom k σ τ (x : MvPolynomial σ k),
        Ideal.mul_mem_left _ m (inlHom_mem_prodIdeal I I' x.2)⟩ : prodIdeal I I') =
      m • ⟨inlHom k σ τ (x : MvPolynomial σ k), inlHom_mem_prodIdeal I I' x.2⟩ := rfl
  rw [h, map_smul, ← mk_smul_cotangent]

/-- The class of `m · ι' x'` in `J/J²`. -/
theorem toCotangent_mul_inrHom (m : MvPolynomial (σ ⊕ τ) k) (x : I') :
    Ideal.toCotangent (prodIdeal I I')
        ⟨m * inrHom k σ τ (x : MvPolynomial τ k),
          Ideal.mul_mem_left _ m (inrHom_mem_prodIdeal I I' x.2)⟩ =
      Ideal.Quotient.mk (prodIdeal I I') m •
        Ideal.toCotangent (prodIdeal I I')
          ⟨inrHom k σ τ (x : MvPolynomial τ k), inrHom_mem_prodIdeal I I' x.2⟩ := by
  have h : (⟨m * inrHom k σ τ (x : MvPolynomial τ k),
        Ideal.mul_mem_left _ m (inrHom_mem_prodIdeal I I' x.2)⟩ : prodIdeal I I') =
      m • ⟨inrHom k σ τ (x : MvPolynomial τ k), inrHom_mem_prodIdeal I I' x.2⟩ := rfl
  rw [h, map_smul, ← mk_smul_cotangent]

/-- **`retractInl` is a left inverse of the first component of `degreeZeroHom`.** -/
theorem retractInl_degZeroInl (w : prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :
    retractInl I I' (degZeroInl I I' w) = w := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I c
    rw [degZeroInl_tmul, ← toCotangent_mul_inlHom, retractInl_toCotangent]
    exact (psi_mul_inlHom I I' m x).trans (smul_one_tmul_bc I I' _ _)
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- **`retractInl` kills the second component of `degreeZeroHom`.** -/
theorem retractInl_degZeroInr (w : prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :
    retractInl I I' (degZeroInr I I' w) = 0 := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I' c
    rw [degZeroInr_tmul, ← toCotangent_mul_inrHom, retractInl_toCotangent]
    exact psi_mul_inrHom I I' m x
  | add a b ha hb => rw [map_add, map_add, ha, hb, add_zero]


/-! ### The retraction onto the second summand -/

/-- Scalars from `k` pass through `1 ⊗ -` in `(k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'²`. -/
theorem one_tmul_smul_k' (a : k) (c : I'.Cotangent) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] (a • c) =
      a • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] c) := by
  have h1 : a • c = (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I')
      (algebraMap k (MvPolynomial τ k) a)) • c := by
    rw [algebraMap_smul, algebraMap_smul]
  have h2 : algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I')
      (algebraMap k (MvPolynomial τ k) a) • (1 : prodQuot I I') =
      algebraMap k (prodQuot I I') a := by
    rw [Algebra.smul_def, mul_one]
    change Ideal.Quotient.mk (prodIdeal I I')
      (inrHom k σ τ (algebraMap k (MvPolynomial τ k) a)) = _
    rw [(inrHom k σ τ).commutes a,
      IsScalarTower.algebraMap_apply k (MvPolynomial (σ ⊕ τ) k) (prodQuot I I')]
    rfl
  have h3 : a • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] c) =
      (a • (1 : prodQuot I I')) ⊗ₜ[MvPolynomial τ k ⧸ I'] c :=
    (TensorProduct.smul_tmul' a 1 c).symm
  rw [h1, ← TensorProduct.smul_tmul, h2, h3, Algebra.algebraMap_eq_smul_one]

/-- The `k`-linear map `k[x_τ] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'²`, `q ↦ 1 ⊗ [π' q]`. -/
noncomputable def psiRight :
    MvPolynomial τ k →ₗ[k] (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) where
  toFun q := (1 : prodQuot I I') ⊗ₜ Ideal.toCotangent I' (idealProj I' q)
  map_add' p q := by
    simp only [map_add, TensorProduct.tmul_add]
  map_smul' a p := by
    simp only [RingHom.id_apply, map_smul, LinearMap.map_smul_of_tower, one_tmul_smul_k']

/-- `psiRight` unfolded. -/
theorem psiRight_apply (q : MvPolynomial τ k) :
    psiRight I I' q = (1 : prodQuot I I') ⊗ₜ Ideal.toCotangent I' (idealProj I' q) :=
  rfl

/-- The `k`-bilinear map used to build the retraction onto the second summand. -/
noncomputable def psiBilin' :
    MvPolynomial σ k →ₗ[k] MvPolynomial τ k →ₗ[k]
      (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :=
  LinearMap.mk₂ k
    (fun p q => Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) • psiRight I I' q)
    (fun _ _ _ => by rw [map_add, map_add, add_smul])
    (fun a p q => by rw [map_smul, mk_smul_k, smul_assoc])
    (fun _ _ _ => by rw [map_add, smul_add])
    (fun a p q => by rw [map_smul, smul_comm])

/-- The `k`-linear retraction `k[x_σ] ⊗_k k[x_τ] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'²`. -/
noncomputable def psiTensor' :
    MvPolynomial σ k ⊗[k] MvPolynomial τ k →ₗ[k]
      (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :=
  TensorProduct.lift (psiBilin' I I')

/-- The `k`-linear retraction `k[x_{σ ⊕ τ}] → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'²`. -/
noncomputable def psi' :
    MvPolynomial (σ ⊕ τ) k →ₗ[k] (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :=
  (psiTensor' I I').comp (toTensor k σ τ).toLinearMap

/-- The second retraction on a product of a polynomial in the first block and one in the
second. -/
theorem psi'_inlHom_mul_inrHom (p : MvPolynomial σ k) (q : MvPolynomial τ k) :
    psi' I I' (inlHom k σ τ p * inrHom k σ τ q) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) • psiRight I I' q := by
  have h : toTensor k σ τ (inlHom k σ τ p * inrHom k σ τ q) = p ⊗ₜ[k] q := by
    rw [map_mul, toTensor_inlHom, toTensor_inrHom, Algebra.TensorProduct.tmul_mul_tmul,
      mul_one, one_mul]
  change (psiTensor' I I') (toTensor k σ τ (inlHom k σ τ p * inrHom k σ τ q)) = _
  rw [h]
  rfl

/-- Moving a polynomial coefficient out of `1 ⊗ [q · x']`. -/
theorem one_tmul_toCotangent_mul' (q : MvPolynomial τ k) (x : I') :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I']
        Ideal.toCotangent I' ⟨q * (x : MvPolynomial τ k), I'.mul_mem_left q x.2⟩ =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) := by
  have e1 : Ideal.toCotangent I' ⟨q * (x : MvPolynomial τ k), I'.mul_mem_left q x.2⟩ =
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) • Ideal.toCotangent I' x := by
    have h1 : (⟨q * (x : MvPolynomial τ k), I'.mul_mem_left q x.2⟩ : I') = q • x := rfl
    rw [h1, map_smul]
    exact (algebraMap_smul (MvPolynomial τ k ⧸ I') q (Ideal.toCotangent I' x)).symm
  have e2 : (1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I']
        ((algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) • Ideal.toCotangent I' x) =
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) := by
    exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)
  have e3 : (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) := by
    exact (algebraMap_smul (prodQuot I I')
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) _).symm
  rw [e1, e2, e3]

/-- **The retraction property for the second summand.** -/
theorem psi'_mul_inrHom (m : MvPolynomial (σ ⊕ τ) k) (x : I') :
    psi' I I' (m * inrHom k σ τ (x : MvPolynomial τ k)) =
      Ideal.Quotient.mk (prodIdeal I I') m •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) := by
  obtain ⟨z, rfl⟩ := ofTensor_surjective k σ τ m
  induction z using TensorProduct.induction_on with
  | zero =>
    have hz0 : (0 : prodQuot I I') •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) = 0 := by
      exact zero_smul (prodQuot I I')
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x)
    simp only [map_zero, zero_mul]
    exact hz0.symm
  | tmul p q =>
    have hrw : inlHom k σ τ p * inrHom k σ τ q * inrHom k σ τ (x : MvPolynomial τ k) =
        inlHom k σ τ p * inrHom k σ τ (q * (x : MvPolynomial τ k)) := by
      rw [map_mul]; ring
    rw [ofTensor_tmul, hrw, psi'_inlHom_mul_inrHom, psiRight_apply]
    have hproj : idealProj I' (q * (x : MvPolynomial τ k)) =
        ⟨q * (x : MvPolynomial τ k), I'.mul_mem_left q x.2⟩ :=
      idealProj_coe I' ⟨q * (x : MvPolynomial τ k), I'.mul_mem_left q x.2⟩
    rw [hproj, one_tmul_toCotangent_mul']
    have hs : Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
        (Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
          ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x)) =
        (Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) *
            Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q)) •
          ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x) := by
      exact (mul_smul (Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p))
        (Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q))
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] Ideal.toCotangent I' x)).symm
    rw [hs, map_mul]
  | add z w hz hw =>
    rw [map_add, add_mul, map_add, hz, hw, map_add, add_smul]

/-- **The retraction property for the second summand, second case.** -/
theorem psi'_mul_inlHom (m : MvPolynomial (σ ⊕ τ) k) (x : I) :
    psi' I I' (m * inlHom k σ τ (x : MvPolynomial σ k)) = 0 := by
  obtain ⟨z, rfl⟩ := ofTensor_surjective k σ τ m
  induction z using TensorProduct.induction_on with
  | zero => simp
  | tmul p q =>
    have hrw : inlHom k σ τ p * inrHom k σ τ q * inlHom k σ τ (x : MvPolynomial σ k) =
        inlHom k σ τ (p * (x : MvPolynomial σ k)) * inrHom k σ τ q := by
      rw [map_mul]; ring
    rw [ofTensor_tmul, hrw, psi'_inlHom_mul_inrHom, map_mul, map_mul,
      Ideal.Quotient.eq_zero_iff_mem.mpr (inlHom_mem_prodIdeal I I' x.2), mul_zero]
    exact zero_smul (prodQuot I I') (psiRight I I' q)
  | add z w hz hw =>
    rw [map_add, add_mul, map_add, hz, hw, add_zero]

/-- `zero_smul` restated for the second base-changed conormal module. -/
theorem zero_smul_bc' (v : prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :
    (0 : prodQuot I I') • v = 0 := by
  exact zero_smul (prodQuot I I') v

/-- The scalar action of a class of a polynomial on a pure tensor, second summand. -/
theorem smul_one_tmul_bc' (t : prodQuot I I') (c : I'.Cotangent) :
    t • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] c) = t ⊗ₜ[MvPolynomial τ k ⧸ I'] c :=
  (TensorProduct.smul_tmul' t (1 : prodQuot I I') c).symm.trans
    (congrArg (fun u => u ⊗ₜ[MvPolynomial τ k ⧸ I'] c) (mul_one t))

/-- **The second retraction kills `J · J`.** -/
theorem psi'_mul_mem_mem (m : MvPolynomial (σ ⊕ τ) k) (hm : m ∈ prodIdeal I I')
    (y : MvPolynomial (σ ⊕ τ) k) (hy : y ∈ prodIdeal I I') : psi' I I' (m * y) = 0 := by
  have key : ∀ z ∈ Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I'),
      ∀ w ∈ prodIdeal I I', psi' I I' (z * w) = 0 := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
      intro w hw
      rcases hu with ⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩
      · rw [mul_comm]
        exact psi'_mul_inlHom I I' w ⟨x, hx⟩
      · rw [mul_comm, psi'_mul_inrHom I I' w ⟨x, hx⟩,
          Ideal.Quotient.eq_zero_iff_mem.mpr hw, zero_smul_bc']
    | zero => intro w _; rw [zero_mul, map_zero]
    | add a b _ _ iha ihb =>
      intro w hw
      rw [add_mul, map_add, iha w hw, ihb w hw, add_zero]
    | smul c a _ iha =>
      intro w hw
      have hcomm : c • a * w = a * (c * w) := by rw [smul_eq_mul]; ring
      rw [hcomm]
      exact iha (c * w) (Ideal.mul_mem_left _ c hw)
  refine key m ?_ y hy
  rwa [prodIdeal_eq_span] at hm

/-- The `k`-linear retraction `J/J² → (k[x_{σ ⊕ τ}]/J) ⊗_{k[x_τ]/I'} I'/I'²`. -/
noncomputable def retractInr :
    (prodIdeal I I').Cotangent →ₗ[k] (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :=
  Ideal.Cotangent.lift
    ((psi' I I').comp ((Submodule.subtype (prodIdeal I I')).restrictScalars k))
    fun x y => psi'_mul_mem_mem I I' x.1 x.2 y.1 y.2

/-- `retractInr` on a generator. -/
@[simp]
theorem retractInr_toCotangent (y : prodIdeal I I') :
    retractInr I I' (Ideal.toCotangent (prodIdeal I I') y) =
      psi' I I' (y : MvPolynomial (σ ⊕ τ) k) :=
  Ideal.Cotangent.lift_toCotangent _ _ y

/-- **`retractInr` is a left inverse of the second component of `degreeZeroHom`.** -/
theorem retractInr_degZeroInr (w : prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :
    retractInr I I' (degZeroInr I I' w) = w := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I' c
    rw [degZeroInr_tmul, ← toCotangent_mul_inrHom, retractInr_toCotangent]
    exact (psi'_mul_inrHom I I' m x).trans (smul_one_tmul_bc' I I' _ _)
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- **`retractInr` kills the first component of `degreeZeroHom`.** -/
theorem retractInr_degZeroInl (w : prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :
    retractInr I I' (degZeroInl I I' w) = 0 := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I c
    rw [degZeroInl_tmul, ← toCotangent_mul_inlHom, retractInr_toCotangent]
    exact psi'_mul_inlHom I I' m x
  | add a b ha hb => rw [map_add, map_add, ha, hb, add_zero]

/-- **The degree-zero comparison map is injective.** -/
theorem degreeZeroHom_injective : Function.Injective (degreeZeroHom I I') := by
  rw [injective_iff_map_eq_zero]
  rintro ⟨w, w'⟩ h
  rw [degreeZeroHom_apply] at h
  have h1 : retractInl I I' (degZeroInl I I' w + degZeroInr I I' w') = 0 := by
    rw [h, map_zero]
  have h2 : retractInr I I' (degZeroInl I I' w + degZeroInr I I' w') = 0 := by
    rw [h, map_zero]
  rw [map_add, retractInl_degZeroInl, retractInl_degZeroInr, add_zero] at h1
  rw [map_add, retractInr_degZeroInl, retractInr_degZeroInr, zero_add] at h2
  rw [Prod.mk_eq_zero]
  exact ⟨h1, h2⟩

/-- **The conormal module of the product ideal is the external sum of the two conormal
modules.**  This is the degree-zero half of the comparison of `conormalComplex k k[x_{σ ⊕ τ}] J`
with the external sum of `conormalComplex k k[x_σ] I` and `conormalComplex k k[x_τ] I'`. -/
noncomputable def degreeZeroEquiv :
    ((prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) ×
        (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent)) ≃ₗ[prodQuot I I']
      (prodIdeal I I').Cotangent :=
  LinearEquiv.ofBijective (degreeZeroHom I I')
    ⟨degreeZeroHom_injective I I', degreeZeroHom_surjective I I'⟩

/-! ## The degree-one comparison: Kähler differentials of `k[x_{σ ⊕ τ}]` -/

/-- The degree-one term of the first summand of the external sum. -/
abbrev degOneL : Type u :=
  prodQuot I I' ⊗[MvPolynomial σ k ⧸ I]
    ((MvPolynomial σ k ⧸ I) ⊗[MvPolynomial σ k] Ω[MvPolynomial σ k⁄k])

/-- The degree-one term of the second summand of the external sum. -/
abbrev degOneR : Type u :=
  prodQuot I I' ⊗[MvPolynomial τ k ⧸ I']
    ((MvPolynomial τ k ⧸ I') ⊗[MvPolynomial τ k] Ω[MvPolynomial τ k⁄k])

/-- The degree-one term of the conormal complex of the product. -/
abbrev degOneP : Type u :=
  prodQuot I I' ⊗[MvPolynomial (σ ⊕ τ) k] Ω[MvPolynomial (σ ⊕ τ) k⁄k]

/-- The basis of `degOneL` indexed by the first block of variables. -/
noncomputable def basisL : Module.Basis σ (prodQuot I I') (degOneL I I') :=
  ((KaehlerDifferential.mvPolynomialBasis k σ).baseChange
    (MvPolynomial σ k ⧸ I)).baseChange (prodQuot I I')

/-- The basis of `degOneR` indexed by the second block of variables. -/
noncomputable def basisR : Module.Basis τ (prodQuot I I') (degOneR I I') :=
  ((KaehlerDifferential.mvPolynomialBasis k τ).baseChange
    (MvPolynomial τ k ⧸ I')).baseChange (prodQuot I I')

/-- The basis of `degOneP` indexed by all the variables. -/
noncomputable def basisP : Module.Basis (σ ⊕ τ) (prodQuot I I') (degOneP I I') :=
  (KaehlerDifferential.mvPolynomialBasis k (σ ⊕ τ)).baseChange (prodQuot I I')

/-- The basis of the degree-one term of the external sum. -/
noncomputable def basisSum :
    Module.Basis (σ ⊕ τ) (prodQuot I I') (degOneL I I' × degOneR I I') :=
  (basisL I I').prod (basisR I I')

/-- `basisL` on a basis index. -/
theorem basisL_apply (i : σ) :
    basisL I I' i = (1 : prodQuot I I') ⊗ₜ ((1 : MvPolynomial σ k ⧸ I) ⊗ₜ
      KaehlerDifferential.D k (MvPolynomial σ k) (MvPolynomial.X i)) := by
  rw [basisL, Module.Basis.baseChange_apply, Module.Basis.baseChange_apply,
    KaehlerDifferential.mvPolynomialBasis_apply]

/-- `basisR` on a basis index. -/
theorem basisR_apply (j : τ) :
    basisR I I' j = (1 : prodQuot I I') ⊗ₜ ((1 : MvPolynomial τ k ⧸ I') ⊗ₜ
      KaehlerDifferential.D k (MvPolynomial τ k) (MvPolynomial.X j)) := by
  rw [basisR, Module.Basis.baseChange_apply, Module.Basis.baseChange_apply,
    KaehlerDifferential.mvPolynomialBasis_apply]

/-- `basisP` on a basis index. -/
theorem basisP_apply (i : σ ⊕ τ) :
    basisP I I' i = (1 : prodQuot I I') ⊗ₜ
      KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (MvPolynomial.X i) := by
  rw [basisP, Module.Basis.baseChange_apply, KaehlerDifferential.mvPolynomialBasis_apply]

/-- **The degree-one comparison equivalence.**  Both sides are free over `k[x_{σ ⊕ τ}]/J` with
bases indexed by `σ ⊕ τ`, given by the classes of `dX_i`. -/
noncomputable def degreeOneEquiv :
    (degOneL I I' × degOneR I I') ≃ₗ[prodQuot I I'] degOneP I I' :=
  (basisSum I I').equiv (basisP I I') (Equiv.refl (σ ⊕ τ))

/-- `degreeOneEquiv` sends `dX_i ⊞ 0` to `dX_{inl i}`. -/
theorem degreeOneEquiv_inl_X (i : σ) :
    degreeOneEquiv I I' (basisL I I' i, 0) = (1 : prodQuot I I') ⊗ₜ
      KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (MvPolynomial.X (Sum.inl i)) := by
  have h : (basisL I I' i, (0 : degOneR I I')) = basisSum I I' (Sum.inl i) :=
    Prod.ext ((basisL I I').prod_apply_inl_fst (basisR I I') i).symm
      ((basisL I I').prod_apply_inl_snd (basisR I I') i).symm
  rw [h, degreeOneEquiv, Module.Basis.equiv_apply, Equiv.refl_apply, basisP_apply]

/-- `degreeOneEquiv` sends `0 ⊞ dX_j` to `dX_{inr j}`. -/
theorem degreeOneEquiv_inr_X (j : τ) :
    degreeOneEquiv I I' (0, basisR I I' j) = (1 : prodQuot I I') ⊗ₜ
      KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (MvPolynomial.X (Sum.inr j)) := by
  have h : ((0 : degOneL I I'), basisR I I' j) = basisSum I I' (Sum.inr j) :=
    Prod.ext ((basisL I I').prod_apply_inr_fst (basisR I I') j).symm
      ((basisL I I').prod_apply_inr_snd (basisR I I') j).symm
  rw [h, degreeOneEquiv, Module.Basis.equiv_apply, Equiv.refl_apply, basisP_apply]


/-! ### Compatibility of the degree-one comparison with the universal derivation -/

/-- Moving an `S`-scalar which is the class of `p` through `1 ⊗ -` turns it into the class of
`ι p` in `k[x_{σ ⊕ τ}]/J`. -/
theorem one_tmul_smul_left {N : Type u} [AddCommGroup N] [Module (MvPolynomial σ k ⧸ I) N]
    (p : MvPolynomial σ k) (v : N) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I]
        ((algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) • v) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] v) := by
  have e2 : (1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I]
      ((algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) • v) =
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] v) := by
    exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)
  have e3 : (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) •
      ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] v) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] v) := by
    exact (algebraMap_smul (prodQuot I I')
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) _).symm
  rw [e2, e3]

/-- The second-summand analogue of `one_tmul_smul_left`. -/
theorem one_tmul_smul_right {N : Type u} [AddCommGroup N] [Module (MvPolynomial τ k ⧸ I') N]
    (q : MvPolynomial τ k) (v : N) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I']
        ((algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) • v) =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] v) := by
  have e2 : (1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I']
      ((algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) • v) =
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] v) := by
    exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)
  have e3 : (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) •
      ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] v) =
      Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] v) := by
    exact (algebraMap_smul (prodQuot I I')
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) _).symm
  rw [e2, e3]

/-- Moving a polynomial scalar through `1 ⊗ -` over the ambient ring `k[x_{σ ⊕ τ}]`. -/
theorem one_tmul_smul_prod {N : Type u} [AddCommGroup N]
    [Module (MvPolynomial (σ ⊕ τ) k) N] (m : MvPolynomial (σ ⊕ τ) k) (v : N) :
    (1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] (m • v) =
      Ideal.Quotient.mk (prodIdeal I I') m •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] v) := by
  have e2 : (1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] (m • v) =
      m • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] v) := by
    exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)
  have e3 : m • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] v) =
      Ideal.Quotient.mk (prodIdeal I I') m •
        ((1 : prodQuot I I') ⊗ₜ[MvPolynomial (σ ⊕ τ) k] v) := by
    exact (algebraMap_smul (prodQuot I I') m _).symm
  rw [e2, e3]

/-- Moving a polynomial scalar out of the inner tensor factor of `degOneL`. -/
theorem one_tmul_smul_kaehlerL (p : MvPolynomial σ k) (ω : Ω[MvPolynomial σ k⁄k]) :
    (1 : MvPolynomial σ k ⧸ I) ⊗ₜ[MvPolynomial σ k] (p • ω) =
      (algebraMap (MvPolynomial σ k) (MvPolynomial σ k ⧸ I) p) •
        ((1 : MvPolynomial σ k ⧸ I) ⊗ₜ[MvPolynomial σ k] ω) := by
  exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)

/-- Moving a polynomial scalar out of the inner tensor factor of `degOneR`. -/
theorem one_tmul_smul_kaehlerR (q : MvPolynomial τ k) (ω : Ω[MvPolynomial τ k⁄k]) :
    (1 : MvPolynomial τ k ⧸ I') ⊗ₜ[MvPolynomial τ k] (q • ω) =
      (algebraMap (MvPolynomial τ k) (MvPolynomial τ k ⧸ I') q) •
        ((1 : MvPolynomial τ k ⧸ I') ⊗ₜ[MvPolynomial τ k] ω) := by
  exact (TensorProduct.smul_tmul _ _ _).symm.trans (TensorProduct.smul_tmul' _ _ _)

/-- Shorthand for `1 ⊗ (1 ⊗ ω)` in the degree-one term of the first summand. -/
noncomputable abbrev tL (ω : Ω[MvPolynomial σ k⁄k]) : degOneL I I' :=
  (1 : prodQuot I I') ⊗ₜ ((1 : MvPolynomial σ k ⧸ I) ⊗ₜ ω)

/-- Shorthand for `1 ⊗ (1 ⊗ ω)` in the degree-one term of the second summand. -/
noncomputable abbrev tR (ω : Ω[MvPolynomial τ k⁄k]) : degOneR I I' :=
  (1 : prodQuot I I') ⊗ₜ ((1 : MvPolynomial τ k ⧸ I') ⊗ₜ ω)

/-- Shorthand for `1 ⊗ ω` in the degree-one term of the conormal complex of the product. -/
noncomputable abbrev tP (ω : Ω[MvPolynomial (σ ⊕ τ) k⁄k]) : degOneP I I' :=
  (1 : prodQuot I I') ⊗ₜ ω

/-- `tL` is additive. -/
theorem tL_add (ω₁ ω₂ : Ω[MvPolynomial σ k⁄k]) :
    tL I I' (ω₁ + ω₂) = tL I I' ω₁ + tL I I' ω₂ := by
  rw [tL, TensorProduct.tmul_add, TensorProduct.tmul_add]

/-- `tR` is additive. -/
theorem tR_add (ω₁ ω₂ : Ω[MvPolynomial τ k⁄k]) :
    tR I I' (ω₁ + ω₂) = tR I I' ω₁ + tR I I' ω₂ := by
  rw [tR, TensorProduct.tmul_add, TensorProduct.tmul_add]

/-- `tP` is additive. -/
theorem tP_add (ω₁ ω₂ : Ω[MvPolynomial (σ ⊕ τ) k⁄k]) :
    tP I I' (ω₁ + ω₂) = tP I I' ω₁ + tP I I' ω₂ := by
  rw [tP, TensorProduct.tmul_add]

/-- Polynomial scalars pass through `tL` as classes in `k[x_{σ ⊕ τ}]/J`. -/
theorem tL_smul (p : MvPolynomial σ k) (ω : Ω[MvPolynomial σ k⁄k]) :
    tL I I' (p • ω) = Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p) • tL I I' ω := by
  rw [tL, tL, one_tmul_smul_kaehlerL, one_tmul_smul_left]

/-- Polynomial scalars pass through `tR` as classes in `k[x_{σ ⊕ τ}]/J`. -/
theorem tR_smul (q : MvPolynomial τ k) (ω : Ω[MvPolynomial τ k⁄k]) :
    tR I I' (q • ω) = Ideal.Quotient.mk (prodIdeal I I') (inrHom k σ τ q) • tR I I' ω := by
  rw [tR, tR, one_tmul_smul_kaehlerR, one_tmul_smul_right]

/-- Polynomial scalars pass through `tP` as classes in `k[x_{σ ⊕ τ}]/J`. -/
theorem tP_smul (m : MvPolynomial (σ ⊕ τ) k) (ω : Ω[MvPolynomial (σ ⊕ τ) k⁄k]) :
    tP I I' (m • ω) = Ideal.Quotient.mk (prodIdeal I I') m • tP I I' ω := by
  rw [tP, tP, one_tmul_smul_prod]

/-- The first component of the degree-one comparison. -/
noncomputable def degreeOneInl : degOneL I I' →ₗ[prodQuot I I'] degOneP I I' :=
  (degreeOneEquiv I I').toLinearMap.comp
    (LinearMap.inl (prodQuot I I') (degOneL I I') (degOneR I I'))

/-- The second component of the degree-one comparison. -/
noncomputable def degreeOneInr : degOneR I I' →ₗ[prodQuot I I'] degOneP I I' :=
  (degreeOneEquiv I I').toLinearMap.comp
    (LinearMap.inr (prodQuot I I') (degOneL I I') (degOneR I I'))

/-- `degreeOneEquiv` is the sum of its two components. -/
theorem degreeOneEquiv_apply (w : degOneL I I') (w' : degOneR I I') :
    degreeOneEquiv I I' (w, w') = degreeOneInl I I' w + degreeOneInr I I' w' := by
  have h : ((w, w') : degOneL I I' × degOneR I I') = (w, 0) + (0, w') := by simp
  rw [h, map_add]
  rfl

/-- `degreeOneInl` on the basis vector `dX_i`. -/
theorem degreeOneInl_X (i : σ) :
    degreeOneInl I I' (tL I I' (KaehlerDifferential.D k (MvPolynomial σ k) (MvPolynomial.X i))) =
      tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (MvPolynomial.X (Sum.inl i))) := by
  have h : tL I I' (KaehlerDifferential.D k (MvPolynomial σ k) (MvPolynomial.X i)) =
      basisL I I' i := (basisL_apply I I' i).symm
  rw [h]
  exact degreeOneEquiv_inl_X I I' i

/-- `degreeOneInr` on the basis vector `dX_j`. -/
theorem degreeOneInr_X (j : τ) :
    degreeOneInr I I' (tR I I' (KaehlerDifferential.D k (MvPolynomial τ k) (MvPolynomial.X j))) =
      tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (MvPolynomial.X (Sum.inr j))) := by
  have h : tR I I' (KaehlerDifferential.D k (MvPolynomial τ k) (MvPolynomial.X j)) =
      basisR I I' j := (basisR_apply I I' j).symm
  rw [h]
  exact degreeOneEquiv_inr_X I I' j

/-- The universal derivation of a polynomial ring kills constants. -/
theorem D_C_eq_zero {υ : Type u} (a : k) :
    KaehlerDifferential.D k (MvPolynomial υ k) (MvPolynomial.C a) = 0 := by
  have h : (MvPolynomial.C a : MvPolynomial υ k) = algebraMap k (MvPolynomial υ k) a := by
    simp [MvPolynomial.algebraMap_eq]
  rw [h, Derivation.map_algebraMap]

/-- **Compatibility of the first component of the degree-one comparison with the universal
derivation:** it sends the class of `dp` to the class of `d(ι p)`, for every polynomial `p`. -/
theorem degreeOneInl_D (p : MvPolynomial σ k) :
    degreeOneInl I I' (tL I I' (KaehlerDifferential.D k (MvPolynomial σ k) p)) =
      tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (inlHom k σ τ p)) := by
  induction p using MvPolynomial.induction_on with
  | C a =>
    rw [MvPolynomial.rename_C, D_C_eq_zero, D_C_eq_zero, tL, tP,
      TensorProduct.tmul_zero, TensorProduct.tmul_zero, map_zero, TensorProduct.tmul_zero]
  | add p q hp hq =>
    rw [map_add, tL_add, map_add, hp, hq, map_add, map_add, tP_add]
  | mul_X p i hp =>
    have hleib : KaehlerDifferential.D k (MvPolynomial σ k) (p * MvPolynomial.X i) =
        p • KaehlerDifferential.D k (MvPolynomial σ k) (MvPolynomial.X i) +
          MvPolynomial.X i • KaehlerDifferential.D k (MvPolynomial σ k) p :=
      Derivation.leibniz _ _ _
    have hren : inlHom k σ τ (p * MvPolynomial.X i) =
        inlHom k σ τ p * MvPolynomial.X (Sum.inl i) := by
      rw [map_mul, MvPolynomial.rename_X]
    have hleib' : KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
          (inlHom k σ τ p * MvPolynomial.X (Sum.inl i)) =
        inlHom k σ τ p • KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (MvPolynomial.X (Sum.inl i)) +
          MvPolynomial.X (Sum.inl i) • KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (inlHom k σ τ p) :=
      Derivation.leibniz _ _ _
    rw [hleib, tL_add, map_add, tL_smul, tL_smul, map_smul, map_smul, hp, degreeOneInl_X, hren,
      hleib', tP_add, tP_smul, tP_smul, MvPolynomial.rename_X]

/-- **Compatibility of the second component of the degree-one comparison with the universal
derivation.** -/
theorem degreeOneInr_D (q : MvPolynomial τ k) :
    degreeOneInr I I' (tR I I' (KaehlerDifferential.D k (MvPolynomial τ k) q)) =
      tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k) (inrHom k σ τ q)) := by
  induction q using MvPolynomial.induction_on with
  | C a =>
    rw [MvPolynomial.rename_C, D_C_eq_zero, D_C_eq_zero, tR, tP,
      TensorProduct.tmul_zero, TensorProduct.tmul_zero, map_zero, TensorProduct.tmul_zero]
  | add p q hp hq =>
    rw [map_add, tR_add, map_add, hp, hq, map_add, map_add, tP_add]
  | mul_X q j hq =>
    have hleib : KaehlerDifferential.D k (MvPolynomial τ k) (q * MvPolynomial.X j) =
        q • KaehlerDifferential.D k (MvPolynomial τ k) (MvPolynomial.X j) +
          MvPolynomial.X j • KaehlerDifferential.D k (MvPolynomial τ k) q :=
      Derivation.leibniz _ _ _
    have hren : inrHom k σ τ (q * MvPolynomial.X j) =
        inrHom k σ τ q * MvPolynomial.X (Sum.inr j) := by
      rw [map_mul, MvPolynomial.rename_X]
    have hleib' : KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
          (inrHom k σ τ q * MvPolynomial.X (Sum.inr j)) =
        inrHom k σ τ q • KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (MvPolynomial.X (Sum.inr j)) +
          MvPolynomial.X (Sum.inr j) • KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (inrHom k σ τ q) :=
      Derivation.leibniz _ _ _
    rw [hleib, tR_add, map_add, tR_smul, tR_smul, map_smul, map_smul, hq, degreeOneInr_X, hren,
      hleib', tP_add, tP_smul, tP_smul, MvPolynomial.rename_X]


/-! ## The isomorphism of two-term complexes -/

section ComplexComparison

open NormalSheafPicard.AffineIntrinsicNormalSheaf AffineNormalCone PicardCriteria

/-- `zero_smul` restated for the degree-one term of the conormal complex of the product. -/
theorem zero_smul_P (v : degOneP I I') : (0 : prodQuot I I') • v = 0 := by
  exact zero_smul (prodQuot I I') v

/-- A pure tensor as a scalar multiple of `1 ⊗ v`, first summand. -/
theorem smul_one_tmul_left {N : Type u} [AddCommGroup N] [Module (MvPolynomial σ k ⧸ I) N]
    (t : prodQuot I I') (v : N) :
    t • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial σ k ⧸ I] v) = t ⊗ₜ[MvPolynomial σ k ⧸ I] v :=
  (TensorProduct.smul_tmul' t (1 : prodQuot I I') v).symm.trans
    (congrArg (fun u => u ⊗ₜ[MvPolynomial σ k ⧸ I] v) (mul_one t))

/-- A pure tensor as a scalar multiple of `1 ⊗ v`, second summand. -/
theorem smul_one_tmul_right {N : Type u} [AddCommGroup N] [Module (MvPolynomial τ k ⧸ I') N]
    (t : prodQuot I I') (v : N) :
    t • ((1 : prodQuot I I') ⊗ₜ[MvPolynomial τ k ⧸ I'] v) = t ⊗ₜ[MvPolynomial τ k ⧸ I'] v :=
  (TensorProduct.smul_tmul' t (1 : prodQuot I I') v).symm.trans
    (congrArg (fun u => u ⊗ₜ[MvPolynomial τ k ⧸ I'] v) (mul_one t))

/-- **The comparison square for the first summand.** -/
theorem square_inl (w : prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) :
    degreeOneInl I I' (LinearMap.baseChange (prodQuot I I')
        (conormalMap k (MvPolynomial σ k) I) w) =
      conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I') (degZeroInl I I' w) := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero, map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I c
    have hL : LinearMap.baseChange (prodQuot I I') (conormalMap k (MvPolynomial σ k) I)
          (Ideal.Quotient.mk (prodIdeal I I') m ⊗ₜ Ideal.toCotangent I x) =
        Ideal.Quotient.mk (prodIdeal I I') m •
          tL I I' (KaehlerDifferential.D k (MvPolynomial σ k) (x : MvPolynomial σ k)) := by
      rw [LinearMap.baseChange_tmul, conormalMap_toCotangent, smul_one_tmul_left]
    have hR : conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I') (degZeroInl I I'
          (Ideal.Quotient.mk (prodIdeal I I') m ⊗ₜ Ideal.toCotangent I x)) =
        Ideal.Quotient.mk (prodIdeal I I') m •
          tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (inlHom k σ τ (x : MvPolynomial σ k))) := by
      rw [degZeroInl_tmul, ← toCotangent_mul_inlHom]
      have h0 : conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I')
            (Ideal.toCotangent (prodIdeal I I') ⟨m * inlHom k σ τ (x : MvPolynomial σ k),
              Ideal.mul_mem_left _ m (inlHom_mem_prodIdeal I I' x.2)⟩) =
          tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (m * inlHom k σ τ (x : MvPolynomial σ k))) := rfl
      rw [h0, Derivation.leibniz, tP_add, tP_smul, tP_smul,
        Ideal.Quotient.eq_zero_iff_mem.mpr (inlHom_mem_prodIdeal I I' x.2), zero_smul_P, add_zero]
    rw [hL, map_smul, degreeOneInl_D, hR]
  | add a b ha hb => rw [map_add, map_add, map_add, map_add, ha, hb]

/-- **The comparison square for the second summand.** -/
theorem square_inr (w : prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent) :
    degreeOneInr I I' (LinearMap.baseChange (prodQuot I I')
        (conormalMap k (MvPolynomial τ k) I') w) =
      conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I') (degZeroInr I I' w) := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero, map_zero, map_zero]
  | tmul t c =>
    obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective t
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective I' c
    have hL : LinearMap.baseChange (prodQuot I I') (conormalMap k (MvPolynomial τ k) I')
          (Ideal.Quotient.mk (prodIdeal I I') m ⊗ₜ Ideal.toCotangent I' x) =
        Ideal.Quotient.mk (prodIdeal I I') m •
          tR I I' (KaehlerDifferential.D k (MvPolynomial τ k) (x : MvPolynomial τ k)) := by
      rw [LinearMap.baseChange_tmul, conormalMap_toCotangent, smul_one_tmul_right]
    have hR : conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I') (degZeroInr I I'
          (Ideal.Quotient.mk (prodIdeal I I') m ⊗ₜ Ideal.toCotangent I' x)) =
        Ideal.Quotient.mk (prodIdeal I I') m •
          tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (inrHom k σ τ (x : MvPolynomial τ k))) := by
      rw [degZeroInr_tmul, ← toCotangent_mul_inrHom]
      have h0 : conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I')
            (Ideal.toCotangent (prodIdeal I I') ⟨m * inrHom k σ τ (x : MvPolynomial τ k),
              Ideal.mul_mem_left _ m (inrHom_mem_prodIdeal I I' x.2)⟩) =
          tP I I' (KaehlerDifferential.D k (MvPolynomial (σ ⊕ τ) k)
            (m * inrHom k σ τ (x : MvPolynomial τ k))) := rfl
      rw [h0, Derivation.leibniz, tP_add, tP_smul, tP_smul,
        Ideal.Quotient.eq_zero_iff_mem.mpr (inrHom_mem_prodIdeal I I' x.2), zero_smul_P, add_zero]
    rw [hL, map_smul, degreeOneInr_D, hR]
  | add a b ha hb => rw [map_add, map_add, map_add, map_add, ha, hb]

/-- **The external sum of the two conormal complexes**, over the coordinate ring of the
product: the affine model of `pr₁^* L_X ⊕ pr₂^* L_Y`. -/
noncomputable abbrev conormalSum : LinearTwoTermComplex (prodQuot I I') :=
  ((conormalComplex k (MvPolynomial σ k) I).baseChange (prodQuot I I')).sum
    ((conormalComplex k (MvPolynomial τ k) I').baseChange (prodQuot I I'))

/-- `degreeZeroEquiv` is `degreeZeroHom`. -/
theorem degreeZeroEquiv_apply (z : (prodQuot I I' ⊗[MvPolynomial σ k ⧸ I] I.Cotangent) ×
    (prodQuot I I' ⊗[MvPolynomial τ k ⧸ I'] I'.Cotangent)) :
    degreeZeroEquiv I I' z = degreeZeroHom I I' z :=
  rfl

/-- **The comparison chain map** from the external sum of the conormal complexes of the two
factors to the conormal complex of the product embedding. -/
noncomputable def conormalProdHom :
    LinearTwoTermComplex.Hom (conormalSum I I')
      (conormalComplex k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I')) where
  degreeZero := degreeZeroHom I I'
  degreeOne := (degreeOneEquiv I I').toLinearMap
  comm z := by
    obtain ⟨w, w'⟩ := z
    have h : (conormalSum I I').differential (w, w') =
        (LinearMap.baseChange (prodQuot I I') (conormalMap k (MvPolynomial σ k) I) w,
          LinearMap.baseChange (prodQuot I I') (conormalMap k (MvPolynomial τ k) I') w') := rfl
    change degreeOneEquiv I I' ((conormalSum I I').differential (w, w')) = _
    rw [h, degreeOneEquiv_apply, degreeZeroHom_apply, square_inl, square_inr, ← map_add]

/-- **The inverse comparison chain map.** -/
noncomputable def conormalProdInv :
    LinearTwoTermComplex.Hom (conormalComplex k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I'))
      (conormalSum I I') where
  degreeZero := (degreeZeroEquiv I I').symm.toLinearMap
  degreeOne := (degreeOneEquiv I I').symm.toLinearMap
  comm c := by
    have h := (conormalProdHom I I').comm ((degreeZeroEquiv I I').symm c)
    have h2 : degreeZeroHom I I' ((degreeZeroEquiv I I').symm c) = c :=
      (degreeZeroEquiv I I').apply_symm_apply c
    have h3 : (conormalProdHom I I').degreeZero ((degreeZeroEquiv I I').symm c) = c := h2
    rw [h3] at h
    change (degreeOneEquiv I I').symm (conormalMap k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I') c) =
      (conormalSum I I').differential ((degreeZeroEquiv I I').symm c)
    have h4 : ∀ u, (conormalProdHom I I').degreeOne u = degreeOneEquiv I I' u := fun _ => rfl
    rw [← h, h4, LinearEquiv.symm_apply_apply]

/-- **The conormal complex of a product embedding is isomorphic to the external sum of the
conormal complexes of the two factors.**  Both composites of `conormalProdHom` and
`conormalProdInv` are the identity, so the chain homotopies are zero. -/
noncomputable def conormalProdEquiv :
    LinearTwoTermComplex.HomotopyEquivalence (conormalSum I I')
      (conormalComplex k (MvPolynomial (σ ⊕ τ) k) (prodIdeal I I')) where
  hom := conormalProdHom I I'
  inv := conormalProdInv I I'
  unit :=
    { homotopy := 0
      degreeZero := fun x => by
        change (degreeZeroEquiv I I').symm (degreeZeroHom I I' x) = x + 0
        rw [add_zero, ← degreeZeroEquiv_apply, LinearEquiv.symm_apply_apply]
      degreeOne := fun x => by
        change (degreeOneEquiv I I').symm (degreeOneEquiv I I' x) = x + _
        rw [LinearEquiv.symm_apply_apply, LinearMap.zero_apply, map_zero, add_zero] }
  counit :=
    { homotopy := 0
      degreeZero := fun x => by
        change x = degreeZeroHom I I' ((degreeZeroEquiv I I').symm x) + 0
        rw [add_zero, ← degreeZeroEquiv_apply, LinearEquiv.apply_symm_apply]
      degreeOne := fun x => by
        change x = degreeOneEquiv I I' ((degreeOneEquiv I I').symm x) + _
        rw [LinearEquiv.apply_symm_apply, LinearMap.zero_apply, map_zero, add_zero] }

/-- **The external sum of two obstruction theories for affine local embeddings is an obstruction
theory for the product embedding.**

If `φ` is an obstruction theory for the embedding `Spec (k[x_σ]/I) ↪ 𝔸^σ` and `φ'` one for
`Spec (k[x_τ]/I') ↪ 𝔸^τ`, then the external sum of the two, transported along
`conormalProdEquiv`, is an obstruction theory for the product embedding
`Spec (k[x_{σ ⊕ τ}]/J) ↪ 𝔸^{σ ⊕ τ}`. -/
theorem isObstructionTheory_externalSum_conormal
    {E : LinearTwoTermComplex (MvPolynomial σ k ⧸ I)}
    {E' : LinearTwoTermComplex (MvPolynomial τ k ⧸ I')}
    {φ : LinearTwoTermComplex.Hom E (conormalComplex k (MvPolynomial σ k) I)}
    {φ' : LinearTwoTermComplex.Hom E' (conormalComplex k (MvPolynomial τ k) I')}
    (h : IsObstructionTheory φ) (h' : IsObstructionTheory φ') :
    IsObstructionTheory ((conormalProdEquiv I I').hom.comp
      ((φ.baseChange (prodQuot I I')).sum (φ'.baseChange (prodQuot I I')))) :=
  ((h.baseChange (prodQuot I I')).sum (h'.baseChange (prodQuot I I'))).comp_homotopyEquivalence
    (conormalProdEquiv I I')


/-! ### Virtual ranks -/

/-- Base change of a perfect (finite free) two-term complex along any algebra map is perfect. -/
theorem isPerfectTwoTerm_baseChange {A B : Type u} [CommRing A] [CommRing B] [Algebra A B]
    {E : LinearTwoTermComplex A} (h : IsPerfectTwoTerm E) :
    IsPerfectTwoTerm (E.baseChange B) := by
  have h1 := h.free_degreeZero
  have h2 := h.finite_degreeZero
  have h3 := h.free_degreeOne
  have h4 := h.finite_degreeOne
  exact
    { free_degreeZero := inferInstance
      finite_degreeZero := inferInstance
      free_degreeOne := inferInstance
      finite_degreeOne := inferInstance }

/-- Base change along any algebra map preserves the virtual rank of a perfect two-term
complex. -/
theorem virtualRank_baseChange {A B : Type u} [CommRing A] [CommRing B] [Algebra A B]
    [Nontrivial A] [Nontrivial B] {E : LinearTwoTermComplex A} (h : IsPerfectTwoTerm E) :
    virtualRank (E.baseChange B) = virtualRank E := by
  have h1 := h.free_degreeZero
  have h3 := h.free_degreeOne
  have key : ((Module.finrank B (B ⊗[A] E.degreeOne) : ℤ) -
      (Module.finrank B (B ⊗[A] E.degreeZero) : ℤ)) =
      ((Module.finrank A E.degreeOne : ℤ) - (Module.finrank A E.degreeZero : ℤ)) := by
    rw [Module.finrank_baseChange, Module.finrank_baseChange]
  exact key

/-- **Virtual ranks add for the external sum over the coordinate ring of the product.** -/
theorem virtualRank_externalSum [Nontrivial (MvPolynomial σ k ⧸ I)]
    [Nontrivial (MvPolynomial τ k ⧸ I')] [Nontrivial (prodQuot I I')]
    {E : LinearTwoTermComplex (MvPolynomial σ k ⧸ I)}
    {E' : LinearTwoTermComplex (MvPolynomial τ k ⧸ I')} (h : IsPerfectTwoTerm E)
    (h' : IsPerfectTwoTerm E') :
    virtualRank ((E.baseChange (prodQuot I I')).sum (E'.baseChange (prodQuot I I'))) =
      virtualRank E + virtualRank E' := by
  have key := virtualRank_sum (isPerfectTwoTerm_baseChange (B := prodQuot I I') h)
    (isPerfectTwoTerm_baseChange (B := prodQuot I I') h')
  rw [virtualRank_baseChange h, virtualRank_baseChange h'] at key
  exact key

end ComplexComparison

/-! ## `k[x_{σ ⊕ τ}]/J` is the coordinate ring of the product -/

/-- The `k`-algebra map `k[x_{σ ⊕ τ}] → (k[x_σ]/I) ⊗[k] (k[x_τ]/I')`. -/
noncomputable def toTensorQuot :
    MvPolynomial (σ ⊕ τ) k →ₐ[k] (MvPolynomial σ k ⧸ I) ⊗[k] (MvPolynomial τ k ⧸ I') :=
  (Algebra.TensorProduct.map (Ideal.Quotient.mkₐ k I) (Ideal.Quotient.mkₐ k I')).comp
    (toTensor k σ τ)

/-- `toTensorQuot` on the first block of variables. -/
@[simp]
theorem toTensorQuot_inlHom (p : MvPolynomial σ k) :
    toTensorQuot I I' (inlHom k σ τ p) = Ideal.Quotient.mk I p ⊗ₜ[k] 1 := by
  rw [toTensorQuot, AlgHom.comp_apply, toTensor_inlHom, Algebra.TensorProduct.map_tmul]
  rfl

/-- `toTensorQuot` on the second block of variables. -/
@[simp]
theorem toTensorQuot_inrHom (q : MvPolynomial τ k) :
    toTensorQuot I I' (inrHom k σ τ q) = 1 ⊗ₜ[k] Ideal.Quotient.mk I' q := by
  rw [toTensorQuot, AlgHom.comp_apply, toTensor_inrHom, Algebra.TensorProduct.map_tmul]
  rfl

/-- `toTensorQuot` kills the product ideal. -/
theorem toTensorQuot_eq_zero_of_mem {z : MvPolynomial (σ ⊕ τ) k} (hz : z ∈ prodIdeal I I') :
    toTensorQuot I I' z = 0 := by
  have key : ∀ y ∈ Ideal.span (inlHom k σ τ '' I ∪ inrHom k σ τ '' I'),
      toTensorQuot I I' y = 0 := by
    intro y hy
    induction hy using Submodule.span_induction with
    | mem u hu =>
      rcases hu with ⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩
      · rw [toTensorQuot_inlHom, Ideal.Quotient.eq_zero_iff_mem.mpr hx, TensorProduct.zero_tmul]
      · rw [toTensorQuot_inrHom, Ideal.Quotient.eq_zero_iff_mem.mpr hx, TensorProduct.tmul_zero]
    | zero => rw [map_zero]
    | add a b _ _ iha ihb => rw [map_add, iha, ihb, add_zero]
    | smul c a _ iha =>
      rw [smul_eq_mul, map_mul, iha]
      exact mul_zero (toTensorQuot I I' c)
  refine key z ?_
  rwa [prodIdeal_eq_span] at hz

/-- The `k`-algebra map `k[x_{σ ⊕ τ}]/J → (k[x_σ]/I) ⊗[k] (k[x_τ]/I')`. -/
noncomputable def prodQuotToTensor :
    prodQuot I I' →ₐ[k] (MvPolynomial σ k ⧸ I) ⊗[k] (MvPolynomial τ k ⧸ I') :=
  Ideal.Quotient.liftₐ (prodIdeal I I') (toTensorQuot I I')
    fun _ hz => toTensorQuot_eq_zero_of_mem I I' hz

/-- `prodQuotToTensor` on the class of a polynomial. -/
@[simp]
theorem prodQuotToTensor_mk (z : MvPolynomial (σ ⊕ τ) k) :
    prodQuotToTensor I I' (Ideal.Quotient.mk (prodIdeal I I') z) = toTensorQuot I I' z :=
  rfl

/-- The `k`-algebra map `(k[x_σ]/I) ⊗[k] (k[x_τ]/I') → k[x_{σ ⊕ τ}]/J`, given by the two
projections of the product. -/
noncomputable def tensorToProdQuot :
    (MvPolynomial σ k ⧸ I) ⊗[k] (MvPolynomial τ k ⧸ I') →ₐ[k] prodQuot I I' :=
  Algebra.TensorProduct.lift (toProdQuotLeft I I') (toProdQuotRight I I')
    fun _ _ => Commute.all _ _

/-- `tensorToProdQuot` on a pure tensor of classes of polynomials. -/
@[simp]
theorem tensorToProdQuot_tmul (p : MvPolynomial σ k) (q : MvPolynomial τ k) :
    tensorToProdQuot I I' (Ideal.Quotient.mk I p ⊗ₜ[k] Ideal.Quotient.mk I' q) =
      Ideal.Quotient.mk (prodIdeal I I') (inlHom k σ τ p * inrHom k σ τ q) := by
  rw [tensorToProdQuot, Algebra.TensorProduct.lift_tmul, map_mul]
  rfl

/-- `prodQuotToTensor` is a left inverse of `tensorToProdQuot`. -/
theorem prodQuotToTensor_tensorToProdQuot
    (z : (MvPolynomial σ k ⧸ I) ⊗[k] (MvPolynomial τ k ⧸ I')) :
    prodQuotToTensor I I' (tensorToProdQuot I I' z) = z := by
  induction z using TensorProduct.induction_on with
  | zero => rw [map_zero, map_zero]
  | tmul s s' =>
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective s
    obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective s'
    rw [tensorToProdQuot_tmul, prodQuotToTensor_mk, map_mul, toTensorQuot_inlHom,
      toTensorQuot_inrHom, Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- `tensorToProdQuot` is a left inverse of `prodQuotToTensor`, on representatives. -/
theorem tensorToProdQuot_toTensorQuot (m : MvPolynomial (σ ⊕ τ) k) :
    tensorToProdQuot I I' (toTensorQuot I I' m) = Ideal.Quotient.mk (prodIdeal I I') m := by
  have key : (tensorToProdQuot I I').comp (toTensorQuot I I') =
      Ideal.Quotient.mkₐ k (prodIdeal I I') := by
    refine MvPolynomial.algHom_ext fun i => ?_
    rcases i with i | j
    · have hone : inrHom k σ τ (1 : MvPolynomial τ k) = 1 := map_one _
      have hX : (MvPolynomial.X (Sum.inl i) : MvPolynomial (σ ⊕ τ) k) =
          inlHom k σ τ (MvPolynomial.X i) := (MvPolynomial.rename_X _ _).symm
      rw [AlgHom.comp_apply, hX, toTensorQuot_inlHom,
        show (1 : MvPolynomial τ k ⧸ I') = Ideal.Quotient.mk I' 1 from rfl,
        tensorToProdQuot_tmul, hone, mul_one]
      rfl
    · have hone : inlHom k σ τ (1 : MvPolynomial σ k) = 1 := map_one _
      have hX : (MvPolynomial.X (Sum.inr j) : MvPolynomial (σ ⊕ τ) k) =
          inrHom k σ τ (MvPolynomial.X j) := (MvPolynomial.rename_X _ _).symm
      rw [AlgHom.comp_apply, hX, toTensorQuot_inrHom,
        show (1 : MvPolynomial σ k ⧸ I) = Ideal.Quotient.mk I 1 from rfl,
        tensorToProdQuot_tmul, hone, one_mul]
      rfl
  exact AlgHom.congr_fun key m

/-- **The coordinate ring of the product embedding is the tensor product of the coordinate rings
of the two factors:** `k[x_{σ ⊕ τ}]/J ≃ₐ[k] (k[x_σ]/I) ⊗[k] (k[x_τ]/I')`.  Together with
`conormalProdEquiv` this identifies `conormalSum I I'` with the external sum
`PicardCriteria.externalSum k (conormalComplex k k[x_σ] I) (conormalComplex k k[x_τ] I')` of
`ObstructionTheory/ExternalSum.lean`. -/
noncomputable def prodQuotAlgEquiv :
    prodQuot I I' ≃ₐ[k] (MvPolynomial σ k ⧸ I) ⊗[k] (MvPolynomial τ k ⧸ I') :=
  AlgEquiv.ofAlgHom (prodQuotToTensor I I') (tensorToProdQuot I I')
    (AlgHom.ext fun z => prodQuotToTensor_tensorToProdQuot I I' z)
    (AlgHom.ext fun c => by
      obtain ⟨m, rfl⟩ := Ideal.Quotient.mk_surjective c
      exact tensorToProdQuot_toTensorQuot I I' m)

end ExternalSumConormal

end GromovWitten.AlgebraicGeometry
