/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude Fable 5.1
-/

import GromovWitten.AlgebraicGeometry.IntersectionTheory.BundleHomotopy
import GromovWitten.AlgebraicGeometry.IntersectionTheory.BundleHomotopyRankOne
import GromovWitten.AlgebraicGeometry.IntersectionTheory.LocalOrdSymmetry
import Mathlib.RingTheory.Polynomial.Ideal

/-!
# The Gysin map of a section of the trivial line bundle

Let `R` be a Noetherian commutative ring, `X = Spec R`, and let `E = Spec R[T]` be the trivial
line bundle over `X`.  For `c : R` the evaluation homomorphism `R[T] → R`, `T ↦ c`, is surjective
and defines a closed immersion `σ_c : X → E`, the section of the bundle with constant value `c`.
Its ideal is generated by `s := T - c`.

This file constructs the *cycle level* Gysin map of that section,
`i_c^* : Z(E) → Z(X)`, `i_c^* z = ∑_{V ∌ s} z(V) · σ_c^{-1} (div_V s)`,
and proves the two properties which make it a one-sided inverse of the flat pullback modulo
rational equivalence, namely `i_c^* ∘ π^* = id` on cycles and the fact that `i_c^*` of a
principal divisor in *good position* with respect to `c` is again a sum of principal divisors.
Together these give injectivity of the flat pullback on Chow groups (carried out in a later
file).

## Contents

* `VectorBundle.sectionMap`, `VectorBundle.sectionPoint`: the closed immersion `σ_c` and its
  action on points, together with the identification of its image with the locus `s ∈ Q`.
* `VectorBundle.sectionRestrict`: restriction of cycles along `σ_c`, `z ↦ z ∘ σ_c`.
* `VectorBundle.elementGenerator`: the principal-divisor generator attached to a prime `P` of
  `R[T]` and an element `a ∉ P`; `VectorBundle.sectionDivisor` is the special case `a = s`.
* `VectorBundle.exists_generator_eq_elementGenerator_sub`: every principal divisor on `E` is a
  difference of two such divisors.
* `VectorBundle.sectionGysin`: the Gysin map of the section.
* `VectorBundle.sectionGysin_pullbackBundle`: `i_c^* (π^* w) = w`, unconditionally.
* `VectorBundle.sectionGenerator` and
  `VectorBundle.sectionRestrict_elementGenerator_mem`: a subvariety of `E` contained in the
  section is a closed subscheme of the base as well, so the restriction along `σ_c` of a
  principal divisor carried by it is a principal divisor on `X`.
* `VectorBundle.divisor_sectionPoly_support`: the divisor of `s` on a subvariety `V(P)` not
  contained in the section is supported exactly on the components of `V(P) ∩ σ_c(X)`.
* `VectorBundle.sectionGysin_elementGenerator_mem`: `i_c^*` of the divisor of `a` on `V(P)` is a
  rational equivalence relation on `X`, provided `a` is in good position.

## Hypotheses taken as arguments

`VectorBundle.LocalOrdSymmetry` (Fulton's symmetric local identity in a two-dimensional local
domain) is copied verbatim from the companion file which proves it; no result in this file uses
it yet.

`VectorBundle.sectionGysin_elementGenerator_mem` takes as an explicit hypothesis `hident` the
cycle-level form of that identity, namely that taking first the divisor of `s` and then the
divisor of `a` gives the same cycle on the base as taking first the divisor of `a` and then the
divisor of `s`.  Deducing `hident` from `LocalOrdSymmetry` requires identifying the stalk of
`Spec D` at a prime with `Localization.AtPrime` and the stalk of `Spec (D ⧸ q)` with a quotient
of `Localization.AtPrime`, which is not carried out here.  Everything else in the proof of
`sectionGysin_elementGenerator_mem` is unconditional.
-/

open CategoryTheory AlgebraicGeometry

universe u

namespace GromovWitten.AlgebraicGeometry.IntersectionTheory

namespace VectorBundle

/-- A rational cycle on a quasi-compact scheme is the sum of its single-point components. -/
theorem finsum_singlePoint_smul {X : Scheme.{u}} [CompactSpace X] (z : AlgebraicCycle X ℚ) :
    ∑ᶠ x, (z : X → ℚ) x • AlgebraicCycle.singlePoint x = z := by
  classical
  have hfin := AlgebraicCycle.finite_support z
  have hsub : Function.support (fun x ↦ (z : X → ℚ) x • AlgebraicCycle.singlePoint x) ⊆
      (hfin.toFinset : Set X) := by
    intro x hx
    rw [Finset.mem_coe, Set.Finite.mem_toFinset, Function.mem_support]
    intro hz
    refine hx ?_
    change (z : X → ℚ) x • AlgebraicCycle.singlePoint x = 0
    rw [hz, zero_smul]
  rw [finsum_eq_sum_of_support_subset _ hsub]
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp only [Function.locallyFinsuppWithin.coe_sum, Finset.sum_apply]
  have hterm : ∀ x : X,
      (((z : X → ℚ) x • AlgebraicCycle.singlePoint x : AlgebraicCycle X ℚ) : X → ℚ) y =
        (z : X → ℚ) x * (if y = x then 1 else 0) := by
    intro x
    rw [Function.locallyFinsuppWithin.coe_rational_smul]
    simp only [Pi.smul_apply, AlgebraicCycle.singlePoint_apply, smul_eq_mul]
  simp only [hterm]
  rw [Finset.sum_eq_single y]
  · simp
  · intro b _ hb
    rw [if_neg (fun hcon : y = b ↦ hb hcon.symm), mul_zero]
  · intro hy
    have hzy : (z : X → ℚ) y = 0 := by
      by_contra hne
      exact hy (by simpa using hne)
    rw [hzy, zero_mul]

/-! ## The section of the trivial line bundle -/

section Section

variable {R : Type u} [CommRing R] (c : R)

/-- The section with constant value `c` of the trivial line bundle `Spec R[T] → Spec R`, as the
spectrum of the evaluation homomorphism `T ↦ c`. -/
noncomputable def sectionMap :
    Spec (CommRingCat.of R) ⟶ Spec (CommRingCat.of (Polynomial R)) :=
  Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom c))

/-- Evaluation at `c` is a surjective ring homomorphism. -/
theorem evalRingHom_surjective : Function.Surjective (Polynomial.evalRingHom c) :=
  fun r ↦ ⟨Polynomial.C r, by simp⟩

instance isClosedImmersion_sectionMap :
    _root_.AlgebraicGeometry.IsClosedImmersion (sectionMap c) :=
  _root_.AlgebraicGeometry.IsClosedImmersion.spec_of_surjective _ (evalRingHom_surjective c)

/-- The defining equation of the section: the polynomial `T - c`. -/
noncomputable def sectionPoly : Polynomial R := Polynomial.X - Polynomial.C c

/-- The kernel of evaluation at `c` is generated by `T - c`. -/
theorem ker_evalRingHom_eq :
    RingHom.ker (Polynomial.evalRingHom c) = Ideal.span {sectionPoly c} :=
  Polynomial.ker_evalRingHom c

/-- The image of a point of the base under the section, a point of the total space. -/
noncomputable def sectionPoint (x : ↥(Spec (CommRingCat.of R))) :
    ↥(Spec (CommRingCat.of (Polynomial R))) :=
  (sectionMap c).base x

/-- The prime of `R[T]` attached to the image of a point under the section is the contraction of
the prime of `R` along evaluation. -/
theorem sectionPoint_asIdeal (x : ↥(Spec (CommRingCat.of R))) :
    (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal =
      (x : PrimeSpectrum R).asIdeal.comap (Polynomial.evalRingHom c) := rfl

/-- Membership in the prime of the image of a point under the section. -/
theorem mem_sectionPoint_iff (x : ↥(Spec (CommRingCat.of R))) (f : Polynomial R) :
    f ∈ (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal ↔
      f.eval c ∈ (x : PrimeSpectrum R).asIdeal := Iff.rfl

/-- The defining equation of the section vanishes at every point of the section. -/
theorem sectionPoly_mem_sectionPoint (x : ↥(Spec (CommRingCat.of R))) :
    sectionPoly c ∈ (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal := by
  rw [mem_sectionPoint_iff]
  simp [sectionPoly]

/-- The section is injective on points. -/
theorem sectionPoint_injective : Function.Injective (sectionPoint c) := by
  intro x y h
  exact PrimeSpectrum.comap_injective_of_surjective _ (evalRingHom_surjective c) h

/-- The section preserves the certified dimension grading. -/
theorem dimension_sectionPoint
    (dimX : DimensionFunction (Spec (CommRingCat.of R)))
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (x : ↥(Spec (CommRingCat.of R))) :
    dimX x = dimE (sectionPoint c x) :=
  DimensionFunction.apply_eq_of_isClosedImmersion dimX dimE (sectionMap c) x

/-- A prime containing `T - c` is the contraction of its own image under evaluation. -/
theorem comap_map_evalRingHom (Q : Ideal (Polynomial R))
    (hQ : sectionPoly c ∈ Q) :
    (Q.map (Polynomial.evalRingHom c)).comap (Polynomial.evalRingHom c) = Q := by
  rw [Ideal.comap_map_of_surjective _ (evalRingHom_surjective c), ← RingHom.ker_eq_comap_bot,
    ker_evalRingHom_eq]
  exact sup_eq_left.mpr ((Ideal.span_singleton_le_iff_mem _).2 hQ)

/-- The image of a prime containing `T - c` under evaluation is prime. -/
theorem isPrime_map_evalRingHom (Q : Ideal (Polynomial R)) (hp : Q.IsPrime)
    (hQ : sectionPoly c ∈ Q) : (Q.map (Polynomial.evalRingHom c)).IsPrime :=
  Ideal.map_isPrime_of_surjective (evalRingHom_surjective c)
    (by rw [ker_evalRingHom_eq]; exact (Ideal.span_singleton_le_iff_mem _).2 hQ)

/-- The point of the base attached to a prime of the total space containing `T - c`. -/
noncomputable def basePoint (Q : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hQ : sectionPoly c ∈ (Q : PrimeSpectrum (Polynomial R)).asIdeal) :
    ↥(Spec (CommRingCat.of R)) :=
  show PrimeSpectrum R from
    ⟨(Q : PrimeSpectrum (Polynomial R)).asIdeal.map (Polynomial.evalRingHom c),
      isPrime_map_evalRingHom c _ (Q : PrimeSpectrum (Polynomial R)).isPrime hQ⟩

/-- The section maps `basePoint` back to the point it came from. -/
theorem sectionPoint_basePoint (Q : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hQ : sectionPoly c ∈ (Q : PrimeSpectrum (Polynomial R)).asIdeal) :
    sectionPoint c (basePoint c Q hQ) = Q :=
  PrimeSpectrum.ext (comap_map_evalRingHom c _ hQ)

/-- The image of the section is exactly the zero locus of `T - c`. -/
theorem mem_range_sectionPoint_iff (Q : ↥(Spec (CommRingCat.of (Polynomial R)))) :
    Q ∈ Set.range (sectionPoint c) ↔
      sectionPoly c ∈ (Q : PrimeSpectrum (Polynomial R)).asIdeal := by
  constructor
  · rintro ⟨x, rfl⟩
    exact sectionPoly_mem_sectionPoint c x
  · intro hQ
    exact ⟨basePoint c Q hQ, sectionPoint_basePoint c Q hQ⟩

/-! ## Restriction of cycles along the section -/

/-- The restriction of a cycle on the total space along the section, as a cycle on the base.
Local finiteness is inherited through the continuous injective map on points. -/
noncomputable def sectionRestrictCycle
    (z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
    AlgebraicCycle (Spec (CommRingCat.of R)) ℚ where
  toFun x := (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (sectionPoint c x)
  supportWithinDomain' := Set.subset_univ _
  supportLocallyFiniteWithinDomain' x _ := by
    obtain ⟨t, ht, hfin⟩ := z.supportLocallyFiniteWithinDomain (sectionPoint c x) (by trivial)
    refine ⟨(sectionMap c).base ⁻¹' t,
      (sectionMap c).continuous.continuousAt.preimage_mem_nhds ht, ?_⟩
    refine Set.Finite.of_finite_image (f := sectionPoint c) (hfin.subset ?_)
      ((sectionPoint_injective c).injOn)
    rintro y ⟨w, hw, rfl⟩
    exact ⟨hw.1, hw.2⟩

@[simp]
theorem sectionRestrictCycle_apply
    (z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ)
    (x : ↥(Spec (CommRingCat.of R))) :
    (sectionRestrictCycle c z : ↥(Spec (CommRingCat.of R)) → ℚ) x =
      (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (sectionPoint c x) := rfl

/-- Restriction of cycles along the section of the trivial line bundle, as a linear map. -/
noncomputable def sectionRestrict :
    AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ →ₗ[ℚ]
      AlgebraicCycle (Spec (CommRingCat.of R)) ℚ where
  toFun := sectionRestrictCycle c
  map_add' z w := by
    apply Function.locallyFinsuppWithin.coe_injective
    funext x
    simp
  map_smul' r z := by
    apply Function.locallyFinsuppWithin.coe_injective
    funext x
    simp [Function.locallyFinsuppWithin.coe_rational_smul]

@[simp]
theorem sectionRestrict_apply
    (z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ)
    (x : ↥(Spec (CommRingCat.of R))) :
    (sectionRestrict c z : ↥(Spec (CommRingCat.of R)) → ℚ) x =
      (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (sectionPoint c x) := rfl

end Section

/-! ## Principal-divisor generators on the closed subschemes of the total space -/

section Generator

variable {R : Type u} [CommRing R] [IsNoetherianRing R]

/-- The quotient of a polynomial ring by a prime ideal is a domain, in the shape instance search
needs for the corresponding object of `CommRingCat`. -/
instance isDomain_quotientPolynomial (P : Ideal (Polynomial R)) [P.IsPrime] :
    IsDomain ↑(CommRingCat.of (Polynomial R ⧸ P)) :=
  inferInstanceAs (IsDomain (Polynomial R ⧸ P))

/-- The quotient of a polynomial ring over a Noetherian ring by an ideal is Noetherian, in the
shape instance search needs for the corresponding object of `CommRingCat`. -/
instance isNoetherianRing_quotientPolynomial (P : Ideal (Polynomial R)) :
    IsNoetherianRing ↑(CommRingCat.of (Polynomial R ⧸ P)) :=
  inferInstanceAs (IsNoetherianRing (Polynomial R ⧸ P))

/-- The integral closed subscheme `V(P) ⊆ Spec R[T]` cut out by a prime ideal `P`. -/
noncomputable def quotientSubscheme (P : Ideal (Polynomial R)) [P.IsPrime] :
    IntegralClosedSubscheme (Spec (CommRingCat.of (Polynomial R))) where
  scheme := Spec (CommRingCat.of (Polynomial R ⧸ P))
  inclusion := quotImmersion P

omit [IsNoetherianRing R] in
/-- The class of a polynomial outside a prime `P` is a nonzero element of the quotient. -/
theorem quotientMk_ne_zero (P : Ideal (Polynomial R)) (a : Polynomial R) (ha : a ∉ P) :
    (Ideal.Quotient.mk P a : Polynomial R ⧸ P) ≠ 0 :=
  fun h ↦ ha (Ideal.Quotient.eq_zero_iff_mem.1 h)

/-- The rational function on the subvariety `V(P)` determined by a polynomial outside `P`. -/
noncomputable def elementFunction (P : Ideal (Polynomial R)) [P.IsPrime]
    (a : Polynomial R) (ha : a ∉ P) :
    (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionFieldˣ :=
  functionFieldUnit (CommRingCat.of (Polynomial R ⧸ P)) (Ideal.Quotient.mk P a)
    (quotientMk_ne_zero P a ha)

/-- The principal-divisor generator on the subvariety `V(P)` of the total space attached to a
polynomial `a` not lying in `P`. -/
noncomputable def elementGenerator (P : Ideal (Polynomial R)) [P.IsPrime]
    (a : Polynomial R) (ha : a ∉ P) :
    RationalFunctionGenerator (Spec (CommRingCat.of (Polynomial R))) where
  subspace := quotientSubscheme P
  function := elementFunction P a ha

/-- The point of `V(P)` corresponding to a prime of `R[T]` containing `P`. -/
noncomputable def quotientPoint (P Q : Ideal (Polynomial R)) (hQp : Q.IsPrime) (hPQ : P ≤ Q) :
    ↥(Spec (CommRingCat.of (Polynomial R ⧸ P))) :=
  show PrimeSpectrum (Polynomial R ⧸ P) from
    ⟨Q.map (Ideal.Quotient.mk P),
      Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
        (by rw [Ideal.mk_ker]; exact hPQ)⟩

omit [IsNoetherianRing R] in
/-- The closed immersion of `V(P)` sends `quotientPoint` back to the prime it came from. -/
theorem quotImmersion_base_quotientPoint (P Q : Ideal (Polynomial R)) (hQp : Q.IsPrime)
    (hPQ : P ≤ Q) :
    ((quotImmersion P).base (quotientPoint P Q hQp hPQ) :
        PrimeSpectrum (Polynomial R)).asIdeal = Q := by
  change (Q.map (Ideal.Quotient.mk P)).comap (Ideal.Quotient.mk P) = Q
  rw [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
    ← RingHom.ker_eq_comap_bot, Ideal.mk_ker]
  exact sup_eq_left.mpr hPQ

omit [IsNoetherianRing R] in
/-- The image of the closed immersion of `V(P)` consists of the primes containing `P`. -/
theorem mem_range_quotImmersion_iff (P : Ideal (Polynomial R))
    (Q : ↥(Spec (CommRingCat.of (Polynomial R)))) :
    Q ∈ Set.range (quotImmersion P).base ↔ P ≤ (Q : PrimeSpectrum (Polynomial R)).asIdeal := by
  constructor
  · rintro ⟨y, rfl⟩
    intro a ha
    change Ideal.Quotient.mk P a ∈ (y : PrimeSpectrum (Polynomial R ⧸ P)).asIdeal
    rw [Ideal.Quotient.eq_zero_iff_mem.2 ha]
    exact Ideal.zero_mem _
  · intro hPQ
    exact ⟨quotientPoint P _ (Q : PrimeSpectrum (Polynomial R)).isPrime hPQ,
      PrimeSpectrum.ext (quotImmersion_base_quotientPoint P _ _ hPQ)⟩

/-- The coefficient of the divisor of `elementGenerator` at a point of `V(P)`. -/
theorem elementGenerator_divisor_apply_image (P : Ideal (Polynomial R)) [P.IsPrime]
    (a : Polynomial R) (ha : a ∉ P)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (Q : ↥(Spec (CommRingCat.of (Polynomial R ⧸ P)))) :
    (elementGenerator P a ha).divisor dimE ((quotImmersion P).base Q) =
      (((Spec (CommRingCat.of (Polynomial R ⧸ P))).ord
        (elementFunction P a ha :
          (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionField) Q : ℤ) : ℚ) :=
  AlgebraicCycle.map_closedImmersion_apply_image (quotImmersion P) (dimE : _ → ℤ) _ Q

/-- The coefficient of the divisor of `elementGenerator` at a prime containing `P`, computed as
the order of vanishing at the corresponding point of `V(P)`. -/
theorem elementGenerator_divisor_apply_of_le (P : Ideal (Polynomial R)) [P.IsPrime]
    (a : Polynomial R) (ha : a ∉ P)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (Q : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hPQ : P ≤ (Q : PrimeSpectrum (Polynomial R)).asIdeal) :
    (elementGenerator P a ha).divisor dimE Q =
      (((Spec (CommRingCat.of (Polynomial R ⧸ P))).ord
        (elementFunction P a ha :
          (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionField)
        (quotientPoint P (Q : PrimeSpectrum (Polynomial R)).asIdeal
          (Q : PrimeSpectrum (Polynomial R)).isPrime hPQ) : ℤ) : ℚ) := by
  have himg : (quotImmersion P).base
      (quotientPoint P (Q : PrimeSpectrum (Polynomial R)).asIdeal
        (Q : PrimeSpectrum (Polynomial R)).isPrime hPQ) = Q :=
    PrimeSpectrum.ext (quotImmersion_base_quotientPoint P _ _ hPQ)
  have h := elementGenerator_divisor_apply_image P a ha dimE
    (quotientPoint P (Q : PrimeSpectrum (Polynomial R)).asIdeal
      (Q : PrimeSpectrum (Polynomial R)).isPrime hPQ)
  rwa [himg] at h

/-- The divisor of `elementGenerator` vanishes off the subvariety `V(P)`. -/
theorem elementGenerator_divisor_apply_of_not_le (P : Ideal (Polynomial R)) [P.IsPrime]
    (a : Polynomial R) (ha : a ∉ P)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (Q : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hQ : ¬ P ≤ (Q : PrimeSpectrum (Polynomial R)).asIdeal) :
    (elementGenerator P a ha).divisor dimE Q = 0 :=
  AlgebraicCycle.map_closedImmersion_apply_of_not_mem_range (quotImmersion P) (dimE : _ → ℤ) _ Q
    (fun h ↦ hQ ((mem_range_quotImmersion_iff P Q).1 h))

/-- The divisor of the defining equation of the section on a subvariety `V(P)` of the total
space which is not contained in the section. -/
noncomputable def sectionDivisor (c : R) (P : Ideal (Polynomial R)) [P.IsPrime]
    (hP : sectionPoly c ∉ P) :
    RationalFunctionGenerator (Spec (CommRingCat.of (Polynomial R))) :=
  elementGenerator P (sectionPoly c) hP

/-- Every nonzero rational function on an integral Noetherian affine scheme is a ratio of two
nonzero global sections, so its principal cycle is the difference of the principal cycles of two
global sections. -/
theorem exists_principalCycle_eq_sub (B : CommRingCat.{u}) [IsDomain B] [IsNoetherianRing B]
    (f : (Spec B).functionField) (hf : f ≠ 0) :
    ∃ (a b : B) (ha : a ≠ 0) (hb : b ≠ 0),
      (Spec B).principalCycle f =
        (Spec B).principalCycle (functionFieldUnit B a ha : (Spec B).functionField) -
          (Spec B).principalCycle (functionFieldUnit B b hb : (Spec B).functionField) := by
  obtain ⟨a, b, hbm, hab⟩ :=
    IsFractionRing.div_surjective (A := B) (K := (Spec B).functionField) f
  have hinj : Function.Injective (algebraMap B (Spec B).functionField) :=
    IsFractionRing.injective B (Spec B).functionField
  have hb0 : b ≠ 0 := nonZeroDivisors.ne_zero hbm
  have hbf : algebraMap B (Spec B).functionField b ≠ 0 :=
    fun h ↦ hb0 (hinj (by rw [h, map_zero]))
  have ha0 : a ≠ 0 := by
    intro h
    rw [h, map_zero, zero_div] at hab
    exact hf hab.symm
  have haf : algebraMap B (Spec B).functionField a ≠ 0 :=
    fun h ↦ ha0 (hinj (by rw [h, map_zero]))
  refine ⟨a, b, ha0, hb0, ?_⟩
  have hkey : algebraMap B (Spec B).functionField a =
      f * algebraMap B (Spec B).functionField b := (div_eq_iff hbf).1 hab
  have hmul := (Spec B).principalCycle_mul hf hbf
  rw [← hkey] at hmul
  rw [functionFieldUnit_val, functionFieldUnit_val]
  exact eq_sub_of_add_eq hmul.symm

/-- Every principal divisor on the total space of the trivial line bundle is the difference of
the divisors of two polynomials on one and the same subvariety `V(P)`. -/
theorem exists_generator_eq_elementGenerator_sub
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (g : RationalFunctionGenerator (Spec (CommRingCat.of (Polynomial R)))) :
    ∃ (P : Ideal (Polynomial R)) (hP : P.IsPrime) (a b : Polynomial R)
      (ha : a ∉ P) (hb : b ∉ P),
      g.divisor dimE =
        (@elementGenerator R _ _ P hP a ha).divisor dimE -
          (@elementGenerator R _ _ P hP b hb).divisor dimE := by
  obtain ⟨P, ε, hfac⟩ :=
    _root_.AlgebraicGeometry.IsClosedImmersion.Spec_iff.1 g.subspace.isClosedImmersion
  have hint : _root_.AlgebraicGeometry.IsIntegral (Spec (CommRingCat.of (Polynomial R ⧸ P))) :=
    _root_.AlgebraicGeometry.IsIntegral.of_isIso ε.hom
  have hdom : IsDomain (Polynomial R ⧸ P) :=
    (_root_.AlgebraicGeometry.affine_isIntegral_iff
      (CommRingCat.of (Polynomial R ⧸ P))).1 hint
  have hP : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).1 hdom
  set f' : (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionFieldˣ :=
    Units.map (_root_.AlgebraicGeometry.Scheme.dominantFunctionFieldMap ε.inv).toMonoidHom
      g.function with hf'
  have h1 : g.divisor dimE =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (ε.hom ≫ quotImmersion P)
        (fun x ↦ (dimE : _ → ℤ) ((ε.hom ≫ quotImmersion P).base x)) (dimE : _ → ℤ)
        (g.subspace.scheme.principalCycle (g.function : _)) :=
    AlgebraicCycle.map_congr_hom hfac (dimE : _ → ℤ) _
  have h2 := AlgebraicCycle.map_comp_of_isClosedImmersion ε.hom (quotImmersion P)
    ((DimensionFunction.comapClosedImmersion (quotImmersion P) dimE : _ → ℤ))
    (dimE : _ → ℤ) (g.subspace.scheme.principalCycle (g.function : _))
  have h3 := map_isIso_principalCycle ε
    (DimensionFunction.comapClosedImmersion (quotImmersion P) dimE)
    (g.function : g.subspace.scheme.functionField)
  rw [h3] at h2
  have h4 : g.divisor dimE =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (quotImmersion P)
        (fun z ↦ (dimE : _ → ℤ) ((quotImmersion P).base z)) (dimE : _ → ℤ)
        ((Spec (CommRingCat.of (Polynomial R ⧸ P))).principalCycle (f' : _)) := h1.trans h2.symm
  obtain ⟨a, b, ha0, hb0, hsub⟩ :=
    exists_principalCycle_eq_sub (CommRingCat.of (Polynomial R ⧸ P))
      (f' : (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionField) (Units.ne_zero f')
  obtain ⟨a', rfl⟩ := Ideal.Quotient.mk_surjective (I := P) a
  obtain ⟨b', rfl⟩ := Ideal.Quotient.mk_surjective (I := P) b
  have ha : a' ∉ P := fun h ↦ ha0 (Ideal.Quotient.eq_zero_iff_mem.2 h)
  have hb : b' ∉ P := fun h ↦ hb0 (Ideal.Quotient.eq_zero_iff_mem.2 h)
  refine ⟨P, hP, a', b', ha, hb, ?_⟩
  have hlin := (AlgebraicCycle.mapLinear (quotImmersion P)
      (fun z ↦ (dimE : _ → ℤ) ((quotImmersion P).base z)) (dimE : _ → ℤ)).map_sub
    ((Spec (CommRingCat.of (Polynomial R ⧸ P))).principalCycle
      (functionFieldUnit (CommRingCat.of (Polynomial R ⧸ P)) (Ideal.Quotient.mk P a') ha0 : _))
    ((Spec (CommRingCat.of (Polynomial R ⧸ P))).principalCycle
      (functionFieldUnit (CommRingCat.of (Polynomial R ⧸ P)) (Ideal.Quotient.mk P b') hb0 : _))
  rw [h4, hsub]
  exact hlin

/-! ## The Gysin map of the section -/

open Classical in
/-- The contribution of a point `V` of the total space to the Gysin map of the section: the
restriction along the section of the principal divisor of `T - c` on the subvariety `V(V)`, and
zero for the points lying on the section itself. -/
noncomputable def sectionGysinTerm (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (V : ↥(Spec (CommRingCat.of (Polynomial R)))) :
    AlgebraicCycle (Spec (CommRingCat.of R)) ℚ :=
  if h : sectionPoly c ∉ (V : PrimeSpectrum (Polynomial R)).asIdeal then
    sectionRestrict c
      ((@sectionDivisor R _ _ c (V : PrimeSpectrum (Polynomial R)).asIdeal
        (V : PrimeSpectrum (Polynomial R)).isPrime h).divisor dimE)
  else 0

/-- The summand of the Gysin map attached to a point vanishes wherever the cycle does, so the
defining sum has finite support. -/
theorem finite_support_sectionGysinSummand (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
    (Function.support fun V ↦ (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
      sectionGysinTerm c dimE V).Finite :=
  (AlgebraicCycle.finite_support z).subset fun V hV hz0 ↦ hV (by
    change (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V = 0 at hz0
    change (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
      sectionGysinTerm c dimE V = 0
    rw [hz0, zero_smul])

/-- The cycle-level Gysin map of the section with constant value `c` of the trivial line
bundle: every subvariety not contained in the section contributes the restriction to the base of
the principal divisor of `T - c` on it. -/
noncomputable def sectionGysin (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) :
    AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ →ₗ[ℚ]
      AlgebraicCycle (Spec (CommRingCat.of R)) ℚ where
  toFun z := ∑ᶠ V, (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
    sectionGysinTerm c dimE V
  map_add' z w := by
    have h : ∀ V, ((z + w : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
          ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V =
        (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V +
          (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V := by
      intro V
      have hzw : ((z + w : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
          ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V =
          (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V +
            (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V := by simp
      rw [hzw, add_smul]
    simp only [h]
    exact finsum_add_distrib (finite_support_sectionGysinSummand c dimE z)
      (finite_support_sectionGysinSummand c dimE w)
  map_smul' r z := by
    have h : ∀ V, ((r • z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
          ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V =
        r • ((z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
          sectionGysinTerm c dimE V) := by
      intro V
      rw [Function.locallyFinsuppWithin.coe_rational_smul]
      simp [smul_smul]
    simp only [RingHom.id_apply, h]
    exact (smul_finsum' r (finite_support_sectionGysinSummand c dimE z)).symm

/-- The defining formula for the Gysin map of the section. -/
theorem sectionGysin_apply (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (z : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ) :
    sectionGysin c dimE z =
      ∑ᶠ V, (z : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
        sectionGysinTerm c dimE V := rfl

/-- The Gysin summand at a point not lying on the section. -/
theorem sectionGysinTerm_of_notMem (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (V : ↥(Spec (CommRingCat.of (Polynomial R))))
    (h : sectionPoly c ∉ (V : PrimeSpectrum (Polynomial R)).asIdeal) :
    sectionGysinTerm c dimE V =
      sectionRestrict c
        ((@sectionDivisor R _ _ c (V : PrimeSpectrum (Polynomial R)).asIdeal
          (V : PrimeSpectrum (Polynomial R)).isPrime h).divisor dimE) := by
  classical
  rw [sectionGysinTerm, dif_pos h]

/-- The Gysin summand vanishes at a point lying on the section. -/
theorem sectionGysinTerm_of_mem (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (V : ↥(Spec (CommRingCat.of (Polynomial R))))
    (h : sectionPoly c ∈ (V : PrimeSpectrum (Polynomial R)).asIdeal) :
    sectionGysinTerm c dimE V = 0 := by
  classical
  rw [sectionGysinTerm, dif_neg (not_not_intro h)]

end Generator

/-! ## The Gysin map of the section inverts the flat pullback -/

section Pullback

variable {R : Type u} [CommRing R] [IsNoetherianRing R] (c : R)

omit [IsNoetherianRing R] in
/-- The defining equation of the section does not lie in the extension of a proper ideal of the
base: its coefficient in degree one is the unit `1`. -/
theorem sectionPoly_notMem_map (p : Ideal R) (hp : p ≠ ⊤) :
    sectionPoly c ∉ Ideal.map (algebraMap R (Polynomial R)) p := by
  rw [Polynomial.algebraMap_eq]
  intro h
  rw [Ideal.mem_map_C_iff] at h
  exact hp ((Ideal.eq_top_iff_one p).2 (by simpa [sectionPoly] using h 1))

omit [IsNoetherianRing R] in
/-- Evaluation at `c` undoes the inclusion of constants. -/
theorem evalRingHom_comp_C :
    (Polynomial.evalRingHom c).comp (algebraMap R (Polynomial R)) = RingHom.id R :=
  RingHom.ext fun r ↦ by simp

omit [IsNoetherianRing R] in
/-- A point of the base lies in the closure of `x` exactly when the fibre over `x` meets the
section at that point. -/
theorem map_le_sectionPoint_iff (x y : ↥(Spec (CommRingCat.of R))) :
    Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal ≤
        (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal ↔
      (x : PrimeSpectrum R).asIdeal ≤ (y : PrimeSpectrum R).asIdeal := by
  rw [Ideal.map_le_iff_le_comap, sectionPoint_asIdeal, Ideal.comap_comap,
    evalRingHom_comp_C, Ideal.comap_id]

omit [IsNoetherianRing R] in
/-- The ideal of the section at the point `x`, read in the fibre `R[T] ⧸ p·R[T]`, is generated by
the class of `T - c`. -/
theorem map_mk_sectionPoint_eq_span (p : Ideal R) :
    Ideal.map (Ideal.Quotient.mk (Ideal.map (algebraMap R (Polynomial R)) p))
        (Ideal.comap (Polynomial.evalRingHom c) p) =
      Ideal.span {Ideal.Quotient.mk (Ideal.map (algebraMap R (Polynomial R)) p)
        (sectionPoly c)} := by
  refine le_antisymm ?_ ?_
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    have hfp : Polynomial.eval c f ∈ p := hf
    have hC : Polynomial.C (Polynomial.eval c f) ∈
        Ideal.map (algebraMap R (Polynomial R)) p := by
      rw [Polynomial.algebraMap_eq]
      exact Ideal.mem_map_of_mem _ hfp
    obtain ⟨g, hg⟩ : sectionPoly c ∣ f - Polynomial.C (Polynomial.eval c f) := by
      simpa [sectionPoly] using Polynomial.X_sub_C_dvd_sub_C_eval (a := c) (p := f)
    change Ideal.Quotient.mk _ f ∈ Ideal.span _
    have hzero : Ideal.Quotient.mk (Ideal.map (algebraMap R (Polynomial R)) p)
        (Polynomial.C (Polynomial.eval c f)) = 0 := Ideal.Quotient.eq_zero_iff_mem.2 hC
    have heq : Ideal.Quotient.mk (Ideal.map (algebraMap R (Polynomial R)) p) f =
        Ideal.Quotient.mk _ (sectionPoly c) * Ideal.Quotient.mk _ g := by
      rw [← map_mul, ← hg, map_sub, hzero, sub_zero]
    rw [heq]
    exact Ideal.mem_span_singleton.2 (dvd_mul_right _ _)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    refine Ideal.mem_map_of_mem _ ?_
    change Polynomial.eval c (sectionPoly c) ∈ p
    simp [sectionPoly]

omit [IsNoetherianRing R] in
/-- Extension to the quotient by `P` is injective on the ideals containing `P`. -/
theorem comap_map_quotientMk (P I : Ideal (Polynomial R)) (h : P ≤ I) :
    Ideal.comap (Ideal.Quotient.mk P) (Ideal.map (Ideal.Quotient.mk P) I) = I := by
  rw [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective, ← RingHom.ker_eq_comap_bot,
    Ideal.mk_ker]
  exact sup_eq_left.mpr h

omit [IsNoetherianRing R] in
/-- A prime strictly above a height-one prime of the quotient by `P` does not have height one. -/
theorem height_map_ne_one_of_lt (P I J : Ideal (Polynomial R)) (hI : I.IsPrime) (hJ : J.IsPrime)
    (hPI : P ≤ I) (hPJ : P ≤ J) (hIJ : I < J)
    (hheight : (Ideal.map (Ideal.Quotient.mk P) I).height = 1) :
    (Ideal.map (Ideal.Quotient.mk P) J).height ≠ 1 := by
  have h1 : (Ideal.map (Ideal.Quotient.mk P) I).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective (by rw [Ideal.mk_ker]; exact hPI)
  have h2 : (Ideal.map (Ideal.Quotient.mk P) J).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective (by rw [Ideal.mk_ker]; exact hPJ)
  have hlt : Ideal.map (Ideal.Quotient.mk P) I < Ideal.map (Ideal.Quotient.mk P) J := by
    refine lt_of_le_of_ne (Ideal.map_mono hIJ.le) ?_
    intro heq
    exact hIJ.ne (by rw [← comap_map_quotientMk P I hPI, ← comap_map_quotientMk P J hPJ, heq])
  have hadd := Ideal.height_add_one_le_of_lt_of_isPrime hlt
  rw [hheight] at hadd
  intro hcon
  rw [hcon] at hadd
  exact absurd hadd (by decide)

omit [IsNoetherianRing R] in
/-- The section passes through the closure of `x` exactly over the closure of `x`. -/
theorem le_sectionPoint_iff_of_eq (P : Ideal (Polynomial R))
    (x y : ↥(Spec (CommRingCat.of R)))
    (hPeq : P = Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal) :
    P ≤ (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal ↔
      (x : PrimeSpectrum R).asIdeal ≤ (y : PrimeSpectrum R).asIdeal := by
  rw [hPeq]
  exact map_le_sectionPoint_iff c x y

omit [IsNoetherianRing R] in
/-- In the fibre over `x`, the point where the section meets it is cut out by the class of
`T - c`. -/
theorem map_mk_sectionPoint_eq_span_of_eq (P : Ideal (Polynomial R))
    (x : ↥(Spec (CommRingCat.of R)))
    (hPeq : P = Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal) :
    Ideal.map (Ideal.Quotient.mk P)
        (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal =
      Ideal.span {Ideal.Quotient.mk P (sectionPoly c)} := by
  subst hPeq
  exact map_mk_sectionPoint_eq_span c _

/-- The section meets the fibre over a point `x` of the base transversally in the single point
`x`: the divisor of `T - c` on the fibre, restricted along the section, is the single-point
cycle at `x`. -/
theorem sectionRestrict_divisor_sectionPoly
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (x : ↥(Spec (CommRingCat.of R))) (P : Ideal (Polynomial R)) [P.IsPrime]
    (hPeq : P = Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal)
    (hs : sectionPoly c ∉ P) :
    sectionRestrict c ((elementGenerator P (sectionPoly c) hs).divisor dimE) =
      AlgebraicCycle.singlePoint x := by
  classical
  have hlex : P ≤ (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal :=
    (le_sectionPoint_iff_of_eq c P x x hPeq).2 le_rfl
  have hQx := map_mk_sectionPoint_eq_span_of_eq c P x hPeq
  have hb0 : Ideal.Quotient.mk P (sectionPoly c) ≠ 0 := quotientMk_ne_zero P _ hs
  have hpx : (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal.IsPrime :=
    (sectionPoint c x : PrimeSpectrum (Polynomial R)).isPrime
  have hprimex : (Ideal.map (Ideal.Quotient.mk P)
      (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      (by rw [Ideal.mk_ker]; exact hlex)
  have hnotunit : ¬ IsUnit (Ideal.Quotient.mk P (sectionPoly c)) := by
    intro hu
    refine hprimex.ne_top ?_
    rw [hQx]
    exact Ideal.span_singleton_eq_top.2 hu
  have hheightx : (Ideal.map (Ideal.Quotient.mk P)
      (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal).height = 1 := by
    rw [hQx]
    exact Ideal.height_span_singleton_eq_one_of_mem_nonZeroDivisors
      (mem_nonZeroDivisors_of_ne_zero hb0) hnotunit
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp only [sectionRestrict_apply, AlgebraicCycle.singlePoint_apply]
  by_cases hle : P ≤ (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
  · rw [elementGenerator_divisor_apply_of_le P (sectionPoly c) hs dimE _ hle]
    by_cases hyx : y = x
    · subst hyx
      rw [if_pos rfl]
      have hcoheight : Order.coheight (quotientPoint P
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle) = 1 := by
        rw [coheight_eq_ideal_height (Polynomial R ⧸ P)
          (quotientPoint P (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
            (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle)]
        exact hheightx
      have hord := ord_algebraMap_eq_one (CommRingCat.of (Polynomial R ⧸ P))
        (quotientPoint P (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle)
        (Ideal.Quotient.mk P (sectionPoly c)) hb0 hcoheight
        (fun S _ _ _ ↦ by
          have hgoal : Ideal.map (Ideal.Quotient.mk P)
              (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal =
              Ideal.span {Ideal.Quotient.mk P (sectionPoly c)} := hQx
          change Ideal.map (algebraMap (Polynomial R ⧸ P) S)
            (Ideal.map (Ideal.Quotient.mk P) _) = _
          rw [hgoal, Ideal.map_span, Set.image_singleton])
      have hord' : ((Spec (CommRingCat.of (Polynomial R ⧸ P))).ord
          (elementFunction P (sectionPoly c) hs :
            (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionField)
          (quotientPoint P (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
            (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle) : ℤ) = 1 := hord
      rw [hord']
      norm_num
    · rw [if_neg hyx]
      have hple : (x : PrimeSpectrum R).asIdeal ≤ (y : PrimeSpectrum R).asIdeal :=
        (le_sectionPoint_iff_of_eq c P x y hPeq).1 hle
      have hltx : (sectionPoint c x : PrimeSpectrum (Polynomial R)).asIdeal <
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal := by
        refine lt_of_le_of_ne (Ideal.comap_mono hple) ?_
        intro heq
        exact hyx (sectionPoint_injective c (PrimeSpectrum.ext heq)).symm
      have hcoheight : Order.coheight (quotientPoint P
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle) ≠ 1 := by
        rw [coheight_eq_ideal_height (Polynomial R ⧸ P)
          (quotientPoint P (sectionPoint c y : PrimeSpectrum (Polynomial R)).asIdeal
            (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hle)]
        exact height_map_ne_one_of_lt P _ _
          (sectionPoint c x : PrimeSpectrum (Polynomial R)).isPrime
          (sectionPoint c y : PrimeSpectrum (Polynomial R)).isPrime hlex hle hltx hheightx
      rw [_root_.AlgebraicGeometry.Scheme.ord_eq_zero_of_coheight_neq_one hcoheight]
      norm_num
  · rw [elementGenerator_divisor_apply_of_not_le P (sectionPoly c) hs dimE _ hle, if_neg]
    intro hyx
    subst hyx
    exact hle hlex

/-- The Gysin summand of the section at the generic point of the fibre over `x` is the
single-point cycle at `x`. -/
theorem sectionGysinTerm_bundlePoint
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (x : ↥(Spec (CommRingCat.of R))) :
    sectionGysinTerm c dimE (bundlePoint (polyTrivialization R) x) =
      AlgebraicCycle.singlePoint x := by
  classical
  have hs : sectionPoly c ∉
      Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal :=
    sectionPoly_notMem_map c _ (x : PrimeSpectrum R).isPrime.ne_top
  have hs' : sectionPoly c ∉
      (bundlePoint (polyTrivialization R) x : PrimeSpectrum (Polynomial R)).asIdeal := hs
  have hP : (Ideal.map (algebraMap R (Polynomial R)) (x : PrimeSpectrum R).asIdeal).IsPrime :=
    isPrime_map_algebraMap (polyTrivialization R) x
  rw [sectionGysinTerm_of_notMem c dimE _ hs']
  exact sectionRestrict_divisor_sectionPoly c dimE x _ rfl hs'

/-- **(A)** The Gysin map of the section with constant value `c` inverts the flat pullback along
the trivial line bundle at the level of cycles: the section meets the fibre over each point of
the base transversally in exactly one point. -/
theorem sectionGysin_pullbackBundle
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (w : AlgebraicCycle (Spec (CommRingCat.of R)) ℚ) :
    sectionGysin c dimE (AlgebraicCycle.pullbackBundle (polyTrivialization R) w) = w := by
  classical
  rw [sectionGysin_apply]
  have hsupp : Function.support (fun V ↦
      (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V) ⊆
      Set.range (bundlePoint (polyTrivialization R)) := by
    intro V hV
    by_contra hmem
    refine hV ?_
    have hz : (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V = 0 :=
      AlgebraicCycle.pullbackBundleFun_eq_zero_of_notMem _ w hmem
    change (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
      ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V = 0
    rw [hz, zero_smul]
  have hind : Set.indicator (Set.range (bundlePoint (polyTrivialization R)))
      (fun V ↦ (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V) =
      fun V ↦ (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V :=
    Set.indicator_eq_self.2 hsupp
  have step : (∑ᶠ V, (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V) =
      ∑ᶠ x, (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (bundlePoint (polyTrivialization R) x) •
        sectionGysinTerm c dimE (bundlePoint (polyTrivialization R) x) := by
    rw [← finsum_mem_range (f := fun V ↦ (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V • sectionGysinTerm c dimE V)
      (bundlePoint_injective (polyTrivialization R)), finsum_mem_def, hind]
  rw [step]
  have hval : ∀ x : ↥(Spec (CommRingCat.of R)),
      (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
          ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (bundlePoint (polyTrivialization R) x) •
          sectionGysinTerm c dimE (bundlePoint (polyTrivialization R) x) =
        (w : ↥(Spec (CommRingCat.of R)) → ℚ) x • AlgebraicCycle.singlePoint x := by
    intro x
    have h1 : (AlgebraicCycle.pullbackBundle (polyTrivialization R) w :
        ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) (bundlePoint (polyTrivialization R) x) =
        (w : ↥(Spec (CommRingCat.of R)) → ℚ) x :=
      AlgebraicCycle.pullbackBundle_apply_bundlePoint _ w x
    rw [h1, sectionGysinTerm_bundlePoint c dimE x]
  simp only [hval]
  exact finsum_singlePoint_smul w

end Pullback

/-! ## Divisors on the components of the section -/

section GysinRelations

variable {R : Type u} [CommRing R] [IsNoetherianRing R] (c : R)

/-- Modulo a prime containing `T - c` every polynomial is congruent to a constant, so the
polynomial ring modulo such a prime is a quotient of the base ring itself. -/
noncomputable def sectionQuotientHom (Q : Ideal (Polynomial R)) : R →+* Polynomial R ⧸ Q :=
  (Ideal.Quotient.mk Q).comp (Polynomial.C : R →+* Polynomial R)

omit [IsNoetherianRing R] in
/-- Reduction modulo a prime containing `T - c` factors through evaluation at `c`. -/
theorem sectionQuotientHom_comp_evalRingHom (Q : Ideal (Polynomial R))
    (hQ : sectionPoly c ∈ Q) :
    (sectionQuotientHom Q).comp (Polynomial.evalRingHom c) = Ideal.Quotient.mk Q := by
  refine RingHom.ext fun f ↦ ?_
  obtain ⟨g, hg⟩ : sectionPoly c ∣ f - Polynomial.C (Polynomial.eval c f) := by
    simpa [sectionPoly] using Polynomial.X_sub_C_dvd_sub_C_eval (a := c) (p := f)
  have hmem : f - Polynomial.C (Polynomial.eval c f) ∈ Q := by
    rw [hg]
    exact Ideal.mul_mem_right _ _ hQ
  change Ideal.Quotient.mk Q (Polynomial.C (Polynomial.eval c f)) = Ideal.Quotient.mk Q f
  rw [eq_comm, ← sub_eq_zero, ← map_sub]
  exact Ideal.Quotient.eq_zero_iff_mem.2 hmem

omit [IsNoetherianRing R] in
/-- The base ring surjects onto the polynomial ring modulo a prime containing `T - c`. -/
theorem sectionQuotientHom_surjective (Q : Ideal (Polynomial R)) (hQ : sectionPoly c ∈ Q) :
    Function.Surjective (sectionQuotientHom Q) := by
  intro y
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective y
  exact ⟨Polynomial.eval c f, congrArg (fun h : Polynomial R →+* Polynomial R ⧸ Q ↦ h f)
    (sectionQuotientHom_comp_evalRingHom c Q hQ)⟩

/-- The subvariety `V(Q) ⊆ Spec R[T]` of a prime containing `T - c`, viewed as a closed
subscheme of the base through the section. -/
noncomputable def sectionQuotientImmersion (Q : Ideal (Polynomial R)) :
    Spec (CommRingCat.of (Polynomial R ⧸ Q)) ⟶ Spec (CommRingCat.of R) :=
  Spec.map (CommRingCat.ofHom (sectionQuotientHom Q))

omit [IsNoetherianRing R] in
/-- A prime containing `T - c` cuts out a closed subscheme of the base. -/
theorem isClosedImmersion_sectionQuotientImmersion (Q : Ideal (Polynomial R))
    (hQ : sectionPoly c ∈ Q) :
    _root_.AlgebraicGeometry.IsClosedImmersion (sectionQuotientImmersion Q) :=
  _root_.AlgebraicGeometry.IsClosedImmersion.spec_of_surjective _
    (sectionQuotientHom_surjective c Q hQ)

omit [IsNoetherianRing R] in
/-- The closed immersion of `V(Q)` into the total space factors through the section. -/
theorem sectionQuotientImmersion_comp (Q : Ideal (Polynomial R)) (hQ : sectionPoly c ∈ Q) :
    sectionQuotientImmersion Q ≫ sectionMap c = quotImmersion Q := by
  rw [sectionQuotientImmersion, sectionMap, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
    sectionQuotientHom_comp_evalRingHom c Q hQ]

/-- The principal-divisor generator on the base attached to a prime `Q` of `R[T]` containing
`T - c` and a polynomial `a ∉ Q`: the subvariety is `V(Q)`, viewed inside the base through the
section, and the rational function is the class of `a`. -/
noncomputable def sectionGenerator (Q : Ideal (Polynomial R)) [Q.IsPrime]
    (hQ : sectionPoly c ∈ Q) (a : Polynomial R) (ha : a ∉ Q) :
    RationalFunctionGenerator (Spec (CommRingCat.of R)) where
  subspace :=
    { scheme := Spec (CommRingCat.of (Polynomial R ⧸ Q))
      inclusion := sectionQuotientImmersion Q
      isClosedImmersion := isClosedImmersion_sectionQuotientImmersion c Q hQ }
  function := elementFunction Q a ha

/-- The restriction along the section of the divisor of `a` on a subvariety `V(Q)` contained in
the section is the divisor on the base of the corresponding generator.  Consequently it is an
actual principal divisor on the base. -/
theorem sectionRestrict_elementGenerator_divisor (Q : Ideal (Polynomial R)) [Q.IsPrime]
    (hQ : sectionPoly c ∈ Q) (a : Polynomial R) (ha : a ∉ Q)
    (dimX : DimensionFunction (Spec (CommRingCat.of R)))
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) :
    sectionRestrict c ((elementGenerator Q a ha).divisor dimE) =
      (sectionGenerator c Q hQ a ha).divisor dimX := by
  have hdimeq : (dimX : ↥(Spec (CommRingCat.of R)) → ℤ) =
      fun y ↦ (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ) ((sectionMap c).base y) :=
    funext fun y ↦ DimensionFunction.apply_eq_of_isClosedImmersion dimX dimE (sectionMap c) y
  have hcong := AlgebraicCycle.map_congr_hom (sectionQuotientImmersion_comp c Q hQ)
    (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ)
    ((Spec (CommRingCat.of (Polynomial R ⧸ Q))).principalCycle
      (elementFunction Q a ha : (Spec (CommRingCat.of (Polynomial R ⧸ Q))).functionField))
  have hclosed := (sectionGenerator c Q hQ a ha).map_divisor_closedImmersion (sectionMap c)
    dimX dimE
  rw [hdimeq] at hclosed
  have hdiv : (elementGenerator Q a ha).divisor dimE =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (sectionMap c)
        (fun y ↦ (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ) ((sectionMap c).base y))
        (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ)
        ((sectionGenerator c Q hQ a ha).divisor dimX) := by
    rw [hclosed]
    exact hcong.symm
  rw [hdiv]
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp only [sectionRestrict_apply]
  exact AlgebraicCycle.map_closedImmersion_apply_image (sectionMap c)
    (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ) _ y

/-- The restriction along the section of the divisor of `a` on a subvariety contained in the
section is a rational-equivalence relation on the base. -/
theorem sectionRestrict_elementGenerator_mem (Q : Ideal (Polynomial R)) [Q.IsPrime]
    (hQ : sectionPoly c ∈ Q) (a : Polynomial R) (ha : a ∉ Q)
    (dimX : DimensionFunction (Spec (CommRingCat.of R)))
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) :
    sectionRestrict c ((elementGenerator Q a ha).divisor dimE) ∈
      totalRationalRelations (Spec (CommRingCat.of R)) dimX := by
  rw [sectionRestrict_elementGenerator_divisor c Q hQ a ha dimX dimE]
  exact Submodule.subset_span ⟨sectionGenerator c Q hQ a ha, rfl⟩

/-! ## The Gysin image of a principal divisor -/

open Classical in
/-- The summand attached to a point `V` of the total space in the Gysin formula, for a general
polynomial `b` in place of the defining equation `T - c` of the section. -/
noncomputable def sectionGysinTermOf (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) (b : Polynomial R)
    (V : ↥(Spec (CommRingCat.of (Polynomial R)))) :
    AlgebraicCycle (Spec (CommRingCat.of R)) ℚ :=
  if h : b ∉ (V : PrimeSpectrum (Polynomial R)).asIdeal then
    sectionRestrict c
      ((@elementGenerator R _ _ (V : PrimeSpectrum (Polynomial R)).asIdeal
        (V : PrimeSpectrum (Polynomial R)).isPrime b h).divisor dimE)
  else 0

/-- The generalised Gysin summand at a point where `b` does not vanish identically. -/
theorem sectionGysinTermOf_of_notMem (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) (b : Polynomial R)
    (V : ↥(Spec (CommRingCat.of (Polynomial R))))
    (h : b ∉ (V : PrimeSpectrum (Polynomial R)).asIdeal) :
    sectionGysinTermOf c dimE b V =
      sectionRestrict c
        ((@elementGenerator R _ _ (V : PrimeSpectrum (Polynomial R)).asIdeal
          (V : PrimeSpectrum (Polynomial R)).isPrime b h).divisor dimE) := by
  classical
  rw [sectionGysinTermOf, dif_pos h]

/-- If a divisor on the total space is supported on subvarieties which lie inside the section
and on which `b` does not vanish identically, the corresponding Gysin sum is a
rational-equivalence relation on the base. -/
theorem finsum_sectionGysinTermOf_mem (c : R)
    (dimX : DimensionFunction (Spec (CommRingCat.of R)))
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R)))) (b : Polynomial R)
    (w : AlgebraicCycle (Spec (CommRingCat.of (Polynomial R))) ℚ)
    (hsupp : ∀ V : ↥(Spec (CommRingCat.of (Polynomial R))),
      (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V ≠ 0 →
        sectionPoly c ∈ (V : PrimeSpectrum (Polynomial R)).asIdeal ∧
          b ∉ (V : PrimeSpectrum (Polynomial R)).asIdeal) :
    (∑ᶠ V, (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
        sectionGysinTermOf c dimE b V) ∈
      totalRationalRelations (Spec (CommRingCat.of R)) dimX := by
  classical
  have hfin := AlgebraicCycle.finite_support w
  have hsub : Function.support (fun V ↦ (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
      sectionGysinTermOf c dimE b V) ⊆ (hfin.toFinset : Set _) := by
    intro V hV
    rw [Finset.mem_coe, Set.Finite.mem_toFinset, Function.mem_support]
    intro hz
    refine hV ?_
    change (w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
      sectionGysinTermOf c dimE b V = 0
    rw [hz, zero_smul]
  rw [finsum_eq_sum_of_support_subset _ hsub]
  refine Submodule.sum_mem _ fun V _ ↦ ?_
  rcases eq_or_ne ((w : ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V) 0 with h0 | h0
  · rw [h0, zero_smul]
    exact Submodule.zero_mem _
  · obtain ⟨hsV, hbV⟩ := hsupp V h0
    refine Submodule.smul_mem _ _ ?_
    rw [sectionGysinTermOf_of_notMem c dimE b V hbV]
    exact @sectionRestrict_elementGenerator_mem R _ _ c
      (V : PrimeSpectrum (Polynomial R)).asIdeal
      (V : PrimeSpectrum (Polynomial R)).isPrime hsV b hbV dimX dimE

/-- The divisor of the defining equation of the section on a subvariety `V(P)` not contained in
the section is supported on the components of the intersection `V(P) ∩ σ_c(X)`: each point of
its support is a prime strictly above `P`, contains `T - c`, and is minimal with these
properties. -/
theorem divisor_sectionPoly_support (c : R)
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (P : Ideal (Polynomial R)) [P.IsPrime] (hP : sectionPoly c ∉ P)
    (V : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hV : ((elementGenerator P (sectionPoly c) hP).divisor dimE :
      ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V ≠ 0) :
    P < (V : PrimeSpectrum (Polynomial R)).asIdeal ∧
      sectionPoly c ∈ (V : PrimeSpectrum (Polynomial R)).asIdeal ∧
      ∀ Q' : Ideal (Polynomial R), Q'.IsPrime → P ≤ Q' →
        Q' < (V : PrimeSpectrum (Polynomial R)).asIdeal → sectionPoly c ∉ Q' := by
  classical
  have hVp : (V : PrimeSpectrum (Polynomial R)).asIdeal.IsPrime :=
    (V : PrimeSpectrum (Polynomial R)).isPrime
  have hle : P ≤ (V : PrimeSpectrum (Polynomial R)).asIdeal := by
    by_contra h
    exact hV (elementGenerator_divisor_apply_of_not_le P _ hP dimE V h)
  rw [elementGenerator_divisor_apply_of_le P _ hP dimE V hle] at hV
  have hord : (Spec (CommRingCat.of (Polynomial R ⧸ P))).ord
      (elementFunction P (sectionPoly c) hP :
        (Spec (CommRingCat.of (Polynomial R ⧸ P))).functionField)
      (quotientPoint P (V : PrimeSpectrum (Polynomial R)).asIdeal
        (V : PrimeSpectrum (Polynomial R)).isPrime hle) ≠ 0 := by
    intro h
    rw [h] at hV
    norm_num at hV
  have hco : Order.coheight (quotientPoint P (V : PrimeSpectrum (Polynomial R)).asIdeal
      (V : PrimeSpectrum (Polynomial R)).isPrime hle) = 1 := by
    by_contra h
    exact hord (_root_.AlgebraicGeometry.Scheme.ord_eq_zero_of_coheight_neq_one h _)
  have hheight : (Ideal.map (Ideal.Quotient.mk P)
      (V : PrimeSpectrum (Polynomial R)).asIdeal).height = 1 :=
    (coheight_eq_ideal_height (Polynomial R ⧸ P)
      (quotientPoint P (V : PrimeSpectrum (Polynomial R)).asIdeal
        (V : PrimeSpectrum (Polynomial R)).isPrime hle)).symm.trans hco
  have hsmem : sectionPoly c ∈ (V : PrimeSpectrum (Polynomial R)).asIdeal := by
    by_contra hns
    refine hord (ord_algebraMap_eq_zero_of_notMem (CommRingCat.of (Polynomial R ⧸ P))
      (quotientPoint P (V : PrimeSpectrum (Polynomial R)).asIdeal
        (V : PrimeSpectrum (Polynomial R)).isPrime hle)
      (Ideal.Quotient.mk P (sectionPoly c)) ?_)
    intro hmem
    refine hns ?_
    have hmem' : Ideal.Quotient.mk P (sectionPoly c) ∈
        Ideal.map (Ideal.Quotient.mk P) (V : PrimeSpectrum (Polynomial R)).asIdeal := hmem
    rw [← comap_map_quotientMk P (V : PrimeSpectrum (Polynomial R)).asIdeal hle]
    exact hmem'
  refine ⟨lt_of_le_of_ne hle (fun heq ↦ hP (heq ▸ hsmem)), hsmem, ?_⟩
  intro Q' hQ' hPQ' hQV hsQ'
  have hmapQ' : (Ideal.map (Ideal.Quotient.mk P) Q').IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      (by rw [Ideal.mk_ker]; exact hPQ')
  have hmapV : (Ideal.map (Ideal.Quotient.mk P)
      (V : PrimeSpectrum (Polynomial R)).asIdeal).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      (by rw [Ideal.mk_ker]; exact hle)
  have hltmap : Ideal.map (Ideal.Quotient.mk P) Q' <
      Ideal.map (Ideal.Quotient.mk P) (V : PrimeSpectrum (Polynomial R)).asIdeal := by
    refine lt_of_le_of_ne (Ideal.map_mono hQV.le) ?_
    intro heq
    exact hQV.ne (by
      rw [← comap_map_quotientMk P Q' hPQ',
        ← comap_map_quotientMk P (V : PrimeSpectrum (Polynomial R)).asIdeal hle, heq])
  have hadd := Ideal.height_add_one_le_of_lt_of_isPrime hltmap
  rw [hheight] at hadd
  have h0 : (Ideal.map (Ideal.Quotient.mk P) Q').height = 0 := by
    by_contra h
    have h1 : (1 : ℕ∞) ≤ (Ideal.map (Ideal.Quotient.mk P) Q').height :=
      Order.one_le_iff_ne_zero.2 h
    have h2 : (1 : ℕ∞) + 1 ≤ (Ideal.map (Ideal.Quotient.mk P) Q').height + 1 := by gcongr
    exact absurd (h2.trans hadd) (by decide)
  have hbot : Ideal.map (Ideal.Quotient.mk P) Q' = ⊥ := Ideal.height_eq_zero_iff_eq_bot.1 h0
  have hQP : Q' = P := by
    rw [← comap_map_quotientMk P Q' hPQ', hbot, ← RingHom.ker_eq_comap_bot, Ideal.mk_ker]
  exact hP (hQP ▸ hsQ')

/-- **(B)** The Gysin image of the divisor of `a` on a subvariety `V(P)` in good position with
respect to the section is a rational-equivalence relation on the base.

The hypothesis `hident` is the cycle-level form of Fulton's symmetric local identity
(*Intersection Theory*, A.3): the two iterated divisors, first `T - c` then `a` and first `a`
then `T - c`, agree after restriction to the section.  It is a consequence of
`VectorBundle.LocalOrdSymmetry` together with the identification of the stalks of `Spec D` and
`Spec (D ⧸ q)` with localisations; that translation is *not* carried out here, so `hident` is
taken as an explicit hypothesis.  Everything else — that each term of the right-hand side is an
honest principal divisor on the base, and that the support of the divisor of `T - c` consists of
the components of `V(P) ∩ σ_c(X)`, on which `hgood` applies — is proved. -/
theorem sectionGysin_elementGenerator_mem (c : R)
    (dimX : DimensionFunction (Spec (CommRingCat.of R)))
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (P : Ideal (Polynomial R)) [P.IsPrime] (hP : sectionPoly c ∉ P)
    (a : Polynomial R) (ha : a ∉ P)
    (hgood : ∀ Q : Ideal (Polynomial R), Q.IsPrime → P < Q → sectionPoly c ∈ Q →
      (∀ Q' : Ideal (Polynomial R), Q'.IsPrime → P ≤ Q' → Q' < Q → sectionPoly c ∉ Q') →
      a ∉ Q)
    (hident : sectionGysin c dimE ((elementGenerator P a ha).divisor dimE) =
      ∑ᶠ V : ↥(Spec (CommRingCat.of (Polynomial R))),
        ((elementGenerator P (sectionPoly c) hP).divisor dimE :
          ↥(Spec (CommRingCat.of (Polynomial R))) → ℚ) V •
          sectionGysinTermOf c dimE a V) :
    sectionGysin c dimE ((elementGenerator P a ha).divisor dimE) ∈
      totalRationalRelations (Spec (CommRingCat.of R)) dimX := by
  rw [hident]
  refine finsum_sectionGysinTermOf_mem c dimX dimE a _ fun V hV ↦ ?_
  obtain ⟨hlt, hsmem, hmin⟩ := divisor_sectionPoly_support c dimE P hP V hV
  exact ⟨hsmem, hgood _ (V : PrimeSpectrum (Polynomial R)).isPrime hlt hsmem hmin⟩

end GysinRelations

end VectorBundle

end GromovWitten.AlgebraicGeometry.IntersectionTheory
