/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/

import GromovWitten.AlgebraicGeometry.IntersectionTheory.BundlePullbackChow
import Mathlib.RingTheory.KrullDimension.PID
import Mathlib.RingTheory.Localization.Algebra

/-!
# The rank-one key lemma for homotopy invariance of rational Chow groups

This file proves the heart of Fulton, *Intersection Theory*, Proposition 1.9 for a trivial line
bundle: if `V` is a subvariety of `E = X × 𝔸¹` (with `X = Spec R`) which dominates its image
`W = closure p` in `X` but is *not* the whole preimage of `W`, then there is a rational function
on the integral closed subscheme `π⁻¹(W) = Spec (R ⧸ p)[T]` whose principal divisor has
coefficient `1` at `V`, coefficient `0` at every other point over the generic point of `W`, and
is automatically supported over `W`.

## Contents

* `VectorBundle.algebraMap_functionField_eq_stalk`: the canonical map of the coordinate ring into
  the function field of an affine scheme factors through any stalk.
* `VectorBundle.ring_ord_eq_one_of_span_isMaximal`: an element generating a maximal ideal has
  length-theoretic order of vanishing one.
* `VectorBundle.ord_algebraMap_eq_zero_of_notMem` and `VectorBundle.ord_algebraMap_eq_one`: the
  two computations of `Scheme.ord` for a global section of an affine scheme, at a point where the
  section is a unit and at a codimension-one point where the section generates the maximal ideal
  of the stalk.
* `VectorBundle.exists_localGenerator`: the commutative-algebra core.  For a domain `D` and a
  nonzero prime `Pb` of `D[T]` contracting to `0` in `D`, there is a nonzero `r ∈ Pb` which
  generates `Pb` after localising at `Pb`, which lies in no other prime contracting to `0`, and
  `Pb` has height one.  The proof passes to `K[T]` (`K` the fraction field), where the extension
  of `Pb` is generated by an irreducible polynomial, and clears denominators.
* `VectorBundle.exists_generator_of_domain`: the resulting unit of the function field of
  `Spec D[T]` with its two order computations.
* `VectorBundle.exists_rankOne_generator`: the key lemma, in the exact form consumed by the
  proof of surjectivity of the flat pullback along an affine vector bundle.

No hypothesis beyond Noetherianity of the base is used, and no statement is left unproved.
-/

open CategoryTheory AlgebraicGeometry

universe u

namespace GromovWitten.AlgebraicGeometry.IntersectionTheory

namespace VectorBundle

/-! ## The order of vanishing of a global section of an affine scheme -/

/-- The ideal attached to a point of an affine scheme is prime.  This restates the field of
`PrimeSpectrum` in a shape which instance search finds for a point of `Spec B`. -/
instance (priority := 10000) isPrimeAsIdealSpec (B : CommRingCat.{u}) (q : ↥(Spec B)) :
    (q : PrimeSpectrum B).asIdeal.IsPrime :=
  (q : PrimeSpectrum B).isPrime

/-- The stalk of an affine scheme at a point is an algebra over the coordinate ring. -/
noncomputable instance (priority := low) algebraStalkSpec (B : CommRingCat.{u}) (q : ↥(Spec B)) :
    Algebra B ((Spec B).presheaf.stalk q) :=
  StructureSheaf.stalkAlgebra (R := B) q

/-- The stalk of an affine scheme at a point is the localisation at the corresponding prime. -/
instance (priority := 10000) isLocalizationStalkSpec (B : CommRingCat.{u}) (q : ↥(Spec B)) :
    IsLocalization.AtPrime ((Spec B).presheaf.stalk q) (q : PrimeSpectrum B).asIdeal :=
  StructureSheaf.IsLocalization.to_stalk (R := B) q

/-- The structure map of the function field of an integral affine scheme factors through the
stalk at any point: both maps are the germ at the generic point of the global section attached
to a ring element. -/
theorem algebraMap_functionField_eq_stalk (B : CommRingCat.{u}) [IsDomain B] (q : ↥(Spec B))
    (b : B) :
    algebraMap B (Spec B).functionField b =
      algebraMap ((Spec B).presheaf.stalk q) (Spec B).functionField
        (algebraMap B ((Spec B).presheaf.stalk q) b) := by
  have h1 : algebraMap B ((Spec B).presheaf.stalk q) b =
      (Spec B).presheaf.germ ⊤ q (TopologicalSpace.Opens.mem_top q)
        (algebraMap B Γ(Spec B, ⊤) b) :=
    (StructureSheaf.algebraMap_germ_apply (R := B) ⊤ q _ b).symm
  have h2 : algebraMap B (Spec B).functionField b =
      (Spec B).presheaf.germ ⊤ (genericPoint (Spec B))
        (TopologicalSpace.Opens.mem_top _) (algebraMap B Γ(Spec B, ⊤) b) :=
    (StructureSheaf.algebraMap_germ_apply (R := B) ⊤ (genericPoint (Spec B)) _ b).symm
  rw [h1, h2, RingHom.algebraMap_toAlgebra, ← ConcreteCategory.comp_apply,
    TopCat.Presheaf.germ_stalkSpecializes]

/-- A nonzero global section of an integral affine scheme, viewed as a unit of the function
field. -/
noncomputable def functionFieldUnit (B : CommRingCat.{u}) [IsDomain B] (b : B) (hb : b ≠ 0) :
    (Spec B).functionFieldˣ :=
  Units.mk0 (algebraMap B (Spec B).functionField b) fun hz =>
    hb (IsFractionRing.injective B (Spec B).functionField (by rw [hz, map_zero]))

/-- The underlying rational function of `functionFieldUnit` is the image of the section. -/
theorem functionFieldUnit_val (B : CommRingCat.{u}) [IsDomain B] (b : B) (hb : b ≠ 0) :
    (functionFieldUnit B b hb : (Spec B).functionField) =
      algebraMap B (Spec B).functionField b := rfl

/-- An element whose principal ideal is maximal has length-theoretic order of vanishing one:
the quotient by that ideal is a field, hence a simple module. -/
theorem ring_ord_eq_one_of_span_isMaximal {S : Type u} [CommRing S] {s : S}
    (h : (Ideal.span {s}).IsMaximal) : Ring.ord S s = 1 := by
  rw [Ring.ord, Module.length_eq_one_iff,
    isSimpleModule_iff_isSimpleModule_of_algebraMap_surjective (S := S ⧸ Ideal.span {s})
      Ideal.Quotient.mk_surjective]
  let _ := Ideal.Quotient.field (Ideal.span {s})
  exact instIsSimpleModule _

/-- The order of vanishing of a global section of an integral Noetherian affine scheme vanishes
at every point whose prime does not contain the section: it is then a unit of the stalk. -/
theorem ord_algebraMap_eq_zero_of_notMem (B : CommRingCat.{u}) [IsDomain B] [IsNoetherianRing B]
    (q : ↥(Spec B)) (b : B) (hb : b ∉ (q : PrimeSpectrum B).asIdeal) :
    (Spec B).ord (algebraMap B (Spec B).functionField b) q = 0 := by
  have hu : IsUnit (algebraMap B ((Spec B).presheaf.stalk q) b) :=
    IsLocalization.map_units ((Spec B).presheaf.stalk q)
      (⟨b, hb⟩ : (q : PrimeSpectrum B).asIdeal.primeCompl)
  rw [algebraMap_functionField_eq_stalk B q b]
  exact _root_.AlgebraicGeometry.Scheme.ord_algebraMap_of_isUnit hu

/-- The order of vanishing of a global section of an integral Noetherian affine scheme is one at
a codimension-one point at which the section generates the maximal ideal of the stalk. -/
theorem ord_algebraMap_eq_one (B : CommRingCat.{u}) [IsDomain B] [IsNoetherianRing B]
    (q : ↥(Spec B)) (b : B) (hb : b ≠ 0) (hq : Order.coheight q = 1)
    (hspan : ∀ (S : Type u) [CommRing S] [Algebra B S]
      [IsLocalization.AtPrime S (q : PrimeSpectrum B).asIdeal],
      Ideal.map (algebraMap B S) (q : PrimeSpectrum B).asIdeal =
        Ideal.span {algebraMap B S b}) :
    (Spec B).ord (algebraMap B (Spec B).functionField b) q = 1 := by
  have hmax : (Ideal.span {algebraMap B ((Spec B).presheaf.stalk q) b}).IsMaximal := by
    rw [← hspan ((Spec B).presheaf.stalk q),
      IsLocalization.AtPrime.map_eq_maximalIdeal (q : PrimeSpectrum B).asIdeal
        ((Spec B).presheaf.stalk q)]
    exact IsLocalRing.maximalIdeal.isMaximal _
  have hkd : Ring.KrullDimLE 1 ((Spec B).presheaf.stalk q) := krullDimLE_of_coheight_le hq.le
  have hnoeth : IsNoetherianRing ((Spec B).presheaf.stalk q) :=
    IsLocalization.isNoetherianRing (q : PrimeSpectrum B).asIdeal.primeCompl
      ((Spec B).presheaf.stalk q) inferInstance
  have hinj : Function.Injective (algebraMap B ((Spec B).presheaf.stalk q)) :=
    IsLocalization.injective ((Spec B).presheaf.stalk q)
      (Ideal.primeCompl_le_nonZeroDivisors (q : PrimeSpectrum B).asIdeal)
  have hu0 : algebraMap B ((Spec B).presheaf.stalk q) b ≠ 0 := fun hz =>
    hb (hinj (by rw [hz, map_zero]))
  have hfne : algebraMap B (Spec B).functionField b ≠ 0 := by
    rw [algebraMap_functionField_eq_stalk B q b]
    exact fun hz => hu0 (IsFractionRing.injective ((Spec B).presheaf.stalk q)
      (Spec B).functionField (by rw [hz, map_zero]))
  rw [_root_.AlgebraicGeometry.Scheme.ord_eq_iff hq hfne,
    show (Spec B).ordHom q hq = Ring.ordFrac ((Spec B).presheaf.stalk q) from rfl,
    algebraMap_functionField_eq_stalk B q b,
    Ring.ordFrac_eq_ord ((Spec B).presheaf.stalk q) hu0]
  exact Ring.ordMonoidWithZeroHom_eq_coe _ (mem_nonZeroDivisors_iff_ne_zero.mpr hu0)
    (by simpa using ring_ord_eq_one_of_span_isMaximal hmax)

/-! ## The commutative-algebra core -/

section RankOneAlgebra

attribute [local instance] Polynomial.algebra Polynomial.isLocalization

/-- The commutative-algebra core of Fulton's Proposition 1.9 in rank one.  Let `D` be a domain
and `Pb` a nonzero prime of `D[T]` whose contraction to `D` is zero.  Then `Pb` contains a
nonzero element `r` which generates `Pb` in any localisation of `D[T]` at `Pb`, which lies in no
other prime of `D[T]` with zero contraction, and `Pb` has height one.  The proof extends `Pb` to
the polynomial ring over the fraction field, which is a principal ideal domain, and clears
denominators in a generator. -/
theorem exists_localGenerator {D : Type u} [CommRing D] [IsDomain D]
    (Pb : Ideal (Polynomial D)) [hPb : Pb.IsPrime]
    (hbot : Pb.comap (Polynomial.C : D →+* Polynomial D) = ⊥) (hne : Pb ≠ ⊥) :
    ∃ r : Polynomial D, r ∈ Pb ∧ r ≠ 0 ∧ Pb.height = 1 ∧
      (∀ Q : Ideal (Polynomial D), Q.IsPrime →
        Q.comap (Polynomial.C : D →+* Polynomial D) = ⊥ → r ∈ Q → Q = Pb) ∧
      ∀ (S : Type u) [CommRing S] [Algebra (Polynomial D) S] [IsLocalization.AtPrime S Pb],
        Pb.map (algebraMap (Polynomial D) S) =
          Ideal.span {algebraMap (Polynomial D) S r} := by
  classical
  set K := FractionRing D with hK
  set M : Submonoid (Polynomial D) :=
    (nonZeroDivisors D).map (Polynomial.C : D →+* Polynomial D) with hM
  have hdisj : ∀ Q : Ideal (Polynomial D),
      Q.comap (Polynomial.C : D →+* Polynomial D) = ⊥ →
      Disjoint (M : Set (Polynomial D)) (Q : Set (Polynomial D)) := by
    intro Q hQ
    rw [Set.disjoint_left]
    rintro x ⟨d, hd, rfl⟩ hxQ
    have hmem : d ∈ Q.comap (Polynomial.C : D →+* Polynomial D) := hxQ
    rw [hQ] at hmem
    exact (mem_nonZeroDivisors_iff_ne_zero.mp hd) (Ideal.mem_bot.mp hmem)
  have hinj : Function.Injective (algebraMap (Polynomial D) (Polynomial K)) := by
    rw [Polynomial.algebraMap_def]
    simpa using Polynomial.map_injective (algebraMap D K)
      (FaithfulSMul.algebraMap_injective D K)
  have hPbdisj := hdisj Pb hbot
  have hPrime' : (Pb.map (algebraMap (Polynomial D) (Polynomial K))).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint M (Polynomial K) Pb hPb hPbdisj
  have hne' : Pb.map (algebraMap (Polynomial D) (Polynomial K)) ≠ ⊥ := by
    obtain ⟨b, hbPb, hb0⟩ := (Submodule.ne_bot_iff _).mp hne
    rw [Submodule.ne_bot_iff]
    exact ⟨algebraMap _ _ b, Ideal.mem_map_of_mem _ hbPb,
      fun hz => hb0 (hinj (by rw [hz, map_zero]))⟩
  have hmax' : (Pb.map (algebraMap (Polynomial D) (Polynomial K))).IsMaximal :=
    _root_.IsPrime.to_maximal_ideal hne'
  have hheight : Pb.height = 1 := by
    rw [← IsLocalization.height_map_of_disjoint (S := Polynomial K) M Pb hPbdisj]
    exact IsPrincipalIdealRing.height_eq_one_of_isMaximal _ (Polynomial.not_isField K)
  have hr₀span : Ideal.span
      {Submodule.IsPrincipal.generator (Pb.map (algebraMap (Polynomial D) (Polynomial K)))} =
      Pb.map (algebraMap (Polynomial D) (Polynomial K)) :=
    Submodule.IsPrincipal.span_singleton_generator _
  have hr₀mem :
      Submodule.IsPrincipal.generator (Pb.map (algebraMap (Polynomial D) (Polynomial K))) ∈
        Pb.map (algebraMap (Polynomial D) (Polynomial K)) :=
    Submodule.IsPrincipal.generator_mem _
  obtain ⟨⟨⟨r, hrmem⟩, ⟨m, hm⟩⟩, hEq⟩ :=
    (IsLocalization.mem_map_algebraMap_iff M (Polynomial K)).mp hr₀mem
  have hunitm : IsUnit (algebraMap (Polynomial D) (Polynomial K) m) :=
    IsLocalization.map_units (Polynomial K) (⟨m, hm⟩ : M)
  have hspanK : Ideal.span {algebraMap (Polynomial D) (Polynomial K) r} =
      Pb.map (algebraMap (Polynomial D) (Polynomial K)) := by
    rw [← hEq, Ideal.span_singleton_mul_right_unit hunitm, hr₀span]
  have hr0 : r ≠ 0 := by
    intro hz
    refine hne' (hspanK.symm.trans ?_)
    rw [hz, map_zero]
    exact Ideal.span_singleton_eq_bot.mpr rfl
  refine ⟨r, hrmem, hr0, hheight, ?_, ?_⟩
  · intro Q hQp hQbot hQr
    have hQdisj := hdisj Q hQbot
    have hQ' : (Q.map (algebraMap (Polynomial D) (Polynomial K))).IsPrime :=
      IsLocalization.isPrime_of_isPrime_disjoint M (Polynomial K) Q hQp hQdisj
    have hle : Pb.map (algebraMap (Polynomial D) (Polynomial K)) ≤
        Q.map (algebraMap (Polynomial D) (Polynomial K)) := by
      rw [← hspanK, Ideal.span_le, Set.singleton_subset_iff]
      exact Ideal.mem_map_of_mem _ hQr
    have heq : Pb.map (algebraMap (Polynomial D) (Polynomial K)) =
        Q.map (algebraMap (Polynomial D) (Polynomial K)) :=
      hmax'.eq_of_le hQ'.ne_top hle
    have h1 := IsLocalization.under_map_of_isPrime_disjoint M (Polynomial K) hPb hPbdisj
    have h2 := IsLocalization.under_map_of_isPrime_disjoint M (Polynomial K) hQp hQdisj
    rw [heq] at h1
    exact h2.symm.trans h1
  · intro S _ _ _
    refine le_antisymm ?_ ?_
    · rw [Ideal.map_le_iff_le_comap]
      intro f hf
      have hfK : algebraMap (Polynomial D) (Polynomial K) f ∈
          Ideal.span {algebraMap (Polynomial D) (Polynomial K) r} := by
        rw [hspanK]
        exact Ideal.mem_map_of_mem _ hf
      obtain ⟨g, hg⟩ := Ideal.mem_span_singleton'.mp hfK
      obtain ⟨⟨n, d⟩, hnd⟩ := IsLocalization.mk'_surjective M g
      have hψn : algebraMap (Polynomial D) (Polynomial K) n =
          g * algebraMap (Polynomial D) (Polynomial K) (d : Polynomial D) := by
        rw [← hnd]
        exact (IsLocalization.mk'_spec (Polynomial K) n d).symm
      have hfe : n * r = f * (d : Polynomial D) := by
        apply hinj
        rw [map_mul, map_mul, hψn, mul_assoc,
          mul_comm (algebraMap (Polynomial D) (Polynomial K) (d : Polynomial D))
            (algebraMap (Polynomial D) (Polynomial K) r), ← mul_assoc, hg]
      have hdc : (d : Polynomial D) ∈ Pb.primeCompl := fun hcon =>
        Set.disjoint_left.mp hPbdisj d.2 hcon
      obtain ⟨u, hu⟩ : IsUnit (algebraMap (Polynomial D) S (d : Polynomial D)) :=
        IsLocalization.map_units S (⟨(d : Polynomial D), hdc⟩ : Pb.primeCompl)
      refine Ideal.mem_span_singleton'.mpr ⟨(↑u⁻¹ : S) * algebraMap (Polynomial D) S n, ?_⟩
      have key : algebraMap (Polynomial D) S n * algebraMap (Polynomial D) S r =
          algebraMap (Polynomial D) S f * (u : S) := by
        rw [hu, ← map_mul, ← map_mul, hfe]
      calc ((↑u⁻¹ : S) * algebraMap (Polynomial D) S n) * algebraMap (Polynomial D) S r
          = (↑u⁻¹ : S) *
            (algebraMap (Polynomial D) S n * algebraMap (Polynomial D) S r) := mul_assoc _ _ _
        _ = (↑u⁻¹ : S) * (algebraMap (Polynomial D) S f * (u : S)) := by rw [key]
        _ = algebraMap (Polynomial D) S f := by
            rw [mul_comm (algebraMap (Polynomial D) S f) (u : S), Units.inv_mul_cancel_left]
    · rw [Ideal.span_le, Set.singleton_subset_iff]
      exact Ideal.mem_map_of_mem _ hrmem

end RankOneAlgebra

/-! ## The generator on the trivial line bundle over an integral base -/

/-- The rank-one key lemma over an integral Noetherian affine base, before descent along the
closed immersion of the base.  A nonzero prime of `D[T]` with zero contraction to `D` carries a
rational function of `Spec D[T]` whose principal divisor is `1` at that point and `0` at every
other point with zero contraction. -/
theorem exists_generator_of_domain {D : Type u} [CommRing D] [IsDomain D] [IsNoetherianRing D]
    (Pb : ↥(Spec (CommRingCat.of (Polynomial D))))
    (hbot : Pb.asIdeal.comap (Polynomial.C : D →+* Polynomial D) = ⊥)
    (hne : Pb.asIdeal ≠ ⊥) :
    ∃ f : (Spec (CommRingCat.of (Polynomial D))).functionFieldˣ,
      (Spec (CommRingCat.of (Polynomial D))).ord
          (f : (Spec (CommRingCat.of (Polynomial D))).functionField) Pb = 1 ∧
        ∀ Q : ↥(Spec (CommRingCat.of (Polynomial D))), Q ≠ Pb →
          Q.asIdeal.comap (Polynomial.C : D →+* Polynomial D) = ⊥ →
          (Spec (CommRingCat.of (Polynomial D))).ord
            (f : (Spec (CommRingCat.of (Polynomial D))).functionField) Q = 0 := by
  have hdomB : IsDomain ↑(CommRingCat.of (Polynomial D)) :=
    inferInstanceAs (IsDomain (Polynomial D))
  have hnoethB : IsNoetherianRing ↑(CommRingCat.of (Polynomial D)) :=
    inferInstanceAs (IsNoetherianRing (Polynomial D))
  have hPbprime : (Pb.asIdeal : Ideal (Polynomial D)).IsPrime := Pb.isPrime
  obtain ⟨r, hrmem, hr0, hheight, huniq, hspan⟩ :=
    exists_localGenerator Pb.asIdeal hbot hne
  have hcoheight : Order.coheight Pb = 1 := by
    rw [coheight_eq_ideal_height (Polynomial D) Pb]
    exact hheight
  refine ⟨functionFieldUnit (CommRingCat.of (Polynomial D)) r hr0, ?_, ?_⟩
  · exact ord_algebraMap_eq_one (CommRingCat.of (Polynomial D)) Pb r hr0 hcoheight
      (fun S i1 i2 i3 => @hspan S i1 i2 i3)
  · intro Q hQ hQbot
    refine ord_algebraMap_eq_zero_of_notMem (CommRingCat.of (Polynomial D)) Q r fun hcon => ?_
    exact hQ (PrimeSpectrum.ext (huniq Q.asIdeal Q.isPrime hQbot hcon))

/-! ## Reduction of a polynomial ring modulo a prime of the base -/

/-- Contracting back an extended ideal along the reduction of coefficients modulo `p` returns the
ideal, provided it contains the extension of `p`. -/
theorem comap_map_mapRingHom {R : Type u} [CommRing R] (p : Ideal R) (Q : Ideal (Polynomial R))
    (hle : Ideal.map (Polynomial.C : R →+* Polynomial R) p ≤ Q) :
    Ideal.comap (Polynomial.mapRingHom (Ideal.Quotient.mk p))
        (Ideal.map (Polynomial.mapRingHom (Ideal.Quotient.mk p)) Q) = Q := by
  have hsurj : Function.Surjective ⇑(Polynomial.mapRingHom (Ideal.Quotient.mk p)) := by
    simpa using Polynomial.map_surjective (Ideal.Quotient.mk p) Ideal.Quotient.mk_surjective
  rw [Ideal.comap_map_of_surjective _ hsurj, ← RingHom.ker_eq_comap_bot,
    Polynomial.ker_mapRingHom, Ideal.mk_ker]
  exact sup_eq_left.mpr hle

/-- If a prime of `R[T]` contracts exactly to `p` in `R`, then its image in `(R ⧸ p)[T]`
contracts to zero. -/
theorem comap_C_map_mapRingHom_eq_bot {R : Type u} [CommRing R] (p : Ideal R)
    (Q : Ideal (Polynomial R)) (hQ : Q.comap (Polynomial.C : R →+* Polynomial R) = p)
    (hle : Ideal.map (Polynomial.C : R →+* Polynomial R) p ≤ Q) :
    (Ideal.map (Polynomial.mapRingHom (Ideal.Quotient.mk p)) Q).comap
        (Polynomial.C : (R ⧸ p) →+* Polynomial (R ⧸ p)) = ⊥ := by
  rw [Submodule.eq_bot_iff]
  intro x hx
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
  have hCa : Polynomial.mapRingHom (Ideal.Quotient.mk p) (Polynomial.C a) ∈
      Ideal.map (Polynomial.mapRingHom (Ideal.Quotient.mk p)) Q := by
    simpa using hx
  have hmem : Polynomial.C a ∈ Q := by
    rw [← comap_map_mapRingHom p Q hle]
    exact hCa
  have hap : a ∈ p := by
    rw [← hQ]
    exact hmem
  exact Ideal.Quotient.eq_zero_iff_mem.mpr hap

/-! ## The key lemma -/

/-- Fulton, *Intersection Theory*, the heart of Proposition 1.9, for a trivial line bundle.  If
the point `P` of `E = Spec R[T]` is not the generic point of the preimage of its image `p` in
`Spec R`, then there is a principal-divisor generator on `E` whose divisor is supported over the
closure of `p`, has coefficient `1` at `P`, and coefficient `0` at every other point over `p`. -/
theorem exists_rankOne_generator {R : Type u} [CommRing R] [IsNoetherianRing R]
    (dimE : DimensionFunction (Spec (CommRingCat.of (Polynomial R))))
    (P : ↥(Spec (CommRingCat.of (Polynomial R))))
    (hP : P.asIdeal ≠ (P.asIdeal.comap (Polynomial.C : R →+* Polynomial R)).map Polynomial.C) :
    ∃ g : RationalFunctionGenerator (Spec (CommRingCat.of (Polynomial R))),
      (∀ x, g.divisor dimE x ≠ 0 →
        P.asIdeal.comap (Polynomial.C : R →+* Polynomial R) ≤ x.asIdeal.comap Polynomial.C) ∧
      g.divisor dimE P = 1 ∧
      ∀ Q, Q ≠ P → Q.asIdeal.comap (Polynomial.C : R →+* Polynomial R) =
          P.asIdeal.comap Polynomial.C → g.divisor dimE Q = 0 := by
  classical
  have hPprime : (P.asIdeal : Ideal (Polynomial R)).IsPrime := P.isPrime
  set p : Ideal R := P.asIdeal.comap (Polynomial.C : R →+* Polynomial R) with hpdef
  have hpprime : p.IsPrime := by
    rw [hpdef]
    infer_instance
  set φ : Polynomial R →+* Polynomial (R ⧸ p) :=
    Polynomial.mapRingHom (Ideal.Quotient.mk p) with hφdef
  have hφsurj : Function.Surjective ⇑φ := by
    rw [hφdef]
    simpa using Polynomial.map_surjective (Ideal.Quotient.mk p) Ideal.Quotient.mk_surjective
  have hker : RingHom.ker φ = p.map (Polynomial.C : R →+* Polynomial R) := by
    rw [hφdef, Polynomial.ker_mapRingHom, Ideal.mk_ker]
  have hPle : Ideal.map (Polynomial.C : R →+* Polynomial R) p ≤ P.asIdeal := by
    rw [Ideal.map_le_iff_le_comap, hpdef]
  have hkerle : RingHom.ker φ ≤ P.asIdeal := by
    rw [hker]
    exact hPle
  have hPbprime : (P.asIdeal.map φ).IsPrime :=
    Ideal.map_isPrime_of_surjective hφsurj hkerle
  have hcomapPb : (P.asIdeal.map φ).comap φ = P.asIdeal := by
    rw [hφdef]
    exact comap_map_mapRingHom p P.asIdeal hPle
  have hPbne : P.asIdeal.map φ ≠ ⊥ := by
    intro hz
    refine hP ?_
    rw [← hcomapPb, hz, ← RingHom.ker_eq_comap_bot, hker]
  have hPbbot : (P.asIdeal.map φ).comap (Polynomial.C : (R ⧸ p) →+* Polynomial (R ⧸ p)) = ⊥ := by
    rw [hφdef]
    exact comap_C_map_mapRingHom_eq_bot p P.asIdeal hpdef.symm hPle
  obtain ⟨f, hf1, hf0⟩ := exists_generator_of_domain
    (D := R ⧸ p) (⟨P.asIdeal.map φ, hPbprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p)))
    hPbbot hPbne
  have hclosed : _root_.AlgebraicGeometry.IsClosedImmersion
      (Spec.map (CommRingCat.ofHom φ)) :=
    _root_.AlgebraicGeometry.IsClosedImmersion.spec_of_surjective _ hφsurj
  have hdivisor : (⟨⟨Spec (CommRingCat.of (Polynomial (R ⧸ p))),
        Spec.map (CommRingCat.ofHom φ)⟩, f⟩ :
        RationalFunctionGenerator (Spec (CommRingCat.of (Polynomial R)))).divisor dimE =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (Spec.map (CommRingCat.ofHom φ))
        (fun z ↦ (dimE : ↥(Spec (CommRingCat.of (Polynomial R))) → ℤ)
          ((Spec.map (CommRingCat.ofHom φ)).base z)) (⇑dimE)
        ((Spec (CommRingCat.of (Polynomial (R ⧸ p)))).principalCycle
          (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField)) := rfl
  refine ⟨⟨⟨Spec (CommRingCat.of (Polynomial (R ⧸ p))),
    Spec.map (CommRingCat.ofHom φ)⟩, f⟩, ?_, ?_, ?_⟩
  · intro x hx
    by_contra hcon
    refine hx ?_
    have hnr : x ∉ Set.range (Spec.map (CommRingCat.ofHom φ)).base := by
      rintro ⟨y, rfl⟩
      refine hcon ?_
      intro a ha
      have hz : φ (Polynomial.C a) = 0 := by
        rw [hφdef]
        simp [Ideal.Quotient.eq_zero_iff_mem.mpr ha]
      have hmem : Polynomial.C a ∈
          ((Spec.map (CommRingCat.ofHom φ)).base y :
            PrimeSpectrum (Polynomial R)).asIdeal := by
        change φ (Polynomial.C a) ∈ (y : PrimeSpectrum (Polynomial (R ⧸ p))).asIdeal
        rw [hz]
        exact Ideal.zero_mem _
      exact hmem
    rw [hdivisor]
    exact AlgebraicCycle.map_closedImmersion_apply_of_not_mem_range
      (Spec.map (CommRingCat.ofHom φ)) (⇑dimE) _ x hnr
  · have hPimage : (Spec.map (CommRingCat.ofHom φ)).base
        (⟨P.asIdeal.map φ, hPbprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) = P :=
      PrimeSpectrum.ext hcomapPb
    have hcycle : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).principalCycle
        (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField)
        (⟨P.asIdeal.map φ, hPbprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) =
        (((Spec (CommRingCat.of (Polynomial (R ⧸ p)))).ord
          (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField)
          (⟨P.asIdeal.map φ, hPbprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) : ℤ) : ℚ) := rfl
    have hval := AlgebraicCycle.map_closedImmersion_apply_image
      (Spec.map (CommRingCat.ofHom φ)) (⇑dimE)
      ((Spec (CommRingCat.of (Polynomial (R ⧸ p)))).principalCycle
        (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField))
      (⟨P.asIdeal.map φ, hPbprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p)))
    rw [← hPimage, hdivisor, hval, hcycle, hf1]
    norm_num
  · intro Q hQP hQp
    have hQprime0 : (Q.asIdeal : Ideal (Polynomial R)).IsPrime := Q.isPrime
    have hQle : Ideal.map (Polynomial.C : R →+* Polynomial R) p ≤ Q.asIdeal := by
      rw [Ideal.map_le_iff_le_comap, ← hQp]
    have hQprime : (Q.asIdeal.map φ).IsPrime := by
      refine Ideal.map_isPrime_of_surjective hφsurj ?_
      rw [hker]
      exact hQle
    have hcomapQ : (Q.asIdeal.map φ).comap φ = Q.asIdeal := by
      rw [hφdef]
      exact comap_map_mapRingHom p Q.asIdeal hQle
    have hQimage : (Spec.map (CommRingCat.ofHom φ)).base
        (⟨Q.asIdeal.map φ, hQprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) = Q :=
      PrimeSpectrum.ext hcomapQ
    have hQbot : (Q.asIdeal.map φ).comap
        (Polynomial.C : (R ⧸ p) →+* Polynomial (R ⧸ p)) = ⊥ := by
      rw [hφdef]
      exact comap_C_map_mapRingHom_eq_bot p Q.asIdeal hQp hQle
    have hQne : (⟨Q.asIdeal.map φ, hQprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) ≠
        ⟨P.asIdeal.map φ, hPbprime⟩ := by
      intro hcon
      refine hQP ?_
      rw [← hQimage, hcon]
      exact PrimeSpectrum.ext hcomapPb
    have hcycle : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).principalCycle
        (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField)
        (⟨Q.asIdeal.map φ, hQprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) =
        (((Spec (CommRingCat.of (Polynomial (R ⧸ p)))).ord
          (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField)
          (⟨Q.asIdeal.map φ, hQprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p))) : ℤ) : ℚ) := rfl
    have hval := AlgebraicCycle.map_closedImmersion_apply_image
      (Spec.map (CommRingCat.ofHom φ)) (⇑dimE)
      ((Spec (CommRingCat.of (Polynomial (R ⧸ p)))).principalCycle
        (f : (Spec (CommRingCat.of (Polynomial (R ⧸ p)))).functionField))
      (⟨Q.asIdeal.map φ, hQprime⟩ : PrimeSpectrum (Polynomial (R ⧸ p)))
    rw [← hQimage, hdivisor, hval, hcycle, hf0 _ hQne hQbot]
    norm_num

end VectorBundle

end GromovWitten.AlgebraicGeometry.IntersectionTheory
