/-
Copyright (c) 2026 GromovWitten Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/

import Mathlib.AlgebraicGeometry.AlgebraicCycle.Basic
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
import Mathlib.AlgebraicGeometry.Morphisms.Etale
import Mathlib.AlgebraicGeometry.OrderOfVanishing
import Mathlib.Algebra.Module.MinimalAxioms
import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.RingTheory.Length
import Mathlib.RingTheory.LocalRing.Length
import Mathlib.RingTheory.TensorProduct.Quotient
import Mathlib.RingTheory.Unramified.LocalRing

/-!
# Dimension-graded rational Chow groups

Mathlib's `AlgebraicCycle X ℚ` supplies locally finite rational cycles on a scheme.  This file
cuts out one dimension at a time and forms the quotient by the additive subgroup generated by
principal-divisor relations.

Principal-divisor generators are actual integral closed subschemes together with nonzero elements
of their function fields.  Their divisor cycles are constructed from order of vanishing and
Mathlib's pushforward of algebraic cycles.  Thus the rational-equivalence system below contains no
caller-selected carrier or divisor map.
-/

open CategoryTheory TopologicalSpace Topology Order

attribute [local instance] specializationOrder

/-! ## Etale invariance of the length order -/

/-- A flat formally unramified local extension preserves the length-based order of every ring
element.  Flat base change identifies the quotient by `a` with the quotient by its image, while
formal unramifiedness identifies the extended maximal ideal with the target maximal ideal; the
remaining residue-field quotient has length one. -/
theorem Ring.ord_algebraMap_of_flat_formallyUnramified_local
    {R S : Type*} [CommRing R] [CommRing S] [IsLocalRing R] [IsLocalRing S]
    [Algebra R S] [IsLocalHom (algebraMap R S)] [Module.Flat R S]
    [Algebra.FormallyUnramified R S] [Algebra.EssFiniteType R S] (a : R) :
    Ring.ord S (algebraMap R S a) = Ring.ord R a := by
  unfold Ring.ord
  have hmap : (Ideal.span {a}).map (algebraMap R S) =
      Ideal.span {algebraMap R S a} := by
    rw [Ideal.map_span]
    congr 1
    simp
  rw [← hmap]
  rw [(Algebra.TensorProduct.quotIdealMapEquivTensorQuot S
    (Ideal.span {a})).toLinearEquiv.length_eq]
  rw [IsLocalRing.length_baseChange]
  rw [Algebra.FormallyUnramified.map_maximalIdeal]
  have hresidue : Module.length S (S ⧸ IsLocalRing.maximalIdeal S) = 1 := by
    rw [Module.length_eq_one_iff]
    rw [isSimpleModule_iff_isSimpleModule_of_algebraMap_surjective
      (S := S ⧸ IsLocalRing.maximalIdeal S) Ideal.Quotient.mk_surjective]
    let _ := Ideal.Quotient.field (IsLocalRing.maximalIdeal S)
    exact instIsSimpleModule _
  rw [hresidue, mul_one]

/-- The zero-preserving multiplicative order has the same compatibility with a flat formally
unramified local extension of Noetherian one-dimensional domains. -/
theorem Ring.ordMonoidWithZeroHom_algebraMap_of_flat_formallyUnramified_local
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsNoetherianRing R] [IsNoetherianRing S]
    [Ring.KrullDimLE 1 R] [Ring.KrullDimLE 1 S]
    [IsLocalRing R] [IsLocalRing S] [Algebra R S]
    [IsLocalHom (algebraMap R S)] [Module.Flat R S]
    [Algebra.FormallyUnramified R S] [Algebra.EssFiniteType R S] (a : R) :
    Ring.ordMonoidWithZeroHom S (algebraMap R S a) =
      Ring.ordMonoidWithZeroHom R a := by
  by_cases ha : a = 0
  · subst a
    simp
  let _ : Module.FaithfullyFlat R S :=
    Module.FaithfullyFlat.of_flat_of_isLocalHom
  have hmap : algebraMap R S a ≠ 0 := by
    simpa using (FaithfulSMul.algebraMap_injective R S).ne ha
  rw [Ring.ordMonoidWithZeroHom_eq_ord (mem_nonZeroDivisors_of_ne_zero hmap),
    Ring.ordMonoidWithZeroHom_eq_ord (mem_nonZeroDivisors_of_ne_zero ha),
    Ring.ord_algebraMap_of_flat_formallyUnramified_local]

/-- Passing to fraction fields, a flat formally unramified local extension of Noetherian
one-dimensional domains preserves the fractional order.  The two scalar-tower hypotheses state
that the displayed map of fraction fields extends the given local-ring map. -/
theorem Ring.ordFrac_algebraMap_of_flat_formallyUnramified_local
    {R S K L : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsNoetherianRing R] [IsNoetherianRing S]
    [Ring.KrullDimLE 1 R] [Ring.KrullDimLE 1 S]
    [IsLocalRing R] [IsLocalRing S] [Field K] [Field L]
    [Algebra R S] [Algebra R K] [IsFractionRing R K]
    [Algebra S L] [IsFractionRing S L] [Algebra K L] [Algebra R L]
    [IsScalarTower R S L] [IsScalarTower R K L]
    [IsLocalHom (algebraMap R S)] [Module.Flat R S]
    [Algebra.FormallyUnramified R S] [Algebra.EssFiniteType R S] (q : K) :
    Ring.ordFrac S (algebraMap K L q) = Ring.ordFrac R q := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := R) q
  by_cases ha : a = 0
  · subst a
    simp
  have hb0 : b ≠ 0 := by
    simpa [mem_nonZeroDivisors_iff_ne_zero] using hb
  let _ : Module.FaithfullyFlat R S :=
    Module.FaithfullyFlat.of_flat_of_isLocalHom
  have hma : algebraMap R S a ≠ 0 := by
    simpa using (FaithfulSMul.algebraMap_injective R S).ne ha
  have hmb : algebraMap R S b ≠ 0 := by
    simpa using (FaithfulSMul.algebraMap_injective R S).ne hb0
  simp only [map_div₀]
  rw [show algebraMap K L (algebraMap R K a) =
      algebraMap S L (algebraMap R S a) by
        rw [← IsScalarTower.algebraMap_apply R K L,
          ← IsScalarTower.algebraMap_apply R S L],
    show algebraMap K L (algebraMap R K b) =
      algebraMap S L (algebraMap R S b) by
        rw [← IsScalarTower.algebraMap_apply R K L,
          ← IsScalarTower.algebraMap_apply R S L]]
  rw [Ring.ordFrac_eq_ord S hma, Ring.ordFrac_eq_ord S hmb,
    Ring.ordFrac_eq_ord R ha, Ring.ordFrac_eq_ord R hb0,
    Ring.ordMonoidWithZeroHom_algebraMap_of_flat_formallyUnramified_local,
    Ring.ordMonoidWithZeroHom_algebraMap_of_flat_formallyUnramified_local]

/-! Mathlib's locally finite functions currently carry their additive group structure, but not
scalar multiplication by the coefficient field.  Rational algebraic cycles therefore need the
following pointwise module instance before one can form the rational span of principal divisors.
The support of a scalar multiple is contained in the original support, so local finiteness is
preserved. -/

namespace Function.locallyFinsuppWithin

universe v

variable {T : Type v} [TopologicalSpace T] {U : Set T}

instance rationalSMul : SMul ℚ (locallyFinsuppWithin U ℚ) where
  smul q D := mk_of_mem_addSubgroup (q • (D : T → ℚ)) <| by
    constructor
    · exact (Function.support_const_smul_subset q (D : T → ℚ)).trans D.supportWithinDomain
    · intro z hz
      obtain ⟨t, ht, hfinite⟩ := D.supportLocallyFiniteWithinDomain z hz
      exact ⟨t, ht, hfinite.subset (Set.inter_subset_inter_right t
        (Function.support_const_smul_subset q (D : T → ℚ)))⟩

@[simp]
theorem coe_rational_smul (q : ℚ) (D : locallyFinsuppWithin U ℚ) :
    ((q • D : locallyFinsuppWithin U ℚ) : T → ℚ) = q • (D : T → ℚ) :=
  rfl

instance rationalModule : Module ℚ (locallyFinsuppWithin U ℚ) :=
  Module.ofMinimalAxioms
    (by
      intro q D E
      apply coe_injective
      ext x
      exact mul_add q (D x) (E x))
    (by
      intro q r D
      apply coe_injective
      ext x
      simp [add_mul])
    (by
      intro q r D
      apply coe_injective
      ext x
      simp [mul_assoc])
    (by
      intro D
      apply coe_injective
      ext x
      simp)

end Function.locallyFinsuppWithin

/-! ## Principal cycles on schemes

The order-of-vanishing function supplied by Mathlib is defined pointwise.  To obtain an algebraic
cycle one still has to prove that its support is locally finite.  The proof below is geometric:
locally choose a Noetherian affine neighbourhood; away from an open set on which the rational
function is a unit, the codimension-one support injects into the finite set of generic points of
the irreducible components of a closed subset. -/

private lemma isMax_mem_genericPoints
    {T : Type*} [TopologicalSpace T] [T0Space T] [QuasiSober T]
    {x : T} (hx : IsMax x) : x ∈ genericPoints T := by
  rw [genericPoints, irreducibleComponents_eq_maximals_closed]
  refine ⟨⟨isClosed_closure, isIrreducible_singleton.closure⟩, ?_⟩
  intro s hs hxs
  let y : T := hs.2.genericPoint
  have hy : IsGenericPoint y s := hs.2.isGenericPoint_genericPoint_closure.trans
    hs.1.closure_eq
  have hxy : x ≤ y := by
    change y ⤳ x
    rw [specializes_iff_closure_subset, hy.def]
    exact hxs
  have hyx : y ≤ x := hx hxy
  have heq : x = y := le_antisymm hxy hyx
  simpa only [heq] using hy.def.symm.le

namespace AlgebraicGeometry.Scheme

universe u

/-- A dominant morphism between integral schemes carries the generic point to the generic
point.  This is the topological input needed to obtain the induced map of function fields from
the stalk map, rather than choosing such a map as extra divisor data. -/
lemma map_genericPoint_of_isDominant
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [IsDominant f] :
    f.base (genericPoint X) = genericPoint Y := by
  have h : IsGenericPoint (f.base (genericPoint X)) (Set.univ : Set Y) := by
    simpa only [Set.image_univ, f.denseRange.closure_range] using
      (genericPoint_spec X).image f.continuous
  exact h.eq (genericPoint_spec Y)

private lemma stalkSpecializes_eqToHom_of_eq
    {Y : Scheme.{u}} {a b c : Y} (e : b = a)
    (ha : a ⤳ c) (hb : b ⤳ c) :
    Y.presheaf.stalkSpecializes ha ≫
        (eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z) e.symm) :
          Y.presheaf.stalk a ⟶ Y.presheaf.stalk b) =
      Y.presheaf.stalkSpecializes hb := by
  subst a
  simp

private lemma SpecMap_eqToHom_fromSpecStalk_of_eq
    {Y : Scheme.{u}} {a b : Y} (e : b = a) :
    Spec.map (eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z) e.symm)) ≫
        Y.fromSpecStalk a =
      Y.fromSpecStalk b := by
  subst a
  simp

/-- The canonical pullback on function fields induced by a dominant morphism of integral
schemes.  It is literally the stalk map at the generic point, transported along the theorem
that the generic point maps to the generic point. -/
noncomputable def dominantFunctionFieldMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [IsDominant f] : Y.functionField →+* X.functionField :=
  ((eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z)
      (map_genericPoint_of_isDominant f).symm) :
      Y.presheaf.stalk (genericPoint Y) ⟶
        Y.presheaf.stalk (f.base (genericPoint X))) ≫
    f.stalkMap (genericPoint X)).hom

/-- The canonical function-field pullback agrees with the ordinary stalk map at every point,
after embedding both local rings into their function fields. -/
@[simp]
lemma dominantFunctionFieldMap_algebraMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [IsDominant f] (x : X)
    (a : Y.presheaf.stalk (f.base x)) :
    dominantFunctionFieldMap f
        (algebraMap (Y.presheaf.stalk (f.base x)) Y.functionField a) =
      algebraMap (X.presheaf.stalk x) X.functionField ((f.stalkMap x).hom a) := by
  let hx : genericPoint X ⤳ x := (genericPoint_spec X).specializes trivial
  let hy : genericPoint Y ⤳ f.base x := (genericPoint_spec Y).specializes trivial
  let hfy : f.base (genericPoint X) ⤳ f.base x :=
    f.base.hom.map_specializes hx
  let e : f.base (genericPoint X) = genericPoint Y :=
    map_genericPoint_of_isDominant f
  have htransport :
      Y.presheaf.stalkSpecializes hy ≫
          (eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z) e.symm) :
            Y.presheaf.stalk (genericPoint Y) ⟶
              Y.presheaf.stalk (f.base (genericPoint X))) =
        Y.presheaf.stalkSpecializes hfy :=
    stalkSpecializes_eqToHom_of_eq e hy hfy
  have hcat :
      Y.presheaf.stalkSpecializes hy ≫
          (eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z) e.symm) :
            Y.presheaf.stalk (genericPoint Y) ⟶
              Y.presheaf.stalk (f.base (genericPoint X))) ≫
          f.stalkMap (genericPoint X) =
        f.stalkMap x ≫ X.presheaf.stalkSpecializes hx := by
    rw [← Category.assoc, htransport]
    exact f.stalkSpecializes_stalkMap (genericPoint X) x hx
  simpa only [dominantFunctionFieldMap, RingHom.algebraMap_toAlgebra,
    ConcreteCategory.comp_apply, e, hx, hy] using
      DFunLike.congr_fun (CommRingCat.hom_ext_iff.mp hcat) a

/-- The morphism of spectra associated to the canonical function-field pullback is the generic
point restriction of the original dominant morphism. -/
lemma Spec_map_dominantFunctionFieldMap_fromSpecStalk
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [IsDominant f] :
    Spec.map (CommRingCat.ofHom (dominantFunctionFieldMap f)) ≫
        Y.fromSpecStalk (genericPoint Y) =
      X.fromSpecStalk (genericPoint X) ≫ f := by
  let e : f.base (genericPoint X) = genericPoint Y :=
    map_genericPoint_of_isDominant f
  rw [dominantFunctionFieldMap]
  change Spec.map
      ((eqToHom (congrArg (fun z ↦ Y.presheaf.stalk z) e.symm) :
          Y.presheaf.stalk (genericPoint Y) ⟶
            Y.presheaf.stalk (f.base (genericPoint X))) ≫
        f.stalkMap (genericPoint X)) ≫
      Y.fromSpecStalk (genericPoint Y) = _
  rw [Spec.map_comp_assoc]
  rw [SpecMap_eqToHom_fromSpecStalk_of_eq e]
  exact SpecMap_stalkMap_fromSpecStalk f

/-- An etale morphism induces a map of the local fraction fields at any source point.  It is
constructed by extending the composite of the injective local-ring map with the target stalk's
map into the source function field. -/
noncomputable def etaleLocalFunctionFieldMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [Etale f] (x : X) : Y.functionField →+* X.functionField := by
  let j : Y.presheaf.stalk (f.base x) →+* X.presheaf.stalk x :=
    (f.stalkMap x).hom
  letI : Algebra (Y.presheaf.stalk (f.base x)) (X.presheaf.stalk x) :=
    j.toAlgebra
  let _ : IsLocalHom (algebraMap (Y.presheaf.stalk (f.base x))
      (X.presheaf.stalk x)) := by
    change IsLocalHom j
    infer_instance
  let _ : Module.Flat (Y.presheaf.stalk (f.base x)) (X.presheaf.stalk x) :=
    by
      change j.Flat
      exact Flat.stalkMap f x
  let _ : Module.FaithfullyFlat (Y.presheaf.stalk (f.base x))
      (X.presheaf.stalk x) := Module.FaithfullyFlat.of_flat_of_isLocalHom
  have hj : Function.Injective j := by
    change Function.Injective (algebraMap (Y.presheaf.stalk (f.base x))
      (X.presheaf.stalk x))
    exact FaithfulSMul.algebraMap_injective _ _
  exact IsFractionRing.lift
    (A := Y.presheaf.stalk (f.base x)) (K := Y.functionField)
    (L := X.functionField)
    (g := (algebraMap (X.presheaf.stalk x) X.functionField).comp j)
    ((IsFractionRing.injective (X.presheaf.stalk x) X.functionField).comp hj)

@[simp]
lemma etaleLocalFunctionFieldMap_algebraMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [Etale f] (x : X) (a : Y.presheaf.stalk (f.base x)) :
    etaleLocalFunctionFieldMap f x
        (algebraMap (Y.presheaf.stalk (f.base x)) Y.functionField a) =
      algebraMap (X.presheaf.stalk x) X.functionField ((f.stalkMap x).hom a) := by
  simp [etaleLocalFunctionFieldMap]

/-- The fraction-field map obtained from any etale local ring is the canonical map induced by
the dominant morphism.  Thus it is independent of the chosen point; no compatibility of local
orders is being supplied as external data. -/
lemma etaleLocalFunctionFieldMap_eq_dominantFunctionFieldMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    (f : X ⟶ Y) [Etale f] [IsDominant f] (x : X) :
    etaleLocalFunctionFieldMap f x = dominantFunctionFieldMap f := by
  apply IsFractionRing.ringHom_ext (A := Y.presheaf.stalk (f.base x))
  intro a
  rw [etaleLocalFunctionFieldMap_algebraMap,
    dominantFunctionFieldMap_algebraMap]

/-- Etale pullback preserves the scheme-theoretic order of vanishing at corresponding
codimension-one points.  This is proved from the local length calculation above, rather than
stored as divisor-descent data. -/
lemma ord_etaleLocalFunctionFieldMap
    {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y]
    [IsLocallyNoetherian X] [IsLocallyNoetherian Y]
    (f : X ⟶ Y) [Etale f] (x : X)
    (hx : coheight x = 1) (hy : coheight (f.base x) = 1)
    (q : Y.functionField) :
    X.ord (etaleLocalFunctionFieldMap f x q) x = Y.ord q (f.base x) := by
  let R := Y.presheaf.stalk (f.base x)
  let S := X.presheaf.stalk x
  let _ : IsDomain R := by dsimp [R]; infer_instance
  let _ : IsDomain S := by dsimp [S]; infer_instance
  let _ : IsNoetherianRing R := by dsimp [R]; infer_instance
  let _ : IsNoetherianRing S := by dsimp [S]; infer_instance
  let _ : IsLocalRing R := by dsimp [R]; infer_instance
  let _ : IsLocalRing S := by dsimp [S]; infer_instance
  let j : R →+* S := (f.stalkMap x).hom
  let _ : Algebra R S := j.toAlgebra
  let _ : IsLocalHom (algebraMap R S) := by
    change IsLocalHom j
    infer_instance
  let _ : Module.Flat R S := by
    change j.Flat
    exact Flat.stalkMap f x
  let _ : Algebra.FormallyUnramified R S := by
    change j.FormallyUnramified
    exact FormallyUnramified.stalkMap f x
  let _ : Algebra.EssFiniteType R S := by
    rw [← RingHom.essFiniteType_algebraMap, RingHom.algebraMap_toAlgebra]
    exact LocallyOfFiniteType.stalkMap f x
  let _ : Ring.KrullDimLE 1 R := krullDimLE_of_coheight_le hy.le
  let _ : Ring.KrullDimLE 1 S := krullDimLE_of_coheight_le hx.le
  let _ : Algebra Y.functionField X.functionField :=
    (etaleLocalFunctionFieldMap f x).toAlgebra
  let _ : Algebra R X.functionField := RingHom.toAlgebra
    ((algebraMap S X.functionField).comp j)
  let _ : IsScalarTower R S X.functionField :=
    IsScalarTower.of_algebraMap_eq' rfl
  let _ : IsScalarTower R Y.functionField X.functionField := by
    apply IsScalarTower.of_algebraMap_eq'
    ext a
    exact (etaleLocalFunctionFieldMap_algebraMap f x a).symm
  rw [X.ord_eq_ordHom_of_coheight_eq_one hx,
    Y.ord_eq_ordHom_of_coheight_eq_one hy]
  change Multiplicative.toAdd
      ((Ring.ordFrac S (algebraMap Y.functionField X.functionField q)).unzeroD 1) =
    Multiplicative.toAdd ((Ring.ordFrac R q).unzeroD 1)
  rw [Ring.ordFrac_algebraMap_of_flat_formallyUnramified_local
    (R := R) (S := S) (K := Y.functionField) (L := X.functionField)]

variable {X : Scheme.{u}} [IsIntegral X] [IsLocallyNoetherian X]

/-- The order-of-vanishing function of a rational function on an integral locally Noetherian
scheme has locally finite support. -/
lemma ord_support_locallyFinite (f : X.functionField) :
    LocallyFiniteSupport (X.ord f) := by
  intro z
  by_cases hf : f = 0
  · subst f
    exact ⟨Set.univ, Filter.univ_mem, by simp⟩
  obtain ⟨V, -, a, hVnonempty, ha, haunit⟩ :=
    AlgebraicGeometry.exists_isUnit_germ_eq (X := X) f hf
  obtain ⟨U, hUaff, hzU, -⟩ := exists_isAffineOpen_mem_and_subset
    (U := (⊤ : X.Opens)) (x := z) (by simp)
  let Z : Set (U : Scheme) := {x | U.ι.base x ∉ V}
  have hZclosed : IsClosed Z := by
    convert V.2.isClosed_compl.preimage U.ι.continuous using 1
    ext q
    simp [Z]
  let _ : IsNoetherianRing Γ(X, U) :=
    IsLocallyNoetherian.component_noetherian ⟨U, hUaff⟩
  let _ : NoetherianSpace U := noetherianSpace_of_isAffineOpen U hUaff
  let _ : T0Space U := U.ι.isOpenEmbedding.toIsEmbedding.t0Space
  let _ : QuasiSober Z := hZclosed.isClosedEmbedding_subtypeVal.quasiSober
  have hgeneric : (genericPoints Z).Finite :=
    genericPoints.finite NoetherianSpace.finite_irreducibleComponents
  have himage : ((fun x : Z ↦ U.ι.base x.1) '' genericPoints Z).Finite :=
    hgeneric.image _
  refine ⟨(U : Set X), U.2.mem_nhds hzU, himage.subset ?_⟩
  intro x hx
  rcases hx with ⟨hxU, hxord⟩
  have hxheight : coheight x = 1 := by
    by_contra h
    exact hxord (X.ord_eq_zero_of_coheight_neq_one h f)
  have hxnotV : x ∉ V := by
    intro hxV
    apply hxord
    rw [← ha]
    exact X.ord_of_isUnit haunit hxV
  let xU : (U : Scheme) := ⟨x, hxU⟩
  let xZ : Z := ⟨xU, hxnotV⟩
  refine ⟨xZ, ?_, rfl⟩
  apply isMax_mem_genericPoints
  intro y hxy
  have hxyU : y.1 ⤳ xU := by
    change y ⤳ xZ at hxy
    simpa only [subtype_specializes_iff] using hxy
  have hxyX : x ≤ U.ι.base y.1 := by
    change U.ι.base y.1 ⤳ x
    exact hxyU.map U.ι.continuous
  have hy_ne_top : U.ι.base y.1 ≠ ⊤ := by
    intro hy
    have htopV : (⊤ : X) ∈ V := by
      change genericPoint X ∈ V
      exact ((genericPoint_spec X).mem_open_set_iff V.isOpen).mpr (by simpa using hVnonempty)
    exact y.2 (hy ▸ htopV)
  have hy_lt_top : U.ι.base y.1 < ⊤ := lt_of_le_of_ne le_top hy_ne_top
  have hypositive : 0 < coheight (U.ι.base y.1) := coheight_pos_of_lt_top hy_lt_top
  have hyone : (1 : ℕ∞) ≤ coheight (U.ι.base y.1) := by
    simpa only [Order.one_le_iff_ne_zero] using ne_of_gt hypositive
  have hmax := coheight_eq_coe_iff_maximal_le_coheight.mp hxheight
  have hyxX : U.ι.base y.1 ≤ x := hmax.2 hyone hxyX
  change xZ ⤳ y
  have hyxSpec : x ⤳ U.ι.base y.1 := hyxX
  have hyxU : xU ⤳ y.1 := U.ι.isOpenEmbedding.isInducing.specializes_iff.mp hyxSpec
  simpa only [subtype_specializes_iff] using hyxU

/-- The principal Weil cycle associated to a rational function on an integral locally
Noetherian scheme.  Its coefficient at a point is the actual order of vanishing. -/
noncomputable def principalCycle (f : X.functionField) : AlgebraicCycle X ℚ where
  toFun x := (X.ord f x : ℚ)
  supportWithinDomain' := Set.subset_univ _
  supportLocallyFiniteWithinDomain' z _ := by
    obtain ⟨t, ht, hfinite⟩ := X.ord_support_locallyFinite f z
    refine ⟨t, ht, hfinite.subset ?_⟩
    rintro x ⟨hxt, hx⟩
    refine ⟨hxt, ?_⟩
    intro hord
    exact hx (by simp [hord])

@[simp]
lemma principalCycle_apply (f : X.functionField) (x : X) :
    X.principalCycle f x = (X.ord f x : ℚ) := rfl

@[simp]
lemma principalCycle_zero : X.principalCycle (0 : X.functionField) = 0 := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext x
  simp

/-- The order of the multiplicative identity vanishes at every point. -/
@[simp]
lemma ord_one : X.ord (1 : X.functionField) = 0 := by
  funext x
  have h := X.ord_mul (x := x) (f := (1 : X.functionField))
    (g := (1 : X.functionField)) one_ne_zero one_ne_zero
  simp only [one_mul] at h
  change X.ord (1 : X.functionField) x = (0 : ℤ)
  omega

/-- The principal cycle of the multiplicative identity is zero. -/
@[simp]
lemma principalCycle_one : X.principalCycle (1 : X.functionField) = 0 := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext x
  simp [principalCycle_apply]

/-- Principal cycles turn multiplication of nonzero rational functions into addition. -/
lemma principalCycle_mul {f g : X.functionField} (hf : f ≠ 0) (hg : g ≠ 0) :
    X.principalCycle (f * g) = X.principalCycle f + X.principalCycle g := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext x
  simp only [principalCycle_apply,
    Function.locallyFinsuppWithin.coe_add, Pi.add_apply]
  exact_mod_cast X.ord_mul (x := x) hf hg

/-- The principal cycle of the inverse is the negative principal cycle. -/
lemma principalCycle_inv {f : X.functionField} (hf : f ≠ 0) :
    X.principalCycle f⁻¹ = -X.principalCycle f := by
  have hinv : f⁻¹ ≠ 0 := inv_ne_zero hf
  have hmul := X.principalCycle_mul hf hinv
  rw [mul_inv_cancel₀ hf, principalCycle_one] at hmul
  apply eq_neg_of_add_eq_zero_left
  simpa [add_comm] using hmul.symm

end AlgebraicGeometry.Scheme

namespace AlgebraicGeometry.Scheme

universe u

variable (X : Scheme.{u}) [IsLocallyNoetherian X]

/-- The scheme-theoretic multiplicity at a point: the length of the local ring as a module over
itself.  At a generic point of a locally Noetherian scheme this length is finite; using the
length, rather than the constant `1`, retains nilpotent thickness along an irreducible
component. -/
noncomputable def genericLength (x : X) : ℕ :=
  (Module.length (X.presheaf.stalk x) (X.presheaf.stalk x)).toNat

/-- A generic local ring of a locally Noetherian scheme is zero-dimensional Noetherian and
hence Artinian, so its module length is genuinely finite. -/
theorem genericLength_length_ne_top (x : X) (hx : IsMax x) :
    Module.length (X.presheaf.stalk x) (X.presheaf.stalk x) ≠ ⊤ := by
  let _ : Ring.KrullDimLE 0 (X.presheaf.stalk x) :=
    krullDimLE_of_coheight_le (by simpa using hx.coheight_eq_zero.le)
  let _ : IsArtinianRing (X.presheaf.stalk x) :=
    IsNoetherianRing.isArtinianRing_of_krullDimLE_zero
  exact Module.length_ne_top

/-- The generic multiplicity is positive, so every actual irreducible component occurs in the
fundamental cycle. -/
theorem genericLength_pos (x : X) (hx : IsMax x) : 0 < X.genericLength x := by
  unfold genericLength
  apply ENat.toNat_pos
  · exact ne_of_gt Module.length_pos
  · exact X.genericLength_length_ne_top x hx

/-- On a reduced locally Noetherian scheme the generic local rings are fields, so all generic
lengths are one. -/
theorem genericLength_eq_one [IsReduced X] (x : X) (hx : IsMax x) :
    X.genericLength x = 1 := by
  let _ : Ring.KrullDimLE 0 (X.presheaf.stalk x) :=
    krullDimLE_of_coheight_le (by simpa using hx.coheight_eq_zero.le)
  let _ : IsArtinianRing (X.presheaf.stalk x) :=
    IsNoetherianRing.isArtinianRing_of_krullDimLE_zero
  let hField : IsField (X.presheaf.stalk x) :=
    IsArtinianRing.isField_of_isReduced_of_isLocalRing _
  let _ : Field (X.presheaf.stalk x) :=
    hField.toField
  unfold genericLength
  rw [ENat.toNat_eq_iff_eq_natCast, Nat.cast_one]
  exact Module.length_eq_one _ _

/-- The ordinary fundamental cycle of a locally Noetherian scheme: the coefficient at each
generic point is the length of its ambient local ring, and it is zero elsewhere.  Local
finiteness follows by restricting to a Noetherian affine neighbourhood, where there are only
finitely many irreducible components. -/
noncomputable def fundamentalCycle : AlgebraicCycle X ℚ := by
  classical
  refine {
    toFun := fun x ↦ if IsMax x then (X.genericLength x : ℚ) else 0
    supportWithinDomain' := Set.subset_univ _
    supportLocallyFiniteWithinDomain' := ?_ }
  intro z _
  obtain ⟨U, hUaff, hzU, -⟩ := exists_isAffineOpen_mem_and_subset
    (U := (⊤ : X.Opens)) (x := z) (by simp)
  let _ : IsNoetherianRing Γ(X, U) :=
    IsLocallyNoetherian.component_noetherian ⟨U, hUaff⟩
  let _ : NoetherianSpace U := noetherianSpace_of_isAffineOpen U hUaff
  let _ : T0Space U := U.ι.isOpenEmbedding.toIsEmbedding.t0Space
  have hgeneric : (genericPoints U).Finite :=
    genericPoints.finite NoetherianSpace.finite_irreducibleComponents
  have himage : ((fun x : U ↦ U.ι.base x) '' genericPoints U).Finite :=
    hgeneric.image _
  refine ⟨(U : Set X), U.2.mem_nhds hzU, himage.subset ?_⟩
  rintro x ⟨hxU, hx⟩
  have hxmax : IsMax x := by
    by_contra h
    exact hx (by simp [h])
  let xU : (U : Scheme) := ⟨x, hxU⟩
  have hxmaxU : IsMax xU := by
    intro y hxy
    have hxyX : x ≤ U.ι.base y := by
      exact hxy.map U.ι.continuous
    have hyxX : U.ι.base y ≤ x := hxmax hxyX
    change y ≤ xU
    exact U.ι.isOpenEmbedding.isInducing.specializes_iff.mp hyxX
  let _ : T0Space (U : Scheme) := inferInstance
  exact ⟨xU, @isMax_mem_genericPoints (U : Scheme) _ inferInstance inferInstance xU hxmaxU,
    rfl⟩

@[simp]
theorem fundamentalCycle_apply_of_isMax (x : X) (hx : IsMax x) :
    X.fundamentalCycle x = (X.genericLength x : ℚ) := by
  simp [fundamentalCycle, hx]

@[simp]
theorem fundamentalCycle_apply_of_isMax_of_isReduced [IsReduced X]
    (x : X) (hx : IsMax x) : X.fundamentalCycle x = 1 := by
  rw [X.fundamentalCycle_apply_of_isMax x hx, X.genericLength_eq_one x hx]
  norm_num

@[simp]
theorem fundamentalCycle_apply_of_not_isMax (x : X) (hx : ¬ IsMax x) :
    X.fundamentalCycle x = 0 := by
  simp [fundamentalCycle, hx]

end AlgebraicGeometry.Scheme

namespace GromovWitten.AlgebraicGeometry.IntersectionTheory

universe u

abbrev Scheme := _root_.AlgebraicGeometry.Scheme
abbrev AlgebraicCycle := _root_.AlgebraicGeometry.AlgebraicCycle

/-- A closed immersion induces an isomorphism on residue fields at every source point, so its
residue degree is one.  Surjectivity is proved from the actual surjective stalk map; injectivity
is the field-homomorphism theorem. -/
lemma residueDegree_eq_one_of_isClosedImmersion
    {X Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f] (x : X) :
    f.residueDegree x = 1 := by
  have hsurj : Function.Surjective (f.residueFieldMap x) := by
    intro b
    obtain ⟨a, ha⟩ := X.residue_surjective x b
    obtain ⟨r, hr⟩ := f.stalkMap_surjective x a
    refine ⟨Y.residue (f.base x) r, ?_⟩
    rw [← ha, ← hr, ← ConcreteCategory.comp_apply,
      _root_.AlgebraicGeometry.Scheme.residue_residueFieldMap]
    exact ConcreteCategory.comp_apply _ _ _
  unfold _root_.AlgebraicGeometry.Scheme.Hom.residueDegree
  let _ := (f.residueFieldMap x).hom.toAlgebra
  apply Algebra.finrank_eq_one_iff_bijective_algebraMap.mpr
  exact ⟨RingHom.injective _, hsurj⟩

/-- Residue degrees multiply under composition.  The scalar-tower structure is obtained from
Mathlib's actual comparison of the three residue-field maps. -/
lemma residueDegree_comp
    {X Y Z : Scheme.{u}} (f : X ⟶ Y) (g : Y ⟶ Z) (x : X) :
    (f ≫ g).residueDegree x =
      g.residueDegree (f.base x) * f.residueDegree x := by
  let F := Z.residueField (g.base (f.base x))
  let K := Y.residueField (f.base x)
  let L := X.residueField x
  let _ : Algebra F K := (g.residueFieldMap (f.base x)).hom.toAlgebra
  let _ : Algebra K L := (f.residueFieldMap x).hom.toAlgebra
  let _ : Algebra F L := ((f ≫ g).residueFieldMap x).hom.toAlgebra
  let _ : IsScalarTower F K L := IsScalarTower.of_algebraMap_eq' (by
    change ((f ≫ g).residueFieldMap x).hom =
      (f.residueFieldMap x).hom.comp (g.residueFieldMap (f.base x)).hom
    rw [_root_.AlgebraicGeometry.Scheme.residueFieldMap_comp]
    rfl)
  unfold _root_.AlgebraicGeometry.Scheme.Hom.residueDegree
  exact (Module.finrank_mul_finrank F K L).symm

/- A specializing scheme map lifts every strict specialization chain ending at an image point
to a strict chain of the same length ending at the chosen source point.  Strictness of a lifted
step follows because its two images are distinct; no choice of a dimension comparison is made. -/
attribute [local instance] specializationOrder in
private lemma liftLTSeries_of_specializing
    {X Y : Scheme.{u}} (f : X ⟶ Y) (hf : SpecializingMap f.base)
    (p : LTSeries Y) (x : X) (hlast : p.last = f.base x) :
    ∃ q : LTSeries X, q.length = p.length ∧ q.last = x := by
  induction p using RelSeries.inductionOn' generalizing x with
  | singleton y =>
      refine ⟨RelSeries.singleton _ x, ?_, ?_⟩
      · rfl
      · simp
  | snoc p y hpy ih =>
      have hpy' : p.last < y := hpy
      have hyfx : y = f.base x := by simpa using hlast
      have hspec : f.base x ⤳ p.last := by
        rw [← hyfx]
        exact hpy'.le
      obtain ⟨x', hxx', hfx'⟩ := hf hspec
      have hx'ltx : x' < x := by
        apply lt_of_le_of_ne
        · change x ⤳ x'
          exact hxx'
        · intro heq
          subst x'
          apply hpy'.ne
          exact hfx'.symm.trans hyfx.symm
      obtain ⟨q, hqLength, hqLast⟩ := ih x' hfx'.symm
      refine ⟨q.snoc x (hqLast ▸ hx'ltx), ?_, ?_⟩
      · simp [hqLength]
      · simp

/- A specializing scheme map cannot increase the height of an image point.  This is proved by
lifting every finite strict chain, rather than accepted as a dimension hypothesis. -/
attribute [local instance] specializationOrder in
lemma height_image_le_of_specializing
    {X Y : Scheme.{u}} (f : X ⟶ Y) (hf : SpecializingMap f.base) (x : X) :
    Order.height (f.base x) ≤ Order.height x := by
  apply Order.height_le
  intro p hp
  obtain ⟨q, hlength, hlast⟩ := liftLTSeries_of_specializing f hf p x hp
  rw [← hlength]
  have h := Order.index_le_height q (Fin.last q.length)
  rw [RelSeries.apply_last, hlast] at h
  exact h

/-- A closed immersion preserves the height of every point.  Its closed image contains every
specialization of one of its points, so every chain below an image point lifts uniquely. -/
lemma height_eq_of_isClosedImmersion
    {X Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f] (x : X) :
    Order.height (f.base x) = Order.height x := by
  symm
  apply Order.height_eq_of_strictMono f.base
  · intro a b hab
    apply lt_of_le_of_ne
    · change f.base b ⤳ f.base a
      exact f.base.hom.map_specializes (show b ⤳ a by exact hab.le)
    · intro h
      exact hab.ne (f.isClosedEmbedding.injective h)
  · intro a b hba
    have hbmem : b ∈ Set.range f.base := by
      have hs : f.base a ⤳ b := by exact hba.le
      exact hs.mem_closed f.isClosedEmbedding.isClosed_range ⟨a, rfl⟩
    obtain ⟨a', ha'⟩ := hbmem
    refine ⟨a', ?_, ha'⟩
    apply lt_of_le_of_ne
    · change a ⤳ a'
      apply f.isClosedEmbedding.isInducing.specializes_iff.mp
      rw [ha']
      exact hba.le
    · intro e
      subst a'
      exact hba.ne ha'.symm

namespace AlgebraicCycle

variable {X Y : Scheme.{u}}

/-- A fibre of a quasi-compact scheme morphism meets the support of a locally finite cycle in a
finite set.  We place the target point in a compact open neighbourhood and use quasi-compactness
before applying local finiteness. -/
private lemma finite_fiber_inter_support (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.QuasiCompact f]
    (c : AlgebraicCycle X ℚ) (y : Y) :
    (f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ)).Finite := by
  obtain ⟨U, hU⟩ :=
    (PrespectralSpace.isTopologicalBasis (X := Y)).exists_subset_of_mem_open
      (by simp : y ∈ (Set.univ : Set Y)) (by simp)
  exact (c.locallyFiniteSupport.finite_inter_support_of_isCompact
    (f.isSpectralMap.2 hU.1.1 hU.1.2)).subset (by
      intro x hx
      have heq : f.base x = y := by simpa using hx.1
      refine ⟨?_, hx.2⟩
      change f.base x ∈ U
      rw [heq]
      exact hU.2.1)

/-- The coefficient used in cycle pushforward is multiplicative along a composite whenever
equality of the endpoint weights forces equality with the intermediate weight.  This is the
precise combinatorial condition needed for dimension-graded composition; residue degrees
themselves multiply by the preceding theorem. -/
lemma mapCoeff_comp_of_between
    {Z : Scheme.{u}} (f : X ⟶ Y) (g : Y ⟶ Z)
    {N : Type*} [DecidableEq N] (wx : X → N) (wy : Y → N) (wz : Z → N)
    (hbetween : ∀ x, wx x = wz ((f ≫ g).base x) → wx x = wy (f.base x))
    (x : X) :
    _root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff (f ≫ g) wx wz x =
      _root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x *
        _root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz (f.base x) := by
  unfold _root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff
  by_cases hxz : wx x = wz ((f ≫ g).base x)
  · have hxy := hbetween x hxz
    have hyz : wy (f.base x) = wz (g.base (f.base x)) := by
      rw [← hxy, ← _root_.AlgebraicGeometry.Scheme.Hom.comp_apply]
      exact hxz
    rw [if_pos hxz, if_pos hxy, if_pos hyz,
      residueDegree_comp, Nat.mul_comm]
  · rw [if_neg hxz]
    by_cases hxy : wx x = wy (f.base x)
    · have hnyz : wy (f.base x) ≠ wz (g.base (f.base x)) := by
        intro hyz
        apply hxz
        rw [_root_.AlgebraicGeometry.Scheme.Hom.comp_apply, hxy, hyz]
      rw [if_pos hxy, if_neg hnyz, mul_zero]
    · rw [if_neg hxy, zero_mul]

/-- Mathlib's residue-degree pushforward sends the zero rational cycle to zero. -/
lemma map_zero (f : X ⟶ Y) [_root_.AlgebraicGeometry.QuasiCompact f]
    (wx : X → ℤ) (wy : Y → ℤ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy
      (0 : AlgebraicCycle X ℚ) = 0 := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp [_root_.AlgebraicGeometry.AlgebraicCycle.map]

/-- Mathlib's residue-degree pushforward is additive on rational cycles.  Finiteness of each
relevant fibre sum is deduced from quasi-compactness and local finiteness, not assumed. -/
lemma map_add (f : X ⟶ Y) [_root_.AlgebraicGeometry.QuasiCompact f]
    (wx : X → ℤ) (wy : Y → ℤ) (c d : AlgebraicCycle X ℚ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy (c + d) =
      _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy c +
        _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy d := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp only [_root_.AlgebraicGeometry.AlgebraicCycle.map,
    Function.locallyFinsupp.map_apply,
    Function.locallyFinsuppWithin.coe_add, Pi.add_apply, add_mul]
  apply finsum_mem_add_distrib'
  · exact (finite_fiber_inter_support f c y).subset (by
      intro x hx
      exact ⟨hx.1, fun hc ↦ hx.2 (by simp [hc])⟩)
  · exact (finite_fiber_inter_support f d y).subset (by
      intro x hx
      exact ⟨hx.1, fun hd ↦ hx.2 (by simp [hd])⟩)

/-- Mathlib's residue-degree pushforward commutes with rational scalar multiplication. -/
lemma map_smul (f : X ⟶ Y) [_root_.AlgebraicGeometry.QuasiCompact f]
    (wx : X → ℤ) (wy : Y → ℤ) (q : ℚ) (c : AlgebraicCycle X ℚ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy (q • c) =
      q • _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy c := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  simp only [_root_.AlgebraicGeometry.AlgebraicCycle.map,
    Function.locallyFinsupp.map_apply,
    Function.locallyFinsuppWithin.coe_rational_smul, Pi.smul_apply, smul_eq_mul]
  rw [mul_finsum]
  apply finsum_congr
  intro x
  by_cases hx : x ∈ f.base ⁻¹' {y}
  · simp [hx, mul_assoc]
  · simp [hx]

/-- The residue-degree map of rational algebraic cycles, bundled with its proved linearity. -/
noncomputable def mapLinear (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.QuasiCompact f]
    (wx : X → ℤ) (wy : Y → ℤ) :
    AlgebraicCycle X ℚ →ₗ[ℚ] AlgebraicCycle Y ℚ where
  toFun := _root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy
  map_add' := map_add f wx wy
  map_smul' := map_smul f wx wy

/-- Residue-degree pushforward composes whenever endpoint weight equality forces the intermediate
weight equality.  The proof partitions the finite part of the source support over each target
fibre and reassociates the actual finite sums; functoriality is not supplied as an assumption. -/
lemma map_comp_of_between
    {Z : Scheme.{u}} (f : X ⟶ Y) (g : Y ⟶ Z)
    [_root_.AlgebraicGeometry.QuasiCompact f]
    [_root_.AlgebraicGeometry.QuasiCompact g]
    {N : Type*} [DecidableEq N] (wx : X → N) (wy : Y → N) (wz : Z → N)
    (hbetween : ∀ x, wx x = wz ((f ≫ g).base x) → wx x = wy (f.base x))
    (c : AlgebraicCycle X ℚ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map g wy wz
        (_root_.AlgebraicGeometry.AlgebraicCycle.map f wx wy c) =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g) wx wz c := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext z
  unfold _root_.AlgebraicGeometry.AlgebraicCycle.map
  change (∑ᶠ y ∈ g.base ⁻¹' {z},
      (∑ᶠ x ∈ f.base ⁻¹' {y}, c x *
        (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ)) *
          (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz y : ℚ)) =
    ∑ᶠ x ∈ (f ≫ g).base ⁻¹' {z}, c x *
      (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff (f ≫ g) wx wz x : ℚ)
  let S : Set X := (f ≫ g).base ⁻¹' {z} ∩ Function.support (c : X → ℚ)
  have hS : S.Finite := finite_fiber_inter_support (f ≫ g) c z
  let T : Set Y := f.base '' S
  have hT : T.Finite := hS.image f.base
  let a : X → ℚ := fun x =>
    (c x * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ)) *
      (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz (f.base x) : ℚ)
  let d : Y → ℚ := fun y =>
    (∑ᶠ x ∈ f.base ⁻¹' {y}, c x *
      (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ)) *
        (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz y : ℚ)
  have houter : (∑ᶠ y ∈ g.base ⁻¹' {z}, d y) = ∑ᶠ y ∈ T, d y := by
    apply finsum_mem_inter_support_eq'
    intro y hy
    constructor
    · intro hgy
      have hd : (∑ᶠ x ∈ f.base ⁻¹' {y}, c x *
          (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ)) ≠ 0 := by
        intro hzero
        apply hy
        dsimp [d]
        rw [hzero]
        exact zero_mul _
      obtain ⟨x, hfx, hxne⟩ := exists_ne_zero_of_finsum_mem_ne_zero hd
      have hcx : c x ≠ 0 := by
        intro hzero
        exact hxne (by simp [hzero])
      refine ⟨x, ?_, hfx⟩
      refine ⟨?_, hcx⟩
      change (f ≫ g).base x = z
      rw [_root_.AlgebraicGeometry.Scheme.Hom.comp_apply, hfx]
      simpa using hgy
    · rintro ⟨x, hxS, rfl⟩
      change g.base (f.base x) = z
      exact hxS.1
  have hdisjoint : T.PairwiseDisjoint
      (fun y : Y => f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ)) := by
    intro y _ y' _ hne
    change Disjoint (f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ))
      (f.base ⁻¹' {y'} ∩ Function.support (c : X → ℚ))
    rw [Set.disjoint_left]
    intro x hx hx'
    apply hne
    have hxy : f.base x = y := by simpa using hx.1
    have hxy' : f.base x = y' := by simpa using hx'.1
    exact hxy.symm.trans hxy'
  have hfiberFinite : ∀ y ∈ T,
      (f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ)).Finite := by
    intro y hy
    apply hS.subset
    intro x hx
    rcases hy with ⟨x', hx'S, hx'eq⟩
    refine ⟨?_, hx.2⟩
    change (f ≫ g).base x = z
    rw [_root_.AlgebraicGeometry.Scheme.Hom.comp_apply]
    have hxy : f.base x = y := by simpa using hx.1
    rw [hxy, ← hx'eq]
    exact hx'S.1
  have hunion : (⋃ y ∈ T,
      (f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ))) = S := by
    ext x
    constructor
    · simp only [Set.mem_iUnion]
      rintro ⟨y, hyT, hx⟩
      rcases hyT with ⟨x', hx'S, rfl⟩
      refine ⟨?_, hx.2⟩
      change (f ≫ g).base x = z
      rw [_root_.AlgebraicGeometry.Scheme.Hom.comp_apply]
      have hfx : f.base x = f.base x' := by simpa using hx.1
      rw [hfx]
      exact hx'S.1
    · intro hxS
      simp only [Set.mem_iUnion]
      refine ⟨f.base x, ⟨x, hxS, rfl⟩, ?_⟩
      exact ⟨by simp, hxS.2⟩
  calc
    (∑ᶠ y ∈ g.base ⁻¹' {z},
      (∑ᶠ x ∈ f.base ⁻¹' {y}, c x *
        (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ)) *
          (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz y : ℚ)) =
        ∑ᶠ y ∈ T, d y := houter
    _ = ∑ᶠ y ∈ T, ∑ᶠ x ∈ f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ), a x := by
      apply finsum_mem_congr rfl
      intro y hy
      dsimp [d]
      rw [finsum_mem_mul]
      calc
        (∑ᶠ x ∈ f.base ⁻¹' {y},
          c x * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ) *
            (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz y : ℚ)) =
          ∑ᶠ x ∈ f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ),
            c x * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f wx wy x : ℚ) *
              (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff g wy wz y : ℚ) := by
                apply finsum_mem_inter_support_eq'
                intro x hx
                constructor
                · intro hmem
                  exact ⟨hmem, fun hcx => hx (by simp [hcx])⟩
                · exact fun h => h.1
        _ = ∑ᶠ x ∈ f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ), a x := by
          apply finsum_mem_congr rfl
          intro x hx
          have hfx : f.base x = y := by simpa using hx.1
          simp [a, hfx]
    _ = ∑ᶠ x ∈ ⋃ y ∈ T,
        (f.base ⁻¹' {y} ∩ Function.support (c : X → ℚ)), a x :=
      (finsum_mem_biUnion hdisjoint hT hfiberFinite).symm
    _ = ∑ᶠ x ∈ S, a x := finsum_mem_congr hunion (fun _ _ => rfl)
    _ = ∑ᶠ x ∈ (f ≫ g).base ⁻¹' {z}, a x := by
      apply finsum_mem_inter_support_eq'
      intro x hx
      constructor
      · exact fun h => h.1
      · intro hxcomp
        refine ⟨hxcomp, ?_⟩
        intro hcx
        apply hx
        simp [a, hcx]
    _ = ∑ᶠ x ∈ (f ≫ g).base ⁻¹' {z}, c x *
        (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff (f ≫ g) wx wz x : ℚ) := by
      apply finsum_mem_congr rfl
      intro x hx
      rw [mapCoeff_comp_of_between f g wx wy wz hbetween]
      push_cast
      simp [a, mul_assoc]

/-- For a closed immersion, residue-degree pushforward with the pulled-back target weight simply
places a coefficient at its image. -/
lemma map_closedImmersion_apply_image (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (wy : Y → ℤ) (c : AlgebraicCycle X ℚ) (x : X) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f
      (fun a ↦ wy (f.base a)) wy c (f.base x) = c x := by
  unfold _root_.AlgebraicGeometry.AlgebraicCycle.map
  change (∑ᶠ a ∈ f.base ⁻¹' {f.base x},
    c a * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f
      (fun a ↦ wy (f.base a)) wy a : ℚ)) = c x
  rw [finsum_eq_single _ x]
  · simp [_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff,
      residueDegree_eq_one_of_isClosedImmersion]
  · intro a hax
    have hnot : a ∉ f.base ⁻¹' {f.base x} := by
      intro ha
      apply hax
      apply f.isClosedEmbedding.injective
      simpa using ha
    simp [hnot]

/-- A closed-immersion pushforward vanishes away from the image. -/
lemma map_closedImmersion_apply_of_not_mem_range (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (wy : Y → ℤ) (c : AlgebraicCycle X ℚ) (y : Y)
    (hy : y ∉ Set.range f.base) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f
      (fun a ↦ wy (f.base a)) wy c y = 0 := by
  unfold _root_.AlgebraicGeometry.AlgebraicCycle.map
  change (∑ᶠ a ∈ f.base ⁻¹' {y},
    c a * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f
      (fun a ↦ wy (f.base a)) wy a : ℚ)) = 0
  apply finsum_mem_of_eqOn_zero
  intro a ha
  exact (hy ⟨a, by simpa using ha⟩).elim

/-- Residue-degree cycle pushforward is functorial for two closed immersions.  The proof evaluates
on and off the two closed images, using the proved residue-degree-one calculation and injectivity
of the underlying embeddings. -/
lemma map_comp_of_isClosedImmersion
    {Z : Scheme.{u}} (f : X ⟶ Y) (g : Y ⟶ Z)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    [_root_.AlgebraicGeometry.IsClosedImmersion g]
    (wy : Y → ℤ) (wz : Z → ℤ) (c : AlgebraicCycle X ℚ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map g
        (fun y ↦ wz (g.base y)) wz
        (_root_.AlgebraicGeometry.AlgebraicCycle.map f
          (fun x ↦ wy (f.base x)) wy c) =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g)
        (fun x ↦ wz ((f ≫ g).base x)) wz c := by
  apply Function.locallyFinsuppWithin.coe_injective
  funext z
  change _root_.AlgebraicGeometry.AlgebraicCycle.map g
        (fun y ↦ wz (g.base y)) wz
        (_root_.AlgebraicGeometry.AlgebraicCycle.map f
          (fun x ↦ wy (f.base x)) wy c) z =
      _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g)
        (fun x ↦ wz ((f ≫ g).base x)) wz c z
  by_cases hz : z ∈ Set.range g.base
  · obtain ⟨y, rfl⟩ := hz
    rw [map_closedImmersion_apply_image]
    by_cases hy : y ∈ Set.range f.base
    · obtain ⟨x, rfl⟩ := hy
      rw [map_closedImmersion_apply_image]
      change c x = _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g)
        (fun x ↦ wz ((f ≫ g).base x)) wz c ((f ≫ g).base x)
      rw [map_closedImmersion_apply_image]
    · rw [map_closedImmersion_apply_of_not_mem_range f wy c y hy]
      have hnot : g.base y ∉ Set.range (f ≫ g).base := by
        rintro ⟨x, hx⟩
        apply hy
        refine ⟨x, g.isClosedEmbedding.injective ?_⟩
        simpa using hx
      rw [map_closedImmersion_apply_of_not_mem_range (f ≫ g) wz c _ hnot]
  · rw [map_closedImmersion_apply_of_not_mem_range g wz _ z hz]
    have hnot : z ∉ Set.range (f ≫ g).base := by
      rintro ⟨x, hx⟩
      exact hz ⟨f.base x, by simpa using hx⟩
    rw [map_closedImmersion_apply_of_not_mem_range (f ≫ g) wz c z hnot]

end AlgebraicCycle

/-- A finite dimension grading for points of a scheme.  The integer attached to a point is
certified to be the Krull dimension of its closure, represented by its order-theoretic height;
callers cannot choose an unrelated grading.  Schemes with infinite-dimensional point closures
intentionally have no inhabitant of this type. -/
structure DimensionFunction (X : Scheme.{u}) where
  toFun : X → ℤ
  nonnegative (x : X) : 0 ≤ toFun x
  height_eq (x : X) : Order.height x = (Int.toNat (toFun x) : ℕ∞)

instance {X : Scheme.{u}} : CoeFun (DimensionFunction X) (fun _ ↦ X → ℤ) :=
  ⟨DimensionFunction.toFun⟩

@[ext]
theorem DimensionFunction.ext {X : Scheme.{u}} {d e : DimensionFunction X}
    (h : ∀ x, d x = e x) : d = e := by
  cases d
  cases e
  simp only [mk.injEq]
  exact funext h

/-- The certified dimension functions of two schemes agree along a closed immersion.  This is
forced by preservation of order-theoretic height and nonnegativity; it is not extra compatibility
data attached to the morphism. -/
theorem DimensionFunction.apply_eq_of_isClosedImmersion
    {X Y : Scheme.{u}} (dimensionX : DimensionFunction X)
    (dimensionY : DimensionFunction Y) (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f] (x : X) :
    dimensionX x = dimensionY (f.base x) := by
  have hcast : (Int.toNat (dimensionX x) : ℕ∞) =
      (Int.toNat (dimensionY (f.base x)) : ℕ∞) := by
    rw [← dimensionX.height_eq, ← dimensionY.height_eq,
      height_eq_of_isClosedImmersion f]
  have hnat : Int.toNat (dimensionX x) =
      Int.toNat (dimensionY (f.base x)) := ENat.natCast_inj.mp hcast
  rw [← Int.toNat_of_nonneg (dimensionX.nonnegative x),
    ← Int.toNat_of_nonneg (dimensionY.nonnegative (f.base x))]
  exact congrArg Int.ofNat hnat

/-- A proper morphism cannot increase the closure dimension of a point.  Properness supplies an
actual closed underlying map, hence a specializing map; the preceding chain-lifting theorem then
gives the height inequality from which this integer inequality is derived. -/
theorem DimensionFunction.apply_le_of_isProper
    {X Y : Scheme.{u}} (dimensionX : DimensionFunction X)
    (dimensionY : DimensionFunction Y) (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsProper f] (x : X) :
    dimensionY (f.base x) ≤ dimensionX x := by
  have hheight : Order.height (f.base x) ≤ Order.height x :=
    height_image_le_of_specializing f f.isClosedMap.specializingMap x
  rw [dimensionY.height_eq, dimensionX.height_eq] at hheight
  have hnat : Int.toNat (dimensionY (f.base x)) ≤ Int.toNat (dimensionX x) := by
    exact_mod_cast hheight
  rw [← Int.toNat_of_nonneg (dimensionY.nonnegative (f.base x)),
    ← Int.toNat_of_nonneg (dimensionX.nonnegative x)]
  exact_mod_cast hnat

/-- The canonical finite dimension grading on the spectrum of a field. -/
def DimensionFunction.specField (k : Type u) [Field k] :
    DimensionFunction (_root_.AlgebraicGeometry.Spec (.of k)) where
  toFun := fun _ ↦ 0
  nonnegative := by simp
  height_eq := by
    intro x
    simp only [Int.toNat_zero, Nat.cast_zero]
    rw [Order.height_eq_zero]
    intro y _
    exact (Subsingleton.elim x y).le

@[simp]
theorem DimensionFunction.specField_apply (k : Type u) [Field k]
    (x : _root_.AlgebraicGeometry.Spec (.of k)) :
    DimensionFunction.specField k x = 0 :=
  rfl

/-- Rational cycles concentrated in dimension `i`. -/
def cyclesOfDimension (X : Scheme.{u}) (dimension : DimensionFunction X) (i : ℤ) :
    Submodule ℚ (AlgebraicCycle X ℚ) where
  carrier := {z | ∀ x, dimension x ≠ i → z x = 0}
  zero_mem' x _ := rfl
  add_mem' ha hb x hx := by simp [ha x hx, hb x hx]
  smul_mem' c z hz x hx := by simp [hz x hx]

namespace cyclesOfDimension

variable {X : Scheme.{u}} {dimension : DimensionFunction X} {i : ℤ}

/-- The rational cycle consisting of one point with coefficient one. -/
noncomputable def point (x : X) (hx : dimension x = i) :
    cyclesOfDimension X dimension i := by
  classical
  refine ⟨Function.locallyFinsuppWithin.single x 1, ?_⟩
  intro y hy
  by_cases h : y = x
  · subst y
    exact (hy hx).elim
  · simp [h]

@[simp]
theorem point_apply_self (x : X) (hx : dimension x = i) :
    (point x hx : AlgebraicCycle X ℚ) x = 1 := by
  simp [point]

@[simp]
theorem point_apply_of_ne (x y : X) (hx : dimension x = i) (h : y ≠ x) :
    (point x hx : AlgebraicCycle X ℚ) y = 0 := by
  simp [point, h]

/-- Project an arbitrary rational algebraic cycle onto its dimension-`i` part.  Local finiteness
is inherited because the projected support is contained in the original support. -/
noncomputable def project (z : AlgebraicCycle X ℚ) : cyclesOfDimension X dimension i := by
  classical
  let c : AlgebraicCycle X ℚ :=
    { toFun := fun x ↦ if dimension x = i then z x else 0
      supportWithinDomain' := Set.subset_univ _
      supportLocallyFiniteWithinDomain' := by
        intro x _
        obtain ⟨t, ht, hfinite⟩ := z.supportLocallyFiniteWithinDomain x (by trivial)
        refine ⟨t, ht, hfinite.subset ?_⟩
        intro y hy
        refine ⟨hy.1, ?_⟩
        by_contra hz
        have hzy : z y = 0 := by simpa [Function.mem_support] using hz
        exact hy.2 (by simp [hzy]) }
  refine ⟨c, ?_⟩
  intro x hx
  simp [c, hx]

@[simp]
theorem project_apply (z : AlgebraicCycle X ℚ) (x : X) :
    (project (dimension := dimension) (i := i) z : AlgebraicCycle X ℚ) x =
      if dimension x = i then z x else 0 :=
  rfl

/-- Proper pushforward on dimension-`i` rational cycles.  The source and target weights are the
certified closure dimensions.  Mathlib's `mapCoeff` therefore makes a component vanish exactly
when its image has smaller dimension, and otherwise multiplies it by the actual residue-field
degree. -/
noncomputable def properPushforward
    {Y : Scheme.{u}} {dimensionY : DimensionFunction Y}
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsProper f] :
    cyclesOfDimension X dimension i →ₗ[ℚ]
      cyclesOfDimension Y dimensionY i where
  toFun c := ⟨_root_.AlgebraicGeometry.AlgebraicCycle.map f
      dimension dimensionY c.1, by
    intro y hy
    unfold _root_.AlgebraicGeometry.AlgebraicCycle.map
    change (∑ᶠ x ∈ f.base ⁻¹' {y},
      c.1 x * (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f
        dimension dimensionY x : ℚ)) = 0
    apply finsum_mem_of_eqOn_zero
    intro x hx
    by_cases hcx : c.1 x = 0
    · simp [hcx]
    have hdx : dimension x = i := by
      by_contra h
      exact hcx (c.2 x h)
    have hxy : f.base x = y := by simpa using hx
    have hdim : dimension x ≠ dimensionY (f.base x) := by
      rw [hdx, hxy]
      exact Ne.symm hy
    simp [_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff, hdim]⟩
  map_add' c d := by
    apply Subtype.ext
    exact AlgebraicCycle.map_add f dimension dimensionY c.1 d.1
  map_smul' q c := by
    apply Subtype.ext
    exact AlgebraicCycle.map_smul f dimension dimensionY q c.1

/-- Coefficient formula for proper pushforward of a dimension-graded cycle. -/
@[simp]
theorem properPushforward_apply
    {Y : Scheme.{u}} {dimensionY : DimensionFunction Y}
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsProper f]
    (c : cyclesOfDimension X dimension i) (y : Y) :
    ((properPushforward (dimension := dimension) (dimensionY := dimensionY)
      (i := i) f c : cyclesOfDimension Y dimensionY i) :
        AlgebraicCycle Y ℚ) y =
      ∑ᶠ x ∈ f.base ⁻¹' {y}, c.1 x *
        (_root_.AlgebraicGeometry.AlgebraicCycle.mapCoeff f
          dimension dimensionY x : ℚ) :=
  rfl

/-- Proper pushforward along the identity is the identity linear map. -/
@[simp]
theorem properPushforward_id :
    properPushforward (dimension := dimension) (dimensionY := dimension)
      (i := i) (𝟙 X) = LinearMap.id := by
  apply LinearMap.ext
  intro c
  apply Subtype.ext
  exact _root_.AlgebraicGeometry.AlgebraicCycle.map_id dimension c.1

/-- Dimension-graded proper pushforward composes for arbitrary proper scheme morphisms.  The
intermediate weight condition needed by the residue-degree sum is forced by the two proved
dimension inequalities: if the composite preserves dimension, neither factor can lower it. -/
@[simp]
theorem properPushforward_comp
    {Y Z : Scheme.{u}} {dimensionY : DimensionFunction Y}
    {dimensionZ : DimensionFunction Z}
    (f : X ⟶ Y) (g : Y ⟶ Z)
    [_root_.AlgebraicGeometry.IsProper f]
    [_root_.AlgebraicGeometry.IsProper g] :
    properPushforward (dimension := dimension) (dimensionY := dimensionZ)
      (i := i) (f ≫ g) =
    (properPushforward (dimension := dimensionY) (dimensionY := dimensionZ)
      (i := i) g).comp
      (properPushforward (dimension := dimension) (dimensionY := dimensionY)
        (i := i) f) := by
  apply LinearMap.ext
  intro c
  apply Subtype.ext
  change _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g)
      dimension dimensionZ c.1 =
    _root_.AlgebraicGeometry.AlgebraicCycle.map g dimensionY dimensionZ
      (_root_.AlgebraicGeometry.AlgebraicCycle.map f dimension dimensionY c.1)
  symm
  apply AlgebraicCycle.map_comp_of_between f g dimension dimensionY dimensionZ
  intro x hxz
  exact Int.le_antisymm
    (hxz.trans_le (dimensionY.apply_le_of_isProper dimensionZ g (f.base x)))
    (dimension.apply_le_of_isProper dimensionY f x)

/-- Proper pushforward composes for closed immersions.  Both dimension compatibilities are
theorems forced by the closed embeddings, and the underlying cycle identity is the explicit
closed-image calculation above. -/
@[simp]
theorem properPushforward_comp_closedImmersion
    {Y Z : Scheme.{u}} {dimensionY : DimensionFunction Y}
    {dimensionZ : DimensionFunction Z}
    (f : X ⟶ Y) (g : Y ⟶ Z)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    [_root_.AlgebraicGeometry.IsClosedImmersion g] :
    properPushforward (dimension := dimension) (dimensionY := dimensionZ)
      (i := i) (f ≫ g) =
    (properPushforward (dimension := dimensionY) (dimensionY := dimensionZ)
      (i := i) g).comp
      (properPushforward (dimension := dimension) (dimensionY := dimensionY)
        (i := i) f) := by
  apply LinearMap.ext
  intro c
  apply Subtype.ext
  change _root_.AlgebraicGeometry.AlgebraicCycle.map (f ≫ g)
      dimension dimensionZ c.1 =
    _root_.AlgebraicGeometry.AlgebraicCycle.map g dimensionY dimensionZ
      (_root_.AlgebraicGeometry.AlgebraicCycle.map f dimension dimensionY c.1)
  have hdx : dimension = fun x ↦ dimensionY (f.base x) := by
    funext x
    exact DimensionFunction.apply_eq_of_isClosedImmersion dimension dimensionY f x
  have hdy : dimensionY = fun y ↦ dimensionZ (g.base y) := by
    funext y
    exact DimensionFunction.apply_eq_of_isClosedImmersion dimensionY dimensionZ g y
  rw [hdx, hdy]
  exact (AlgebraicCycle.map_comp_of_isClosedImmersion f g
    (fun y ↦ dimensionZ (g.base y)) dimensionZ c.1).symm

/-- The fundamental cycle of a locally Noetherian scheme, placed in a fixed dimension whenever
all of its irreducible components have that dimension.  The underlying algebraic cycle is used
without projecting away any components. -/
noncomputable def fundamental [_root_.AlgebraicGeometry.IsLocallyNoetherian X]
    (pure : ∀ x : X, IsMax x → dimension x = i) :
    cyclesOfDimension X dimension i :=
  ⟨X.fundamentalCycle, by
    intro x hx
    by_cases hmax : IsMax x
    · exact (hx (pure x hmax)).elim
    · exact X.fundamentalCycle_apply_of_not_isMax x hmax⟩

@[simp]
theorem fundamental_apply_of_isMax [_root_.AlgebraicGeometry.IsLocallyNoetherian X]
    (pure : ∀ x : X, IsMax x → dimension x = i)
    (x : X) (hx : IsMax x) :
    (fundamental pure : AlgebraicCycle X ℚ) x = (X.genericLength x : ℚ) :=
  X.fundamentalCycle_apply_of_isMax x hx

@[simp]
theorem fundamental_apply_of_isMax_of_isReduced
    [_root_.AlgebraicGeometry.IsLocallyNoetherian X]
    [_root_.AlgebraicGeometry.IsReduced X]
    (pure : ∀ x : X, IsMax x → dimension x = i)
    (x : X) (hx : IsMax x) :
    (fundamental pure : AlgebraicCycle X ℚ) x = 1 := by
  change X.fundamentalCycle x = 1
  exact X.fundamentalCycle_apply_of_isMax_of_isReduced x hx

end cyclesOfDimension

/-- An integral locally Noetherian closed subscheme of `X`, represented invariantly by a closed
immersion.  Every condition is a standard Mathlib geometric proposition; there are no abstract
predicates or caller-selected cycle carriers. -/
structure IntegralClosedSubscheme (X : Scheme.{u}) where
  scheme : Scheme.{u}
  inclusion : scheme ⟶ X
  [isClosedImmersion : _root_.AlgebraicGeometry.IsClosedImmersion inclusion]
  [isIntegral : _root_.AlgebraicGeometry.IsIntegral scheme]
  [isLocallyNoetherian : _root_.AlgebraicGeometry.IsLocallyNoetherian scheme]

attribute [instance] IntegralClosedSubscheme.isClosedImmersion
  IntegralClosedSubscheme.isIntegral IntegralClosedSubscheme.isLocallyNoetherian

namespace IntegralClosedSubscheme

variable {X : Scheme.{u}} (Z : IntegralClosedSubscheme X)

/-- Regard an integral closed subscheme of `X` as one of `Y` by composing with a closed
immersion `X → Y`.  The source scheme, its integral structure, and its local Noetherian
structure are unchanged. -/
def closedImage {Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f] :
    IntegralClosedSubscheme Y where
  scheme := Z.scheme
  inclusion := Z.inclusion ≫ f

/-- Push a cycle on an integral closed subscheme into the ambient scheme.  The weight on the
source is the pullback of the ambient dimension, so Mathlib's residue-degree formula cannot move
a coefficient into a different graded component. -/
noncomputable def pushforward (dimension : DimensionFunction X)
    (c : AlgebraicCycle Z.scheme ℚ) : AlgebraicCycle X ℚ :=
  _root_.AlgebraicGeometry.AlgebraicCycle.map Z.inclusion
    (fun z ↦ dimension (Z.inclusion.base z)) dimension c

/-- Pushing from an integral closed subscheme and then through a closed immersion agrees with
pushing through the composite closed immersion.  Dimension compatibility is derived from the
closed embedding instead of being supplied as a hypothesis. -/
lemma pushforward_comp_closedImmersion
    {Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (dimensionX : DimensionFunction X) (dimensionY : DimensionFunction Y)
    (c : AlgebraicCycle Z.scheme ℚ) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f dimensionX dimensionY
        (Z.pushforward dimensionX c) =
      (Z.closedImage f).pushforward dimensionY c := by
  unfold IntegralClosedSubscheme.pushforward
  have hdim : dimensionX = fun x ↦ dimensionY (f.base x) := by
    funext x
    exact DimensionFunction.apply_eq_of_isClosedImmersion dimensionX dimensionY f x
  rw [hdim]
  exact AlgebraicCycle.map_comp_of_isClosedImmersion
    Z.inclusion f (fun x ↦ dimensionY (f.base x)) dimensionY c

end IntegralClosedSubscheme

/-- A genuine principal-divisor generator: an integral locally Noetherian closed subscheme and
a unit of its function field.  It contains no dimension label or caller-supplied homogeneity
theorem. -/
structure RationalFunctionGenerator (X : Scheme.{u}) where
  subspace : IntegralClosedSubscheme X
  function : subspace.scheme.functionFieldˣ

namespace RationalFunctionGenerator

variable {X : Scheme.{u}}

/-- A rational-function generator remains the same integral scheme and function after its
closed inclusion is composed with a closed immersion of ambient schemes. -/
def closedImage {Y : Scheme.{u}} (g : RationalFunctionGenerator X)
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsClosedImmersion f] :
    RationalFunctionGenerator Y where
  subspace := g.subspace.closedImage f
  function := g.function

/-- The unmodified principal divisor pushed from its integral closed subscheme to the ambient
scheme. -/
noncomputable def divisor (dimension : DimensionFunction X)
    (g : RationalFunctionGenerator X) : AlgebraicCycle X ℚ :=
  g.subspace.pushforward dimension <|
    g.subspace.scheme.principalCycle
      (g.function : g.subspace.scheme.functionField)

/-- Closed-immersion pushforward sends an actual principal divisor generator to the principal
divisor of the same function on the composite integral closed subscheme. -/
lemma map_divisor_closedImmersion
    {Y : Scheme.{u}} (g : RationalFunctionGenerator X) (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (dimensionX : DimensionFunction X) (dimensionY : DimensionFunction Y) :
    _root_.AlgebraicGeometry.AlgebraicCycle.map f dimensionX dimensionY
        (g.divisor dimensionX) =
      (g.closedImage f).divisor dimensionY := by
  unfold divisor
  exact g.subspace.pushforward_comp_closedImmersion f dimensionX dimensionY _

end RationalFunctionGenerator

/-- The canonical ungraded rational-equivalence subspace, generated by every actual principal
divisor on every integral closed subscheme.  Dimension grading is imposed afterwards by
intersection, so no generator can be omitted for lack of a separately supplied catenarity
proof. -/
def totalRationalRelations (X : Scheme.{u}) (dimension : DimensionFunction X) :
    Submodule ℚ (AlgebraicCycle X ℚ) :=
  Submodule.span ℚ
    (Set.range (fun g : RationalFunctionGenerator X ↦ g.divisor dimension))

/-- Closed-immersion pushforward carries the canonical span of principal divisors into the
canonical span on the target.  This follows generator-by-generator from the composite closed
subscheme and the same rational function. -/
lemma totalRationalRelations_map_closedImmersion
    {X Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (dimensionX : DimensionFunction X) (dimensionY : DimensionFunction Y) :
    Submodule.map (AlgebraicCycle.mapLinear f dimensionX dimensionY)
        (totalRationalRelations X dimensionX) ≤
      totalRationalRelations Y dimensionY := by
  rw [totalRationalRelations, totalRationalRelations,
    Submodule.map_span]
  apply Submodule.span_mono
  rintro z ⟨c, ⟨g, rfl⟩, rfl⟩
  change _root_.AlgebraicGeometry.AlgebraicCycle.map f dimensionX dimensionY
      (g.divisor dimensionX) ∈
    Set.range (fun h : RationalFunctionGenerator Y ↦ h.divisor dimensionY)
  rw [g.map_divisor_closedImmersion f dimensionX dimensionY]
  exact Set.mem_range_self (g.closedImage f)

/-- Comap form of preservation of total rational equivalence under a closed immersion. -/
lemma totalRationalRelations_le_comap_closedImmersion
    {X Y : Scheme.{u}} (f : X ⟶ Y)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (dimensionX : DimensionFunction X) (dimensionY : DimensionFunction Y) :
    totalRationalRelations X dimensionX ≤
      Submodule.comap (AlgebraicCycle.mapLinear f dimensionX dimensionY)
        (totalRationalRelations Y dimensionY) := by
  rw [← Submodule.map_le_iff_le_comap]
  exact totalRationalRelations_map_closedImmersion f dimensionX dimensionY

/-- There is exactly one rational-equivalence system: the canonical geometric one.  The inductive
wrapper retains the ambient parameters for downstream notation while preventing callers from
choosing a carrier or fabricating a divisor. -/
inductive RationalEquivalenceSystem (X : Scheme.{u})
    (dimension : DimensionFunction X) (i : ℤ) : Type (u + 1)
  | canonical

instance {X : Scheme.{u}} {dimension : DimensionFunction X} {i : ℤ} :
    Subsingleton (RationalEquivalenceSystem X dimension i) :=
  ⟨fun a b ↦ by cases a; cases b; rfl⟩

namespace RationalEquivalenceSystem

variable {X : Scheme.{u}} {dimension : DimensionFunction X} {i : ℤ}
  (R : RationalEquivalenceSystem X dimension i)

/-- The generator type is fixed by the geometry, independently of the unique wrapper value. -/
abbrev Generator : Type (u + 1) :=
  match R with
  | .canonical => RationalFunctionGenerator X

/-- The full pushed-forward principal divisor attached to a canonical generator. -/
noncomputable def divisor (g : R.Generator) : AlgebraicCycle X ℚ :=
  match R with
  | .canonical => g.divisor dimension

/-- The degree-`i` rational-equivalence subspace is the intersection of dimension-`i` cycles
with the canonical ungraded span of all principal divisors. -/
def relations : Submodule ℚ (cyclesOfDimension X dimension i) :=
  match R with
  | .canonical =>
      Submodule.comap (cyclesOfDimension X dimension i).subtype
        (totalRationalRelations X dimension)

/-- The dimension-`i` Chow group with rational cycle coefficients. -/
abbrev ChowGroup :=
  (cyclesOfDimension X dimension i) ⧸ R.relations

/-- Send a dimension-graded cycle to its rational-equivalence class. -/
abbrev quotientMap : cyclesOfDimension X dimension i →ₗ[ℚ] R.ChowGroup :=
  R.relations.mkQ

@[simp]
theorem quotientMap_divisor (g : R.Generator)
    (hg : R.divisor g ∈ cyclesOfDimension X dimension i) :
    R.quotientMap ⟨R.divisor g, hg⟩ = 0 := by
  change (Submodule.Quotient.mk
    (⟨R.divisor g, hg⟩ : cyclesOfDimension X dimension i) : R.ChowGroup) = 0
  rw [Submodule.Quotient.mk_eq_zero]
  cases R
  exact Submodule.subset_span (Set.mem_range_self g)

/-- Data for an operation on cycles which descends through rational equivalence. -/
structure DescendingMap
    {Y : Scheme.{u}} {dimensionY : DimensionFunction Y} {j : ℤ}
    (S : RationalEquivalenceSystem Y dimensionY j) where
  onCycles : cyclesOfDimension X dimension i →ₗ[ℚ] cyclesOfDimension Y dimensionY j
  maps_relations : R.relations ≤ Submodule.comap onCycles S.relations

namespace DescendingMap

variable {Y : Scheme.{u}} {dimensionY : DimensionFunction Y} {j : ℤ}
  {S : RationalEquivalenceSystem Y dimensionY j}

/-- The identity operation on cycles preserves rational equivalence. -/
def id : R.DescendingMap R where
  onCycles := LinearMap.id
  maps_relations := by
    intro z hz
    exact hz

/-- Composition of operations which preserve rational equivalence. -/
def comp
    {Z : Scheme.{u}} {dimensionZ : DimensionFunction Z} {k : ℤ}
    {T : RationalEquivalenceSystem Z dimensionZ k}
    (g : S.DescendingMap T) (f : R.DescendingMap S) : R.DescendingMap T where
  onCycles := g.onCycles.comp f.onCycles
  maps_relations := by
    intro z hz
    exact g.maps_relations (f.maps_relations hz)

/-- The induced homomorphism on Chow groups. -/
def inducedMap (f : R.DescendingMap S) : R.ChowGroup →ₗ[ℚ] S.ChowGroup :=
  Submodule.mapQ R.relations S.relations f.onCycles f.maps_relations

@[simp]
theorem map_quotientMap (f : R.DescendingMap S) (z : cyclesOfDimension X dimension i) :
    inducedMap R f (R.quotientMap z) = S.quotientMap (f.onCycles z) :=
  rfl

@[simp]
theorem inducedMap_id : inducedMap R (id R) = LinearMap.id := by
  apply LinearMap.ext
  rintro ⟨z⟩
  rfl

@[simp]
theorem inducedMap_comp
    {Z : Scheme.{u}} {dimensionZ : DimensionFunction Z} {k : ℤ}
    {T : RationalEquivalenceSystem Z dimensionZ k}
    (g : S.DescendingMap T) (f : R.DescendingMap S) :
    inducedMap R (comp R g f) = (inducedMap S g).comp (inducedMap R f) := by
  apply LinearMap.ext
  rintro ⟨z⟩
  rfl

/-- The dimension-graded cycle pushforward of a closed immersion, together with its proved
preservation of the canonical rational-equivalence subspaces. -/
noncomputable def ofClosedImmersion
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (S : RationalEquivalenceSystem Y dimensionY i) : R.DescendingMap S where
  onCycles := cyclesOfDimension.properPushforward f
  maps_relations := by
    cases R
    cases S
    intro z hz
    change (_root_.AlgebraicGeometry.AlgebraicCycle.map f
      dimension dimensionY z.1) ∈ totalRationalRelations Y dimensionY
    exact totalRationalRelations_le_comap_closedImmersion
      f dimension dimensionY hz

/-- Closed-immersion pushforward on dimension-graded rational Chow groups. -/
noncomputable def closedImmersionPushforward
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (S : RationalEquivalenceSystem Y dimensionY i) :
    R.ChowGroup →ₗ[ℚ] S.ChowGroup :=
  inducedMap R (ofClosedImmersion R f S)

/-- Closed-immersion Chow pushforward is induced by the actual residue-degree pushforward on
dimension-graded cycles. -/
@[simp]
theorem closedImmersionPushforward_quotientMap
    (f : X ⟶ Y) [_root_.AlgebraicGeometry.IsClosedImmersion f]
    (S : RationalEquivalenceSystem Y dimensionY i)
    (z : cyclesOfDimension X dimension i) :
    closedImmersionPushforward R f S (R.quotientMap z) =
      S.quotientMap (cyclesOfDimension.properPushforward f z) :=
  rfl

/-- Closed-immersion Chow pushforward along the identity is the identity. -/
@[simp]
theorem closedImmersionPushforward_id :
    closedImmersionPushforward R (𝟙 X) R = LinearMap.id := by
  apply LinearMap.ext
  rintro ⟨z⟩
  change R.quotientMap (cyclesOfDimension.properPushforward (𝟙 X) z) =
    R.quotientMap z
  rw [cyclesOfDimension.properPushforward_id]
  rfl

/-- Closed-immersion pushforward is functorial on rational Chow groups. -/
@[simp]
theorem closedImmersionPushforward_comp
    {Z : Scheme.{u}} {dimensionZ : DimensionFunction Z}
    {T : RationalEquivalenceSystem Z dimensionZ i}
    (S' : RationalEquivalenceSystem Y dimensionY i)
    (f : X ⟶ Y) (g : Y ⟶ Z)
    [_root_.AlgebraicGeometry.IsClosedImmersion f]
    [_root_.AlgebraicGeometry.IsClosedImmersion g] :
    closedImmersionPushforward R (f ≫ g) T =
      (closedImmersionPushforward S' g T).comp
        (closedImmersionPushforward R f S') := by
  apply LinearMap.ext
  rintro ⟨z⟩
  change T.quotientMap
      (cyclesOfDimension.properPushforward (f ≫ g) z) =
    T.quotientMap
      (cyclesOfDimension.properPushforward g
        (cyclesOfDimension.properPushforward f z))
  rw [cyclesOfDimension.properPushforward_comp_closedImmersion]
  rfl

end DescendingMap

end RationalEquivalenceSystem

namespace PointChow

variable (k : Type u) [Field k]

private noncomputable abbrev X : Scheme.{u} := _root_.AlgebraicGeometry.Spec (.of k)

/-- The canonical rational-equivalence system on `Spec(k)`. -/
def rationalEquivalence (i : ℤ) :
    RationalEquivalenceSystem (X k) (DimensionFunction.specField k) i :=
  .canonical

/-- Actual integral closed-subscheme/rational-function generators on the point. -/
abbrev RelationGenerator (i : ℤ) := (rationalEquivalence k i).Generator

/-- Every principal divisor on an integral closed subscheme of a point vanishes.  Closedness
makes the source inject into the one-point spectrum, hence every source point is maximal and
has coheight zero; Mathlib's order of vanishing is therefore zero. -/
theorem divisor_eq_zero (g : RationalFunctionGenerator (X k)) :
    g.divisor (DimensionFunction.specField k) = 0 := by
  let _ : Subsingleton g.subspace.scheme :=
    ⟨fun x y ↦ g.subspace.inclusion.isClosedEmbedding.injective
      (Subsingleton.elim _ _)⟩
  have hprincipal : g.subspace.scheme.principalCycle
      (g.function : g.subspace.scheme.functionField) = 0 := by
    apply Function.locallyFinsuppWithin.coe_injective
    funext z
    change g.subspace.scheme.principalCycle
      (g.function : g.subspace.scheme.functionField) z = (0 : ℚ)
    rw [_root_.AlgebraicGeometry.Scheme.principalCycle_apply]
    have hzmax : IsMax z := by
      intro y _
      exact (Subsingleton.elim y z).le
    have hcoheight : coheight z ≠ 1 := by
      rw [hzmax.coheight_eq_zero]
      norm_num
    rw [g.subspace.scheme.ord_eq_zero_of_coheight_neq_one hcoheight]
    rfl
  unfold RationalFunctionGenerator.divisor
  rw [hprincipal]
  unfold IntegralClosedSubscheme.pushforward
  apply Function.locallyFinsuppWithin.coe_injective
  funext y
  unfold _root_.AlgebraicGeometry.AlgebraicCycle.map
  change (∑ᶠ x ∈ (⇑g.subspace.inclusion) ⁻¹' {y}, (0 : ℚ) * _) = 0
  simp

/-- Rational equivalence on a point has zero relation subspace. -/
theorem relations_eq_bot (i : ℤ) : (rationalEquivalence k i).relations = ⊥ := by
  have htotal : totalRationalRelations (X k) (DimensionFunction.specField k) = ⊥ := by
    rw [totalRationalRelations]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro z ⟨g, rfl⟩
      change g.divisor (DimensionFunction.specField k) ∈
        (⊥ : Submodule ℚ (AlgebraicCycle (X k) ℚ))
      rw [divisor_eq_zero]
      exact Submodule.zero_mem _
    · exact bot_le
  rw [RationalEquivalenceSystem.relations]
  change Submodule.comap
    (cyclesOfDimension (X k) (DimensionFunction.specField k) i).subtype
      (totalRationalRelations (X k) (DimensionFunction.specField k)) = ⊥
  rw [htotal]
  exact LinearMap.ker_eq_bot.mpr fun x y h ↦ Subtype.ext h

/-- The cycle with coefficient one at the unique point of `Spec(k)`. -/
noncomputable def fundamentalCycle :
    cyclesOfDimension (X k) (DimensionFunction.specField k) 0 :=
  cyclesOfDimension.fundamental (fun x _ ↦ DimensionFunction.specField_apply k x)

@[simp]
theorem fundamentalCycle_apply :
    (fundamentalCycle k : AlgebraicCycle (X k) ℚ) default = 1 :=
  cyclesOfDimension.fundamental_apply_of_isMax_of_isReduced _ default (by
    intro x _
    exact (Subsingleton.elim x default).le)

/-- Evaluation at the unique point identifies zero-dimensional cycles on `Spec(k)` with `ℚ`. -/
noncomputable def cyclesEquivRat :
    cyclesOfDimension (X k) (DimensionFunction.specField k) 0 ≃ₗ[ℚ] ℚ where
  toFun z := z.1 default
  invFun q := q • fundamentalCycle k
  map_add' z w := by simp
  map_smul' q z := by simp
  left_inv z := by
    apply Subtype.ext
    apply Function.locallyFinsuppWithin.coe_injective
    funext x
    have hx : x = default := Subsingleton.elim _ _
    subst x
    change z.1 default * (fundamentalCycle k).1 default = z.1 default
    rw [fundamentalCycle_apply]
    simp
  right_inv q := by
    change q * (fundamentalCycle k).1 default = q
    rw [fundamentalCycle_apply]
    simp

/-- The actual degree-zero rational Chow group of a point is canonically `ℚ`. -/
noncomputable def chowEquivRat :
    (rationalEquivalence k 0).ChowGroup ≃ₗ[ℚ] ℚ :=
  ((rationalEquivalence k 0).relations.quotEquivOfEqBot (relations_eq_bot k 0)).trans
    (cyclesEquivRat k)

/-- The fundamental cycle of the point has degree one under the canonical identification. -/
@[simp]
theorem fundamentalClass_degree_one :
    chowEquivRat k
      ((rationalEquivalence k 0).quotientMap
        (fundamentalCycle k)) = 1 := by
  change (cyclesEquivRat k)
      ((rationalEquivalence k 0).relations.quotEquivOfEqBot (relations_eq_bot k 0)
      ((rationalEquivalence k 0).quotientMap
        (fundamentalCycle k))) = 1
  change (cyclesEquivRat k) (fundamentalCycle k) = 1
  exact fundamentalCycle_apply k

end PointChow

end GromovWitten.AlgebraicGeometry.IntersectionTheory
